import Link from 'next/link';
import { User, BookOpen } from 'lucide-react';
import {
  EDITORIAL_EXPERTS,
  getPrimaryEditorForContent,
  type EditorialExpert,
} from '@/lib/trust/editorial-team';

type Props = {
  contentType?: 'county' | 'route' | 'city-hub' | 'directory';
  className?: string;
  compact?: boolean;
};

export function EditorialTeamPanel({
  contentType = 'directory',
  className = '',
  compact = false,
}: Props) {
  const lead = getPrimaryEditorForContent(contentType);
  const others = EDITORIAL_EXPERTS.filter((e) => e.id !== lead.id);

  return (
    <section
      className={`rounded-2xl border bg-card p-6 ${className}`}
      aria-labelledby="editorial-team-heading"
    >
      <div className="flex items-start gap-3 mb-4">
        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10">
          <BookOpen className="h-5 w-5 text-primary" aria-hidden="true" />
        </div>
        <div>
          <h2 id="editorial-team-heading" className="text-lg font-semibold tracking-tight">
            Researched by our editorial team
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed mt-1">
            Move Trust Hub content is written and reviewed by moving-industry researchers — not
            generated by movers or brokers. We screen USDOT/MC numbers against placeholder
            patterns, confirm verified listings on FMCSA.gov, and only surface attributable reviews.
          </p>
        </div>
      </div>

      <ExpertCard expert={lead} primary />

      {!compact && others.length > 0 && (
        <div className="mt-4 grid sm:grid-cols-2 gap-3">
          {others.map((expert) => (
            <ExpertCard key={expert.id} expert={expert} />
          ))}
        </div>
      )}

      <p className="text-xs text-muted-foreground mt-4">
        <Link href="/about" className="text-primary font-medium hover:underline">
          About our editorial standards
        </Link>
        {' · '}
        <Link href="/resources/how-to-choose#reputation-score" className="text-primary hover:underline">
          How we score movers
        </Link>
        {' · '}
        <Link href="/verify-dot" className="text-primary hover:underline">
          Verify USDOT yourself
        </Link>
      </p>
    </section>
  );
}

function ExpertCard({ expert, primary = false }: { expert: EditorialExpert; primary?: boolean }) {
  return (
    <div
      className={`rounded-xl border p-4 ${primary ? 'bg-muted/20' : 'bg-background'}`}
    >
      <div className="flex items-center gap-2 mb-2">
        <User className="h-4 w-4 text-primary" aria-hidden="true" />
        <div>
          <div className="font-medium text-sm">{expert.name}</div>
          <div className="text-xs text-muted-foreground">{expert.role}</div>
        </div>
      </div>
      <p className="text-xs text-muted-foreground leading-relaxed">{expert.bio}</p>
      <div className="flex flex-wrap gap-1.5 mt-2">
        {expert.expertise.map((tag) => (
          <span
            key={tag}
            className="rounded-full border bg-background px-2 py-0.5 text-[10px] font-medium text-muted-foreground"
          >
            {tag}
          </span>
        ))}
      </div>
    </div>
  );
}