import type { Market } from '@/lib/destinations/types';

export const markets: Market[] = [
  {
    slug: 'myrtle-beach-sc',
    displayName: 'Myrtle Beach',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc', 'brunswick-nc', 'new-hanover-nc'],
    lat: 33.6887,
    lng: -78.8877,
    defaultToZip: '29577',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,200–$5,800',
      twoBR: '$5,900–$8,900',
      threeBR: '$8,200–$12,500',
      fourBR: '$11,800–$17,200',
    },
    inboundGrowthStat: '3.88:1 inbound ratio (moveBuddha/PODS 2026)',
    peakSeasonNote: 'May–September; book 8–12 weeks ahead',
    priority: 1,
    mapDescription:
      'Interactive map of Myrtle Beach, SC and surrounding counties (Horry, SC; Brunswick, NC; New Hanover, NC). Priority inbound destination on the Grand Strand. Use county links below to browse vetted local movers.',
  },
  {
    slug: 'florida',
    displayName: 'Florida',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: [],
    lat: 28.0,
    lng: -82.0,
    defaultToZip: '32202',
    topInboundOrigins: ['New York', 'New Jersey', 'Illinois', 'California'],
    avgCostRanges: {
      studio: '$2,800–$5,500',
      twoBR: '$5,200–$8,400',
      threeBR: '$7,500–$11,800',
      fourBR: '$10,500–$16,000',
    },
    inboundGrowthStat: 'Highest-volume Sunbelt inbound corridor in 2026',
    peakSeasonNote: 'Year-round demand; hurricane season June–November requires contingency planning',
    isClusterParent: true,
    priority: 2,
    mapDescription:
      'Florida inbound migration hub covering Jacksonville, Sarasota, Naples, the Palm Beach County corridor (Boca Raton, Delray Beach, Boynton Beach, Deerfield Beach), and central Florida growth markets.',
  },
  {
    slug: 'jacksonville',
    displayName: 'Jacksonville',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['duval-fl', 'st-johns-fl', 'clay-fl'],
    lat: 30.3322,
    lng: -81.6557,
    defaultToZip: '32202',
    topInboundOrigins: ['New York', 'New Jersey', 'Georgia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,600–$5,200',
      twoBR: '$4,800–$7,900',
      threeBR: '$7,000–$11,200',
      fourBR: '$9,800–$14,500',
    },
    inboundGrowthStat: 'Top-5 Florida metro for net inbound moves (2026)',
    peakSeasonNote: 'Spring and fall offer best carrier availability',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Jacksonville, FL and Duval County service area with links to St. Johns and Clay counties for northeast Florida relocations.',
  },
  {
    slug: 'sarasota',
    displayName: 'Sarasota',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['sarasota-fl', 'manatee-fl'],
    lat: 27.3364,
    lng: -82.5307,
    defaultToZip: '34236',
    topInboundOrigins: ['New York', 'New Jersey', 'Illinois', 'Michigan'],
    avgCostRanges: {
      studio: '$2,900–$5,600',
      twoBR: '$5,400–$8,600',
      threeBR: '$7,800–$12,000',
      fourBR: '$11,000–$16,500',
    },
    inboundGrowthStat: 'Gulf Coast retiree and remote-worker hotspot',
    peakSeasonNote: 'Snowbird season October–April tightens southbound schedules',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Sarasota and Manatee counties on Florida\'s Gulf Coast, including condo and waterfront access considerations.',
  },
  {
    slug: 'naples',
    displayName: 'Naples',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['collier-fl', 'lee-fl'],
    lat: 26.142,
    lng: -81.7948,
    defaultToZip: '34102',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'Illinois'],
    avgCostRanges: {
      studio: '$3,100–$6,000',
      twoBR: '$5,800–$9,200',
      threeBR: '$8,500–$13,200',
      fourBR: '$12,000–$18,500',
    },
    inboundGrowthStat: 'Premium coastal market with high specialty-item demand',
    peakSeasonNote: 'Gated communities may require shuttle trucks — confirm access early',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Naples and Collier County on southwest Florida\'s coast, with Lee County spillover for Fort Myers area moves.',
  },
  {
    slug: 'ocala',
    displayName: 'Ocala',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['marion-fl', 'sumter-fl'],
    lat: 29.1872,
    lng: -82.1401,
    defaultToZip: '34471',
    topInboundOrigins: ['New York', 'New Jersey', 'Georgia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,500–$4,900',
      twoBR: '$4,600–$7,400',
      threeBR: '$6,800–$10,500',
      fourBR: '$9,500–$14,000',
    },
    inboundGrowthStat: 'Central Florida horse country and affordable suburban growth',
    peakSeasonNote: 'Summer heat affects loading schedules — book morning slots',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Ocala and Marion County in central Florida, with Sumter County links for The Villages corridor demand.',
  },
  {
    slug: 'st-augustine',
    displayName: 'St. Augustine',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['st-johns-fl', 'flagler-fl'],
    lat: 29.8947,
    lng: -81.3145,
    defaultToZip: '32084',
    topInboundOrigins: ['New York', 'New Jersey', 'Georgia', 'Pennsylvania'],
    avgCostRanges: {
      studio: '$2,700–$5,300',
      twoBR: '$5,000–$8,100',
      threeBR: '$7,200–$11,400',
      fourBR: '$10,200–$15,200',
    },
    inboundGrowthStat: 'Historic coastal city with strong Northeast inbound flow',
    peakSeasonNote: 'Tourism season can affect downtown access — plan delivery windows',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'St. Augustine in St. Johns County with Flagler County links for northeast Florida coastal relocations.',
  },
  {
    slug: 'wildwood',
    displayName: 'Wildwood',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['sumter-fl', 'lake-fl', 'marion-fl'],
    lat: 28.9653,
    lng: -82.0384,
    defaultToZip: '34785',
    topInboundOrigins: ['New York', 'New Jersey', 'Michigan', 'Ohio'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,500–$7,200',
      threeBR: '$6,500–$10,200',
      fourBR: '$9,200–$13,800',
    },
    inboundGrowthStat: 'Central Florida growth corridor driven by 55+ and suburban expansion',
    peakSeasonNote: 'Active adult communities may have move-day restrictions',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Wildwood and Sumter County in central Florida, including The Villages and Lake County spillover.',
  },
  {
    slug: 'boca-raton',
    displayName: 'Boca Raton',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['palm-beach-fl'],
    lat: 26.3683,
    lng: -80.1289,
    defaultToZip: '33432',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'Illinois'],
    avgCostRanges: {
      studio: '$3,400–$6,400',
      twoBR: '$6,000–$9,800',
      threeBR: '$8,800–$13,800',
      fourBR: '$12,800–$19,200',
    },
    inboundGrowthStat: 'Affluent Palm Beach corridor with luxury high-rise and gated-community demand',
    peakSeasonNote: 'Snowbird season October–April tightens southbound schedules; luxury buildings require COI and elevator reservations',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Boca Raton in Palm Beach County — luxury coastal relocations with Mizner Park, gated communities, and strict high-rise move protocols.',
  },
  {
    slug: 'deerfield-beach',
    displayName: 'Deerfield Beach',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['palm-beach-fl', 'broward-fl'],
    lat: 26.3184,
    lng: -80.0998,
    defaultToZip: '33441',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,200–$6,100',
      twoBR: '$5,800–$9,300',
      threeBR: '$8,400–$13,000',
      fourBR: '$12,000–$18,200',
    },
    inboundGrowthStat: 'Family-friendly coastal city on the Palm Beach–Broward border with boating access',
    peakSeasonNote: 'Hillsboro Inlet and waterfront homes may need specialty handling; book before winter snowbird peak',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Deerfield Beach spanning Palm Beach and Broward counties — family neighborhoods, Quiet Waters Park, and Intracoastal boating communities.',
  },
  {
    slug: 'boynton-beach',
    displayName: 'Boynton Beach',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['palm-beach-fl'],
    lat: 26.5284,
    lng: -80.0664,
    defaultToZip: '33435',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'Michigan'],
    avgCostRanges: {
      studio: '$3,100–$6,000',
      twoBR: '$5,700–$9,100',
      threeBR: '$8,300–$12,800',
      fourBR: '$11,800–$17,800',
    },
    inboundGrowthStat: 'Growing Palm Beach County value market between Boca Raton and West Palm Beach',
    peakSeasonNote: 'Oceanfront condos and 55+ communities often restrict move windows — confirm HOA rules early',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Boynton Beach in Palm Beach County — Oceanfront Park corridor, family suburbs, and affordable coastal alternatives to Boca Raton.',
  },
  {
    slug: 'delray-beach',
    displayName: 'Delray Beach',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['palm-beach-fl'],
    lat: 26.4615,
    lng: -80.0728,
    defaultToZip: '33444',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'California'],
    avgCostRanges: {
      studio: '$3,300–$6,300',
      twoBR: '$5,900–$9,500',
      threeBR: '$8,600–$13,400',
      fourBR: '$12,400–$18,800',
    },
    inboundGrowthStat: 'Atlantic Avenue arts district and walkable downtown driving Northeast inbound flow',
    peakSeasonNote: 'Historic downtown and beach condos require tight delivery windows during festival season',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Delray Beach in Palm Beach County — Pineapple Grove, Atlantic Avenue dining district, and beach-access residential moves.',
  },
  {
    slug: 'knoxville-tn',
    displayName: 'Knoxville',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['knox-tn', 'anderson-tn'],
    lat: 35.9606,
    lng: -83.9207,
    defaultToZip: '37902',
    topInboundOrigins: ['Chicago', 'Detroit', 'Atlanta', 'New York'],
    avgCostRanges: {
      studio: '$3,100–$5,700',
      twoBR: '$5,500–$8,500',
      threeBR: '$7,800–$11,900',
      fourBR: '$11,000–$16,200',
    },
    inboundGrowthStat: 'Top-10 inbound ratio among mid-size metros (2026)',
    peakSeasonNote: 'Spring and fall ideal; summer UT/ORNL turnover spikes demand',
    priority: 3,
    mapDescription:
      'Knoxville, TN in Knox County with Anderson County links for Oak Ridge and eastern Tennessee relocations.',
  },
  {
    slug: 'texas',
    displayName: 'Texas',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: [],
    lat: 31.0,
    lng: -99.0,
    defaultToZip: '75201',
    topInboundOrigins: ['California', 'Illinois', 'New York', 'Florida'],
    avgCostRanges: {
      studio: '$2,900–$5,800',
      twoBR: '$5,400–$8,800',
      threeBR: '$7,900–$12,400',
      fourBR: '$11,200–$17,500',
    },
    inboundGrowthStat: 'Leading job-growth state for interstate household moves',
    peakSeasonNote: 'Summer corporate relocations peak May–August',
    isClusterParent: true,
    priority: 4,
    mapDescription:
      'Texas inbound hub covering Dallas–Fort Worth, Austin, Houston, and Leander suburb growth corridors.',
  },
  {
    slug: 'dallas-fort-worth',
    displayName: 'Dallas–Fort Worth',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['dallas-tx', 'tarrant-tx', 'collin-tx', 'denton-tx'],
    lat: 32.7767,
    lng: -96.797,
    defaultToZip: '75201',
    topInboundOrigins: ['California', 'Illinois', 'New York', 'Florida'],
    avgCostRanges: {
      studio: '$2,800–$5,600',
      twoBR: '$5,200–$8,400',
      threeBR: '$7,600–$11,800',
      fourBR: '$10,800–$16,200',
    },
    inboundGrowthStat: 'DFW metro leads Texas net inbound volume',
    peakSeasonNote: 'Suburban new-build communities may have narrow street access',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Dallas–Fort Worth metro spanning Dallas, Tarrant, Collin, and Denton counties in north Texas.',
  },
  {
    slug: 'austin',
    displayName: 'Austin',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['travis-tx', 'williamson-tx', 'hays-tx'],
    lat: 30.2672,
    lng: -97.7431,
    defaultToZip: '78701',
    topInboundOrigins: ['California', 'New York', 'Illinois', 'Washington'],
    avgCostRanges: {
      studio: '$3,000–$6,000',
      twoBR: '$5,600–$9,000',
      threeBR: '$8,200–$12,600',
      fourBR: '$11,500–$17,800',
    },
    inboundGrowthStat: 'Tech corridor relocation hub with sustained CA inbound flow',
    peakSeasonNote: 'Downtown high-rises and hill-country homes both need access surveys',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Austin and Travis County with Williamson and Hays counties for greater Austin metro moves.',
  },
  {
    slug: 'houston',
    displayName: 'Houston',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['harris-tx', 'fort-bend-tx', 'montgomery-tx'],
    lat: 29.7604,
    lng: -95.3698,
    defaultToZip: '77002',
    topInboundOrigins: ['California', 'Louisiana', 'Illinois', 'New York'],
    avgCostRanges: {
      studio: '$2,700–$5,500',
      twoBR: '$5,000–$8,200',
      threeBR: '$7,400–$11,600',
      fourBR: '$10,500–$16,000',
    },
    inboundGrowthStat: 'Fourth-largest U.S. metro by population; strong energy-sector transfers',
    peakSeasonNote: 'Hurricane season requires flexible delivery date clauses',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Houston and Harris County with Fort Bend and Montgomery counties for greater Houston relocations.',
  },
  {
    slug: 'leander',
    displayName: 'Leander',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['williamson-tx', 'travis-tx'],
    lat: 30.5788,
    lng: -97.8531,
    defaultToZip: '78641',
    topInboundOrigins: ['California', 'Washington', 'Illinois', 'Colorado'],
    avgCostRanges: {
      studio: '$2,900–$5,700',
      twoBR: '$5,400–$8,600',
      threeBR: '$7,900–$12,200',
      fourBR: '$11,200–$17,000',
    },
    inboundGrowthStat: 'Fastest-growing Austin suburb corridor (Williamson County)',
    peakSeasonNote: 'New construction neighborhoods — confirm truck clearance with HOA',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Leander in Williamson County, north of Austin, with Travis County links for metro-wide moves.',
  },
  {
    slug: 'carolinas',
    displayName: 'The Carolinas',
    stateCode: 'NC',
    stateName: 'North & South Carolina',
    primaryCounties: [],
    lat: 35.0,
    lng: -80.5,
    defaultToZip: '28202',
    topInboundOrigins: ['New York', 'New Jersey', 'California', 'Florida'],
    avgCostRanges: {
      studio: '$2,800–$5,400',
      twoBR: '$5,200–$8,300',
      threeBR: '$7,600–$11,700',
      fourBR: '$10,800–$16,400',
    },
    inboundGrowthStat: 'Carolinas rank among top 5 regional inbound destinations (2026)',
    peakSeasonNote: 'Banking and tech hiring cycles drive spring/fall relocation peaks',
    isClusterParent: true,
    priority: 5,
    mapDescription:
      'Carolinas inbound hub covering Charlotte, Raleigh, Wilmington, Greenville-Spartanburg, Hickory, and Hilton Head.',
  },
  {
    slug: 'charlotte',
    displayName: 'Charlotte',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['mecklenburg-nc', 'union-nc', 'gaston-nc'],
    lat: 35.2271,
    lng: -80.8431,
    defaultToZip: '28202',
    topInboundOrigins: ['New York', 'New Jersey', 'Florida', 'California'],
    avgCostRanges: {
      studio: '$2,700–$5,300',
      twoBR: '$5,000–$8,100',
      threeBR: '$7,300–$11,400',
      fourBR: '$10,400–$15,800',
    },
    inboundGrowthStat: 'Banking and fintech hub with strong Northeast inbound flow',
    peakSeasonNote: 'Uptown high-rises and suburban new builds both need access planning',
    clusterParent: 'carolinas',
    priority: 5,
    mapDescription:
      'Charlotte and Mecklenburg County with Union and Gaston counties for greater Charlotte relocations.',
  },
  {
    slug: 'raleigh',
    displayName: 'Raleigh',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['wake-nc', 'durham-nc', 'johnston-nc'],
    lat: 35.7796,
    lng: -78.6382,
    defaultToZip: '27601',
    topInboundOrigins: ['New York', 'New Jersey', 'California', 'Florida'],
    avgCostRanges: {
      studio: '$2,800–$5,500',
      twoBR: '$5,200–$8,400',
      threeBR: '$7,600–$11,800',
      fourBR: '$10,800–$16,200',
    },
    inboundGrowthStat: 'Research Triangle leads NC net inbound migration',
    peakSeasonNote: 'University and tech hiring cycles peak late spring',
    clusterParent: 'carolinas',
    priority: 5,
    mapDescription:
      'Raleigh and Wake County in the Research Triangle with Durham and Johnston county links.',
  },
  {
    slug: 'wilmington-nc',
    displayName: 'Wilmington',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['new-hanover-nc', 'brunswick-nc', 'pender-nc'],
    lat: 34.2257,
    lng: -77.9447,
    defaultToZip: '28401',
    topInboundOrigins: ['New York', 'New Jersey', 'Virginia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,900–$5,600',
      twoBR: '$5,400–$8,600',
      threeBR: '$7,900–$12,100',
      fourBR: '$11,200–$16,800',
    },
    inboundGrowthStat: 'Coastal NC port city with retiree and remote-worker demand',
    peakSeasonNote: 'Hurricane season and beach-access properties require early planning',
    clusterParent: 'carolinas',
    priority: 5,
    mapDescription:
      'Wilmington and New Hanover County with Brunswick and Pender counties for coastal North Carolina moves.',
  },
  {
    slug: 'greenville-spartanburg',
    displayName: 'Greenville–Spartanburg',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['greenville-sc', 'spartanburg-sc', 'anderson-sc'],
    lat: 34.8526,
    lng: -82.394,
    defaultToZip: '29601',
    topInboundOrigins: ['New York', 'New Jersey', 'Florida', 'Ohio'],
    avgCostRanges: {
      studio: '$2,500–$4,900',
      twoBR: '$4,600–$7,500',
      threeBR: '$6,800–$10,600',
      fourBR: '$9,600–$14,500',
    },
    inboundGrowthStat: 'Upstate SC manufacturing and logistics growth corridor',
    peakSeasonNote: 'Affordable alternative to Charlotte — book early in summer',
    clusterParent: 'carolinas',
    priority: 5,
    mapDescription:
      'Greenville and Spartanburg counties in South Carolina\'s Upstate with Anderson County links.',
  },
  {
    slug: 'hickory',
    displayName: 'Hickory',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['catawba-nc', 'burke-nc', 'alexander-nc'],
    lat: 35.7332,
    lng: -81.3412,
    defaultToZip: '28601',
    topInboundOrigins: ['Florida', 'New York', 'Ohio', 'Georgia'],
    avgCostRanges: {
      studio: '$2,400–$4,700',
      twoBR: '$4,400–$7,100',
      threeBR: '$6,400–$10,000',
      fourBR: '$9,100–$13,600',
    },
    inboundGrowthStat: 'Foothills lifestyle market with lower cost than Charlotte metro',
    peakSeasonNote: 'Mountain terrain may require smaller shuttle trucks at destination',
    clusterParent: 'carolinas',
    priority: 5,
    mapDescription:
      'Hickory and Catawba County in the North Carolina foothills with Burke and Alexander county links.',
  },
  {
    slug: 'hilton-head',
    displayName: 'Hilton Head',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['beaufort-sc', 'jasper-sc'],
    lat: 32.2163,
    lng: -80.7526,
    defaultToZip: '29928',
    topInboundOrigins: ['New York', 'New Jersey', 'Ohio', 'Pennsylvania'],
    avgCostRanges: {
      studio: '$3,000–$5,800',
      twoBR: '$5,600–$9,000',
      threeBR: '$8,200–$12,600',
      fourBR: '$11,600–$17,500',
    },
    inboundGrowthStat: 'Premium island and Lowcountry retiree destination',
    peakSeasonNote: 'Gated communities and bridge access may require shuttle service',
    clusterParent: 'carolinas',
    priority: 5,
    mapDescription:
      'Hilton Head Island and Beaufort County with Jasper County links for Lowcountry South Carolina moves.',
  },
  {
    slug: 'boise-id',
    displayName: 'Boise',
    stateCode: 'ID',
    stateName: 'Idaho',
    primaryCounties: ['ada-id', 'canyon-id', 'gem-id'],
    lat: 43.615,
    lng: -116.2023,
    defaultToZip: '83702',
    topInboundOrigins: ['California', 'Washington', 'Oregon', 'Texas'],
    avgCostRanges: {
      studio: '$3,400–$6,200',
      twoBR: '$6,200–$9,500',
      threeBR: '$9,000–$13,500',
      fourBR: '$12,800–$19,000',
    },
    inboundGrowthStat: 'Top western inbound ratio driven by CA outmigration',
    peakSeasonNote: 'Summer is peak season; winter weather can delay cross-country delivery',
    priority: 6,
    mapDescription:
      'Boise and Ada County in Idaho\'s Treasure Valley with Canyon and Gem county links.',
  },
  {
    slug: 'eugene-springfield-or',
    displayName: 'Eugene–Springfield',
    stateCode: 'OR',
    stateName: 'Oregon',
    primaryCounties: ['lane-or'],
    lat: 44.0521,
    lng: -123.0868,
    defaultToZip: '97401',
    topInboundOrigins: ['California', 'Washington', 'Texas', 'Colorado'],
    avgCostRanges: {
      studio: '$3,200–$6,000',
      twoBR: '$5,900–$9,200',
      threeBR: '$8,600–$13,000',
      fourBR: '$12,200–$18,200',
    },
    inboundGrowthStat: 'Willamette Valley lifestyle market with university and tech spillover',
    peakSeasonNote: 'Rainy-season loading requires covered truck access planning',
    priority: 7,
    mapDescription:
      'Eugene and Springfield in Lane County, Oregon\'s Willamette Valley corridor.',
  },
  {
    slug: 'tulsa-ok',
    displayName: 'Tulsa',
    stateCode: 'OK',
    stateName: 'Oklahoma',
    primaryCounties: ['tulsa-ok', 'wagoner-ok', 'creek-ok'],
    lat: 36.154,
    lng: -95.9928,
    defaultToZip: '74103',
    topInboundOrigins: ['Texas', 'California', 'Colorado', 'Missouri'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,500–$7,200',
      threeBR: '$6,500–$10,200',
      fourBR: '$9,200–$13,800',
    },
    inboundGrowthStat: 'Affordable mid-size metro with energy and aerospace hiring',
    peakSeasonNote: 'Tornado season awareness — confirm carrier contingency policies',
    priority: 8,
    mapDescription:
      'Tulsa and Tulsa County in northeast Oklahoma with Wagoner and Creek county links.',
  },
  {
    slug: 'phoenix-az',
    displayName: 'Phoenix',
    stateCode: 'AZ',
    stateName: 'Arizona',
    primaryCounties: ['maricopa-az', 'pinal-az'],
    lat: 33.4484,
    lng: -112.074,
    defaultToZip: '85004',
    topInboundOrigins: ['California', 'Illinois', 'Washington', 'Texas'],
    avgCostRanges: {
      studio: '$2,800–$5,600',
      twoBR: '$5,200–$8,500',
      threeBR: '$7,600–$11,900',
      fourBR: '$10,800–$16,500',
    },
    inboundGrowthStat: 'Sunbelt leader for CA and Midwest inbound volume',
    peakSeasonNote: 'Summer heat limits loading hours — schedule early-morning crews',
    priority: 9,
    mapDescription:
      'Phoenix and Maricopa County in the Valley of the Sun with Pinal County suburb links.',
  },
  {
    slug: 'little-rock-ar',
    displayName: 'Little Rock',
    stateCode: 'AR',
    stateName: 'Arkansas',
    primaryCounties: ['pulaski-ar', 'saline-ar', 'lonoke-ar'],
    lat: 34.7465,
    lng: -92.2896,
    defaultToZip: '72201',
    topInboundOrigins: ['Texas', 'California', 'Tennessee', 'Missouri'],
    avgCostRanges: {
      studio: '$2,300–$4,600',
      twoBR: '$4,200–$6,900',
      threeBR: '$6,200–$9,800',
      fourBR: '$8,800–$13,200',
    },
    inboundGrowthStat: 'State capital with healthcare and government-sector relocations',
    peakSeasonNote: 'Affordable market — fewer carriers may serve AR directly; book early',
    priority: 10,
    mapDescription:
      'Little Rock and Pulaski County in central Arkansas with Saline and Lonoke county links.',
  },
  {
    slug: 'birmingham-al',
    displayName: 'Birmingham',
    stateCode: 'AL',
    stateName: 'Alabama',
    primaryCounties: ['jefferson-al', 'shelby-al', 'st-clair-al'],
    lat: 33.5186,
    lng: -86.8104,
    defaultToZip: '35203',
    topInboundOrigins: ['Georgia', 'Florida', 'Texas', 'California'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,400–$7,200',
      threeBR: '$6,500–$10,200',
      fourBR: '$9,200–$13,800',
    },
    inboundGrowthStat: 'Healthcare and finance hub for southeastern inbound moves',
    peakSeasonNote: 'Hilly terrain in suburbs may affect truck access',
    priority: 11,
    mapDescription:
      'Birmingham and Jefferson County in central Alabama with Shelby and St. Clair county links.',
  },
  {
    slug: 'huntsville-al',
    displayName: 'Huntsville',
    stateCode: 'AL',
    stateName: 'Alabama',
    primaryCounties: ['madison-al', 'limestone-al', 'morgan-al'],
    lat: 34.7304,
    lng: -86.5861,
    defaultToZip: '35801',
    topInboundOrigins: ['California', 'Texas', 'Florida', 'Georgia'],
    avgCostRanges: {
      studio: '$2,500–$5,000',
      twoBR: '$4,600–$7,500',
      threeBR: '$6,800–$10,600',
      fourBR: '$9,600–$14,500',
    },
    inboundGrowthStat: 'Defense and aerospace corridor with sustained tech inbound flow',
    peakSeasonNote: 'Redstone Arsenal area moves may require security clearance coordination',
    priority: 12,
    mapDescription:
      'Huntsville and Madison County in north Alabama with Limestone and Morgan county links.',
  },
];

export function getMarketBySlug(slug: string): Market | undefined {
  return markets.find((market) => market.slug === slug);
}

export function getClusterMarkets(cluster: string): Market[] {
  return markets.filter((market) => market.clusterParent === cluster);
}

export function getMarketPath(market: Market): string {
  if (market.isClusterParent) {
    return `/moving-to/${market.slug}`;
  }
  if (market.clusterParent) {
    return `/moving-to/${market.clusterParent}/${market.slug}`;
  }
  return `/moving-to/${market.slug}`;
}

export const priorityMarketsForNav = [...markets].sort((a, b) => {
  if (a.priority !== b.priority) return a.priority - b.priority;
  if (a.isClusterParent && !b.isClusterParent) return -1;
  if (!a.isClusterParent && b.isClusterParent) return 1;
  return a.displayName.localeCompare(b.displayName);
});

export function getStandaloneAndClusterParentMarkets(): Market[] {
  return markets.filter((market) => market.isClusterParent || !market.clusterParent);
}