import type { Market } from '@/lib/destinations/types';

export const markets: Market[] = [
  {
    slug: 'south-carolina',
    displayName: 'South Carolina',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: [],
    lat: 33.8,
    lng: -80.9,
    defaultToZip: '29577',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,000–$5,700',
      twoBR: '$5,600–$8,700',
      threeBR: '$8,100–$12,300',
      fourBR: '$11,500–$16,900',
    },
    inboundGrowthStat: 'Grand Strand coastal corridor · no retirement income tax · beaches to Upstate',
    peakSeasonNote: 'May–September peak on coast; book 8–12 weeks ahead',
    isClusterParent: true,
    priority: 1,
    mapDescription:
      'South Carolina inbound hub covering the Grand Strand, Lowcountry, and Upstate growth corridors.',
  },
  {
    slug: 'myrtle-beach-sc',
    displayName: 'Myrtle Beach',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc', 'brunswick-nc', 'new-hanover-nc'],
    lat: 33.6887,
    lng: -78.8877,
    defaultToZip: '29577',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,200–$5,800',
      twoBR: '$5,900–$8,900',
      threeBR: '$8,200–$12,500',
      fourBR: '$11,800–$17,200',
    },
    inboundGrowthStat: '3.88:1 inbound ratio · flagship Grand Strand destination (2026)',
    peakSeasonNote: 'May–September; book 8–12 weeks ahead',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Myrtle Beach in Horry County — flagship Grand Strand destination with highest inbound intent on the Carolina coast.',
  },
  {
    slug: 'north-myrtle-beach',
    displayName: 'North Myrtle Beach',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc'],
    lat: 33.816,
    lng: -78.68,
    defaultToZip: '29582',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,200–$5,800',
      twoBR: '$5,900–$8,900',
      threeBR: '$8,200–$12,500',
      fourBR: '$11,800–$17,200',
    },
    inboundGrowthStat: 'Shag dance capital & family-friendly northern Grand Strand anchor',
    peakSeasonNote: 'Main Street & Barefoot Resort gated communities require early elevator and access planning',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'North Myrtle Beach in Horry County — Main Street nightlife, Cherry Grove pier, and family-oriented northern Grand Strand beaches.',
  },
  {
    slug: 'surfside-beach',
    displayName: 'Surfside Beach',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc'],
    lat: 33.6063,
    lng: -78.9736,
    defaultToZip: '29575',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,100–$5,700',
      twoBR: '$5,800–$8,800',
      threeBR: '$8,100–$12,400',
      fourBR: '$11,600–$17,000',
    },
    inboundGrowthStat: '"Family Beach" with pier town charm and residential coastal appeal',
    peakSeasonNote: 'Smaller beach town streets may need shuttle trucks — confirm access before peak summer',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Surfside Beach in Horry County — Family Beach pier town between Myrtle Beach and Garden City with residential neighborhoods.',
  },
  {
    slug: 'atlantic-beach',
    displayName: 'Atlantic Beach',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc'],
    lat: 33.7918,
    lng: -78.7172,
    defaultToZip: '29582',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Virginia'],
    avgCostRanges: {
      studio: '$3,200–$5,800',
      twoBR: '$5,900–$8,900',
      threeBR: '$8,200–$12,500',
      fourBR: '$11,800–$17,200',
    },
    inboundGrowthStat: 'Historic Black beach town heritage with growing retiree and family inbound flow',
    peakSeasonNote: 'Compact oceanfront grid — limited truck parking during summer weekends',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Atlantic Beach in Horry County — historic coastal community between North Myrtle Beach and Crescent Beach.',
  },
  {
    slug: 'garden-city-beach',
    displayName: 'Garden City Beach',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc', 'georgetown-sc'],
    lat: 33.5882,
    lng: -79.0087,
    defaultToZip: '29576',
    topInboundOrigins: ['New York', 'New Jersey', 'Ohio', 'Michigan'],
    avgCostRanges: {
      studio: '$3,100–$5,700',
      twoBR: '$5,800–$8,800',
      threeBR: '$8,100–$12,400',
      fourBR: '$11,600–$17,000',
    },
    inboundGrowthStat: 'Pier village & rental corridor spanning Horry and Georgetown counties',
    peakSeasonNote: 'Summer rental turnover peaks late May–August — book 8+ weeks ahead',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Garden City Beach spanning Horry and Georgetown counties — pier village, vacation rentals, and family beach homes.',
  },
  {
    slug: 'little-river',
    displayName: 'Little River',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc'],
    lat: 33.8732,
    lng: -78.6142,
    defaultToZip: '29566',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,000–$5,600',
      twoBR: '$5,600–$8,600',
      threeBR: '$8,000–$12,200',
      fourBR: '$11,400–$16,800',
    },
    inboundGrowthStat: 'Waterfront dining & Calabash seafood gateway at the NC border',
    peakSeasonNote: 'Intracoastal and waterfront homes may need specialty handling near the state line',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Little River in northern Horry County — Intracoastal Waterway, seafood waterfront, and NC border spillover.',
  },
  {
    slug: 'murrells-inlet',
    displayName: 'Murrells Inlet',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['georgetown-sc', 'horry-sc'],
    lat: 33.5471,
    lng: -79.0414,
    defaultToZip: '29576',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,100–$5,700',
      twoBR: '$5,800–$8,800',
      threeBR: '$8,100–$12,400',
      fourBR: '$11,600–$17,000',
    },
    inboundGrowthStat: 'Seafood capital of South Carolina — MarshWalk & inlet waterfront demand',
    peakSeasonNote: 'MarshWalk restaurants and marsh-front homes require tide-aware delivery planning',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Murrells Inlet in Georgetown County — MarshWalk dining district, inlet boating, and marsh-front residential moves.',
  },
  {
    slug: 'socastee',
    displayName: 'Socastee',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc'],
    lat: 33.686,
    lng: -79.0088,
    defaultToZip: '29588',
    topInboundOrigins: ['New York', 'New Jersey', 'Ohio', 'Pennsylvania'],
    avgCostRanges: {
      studio: '$3,000–$5,600',
      twoBR: '$5,600–$8,600',
      threeBR: '$8,000–$12,200',
      fourBR: '$11,400–$16,800',
    },
    inboundGrowthStat: 'Inland Grand Strand suburb with affordable single-family and Intracoastal access',
    peakSeasonNote: 'US-501 and Highway 17 traffic peaks summer — schedule morning delivery windows',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Socastee in Horry County — inland Grand Strand neighborhoods between Myrtle Beach and Conway with Intracoastal access.',
  },
  {
    slug: 'carolina-forest',
    displayName: 'Carolina Forest',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['horry-sc'],
    lat: 33.73,
    lng: -78.92,
    defaultToZip: '29579',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,100–$5,700',
      twoBR: '$5,700–$8,700',
      threeBR: '$8,100–$12,300',
      fourBR: '$11,600–$16,900',
    },
    inboundGrowthStat: 'Master-planned golf & family community — fastest-growing Horry County suburb',
    peakSeasonNote: 'Gated golf communities and new-build streets may require shuttle trucks — confirm HOA rules',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Carolina Forest in Horry County — master-planned communities, golf courses, and suburban family relocations inland from the beach.',
  },
  {
    slug: 'florida',
    displayName: 'Florida',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: [],
    lat: 28.0,
    lng: -82.0,
    defaultToZip: '32202',
    topInboundOrigins: ['New York', 'New Jersey', 'Illinois', 'California'],
    avgCostRanges: {
      studio: '$2,800–$5,500',
      twoBR: '$5,200–$8,400',
      threeBR: '$7,500–$11,800',
      fourBR: '$10,500–$16,000',
    },
    inboundGrowthStat: 'Highest-volume Sunbelt inbound corridor in 2026',
    peakSeasonNote: 'Year-round demand; hurricane season June–November requires contingency planning',
    isClusterParent: true,
    priority: 2,
    mapDescription:
      'Florida inbound migration hub covering Miami-Dade and Broward (Miami, Fort Lauderdale, Hollywood, Pompano Beach), the Palm Beach corridor, Jacksonville, Sarasota, Naples, and central Florida growth markets.',
  },
  {
    slug: 'jacksonville',
    displayName: 'Jacksonville',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['duval-fl', 'st-johns-fl', 'clay-fl'],
    lat: 30.3322,
    lng: -81.6557,
    defaultToZip: '32202',
    topInboundOrigins: ['New York', 'New Jersey', 'Georgia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,600–$5,200',
      twoBR: '$4,800–$7,900',
      threeBR: '$7,000–$11,200',
      fourBR: '$9,800–$14,500',
    },
    inboundGrowthStat: 'Top-5 Florida metro for net inbound moves (2026)',
    peakSeasonNote: 'Spring and fall offer best carrier availability',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Jacksonville, FL and Duval County service area with links to St. Johns and Clay counties for northeast Florida relocations.',
  },
  {
    slug: 'sarasota',
    displayName: 'Sarasota',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['sarasota-fl', 'manatee-fl'],
    lat: 27.3364,
    lng: -82.5307,
    defaultToZip: '34236',
    topInboundOrigins: ['New York', 'New Jersey', 'Illinois', 'Michigan'],
    avgCostRanges: {
      studio: '$2,900–$5,600',
      twoBR: '$5,400–$8,600',
      threeBR: '$7,800–$12,000',
      fourBR: '$11,000–$16,500',
    },
    inboundGrowthStat: 'Gulf Coast retiree and remote-worker hotspot',
    peakSeasonNote: 'Snowbird season October–April tightens southbound schedules',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Sarasota and Manatee counties on Florida\'s Gulf Coast, including condo and waterfront access considerations.',
  },
  {
    slug: 'naples',
    displayName: 'Naples',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['collier-fl', 'lee-fl'],
    lat: 26.142,
    lng: -81.7948,
    defaultToZip: '34102',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'Illinois'],
    avgCostRanges: {
      studio: '$3,100–$6,000',
      twoBR: '$5,800–$9,200',
      threeBR: '$8,500–$13,200',
      fourBR: '$12,000–$18,500',
    },
    inboundGrowthStat: 'Premium coastal market with high specialty-item demand',
    peakSeasonNote: 'Gated communities may require shuttle trucks — confirm access early',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Naples and Collier County on southwest Florida\'s coast, with Lee County spillover for Fort Myers area moves.',
  },
  {
    slug: 'ocala',
    displayName: 'Ocala',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['marion-fl', 'sumter-fl'],
    lat: 29.1872,
    lng: -82.1401,
    defaultToZip: '34471',
    topInboundOrigins: ['New York', 'New Jersey', 'Georgia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,500–$4,900',
      twoBR: '$4,600–$7,400',
      threeBR: '$6,800–$10,500',
      fourBR: '$9,500–$14,000',
    },
    inboundGrowthStat: 'Central Florida horse country and affordable suburban growth',
    peakSeasonNote: 'Summer heat affects loading schedules — book morning slots',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Ocala and Marion County in central Florida, with Sumter County links for The Villages corridor demand.',
  },
  {
    slug: 'st-augustine',
    displayName: 'St. Augustine',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['st-johns-fl', 'flagler-fl'],
    lat: 29.8947,
    lng: -81.3145,
    defaultToZip: '32084',
    topInboundOrigins: ['New York', 'New Jersey', 'Georgia', 'Pennsylvania'],
    avgCostRanges: {
      studio: '$2,700–$5,300',
      twoBR: '$5,000–$8,100',
      threeBR: '$7,200–$11,400',
      fourBR: '$10,200–$15,200',
    },
    inboundGrowthStat: 'Historic coastal city with strong Northeast inbound flow',
    peakSeasonNote: 'Tourism season can affect downtown access — plan delivery windows',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'St. Augustine in St. Johns County with Flagler County links for northeast Florida coastal relocations.',
  },
  {
    slug: 'wildwood',
    displayName: 'Wildwood',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['sumter-fl', 'lake-fl', 'marion-fl'],
    lat: 28.9653,
    lng: -82.0384,
    defaultToZip: '34785',
    topInboundOrigins: ['New York', 'New Jersey', 'Michigan', 'Ohio'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,500–$7,200',
      threeBR: '$6,500–$10,200',
      fourBR: '$9,200–$13,800',
    },
    inboundGrowthStat: 'Central Florida growth corridor driven by 55+ and suburban expansion',
    peakSeasonNote: 'Active adult communities may have move-day restrictions',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Wildwood and Sumter County in central Florida, including The Villages and Lake County spillover.',
  },
  {
    slug: 'boca-raton',
    displayName: 'Boca Raton',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['palm-beach-fl'],
    lat: 26.3683,
    lng: -80.1289,
    defaultToZip: '33432',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'Illinois'],
    avgCostRanges: {
      studio: '$3,400–$6,400',
      twoBR: '$6,000–$9,800',
      threeBR: '$8,800–$13,800',
      fourBR: '$12,800–$19,200',
    },
    inboundGrowthStat: 'Affluent Palm Beach corridor with luxury high-rise and gated-community demand',
    peakSeasonNote: 'Snowbird season October–April tightens southbound schedules; luxury buildings require COI and elevator reservations',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Boca Raton in Palm Beach County — luxury coastal relocations with Mizner Park, gated communities, and strict high-rise move protocols.',
  },
  {
    slug: 'deerfield-beach',
    displayName: 'Deerfield Beach',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['palm-beach-fl', 'broward-fl'],
    lat: 26.3184,
    lng: -80.0998,
    defaultToZip: '33441',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,200–$6,100',
      twoBR: '$5,800–$9,300',
      threeBR: '$8,400–$13,000',
      fourBR: '$12,000–$18,200',
    },
    inboundGrowthStat: 'Family-friendly coastal city on the Palm Beach–Broward border with boating access',
    peakSeasonNote: 'Hillsboro Inlet and waterfront homes may need specialty handling; book before winter snowbird peak',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Deerfield Beach spanning Palm Beach and Broward counties — family neighborhoods, Quiet Waters Park, and Intracoastal boating communities.',
  },
  {
    slug: 'boynton-beach',
    displayName: 'Boynton Beach',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['palm-beach-fl'],
    lat: 26.5284,
    lng: -80.0664,
    defaultToZip: '33435',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'Michigan'],
    avgCostRanges: {
      studio: '$3,100–$6,000',
      twoBR: '$5,700–$9,100',
      threeBR: '$8,300–$12,800',
      fourBR: '$11,800–$17,800',
    },
    inboundGrowthStat: 'Growing Palm Beach County value market between Boca Raton and West Palm Beach',
    peakSeasonNote: 'Oceanfront condos and 55+ communities often restrict move windows — confirm HOA rules early',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Boynton Beach in Palm Beach County — Oceanfront Park corridor, family suburbs, and affordable coastal alternatives to Boca Raton.',
  },
  {
    slug: 'delray-beach',
    displayName: 'Delray Beach',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['palm-beach-fl'],
    lat: 26.4615,
    lng: -80.0728,
    defaultToZip: '33444',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'California'],
    avgCostRanges: {
      studio: '$3,300–$6,300',
      twoBR: '$5,900–$9,500',
      threeBR: '$8,600–$13,400',
      fourBR: '$12,400–$18,800',
    },
    inboundGrowthStat: 'Atlantic Avenue arts district and walkable downtown driving Northeast inbound flow',
    peakSeasonNote: 'Historic downtown and beach condos require tight delivery windows during festival season',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Delray Beach in Palm Beach County — Pineapple Grove, Atlantic Avenue dining district, and beach-access residential moves.',
  },
  {
    slug: 'miami',
    displayName: 'Miami',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['miami-dade-fl'],
    lat: 25.7617,
    lng: -80.1918,
    defaultToZip: '33101',
    topInboundOrigins: ['New York', 'New Jersey', 'California', 'Illinois'],
    avgCostRanges: {
      studio: '$3,500–$6,600',
      twoBR: '$6,200–$10,200',
      threeBR: '$9,000–$14,200',
      fourBR: '$13,000–$19,800',
    },
    inboundGrowthStat: 'Major urban inbound hub — finance, tech, international, and condo high-rise demand',
    peakSeasonNote: 'Miami Beach and Brickell towers require COI, elevator slots, and causeway logistics — book early for snowbird season',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Miami and Miami-Dade County — Brickell high-rises, Miami Beach condos, Coral Gables estates, and dense urban move protocols.',
  },
  {
    slug: 'fort-lauderdale',
    displayName: 'Fort Lauderdale',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['broward-fl'],
    lat: 26.1224,
    lng: -80.1373,
    defaultToZip: '33301',
    topInboundOrigins: ['New York', 'New Jersey', 'Massachusetts', 'Pennsylvania'],
    avgCostRanges: {
      studio: '$3,300–$6,400',
      twoBR: '$6,000–$9,800',
      threeBR: '$8,700–$13,500',
      fourBR: '$12,500–$18,500',
    },
    inboundGrowthStat: 'Yachting capital and beach-lifestyle metro with strong Northeast inbound flow',
    peakSeasonNote: 'Las Olas and beach high-rises need elevator reservations; winter snowbird peak tightens schedules',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Fort Lauderdale in Broward County — Las Olas corridor, Intracoastal waterfront, and beach-access condo moves.',
  },
  {
    slug: 'hollywood',
    displayName: 'Hollywood',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['broward-fl'],
    lat: 26.0112,
    lng: -80.1495,
    defaultToZip: '33020',
    topInboundOrigins: ['New York', 'New Jersey', 'Ohio', 'Michigan'],
    avgCostRanges: {
      studio: '$3,200–$6,200',
      twoBR: '$5,900–$9,500',
      threeBR: '$8,500–$13,200',
      fourBR: '$12,200–$18,200',
    },
    inboundGrowthStat: 'Broadwalk beach lifestyle between Fort Lauderdale and Miami with family and retiree demand',
    peakSeasonNote: 'Hollywood Beach broadwalk condos and mid-rise buildings often restrict weekend move windows',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Hollywood in Broward County — Hollywood Beach Broadwalk, downtown arts district, and family suburban neighborhoods.',
  },
  {
    slug: 'pompano-beach',
    displayName: 'Pompano Beach',
    stateCode: 'FL',
    stateName: 'Florida',
    primaryCounties: ['broward-fl', 'palm-beach-fl'],
    lat: 26.2379,
    lng: -80.1248,
    defaultToZip: '33060',
    topInboundOrigins: ['New York', 'New Jersey', 'Pennsylvania', 'Ohio'],
    avgCostRanges: {
      studio: '$3,200–$6,100',
      twoBR: '$5,800–$9,300',
      threeBR: '$8,400–$13,000',
      fourBR: '$12,000–$18,000',
    },
    inboundGrowthStat: 'Affordable Broward beach market north of Fort Lauderdale with boating and fishing community appeal',
    peakSeasonNote: 'Hillsboro Inlet and beach-access properties may need shuttle trucks — confirm building rules early',
    clusterParent: 'florida',
    priority: 2,
    mapDescription:
      'Pompano Beach in Broward County — fishing pier corridor, boating communities, and Palm Beach County border spillover.',
  },
  {
    slug: 'tennessee',
    displayName: 'Tennessee',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: [],
    lat: 35.8,
    lng: -86.4,
    defaultToZip: '37201',
    topInboundOrigins: ['California', 'Illinois', 'New York', 'Florida'],
    avgCostRanges: {
      studio: '$2,400–$5,400',
      twoBR: '$4,500–$8,200',
      threeBR: '$6,500–$11,500',
      fourBR: '$9,200–$16,000',
    },
    inboundGrowthStat: 'No state income tax · top-5 inbound state for net migration (2026)',
    peakSeasonNote: 'Spring and fall offer best carrier availability statewide',
    isClusterParent: true,
    priority: 3,
    mapDescription:
      'Tennessee inbound hub covering Nashville metro, Knoxville, Chattanooga, Clarksville, Murfreesboro, Williamson County, and Tri-Cities growth corridors.',
  },
  {
    slug: 'nashville-tn',
    displayName: 'Nashville',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['davidson-tn', 'williamson-tn', 'rutherford-tn'],
    lat: 36.1627,
    lng: -86.7816,
    defaultToZip: '37201',
    topInboundOrigins: ['California', 'Illinois', 'New York', 'Florida'],
    avgCostRanges: {
      studio: '$2,800–$5,400',
      twoBR: '$5,200–$8,200',
      threeBR: '$7,600–$11,500',
      fourBR: '$10,800–$16,000',
    },
    inboundGrowthStat: 'Booming job market · music & tech hub · top Nashville metro inbound volume',
    peakSeasonNote: 'Corporate relocations peak May–August; book 8–10 weeks ahead',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Nashville and Davidson County with Middle Tennessee suburban ring spillover into Williamson and Rutherford counties.',
  },
  {
    slug: 'knoxville-tn',
    displayName: 'Knoxville',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['knox-tn', 'anderson-tn'],
    lat: 35.9606,
    lng: -83.9207,
    defaultToZip: '37902',
    topInboundOrigins: ['Chicago', 'Detroit', 'Atlanta', 'New York'],
    avgCostRanges: {
      studio: '$3,100–$5,700',
      twoBR: '$5,500–$8,500',
      threeBR: '$7,800–$11,900',
      fourBR: '$11,000–$16,200',
    },
    inboundGrowthStat: 'Top-10 inbound ratio · UT/ORNL corridor · Smoky Mountain access',
    peakSeasonNote: 'Spring and fall ideal; summer UT/ORNL turnover spikes demand',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Knoxville in Knox County with Anderson County links for Oak Ridge and eastern Tennessee relocations.',
  },
  {
    slug: 'clarksville-tn',
    displayName: 'Clarksville',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['montgomery-tn', 'stewart-tn'],
    lat: 36.5298,
    lng: -87.3595,
    defaultToZip: '37040',
    topInboundOrigins: ['Texas', 'California', 'Georgia', 'Kentucky'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,500–$7,200',
      threeBR: '$6,500–$10,200',
      fourBR: '$9,200–$13,800',
    },
    inboundGrowthStat: 'Fort Campbell military corridor · high affordability · diverse inbound',
    peakSeasonNote: 'PCS season tightens summer schedules — coordinate with base housing early',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Clarksville in Montgomery County with Stewart County links for Fort Campbell military relocations.',
  },
  {
    slug: 'murfreesboro-tn',
    displayName: 'Murfreesboro',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['rutherford-tn', 'wilson-tn'],
    lat: 35.8456,
    lng: -86.3922,
    defaultToZip: '37130',
    topInboundOrigins: ['Illinois', 'California', 'Georgia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,600–$5,100',
      twoBR: '$4,800–$7,800',
      threeBR: '$7,000–$10,800',
      fourBR: '$9,800–$14,500',
    },
    inboundGrowthStat: 'MTSU anchor · younger demographic · Nashville suburban growth spillover',
    peakSeasonNote: 'University turnover peaks May–August; suburban new-build may need shuttle trucks',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Murfreesboro in Rutherford County — fast-growing Nashville metro suburb with MTSU and I-24 corridor demand.',
  },
  {
    slug: 'chattanooga-tn',
    displayName: 'Chattanooga',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['hamilton-tn', 'bradley-tn'],
    lat: 35.0456,
    lng: -85.3097,
    defaultToZip: '37402',
    topInboundOrigins: ['Atlanta', 'Chicago', 'Detroit', 'New York'],
    avgCostRanges: {
      studio: '$2,500–$4,900',
      twoBR: '$4,600–$7,400',
      threeBR: '$6,800–$10,500',
      fourBR: '$9,500–$14,000',
    },
    inboundGrowthStat: 'Gig City · outdoor lifestyle · remote-worker and tech inbound hotspot',
    peakSeasonNote: 'Lookout Mountain and riverfront access may need shuttle coordination',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Chattanooga in Hamilton County with outdoor recreation, gig-economy tech growth, and Bradley County spillover.',
  },
  {
    slug: 'lebanon-tn',
    displayName: 'Lebanon',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['wilson-tn', 'davidson-tn'],
    lat: 36.2081,
    lng: -86.2911,
    defaultToZip: '37087',
    topInboundOrigins: ['Illinois', 'California', 'Georgia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,600–$5,000',
      twoBR: '$4,700–$7,600',
      threeBR: '$6,900–$10,600',
      fourBR: '$9,700–$14,200',
    },
    inboundGrowthStat: 'Fast-growing Wilson County · larger lots · quieter Nashville-adjacent pace',
    peakSeasonNote: 'New subdivisions may have narrow streets — confirm truck access before booking',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Lebanon in Wilson County — Nashville metro growth corridor with family-oriented suburban expansion.',
  },
  {
    slug: 'franklin-brentwood-tn',
    displayName: 'Franklin / Brentwood',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['williamson-tn', 'davidson-tn'],
    lat: 35.9251,
    lng: -86.8689,
    defaultToZip: '37064',
    topInboundOrigins: ['Illinois', 'California', 'New York', 'Texas'],
    avgCostRanges: {
      studio: '$3,000–$5,800',
      twoBR: '$5,600–$8,900',
      threeBR: '$8,200–$12,600',
      fourBR: '$11,500–$17,500',
    },
    inboundGrowthStat: 'Wealthy Williamson County · top schools · high-end suburban communities',
    peakSeasonNote: 'Gated estates and luxury builds may require white-glove and shuttle accessorials',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Franklin and Brentwood in Williamson County — premium Nashville metro suburbs with top-rated schools.',
  },
  {
    slug: 'mount-juliet-tn',
    displayName: 'Mount Juliet',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['wilson-tn', 'davidson-tn'],
    lat: 36.2001,
    lng: -86.5186,
    defaultToZip: '37122',
    topInboundOrigins: ['Illinois', 'California', 'Georgia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,600–$5,100',
      twoBR: '$4,800–$7,700',
      threeBR: '$7,000–$10,700',
      fourBR: '$9,800–$14,400',
    },
    inboundGrowthStat: 'Family-friendly lakeside suburb · retail growth · strong school district appeal',
    peakSeasonNote: 'Providence marketplace corridor traffic can affect delivery scheduling',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Mount Juliet in Wilson County — family-oriented Nashville suburb with lake access and retail development.',
  },
  {
    slug: 'columbia-tn',
    displayName: 'Columbia',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['maury-tn', 'williamson-tn'],
    lat: 35.6151,
    lng: -87.0353,
    defaultToZip: '38401',
    topInboundOrigins: ['Illinois', 'Georgia', 'Ohio', 'Kentucky'],
    avgCostRanges: {
      studio: '$2,400–$4,700',
      twoBR: '$4,400–$7,100',
      threeBR: '$6,500–$10,000',
      fourBR: '$9,200–$13,600',
    },
    inboundGrowthStat: 'Historic Mule Town · affordable south-of-Nashville alternative',
    peakSeasonNote: 'Historic downtown streets may need smaller equipment or shuttle trucks',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Columbia in Maury County — affordable Nashville corridor alternative with historic downtown charm.',
  },
  {
    slug: 'tri-cities-tn',
    displayName: 'Johnson City / Kingsport',
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryCounties: ['washington-tn', 'sullivan-tn', 'carter-tn'],
    lat: 36.3134,
    lng: -82.3535,
    defaultToZip: '37601',
    topInboundOrigins: ['Florida', 'North Carolina', 'Virginia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,500–$7,200',
      threeBR: '$6,600–$10,300',
      fourBR: '$9,300–$13,900',
    },
    inboundGrowthStat: 'Tri-Cities region · ETSU · healthcare · mountain retirement & remote work',
    peakSeasonNote: 'Mountain terrain and rural driveways may require shuttle or long-carry fees',
    clusterParent: 'tennessee',
    priority: 3,
    mapDescription:
      'Johnson City, Kingsport, and Bristol Tri-Cities region in Washington and Sullivan counties.',
  },
  {
    slug: 'texas',
    displayName: 'Texas',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: [],
    lat: 31.0,
    lng: -99.0,
    defaultToZip: '75201',
    topInboundOrigins: ['California', 'Illinois', 'New York', 'Florida'],
    avgCostRanges: {
      studio: '$2,900–$5,800',
      twoBR: '$5,400–$8,800',
      threeBR: '$7,900–$12,400',
      fourBR: '$11,200–$17,500',
    },
    inboundGrowthStat: 'Leading job-growth state for interstate household moves',
    peakSeasonNote: 'Summer corporate relocations peak May–August',
    isClusterParent: true,
    priority: 4,
    mapDescription:
      'Texas inbound hub covering Dallas–Fort Worth, Austin, Houston, San Antonio, and West Texas growth corridors.',
  },
  {
    slug: 'dallas-fort-worth-tx',
    displayName: 'Dallas–Fort Worth',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['dallas-tx', 'tarrant-tx', 'collin-tx', 'denton-tx'],
    lat: 32.7767,
    lng: -96.797,
    defaultToZip: '75201',
    topInboundOrigins: ['California', 'Illinois', 'New York', 'Florida'],
    avgCostRanges: {
      studio: '$2,800–$5,600',
      twoBR: '$5,200–$8,400',
      threeBR: '$7,600–$11,800',
      fourBR: '$10,800–$16,200',
    },
    inboundGrowthStat: 'DFW metro leads Texas net inbound · Frisco · Plano · McKinney suburbs',
    peakSeasonNote: 'Suburban new-build communities may have narrow street access',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Dallas–Fort Worth metro spanning Dallas, Tarrant, Collin, and Denton counties in north Texas.',
  },
  {
    slug: 'austin-tx',
    displayName: 'Austin',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['travis-tx', 'williamson-tx', 'hays-tx'],
    lat: 30.2672,
    lng: -97.7431,
    defaultToZip: '78701',
    topInboundOrigins: ['California', 'New York', 'Illinois', 'Washington'],
    avgCostRanges: {
      studio: '$3,000–$6,000',
      twoBR: '$5,600–$9,000',
      threeBR: '$8,200–$12,600',
      fourBR: '$11,500–$17,800',
    },
    inboundGrowthStat: 'Silicon Hills tech boom · live music · Hill Country outdoor lifestyle',
    peakSeasonNote: 'Downtown high-rises and hill-country homes both need access surveys',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Austin and Travis County with Williamson and Hays counties for greater Austin metro moves.',
  },
  {
    slug: 'houston-tx',
    displayName: 'Houston',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['harris-tx', 'fort-bend-tx', 'montgomery-tx'],
    lat: 29.7604,
    lng: -95.3698,
    defaultToZip: '77002',
    topInboundOrigins: ['California', 'Louisiana', 'Illinois', 'New York'],
    avgCostRanges: {
      studio: '$2,700–$5,500',
      twoBR: '$5,000–$8,200',
      threeBR: '$7,400–$11,600',
      fourBR: '$10,500–$16,000',
    },
    inboundGrowthStat: 'Energy capital · NASA · medical center · Woodlands · Katy · Sugar Land',
    peakSeasonNote: 'Hurricane season requires flexible delivery date clauses',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Houston and Harris County with Fort Bend and Montgomery counties for greater Houston relocations.',
  },
  {
    slug: 'san-antonio-tx',
    displayName: 'San Antonio',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['bexar-tx', 'comal-tx', 'guadalupe-tx'],
    lat: 29.4241,
    lng: -98.4936,
    defaultToZip: '78205',
    topInboundOrigins: ['California', 'Illinois', 'Florida', 'Colorado'],
    avgCostRanges: {
      studio: '$2,500–$5,000',
      twoBR: '$4,700–$7,600',
      threeBR: '$6,900–$10,800',
      fourBR: '$9,800–$14,500',
    },
    inboundGrowthStat: 'Alamo historic charm · military bases · River Walk · affordable families',
    peakSeasonNote: 'Military PCS season and summer family moves tighten schedules',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'San Antonio in Bexar County with Comal and Guadalupe counties for greater metro relocations.',
  },
  {
    slug: 'el-paso-tx',
    displayName: 'El Paso',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['el-paso-tx', 'hudspeth-tx'],
    lat: 31.7619,
    lng: -106.485,
    defaultToZip: '79901',
    topInboundOrigins: ['California', 'Arizona', 'New Mexico', 'Colorado'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,400–$7,100',
      threeBR: '$6,500–$10,000',
      fourBR: '$9,200–$13,600',
    },
    inboundGrowthStat: 'Border metro affordability · Fort Bliss military · desert lifestyle',
    peakSeasonNote: 'Summer heat affects loading schedules — book morning slots',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'El Paso in El Paso County with Hudspeth County links for West Texas border relocations.',
  },
  {
    slug: 'arlington-tx',
    displayName: 'Arlington',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['tarrant-tx', 'dallas-tx'],
    lat: 32.7357,
    lng: -97.1081,
    defaultToZip: '76010',
    topInboundOrigins: ['California', 'Illinois', 'Louisiana', 'Oklahoma'],
    avgCostRanges: {
      studio: '$2,600–$5,200',
      twoBR: '$4,800–$7,800',
      threeBR: '$7,000–$10,900',
      fourBR: '$9,900–$14,800',
    },
    inboundGrowthStat: 'DFW entertainment hub · AT&T Stadium corridor · central Tarrant County',
    peakSeasonNote: 'Stadium-event weekends can affect downtown access — plan delivery windows',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Arlington in Tarrant County between Dallas and Fort Worth with DFW spillover demand.',
  },
  {
    slug: 'irving-tx',
    displayName: 'Irving',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['dallas-tx', 'tarrant-tx'],
    lat: 32.814,
    lng: -96.9489,
    defaultToZip: '75038',
    topInboundOrigins: ['California', 'Illinois', 'New York', 'Florida'],
    avgCostRanges: {
      studio: '$2,700–$5,300',
      twoBR: '$5,000–$8,000',
      threeBR: '$7,300–$11,200',
      fourBR: '$10,400–$15,500',
    },
    inboundGrowthStat: 'Las Colinas corporate corridor · DFW Airport adjacency · diverse suburbs',
    peakSeasonNote: 'High-rise Las Colinas buildings may require COI and elevator reservations',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Irving in Dallas County with Las Colinas corporate corridor and DFW Airport proximity.',
  },
  {
    slug: 'grand-prairie-tx',
    displayName: 'Grand Prairie',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['dallas-tx', 'tarrant-tx', 'ellis-tx'],
    lat: 32.746,
    lng: -96.9978,
    defaultToZip: '75050',
    topInboundOrigins: ['California', 'Illinois', 'Louisiana', 'Oklahoma'],
    avgCostRanges: {
      studio: '$2,600–$5,100',
      twoBR: '$4,800–$7,700',
      threeBR: '$7,000–$10,800',
      fourBR: '$9,900–$14,600',
    },
    inboundGrowthStat: 'Value-oriented DFW suburb · family-friendly · Dallas–Tarrant border growth',
    peakSeasonNote: 'Lake-area and new-build streets may need shuttle truck coordination',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Grand Prairie spanning Dallas and Tarrant counties in the central DFW metro.',
  },
  {
    slug: 'lubbock-tx',
    displayName: 'Lubbock',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['lubbock-tx', 'hockley-tx'],
    lat: 33.5779,
    lng: -101.8552,
    defaultToZip: '79401',
    topInboundOrigins: ['California', 'Texas', 'Oklahoma', 'New Mexico'],
    avgCostRanges: {
      studio: '$2,300–$4,600',
      twoBR: '$4,300–$6,900',
      threeBR: '$6,300–$9,800',
      fourBR: '$8,900–$13,200',
    },
    inboundGrowthStat: 'Texas Tech hub · West Texas affordability · prairie lifestyle',
    peakSeasonNote: 'Wind and dust storms can delay loading — confirm weather contingency clauses',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Lubbock in Lubbock County — West Texas university and healthcare anchor city.',
  },
  {
    slug: 'midland-odessa-tx',
    displayName: 'Midland–Odessa',
    stateCode: 'TX',
    stateName: 'Texas',
    primaryCounties: ['midland-tx', 'ector-tx', 'martin-tx'],
    lat: 31.9973,
    lng: -102.0779,
    defaultToZip: '79701',
    topInboundOrigins: ['California', 'Texas', 'Oklahoma', 'Louisiana'],
    avgCostRanges: {
      studio: '$2,500–$5,000',
      twoBR: '$4,600–$7,500',
      threeBR: '$6,800–$10,600',
      fourBR: '$9,600–$14,300',
    },
    inboundGrowthStat: 'Permian Basin energy corridor · job growth · housing demand cycles',
    peakSeasonNote: 'Energy-sector boom cycles tighten housing and carrier availability',
    clusterParent: 'texas',
    priority: 4,
    mapDescription:
      'Midland and Odessa in the Permian Basin spanning Midland, Ector, and Martin counties.',
  },
  {
    slug: 'greenville-spartanburg',
    displayName: 'Greenville–Spartanburg',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['greenville-sc', 'spartanburg-sc', 'anderson-sc'],
    lat: 34.8526,
    lng: -82.394,
    defaultToZip: '29601',
    topInboundOrigins: ['New York', 'New Jersey', 'Florida', 'Ohio'],
    avgCostRanges: {
      studio: '$2,500–$4,900',
      twoBR: '$4,600–$7,500',
      threeBR: '$6,800–$10,600',
      fourBR: '$9,600–$14,500',
    },
    inboundGrowthStat: 'Upstate SC manufacturing and logistics growth corridor',
    peakSeasonNote: 'Affordable alternative to Charlotte — book early in summer',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Greenville and Spartanburg counties in South Carolina\'s Upstate with Anderson County links.',
  },
  {
    slug: 'hilton-head',
    displayName: 'Hilton Head',
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryCounties: ['beaufort-sc', 'jasper-sc'],
    lat: 32.2163,
    lng: -80.7526,
    defaultToZip: '29928',
    topInboundOrigins: ['New York', 'New Jersey', 'Ohio', 'Pennsylvania'],
    avgCostRanges: {
      studio: '$3,000–$5,800',
      twoBR: '$5,600–$9,000',
      threeBR: '$8,200–$12,600',
      fourBR: '$11,600–$17,500',
    },
    inboundGrowthStat: 'Premium island and Lowcountry retiree destination',
    peakSeasonNote: 'Gated communities and bridge access may require shuttle service',
    clusterParent: 'south-carolina',
    priority: 1,
    mapDescription:
      'Hilton Head Island and Beaufort County with Jasper County links for Lowcountry South Carolina moves.',
  },
  {
    slug: 'north-carolina',
    displayName: 'North Carolina',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: [],
    lat: 35.5,
    lng: -79.5,
    defaultToZip: '28202',
    topInboundOrigins: ['New York', 'New Jersey', 'California', 'Florida'],
    avgCostRanges: {
      studio: '$2,700–$5,400',
      twoBR: '$5,000–$8,200',
      threeBR: '$7,300–$11,500',
      fourBR: '$10,400–$16,000',
    },
    inboundGrowthStat: 'Top growth state · banking/tech/biotech · coast to mountains',
    peakSeasonNote: 'Banking and tech hiring cycles drive spring/fall relocation peaks',
    isClusterParent: true,
    priority: 5,
    mapDescription:
      'North Carolina inbound hub covering Charlotte, Research Triangle, Lake Norman, coastal Wilmington, and foothills Hickory.',
  },
  {
    slug: 'charlotte-nc',
    displayName: 'Charlotte',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['mecklenburg-nc', 'union-nc', 'gaston-nc'],
    lat: 35.2271,
    lng: -80.8431,
    defaultToZip: '28202',
    topInboundOrigins: ['New York', 'New Jersey', 'Florida', 'California'],
    avgCostRanges: {
      studio: '$2,700–$5,300',
      twoBR: '$5,000–$8,100',
      threeBR: '$7,300–$11,400',
      fourBR: '$10,400–$15,800',
    },
    inboundGrowthStat: 'Largest NC city · banking center · corporate jobs · lakefront suburbs',
    peakSeasonNote: 'Uptown high-rises and suburban new builds both need access planning',
    clusterParent: 'north-carolina',
    priority: 5,
    mapDescription:
      'Charlotte and Mecklenburg County with Union and Gaston counties for greater Charlotte relocations.',
  },
  {
    slug: 'raleigh-durham-nc',
    displayName: 'Raleigh & Durham',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['wake-nc', 'durham-nc', 'orange-nc'],
    lat: 35.7796,
    lng: -78.6382,
    defaultToZip: '27601',
    topInboundOrigins: ['New York', 'New Jersey', 'California', 'Florida'],
    avgCostRanges: {
      studio: '$2,800–$5,500',
      twoBR: '$5,200–$8,400',
      threeBR: '$7,600–$11,800',
      fourBR: '$10,800–$16,200',
    },
    inboundGrowthStat: 'Research Triangle · tech/biotech · young professionals · top schools',
    peakSeasonNote: 'University and tech hiring cycles peak late spring',
    clusterParent: 'north-carolina',
    priority: 5,
    mapDescription:
      'Raleigh, Durham, and Chapel Hill in the Research Triangle with Wake, Durham, and Orange counties.',
  },
  {
    slug: 'wendell-zebulon-nc',
    displayName: 'Wendell & Zebulon',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['wake-nc', 'johnston-nc'],
    lat: 35.781,
    lng: -78.3698,
    defaultToZip: '27591',
    topInboundOrigins: ['New York', 'New Jersey', 'Florida', 'California'],
    avgCostRanges: {
      studio: '$2,700–$5,200',
      twoBR: '$5,000–$8,000',
      threeBR: '$7,300–$11,300',
      fourBR: '$10,300–$15,500',
    },
    inboundGrowthStat: 'Fastest-growing Wake County municipalities · Wendell Falls mega-developments',
    peakSeasonNote: 'New-build communities may have narrow streets — confirm truck access',
    clusterParent: 'north-carolina',
    priority: 5,
    mapDescription:
      'Wendell and Zebulon in eastern Wake County — fastest-growing Triangle spillover corridor.',
  },
  {
    slug: 'apex-fuquay-varina-nc',
    displayName: 'Apex & Fuquay-Varina',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['wake-nc', 'chatham-nc'],
    lat: 35.7327,
    lng: -78.8503,
    defaultToZip: '27502',
    topInboundOrigins: ['New York', 'New Jersey', 'California', 'Florida'],
    avgCostRanges: {
      studio: '$2,750–$5,300',
      twoBR: '$5,100–$8,200',
      threeBR: '$7,500–$11,600',
      fourBR: '$10,600–$15,900',
    },
    inboundGrowthStat: 'Southwest Wake growth · top safety ratings · schools · Triangle proximity',
    peakSeasonNote: 'Master-planned subdivisions may require HOA move-day scheduling',
    clusterParent: 'north-carolina',
    priority: 5,
    mapDescription:
      'Apex and Fuquay-Varina in southwest Wake County — family-oriented Triangle suburbs.',
  },
  {
    slug: 'mooresville-nc',
    displayName: 'Mooresville',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['iredell-nc', 'mecklenburg-nc'],
    lat: 35.5849,
    lng: -80.8101,
    defaultToZip: '28115',
    topInboundOrigins: ['New York', 'New Jersey', 'Florida', 'Ohio'],
    avgCostRanges: {
      studio: '$2,650–$5,200',
      twoBR: '$4,900–$7,900',
      threeBR: '$7,200–$11,200',
      fourBR: '$10,200–$15,300',
    },
    inboundGrowthStat: 'Lake Norman lifestyle · easy Charlotte commute · family lakefront appeal',
    peakSeasonNote: 'Lakefront and peninsula homes may need shuttle truck coordination',
    clusterParent: 'north-carolina',
    priority: 5,
    mapDescription:
      'Mooresville on Lake Norman in Iredell County with Charlotte metro spillover demand.',
  },
  {
    slug: 'wilmington-leland-nc',
    displayName: 'Wilmington & Leland',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['new-hanover-nc', 'brunswick-nc', 'pender-nc'],
    lat: 34.2257,
    lng: -77.9447,
    defaultToZip: '28401',
    topInboundOrigins: ['New York', 'New Jersey', 'Virginia', 'Ohio'],
    avgCostRanges: {
      studio: '$2,900–$5,600',
      twoBR: '$5,400–$8,600',
      threeBR: '$7,900–$12,100',
      fourBR: '$11,200–$16,800',
    },
    inboundGrowthStat: 'Coastal NC port city · Leland spillover · large-scale master-planned growth',
    peakSeasonNote: 'Hurricane season and beach-access properties require early planning',
    clusterParent: 'north-carolina',
    priority: 5,
    mapDescription:
      'Wilmington and Leland spanning New Hanover and Brunswick counties on coastal North Carolina.',
  },
  {
    slug: 'hickory-nc',
    displayName: 'Hickory',
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryCounties: ['catawba-nc', 'burke-nc', 'alexander-nc'],
    lat: 35.7332,
    lng: -81.3412,
    defaultToZip: '28601',
    topInboundOrigins: ['Florida', 'New York', 'Ohio', 'Georgia'],
    avgCostRanges: {
      studio: '$2,400–$4,700',
      twoBR: '$4,400–$7,100',
      threeBR: '$6,400–$10,000',
      fourBR: '$9,100–$13,600',
    },
    inboundGrowthStat: 'Blue Ridge foothills · affordable Charlotte alternative · mountain access',
    peakSeasonNote: 'Mountain terrain may require smaller shuttle trucks at destination',
    clusterParent: 'north-carolina',
    priority: 5,
    mapDescription:
      'Hickory and Catawba County in the North Carolina foothills with Burke and Alexander county links.',
  },
  {
    slug: 'boise-id',
    displayName: 'Boise',
    stateCode: 'ID',
    stateName: 'Idaho',
    primaryCounties: ['ada-id', 'canyon-id', 'gem-id'],
    lat: 43.615,
    lng: -116.2023,
    defaultToZip: '83702',
    topInboundOrigins: ['California', 'Washington', 'Oregon', 'Texas'],
    avgCostRanges: {
      studio: '$3,400–$6,200',
      twoBR: '$6,200–$9,500',
      threeBR: '$9,000–$13,500',
      fourBR: '$12,800–$19,000',
    },
    inboundGrowthStat: 'Top western inbound ratio driven by CA outmigration',
    peakSeasonNote: 'Summer is peak season; winter weather can delay cross-country delivery',
    priority: 6,
    mapDescription:
      'Boise and Ada County in Idaho\'s Treasure Valley with Canyon and Gem county links.',
  },
  {
    slug: 'eugene-springfield-or',
    displayName: 'Eugene–Springfield',
    stateCode: 'OR',
    stateName: 'Oregon',
    primaryCounties: ['lane-or'],
    lat: 44.0521,
    lng: -123.0868,
    defaultToZip: '97401',
    topInboundOrigins: ['California', 'Washington', 'Texas', 'Colorado'],
    avgCostRanges: {
      studio: '$3,200–$6,000',
      twoBR: '$5,900–$9,200',
      threeBR: '$8,600–$13,000',
      fourBR: '$12,200–$18,200',
    },
    inboundGrowthStat: 'Willamette Valley lifestyle market with university and tech spillover',
    peakSeasonNote: 'Rainy-season loading requires covered truck access planning',
    priority: 7,
    mapDescription:
      'Eugene and Springfield in Lane County, Oregon\'s Willamette Valley corridor.',
  },
  {
    slug: 'tulsa-ok',
    displayName: 'Tulsa',
    stateCode: 'OK',
    stateName: 'Oklahoma',
    primaryCounties: ['tulsa-ok', 'wagoner-ok', 'creek-ok'],
    lat: 36.154,
    lng: -95.9928,
    defaultToZip: '74103',
    topInboundOrigins: ['Texas', 'California', 'Colorado', 'Missouri'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,500–$7,200',
      threeBR: '$6,500–$10,200',
      fourBR: '$9,200–$13,800',
    },
    inboundGrowthStat: 'Affordable mid-size metro with energy and aerospace hiring',
    peakSeasonNote: 'Tornado season awareness — confirm carrier contingency policies',
    priority: 8,
    mapDescription:
      'Tulsa and Tulsa County in northeast Oklahoma with Wagoner and Creek county links.',
  },
  {
    slug: 'phoenix-az',
    displayName: 'Phoenix',
    stateCode: 'AZ',
    stateName: 'Arizona',
    primaryCounties: ['maricopa-az', 'pinal-az'],
    lat: 33.4484,
    lng: -112.074,
    defaultToZip: '85004',
    topInboundOrigins: ['California', 'Illinois', 'Washington', 'Texas'],
    avgCostRanges: {
      studio: '$2,800–$5,600',
      twoBR: '$5,200–$8,500',
      threeBR: '$7,600–$11,900',
      fourBR: '$10,800–$16,500',
    },
    inboundGrowthStat: 'Sunbelt leader for CA and Midwest inbound volume',
    peakSeasonNote: 'Summer heat limits loading hours — schedule early-morning crews',
    priority: 9,
    mapDescription:
      'Phoenix and Maricopa County in the Valley of the Sun with Pinal County suburb links.',
  },
  {
    slug: 'little-rock-ar',
    displayName: 'Little Rock',
    stateCode: 'AR',
    stateName: 'Arkansas',
    primaryCounties: ['pulaski-ar', 'saline-ar', 'lonoke-ar'],
    lat: 34.7465,
    lng: -92.2896,
    defaultToZip: '72201',
    topInboundOrigins: ['Texas', 'California', 'Tennessee', 'Missouri'],
    avgCostRanges: {
      studio: '$2,300–$4,600',
      twoBR: '$4,200–$6,900',
      threeBR: '$6,200–$9,800',
      fourBR: '$8,800–$13,200',
    },
    inboundGrowthStat: 'State capital with healthcare and government-sector relocations',
    peakSeasonNote: 'Affordable market — fewer carriers may serve AR directly; book early',
    priority: 10,
    mapDescription:
      'Little Rock and Pulaski County in central Arkansas with Saline and Lonoke county links.',
  },
  {
    slug: 'birmingham-al',
    displayName: 'Birmingham',
    stateCode: 'AL',
    stateName: 'Alabama',
    primaryCounties: ['jefferson-al', 'shelby-al', 'st-clair-al'],
    lat: 33.5186,
    lng: -86.8104,
    defaultToZip: '35203',
    topInboundOrigins: ['Georgia', 'Florida', 'Texas', 'California'],
    avgCostRanges: {
      studio: '$2,400–$4,800',
      twoBR: '$4,400–$7,200',
      threeBR: '$6,500–$10,200',
      fourBR: '$9,200–$13,800',
    },
    inboundGrowthStat: 'Healthcare and finance hub for southeastern inbound moves',
    peakSeasonNote: 'Hilly terrain in suburbs may affect truck access',
    priority: 11,
    mapDescription:
      'Birmingham and Jefferson County in central Alabama with Shelby and St. Clair county links.',
  },
  {
    slug: 'huntsville-al',
    displayName: 'Huntsville',
    stateCode: 'AL',
    stateName: 'Alabama',
    primaryCounties: ['madison-al', 'limestone-al', 'morgan-al'],
    lat: 34.7304,
    lng: -86.5861,
    defaultToZip: '35801',
    topInboundOrigins: ['California', 'Texas', 'Florida', 'Georgia'],
    avgCostRanges: {
      studio: '$2,500–$5,000',
      twoBR: '$4,600–$7,500',
      threeBR: '$6,800–$10,600',
      fourBR: '$9,600–$14,500',
    },
    inboundGrowthStat: 'Defense and aerospace corridor with sustained tech inbound flow',
    peakSeasonNote: 'Redstone Arsenal area moves may require security clearance coordination',
    priority: 12,
    mapDescription:
      'Huntsville and Madison County in north Alabama with Limestone and Morgan county links.',
  },
];

export function getMarketBySlug(slug: string): Market | undefined {
  return markets.find((market) => market.slug === slug);
}

export function getClusterMarkets(cluster: string): Market[] {
  return markets.filter((market) => market.clusterParent === cluster);
}

/** Sub-cities for cluster cards and nav — stable alphabetical order. */
export function getSortedClusterMarkets(cluster: string): Market[] {
  return getClusterMarkets(cluster).sort((a, b) =>
    a.displayName.localeCompare(b.displayName)
  );
}

export function getMarketPath(market: Market): string {
  if (market.isClusterParent) {
    return `/moving-to/${market.slug}`;
  }
  if (market.clusterParent) {
    return `/moving-to/${market.clusterParent}/${market.slug}`;
  }
  return `/moving-to/${market.slug}`;
}

export const priorityMarketsForNav = [...markets].sort((a, b) => {
  if (a.priority !== b.priority) return a.priority - b.priority;
  if (a.isClusterParent && !b.isClusterParent) return -1;
  if (!a.isClusterParent && b.isClusterParent) return 1;
  return a.displayName.localeCompare(b.displayName);
});

export function getStandaloneAndClusterParentMarkets(): Market[] {
  return markets.filter((market) => market.isClusterParent || !market.clusterParent);
}