import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Alabama counties */
export const alabamaCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  jefferson: { seat: 'Birmingham', metro: 'birmingham-metro-al' },
  madison: { seat: 'Huntsville', metro: 'huntsville-metro-al' },
  mobile: { seat: 'Mobile', metro: 'mobile-metro-al' },
  baldwin: { seat: 'Bay Minette', metro: 'baldwin-coastal-al' },
  tuscaloosa: { seat: 'Tuscaloosa', metro: 'tuscaloosa-metro-al' },
  shelby: { seat: 'Columbiana', metro: 'birmingham-metro-al' },
  montgomery: { seat: 'Montgomery', metro: 'montgomery-metro-al' },
  lee: { seat: 'Opelika', metro: 'auburn-opelika-metro-al' },
  limestone: { seat: 'Athens', metro: 'huntsville-metro-al' },
  morgan: { seat: 'Decatur', metro: 'decatur-metro-al' },
  calhoun: { seat: 'Anniston', metro: 'anniston-metro-al' },
  houston: { seat: 'Dothan', metro: 'dothan-metro-al' },
  etowah: { seat: 'Gadsden', metro: 'gadsden-metro-al' },
  marshall: { seat: 'Guntersville', metro: 'marshall-lakes-al' },
  'st-clair': { seat: 'Pell City', metro: 'birmingham-metro-al' },
  lauderdale: { seat: 'Florence', metro: 'florence-shoals-metro-al' },
  cullman: { seat: 'Cullman', metro: 'cullman-metro-al' },
  elmore: { seat: 'Wetumpka', metro: 'montgomery-metro-al' },
  talladega: { seat: 'Talladega', metro: 'talladega-metro-al' },
  dekalb: { seat: 'Fort Payne', metro: 'fort-payne-metro-al' },
  walker: { seat: 'Jasper', metro: 'jasper-metro-al' },
  autauga: { seat: 'Prattville', metro: 'montgomery-metro-al' },
  blount: { seat: 'Oneonta', metro: 'birmingham-metro-al' },
  colbert: { seat: 'Tuscumbia', metro: 'florence-shoals-metro-al' },
  russell: { seat: 'Phenix City', metro: 'phenix-city-metro-al' },
  coffee: { seat: 'Elba', metro: 'wiregrass-metro-al' },
  jackson: { seat: 'Scottsboro', metro: 'scottsboro-metro-al' },
  dale: { seat: 'Ozark', metro: 'wiregrass-metro-al' },
  chilton: { seat: 'Clanton', metro: 'clanton-metro-al' },
  tallapoosa: { seat: 'Dadeville', metro: 'alexander-city-metro-al' },
  covington: { seat: 'Andalusia', metro: 'andalusia-metro-al' },
  escambia: { seat: 'Brewton', metro: 'brewton-metro-al' },
  dallas: { seat: 'Selma', metro: 'selma-metro-al' },
  chambers: { seat: 'LaFayette', metro: 'valley-metro-al' },
  pike: { seat: 'Troy', metro: 'wiregrass-metro-al' },
  lawrence: { seat: 'Moulton', metro: 'moulton-metro-al' },
  franklin: { seat: 'Russellville', metro: 'russellville-metro-al' },
  marion: { seat: 'Hamilton', metro: 'hamilton-metro-al' },
  geneva: { seat: 'Geneva', metro: 'geneva-metro-al' },
  cherokee: { seat: 'Centre', metro: 'centre-metro-al' },
  barbour: { seat: 'Clayton', metro: 'eufaula-metro-al' },
  winston: { seat: 'Double Springs', metro: 'double-springs-metro-al' },
  randolph: { seat: 'Wedowee', metro: 'wedowee-metro-al' },
  bibb: { seat: 'Centreville', metro: 'centreville-metro-al' },
  clarke: { seat: 'Grove Hill', metro: 'grove-hill-metro-al' },
  monroe: { seat: 'Monroeville', metro: 'monroeville-metro-al' },
  henry: { seat: 'Abbeville', metro: 'abbeville-metro-al' },
  marengo: { seat: 'Linden', metro: 'linden-metro-al' },
  macon: { seat: 'Tuskegee', metro: 'tuskegee-metro-al' },
  pickens: { seat: 'Carrollton', metro: 'carrollton-metro-al' },
  butler: { seat: 'Greenville', metro: 'greenville-metro-al' },
  cleburne: { seat: 'Heflin', metro: 'heflin-metro-al' },
  fayette: { seat: 'Fayette', metro: 'fayette-metro-al' },
  hale: { seat: 'Greensboro', metro: 'greensboro-metro-al' },
  washington: { seat: 'Chatom', metro: 'chatom-metro-al' },
  clay: { seat: 'Ashland', metro: 'ashland-metro-al' },
  lamar: { seat: 'Vernon', metro: 'vernon-metro-al' },
  crenshaw: { seat: 'Luverne', metro: 'luverne-metro-al' },
  choctaw: { seat: 'Butler', metro: 'choctaw-metro-al' },
  sumter: { seat: 'Livingston', metro: 'livingston-metro-al' },
  conecuh: { seat: 'Evergreen', metro: 'evergreen-metro-al' },
  coosa: { seat: 'Rockford', metro: 'rockford-metro-al' },
  bullock: { seat: 'Union Springs', metro: 'union-springs-metro-al' },
  wilcox: { seat: 'Camden', metro: 'camden-metro-al' },
  lowndes: { seat: 'Hayneville', metro: 'hayneville-metro-al' },
  perry: { seat: 'Marion', metro: 'perry-metro-al' },
  greene: { seat: 'Eutaw', metro: 'eutaw-metro-al' },
};

export function applyAlabamaCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'alabama') return county;
  const override = alabamaCountyOverrides[county.slug];
  return override ? { ...county, ...override } : county;
}