import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Arkansas counties */
export const arkansasCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  pulaski: { seat: 'Little Rock', metro: 'little-rock-metro-ar' },
  benton: { seat: 'Bentonville', metro: 'northwest-arkansas-metro-ar' },
  washington: { seat: 'Fayetteville', metro: 'northwest-arkansas-metro-ar' },
  faulkner: { seat: 'Conway', metro: 'little-rock-metro-ar' },
  saline: { seat: 'Benton', metro: 'little-rock-metro-ar' },
  sebastian: { seat: 'Fort Smith', metro: 'fort-smith-metro-ar' },
  craighead: { seat: 'Jonesboro', metro: 'jonesboro-metro-ar' },
  garland: { seat: 'Hot Springs', metro: 'hot-springs-metro-ar' },
  white: { seat: 'Searcy', metro: 'searcy-metro-ar' },
  lonoke: { seat: 'Lonoke', metro: 'little-rock-metro-ar' },
  pope: { seat: 'Russellville', metro: 'russellville-metro-ar' },
  crawford: { seat: 'Van Buren', metro: 'fort-smith-metro-ar' },
  jefferson: { seat: 'Pine Bluff', metro: 'pine-bluff-metro-ar' },
  greene: { seat: 'Paragould', metro: 'paragould-metro-ar' },
  crittenden: { seat: 'Marion', metro: 'west-memphis-metro-ar' },
  baxter: { seat: 'Mountain Home', metro: 'mountain-home-metro-ar' },
  miller: { seat: 'Texarkana', metro: 'texarkana-metro-ar' },
  independence: { seat: 'Batesville', metro: 'batesville-metro-ar' },
  boone: { seat: 'Harrison', metro: 'harrison-metro-ar' },
  mississippi: { seat: 'Blytheville', metro: 'blytheville-metro-ar' },
  union: { seat: 'El Dorado', metro: 'el-dorado-metro-ar' },
  'hot-spring': { seat: 'Malvern', metro: 'malvern-metro-ar' },
  carroll: { seat: 'Berryville', metro: 'berryville-metro-ar' },
  johnson: { seat: 'Clarksville', metro: 'clarksville-metro-ar' },
  cleburne: { seat: 'Heber Springs', metro: 'heber-springs-metro-ar' },
  poinsett: { seat: 'Harrisburg', metro: 'harrisburg-metro-ar' },
  columbia: { seat: 'Magnolia', metro: 'magnolia-metro-ar' },
  logan: { seat: 'Paris', metro: 'paris-metro-ar' },
  'st-francis': { seat: 'Forrest City', metro: 'forrest-city-metro-ar' },
  ouachita: { seat: 'Camden', metro: 'camden-metro-ar' },
  conway: { seat: 'Morrilton', metro: 'morrilton-metro-ar' },
  clark: { seat: 'Arkadelphia', metro: 'arkadelphia-metro-ar' },
  yell: { seat: 'Danville', metro: 'danville-metro-ar' },
  polk: { seat: 'Mena', metro: 'mena-metro-ar' },
  grant: { seat: 'Sheridan', metro: 'little-rock-metro-ar' },
  hempstead: { seat: 'Hope', metro: 'hope-metro-ar' },
  randolph: { seat: 'Pocahontas', metro: 'pocahontas-metro-ar' },
  madison: { seat: 'Huntsville', metro: 'huntsville-metro-ar' },
  sharp: { seat: 'Ash Flat', metro: 'ash-flat-metro-ar' },
  franklin: { seat: 'Ozark', metro: 'ozark-metro-ar' },
  ashley: { seat: 'Hamburg', metro: 'hamburg-metro-ar' },
  marion: { seat: 'Yellville', metro: 'yellville-metro-ar' },
  drew: { seat: 'Monticello', metro: 'monticello-metro-ar' },
  jackson: { seat: 'Newport', metro: 'newport-metro-ar' },
  lawrence: { seat: 'Walnut Ridge', metro: 'walnut-ridge-metro-ar' },
  'van-buren': { seat: 'Clinton', metro: 'clinton-metro-ar' },
  cross: { seat: 'Wynne', metro: 'wynne-metro-ar' },
  sevier: { seat: 'De Queen', metro: 'de-queen-metro-ar' },
  arkansas: { seat: 'DeWitt', metro: 'dewitt-metro-ar' },
  izard: { seat: 'Melbourne', metro: 'melbourne-metro-ar' },
  clay: { seat: 'Corning', metro: 'corning-metro-ar' },
  phillips: { seat: 'Helena-West Helena', metro: 'helena-west-helena-metro-ar' },
  stone: { seat: 'Mountain View', metro: 'mountain-view-metro-ar' },
  lincoln: { seat: 'Star City', metro: 'star-city-metro-ar' },
  fulton: { seat: 'Salem', metro: 'salem-metro-ar' },
  howard: { seat: 'Nashville', metro: 'nashville-metro-ar' },
  'little-river': { seat: 'Ashdown', metro: 'ashdown-metro-ar' },
  perry: { seat: 'Perryville', metro: 'perryville-metro-ar' },
  scott: { seat: 'Waldron', metro: 'waldron-metro-ar' },
  pike: { seat: 'Murfreesboro', metro: 'murfreesboro-metro-ar' },
  desha: { seat: 'Arkansas City', metro: 'arkansas-city-metro-ar' },
  bradley: { seat: 'Warren', metro: 'warren-metro-ar' },
  chicot: { seat: 'Lake Village', metro: 'lake-village-metro-ar' },
  montgomery: { seat: 'Mount Ida', metro: 'mount-ida-metro-ar' },
  lee: { seat: 'Marianna', metro: 'marianna-metro-ar' },
  prairie: { seat: 'Des Arc', metro: 'des-arc-metro-ar' },
  nevada: { seat: 'Prescott', metro: 'prescott-metro-ar' },
  searcy: { seat: 'Marshall', metro: 'marshall-metro-ar' },
  cleveland: { seat: 'Rison', metro: 'rison-metro-ar' },
  newton: { seat: 'Jasper', metro: 'jasper-metro-ar' },
  monroe: { seat: 'Clarendon', metro: 'clarendon-metro-ar' },
  dallas: { seat: 'Fordyce', metro: 'fordyce-metro-ar' },
  lafayette: { seat: 'Lewisville', metro: 'lewisville-metro-ar' },
  woodruff: { seat: 'Augusta', metro: 'augusta-metro-ar' },
  calhoun: { seat: 'Hampton', metro: 'hampton-metro-ar' },
};

export function applyArkansasCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'arkansas') return county;
  const override = arkansasCountyOverrides[county.slug];
  return override ? { ...county, ...override } : county;
}