import type { LocalCounty } from '@/lib/local-movers/types';

const CA = 'california';
const CODE = 'CA';

/** All 58 California counties — slug matches URL segment */
export const californiaCounties: LocalCounty[] = [
  { slug: 'alameda', name: 'Alameda', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'Oakland' },
  { slug: 'alpine', name: 'Alpine', stateCode: CODE, stateSlug: CA, metro: 'sierra-rural-ca', seat: 'Markleeville' },
  { slug: 'amador', name: 'Amador', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'Jackson' },
  { slug: 'butte', name: 'Butte', stateCode: CODE, stateSlug: CA, metro: 'chico-metro-ca', seat: 'Oroville' },
  { slug: 'calaveras', name: 'Calaveras', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'San Andreas' },
  { slug: 'colusa', name: 'Colusa', stateCode: CODE, stateSlug: CA, metro: 'northern-valley-ca', seat: 'Colusa' },
  { slug: 'contra-costa', name: 'Contra Costa', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'Martinez' },
  { slug: 'del-norte', name: 'Del Norte', stateCode: CODE, stateSlug: CA, metro: 'north-coast-ca', seat: 'Crescent City' },
  { slug: 'el-dorado', name: 'El Dorado', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'Placerville' },
  { slug: 'fresno', name: 'Fresno', stateCode: CODE, stateSlug: CA, metro: 'central-valley-ca', seat: 'Fresno' },
  { slug: 'glenn', name: 'Glenn', stateCode: CODE, stateSlug: CA, metro: 'northern-valley-ca', seat: 'Willows' },
  { slug: 'humboldt', name: 'Humboldt', stateCode: CODE, stateSlug: CA, metro: 'north-coast-ca', seat: 'Eureka' },
  { slug: 'imperial', name: 'Imperial', stateCode: CODE, stateSlug: CA, metro: 'san-diego-ca', seat: 'El Centro' },
  { slug: 'inyo', name: 'Inyo', stateCode: CODE, stateSlug: CA, metro: 'sierra-rural-ca', seat: 'Independence' },
  { slug: 'kern', name: 'Kern', stateCode: CODE, stateSlug: CA, metro: 'bakersfield-metro-ca', seat: 'Bakersfield' },
  { slug: 'kings', name: 'Kings', stateCode: CODE, stateSlug: CA, metro: 'central-valley-ca', seat: 'Hanford' },
  { slug: 'lake', name: 'Lake', stateCode: CODE, stateSlug: CA, metro: 'north-coast-ca', seat: 'Lakeport' },
  { slug: 'lassen', name: 'Lassen', stateCode: CODE, stateSlug: CA, metro: 'northern-valley-ca', seat: 'Susanville' },
  { slug: 'los-angeles', name: 'Los Angeles', stateCode: CODE, stateSlug: CA, metro: 'greater-la-ca', seat: 'Los Angeles' },
  { slug: 'madera', name: 'Madera', stateCode: CODE, stateSlug: CA, metro: 'central-valley-ca', seat: 'Madera' },
  { slug: 'marin', name: 'Marin', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'San Rafael' },
  { slug: 'mariposa', name: 'Mariposa', stateCode: CODE, stateSlug: CA, metro: 'central-valley-ca', seat: 'Mariposa' },
  { slug: 'mendocino', name: 'Mendocino', stateCode: CODE, stateSlug: CA, metro: 'north-coast-ca', seat: 'Ukiah' },
  { slug: 'merced', name: 'Merced', stateCode: CODE, stateSlug: CA, metro: 'central-valley-ca', seat: 'Merced' },
  { slug: 'modoc', name: 'Modoc', stateCode: CODE, stateSlug: CA, metro: 'northern-valley-ca', seat: 'Alturas' },
  { slug: 'mono', name: 'Mono', stateCode: CODE, stateSlug: CA, metro: 'sierra-rural-ca', seat: 'Bridgeport' },
  { slug: 'monterey', name: 'Monterey', stateCode: CODE, stateSlug: CA, metro: 'central-coast-ca', seat: 'Salinas' },
  { slug: 'napa', name: 'Napa', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'Napa' },
  { slug: 'nevada', name: 'Nevada', stateCode: CODE, stateSlug: CA, metro: 'northern-valley-ca', seat: 'Nevada City' },
  { slug: 'orange', name: 'Orange', stateCode: CODE, stateSlug: CA, metro: 'greater-la-ca', seat: 'Santa Ana' },
  { slug: 'placer', name: 'Placer', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'Auburn' },
  { slug: 'plumas', name: 'Plumas', stateCode: CODE, stateSlug: CA, metro: 'northern-valley-ca', seat: 'Quincy' },
  { slug: 'riverside', name: 'Riverside', stateCode: CODE, stateSlug: CA, metro: 'greater-la-ca', seat: 'Riverside' },
  { slug: 'sacramento', name: 'Sacramento', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'Sacramento' },
  { slug: 'san-benito', name: 'San Benito', stateCode: CODE, stateSlug: CA, metro: 'central-coast-ca', seat: 'Hollister' },
  { slug: 'san-bernardino', name: 'San Bernardino', stateCode: CODE, stateSlug: CA, metro: 'greater-la-ca', seat: 'San Bernardino' },
  { slug: 'san-diego', name: 'San Diego', stateCode: CODE, stateSlug: CA, metro: 'san-diego-ca', seat: 'San Diego' },
  { slug: 'san-francisco', name: 'San Francisco', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'San Francisco' },
  { slug: 'san-joaquin', name: 'San Joaquin', stateCode: CODE, stateSlug: CA, metro: 'central-valley-ca', seat: 'Stockton' },
  { slug: 'san-luis-obispo', name: 'San Luis Obispo', stateCode: CODE, stateSlug: CA, metro: 'central-coast-ca', seat: 'San Luis Obispo' },
  { slug: 'san-mateo', name: 'San Mateo', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'Redwood City' },
  { slug: 'santa-barbara', name: 'Santa Barbara', stateCode: CODE, stateSlug: CA, metro: 'central-coast-ca', seat: 'Santa Barbara' },
  { slug: 'santa-clara', name: 'Santa Clara', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'San Jose' },
  { slug: 'santa-cruz', name: 'Santa Cruz', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'Santa Cruz' },
  { slug: 'shasta', name: 'Shasta', stateCode: CODE, stateSlug: CA, metro: 'northern-valley-ca', seat: 'Redding' },
  { slug: 'sierra', name: 'Sierra', stateCode: CODE, stateSlug: CA, metro: 'sierra-rural-ca', seat: 'Downieville' },
  { slug: 'siskiyou', name: 'Siskiyou', stateCode: CODE, stateSlug: CA, metro: 'north-coast-ca', seat: 'Yreka' },
  { slug: 'solano', name: 'Solano', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'Fairfield' },
  { slug: 'sonoma', name: 'Sonoma', stateCode: CODE, stateSlug: CA, metro: 'bay-area-ca', seat: 'Santa Rosa' },
  { slug: 'stanislaus', name: 'Stanislaus', stateCode: CODE, stateSlug: CA, metro: 'central-valley-ca', seat: 'Modesto' },
  { slug: 'sutter', name: 'Sutter', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'Yuba City' },
  { slug: 'tehama', name: 'Tehama', stateCode: CODE, stateSlug: CA, metro: 'northern-valley-ca', seat: 'Red Bluff' },
  { slug: 'trinity', name: 'Trinity', stateCode: CODE, stateSlug: CA, metro: 'north-coast-ca', seat: 'Weaverville' },
  { slug: 'tulare', name: 'Tulare', stateCode: CODE, stateSlug: CA, metro: 'central-valley-ca', seat: 'Visalia' },
  { slug: 'tuolumne', name: 'Tuolumne', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'Sonora' },
  { slug: 'ventura', name: 'Ventura', stateCode: CODE, stateSlug: CA, metro: 'greater-la-ca', seat: 'Ventura' },
  { slug: 'yolo', name: 'Yolo', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'Woodland' },
  { slug: 'yuba', name: 'Yuba', stateCode: CODE, stateSlug: CA, metro: 'sacramento-metro-ca', seat: 'Marysville' },
];