import type { LocalCounty } from '@/lib/local-movers/types';

const FL = 'florida';
const CODE = 'FL';

/** All 67 Florida counties — slug matches URL segment */
export const floridaCounties: LocalCounty[] = [
  { slug: 'alachua', name: 'Alachua', stateCode: CODE, stateSlug: FL, metro: 'north-central-fl', seat: 'Gainesville' },
  { slug: 'baker', name: 'Baker', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'Macclenny' },
  { slug: 'bay', name: 'Bay', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Panama City' },
  { slug: 'bradford', name: 'Bradford', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'Starke' },
  { slug: 'brevard', name: 'Brevard', stateCode: CODE, stateSlug: FL, metro: 'space-coast-fl', seat: 'Titusville' },
  { slug: 'broward', name: 'Broward', stateCode: CODE, stateSlug: FL, metro: 'south-florida', seat: 'Fort Lauderdale' },
  { slug: 'calhoun', name: 'Calhoun', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Blountstown' },
  { slug: 'charlotte', name: 'Charlotte', stateCode: CODE, stateSlug: FL, metro: 'southwest-fl', seat: 'Punta Gorda' },
  { slug: 'citrus', name: 'Citrus', stateCode: CODE, stateSlug: FL, metro: 'nature-coast-fl', seat: 'Inverness' },
  { slug: 'clay', name: 'Clay', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'Green Cove Springs' },
  { slug: 'collier', name: 'Collier', stateCode: CODE, stateSlug: FL, metro: 'southwest-fl', seat: 'Naples' },
  { slug: 'columbia', name: 'Columbia', stateCode: CODE, stateSlug: FL, metro: 'north-central-fl', seat: 'Lake City' },
  { slug: 'desoto', name: 'DeSoto', stateCode: CODE, stateSlug: FL, metro: 'southwest-fl', seat: 'Arcadia' },
  { slug: 'dixie', name: 'Dixie', stateCode: CODE, stateSlug: FL, metro: 'nature-coast-fl', seat: 'Cross City' },
  { slug: 'duval', name: 'Duval', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'Jacksonville' },
  { slug: 'escambia', name: 'Escambia', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Pensacola' },
  { slug: 'flagler', name: 'Flagler', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'Bunnell' },
  { slug: 'franklin', name: 'Franklin', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Apalachicola' },
  { slug: 'gadsden', name: 'Gadsden', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Quincy' },
  { slug: 'gilchrist', name: 'Gilchrist', stateCode: CODE, stateSlug: FL, metro: 'north-central-fl', seat: 'Trenton' },
  { slug: 'glades', name: 'Glades', stateCode: CODE, stateSlug: FL, metro: 'southwest-fl', seat: 'Moore Haven' },
  { slug: 'gulf', name: 'Gulf', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Port St. Joe' },
  { slug: 'hamilton', name: 'Hamilton', stateCode: CODE, stateSlug: FL, metro: 'north-central-fl', seat: 'Jasper' },
  { slug: 'hardee', name: 'Hardee', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Wauchula' },
  { slug: 'hendry', name: 'Hendry', stateCode: CODE, stateSlug: FL, metro: 'southwest-fl', seat: 'LaBelle' },
  { slug: 'hernando', name: 'Hernando', stateCode: CODE, stateSlug: FL, metro: 'tampa-bay', seat: 'Brooksville' },
  { slug: 'highlands', name: 'Highlands', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Sebring' },
  { slug: 'hillsborough', name: 'Hillsborough', stateCode: CODE, stateSlug: FL, metro: 'tampa-bay', seat: 'Tampa' },
  { slug: 'holmes', name: 'Holmes', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Bonifay' },
  { slug: 'indian-river', name: 'Indian River', stateCode: CODE, stateSlug: FL, metro: 'space-coast-fl', seat: 'Vero Beach' },
  { slug: 'jackson', name: 'Jackson', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Marianna' },
  { slug: 'jefferson', name: 'Jefferson', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Monticello' },
  { slug: 'lafayette', name: 'Lafayette', stateCode: CODE, stateSlug: FL, metro: 'north-central-fl', seat: 'Mayo' },
  { slug: 'lake', name: 'Lake', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Tavares' },
  { slug: 'lee', name: 'Lee', stateCode: CODE, stateSlug: FL, metro: 'southwest-fl', seat: 'Fort Myers' },
  { slug: 'leon', name: 'Leon', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Tallahassee' },
  { slug: 'levy', name: 'Levy', stateCode: CODE, stateSlug: FL, metro: 'nature-coast-fl', seat: 'Bronson' },
  { slug: 'liberty', name: 'Liberty', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Bristol' },
  { slug: 'madison', name: 'Madison', stateCode: CODE, stateSlug: FL, metro: 'north-central-fl', seat: 'Madison' },
  { slug: 'manatee', name: 'Manatee', stateCode: CODE, stateSlug: FL, metro: 'tampa-bay', seat: 'Bradenton' },
  { slug: 'marion', name: 'Marion', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Ocala' },
  { slug: 'martin', name: 'Martin', stateCode: CODE, stateSlug: FL, metro: 'south-florida', seat: 'Stuart' },
  { slug: 'miami-dade', name: 'Miami-Dade', stateCode: CODE, stateSlug: FL, metro: 'south-florida', seat: 'Miami' },
  { slug: 'monroe', name: 'Monroe', stateCode: CODE, stateSlug: FL, metro: 'keys-fl', seat: 'Key West' },
  { slug: 'nassau', name: 'Nassau', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'Fernandina Beach' },
  { slug: 'okaloosa', name: 'Okaloosa', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Crestview' },
  { slug: 'okeechobee', name: 'Okeechobee', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Okeechobee' },
  { slug: 'orange', name: 'Orange', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Orlando' },
  { slug: 'osceola', name: 'Osceola', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Kissimmee' },
  { slug: 'palm-beach', name: 'Palm Beach', stateCode: CODE, stateSlug: FL, metro: 'south-florida', seat: 'West Palm Beach' },
  { slug: 'pasco', name: 'Pasco', stateCode: CODE, stateSlug: FL, metro: 'tampa-bay', seat: 'Dade City' },
  { slug: 'pinellas', name: 'Pinellas', stateCode: CODE, stateSlug: FL, metro: 'tampa-bay', seat: 'Clearwater' },
  { slug: 'polk', name: 'Polk', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Bartow' },
  { slug: 'putnam', name: 'Putnam', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'Palatka' },
  { slug: 'santa-rosa', name: 'Santa Rosa', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Milton' },
  { slug: 'sarasota', name: 'Sarasota', stateCode: CODE, stateSlug: FL, metro: 'tampa-bay', seat: 'Sarasota' },
  { slug: 'seminole', name: 'Seminole', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Sanford' },
  { slug: 'st-johns', name: 'St. Johns', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'St. Augustine' },
  { slug: 'st-lucie', name: 'St. Lucie', stateCode: CODE, stateSlug: FL, metro: 'south-florida', seat: 'Fort Pierce' },
  { slug: 'sumter', name: 'Sumter', stateCode: CODE, stateSlug: FL, metro: 'central-florida', seat: 'Bushnell' },
  { slug: 'suwannee', name: 'Suwannee', stateCode: CODE, stateSlug: FL, metro: 'north-central-fl', seat: 'Live Oak' },
  { slug: 'taylor', name: 'Taylor', stateCode: CODE, stateSlug: FL, metro: 'nature-coast-fl', seat: 'Perry' },
  { slug: 'union', name: 'Union', stateCode: CODE, stateSlug: FL, metro: 'north-central-fl', seat: 'Lake Butler' },
  { slug: 'volusia', name: 'Volusia', stateCode: CODE, stateSlug: FL, metro: 'northeast-fl', seat: 'DeLand' },
  { slug: 'wakulla', name: 'Wakulla', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Crawfordville' },
  { slug: 'walton', name: 'Walton', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'DeFuniak Springs' },
  { slug: 'washington', name: 'Washington', stateCode: CODE, stateSlug: FL, metro: 'panhandle-fl', seat: 'Chipley' },
];