import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Georgia counties */
export const georgiaCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  fulton: { seat: 'Atlanta', metro: 'atlanta-metro-ga' },
  gwinnett: { seat: 'Lawrenceville', metro: 'atlanta-metro-ga' },
  cobb: { seat: 'Marietta', metro: 'atlanta-metro-ga' },
  dekalb: { seat: 'Decatur', metro: 'atlanta-metro-ga' },
  clayton: { seat: 'Jonesboro', metro: 'atlanta-metro-ga' },
  cherokee: { seat: 'Canton', metro: 'atlanta-metro-ga' },
  forsyth: { seat: 'Cumming', metro: 'atlanta-metro-ga' },
  henry: { seat: 'McDonough', metro: 'atlanta-metro-ga' },
  fayette: { seat: 'Fayetteville', metro: 'atlanta-metro-ga' },
  douglas: { seat: 'Douglasville', metro: 'atlanta-metro-ga' },
  rockdale: { seat: 'Conyers', metro: 'atlanta-metro-ga' },
  paulding: { seat: 'Dallas', metro: 'atlanta-metro-ga' },
  coweta: { seat: 'Newnan', metro: 'atlanta-metro-ga' },
  barrow: { seat: 'Winder', metro: 'atlanta-metro-ga' },
  newton: { seat: 'Covington', metro: 'atlanta-metro-ga' },
  hall: { seat: 'Gainesville', metro: 'atlanta-metro-ga' },
  walton: { seat: 'Monroe', metro: 'atlanta-metro-ga' },
  chatham: { seat: 'Savannah', metro: 'savannah-metro-ga' },
  richmond: { seat: 'Augusta', metro: 'augusta-metro-ga' },
  columbia: { seat: 'Appling', metro: 'augusta-metro-ga' },
  muscogee: { seat: 'Columbus', metro: 'columbus-metro-ga' },
  pickens: { seat: 'Jasper', metro: 'atlanta-metro-ga' },
  bartow: { seat: 'Cartersville', metro: 'atlanta-metro-ga' },
  spalding: { seat: 'Griffin', metro: 'atlanta-metro-ga' },
  butts: { seat: 'Jackson', metro: 'atlanta-metro-ga' },
  carroll: { seat: 'Carrollton', metro: 'atlanta-metro-ga' },
  dawson: { seat: 'Dawsonville', metro: 'atlanta-metro-ga' },
  lumpkin: { seat: 'Dahlonega', metro: 'atlanta-metro-ga' },
  morgan: { seat: 'Madison', metro: 'athens-metro-ga' },
  oconee: { seat: 'Watkinsville', metro: 'atlanta-metro-ga' },
  jackson: { seat: 'Jefferson', metro: 'atlanta-metro-ga' },
  haralson: { seat: 'Buchanan', metro: 'atlanta-metro-ga' },
  polk: { seat: 'Cedartown', metro: 'atlanta-metro-ga' },
  heard: { seat: 'Franklin', metro: 'atlanta-metro-ga' },
  meriwether: { seat: 'Greenville', metro: 'lagrange-metro-ga' },
  floyd: { seat: 'Rome', metro: 'rome-metro-ga' },
  gordon: { seat: 'Calhoun', metro: 'rome-metro-ga' },
  chattooga: { seat: 'Summerville', metro: 'rome-metro-ga' },
  walker: { seat: 'LaFayette', metro: 'chattanooga-metro-ga' },
  whitfield: { seat: 'Dalton', metro: 'dalton-metro-ga' },
  murray: { seat: 'Chatsworth', metro: 'dalton-metro-ga' },
  catoosa: { seat: 'Ringgold', metro: 'chattanooga-metro-ga' },
  dade: { seat: 'Trenton', metro: 'chattanooga-metro-ga' },
  appling: { seat: 'Baxley', metro: 'savannah-metro-ga' },
  atkinson: { seat: 'Pearson', metro: 'valdosta-metro-ga' },
  bacon: { seat: 'Alma', metro: 'savannah-metro-ga' },
  baker: { seat: 'Newton', metro: 'albany-metro-ga' },
  baldwin: { seat: 'Milledgeville', metro: 'macon-metro-ga' },
  banks: { seat: 'Homer', metro: 'atlanta-metro-ga' },
  berrien: { seat: 'Nashville', metro: 'valdosta-metro-ga' },
  bibb: { seat: 'Macon', metro: 'macon-metro-ga' },
  bleckley: { seat: 'Cochran', metro: 'macon-metro-ga' },
  brantley: { seat: 'Nahunta', metro: 'savannah-metro-ga' },
  houston: { seat: 'Perry', metro: 'macon-metro-ga' },
  lowndes: { seat: 'Valdosta', metro: 'valdosta-metro-ga' },
  bulloch: { seat: 'Statesboro', metro: 'savannah-metro-ga' },
  effingham: { seat: 'Springfield', metro: 'savannah-metro-ga' },
  glynn: { seat: 'Brunswick', metro: 'brunswick-metro-ga' },
  dougherty: { seat: 'Albany', metro: 'albany-metro-ga' },
  troup: { seat: 'LaGrange', metro: 'lagrange-metro-ga' },
  liberty: { seat: 'Hinesville', metro: 'savannah-metro-ga' },
  camden: { seat: 'Woodbine', metro: 'brunswick-metro-ga' },
  bryan: { seat: 'Pembroke', metro: 'savannah-metro-ga' },
  laurens: { seat: 'Dublin', metro: 'macon-metro-ga' },
  habersham: { seat: 'Clarkesville', metro: 'atlanta-metro-ga' },
  colquitt: { seat: 'Moultrie', metro: 'albany-metro-ga' },
  thomas: { seat: 'Thomasville', metro: 'valdosta-metro-ga' },
  lee: { seat: 'Leesburg', metro: 'albany-metro-ga' },
  gilmer: { seat: 'Ellijay', metro: 'atlanta-metro-ga' },
  madison: { seat: 'Danielsville', metro: 'athens-metro-ga' },
  wayne: { seat: 'Jesup', metro: 'savannah-metro-ga' },
  monroe: { seat: 'Forsyth', metro: 'macon-metro-ga' },
  peach: { seat: 'Fort Valley', metro: 'macon-metro-ga' },
  white: { seat: 'Cleveland', metro: 'atlanta-metro-ga' },
  decatur: { seat: 'Bainbridge', metro: 'albany-metro-ga' },
  jones: { seat: 'Gray', metro: 'macon-metro-ga' },
  hart: { seat: 'Hartwell', metro: 'athens-metro-ga' },
  upson: { seat: 'Thomaston', metro: 'macon-metro-ga' },
  sumter: { seat: 'Americus', metro: 'albany-metro-ga' },
  stephens: { seat: 'Toccoa', metro: 'athens-metro-ga' },
  union: { seat: 'Blairsville', metro: 'atlanta-metro-ga' },
  toombs: { seat: 'Lyons', metro: 'savannah-metro-ga' },
  grady: { seat: 'Cairo', metro: 'valdosta-metro-ga' },
  franklin: { seat: 'Carnesville', metro: 'athens-metro-ga' },
  fannin: { seat: 'Blue Ridge', metro: 'chattanooga-metro-ga' },
  burke: { seat: 'Waynesboro', metro: 'augusta-metro-ga' },
  tattnall: { seat: 'Reidsville', metro: 'savannah-metro-ga' },
  putnam: { seat: 'Eatonton', metro: 'macon-metro-ga' },
  emanuel: { seat: 'Swainsboro', metro: 'savannah-metro-ga' },
  long: { seat: 'Ludowici', metro: 'savannah-metro-ga' },
  greene: { seat: 'Greensboro', metro: 'macon-metro-ga' },
  mcduffie: { seat: 'Thomson', metro: 'augusta-metro-ga' },
  lamar: { seat: 'Barnesville', metro: 'atlanta-metro-ga' },
  pike: { seat: 'Zebulon', metro: 'atlanta-metro-ga' },
  pierce: { seat: 'Blackshear', metro: 'savannah-metro-ga' },
  mitchell: { seat: 'Camilla', metro: 'albany-metro-ga' },
  elbert: { seat: 'Elberton', metro: 'athens-metro-ga' },
  worth: { seat: 'Sylvester', metro: 'albany-metro-ga' },
  dodge: { seat: 'Eastman', metro: 'macon-metro-ga' },
  washington: { seat: 'Sandersville', metro: 'macon-metro-ga' },
  crisp: { seat: 'Cordele', metro: 'valdosta-metro-ga' },
  cook: { seat: 'Adel', metro: 'valdosta-metro-ga' },
  jasper: { seat: 'Monticello', metro: 'atlanta-metro-ga' },
  rabun: { seat: 'Clayton', metro: 'atlanta-metro-ga' },
  'ben-hill': { seat: 'Fitzgerald', metro: 'valdosta-metro-ga' },
  oglethorpe: { seat: 'Lexington', metro: 'athens-metro-ga' },
  brooks: { seat: 'Quitman', metro: 'valdosta-metro-ga' },
  'jeff-davis': { seat: 'Hazlehurst', metro: 'savannah-metro-ga' },
  jefferson: { seat: 'Louisville', metro: 'augusta-metro-ga' },
  screven: { seat: 'Sylvania', metro: 'savannah-metro-ga' },
  towns: { seat: 'Hiawassee', metro: 'atlanta-metro-ga' },
  charlton: { seat: 'Folkston', metro: 'brunswick-metro-ga' },
  mcintosh: { seat: 'Darien', metro: 'brunswick-metro-ga' },
  crawford: { seat: 'Knoxville', metro: 'macon-metro-ga' },
  macon: { seat: 'Oglethorpe', metro: 'macon-metro-ga' },
  candler: { seat: 'Metter', metro: 'savannah-metro-ga' },
  telfair: { seat: 'McRae-Helena', metro: 'savannah-metro-ga' },
  dooly: { seat: 'Vienna', metro: 'macon-metro-ga' },
  evans: { seat: 'Claxton', metro: 'savannah-metro-ga' },
  lanier: { seat: 'Lakeland', metro: 'valdosta-metro-ga' },
  early: { seat: 'Blakely', metro: 'albany-metro-ga' },
  pulaski: { seat: 'Hawkinsville', metro: 'macon-metro-ga' },
  wilkes: { seat: 'Washington', metro: 'athens-metro-ga' },
  johnson: { seat: 'Wrightsville', metro: 'macon-metro-ga' },
  seminole: { seat: 'Donalsonville', metro: 'albany-metro-ga' },
  turner: { seat: 'Ashburn', metro: 'valdosta-metro-ga' },
  irwin: { seat: 'Ocilla', metro: 'valdosta-metro-ga' },
  jenkins: { seat: 'Millen', metro: 'savannah-metro-ga' },
  wilcox: { seat: 'Abbeville', metro: 'valdosta-metro-ga' },
  montgomery: { seat: 'Mount Vernon', metro: 'savannah-metro-ga' },
  hancock: { seat: 'Sparta', metro: 'macon-metro-ga' },
  wilkinson: { seat: 'Irwinton', metro: 'macon-metro-ga' },
  wheeler: { seat: 'Alamo', metro: 'savannah-metro-ga' },
  marion: { seat: 'Buena Vista', metro: 'columbus-metro-ga' },
  twiggs: { seat: 'Jeffersonville', metro: 'macon-metro-ga' },
  clinch: { seat: 'Homerville', metro: 'valdosta-metro-ga' },
  treutlen: { seat: 'Soperton', metro: 'savannah-metro-ga' },
  randolph: { seat: 'Cuthbert', metro: 'albany-metro-ga' },
  miller: { seat: 'Colquitt', metro: 'albany-metro-ga' },
  talbot: { seat: 'Talbotton', metro: 'columbus-metro-ga' },
  calhoun: { seat: 'Morgan', metro: 'albany-metro-ga' },
  warren: { seat: 'Warrenton', metro: 'augusta-metro-ga' },
  chattahoochee: { seat: 'Cusseta', metro: 'columbus-metro-ga' },
  clarke: { seat: 'Athens', metro: 'athens-metro-ga' },
  clay: { seat: 'Fort Gaines', metro: 'albany-metro-ga' },
  echols: { seat: 'Statenville', metro: 'valdosta-metro-ga' },
  glascock: { seat: 'Gibson', metro: 'augusta-metro-ga' },
  harris: { seat: 'Hamilton', metro: 'columbus-metro-ga' },
  lincoln: { seat: 'Lincolnton', metro: 'augusta-metro-ga' },
  quitman: { seat: 'Georgetown', metro: 'albany-metro-ga' },
  schley: { seat: 'Ellaville', metro: 'columbus-metro-ga' },
  stewart: { seat: 'Lumpkin', metro: 'columbus-metro-ga' },
};

export function applyGeorgiaCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'georgia') return county;
  const override = georgiaCountyOverrides[county.slug];
  return override ? { ...county, ...override } : county;
}