import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Illinois counties */
export const illinoisCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  cook: { seat: 'Chicago', metro: 'chicago-metro-il' },
  dupage: { seat: 'Wheaton', metro: 'chicago-metro-west-il' },
  lake: { seat: 'Waukegan', metro: 'chicago-metro-north-il' },
  will: { seat: 'Joliet', metro: 'chicago-metro-southwest-il' },
  kane: { seat: 'Geneva', metro: 'chicago-metro-west-il' },
  mchenry: { seat: 'Woodstock', metro: 'chicago-metro-northwest-il' },
  winnebago: { seat: 'Rockford', metro: 'rockford-metro-il' },
  madison: { seat: 'Edwardsville', metro: 'st-louis-metro-il' },
  'st-clair': { seat: 'Belleville', metro: 'st-louis-metro-il' },
  champaign: { seat: 'Urbana', metro: 'champaign-urbana-metro-il' },
  sangamon: { seat: 'Springfield', metro: 'springfield-metro-il' },
  peoria: { seat: 'Peoria', metro: 'peoria-metro-il' },
  mclean: { seat: 'Bloomington', metro: 'bloomington-normal-metro-il' },
  kendall: { seat: 'Yorkville', metro: 'chicago-metro-southwest-il' },
  'rock-island': { seat: 'Rock Island', metro: 'quad-cities-metro-il' },
  tazewell: { seat: 'Pekin', metro: 'peoria-metro-il' },
  lasalle: { seat: 'Ottawa', metro: 'ottawa-metro-il' },
  kankakee: { seat: 'Kankakee', metro: 'kankakee-metro-il' },
  dekalb: { seat: 'Sycamore', metro: 'dekalb-metro-il' },
  macon: { seat: 'Decatur', metro: 'decatur-metro-il' },
  vermilion: { seat: 'Danville', metro: 'danville-metro-il' },
  williamson: { seat: 'Marion', metro: 'marion-metro-il' },
  adams: { seat: 'Quincy', metro: 'quincy-metro-il' },
  grundy: { seat: 'Morris', metro: 'chicago-metro-southwest-il' },
  whiteside: { seat: 'Morrison', metro: 'sterling-rock-falls-metro-il' },
  boone: { seat: 'Belvidere', metro: 'rockford-metro-il' },
  jackson: { seat: 'Murphysboro', metro: 'carbondale-metro-il' },
  ogle: { seat: 'Oregon', metro: 'oregon-metro-il' },
  henry: { seat: 'Cambridge', metro: 'quad-cities-metro-il' },
  knox: { seat: 'Galesburg', metro: 'galesburg-metro-il' },
  coles: { seat: 'Charleston', metro: 'champaign-urbana-metro-il' },
  macoupin: { seat: 'Carlinville', metro: 'st-louis-metro-il' },
  stephenson: { seat: 'Freeport', metro: 'rockford-metro-il' },
  woodford: { seat: 'Eureka', metro: 'peoria-metro-il' },
  clinton: { seat: 'Carlyle', metro: 'st-louis-metro-il' },
  fayette: { seat: 'Vandalia', metro: 'springfield-metro-il' },
  shelby: { seat: 'Shelbyville', metro: 'decatur-metro-il' },
  perry: { seat: 'Pinckneyville', metro: 'marion-metro-il' },
  washington: { seat: 'Nashville', metro: 'st-louis-metro-il' },
  massac: { seat: 'Metropolis', metro: 'carbondale-metro-il' },
  johnson: { seat: 'Vienna', metro: 'carbondale-metro-il' },
  ford: { seat: 'Paxton', metro: 'champaign-urbana-metro-il' },
  white: { seat: 'Carmi', metro: 'marion-metro-il' },
  clay: { seat: 'Louisville', metro: 'springfield-metro-il' },
  cass: { seat: 'Virginia', metro: 'springfield-metro-il' },
  mason: { seat: 'Havana', metro: 'peoria-metro-il' },
  menard: { seat: 'Petersburg', metro: 'springfield-metro-il' },
  marshall: { seat: 'Lacon', metro: 'peoria-metro-il' },
  greene: { seat: 'Carrollton', metro: 'springfield-metro-il' },
  wabash: { seat: 'Mount Carmel', metro: 'marion-metro-il' },
  cumberland: { seat: 'Toledo', metro: 'champaign-urbana-metro-il' },
  jasper: { seat: 'Newton', metro: 'decatur-metro-il' },
  hamilton: { seat: 'McLeansboro', metro: 'marion-metro-il' },
  schuyler: { seat: 'Rushville', metro: 'quincy-metro-il' },
  brown: { seat: 'Mount Sterling', metro: 'quincy-metro-il' },
  henderson: { seat: 'Oquawka', metro: 'quad-cities-metro-il' },
  edwards: { seat: 'Albion', metro: 'marion-metro-il' },
  putnam: { seat: 'Hennepin', metro: 'ottawa-metro-il' },
  stark: { seat: 'Toulon', metro: 'peoria-metro-il' },
  scott: { seat: 'Winchester', metro: 'springfield-metro-il' },
  pulaski: { seat: 'Mound City', metro: 'carbondale-metro-il' },
  gallatin: { seat: 'Shawneetown', metro: 'marion-metro-il' },
  alexander: { seat: 'Cairo', metro: 'carbondale-metro-il' },
  calhoun: { seat: 'Hardin', metro: 'st-louis-metro-il' },
  pope: { seat: 'Golconda', metro: 'carbondale-metro-il' },
  hardin: { seat: 'Elizabethtown', metro: 'carbondale-metro-il' },
  bureau: { seat: 'Princeton', metro: 'ottawa-metro-il' },
  carroll: { seat: 'Mount Carroll', metro: 'rockford-metro-il' },
  'jo-daviess': { seat: 'Galena', metro: 'galena-metro-il' },
  lee: { seat: 'Dixon', metro: 'rockford-metro-il' },
  mercer: { seat: 'Aledo', metro: 'quad-cities-metro-il' },
  warren: { seat: 'Monmouth', metro: 'galesburg-metro-il' },
  christian: { seat: 'Taylorville', metro: 'decatur-metro-il' },
  'de-witt': { seat: 'Clinton', metro: 'bloomington-normal-metro-il' },
  douglas: { seat: 'Tuscola', metro: 'champaign-urbana-metro-il' },
  edgar: { seat: 'Paris', metro: 'danville-metro-il' },
  effingham: { seat: 'Effingham', metro: 'decatur-metro-il' },
  fulton: { seat: 'Lewistown', metro: 'peoria-metro-il' },
  livingston: { seat: 'Pontiac', metro: 'bloomington-normal-metro-il' },
  logan: { seat: 'Lincoln', metro: 'springfield-metro-il' },
  moultrie: { seat: 'Sullivan', metro: 'decatur-metro-il' },
  piatt: { seat: 'Monticello', metro: 'champaign-urbana-metro-il' },
  hancock: { seat: 'Carthage', metro: 'quincy-metro-il' },
  mcdonough: { seat: 'Macomb', metro: 'galesburg-metro-il' },
  morgan: { seat: 'Jacksonville', metro: 'springfield-metro-il' },
  pike: { seat: 'Pittsfield', metro: 'quincy-metro-il' },
  clark: { seat: 'Marshall', metro: 'danville-metro-il' },
  iroquois: { seat: 'Watseka', metro: 'kankakee-metro-il' },
  bond: { seat: 'Greenville', metro: 'st-louis-metro-il' },
  jersey: { seat: 'Jerseyville', metro: 'st-louis-metro-il' },
  monroe: { seat: 'Waterloo', metro: 'st-louis-metro-il' },
  montgomery: { seat: 'Hillsboro', metro: 'springfield-metro-il' },
  randolph: { seat: 'Chester', metro: 'st-louis-metro-il' },
  crawford: { seat: 'Robinson', metro: 'danville-metro-il' },
  franklin: { seat: 'Benton', metro: 'marion-metro-il' },
  jefferson: { seat: 'Mount Vernon', metro: 'marion-metro-il' },
  lawrence: { seat: 'Lawrenceville', metro: 'danville-metro-il' },
  marion: { seat: 'Salem', metro: 'springfield-metro-il' },
  richland: { seat: 'Olney', metro: 'marion-metro-il' },
  saline: { seat: 'Harrisburg', metro: 'marion-metro-il' },
  union: { seat: 'Jonesboro', metro: 'carbondale-metro-il' },
  wayne: { seat: 'Fairfield', metro: 'marion-metro-il' },
};

export function applyIllinoisCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'illinois') return county;
  const override = illinoisCountyOverrides[county.slug];
  return override ? { ...county, ...override } : county;
}