import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Kentucky counties */
export const kentuckyCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  jefferson: { seat: 'Louisville', metro: 'louisville-metro-ky' },
  fayette: { seat: 'Lexington', metro: 'lexington-metro-ky' },
  kenton: { seat: 'Covington', metro: 'cincinnati-metro-ky' },
  warren: { seat: 'Bowling Green', metro: 'bowling-green-metro-ky' },
  boone: { seat: 'Burlington', metro: 'cincinnati-metro-ky' },
  hardin: { seat: 'Elizabethtown', metro: 'elizabethtown-metro-ky' },
  daviess: { seat: 'Owensboro', metro: 'owensboro-metro-ky' },
  madison: { seat: 'Richmond', metro: 'richmond-metro-ky' },
  campbell: { seat: 'Alexandria', metro: 'cincinnati-metro-ky' },
  bullitt: { seat: 'Shepherdsville', metro: 'louisville-metro-ky' },
  oldham: { seat: 'La Grange', metro: 'louisville-metro-ky' },
  christian: { seat: 'Hopkinsville', metro: 'hopkinsville-metro-ky' },
  pulaski: { seat: 'Somerset', metro: 'somerset-metro-ky' },
  mccracken: { seat: 'Paducah', metro: 'paducah-metro-ky' },
  laurel: { seat: 'London', metro: 'london-metro-ky' },
  scott: { seat: 'Georgetown', metro: 'lexington-metro-ky' },
  jessamine: { seat: 'Nicholasville', metro: 'lexington-metro-ky' },
  pike: { seat: 'Pikeville', metro: 'pikeville-metro-ky' },
  franklin: { seat: 'Frankfort', metro: 'frankfort-metro-ky' },
  shelby: { seat: 'Shelbyville', metro: 'louisville-metro-ky' },
  nelson: { seat: 'Bardstown', metro: 'bardstown-metro-ky' },
  boyd: { seat: 'Catlettsburg', metro: 'ashland-metro-ky' },
  barren: { seat: 'Glasgow', metro: 'glasgow-metro-ky' },
  hopkins: { seat: 'Madisonville', metro: 'madisonville-metro-ky' },
  henderson: { seat: 'Henderson', metro: 'henderson-metro-ky' },
  calloway: { seat: 'Murray', metro: 'murray-metro-ky' },
  clark: { seat: 'Winchester', metro: 'lexington-metro-ky' },
  whitley: { seat: 'Williamsburg', metro: 'williamsburg-metro-ky' },
  graves: { seat: 'Mayfield', metro: 'mayfield-metro-ky' },
  greenup: { seat: 'Greenup', metro: 'greenup-metro-ky' },
  floyd: { seat: 'Prestonsburg', metro: 'prestonsburg-metro-ky' },
  boyle: { seat: 'Danville', metro: 'danville-metro-ky' },
  marshall: { seat: 'Benton', metro: 'benton-metro-ky' },
  meade: { seat: 'Brandenburg', metro: 'louisville-metro-ky' },
  muhlenberg: { seat: 'Greenville', metro: 'greenville-metro-ky' },
  knox: { seat: 'Barbourville', metro: 'barbourville-metro-ky' },
  logan: { seat: 'Russellville', metro: 'russellville-metro-ky' },
  montgomery: { seat: 'Mount Sterling', metro: 'mount-sterling-metro-ky' },
  woodford: { seat: 'Versailles', metro: 'lexington-metro-ky' },
  grayson: { seat: 'Leitchfield', metro: 'leitchfield-metro-ky' },
  taylor: { seat: 'Campbellsville', metro: 'campbellsville-metro-ky' },
  grant: { seat: 'Williamstown', metro: 'williamstown-metro-ky' },
  perry: { seat: 'Hazard', metro: 'hazard-metro-ky' },
  carter: { seat: 'Grayson', metro: 'carter-metro-ky' },
  lincoln: { seat: 'Stanford', metro: 'stanford-metro-ky' },
  anderson: { seat: 'Lawrenceburg', metro: 'lawrenceburg-metro-ky' },
  rowan: { seat: 'Morehead', metro: 'morehead-metro-ky' },
  harlan: { seat: 'Harlan', metro: 'harlan-metro-ky' },
  ohio: { seat: 'Hartford', metro: 'hartford-metro-ky' },
  mercer: { seat: 'Harrodsburg', metro: 'harrodsburg-metro-ky' },
  allen: { seat: 'Scottsville', metro: 'scottsville-metro-ky' },
  bell: { seat: 'Pineville', metro: 'pineville-metro-ky' },
  johnson: { seat: 'Paintsville', metro: 'paintsville-metro-ky' },
  breckinridge: { seat: 'Hardinsburg', metro: 'hardinsburg-metro-ky' },
  spencer: { seat: 'Taylorsville', metro: 'louisville-metro-ky' },
  simpson: { seat: 'Franklin', metro: 'simpson-metro-ky' },
  hart: { seat: 'Munfordville', metro: 'munfordville-metro-ky' },
  marion: { seat: 'Lebanon', metro: 'lebanon-metro-ky' },
  bourbon: { seat: 'Paris', metro: 'paris-metro-ky' },
  harrison: { seat: 'Cynthiana', metro: 'cynthiana-metro-ky' },
  letcher: { seat: 'Whitesburg', metro: 'whitesburg-metro-ky' },
  wayne: { seat: 'Monticello', metro: 'monticello-metro-ky' },
  adair: { seat: 'Columbia', metro: 'columbia-metro-ky' },
  clay: { seat: 'Manchester', metro: 'manchester-metro-ky' },
  russell: { seat: 'Jamestown', metro: 'jamestown-metro-ky' },
  garrard: { seat: 'Lancaster', metro: 'lancaster-metro-ky' },
  mccreary: { seat: 'Whitley City', metro: 'whitley-city-metro-ky' },
  mason: { seat: 'Maysville', metro: 'maysville-metro-ky' },
  henry: { seat: 'New Castle', metro: 'new-castle-metro-ky' },
  casey: { seat: 'Liberty', metro: 'liberty-metro-ky' },
  rockcastle: { seat: 'Mount Vernon', metro: 'mount-vernon-metro-ky' },
  fleming: { seat: 'Flemingsburg', metro: 'flemingsburg-metro-ky' },
  lawrence: { seat: 'Louisa', metro: 'louisa-metro-ky' },
  larue: { seat: 'Hodgenville', metro: 'hodgenville-metro-ky' },
  pendleton: { seat: 'Falmouth', metro: 'falmouth-metro-ky' },
  morgan: { seat: 'West Liberty', metro: 'west-liberty-metro-ky' },
  trigg: { seat: 'Cadiz', metro: 'cadiz-metro-ky' },
  estill: { seat: 'Irvine', metro: 'irvine-metro-ky' },
  bath: { seat: 'Owingsville', metro: 'owingsville-metro-ky' },
  jackson: { seat: 'McKee', metro: 'mckee-metro-ky' },
  knott: { seat: 'Hindman', metro: 'hindman-metro-ky' },
  todd: { seat: 'Elkton', metro: 'elkton-metro-ky' },
  webster: { seat: 'Dixon', metro: 'dixon-metro-ky' },
  lewis: { seat: 'Vanceburg', metro: 'vanceburg-metro-ky' },
  edmonson: { seat: 'Brownsville', metro: 'brownsville-metro-ky' },
  powell: { seat: 'Stanton', metro: 'stanton-metro-ky' },
  caldwell: { seat: 'Princeton', metro: 'princeton-metro-ky' },
  butler: { seat: 'Morgantown', metro: 'morgantown-metro-ky' },
  union: { seat: 'Morganfield', metro: 'morganfield-metro-ky' },
  washington: { seat: 'Springfield', metro: 'springfield-metro-ky' },
  breathitt: { seat: 'Jackson', metro: 'jackson-metro-ky' },
  green: { seat: 'Greensburg', metro: 'greensburg-metro-ky' },
  owen: { seat: 'Owenton', metro: 'owenton-metro-ky' },
  monroe: { seat: 'Tompkinsville', metro: 'tompkinsville-metro-ky' },
  carroll: { seat: 'Carrollton', metro: 'carrollton-metro-ky' },
  magoffin: { seat: 'Salyersville', metro: 'salyersville-metro-ky' },
  martin: { seat: 'Inez', metro: 'inez-metro-ky' },
  metcalfe: { seat: 'Edmonton', metro: 'edmonton-metro-ky' },
  leslie: { seat: 'Hyden', metro: 'hyden-metro-ky' },
  lyon: { seat: 'Eddyville', metro: 'eddyville-metro-ky' },
  clinton: { seat: 'Albany', metro: 'albany-metro-ky' },
  hancock: { seat: 'Hawesville', metro: 'hawesville-metro-ky' },
  mclean: { seat: 'Calhoun', metro: 'calhoun-metro-ky' },
  gallatin: { seat: 'Warsaw', metro: 'warsaw-metro-ky' },
  livingston: { seat: 'Smithland', metro: 'smithland-metro-ky' },
  trimble: { seat: 'Bedford', metro: 'bedford-metro-ky' },
  crittenden: { seat: 'Marion', metro: 'marion-metro-ky' },
  bracken: { seat: 'Brooksville', metro: 'brooksville-metro-ky' },
  nicholas: { seat: 'Carlisle', metro: 'carlisle-metro-ky' },
  ballard: { seat: 'Wickliffe', metro: 'wickliffe-metro-ky' },
  lee: { seat: 'Beattyville', metro: 'beattyville-metro-ky' },
  elliott: { seat: 'Sandy Hook', metro: 'sandy-hook-metro-ky' },
  menifee: { seat: 'Frenchburg', metro: 'frenchburg-metro-ky' },
  wolfe: { seat: 'Campton', metro: 'campton-metro-ky' },
  fulton: { seat: 'Hickman', metro: 'hickman-metro-ky' },
  cumberland: { seat: 'Burkesville', metro: 'burkesville-metro-ky' },
  carlisle: { seat: 'Bardwell', metro: 'bardwell-metro-ky' },
  hickman: { seat: 'Clinton', metro: 'clinton-metro-ky' },
  owsley: { seat: 'Booneville', metro: 'booneville-metro-ky' },
  robertson: { seat: 'Mount Olivet', metro: 'mount-olivet-metro-ky' },
};

export function applyKentuckyCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'kentucky') return county;
  const override = kentuckyCountyOverrides[county.slug];
  return override ? { ...county, ...override } : county;
}