import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Minnesota counties (batches 1–4 — 87 counties (full MN coverage)) */
export const minnesotaCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  hennepin: { seat: "Minneapolis", metro: "hennepin-metro-mn" },
  ramsey: { seat: "Saint Paul", metro: "ramsey-metro-mn" },
  dakota: { seat: "Hastings", metro: "dakota-metro-mn" },
  anoka: { seat: "Anoka", metro: "anoka-metro-mn" },
  washington: { seat: "Stillwater", metro: "washington-metro-mn" },
  'st-louis': { seat: "Duluth", metro: "st-louis-metro-mn" },
  olmsted: { seat: "Rochester", metro: "olmsted-metro-mn" },
  stearns: { seat: "St. Cloud", metro: "stearns-metro-mn" },
  scott: { seat: "Shakopee", metro: "scott-metro-mn" },
  wright: { seat: "Buffalo", metro: "wright-metro-mn" },
  carver: { seat: "Chaska", metro: "carver-metro-mn" },
  sherburne: { seat: "Elk River", metro: "sherburne-metro-mn" },
  'blue-earth': { seat: "Mankato", metro: "blue-earth-metro-mn" },
  rice: { seat: "Faribault", metro: "rice-metro-mn" },
  'crow-wing': { seat: "Brainerd", metro: "crow-wing-metro-mn" },
  clay: { seat: "Moorhead", metro: "clay-metro-mn" },
  'otter-tail': { seat: "Fergus Falls", metro: "otter-tail-metro-mn" },
  chisago: { seat: "Center City", metro: "chisago-metro-mn" },
  winona: { seat: "Winona", metro: "winona-metro-mn" },
  goodhue: { seat: "Red Wing", metro: "goodhue-metro-mn" },
  beltrami: { seat: "Bemidji", metro: "beltrami-metro-mn" },
  itasca: { seat: "Grand Rapids", metro: "itasca-metro-mn" },
  isanti: { seat: "Cambridge", metro: "isanti-metro-mn" },
  kandiyohi: { seat: "Willmar", metro: "kandiyohi-metro-mn" },
  benton: { seat: "Foley", metro: "benton-metro-mn" },
  mower: { seat: "Austin", metro: "mower-metro-mn" },
  douglas: { seat: "Alexandria", metro: "douglas-metro-mn" },
  steele: { seat: "Owatonna", metro: "steele-metro-mn" },
  carlton: { seat: "Carlton", metro: "carlton-metro-mn" },
  mcleod: { seat: "Glencoe", metro: "mcleod-metro-mn" },
  becker: { seat: "Detroit Lakes", metro: "becker-metro-mn" },
  morrison: { seat: "Little Falls", metro: "morrison-metro-mn" },
  nicollet: { seat: "St. Peter", metro: "nicollet-metro-mn" },
  cass: { seat: "Walker", metro: "cass-metro-mn" },
  pine: { seat: "Pine City", metro: "pine-metro-mn" },
  freeborn: { seat: "Albert Lea", metro: "freeborn-metro-mn" },
  polk: { seat: "Crookston", metro: "polk-metro-mn" },
  'le-sueur': { seat: "Le Center", metro: "le-sueur-metro-mn" },
  'mille-lacs': { seat: "Milaca", metro: "mille-lacs-metro-mn" },
  todd: { seat: "Long Prairie", metro: "todd-metro-mn" },
  lyon: { seat: "Marshall", metro: "lyon-metro-mn" },
  brown: { seat: "New Ulm", metro: "brown-metro-mn" },
  meeker: { seat: "Litchfield", metro: "meeker-metro-mn" },
  hubbard: { seat: "Park Rapids", metro: "hubbard-metro-mn" },
  nobles: { seat: "Worthington", metro: "nobles-metro-mn" },
  fillmore: { seat: "Preston", metro: "fillmore-metro-mn" },
  wabasha: { seat: "Wabasha", metro: "wabasha-metro-mn" },
  dodge: { seat: "Mantorville", metro: "dodge-metro-mn" },
  martin: { seat: "Fairmont", metro: "martin-metro-mn" },
  waseca: { seat: "Waseca", metro: "waseca-metro-mn" },
  houston: { seat: "Caledonia", metro: "houston-metro-mn" },
  kanabec: { seat: "Mora", metro: "kanabec-metro-mn" },
  aitkin: { seat: "Aitkin", metro: "aitkin-metro-mn" },
  sibley: { seat: "Gaylord", metro: "sibley-metro-mn" },
  redwood: { seat: "Redwood Falls", metro: "redwood-metro-mn" },
  roseau: { seat: "Roseau", metro: "roseau-metro-mn" },
  wadena: { seat: "Wadena", metro: "wadena-metro-mn" },
  renville: { seat: "Olivia", metro: "renville-metro-mn" },
  faribault: { seat: "Blue Earth", metro: "faribault-metro-mn" },
  pennington: { seat: "Thief River Falls", metro: "pennington-metro-mn" },
  chippewa: { seat: "Montevideo", metro: "chippewa-metro-mn" },
  koochiching: { seat: "International Falls", metro: "koochiching-metro-mn" },
  watonwan: { seat: "St. James", metro: "watonwan-metro-mn" },
  cottonwood: { seat: "Windom", metro: "cottonwood-metro-mn" },
  pope: { seat: "Glenwood", metro: "pope-metro-mn" },
  lake: { seat: "Two Harbors", metro: "lake-metro-mn" },
  jackson: { seat: "Jackson", metro: "jackson-metro-mn" },
  swift: { seat: "Benson", metro: "swift-metro-mn" },
  stevens: { seat: "Morris", metro: "stevens-metro-mn" },
  rock: { seat: "Luverne", metro: "rock-metro-mn" },
  'yellow-medicine': { seat: "Granite Falls", metro: "yellow-medicine-metro-mn" },
  pipestone: { seat: "Pipestone", metro: "pipestone-metro-mn" },
  marshall: { seat: "Warren", metro: "marshall-metro-mn" },
  clearwater: { seat: "Bagley", metro: "clearwater-metro-mn" },
  murray: { seat: "Slayton", metro: "murray-metro-mn" },
  'lac-qui-parle': { seat: "Madison", metro: "lac-qui-parle-metro-mn" },
  norman: { seat: "Ada", metro: "norman-metro-mn" },
  wilkin: { seat: "Breckenridge", metro: "wilkin-metro-mn" },
  grant: { seat: "Elbow Lake", metro: "grant-metro-mn" },
  lincoln: { seat: "Ivanhoe", metro: "lincoln-metro-mn" },
  cook: { seat: "Grand Marais", metro: "cook-metro-mn" },
  mahnomen: { seat: "Mahnomen", metro: "mahnomen-metro-mn" },
  'big-stone': { seat: "Ortonville", metro: "big-stone-metro-mn" },
  kittson: { seat: "Hallock", metro: "kittson-metro-mn" },
  'red-lake': { seat: "Red Lake Falls", metro: "red-lake-metro-mn" },
  'lake-of-the-woods': { seat: "Baudette", metro: "lake-of-the-woods-metro-mn" },
  traverse: { seat: "Wheaton", metro: "traverse-metro-mn" },
};

export function applyMinnesotaCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'minnesota') return county;
  const override = minnesotaCountyOverrides[county.slug];
  if (!override) return county;
  return { ...county, ...override };
}
