import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Missouri counties */
export const missouriCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  'st-louis': { seat: 'Clayton', metro: 'st-louis-metro-mo' },
  jackson: { seat: 'Independence', metro: 'kansas-city-metro-mo' },
  'st-charles': { seat: 'St. Charles', metro: 'st-louis-metro-west-mo' },
  greene: { seat: 'Springfield', metro: 'springfield-metro-mo' },
  'st-louis-city': { seat: 'St. Louis', metro: 'st-louis-metro-mo' },
  clay: { seat: 'Liberty', metro: 'kansas-city-metro-north-mo' },
  jefferson: { seat: 'Hillsboro', metro: 'st-louis-metro-south-mo' },
  boone: { seat: 'Columbia', metro: 'columbia-metro-mo' },
  jasper: { seat: 'Carthage', metro: 'joplin-metro-mo' },
  cass: { seat: 'Harrisonville', metro: 'kansas-city-metro-south-mo' },
  platte: { seat: 'Platte City', metro: 'kansas-city-metro-northwest-mo' },
  franklin: { seat: 'Union', metro: 'st-louis-metro-west-mo' },
  christian: { seat: 'Ozark', metro: 'springfield-metro-south-mo' },
  'cape-girardeau': { seat: 'Jackson', metro: 'cape-girardeau-metro-mo' },
  buchanan: { seat: 'St. Joseph', metro: 'st-joseph-metro-mo' },
  cole: { seat: 'Jefferson City', metro: 'jefferson-city-metro-mo' },
  'st-francois': { seat: 'Farmington', metro: 'farmington-metro-mo' },
  lincoln: { seat: 'Troy', metro: 'st-louis-metro-north-mo' },
  newton: { seat: 'Neosho', metro: 'joplin-metro-mo' },
  johnson: { seat: 'Warrensburg', metro: 'warrensburg-metro-mo' },
  taney: { seat: 'Forsyth', metro: 'branson-metro-mo' },
  pulaski: { seat: 'Waynesville', metro: 'waynesville-metro-mo' },
  callaway: { seat: 'Fulton', metro: 'jefferson-city-metro-mo' },
  phelps: { seat: 'Rolla', metro: 'rolla-metro-mo' },
  pettis: { seat: 'Sedalia', metro: 'sedalia-metro-mo' },
  webster: { seat: 'Marshfield', metro: 'springfield-metro-east-mo' },
  camden: { seat: 'Camdenton', metro: 'camdenton-metro-mo' },
  butler: { seat: 'Poplar Bluff', metro: 'poplar-bluff-metro-mo' },
  howell: { seat: 'West Plains', metro: 'west-plains-metro-mo' },
  lawrence: { seat: 'Mount Vernon', metro: 'mount-vernon-metro-mo' },
  warren: { seat: 'Warrenton', metro: 'st-louis-metro-west-mo' },
  scott: { seat: 'Benton', metro: 'sikeston-metro-mo' },
  laclede: { seat: 'Lebanon', metro: 'lebanon-metro-mo' },
  barry: { seat: 'Cassville', metro: 'cassville-metro-mo' },
  polk: { seat: 'Bolivar', metro: 'bolivar-metro-mo' },
  lafayette: { seat: 'Lexington', metro: 'kansas-city-metro-east-mo' },
  stone: { seat: 'Galena', metro: 'branson-metro-mo' },
  marion: { seat: 'Palmyra', metro: 'hannibal-metro-mo' },
  stoddard: { seat: 'Bloomfield', metro: 'dexter-metro-mo' },
  dunklin: { seat: 'Kennett', metro: 'kennett-metro-mo' },
  texas: { seat: 'Houston', metro: 'houston-metro-mo' },
  miller: { seat: 'Tuscumbia', metro: 'lake-ozarks-metro-mo' },
  adair: { seat: 'Kirksville', metro: 'kirksville-metro-mo' },
  audrain: { seat: 'Mexico', metro: 'mexico-metro-mo' },
  randolph: { seat: 'Huntsville', metro: 'huntsville-metro-mo' },
  mcdonald: { seat: 'Pineville', metro: 'pineville-metro-mo' },
  washington: { seat: 'Potosi', metro: 'potosi-metro-mo' },
  ray: { seat: 'Richmond', metro: 'kansas-city-metro-east-mo' },
  saline: { seat: 'Marshall', metro: 'marshall-metro-mo' },
  crawford: { seat: 'Steelville', metro: 'steelville-metro-mo' },
  henry: { seat: 'Clinton', metro: 'clinton-metro-mo' },
  morgan: { seat: 'Versailles', metro: 'versailles-metro-mo' },
  clinton: { seat: 'Plattsburg', metro: 'kansas-city-metro-north-mo' },
  benton: { seat: 'Warsaw', metro: 'warsaw-metro-mo' },
  vernon: { seat: 'Nevada', metro: 'nevada-metro-mo' },
  nodaway: { seat: 'Maryville', metro: 'maryville-metro-mo' },
  wright: { seat: 'Hartville', metro: 'hartville-metro-mo' },
  perry: { seat: 'Perryville', metro: 'perryville-metro-mo' },
  'ste-genevieve': { seat: 'Ste. Genevieve', metro: 'ste-genevieve-metro-mo' },
  andrew: { seat: 'Savannah', metro: 'st-joseph-metro-mo' },
  dallas: { seat: 'Buffalo', metro: 'buffalo-metro-mo' },
  pike: { seat: 'Bowling Green', metro: 'bowling-green-metro-mo' },
  cooper: { seat: 'Boonville', metro: 'boonville-metro-mo' },
  bates: { seat: 'Butler', metro: 'butler-metro-mo' },
  moniteau: { seat: 'California', metro: 'california-metro-mo' },
  macon: { seat: 'Macon', metro: 'macon-metro-mo' },
  'new-madrid': { seat: 'New Madrid', metro: 'new-madrid-metro-mo' },
  gasconade: { seat: 'Hermann', metro: 'hermann-metro-mo' },
  cedar: { seat: 'Stockton', metro: 'stockton-metro-mo' },
  livingston: { seat: 'Chillicothe', metro: 'chillicothe-metro-mo' },
  dent: { seat: 'Salem', metro: 'salem-metro-mo' },
  pemiscot: { seat: 'Caruthersville', metro: 'caruthersville-metro-mo' },
  osage: { seat: 'Linn', metro: 'linn-metro-mo' },
  madison: { seat: 'Fredericktown', metro: 'fredericktown-metro-mo' },
  douglas: { seat: 'Ava', metro: 'ava-metro-mo' },
  mississippi: { seat: 'Charleston', metro: 'charleston-metro-mo' },
  barton: { seat: 'Lamar', metro: 'lamar-metro-mo' },
  linn: { seat: 'Linneus', metro: 'linneus-metro-mo' },
  montgomery: { seat: 'Montgomery City', metro: 'montgomery-city-metro-mo' },
  bollinger: { seat: 'Marble Hill', metro: 'marble-hill-metro-mo' },
  ripley: { seat: 'Doniphan', metro: 'doniphan-metro-mo' },
  wayne: { seat: 'Greenville', metro: 'greenville-metro-mo' },
  ralls: { seat: 'New London', metro: 'new-london-metro-mo' },
  howard: { seat: 'Fayette', metro: 'fayette-metro-mo' },
  'st-clair': { seat: 'Osceola', metro: 'osceola-metro-mo' },
  lewis: { seat: 'Monticello', metro: 'monticello-metro-mo' },
  grundy: { seat: 'Trenton', metro: 'trenton-metro-mo' },
  dekalb: { seat: 'Maysville', metro: 'maysville-metro-mo' },
  ozark: { seat: 'Gainesville', metro: 'gainesville-metro-mo' },
  iron: { seat: 'Ironton', metro: 'ironton-metro-mo' },
  hickory: { seat: 'Hermitage', metro: 'hermitage-metro-mo' },
  monroe: { seat: 'Paris', metro: 'paris-metro-mo' },
  caldwell: { seat: 'Kingston', metro: 'kingston-metro-mo' },
  oregon: { seat: 'Alton', metro: 'alton-metro-mo' },
  daviess: { seat: 'Gallatin', metro: 'gallatin-metro-mo' },
  carroll: { seat: 'Carrollton', metro: 'carrollton-metro-mo' },
  harrison: { seat: 'Bethany', metro: 'bethany-metro-mo' },
  maries: { seat: 'Vienna', metro: 'vienna-metro-mo' },
  dade: { seat: 'Greenfield', metro: 'greenfield-metro-mo' },
  chariton: { seat: 'Keytesville', metro: 'keytesville-metro-mo' },
  shannon: { seat: 'Eminence', metro: 'eminence-metro-mo' },
  gentry: { seat: 'Albany', metro: 'albany-metro-mo' },
  clark: { seat: 'Kahoka', metro: 'kahoka-metro-mo' },
  reynolds: { seat: 'Centerville', metro: 'centerville-metro-mo' },
  shelby: { seat: 'Shelbyville', metro: 'shelbyville-metro-mo' },
  sullivan: { seat: 'Milan', metro: 'milan-metro-mo' },
  carter: { seat: 'Van Buren', metro: 'van-buren-metro-mo' },
  atchison: { seat: 'Rock Port', metro: 'rock-port-metro-mo' },
  scotland: { seat: 'Memphis', metro: 'memphis-metro-mo' },
  putnam: { seat: 'Unionville', metro: 'unionville-metro-mo' },
  schuyler: { seat: 'Lancaster', metro: 'lancaster-metro-mo' },
  mercer: { seat: 'Princeton', metro: 'princeton-metro-mo' },
  worth: { seat: 'Grant City', metro: 'grant-city-metro-mo' },
};

export function applyMissouriCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'missouri') return county;
  const override = missouriCountyOverrides[county.slug];
  return override ? { ...county, ...override } : county;
}