import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Mississippi counties */
export const mississippiCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  harrison: { seat: 'Gulfport', metro: 'gulfport-biloxi-metro-ms' },
  hinds: { seat: 'Jackson', metro: 'jackson-ms-metro-ms' },
  desoto: { seat: 'Hernando', metro: 'desoto-metro-ms' },
  rankin: { seat: 'Brandon', metro: 'jackson-ms-metro-ms' },
  jackson: { seat: 'Pascagoula', metro: 'pascagoula-metro-ms' },
  madison: { seat: 'Canton', metro: 'jackson-ms-metro-ms' },
  lee: { seat: 'Tupelo', metro: 'tupelo-metro-ms' },
  forrest: { seat: 'Hattiesburg', metro: 'hattiesburg-metro-ms' },
  lauderdale: { seat: 'Meridian', metro: 'meridian-metro-ms' },
  lamar: { seat: 'Purvis', metro: 'hattiesburg-metro-ms' },
  jones: { seat: 'Laurel', metro: 'laurel-metro-ms' },
  'pearl-river': { seat: 'Poplarville', metro: 'picayune-metro-ms' },
  lafayette: { seat: 'Oxford', metro: 'oxford-metro-ms' },
  lowndes: { seat: 'Columbus', metro: 'columbus-ms-metro-ms' },
  oktibbeha: { seat: 'Starkville', metro: 'starkville-metro-ms' },
  hancock: { seat: 'Bay St. Louis', metro: 'hancock-coastal-ms' },
  warren: { seat: 'Vicksburg', metro: 'vicksburg-metro-ms' },
  washington: { seat: 'Greenville', metro: 'greenville-metro-ms' },
  pike: { seat: 'McComb', metro: 'mccomb-metro-ms' },
  lincoln: { seat: 'Brookhaven', metro: 'brookhaven-metro-ms' },
  marshall: { seat: 'Holly Springs', metro: 'holly-springs-metro-ms' },
  alcorn: { seat: 'Corinth', metro: 'corinth-metro-ms' },
  monroe: { seat: 'Aberdeen', metro: 'aberdeen-metro-ms' },
  panola: { seat: 'Batesville', metro: 'batesville-metro-ms' },
  pontotoc: { seat: 'Pontotoc', metro: 'pontotoc-metro-ms' },
  adams: { seat: 'Natchez', metro: 'natchez-metro-ms' },
  tate: { seat: 'Senatobia', metro: 'senatobia-metro-ms' },
  neshoba: { seat: 'Philadelphia', metro: 'philadelphia-metro-ms' },
  union: { seat: 'New Albany', metro: 'new-albany-metro-ms' },
  scott: { seat: 'Forest', metro: 'forest-metro-ms' },
  bolivar: { seat: 'Cleveland', metro: 'cleveland-metro-ms' },
  copiah: { seat: 'Hazlehurst', metro: 'hazlehurst-metro-ms' },
  george: { seat: 'Lucedale', metro: 'lucedale-metro-ms' },
  simpson: { seat: 'Mendenhall', metro: 'mendenhall-metro-ms' },
  prentiss: { seat: 'Booneville', metro: 'booneville-metro-ms' },
  leflore: { seat: 'Greenwood', metro: 'greenwood-metro-ms' },
  itawamba: { seat: 'Fulton', metro: 'fulton-metro-ms' },
  marion: { seat: 'Columbia', metro: 'columbia-metro-ms' },
  yazoo: { seat: 'Yazoo City', metro: 'yazoo-city-metro-ms' },
  sunflower: { seat: 'Indianola', metro: 'indianola-metro-ms' },
  leake: { seat: 'Carthage', metro: 'carthage-metro-ms' },
  tippah: { seat: 'Ripley', metro: 'ripley-metro-ms' },
  newton: { seat: 'Newton', metro: 'newton-metro-ms' },
  grenada: { seat: 'Grenada', metro: 'grenada-metro-ms' },
  stone: { seat: 'Wiggins', metro: 'wiggins-metro-ms' },
  wayne: { seat: 'Waynesboro', metro: 'waynesboro-metro-ms' },
  coahoma: { seat: 'Clarksdale', metro: 'clarksdale-metro-ms' },
  tishomingo: { seat: 'Iuka', metro: 'iuka-metro-ms' },
  clay: { seat: 'West Point', metro: 'west-point-metro-ms' },
  covington: { seat: 'Collins', metro: 'collins-metro-ms' },
  winston: { seat: 'Louisville', metro: 'louisville-metro-ms' },
  attala: { seat: 'Kosciusko', metro: 'kosciusko-metro-ms' },
  chickasaw: { seat: 'Houston', metro: 'houston-ms-metro-ms' },
  jasper: { seat: 'Bay Springs', metro: 'bay-springs-metro-ms' },
  holmes: { seat: 'Lexington', metro: 'lexington-ms-metro-ms' },
  clarke: { seat: 'Quitman', metro: 'quitman-ms-metro-ms' },
  walthall: { seat: 'Tylertown', metro: 'tylertown-metro-ms' },
  smith: { seat: 'Raleigh', metro: 'raleigh-ms-metro-ms' },
  greene: { seat: 'Leakesville', metro: 'leakesville-metro-ms' },
  calhoun: { seat: 'Pittsboro', metro: 'calhoun-city-metro-ms' },
  amite: { seat: 'Liberty', metro: 'liberty-ms-metro-ms' },
  yalobusha: { seat: 'Water Valley', metro: 'water-valley-metro-ms' },
  lawrence: { seat: 'Monticello', metro: 'monticello-ms-metro-ms' },
  perry: { seat: 'New Augusta', metro: 'new-augusta-metro-ms' },
  'jefferson-davis': { seat: 'Prentiss', metro: 'jefferson-davis-metro-ms' },
  tallahatchie: { seat: 'Charleston', metro: 'charleston-metro-ms' },
  webster: { seat: 'Walthall', metro: 'webster-ms-metro-ms' },
  noxubee: { seat: 'Macon', metro: 'macon-metro-ms' },
  montgomery: { seat: 'Winona', metro: 'winona-metro-ms' },
  carroll: { seat: 'Carrollton', metro: 'carrollton-metro-ms' },
  kemper: { seat: 'De Kalb', metro: 'de-kalb-metro-ms' },
  tunica: { seat: 'Tunica', metro: 'tunica-metro-ms' },
  claiborne: { seat: 'Port Gibson', metro: 'port-gibson-metro-ms' },
  choctaw: { seat: 'Ackerman', metro: 'ackerman-metro-ms' },
  franklin: { seat: 'Meadville', metro: 'meadville-metro-ms' },
  humphreys: { seat: 'Belzoni', metro: 'belzoni-metro-ms' },
  benton: { seat: 'Ashland', metro: 'ashland-metro-ms' },
  wilkinson: { seat: 'Woodville', metro: 'woodville-metro-ms' },
  jefferson: { seat: 'Fayette', metro: 'fayette-ms-metro-ms' },
  quitman: { seat: 'Marks', metro: 'marks-metro-ms' },
  sharkey: { seat: 'Rolling Fork', metro: 'rolling-fork-metro-ms' },
  issaquena: { seat: 'Mayersville', metro: 'mayersville-metro-ms' },
};

export function applyMississippiCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'mississippi') return county;
  const override = mississippiCountyOverrides[county.slug];
  return override ? { ...county, ...override } : county;
}