import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated South Dakota counties (66/66 — full set) */
export const southDakotaCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  minnehaha: { seat: 'Sioux Falls', metro: 'minnehaha-metro-sd' },
  pennington: { seat: 'Rapid City', metro: 'pennington-metro-sd' },
  lincoln: { seat: 'Canton', metro: 'lincoln-metro-sd' },
  brookings: { seat: 'Brookings', metro: 'brookings-metro-sd' },
  brown: { seat: 'Aberdeen', metro: 'brown-metro-sd' },
  meade: { seat: 'Sturgis', metro: 'meade-metro-sd' },
  lawrence: { seat: 'Deadwood', metro: 'lawrence-metro-sd' },
  codington: { seat: 'Watertown', metro: 'codington-metro-sd' },
  yankton: { seat: 'Yankton', metro: 'yankton-metro-sd' },
  davison: { seat: 'Mitchell', metro: 'davison-metro-sd' },
  beadle: { seat: 'Huron', metro: 'beadle-metro-sd' },
  hughes: { seat: 'Pierre', metro: 'hughes-metro-sd' },
  union: { seat: 'Elk Point', metro: 'union-metro-sd' },
  clay: { seat: 'Vermillion', metro: 'clay-metro-sd' },
  shannon: { seat: 'Pine Ridge', metro: 'shannon-metro-sd' },
  lake: { seat: 'Madison', metro: 'lake-metro-sd' },
  butte: { seat: 'Belle Fourche', metro: 'butte-metro-sd' },
  roberts: { seat: 'Sisseton', metro: 'roberts-metro-sd' },
  custer: { seat: 'Custer', metro: 'custer-metro-sd' },
  turner: { seat: 'Parker', metro: 'turner-metro-sd' },
  'charles-mix': { seat: 'Lake Andes', metro: 'charles-mix-metro-sd' },
  todd: { seat: 'Mission', metro: 'todd-metro-sd' },
  'fall-river': { seat: 'Hot Springs', metro: 'fall-river-metro-sd' },
  grant: { seat: 'Milbank', metro: 'grant-metro-sd' },
  hutchinson: { seat: 'Olivet', metro: 'hutchinson-metro-sd' },
  'bon-homme': { seat: 'Tyndall', metro: 'bon-homme-metro-sd' },
  hamlin: { seat: 'Hayti', metro: 'hamlin-metro-sd' },
  moody: { seat: 'Flandreau', metro: 'moody-metro-sd' },
  spink: { seat: 'Redfield', metro: 'spink-metro-sd' },
  mccook: { seat: 'Salem', metro: 'mccook-metro-sd' },
  tripp: { seat: 'Winner', metro: 'tripp-metro-sd' },
  day: { seat: 'Webster', metro: 'day-metro-sd' },
  dewey: { seat: 'Timber Lake', metro: 'dewey-metro-sd' },
  kingsbury: { seat: 'De Smet', metro: 'kingsbury-metro-sd' },
  brule: { seat: 'Chamberlain', metro: 'brule-metro-sd' },
  walworth: { seat: 'Selby', metro: 'walworth-metro-sd' },
  deuel: { seat: 'Clear Lake', metro: 'deuel-metro-sd' },
  marshall: { seat: 'Britton', metro: 'marshall-metro-sd' },
  clark: { seat: 'Clark', metro: 'clark-metro-sd' },
  edmunds: { seat: 'Ipswich', metro: 'edmunds-metro-sd' },
  gregory: { seat: 'Burke', metro: 'gregory-metro-sd' },
  corson: { seat: 'McIntosh', metro: 'corson-metro-sd' },
  lyman: { seat: 'Kennebec', metro: 'lyman-metro-sd' },
  hanson: { seat: 'Alexandria', metro: 'hanson-metro-sd' },
  bennett: { seat: 'Martin', metro: 'bennett-metro-sd' },
  hand: { seat: 'Miller', metro: 'hand-metro-sd' },
  stanley: { seat: 'Fort Pierre', metro: 'stanley-metro-sd' },
  douglas: { seat: 'Armour', metro: 'douglas-metro-sd' },
  perkins: { seat: 'Bison', metro: 'perkins-metro-sd' },
  aurora: { seat: 'Plankinton', metro: 'aurora-metro-sd' },
  jackson: { seat: 'Kadoka', metro: 'jackson-metro-sd' },
  sanborn: { seat: 'Woonsocket', metro: 'sanborn-metro-sd' },
  ziebach: { seat: 'Dupree', metro: 'ziebach-metro-sd' },
  mcpherson: { seat: 'Leola', metro: 'mcpherson-metro-sd' },
  potter: { seat: 'Gettysburg', metro: 'potter-metro-sd' },
  miner: { seat: 'Howard', metro: 'miner-metro-sd' },
  mellette: { seat: 'White River', metro: 'mellette-metro-sd' },
  faulk: { seat: 'Faulkton', metro: 'faulk-metro-sd' },
  buffalo: { seat: 'Gann Valley', metro: 'buffalo-metro-sd' },
  haakon: { seat: 'Philip', metro: 'haakon-metro-sd' },
  jerauld: { seat: 'Wessington Springs', metro: 'jerauld-metro-sd' },
  sully: { seat: 'Onida', metro: 'sully-metro-sd' },
  campbell: { seat: 'Mound City', metro: 'campbell-metro-sd' },
  harding: { seat: 'Buffalo', metro: 'harding-metro-sd' },
  hyde: { seat: 'Highmore', metro: 'hyde-metro-sd' },
  jones: { seat: 'Murdo', metro: 'jones-metro-sd' },
};

export function applySouthDakotaCountyOverrides(county: LocalCounty): LocalCounty {
  const override = southDakotaCountyOverrides[county.slug];
  if (!override) return county;
  return { ...county, ...override };
}
