import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Tennessee counties */
export const tennesseeCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  shelby: { seat: 'Memphis', metro: 'memphis-metro-tn' },
  davidson: { seat: 'Nashville', metro: 'nashville-metro-tn' },
  knox: { seat: 'Knoxville', metro: 'knoxville-metro-tn' },
  hamilton: { seat: 'Chattanooga', metro: 'chattanooga-metro-tn' },
  rutherford: { seat: 'Murfreesboro', metro: 'nashville-metro-tn' },
  williamson: { seat: 'Franklin', metro: 'nashville-metro-tn' },
  montgomery: { seat: 'Clarksville', metro: 'clarksville-metro-tn' },
  sumner: { seat: 'Gallatin', metro: 'nashville-metro-tn' },
  wilson: { seat: 'Lebanon', metro: 'nashville-metro-tn' },
  sullivan: { seat: 'Blountville', metro: 'kingsport-bristol-metro-tn' },
  blount: { seat: 'Maryville', metro: 'knoxville-metro-tn' },
  washington: { seat: 'Jonesborough', metro: 'kingsport-bristol-metro-tn' },
  maury: { seat: 'Columbia', metro: 'nashville-metro-tn' },
  bradley: { seat: 'Cleveland', metro: 'cleveland-metro-tn' },
  sevier: { seat: 'Sevierville', metro: 'sevierville-metro-tn' },
  madison: { seat: 'Jackson', metro: 'jackson-metro-tn' },
  putnam: { seat: 'Cookeville', metro: 'cookeville-metro-tn' },
  anderson: { seat: 'Clinton', metro: 'knoxville-metro-tn' },
  robertson: { seat: 'Springfield', metro: 'nashville-metro-tn' },
  greene: { seat: 'Greeneville', metro: 'greeneville-metro-tn' },
  hamblen: { seat: 'Morristown', metro: 'morristown-metro-tn' },
  cumberland: { seat: 'Crossville', metro: 'crossville-metro-tn' },
  loudon: { seat: 'Loudon', metro: 'knoxville-metro-tn' },
  coffee: { seat: 'Manchester', metro: 'manchester-metro-tn' },
  tipton: { seat: 'Covington', metro: 'memphis-metro-tn' },
  jefferson: { seat: 'Dandridge', metro: 'morristown-metro-tn' },
  hawkins: { seat: 'Rogersville', metro: 'kingsport-bristol-metro-tn' },
  dickson: { seat: 'Dickson', metro: 'nashville-metro-tn' },
  mcminn: { seat: 'Athens', metro: 'athens-metro-tn' },
  roane: { seat: 'Kingston', metro: 'knoxville-metro-tn' },
  carter: { seat: 'Elizabethton', metro: 'kingsport-bristol-metro-tn' },
  bedford: { seat: 'Shelbyville', metro: 'shelbyville-metro-tn' },
  gibson: { seat: 'Trenton', metro: 'jackson-metro-tn' },
  monroe: { seat: 'Madisonville', metro: 'monroe-metro-tn' },
  lawrence: { seat: 'Lawrenceburg', metro: 'lawrenceburg-metro-tn' },
  franklin: { seat: 'Winchester', metro: 'manchester-metro-tn' },
  fayette: { seat: 'Somerville', metro: 'memphis-metro-tn' },
  warren: { seat: 'McMinnville', metro: 'mcminnville-metro-tn' },
  cheatham: { seat: 'Ashland City', metro: 'nashville-metro-tn' },
  campbell: { seat: 'Jacksboro', metro: 'knoxville-metro-tn' },
  marshall: { seat: 'Lewisburg', metro: 'lewisburg-metro-tn' },
  cocke: { seat: 'Newport', metro: 'newport-metro-tn' },
  lincoln: { seat: 'Fayetteville', metro: 'fayetteville-metro-tn' },
  dyer: { seat: 'Dyersburg', metro: 'dyersburg-metro-tn' },
  rhea: { seat: 'Dayton', metro: 'dayton-metro-tn' },
  claiborne: { seat: 'Tazewell', metro: 'tazewell-metro-tn' },
  weakley: { seat: 'Dresden', metro: 'weakley-metro-tn' },
  henry: { seat: 'Paris', metro: 'paris-metro-tn' },
  giles: { seat: 'Pulaski', metro: 'pulaski-metro-tn' },
  white: { seat: 'Sparta', metro: 'sparta-metro-tn' },
  obion: { seat: 'Union City', metro: 'union-city-metro-tn' },
  marion: { seat: 'Jasper', metro: 'jasper-metro-tn' },
  carroll: { seat: 'Huntingdon', metro: 'huntingdon-metro-tn' },
  henderson: { seat: 'Lexington', metro: 'lexington-metro-tn' },
  hardin: { seat: 'Savannah', metro: 'savannah-metro-tn' },
  macon: { seat: 'Lafayette', metro: 'lafayette-metro-tn' },
  hickman: { seat: 'Centerville', metro: 'centerville-metro-tn' },
  grainger: { seat: 'Rutledge', metro: 'morristown-metro-tn' },
  mcnairy: { seat: 'Selmer', metro: 'selmer-metro-tn' },
  hardeman: { seat: 'Bolivar', metro: 'bolivar-metro-tn' },
  lauderdale: { seat: 'Ripley', metro: 'ripley-metro-tn' },
  overton: { seat: 'Livingston', metro: 'livingston-metro-tn' },
  scott: { seat: 'Huntsville', metro: 'knoxville-metro-tn' },
  morgan: { seat: 'Wartburg', metro: 'knoxville-metro-tn' },
  dekalb: { seat: 'Smithville', metro: 'smithville-metro-tn' },
  union: { seat: 'Maynardville', metro: 'knoxville-metro-tn' },
  smith: { seat: 'Carthage', metro: 'carthage-metro-tn' },
  fentress: { seat: 'Jamestown', metro: 'jamestown-metro-tn' },
  humphreys: { seat: 'Waverly', metro: 'waverly-metro-tn' },
  johnson: { seat: 'Mountain City', metro: 'kingsport-bristol-metro-tn' },
  polk: { seat: 'Benton', metro: 'benton-metro-tn' },
  chester: { seat: 'Henderson', metro: 'chester-metro-tn' },
  sequatchie: { seat: 'Dunlap', metro: 'dunlap-metro-tn' },
  unicoi: { seat: 'Erwin', metro: 'erwin-metro-tn' },
  haywood: { seat: 'Brownsville', metro: 'brownsville-metro-tn' },
  wayne: { seat: 'Waynesboro', metro: 'waynesboro-metro-tn' },
  bledsoe: { seat: 'Pikeville', metro: 'pikeville-metro-tn' },
  benton: { seat: 'Camden', metro: 'camden-metro-tn' },
  cannon: { seat: 'Woodbury', metro: 'woodbury-metro-tn' },
  stewart: { seat: 'Dover', metro: 'dover-metro-tn' },
  meigs: { seat: 'Decatur', metro: 'meigs-metro-tn' },
  grundy: { seat: 'Altamont', metro: 'grundy-metro-tn' },
  crockett: { seat: 'Alamo', metro: 'alamo-metro-tn' },
  lewis: { seat: 'Hohenwald', metro: 'hohenwald-metro-tn' },
  trousdale: { seat: 'Hartsville', metro: 'hartsville-metro-tn' },
  jackson: { seat: 'Gainesboro', metro: 'gainesboro-metro-tn' },
  decatur: { seat: 'Decaturville', metro: 'decaturville-metro-tn' },
  perry: { seat: 'Linden', metro: 'linden-metro-tn' },
  houston: { seat: 'Erin', metro: 'erin-metro-tn' },
  clay: { seat: 'Celina', metro: 'celina-metro-tn' },
  hancock: { seat: 'Sneedville', metro: 'sneedville-metro-tn' },
  'van-buren': { seat: 'Spencer', metro: 'spencer-metro-tn' },
  moore: { seat: 'Lynchburg', metro: 'lynchburg-metro-tn' },
  lake: { seat: 'Tiptonville', metro: 'tiptonville-metro-tn' },
  pickett: { seat: 'Byrdstown', metro: 'byrdstown-metro-tn' },
};

export function applyTennesseeCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'tennessee') return county;
  const override = tennesseeCountyOverrides[county.slug];
  return override ? { ...county, ...override } : county;
}