import type { LocalCounty } from '@/lib/local-movers/types';

/** Seat and metro overrides for hand-curated Wisconsin counties (all 72 Wisconsin counties) */
export const wisconsinCountyOverrides: Partial<
  Record<string, Pick<LocalCounty, 'seat' | 'metro'>>
> = {
  milwaukee: { seat: "Milwaukee", metro: "milwaukee-metro-wi" },
  dane: { seat: "Madison", metro: "dane-metro-wi" },
  waukesha: { seat: "Waukesha", metro: "waukesha-metro-wi" },
  brown: { seat: "Green Bay", metro: "brown-metro-wi" },
  racine: { seat: "Racine", metro: "racine-metro-wi" },
  outagamie: { seat: "Appleton", metro: "outagamie-metro-wi" },
  winnebago: { seat: "Oshkosh", metro: "winnebago-metro-wi" },
  kenosha: { seat: "Kenosha", metro: "kenosha-metro-wi" },
  rock: { seat: "Janesville", metro: "rock-metro-wi" },
  marathon: { seat: "Wausau", metro: "marathon-metro-wi" },
  washington: { seat: "West Bend", metro: "washington-metro-wi" },
  'la-crosse': { seat: "La Crosse", metro: "la-crosse-metro-wi" },
  sheboygan: { seat: "Sheboygan", metro: "sheboygan-metro-wi" },
  'eau-claire': { seat: "Eau Claire", metro: "eau-claire-metro-wi" },
  walworth: { seat: "Elkhorn", metro: "walworth-metro-wi" },
  'fond-du-lac': { seat: "Fond du Lac", metro: "fond-du-lac-metro-wi" },
  'st-croix': { seat: "Hudson", metro: "st-croix-metro-wi" },
  ozaukee: { seat: "Port Washington", metro: "ozaukee-metro-wi" },
  dodge: { seat: "Juneau", metro: "dodge-metro-wi" },
  jefferson: { seat: "Jefferson", metro: "jefferson-metro-wi" },
  manitowoc: { seat: "Manitowoc", metro: "manitowoc-metro-wi" },
  wood: { seat: "Wisconsin Rapids", metro: "wood-metro-wi" },
  portage: { seat: "Stevens Point", metro: "portage-metro-wi" },
  chippewa: { seat: "Chippewa Falls", metro: "chippewa-metro-wi" },
  sauk: { seat: "Baraboo", metro: "sauk-metro-wi" },
  columbia: { seat: "Portage", metro: "columbia-metro-wi" },
  calumet: { seat: "Chilton", metro: "calumet-metro-wi" },
  grant: { seat: "Lancaster", metro: "grant-metro-wi" },
  waupaca: { seat: "Waupaca", metro: "waupaca-metro-wi" },
  monroe: { seat: "Sparta", metro: "monroe-metro-wi" },
  dunn: { seat: "Menomonie", metro: "dunn-metro-wi" },
  barron: { seat: "Barron", metro: "barron-metro-wi" },
  polk: { seat: "Balsam Lake", metro: "polk-metro-wi" },
  douglas: { seat: "Superior", metro: "douglas-metro-wi" },
  pierce: { seat: "Ellsworth", metro: "pierce-metro-wi" },
  marinette: { seat: "Marinette", metro: "marinette-metro-wi" },
  shawano: { seat: "Shawano", metro: "shawano-metro-wi" },
  oconto: { seat: "Oconto", metro: "oconto-metro-wi" },
  oneida: { seat: "Rhinelander", metro: "oneida-metro-wi" },
  green: { seat: "Monroe", metro: "green-metro-wi" },
  trempealeau: { seat: "Whitehall", metro: "trempealeau-metro-wi" },
  door: { seat: "Sturgeon Bay", metro: "door-metro-wi" },
  lincoln: { seat: "Merrill", metro: "lincoln-metro-wi" },
  juneau: { seat: "Mauston", metro: "juneau-metro-wi" },
  waushara: { seat: "Wautoma", metro: "waushara-metro-wi" },
  iowa: { seat: "Dodgeville", metro: "iowa-metro-wi" },
  vilas: { seat: "Eagle River", metro: "vilas-metro-wi" },
  adams: { seat: "Friendship", metro: "adams-metro-wi" },
  jackson: { seat: "Black River Falls", metro: "jackson-metro-wi" },
  kewaunee: { seat: "Kewaunee", metro: "kewaunee-metro-wi" },
  taylor: { seat: "Medford", metro: "taylor-metro-wi" },
  langlade: { seat: "Antigo", metro: "langlade-metro-wi" },
  'green-lake': { seat: "Green Lake", metro: "green-lake-metro-wi" },
  sawyer: { seat: "Hayward", metro: "sawyer-metro-wi" },
  lafayette: { seat: "Darlington", metro: "lafayette-metro-wi" },
  burnett: { seat: "Grantsburg", metro: "burnett-metro-wi" },
  washburn: { seat: "Shell Lake", metro: "washburn-metro-wi" },
  richland: { seat: "Richland Center", metro: "richland-metro-wi" },
  bayfield: { seat: "Washburn", metro: "bayfield-metro-wi" },
  ashland: { seat: "Ashland", metro: "ashland-metro-wi" },
  marquette: { seat: "Montello", metro: "marquette-metro-wi" },
  crawford: { seat: "Prairie du Chien", metro: "crawford-metro-wi" },
  rusk: { seat: "Ladysmith", metro: "rusk-metro-wi" },
  price: { seat: "Phillips", metro: "price-metro-wi" },
  buffalo: { seat: "Alma", metro: "buffalo-metro-wi" },
  forest: { seat: "Crandon", metro: "forest-metro-wi" },
  pepin: { seat: "Durand", metro: "pepin-metro-wi" },
  iron: { seat: "Hurley", metro: "iron-metro-wi" },
  florence: { seat: "Florence", metro: "florence-metro-wi" },
  menominee: { seat: "Keshena", metro: "menominee-metro-wi" },
  clark: { seat: "Neillsville", metro: "clark-metro-wi" },
  vernon: { seat: "Viroqua", metro: "vernon-metro-wi" },
};

export function applyWisconsinCountyOverrides(county: LocalCounty): LocalCounty {
  if (county.stateSlug !== 'wisconsin') return county;
  const override = wisconsinCountyOverrides[county.slug];
  if (!override) return county;
  return { ...county, ...override };
}
