/** NM-MOVE-001. The PRC directory HTML is not a household-goods company roster. */
export const NEW_MEXICO_MOVE_SNAPSHOT = {
  route: '/new-mexico',
  regulator: 'New Mexico Public Regulation Commission',
  directoryUrl: 'https://www.prc.nm.gov/consumer-relations/company-directory/household-goods-movers/',
  directoryPrompt: 'Select a Household Goods Mover Company below to view their tariff',
  e360Url: 'https://e360.prc.nm.gov/',
  complaintUrl: 'https://complaints.nm-prc.org/',
  noJurisdictionUrl: 'https://www.prc.nm.gov/consumer-relations/no-jurisdiction-resource-list/',
  protectYourMoveUrl: 'https://www.protectyourmove.gov',
  retrievedAt: '2026-10-06',
  directoryHtmlBytes: 211258,
  directoryHtmlSha256: 'b73a70a33749ede004ef87fd8ec169eeebeda354365080a8d93d09eec11df0c0',
  yoastDatePublished: '2021-06-21',
  articleModifiedTime: '2023-06-20T20:58:14+00:00',
  pageClockIsRosterClock: false,
  navigationAnchors: 71,
  navigationAnchorsWereCompanyRows: false,
  hhgRoster: 'NOT_ACQUIRED',
  authorityRows: null,
  directoryCompanyRowsInHtml: 'NONE_PRESENT',
  directoryTariffLinksInHtml: 'NONE_PRESENT',
  e360AnnouncedLive: '2026-01-26',
  e360IsCountedRoster: false,
  providerComplaintRows: 'NOT_ACQUIRED',
  complaintFormIsCensus: false,
  tariffCorpus: 'NOT_ACQUIRED',
  usdotMcBridges: 'NOT_ACQUIRED',
  insurance: 'NOT_ACQUIRED',
  enforcementOrders: 'NOT_ACQUIRED',
  applicationIsActiveAuthority: false,
  otherUtilityDirectoriesParsedAsMovers: false,
  nameOnlyJoins: 0,
  graphWrites: 0,
  newCanonicalOrganizations: 0,
} as const;
