/** WI-MOVE-001: WisDOT publishes LC authority rules, but no clean public LC/HHG roster was acquired. */
export const WISCONSIN_MOVE_SNAPSHOT = {
  regulator: 'Wisconsin Department of Transportation, DMV Motor Carrier Services',
  authorityUrl: 'https://www.wisconsindot.gov/Pages/dmv/com-drv-vehs/mtr-car-trkr/mc-authority.aspx',
  applicationUrl: 'https://wisconsindot.gov/Documents/formdocs/mv2843.pdf',
  insuranceUrl: 'https://wisconsindot.gov/Pages/dmv/com-drv-vehs/mtr-car-trkr/mc-ins.aspx',
  intrastateComplaintUrl: 'https://datcp.wi.gov/Pages/Programs_Services/Complaints.aspx',
  interstateComplaintUrl: 'https://www.fmcsa.dot.gov/protect-your-move/file-a-complaint',
  retrievedAt: '2026-09-29',
  applicationFormDate: '2021-06',
  generatedAt: '2026-09-29T15:36:44Z',
  lcAuthorityVerification: 'KNOWN',
  lcRoster: 'NOT_ACQUIRED',
  householdGoodsRoster: 'NOT_ACQUIRED',
  lcRows: null,
  distinctLcAuthorities: null,
  householdGoodsRows: null,
  rowsWithUsdot: null,
  distinctUsdots: null,
  rowsWithMc: null,
  distinctMcs: null,
  exactFederalBridges: null,
  unmatchedStateRows: null,
  providerInsuranceStatus: 'NOT_ACQUIRED',
  providerComplaintRows: 'NOT_ACQUIRED',
  enforcementCapability: 'PARTIAL',
  providerEnforcementRows: 'NOT_ACQUIRED',
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
