export const WEST_VIRGINIA_MOVE_SNAPSHOT = {
  ticket: "WV-MOVE-001",
  route: "/west-virginia",
  regulator: "Public Service Commission of West Virginia, Transportation Division / Motor Carrier Section",
  retrievedAt: "2026-10-06",
  hhgRoster: "NOT_ACQUIRED",
  authorityRows: null,
  certificateSearchUrl: "http://www.psc.state.wv.us/scripts/utilities/tblMCCertificatesSearch.cfm",
  rulesUrl: "https://www.psc.state.wv.us/forms/motorcarrierrules-2022Full.pdf",
  applicationIsAuthority: false,
  tariffIsCurrentAuthority: false,
  insuranceRequirementIsObservedCoverage: false,
  formEObservations: "NOT_ACQUIRED",
  ucrIsHhgAuthority: false,
  fmcsaIsStateAuthority: false,
  usdotBridges: "NOT_ACQUIRED",
  pscOrders: "NOT_ACQUIRED",
  suspensionOrRevocationRoster: "NOT_ACQUIRED",
  graphWrites: 0,
  newCanonicalOrganizations: 0,
  nameOnlyJoins: 0,
  protectYourMoveUrl: "https://www.protectyourmove.gov",
  ucrUrl: "https://www.ucr.gov/",
} as const;
