import assert from "node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";
import{classifyServiceClaim,extractServiceClaims,geographyConflict,mayUseAsNegativeGroundTruth,normalizeServiceClaim}from"../lib/move-v2/geography/service-area-normalization";import{evidenceTier,findLocalMoversByOriginCounty,mayEnterOriginSearch,orderOriginResults,placementInvalidationReasons,resolveOriginZip,searchInputsAffectTrustworthiness}from"../lib/move-v2/geography/origin-search";import{DERIVED_MODEL_VERSION,shouldSupersedeDerived}from"../lib/move-v2/geography/derived-placement";import{evaluateActivation}from"../lib/move-v2/geography/model-activation";
import{evaluateExclusions,evaluateExhaustive,evaluatePositiveKnown,spearman}from"../lib/move-v2/geography/shadow-evaluation";
const counties=[{name:"King",geoid:"53033"},{name:"Palm Beach",geoid:"12099"}];
test("explicit county match",()=>assert.equal(normalizeServiceClaim("We serve King County.",counties)[0].normalizedGeoid,"53033"));
test("explicit city match uses Census Place",()=>{const x=normalizeServiceClaim("Serving Bellevue.",counties,[{name:"Bellevue",geoid:"5305210"}])[0];assert.equal(x.geographyType,"PLACE");assert.equal(x.normalizedGeoid,"5305210")});
test("city does not imply full county",()=>assert.ok(normalizeServiceClaim("Serving Bellevue.",counties,[{name:"Bellevue",geoid:"5305210"}]).every(x=>x.geographyType!=="COUNTY")));
test("explicit ZIP match",()=>assert.equal(normalizeServiceClaim("Our service area includes 98101.",counties)[0].geographyType,"ZIP"));
test("region normalization retains provenance",()=>{const x=normalizeServiceClaim("Serving Puget Sound.",counties)[0];assert.equal(x.geographyType,"REGION");assert.equal(x.normalizedGeoid,null)});
test("vague region is not silently treated as counties",()=>assert.ok(normalizeServiceClaim("Serving South Florida.",counties).every(x=>x.geographyType!=="COUNTY")));
test("provider exclusion geography",()=>assert.equal(normalizeServiceClaim("We do not serve Palm Beach County.",counties)[0].isExclusion,true));
test("positive explicit claim is positive-only ground truth",()=>assert.equal(mayUseAsNegativeGroundTruth(normalizeServiceClaim("We serve King County.",counties)[0]),false));
test("exhaustive claim supports overcoverage evaluation",()=>assert.equal(mayUseAsNegativeGroundTruth(normalizeServiceClaim("Areas we serve: King County.",counties)[0]),true));
test("example location mention is rejected",()=>assert.equal(classifyServiceClaim("Moving from Miami to Orlando? We can help."),"EXAMPLE_LOCATION_MENTION"));
test("blog-style city mention is rejected",()=>assert.equal(normalizeServiceClaim("For example, moving from Seattle to Bellevue?",counties,[{name:"Bellevue",geoid:"5305210"}])[0].normalizedGeoid,null));
test("service area conflict goes to review",()=>assert.equal(geographyConflict([...normalizeServiceClaim("We serve King County.",counties),...normalizeServiceClaim("We do not serve King County.",counties)]),true));
test("contact ZIP alone is not a service claim",()=>assert.deepEqual(extractServiceClaims("Contact us at 1 Main St, Seattle WA 98101."),[]));
test("shadow model never replaces explicit tier",()=>assert.ok(evidenceTier("PROVIDER_EXPLICIT_COUNTY")<evidenceTier("TRUSTHUB_DERIVED_HOME_COUNTY")));
test("model V1 remains historical when no V2 is published",()=>assert.equal(DERIVED_MODEL_VERSION,"MOVE_LOCAL_DERIVED_2026_08_V1"));
test("ZIP resolves to ZCTA",async()=>{const db={query:async()=>({rows:[{postal_zip:"98101",zcta:"98101",status:"GEOGRAPHIC_ZCTA",state:"WA",primary_county_geoid:"53033",explanation:"ZCTA caveat"}]})};assert.equal((await resolveOriginZip(db,"98101")).zcta,"98101")});
test("non-geographic ZIP remains unsupported",async()=>{const db={query:async()=>({rows:[]})};assert.equal((await resolveOriginZip(db,"99999")).status,"UNSUPPORTED_NON_GEOGRAPHIC")});
test("invalid ZIP remains review",async()=>{const db={query:async()=>({rows:[]})};assert.equal((await resolveOriginZip(db,"98A01")).status,"REVIEW")});
test("ZIP county crossings are separately modeled",()=>{const sql=readFileSync("supabase/migrations/20260816430000_move_v2_origin_search_calibration.sql","utf8");assert.match(sql,/CROSS_COUNTY/);assert.match(sql,/zcta_county_relationship/)});
test("state eligibility precedes geography",()=>assert.equal(mayEnterOriginSearch({state:"WA",eligibility:"STATE_AUTHORITY_REVIEW",role:"MOVER",identityResolved:true}),false));
test("broker excluded",()=>assert.equal(mayEnterOriginSearch({state:"WA",eligibility:"STATE_VERIFIED_MOVING_BROKER",role:"BROKER",identityResolved:true}),false));
test("inactive mover excluded",()=>assert.equal(mayEnterOriginSearch({state:"FL",eligibility:"STATE_INACTIVE_LOCAL_MOVER",role:"MOVER",identityResolved:true}),false));
test("Illinois explicit eligible mover may enter",()=>assert.equal(mayEnterOriginSearch({state:"IL",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER",identityResolved:true}),true));
test("derived edge excluded from ordinary tier",()=>assert.equal(evidenceTier("DERIVED_EDGE_INTERSECTION"),99));
test("explicit result orders ahead of derived",()=>assert.equal(orderOriginResults([{providerId:"d",placementReason:"TRUSTHUB_DERIVED_HOME_COUNTY"},{providerId:"e",placementReason:"PROVIDER_EXPLICIT_COUNTY"}])[0].providerId,"e"));
test("paid status has no effect",()=>{const x={state:"WA",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER" as const,identityResolved:true};assert.equal(mayEnterOriginSearch(x),mayEnterOriginSearch({...x,subscription:"PAID"}))});
test("ratings have no effect",()=>{const x={state:"WA",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER" as const,identityResolved:true};assert.equal(mayEnterOriginSearch(x),mayEnterOriginSearch({...x,rating:5}))});
test("distance does not alter trustworthiness",()=>assert.equal(searchInputsAffectTrustworthiness(),false));
test("placement invalidates on authority and geography change",()=>assert.deepEqual(placementInvalidationReasons({authorityChanged:true,explicitChanged:true}),["authorityChanged","explicitChanged"]));
test("explicit geography supersedes derived",()=>assert.equal(shouldSupersedeDerived(1),true));
test("NJ excluded",()=>assert.equal(mayEnterOriginSearch({state:"NJ",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER",identityResolved:true}),false));
test("auto transport excluded",()=>assert.equal(mayEnterOriginSearch({state:"FL",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER",identityResolved:true,vertical:"AUTO_TRANSPORT"}),false));
test("search-model ordering rerun is idempotent",()=>{const x=[{providerId:"b",placementReason:"TRUSTHUB_DERIVED_HOME_COUNTY"},{providerId:"a",placementReason:"TRUSTHUB_DERIVED_HOME_COUNTY"}];assert.deepEqual(orderOriginResults(x),orderOriginResults(x))});
test("production-facing reads exclude experimental derived by default",async()=>{let sql="";await findLocalMoversByOriginCounty({query:async(q)=>{sql=q;return{rows:[]}}},"WA","53033");assert.match(sql,/not like 'TRUSTHUB_DERIVED%'/)});
test("Preview may explicitly include experimental derived",async()=>{let sql="";await findLocalMoversByOriginCounty({query:async(q)=>{sql=q;return{rows:[]}}},"WA","53033",{includeExperimentalDerived:true});assert.doesNotMatch(sql,/not like 'TRUSTHUB_DERIVED%'/)});
test("V1 activation fails insufficient evidence",()=>assert.equal(evaluateActivation({positiveProviders:25,exhaustiveProviders:10,knownPositiveRecall:1,exclusionViolationRate:0,exhaustiveOvercoverage:.1,urbanProviders:20,ruralProviders:10,fleetBands:3,manualQaPassed:true}).passed,false));
test("positive claims do not create false positives",()=>assert.deepEqual(evaluatePositiveKnown(new Set(["A"]),new Set(["A","B"])).knownPositiveRecall,1));
test("exhaustive claims measure overcoverage",()=>assert.equal(evaluateExhaustive(new Set(["A"]),new Set(["A","B"])).overcoverage,.5));
test("exclusion violations are counted",()=>assert.equal(evaluateExclusions(new Set(["B"]),new Set(["A","B"])).violationCount,1));
test("predictor analysis is descriptive and deterministic",()=>assert.equal(spearman([1,2,3],[10,20,30]),1));
