/* eslint-disable @typescript-eslint/no-explicit-any */
import test from 'node:test'; import assert from 'node:assert/strict'; import { existsSync, readFileSync } from 'node:fs';
import { approveLaunchRelease, auditLaunchRelease, LAUNCH_RELEASE_VERSION } from '../lib/move-v2/launch-candidate/release-approval';
import { adaptV1Company, hasComposedV1Fields } from '../lib/move-v2/launch-candidate/compatibility';
import { enforceRateLimit, publicError, resetRateLimitsForTest, validateCompareIds, validateProviderId, validateZip } from '../lib/move-v2/launch-candidate/public-read-security';
import { MOVE_LAUNCH_EVENTS, resetAnalyticsDedupeForTest, safeMoveEvent } from '../lib/move-v2/launch-candidate/analytics';
import { providerRouteDecision, providerRoutingAudit } from '../lib/move-v2/launch-candidate/provider-routing';
import { selectLaunchSitemap } from '../lib/move-v2/launch-candidate/sitemap-selection';
import { cutover, failureBehavior, rollback, V1_STATE } from '../lib/move-v2/launch-candidate/rehearsal';
import { getDiscoveryRelease, getProviderTrustReport, searchLocalMovers } from '../lib/move-v2/consumer-discovery/server-read';
import golden from '../lib/move-v2/migration/seo-golden-set.json';

test('86/86 immutable release accounts for FL 41 and WA 45',()=>{const a=approveLaunchRelease();assert.equal(a.providers,86);assert.deepEqual(a.byState,{FL:41,WA:45});assert.equal(a.duplicates,0);assert.equal(a.verifiedLocations,52);assert.equal(a.reviewLocations,34);assert.equal(a.explicitService,5);assert.equal(LAUNCH_RELEASE_VERSION,'MOVE_CONSUMER_DISCOVERY_2026_08_V2');});
test('review-location providers remain available without fake distance',()=>{const r=getDiscoveryRelease().providers.find(p=>p.locationStatus==='LOCATION_REVIEW')!;const result=searchLocalMovers({originZip:r.state==='FL'?'33401':'98101'}).results.find((p:any)=>p.provider_id===r.providerId) as any;assert.ok(result);assert.equal(result.approximate_distance_miles,null);});
test('release approval is same-input immutable',()=>assert.deepEqual(auditLaunchRelease(),auditLaunchRelease()));
test('V1 usdot_status compatibility derives without mutation',()=>{const row={id:'1',slug:'x',name:'X',authority_active:true};const adapted=adaptV1Company(row);assert.equal(adapted.usdot_status,'ACTIVE');assert.equal('usdot_status' in row,false);assert.equal(hasComposedV1Fields(row),true);});
test('provider routing exact uses old canonical while unresolved remain V1',()=>{assert.equal(providerRoutingAudit().total,50);assert.deepEqual(providerRoutingAudit(),{total:50,exact:33,review:1,unmatched:16});const exact=providerRouteDecision('allied-van-lines');assert.equal(exact.mode,'V2_COMPOSED');assert.equal((exact as any).canonicalPath,'/companies/allied-van-lines');assert.equal(providerRouteDecision('international-van-lines').mode,'V1_FALLBACK');});
test('public validation rejects malformed and excessive inputs',()=>{assert.throws(()=>validateZip('3340x'));assert.throws(()=>validateProviderId('guess'));assert.throws(()=>validateCompareIds(Array.from({length:5},(_,i)=>`${i}0000000-0000-4000-8000-000000000000`)));});
test('public rate limit is bounded and redacted',()=>{resetRateLimitsForTest();for(let i=0;i<40;i++)enforceRateLimit('search','client',0);assert.throws(()=>enforceRateLimit('search','client',0));assert.deepEqual(publicError(new Error('database password secret')).body,{error:'RESEARCH_TEMPORARILY_UNAVAILABLE'});});
test('public Trust Report excludes internal decisions',()=>{const id=getDiscoveryRelease().providers[0].providerId;const json=JSON.stringify(getProviderTrustReport(id));assert.doesNotMatch(json,/decisionVersion|conflicts|observations|reviewer|service.role/i);});
test('analytics names and fields are privacy bounded and deduplicated',()=>{assert.equal(MOVE_LAUNCH_EVENTS.length,13);assert.throws(()=>safeMoveEvent('move_search',{originZip:'33401'}));resetAnalyticsDedupeForTest();assert.ok(safeMoveEvent('move_search',{state:'FL',move_path:'local'},'one'));assert.equal(safeMoveEvent('move_search',{state:'FL'},'one'),null);});
test('approved sitemap excludes redirects and internals',()=>{const rows=[{path:'/',status:200,indexable:true,canonical:'https://www.movetrusthub.com',decision:'REBUILD_IN_V2_SAME_URL'},{path:'/methodology',status:308,indexable:false,canonical:'https://www.movetrusthub.com/about/how-we-score-movers',decision:'RETIRE_WITH_301'},{path:'/experience-lab/v2',status:200,indexable:false,canonical:'https://www.movetrusthub.com/experience-lab/v2',decision:'INTERNAL_ONLY / NOT PUBLIC'}];assert.deepEqual(selectLaunchSitemap(rows).map(r=>r.path),['/']);});
test('cutover and rollback preserve golden route contract',()=>{const launch=cutover(V1_STATE);assert.equal(launch.v2Reads,true);assert.equal(launch.release,LAUNCH_RELEASE_VERSION);assert.deepEqual(rollback(launch),V1_STATE);assert.equal(golden.length,28);for(const row of golden as any[])assert.equal(row.expectedStatus,200);});
test('failure injection degrades locally without mass 404 or secret leakage',()=>{for(const kind of ['RELEASE_UNAVAILABLE','PUBLIC_READ_ERROR','DB_COMPATIBILITY_FAILURE','RATE_LIMITER_UNAVAILABLE','PROVIDER_MAPPING_MISSING'] as const){const behavior=failureBehavior(kind);assert.equal(behavior.globalStatus,200);assert.equal(behavior.secretLeak,false);}});
test('Move Plan and calculator routes remain preserved',()=>{for(const path of ['app/(move)/my-move/page.tsx','app/(move)/moving-calculator/page.tsx'])assert.equal(existsSync(path),true);const source=readFileSync('app/(move)/moving-calculator/page.tsx','utf8');assert.match(source,/moving-calculator/);});
test('commercial and unsupported/experimental inputs remain absent',()=>{const source=readFileSync('lib/move-v2/consumer-discovery/server-read.ts','utf8');assert.doesNotMatch(source,/subscription|rating|reviewCount|paid/i);assert.equal(auditLaunchRelease().experimentalDerivedIncluded,false);assert.equal(searchLocalMovers({originZip:'07102'}).results.length,0);assert.equal(searchLocalMovers({originZip:'60601'}).results.length,0);});
