import assert from 'node:assert/strict';
import test from 'node:test';
import { classifyFmcsaProvider, preferCurrentMotus, preserveAuthorityRows } from '../lib/move-v2/fmcsa/classifier';
import { buildPublicDecision } from '../lib/move-v2/commercial-firewall';
import { selectDisplayName } from '../lib/move-v2/identity';
import type { CurrentAuthorityFact, FmcsaClassificationInput } from '../lib/move-v2/fmcsa/types';

const authority = (patch: Partial<CurrentAuthorityFact> = {}): CurrentAuthorityFact => ({ sourceRecordKey: 'carrier:1', docketNumber: 'MC0000000001', authorityType: 'Motor Carrier of Household Goods', authorityStatus: 'Active', cargoRequired: true, cargoOnFile: true, bondRequired: false, bondOnFile: false, minimumBipdCoverage: 750, bipdOnFile: 750, ...patch });
const input = (patch: Partial<FmcsaClassificationInput> = {}): FmcsaClassificationInput => ({ usdot: '1', censusStatus: 'A', carrierOperation: 'A', householdGoodsCargo: true, currentAuthorities: [], authorityEvents: [], brokerFinancialResponsibilityReported: false, knownV1Provider: false, ...patch });

test('A active HHG carrier without interstate authority is local candidate', () => assert.equal(classifyFmcsaProvider(input()).classification, 'LOCAL_INTRASTATE_CARRIER_CANDIDATE'));
test('B current interstate HHG authority is interstate carrier', () => assert.equal(classifyFmcsaProvider(input({ currentAuthorities: [authority()] })).classification, 'INTERSTATE_CARRIER'));
test('C historical revocation followed by restoration remains active and keeps history', () => assert.equal(classifyFmcsaProvider(input({ currentAuthorities: [authority()], authorityEvents: [{ sourceRecordKey: 'h1', docketNumber: 'MC0000000001', authorityType: 'Motor Carrier of Household Goods', authorityStatus: 'Revoked', eventDate: '20260101', sourceEra: 'MOTUS_CURRENT' }, { sourceRecordKey: 'h2', docketNumber: 'MC0000000001', authorityType: 'Motor Carrier of Household Goods', authorityStatus: 'Active', eventDate: '20260201', sourceEra: 'MOTUS_CURRENT' }] })).classification, 'INTERSTATE_CARRIER'));
test('D current revocation blocks interstate-active classification', () => assert.notEqual(classifyFmcsaProvider(input({ currentAuthorities: [authority()], authorityEvents: [{ sourceRecordKey: 'h1', docketNumber: 'MC0000000001', authorityType: 'Motor Carrier of Household Goods', authorityStatus: 'Revoked', eventDate: '20260301', sourceEra: 'MOTUS_CURRENT' }] })).classification, 'INTERSTATE_CARRIER'));
test('E broker with active authority and bond is authorized', () => assert.equal(classifyFmcsaProvider(input({ currentAuthorities: [authority({ authorityType: 'Broker of Household Goods', cargoRequired: false, cargoOnFile: false, bondRequired: true, bondOnFile: true, minimumBipdCoverage: null, bipdOnFile: null })] })).classification, 'AUTHORIZED_BROKER'));
test('F inactive broker is not active broker', () => assert.notEqual(classifyFmcsaProvider(input({ currentAuthorities: [authority({ authorityType: 'Broker of Household Goods', authorityStatus: 'Inactive' })] })).classification, 'AUTHORIZED_BROKER'));
test('G active broker missing financial responsibility needs review', () => assert.equal(classifyFmcsaProvider(input({ currentAuthorities: [authority({ authorityType: 'Broker of Household Goods', cargoRequired: false, cargoOnFile: false, bondRequired: true, bondOnFile: false, minimumBipdCoverage: null, bipdOnFile: null })] })).classification, 'NEEDS_REGULATORY_REVIEW'));
test('H independently valid carrier and broker is dual role', () => assert.equal(classifyFmcsaProvider(input({ currentAuthorities: [authority(), authority({ sourceRecordKey: 'broker:1', docketNumber: 'MC0000000002', authorityType: 'Broker of Household Goods', cargoRequired: false, cargoOnFile: false, bondRequired: true, bondOnFile: true, minimumBipdCoverage: null, bipdOnFile: null })] })).classification, 'DUAL_ROLE_CARRIER_BROKER'));
test('I DBA displays while legal name remains', () => { const legal = 'LEGAL LLC'; assert.equal(selectDisplayName(legal, 'DBA MOVERS'), 'DBA MOVERS'); assert.equal(legal, 'LEGAL LLC'); });
test('J legal name displays without DBA', () => assert.equal(selectDisplayName('LEGAL LLC'), 'LEGAL LLC'));
test('K current Motus wins while legacy is preserved', () => assert.deepEqual(preferCurrentMotus('MOTUS_ACTIVE', 'LEGACY_INACTIVE'), { current: 'MOTUS_ACTIVE', history: ['LEGACY_INACTIVE', 'MOTUS_ACTIVE'] }));
test('L multiple authority rows for one USDOT remain', () => assert.equal(preserveAuthorityRows([authority(), authority({ sourceRecordKey: '2' })]).length, 2));
test('M multiple dockets remain distinct', () => assert.deepEqual(preserveAuthorityRows([authority(), authority({ docketNumber: 'MC0000000002' })]).map((row) => row.docketNumber), ['MC0000000001', 'MC0000000002']))
test('N same-release dedupe key prevents duplicate evidence', () => assert.equal(new Map([authority(), authority()].map((row) => [row.sourceRecordKey, row])).size, 1));
test('O subscription state cannot enter classification/public output', () => { const classified = classifyFmcsaProvider(input()); const output = buildPublicDecision({ providerId: 'p1', classification: classified.classification, evidenceStrength: 1, moveEligible: true }); assert.equal('subscriptionStatus' in output, false); });
