import assert from "node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";
import{extractServiceClaims,geographyConflict,normalizeServiceClaim}from"../lib/move-v2/geography/service-area-normalization";import{evidenceTier,mayEnterOriginSearch,orderOriginResults,placementInvalidationReasons,resolveOriginZip,searchInputsAffectTrustworthiness}from"../lib/move-v2/geography/origin-search";import{DERIVED_MODEL_VERSION,shouldSupersedeDerived}from"../lib/move-v2/geography/derived-placement";
const counties=[{name:"King",geoid:"53033"},{name:"Palm Beach",geoid:"12099"}];
test("explicit county match",()=>assert.equal(normalizeServiceClaim("We serve King County.",counties)[0].normalizedGeoid,"53033"));
test("explicit city match",()=>assert.equal(normalizeServiceClaim("Serving Seattle and Bellevue.",counties,["Seattle","Bellevue"])[0].geographyType,"CITY"));
test("explicit ZIP match",()=>assert.equal(normalizeServiceClaim("Our service area includes 98101.",counties)[0].geographyType,"ZIP"));
test("region normalization retains provenance",()=>{const x=normalizeServiceClaim("Serving Puget Sound.",counties)[0];assert.equal(x.geographyType,"REGION");assert.equal(x.normalizedGeoid,null)});
test("vague region is not silently treated as counties",()=>assert.ok(normalizeServiceClaim("Serving South Florida.",counties).every(x=>x.geographyType!=="COUNTY")));
test("provider exclusion geography",()=>assert.equal(normalizeServiceClaim("We do not serve Palm Beach County.",counties)[0].isExclusion,true));
test("service area conflict goes to review",()=>assert.equal(geographyConflict([...normalizeServiceClaim("We serve King County.",counties),...normalizeServiceClaim("We do not serve King County.",counties)]),true));
test("contact ZIP alone is not a service claim",()=>assert.deepEqual(extractServiceClaims("Contact us at 1 Main St, Seattle WA 98101."),[]));
test("shadow model never replaces explicit tier",()=>assert.ok(evidenceTier("PROVIDER_EXPLICIT_COUNTY")<evidenceTier("TRUSTHUB_DERIVED_HOME_COUNTY")));
test("model V1 remains historical when no V2 is published",()=>assert.equal(DERIVED_MODEL_VERSION,"MOVE_LOCAL_DERIVED_2026_08_V1"));
test("ZIP resolves to ZCTA",async()=>{const db={query:async()=>({rows:[{postal_zip:"98101",zcta:"98101",status:"GEOGRAPHIC_ZCTA",state:"WA",primary_county_geoid:"53033",explanation:"ZCTA caveat"}]})};assert.equal((await resolveOriginZip(db,"98101")).zcta,"98101")});
test("non-geographic ZIP remains unsupported",async()=>{const db={query:async()=>({rows:[]})};assert.equal((await resolveOriginZip(db,"99999")).status,"UNSUPPORTED_NON_GEOGRAPHIC")});
test("invalid ZIP remains review",async()=>{const db={query:async()=>({rows:[]})};assert.equal((await resolveOriginZip(db,"98A01")).status,"REVIEW")});
test("ZIP county crossings are separately modeled",()=>{const sql=readFileSync("supabase/migrations/20260816430000_move_v2_origin_search_calibration.sql","utf8");assert.match(sql,/CROSS_COUNTY/);assert.match(sql,/zcta_county_relationship/)});
test("state eligibility precedes geography",()=>assert.equal(mayEnterOriginSearch({state:"WA",eligibility:"STATE_AUTHORITY_REVIEW",role:"MOVER",identityResolved:true}),false));
test("broker excluded",()=>assert.equal(mayEnterOriginSearch({state:"WA",eligibility:"STATE_VERIFIED_MOVING_BROKER",role:"BROKER",identityResolved:true}),false));
test("inactive mover excluded",()=>assert.equal(mayEnterOriginSearch({state:"FL",eligibility:"STATE_INACTIVE_LOCAL_MOVER",role:"MOVER",identityResolved:true}),false));
test("derived edge excluded from ordinary tier",()=>assert.equal(evidenceTier("DERIVED_EDGE_INTERSECTION"),99));
test("explicit result orders ahead of derived",()=>assert.equal(orderOriginResults([{providerId:"d",placementReason:"TRUSTHUB_DERIVED_HOME_COUNTY"},{providerId:"e",placementReason:"PROVIDER_EXPLICIT_COUNTY"}])[0].providerId,"e"));
test("paid status has no effect",()=>{const x={state:"WA",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER" as const,identityResolved:true};assert.equal(mayEnterOriginSearch(x),mayEnterOriginSearch({...x,subscription:"PAID"}))});
test("ratings have no effect",()=>{const x={state:"WA",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER" as const,identityResolved:true};assert.equal(mayEnterOriginSearch(x),mayEnterOriginSearch({...x,rating:5}))});
test("distance does not alter trustworthiness",()=>assert.equal(searchInputsAffectTrustworthiness(),false));
test("placement invalidates on authority and geography change",()=>assert.deepEqual(placementInvalidationReasons({authorityChanged:true,explicitChanged:true}),["authorityChanged","explicitChanged"]));
test("explicit geography supersedes derived",()=>assert.equal(shouldSupersedeDerived(1),true));
test("NJ excluded",()=>assert.equal(mayEnterOriginSearch({state:"NJ",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER",identityResolved:true}),false));
test("auto transport excluded",()=>assert.equal(mayEnterOriginSearch({state:"FL",eligibility:"STATE_VERIFIED_LOCAL_MOVER",role:"MOVER",identityResolved:true,vertical:"AUTO_TRANSPORT"}),false));
test("search-model ordering rerun is idempotent",()=>{const x=[{providerId:"b",placementReason:"TRUSTHUB_DERIVED_HOME_COUNTY"},{providerId:"a",placementReason:"TRUSTHUB_DERIVED_HOME_COUNTY"}];assert.deepEqual(orderOriginResults(x),orderOriginResults(x))});
