import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** Colorado curated county corridor links — batch 1+2+3: 44/64 */
const CO_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  'el-paso': [
    { slug: 'douglas', name: 'Douglas', seat: 'Castle Rock', href: '/local-movers/colorado/douglas', displayLabel: 'Douglas County, CO' },
    { slug: 'pueblo', name: 'Pueblo', seat: 'Pueblo', href: '/local-movers/colorado/pueblo', displayLabel: 'Pueblo County, CO' },
    { slug: 'fremont', name: 'Fremont', seat: 'Canon City', href: '/local-movers/colorado/fremont', displayLabel: 'Fremont County, CO' },
    { slug: 'teller', name: 'Teller', seat: 'Cripple Creek', href: '/local-movers/colorado/teller', displayLabel: 'Teller County, CO' },
    { slug: 'arapahoe', name: 'Arapahoe', seat: 'Littleton', href: '/local-movers/colorado/arapahoe', displayLabel: 'Arapahoe County, CO' },
  ],
  denver: [
    { slug: 'arapahoe', name: 'Arapahoe', seat: 'Littleton', href: '/local-movers/colorado/arapahoe', displayLabel: 'Arapahoe County, CO' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Golden', href: '/local-movers/colorado/jefferson', displayLabel: 'Jefferson County, CO' },
    { slug: 'adams', name: 'Adams', seat: 'Brighton', href: '/local-movers/colorado/adams', displayLabel: 'Adams County, CO' },
    { slug: 'broomfield', name: 'Broomfield', seat: 'Broomfield', href: '/local-movers/colorado/broomfield', displayLabel: 'Broomfield County, CO' },
    { slug: 'boulder', name: 'Boulder', seat: 'Boulder', href: '/local-movers/colorado/boulder', displayLabel: 'Boulder County, CO' },
  ],
  arapahoe: [
    { slug: 'denver', name: 'Denver', seat: 'Denver', href: '/local-movers/colorado/denver', displayLabel: 'Denver County, CO' },
    { slug: 'douglas', name: 'Douglas', seat: 'Castle Rock', href: '/local-movers/colorado/douglas', displayLabel: 'Douglas County, CO' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Golden', href: '/local-movers/colorado/jefferson', displayLabel: 'Jefferson County, CO' },
    { slug: 'el-paso', name: 'El Paso', seat: 'Colorado Springs', href: '/local-movers/colorado/el-paso', displayLabel: 'El Paso County, CO' },
    { slug: 'elbert', name: 'Elbert', seat: 'Kiowa', href: '/local-movers/colorado/elbert', displayLabel: 'Elbert County, CO' },
  ],
  jefferson: [
    { slug: 'denver', name: 'Denver', seat: 'Denver', href: '/local-movers/colorado/denver', displayLabel: 'Denver County, CO' },
    { slug: 'arapahoe', name: 'Arapahoe', seat: 'Littleton', href: '/local-movers/colorado/arapahoe', displayLabel: 'Arapahoe County, CO' },
    { slug: 'adams', name: 'Adams', seat: 'Brighton', href: '/local-movers/colorado/adams', displayLabel: 'Adams County, CO' },
    { slug: 'clear-creek', name: 'Clear Creek', seat: 'Georgetown', href: '/local-movers/colorado/clear-creek', displayLabel: 'Clear Creek County, CO' },
    { slug: 'boulder', name: 'Boulder', seat: 'Boulder', href: '/local-movers/colorado/boulder', displayLabel: 'Boulder County, CO' },
  ],
  adams: [
    { slug: 'denver', name: 'Denver', seat: 'Denver', href: '/local-movers/colorado/denver', displayLabel: 'Denver County, CO' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Golden', href: '/local-movers/colorado/jefferson', displayLabel: 'Jefferson County, CO' },
    { slug: 'weld', name: 'Weld', seat: 'Greeley', href: '/local-movers/colorado/weld', displayLabel: 'Weld County, CO' },
    { slug: 'broomfield', name: 'Broomfield', seat: 'Broomfield', href: '/local-movers/colorado/broomfield', displayLabel: 'Broomfield County, CO' },
    { slug: 'larimer', name: 'Larimer', seat: 'Fort Collins', href: '/local-movers/colorado/larimer', displayLabel: 'Larimer County, CO' },
  ],
  douglas: [
    { slug: 'denver', name: 'Denver', seat: 'Denver', href: '/local-movers/colorado/denver', displayLabel: 'Denver County, CO' },
    { slug: 'arapahoe', name: 'Arapahoe', seat: 'Littleton', href: '/local-movers/colorado/arapahoe', displayLabel: 'Arapahoe County, CO' },
    { slug: 'el-paso', name: 'El Paso', seat: 'Colorado Springs', href: '/local-movers/colorado/el-paso', displayLabel: 'El Paso County, CO' },
    { slug: 'teller', name: 'Teller', seat: 'Cripple Creek', href: '/local-movers/colorado/teller', displayLabel: 'Teller County, CO' },
    { slug: 'park', name: 'Park', seat: 'Fairplay', href: '/local-movers/colorado/park', displayLabel: 'Park County, CO' },
  ],
  weld: [
    { slug: 'adams', name: 'Adams', seat: 'Brighton', href: '/local-movers/colorado/adams', displayLabel: 'Adams County, CO' },
    { slug: 'larimer', name: 'Larimer', seat: 'Fort Collins', href: '/local-movers/colorado/larimer', displayLabel: 'Larimer County, CO' },
    { slug: 'morgan', name: 'Morgan', seat: 'Fort Morgan', href: '/local-movers/colorado/morgan', displayLabel: 'Morgan County, CO' },
    { slug: 'logan', name: 'Logan', seat: 'Sterling', href: '/local-movers/colorado/logan', displayLabel: 'Logan County, CO' },
    { slug: 'boulder', name: 'Boulder', seat: 'Boulder', href: '/local-movers/colorado/boulder', displayLabel: 'Boulder County, CO' },
  ],
  larimer: [
    { slug: 'weld', name: 'Weld', seat: 'Greeley', href: '/local-movers/colorado/weld', displayLabel: 'Weld County, CO' },
    { slug: 'boulder', name: 'Boulder', seat: 'Boulder', href: '/local-movers/colorado/boulder', displayLabel: 'Boulder County, CO' },
    { slug: 'adams', name: 'Adams', seat: 'Brighton', href: '/local-movers/colorado/adams', displayLabel: 'Adams County, CO' },
    { slug: 'morgan', name: 'Morgan', seat: 'Fort Morgan', href: '/local-movers/colorado/morgan', displayLabel: 'Morgan County, CO' },
    { slug: 'routt', name: 'Routt', seat: 'Steamboat Springs', href: '/local-movers/colorado/routt', displayLabel: 'Routt County, CO' },
  ],
  boulder: [
    { slug: 'larimer', name: 'Larimer', seat: 'Fort Collins', href: '/local-movers/colorado/larimer', displayLabel: 'Larimer County, CO' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Golden', href: '/local-movers/colorado/jefferson', displayLabel: 'Jefferson County, CO' },
    { slug: 'broomfield', name: 'Broomfield', seat: 'Broomfield', href: '/local-movers/colorado/broomfield', displayLabel: 'Broomfield County, CO' },
    { slug: 'adams', name: 'Adams', seat: 'Brighton', href: '/local-movers/colorado/adams', displayLabel: 'Adams County, CO' },
    { slug: 'weld', name: 'Weld', seat: 'Greeley', href: '/local-movers/colorado/weld', displayLabel: 'Weld County, CO' },
  ],
  pueblo: [
    { slug: 'el-paso', name: 'El Paso', seat: 'Colorado Springs', href: '/local-movers/colorado/el-paso', displayLabel: 'El Paso County, CO' },
    { slug: 'fremont', name: 'Fremont', seat: 'Canon City', href: '/local-movers/colorado/fremont', displayLabel: 'Fremont County, CO' },
    { slug: 'huerfano', name: 'Huerfano', seat: 'Walsenburg', href: '/local-movers/colorado/huerfano', displayLabel: 'Huerfano County, CO' },
    { slug: 'las-animas', name: 'Las Animas', seat: 'Trinidad', href: '/local-movers/colorado/las-animas', displayLabel: 'Las Animas County, CO' },
    { slug: 'otero', name: 'Otero', seat: 'La Junta', href: '/local-movers/colorado/otero', displayLabel: 'Otero County, CO' },
  ],
  mesa: [
    { slug: 'garfield', name: 'Garfield', seat: 'Glenwood Springs', href: '/local-movers/colorado/garfield', displayLabel: 'Garfield County, CO' },
    { slug: 'delta', name: 'Delta', seat: 'Delta', href: '/local-movers/colorado/delta', displayLabel: 'Delta County, CO' },
    { slug: 'montrose', name: 'Montrose', seat: 'Montrose', href: '/local-movers/colorado/montrose', displayLabel: 'Montrose County, CO' },
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
    { slug: 'routt', name: 'Routt', seat: 'Steamboat Springs', href: '/local-movers/colorado/routt', displayLabel: 'Routt County, CO' },
  ],
  broomfield: [
    { slug: 'denver', name: 'Denver', seat: 'Denver', href: '/local-movers/colorado/denver', displayLabel: 'Denver County, CO' },
    { slug: 'adams', name: 'Adams', seat: 'Brighton', href: '/local-movers/colorado/adams', displayLabel: 'Adams County, CO' },
    { slug: 'boulder', name: 'Boulder', seat: 'Boulder', href: '/local-movers/colorado/boulder', displayLabel: 'Boulder County, CO' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Golden', href: '/local-movers/colorado/jefferson', displayLabel: 'Jefferson County, CO' },
    { slug: 'weld', name: 'Weld', seat: 'Greeley', href: '/local-movers/colorado/weld', displayLabel: 'Weld County, CO' },
  ],
  garfield: [
    { slug: 'mesa', name: 'Mesa', seat: 'Grand Junction', href: '/local-movers/colorado/mesa', displayLabel: 'Mesa County, CO' },
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
    { slug: 'routt', name: 'Routt', seat: 'Steamboat Springs', href: '/local-movers/colorado/routt', displayLabel: 'Routt County, CO' },
    { slug: 'pitkin', name: 'Pitkin', seat: 'Aspen', href: '/local-movers/colorado/pitkin', displayLabel: 'Pitkin County, CO' },
    { slug: 'grand', name: 'Grand', seat: 'Hot Sulphur Springs', href: '/local-movers/colorado/grand', displayLabel: 'Grand County, CO' },
  ],
  'la-plata': [
    { slug: 'montezuma', name: 'Montezuma', seat: 'Cortez', href: '/local-movers/colorado/montezuma', displayLabel: 'Montezuma County, CO' },
    { slug: 'mesa', name: 'Mesa', seat: 'Grand Junction', href: '/local-movers/colorado/mesa', displayLabel: 'Mesa County, CO' },
    { slug: 'delta', name: 'Delta', seat: 'Delta', href: '/local-movers/colorado/delta', displayLabel: 'Delta County, CO' },
    { slug: 'archuleta', name: 'Archuleta', seat: 'Pagosa Springs', href: '/local-movers/colorado/archuleta', displayLabel: 'Archuleta County, CO' },
    { slug: 'san-juan', name: 'San Juan', seat: 'Silverton', href: '/local-movers/colorado/san-juan', displayLabel: 'San Juan County, CO' },
  ],
  eagle: [
    { slug: 'summit', name: 'Summit', seat: 'Breckenridge', href: '/local-movers/colorado/summit', displayLabel: 'Summit County, CO' },
    { slug: 'garfield', name: 'Garfield', seat: 'Glenwood Springs', href: '/local-movers/colorado/garfield', displayLabel: 'Garfield County, CO' },
    { slug: 'pitkin', name: 'Pitkin', seat: 'Aspen', href: '/local-movers/colorado/pitkin', displayLabel: 'Pitkin County, CO' },
    { slug: 'lake', name: 'Lake', seat: 'Leadville', href: '/local-movers/colorado/lake', displayLabel: 'Lake County, CO' },
    { slug: 'grand', name: 'Grand', seat: 'Hot Sulphur Springs', href: '/local-movers/colorado/grand', displayLabel: 'Grand County, CO' },
  ],
  fremont: [
    { slug: 'el-paso', name: 'El Paso', seat: 'Colorado Springs', href: '/local-movers/colorado/el-paso', displayLabel: 'El Paso County, CO' },
    { slug: 'pueblo', name: 'Pueblo', seat: 'Pueblo', href: '/local-movers/colorado/pueblo', displayLabel: 'Pueblo County, CO' },
    { slug: 'teller', name: 'Teller', seat: 'Cripple Creek', href: '/local-movers/colorado/teller', displayLabel: 'Teller County, CO' },
    { slug: 'park', name: 'Park', seat: 'Fairplay', href: '/local-movers/colorado/park', displayLabel: 'Park County, CO' },
    { slug: 'chaffee', name: 'Chaffee', seat: 'Salida', href: '/local-movers/colorado/chaffee', displayLabel: 'Chaffee County, CO' },
  ],
  montrose: [
    { slug: 'mesa', name: 'Mesa', seat: 'Grand Junction', href: '/local-movers/colorado/mesa', displayLabel: 'Mesa County, CO' },
    { slug: 'delta', name: 'Delta', seat: 'Delta', href: '/local-movers/colorado/delta', displayLabel: 'Delta County, CO' },
    { slug: 'montezuma', name: 'Montezuma', seat: 'Cortez', href: '/local-movers/colorado/montezuma', displayLabel: 'Montezuma County, CO' },
    { slug: 'garfield', name: 'Garfield', seat: 'Glenwood Springs', href: '/local-movers/colorado/garfield', displayLabel: 'Garfield County, CO' },
    { slug: 'ouray', name: 'Ouray', seat: 'Ouray', href: '/local-movers/colorado/ouray', displayLabel: 'Ouray County, CO' },
  ],
  delta: [
    { slug: 'mesa', name: 'Mesa', seat: 'Grand Junction', href: '/local-movers/colorado/mesa', displayLabel: 'Mesa County, CO' },
    { slug: 'montrose', name: 'Montrose', seat: 'Montrose', href: '/local-movers/colorado/montrose', displayLabel: 'Montrose County, CO' },
    { slug: 'garfield', name: 'Garfield', seat: 'Glenwood Springs', href: '/local-movers/colorado/garfield', displayLabel: 'Garfield County, CO' },
    { slug: 'gunnison', name: 'Gunnison', seat: 'Gunnison', href: '/local-movers/colorado/gunnison', displayLabel: 'Gunnison County, CO' },
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
  ],
  elbert: [
    { slug: 'douglas', name: 'Douglas', seat: 'Castle Rock', href: '/local-movers/colorado/douglas', displayLabel: 'Douglas County, CO' },
    { slug: 'el-paso', name: 'El Paso', seat: 'Colorado Springs', href: '/local-movers/colorado/el-paso', displayLabel: 'El Paso County, CO' },
    { slug: 'arapahoe', name: 'Arapahoe', seat: 'Littleton', href: '/local-movers/colorado/arapahoe', displayLabel: 'Arapahoe County, CO' },
    { slug: 'weld', name: 'Weld', seat: 'Greeley', href: '/local-movers/colorado/weld', displayLabel: 'Weld County, CO' },
    { slug: 'kit-carson', name: 'Kit Carson', seat: 'Burlington', href: '/local-movers/colorado/kit-carson', displayLabel: 'Kit Carson County, CO' },
  ],
  summit: [
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
    { slug: 'clear-creek', name: 'Clear Creek', seat: 'Georgetown', href: '/local-movers/colorado/clear-creek', displayLabel: 'Clear Creek County, CO' },
    { slug: 'park', name: 'Park', seat: 'Fairplay', href: '/local-movers/colorado/park', displayLabel: 'Park County, CO' },
    { slug: 'lake', name: 'Lake', seat: 'Leadville', href: '/local-movers/colorado/lake', displayLabel: 'Lake County, CO' },
    { slug: 'grand', name: 'Grand', seat: 'Hot Sulphur Springs', href: '/local-movers/colorado/grand', displayLabel: 'Grand County, CO' },
  ],
  morgan: [
    { slug: 'weld', name: 'Weld', seat: 'Greeley', href: '/local-movers/colorado/weld', displayLabel: 'Weld County, CO' },
    { slug: 'larimer', name: 'Larimer', seat: 'Fort Collins', href: '/local-movers/colorado/larimer', displayLabel: 'Larimer County, CO' },
    { slug: 'adams', name: 'Adams', seat: 'Brighton', href: '/local-movers/colorado/adams', displayLabel: 'Adams County, CO' },
    { slug: 'washington', name: 'Washington', seat: 'Akron', href: '/local-movers/colorado/washington', displayLabel: 'Washington County, CO' },
    { slug: 'logan', name: 'Logan', seat: 'Sterling', href: '/local-movers/colorado/logan', displayLabel: 'Logan County, CO' },
  ],
  montezuma: [
    { slug: 'la-plata', name: 'La Plata', seat: 'Durango', href: '/local-movers/colorado/la-plata', displayLabel: 'La Plata County, CO' },
    { slug: 'mesa', name: 'Mesa', seat: 'Grand Junction', href: '/local-movers/colorado/mesa', displayLabel: 'Mesa County, CO' },
    { slug: 'archuleta', name: 'Archuleta', seat: 'Pagosa Springs', href: '/local-movers/colorado/archuleta', displayLabel: 'Archuleta County, CO' },
    { slug: 'san-miguel', name: 'San Miguel', seat: 'Telluride', href: '/local-movers/colorado/san-miguel', displayLabel: 'San Miguel County, CO' },
    { slug: 'dolores', name: 'Dolores', seat: 'Dove Creek', href: '/local-movers/colorado/dolores', displayLabel: 'Dolores County, CO' },
  ],
  routt: [
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
    { slug: 'garfield', name: 'Garfield', seat: 'Glenwood Springs', href: '/local-movers/colorado/garfield', displayLabel: 'Garfield County, CO' },
    { slug: 'summit', name: 'Summit', seat: 'Breckenridge', href: '/local-movers/colorado/summit', displayLabel: 'Summit County, CO' },
    { slug: 'larimer', name: 'Larimer', seat: 'Fort Collins', href: '/local-movers/colorado/larimer', displayLabel: 'Larimer County, CO' },
    { slug: 'moffat', name: 'Moffat', seat: 'Craig', href: '/local-movers/colorado/moffat', displayLabel: 'Moffat County, CO' },
  ],
  teller: [
    { slug: 'el-paso', name: 'El Paso', seat: 'Colorado Springs', href: '/local-movers/colorado/el-paso', displayLabel: 'El Paso County, CO' },
    { slug: 'douglas', name: 'Douglas', seat: 'Castle Rock', href: '/local-movers/colorado/douglas', displayLabel: 'Douglas County, CO' },
    { slug: 'fremont', name: 'Fremont', seat: 'Canon City', href: '/local-movers/colorado/fremont', displayLabel: 'Fremont County, CO' },
    { slug: 'park', name: 'Park', seat: 'Fairplay', href: '/local-movers/colorado/park', displayLabel: 'Park County, CO' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Golden', href: '/local-movers/colorado/jefferson', displayLabel: 'Jefferson County, CO' },
  ],
  chaffee: [
    { slug: 'gunnison', name: 'Gunnison', seat: 'Gunnison', href: '/local-movers/colorado/gunnison', displayLabel: 'Gunnison County, CO' },
    { slug: 'lake', name: 'Lake', seat: 'Leadville', href: '/local-movers/colorado/lake', displayLabel: 'Lake County, CO' },
    { slug: 'park', name: 'Park', seat: 'Fairplay', href: '/local-movers/colorado/park', displayLabel: 'Park County, CO' },
    { slug: 'fremont', name: 'Fremont', seat: 'Canon City', href: '/local-movers/colorado/fremont', displayLabel: 'Fremont County, CO' },
    { slug: 'summit', name: 'Summit', seat: 'Breckenridge', href: '/local-movers/colorado/summit', displayLabel: 'Summit County, CO' },
  ],
  logan: [
    { slug: 'weld', name: 'Weld', seat: 'Greeley', href: '/local-movers/colorado/weld', displayLabel: 'Weld County, CO' },
    { slug: 'morgan', name: 'Morgan', seat: 'Fort Morgan', href: '/local-movers/colorado/morgan', displayLabel: 'Morgan County, CO' },
    { slug: 'yuma', name: 'Yuma', seat: 'Wray', href: '/local-movers/colorado/yuma', displayLabel: 'Yuma County, CO' },
    { slug: 'washington', name: 'Washington', seat: 'Akron', href: '/local-movers/colorado/washington', displayLabel: 'Washington County, CO' },
    { slug: 'sedgwick', name: 'sedgwick', seat: 'sedgwick', href: '/local-movers/colorado/sedgwick', displayLabel: 'sedgwick County, CO' },
  ],
  park: [
    { slug: 'jefferson', name: 'Jefferson', seat: 'Golden', href: '/local-movers/colorado/jefferson', displayLabel: 'Jefferson County, CO' },
    { slug: 'clear-creek', name: 'Clear Creek', seat: 'Georgetown', href: '/local-movers/colorado/clear-creek', displayLabel: 'Clear Creek County, CO' },
    { slug: 'summit', name: 'Summit', seat: 'Breckenridge', href: '/local-movers/colorado/summit', displayLabel: 'Summit County, CO' },
    { slug: 'lake', name: 'Lake', seat: 'Leadville', href: '/local-movers/colorado/lake', displayLabel: 'Lake County, CO' },
    { slug: 'chaffee', name: 'Chaffee', seat: 'Salida', href: '/local-movers/colorado/chaffee', displayLabel: 'Chaffee County, CO' },
  ],
  otero: [
    { slug: 'pueblo', name: 'Pueblo', seat: 'Pueblo', href: '/local-movers/colorado/pueblo', displayLabel: 'Pueblo County, CO' },
    { slug: 'las-animas', name: 'Las Animas', seat: 'Trinidad', href: '/local-movers/colorado/las-animas', displayLabel: 'Las Animas County, CO' },
    { slug: 'huerfano', name: 'Huerfano', seat: 'Walsenburg', href: '/local-movers/colorado/huerfano', displayLabel: 'Huerfano County, CO' },
    { slug: 'prowers', name: 'Prowers', seat: 'Lamar', href: '/local-movers/colorado/prowers', displayLabel: 'Prowers County, CO' },
    { slug: 'crowley', name: 'crowley', seat: 'crowley', href: '/local-movers/colorado/crowley', displayLabel: 'crowley County, CO' },
  ],
  gunnison: [
    { slug: 'pitkin', name: 'Pitkin', seat: 'Aspen', href: '/local-movers/colorado/pitkin', displayLabel: 'Pitkin County, CO' },
    { slug: 'lake', name: 'Lake', seat: 'Leadville', href: '/local-movers/colorado/lake', displayLabel: 'Lake County, CO' },
    { slug: 'chaffee', name: 'Chaffee', seat: 'Salida', href: '/local-movers/colorado/chaffee', displayLabel: 'Chaffee County, CO' },
    { slug: 'mesa', name: 'Mesa', seat: 'Grand Junction', href: '/local-movers/colorado/mesa', displayLabel: 'Mesa County, CO' },
    { slug: 'delta', name: 'Delta', seat: 'Delta', href: '/local-movers/colorado/delta', displayLabel: 'Delta County, CO' },
  ],
  grand: [
    { slug: 'summit', name: 'Summit', seat: 'Breckenridge', href: '/local-movers/colorado/summit', displayLabel: 'Summit County, CO' },
    { slug: 'clear-creek', name: 'Clear Creek', seat: 'Georgetown', href: '/local-movers/colorado/clear-creek', displayLabel: 'Clear Creek County, CO' },
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
    { slug: 'routt', name: 'Routt', seat: 'Steamboat Springs', href: '/local-movers/colorado/routt', displayLabel: 'Routt County, CO' },
    { slug: 'larimer', name: 'Larimer', seat: 'Fort Collins', href: '/local-movers/colorado/larimer', displayLabel: 'Larimer County, CO' },
  ],
  alamosa: [
    { slug: 'conejos', name: 'Conejos', seat: 'Conejos', href: '/local-movers/colorado/conejos', displayLabel: 'Conejos County, CO' },
    { slug: 'rio-grande', name: 'Rio Grande', seat: 'Del Norte', href: '/local-movers/colorado/rio-grande', displayLabel: 'Rio Grande County, CO' },
    { slug: 'saguache', name: 'saguache', seat: 'saguache', href: '/local-movers/colorado/saguache', displayLabel: 'saguache County, CO' },
    { slug: 'costilla', name: 'costilla', seat: 'costilla', href: '/local-movers/colorado/costilla', displayLabel: 'costilla County, CO' },
  ],
  pitkin: [
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
    { slug: 'gunnison', name: 'Gunnison', seat: 'Gunnison', href: '/local-movers/colorado/gunnison', displayLabel: 'Gunnison County, CO' },
    { slug: 'lake', name: 'Lake', seat: 'Leadville', href: '/local-movers/colorado/lake', displayLabel: 'Lake County, CO' },
    { slug: 'garfield', name: 'Garfield', seat: 'Glenwood Springs', href: '/local-movers/colorado/garfield', displayLabel: 'Garfield County, CO' },
    { slug: 'mesa', name: 'Mesa', seat: 'Grand Junction', href: '/local-movers/colorado/mesa', displayLabel: 'Mesa County, CO' },
  ],
  archuleta: [
    { slug: 'la-plata', name: 'La Plata', seat: 'Durango', href: '/local-movers/colorado/la-plata', displayLabel: 'La Plata County, CO' },
    { slug: 'rio-grande', name: 'Rio Grande', seat: 'Del Norte', href: '/local-movers/colorado/rio-grande', displayLabel: 'Rio Grande County, CO' },
    { slug: 'conejos', name: 'Conejos', seat: 'Conejos', href: '/local-movers/colorado/conejos', displayLabel: 'Conejos County, CO' },
    { slug: 'mineral', name: 'mineral', seat: 'mineral', href: '/local-movers/colorado/mineral', displayLabel: 'mineral County, CO' },
    { slug: 'san-juan', name: 'San Juan', seat: 'Silverton', href: '/local-movers/colorado/san-juan', displayLabel: 'San Juan County, CO' },
  ],
  'las-animas': [
    { slug: 'huerfano', name: 'Huerfano', seat: 'Walsenburg', href: '/local-movers/colorado/huerfano', displayLabel: 'Huerfano County, CO' },
    { slug: 'pueblo', name: 'Pueblo', seat: 'Pueblo', href: '/local-movers/colorado/pueblo', displayLabel: 'Pueblo County, CO' },
    { slug: 'otero', name: 'Otero', seat: 'La Junta', href: '/local-movers/colorado/otero', displayLabel: 'Otero County, CO' },
    { slug: 'bent', name: 'bent', seat: 'bent', href: '/local-movers/colorado/bent', displayLabel: 'bent County, CO' },
    { slug: 'baca', name: 'baca', seat: 'baca', href: '/local-movers/colorado/baca', displayLabel: 'baca County, CO' },
  ],
  moffat: [
    { slug: 'routt', name: 'Routt', seat: 'Steamboat Springs', href: '/local-movers/colorado/routt', displayLabel: 'Routt County, CO' },
    { slug: 'garfield', name: 'Garfield', seat: 'Glenwood Springs', href: '/local-movers/colorado/garfield', displayLabel: 'Garfield County, CO' },
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
    { slug: 'rio-blanco', name: 'rio-blanco', seat: 'rio-blanco', href: '/local-movers/colorado/rio-blanco', displayLabel: 'rio-blanco County, CO' },
    { slug: 'jackson', name: 'Jackson', seat: 'Walden', href: '/local-movers/colorado/jackson', displayLabel: 'Jackson County, CO' },
  ],
  prowers: [
    { slug: 'kit-carson', name: 'Kit Carson', seat: 'Burlington', href: '/local-movers/colorado/kit-carson', displayLabel: 'Kit Carson County, CO' },
    { slug: 'las-animas', name: 'Las Animas', seat: 'Trinidad', href: '/local-movers/colorado/las-animas', displayLabel: 'Las Animas County, CO' },
    { slug: 'bent', name: 'bent', seat: 'bent', href: '/local-movers/colorado/bent', displayLabel: 'bent County, CO' },
    { slug: 'baca', name: 'baca', seat: 'baca', href: '/local-movers/colorado/baca', displayLabel: 'baca County, CO' },
    { slug: 'kiowa', name: 'kiowa', seat: 'kiowa', href: '/local-movers/colorado/kiowa', displayLabel: 'kiowa County, CO' },
  ],
  'rio-grande': [
    { slug: 'alamosa', name: 'Alamosa', seat: 'Alamosa', href: '/local-movers/colorado/alamosa', displayLabel: 'Alamosa County, CO' },
    { slug: 'conejos', name: 'Conejos', seat: 'Conejos', href: '/local-movers/colorado/conejos', displayLabel: 'Conejos County, CO' },
    { slug: 'archuleta', name: 'Archuleta', seat: 'Pagosa Springs', href: '/local-movers/colorado/archuleta', displayLabel: 'Archuleta County, CO' },
    { slug: 'mineral', name: 'mineral', seat: 'mineral', href: '/local-movers/colorado/mineral', displayLabel: 'mineral County, CO' },
    { slug: 'saguache', name: 'saguache', seat: 'saguache', href: '/local-movers/colorado/saguache', displayLabel: 'saguache County, CO' },
  ],
  yuma: [
    { slug: 'logan', name: 'Logan', seat: 'Sterling', href: '/local-movers/colorado/logan', displayLabel: 'Logan County, CO' },
    { slug: 'kit-carson', name: 'Kit Carson', seat: 'Burlington', href: '/local-movers/colorado/kit-carson', displayLabel: 'Kit Carson County, CO' },
    { slug: 'washington', name: 'Washington', seat: 'Akron', href: '/local-movers/colorado/washington', displayLabel: 'Washington County, CO' },
    { slug: 'morgan', name: 'Morgan', seat: 'Fort Morgan', href: '/local-movers/colorado/morgan', displayLabel: 'Morgan County, CO' },
    { slug: 'cheyenne', name: 'cheyenne', seat: 'cheyenne', href: '/local-movers/colorado/cheyenne', displayLabel: 'cheyenne County, CO' },
  ],
  'clear-creek': [
    { slug: 'jefferson', name: 'Jefferson', seat: 'Golden', href: '/local-movers/colorado/jefferson', displayLabel: 'Jefferson County, CO' },
    { slug: 'summit', name: 'Summit', seat: 'Breckenridge', href: '/local-movers/colorado/summit', displayLabel: 'Summit County, CO' },
    { slug: 'grand', name: 'Grand', seat: 'Hot Sulphur Springs', href: '/local-movers/colorado/grand', displayLabel: 'Grand County, CO' },
    { slug: 'park', name: 'Park', seat: 'Fairplay', href: '/local-movers/colorado/park', displayLabel: 'Park County, CO' },
    { slug: 'gilpin', name: 'gilpin', seat: 'gilpin', href: '/local-movers/colorado/gilpin', displayLabel: 'gilpin County, CO' },
  ],
  'san-miguel': [
    { slug: 'montezuma', name: 'Montezuma', seat: 'Cortez', href: '/local-movers/colorado/montezuma', displayLabel: 'Montezuma County, CO' },
    { slug: 'dolores', name: 'Dolores', seat: 'Dove Creek', href: '/local-movers/colorado/dolores', displayLabel: 'Dolores County, CO' },
    { slug: 'ouray', name: 'Ouray', seat: 'Ouray', href: '/local-movers/colorado/ouray', displayLabel: 'Ouray County, CO' },
    { slug: 'san-juan', name: 'San Juan', seat: 'Silverton', href: '/local-movers/colorado/san-juan', displayLabel: 'San Juan County, CO' },
    { slug: 'mesa', name: 'Mesa', seat: 'Grand Junction', href: '/local-movers/colorado/mesa', displayLabel: 'Mesa County, CO' },
  ],
  lake: [
    { slug: 'summit', name: 'Summit', seat: 'Breckenridge', href: '/local-movers/colorado/summit', displayLabel: 'Summit County, CO' },
    { slug: 'park', name: 'Park', seat: 'Fairplay', href: '/local-movers/colorado/park', displayLabel: 'Park County, CO' },
    { slug: 'chaffee', name: 'Chaffee', seat: 'Salida', href: '/local-movers/colorado/chaffee', displayLabel: 'Chaffee County, CO' },
    { slug: 'pitkin', name: 'Pitkin', seat: 'Aspen', href: '/local-movers/colorado/pitkin', displayLabel: 'Pitkin County, CO' },
    { slug: 'eagle', name: 'Eagle', seat: 'Eagle', href: '/local-movers/colorado/eagle', displayLabel: 'Eagle County, CO' },
  ],
  conejos: [
    { slug: 'alamosa', name: 'Alamosa', seat: 'Alamosa', href: '/local-movers/colorado/alamosa', displayLabel: 'Alamosa County, CO' },
    { slug: 'rio-grande', name: 'Rio Grande', seat: 'Del Norte', href: '/local-movers/colorado/rio-grande', displayLabel: 'Rio Grande County, CO' },
    { slug: 'archuleta', name: 'Archuleta', seat: 'Pagosa Springs', href: '/local-movers/colorado/archuleta', displayLabel: 'Archuleta County, CO' },
    { slug: 'huerfano', name: 'Huerfano', seat: 'Walsenburg', href: '/local-movers/colorado/huerfano', displayLabel: 'Huerfano County, CO' },
    { slug: 'las-animas', name: 'Las Animas', seat: 'Trinidad', href: '/local-movers/colorado/las-animas', displayLabel: 'Las Animas County, CO' },
  ],
  'kit-carson': [
    { slug: 'yuma', name: 'Yuma', seat: 'Wray', href: '/local-movers/colorado/yuma', displayLabel: 'Yuma County, CO' },
    { slug: 'weld', name: 'Weld', seat: 'Greeley', href: '/local-movers/colorado/weld', displayLabel: 'Weld County, CO' },
    { slug: 'elbert', name: 'Elbert', seat: 'Kiowa', href: '/local-movers/colorado/elbert', displayLabel: 'Elbert County, CO' },
    { slug: 'adams', name: 'Adams', seat: 'Brighton', href: '/local-movers/colorado/adams', displayLabel: 'Adams County, CO' },
    { slug: 'arapahoe', name: 'Arapahoe', seat: 'Littleton', href: '/local-movers/colorado/arapahoe', displayLabel: 'Arapahoe County, CO' },
  ],
  huerfano: [
    { slug: 'pueblo', name: 'Pueblo', seat: 'Pueblo', href: '/local-movers/colorado/pueblo', displayLabel: 'Pueblo County, CO' },
    { slug: 'fremont', name: 'Fremont', seat: 'Canon City', href: '/local-movers/colorado/fremont', displayLabel: 'Fremont County, CO' },
    { slug: 'las-animas', name: 'Las Animas', seat: 'Trinidad', href: '/local-movers/colorado/las-animas', displayLabel: 'Las Animas County, CO' },
    { slug: 'conejos', name: 'Conejos', seat: 'Conejos', href: '/local-movers/colorado/conejos', displayLabel: 'Conejos County, CO' },
    { slug: 'otero', name: 'Otero', seat: 'La Junta', href: '/local-movers/colorado/otero', displayLabel: 'Otero County, CO' },
  ],
};

export function getColoradoNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return CO_COUNTY_NEIGHBORS[countySlug] ?? [];
}
