/**
 * County mover badge counts for state directory grids.
 *
 * California values are the EXACT number of displayable movers on each
 * county page (getMoversForCounty). Regenerated by:
 *   npx tsx scripts/rebuild-california-county-movers.ts
 *   npx tsx scripts/sync-california-badge-counts.ts
 */

/** California — exact listed (displayable) movers per county page */
export const californiaMarketMoverCounts: Record<string, number> = {
  alameda: 31,
  alpine: 25,
  amador: 24,
  butte: 24,
  calaveras: 24,
  colusa: 24,
  'contra-costa': 31,
  'del-norte': 24,
  'el-dorado': 24,
  fresno: 26,
  glenn: 24,
  humboldt: 24,
  imperial: 28,
  inyo: 25,
  kern: 26,
  kings: 26,
  lake: 25,
  lassen: 24,
  'los-angeles': 27,
  madera: 26,
  marin: 31,
  mariposa: 26,
  mendocino: 25,
  merced: 26,
  modoc: 24,
  mono: 25,
  monterey: 24,
  napa: 31,
  nevada: 25,
  orange: 27,
  placer: 24,
  plumas: 24,
  riverside: 27,
  sacramento: 24,
  'san-benito': 24,
  'san-bernardino': 27,
  'san-diego': 28,
  'san-francisco': 31,
  'san-joaquin': 28,
  'san-luis-obispo': 23,
  'san-mateo': 31,
  'santa-barbara': 25,
  'santa-clara': 31,
  'santa-cruz': 31,
  shasta: 24,
  sierra: 25,
  siskiyou: 24,
  solano: 31,
  sonoma: 32,
  stanislaus: 27,
  sutter: 24,
  tehama: 24,
  trinity: 24,
  tulare: 26,
  tuolumne: 24,
  ventura: 27,
  yolo: 24,
  yuba: 24,
};

const marketCountsByState: Record<string, Record<string, number>> = {
  california: californiaMarketMoverCounts,
};

/**
 * Listed/market count for a county, if we have a map.
 * Returns null when no map exists (caller may fall back to live listing count).
 */
export function getCountyMarketMoverCount(
  stateSlug: string,
  countySlug: string
): number | null {
  const map = marketCountsByState[stateSlug];
  if (!map) return null;
  const n = map[countySlug];
  return typeof n === 'number' ? n : null;
}

export type MoverCountBadgeTier = 'high' | 'medium' | 'low' | 'zero';

export function getMoverCountBadgeTier(count: number): MoverCountBadgeTier {
  if (count <= 0) return 'zero';
  if (count >= 50) return 'high';
  if (count >= 10) return 'medium';
  return 'low';
}

export function formatMoverCountLabel(count: number): string {
  if (count <= 0) return 'Contact Us';
  if (count === 1) return '1 Mover';
  return `${count} Movers`;
}
