import { generatedCounties } from '@/data/generated/index';
import { applyGeorgiaCountyOverrides } from '@/lib/local-movers/geography/georgia-overrides';
import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

const georgiaCounties = generatedCounties
  .filter((c) => c.stateSlug === 'georgia')
  .map(applyGeorgiaCountyOverrides);
const countyNameBySlug = new Map(georgiaCounties.map((c) => [c.slug, c.name]));

/** Metro adjacency for curated GA county pages — expands as counties are researched */
const GA_COUNTY_NEIGHBORS: Record<string, string[]> = {
  fulton: ['cobb', 'dekalb', 'forsyth', 'gwinnett', 'cherokee', 'clayton'],
  gwinnett: ['fulton', 'barrow', 'forsyth', 'hall', 'jackson', 'walton'],
  cobb: ['fulton', 'cherokee', 'paulding', 'douglas', 'fayette', 'bartow'],
  dekalb: ['fulton', 'gwinnett', 'rockdale', 'henry', 'clayton', 'walton'],
  clayton: ['fulton', 'dekalb', 'henry', 'fayette', 'rockdale', 'spalding'],
  cherokee: ['cobb', 'fulton', 'forsyth', 'pickens', 'bartow', 'paulding'],
  forsyth: ['gwinnett', 'fulton', 'cherokee', 'hall', 'dawson', 'lumpkin'],
  henry: ['clayton', 'fayette', 'rockdale', 'newton', 'butts', 'spalding'],
  fayette: ['clayton', 'fulton', 'henry', 'coweta', 'spalding', 'heard'],
  douglas: ['cobb', 'paulding', 'fulton', 'carroll', 'fayette', 'haralson'],
  rockdale: ['dekalb', 'gwinnett', 'newton', 'henry', 'walton', 'morgan'],
  paulding: ['cobb', 'douglas', 'bartow', 'polk', 'cherokee', 'haralson'],
  coweta: ['fayette', 'fulton', 'spalding', 'heard', 'meriwether', 'carroll'],
  barrow: ['gwinnett', 'walton', 'jackson', 'oconee', 'clarke', 'banks'],
  newton: ['rockdale', 'walton', 'morgan', 'jasper', 'henry', 'butts'],
  hall: ['gwinnett', 'forsyth', 'banks', 'lumpkin', 'white', 'jackson'],
  walton: ['gwinnett', 'rockdale', 'newton', 'morgan', 'oconee', 'barrow'],
  chatham: ['bryan', 'effingham', 'liberty', 'bulloch', 'screven', 'jasper'],
  richmond: ['columbia', 'mcduffie', 'jefferson', 'burke', 'glascock', 'warren'],
  columbia: ['richmond', 'mcduffie', 'jefferson', 'lincoln', 'wilkes', 'burke'],
  muscogee: ['harris', 'talbot', 'chattahoochee', 'stewart', 'marion', 'schley'],
  pickens: ['cherokee', 'dawson', 'gilmer', 'gordon', 'forsyth', 'bartow'],
  bartow: ['cherokee', 'paulding', 'polk', 'cobb', 'gordon', 'pickens'],
  spalding: ['fayette', 'henry', 'clayton', 'butts', 'coweta', 'pike'],
  butts: ['henry', 'spalding', 'jasper', 'newton', 'lamar', 'monroe'],
  carroll: ['douglas', 'haralson', 'heard', 'coweta', 'fayette', 'paulding'],
  dawson: ['forsyth', 'hall', 'lumpkin', 'pickens', 'gwinnett', 'cherokee'],
  lumpkin: ['dawson', 'hall', 'white', 'banks', 'forsyth', 'union'],
  morgan: ['newton', 'walton', 'oconee', 'jasper', 'greene', 'putnam'],
  oconee: ['clarke', 'barrow', 'walton', 'morgan', 'greene', 'madison'],
  jackson: ['gwinnett', 'barrow', 'hall', 'banks', 'clarke', 'madison'],
  haralson: ['paulding', 'carroll', 'douglas', 'polk', 'coweta', 'heard'],
  polk: ['paulding', 'bartow', 'floyd', 'haralson', 'gordon', 'catoosa'],
  heard: ['carroll', 'coweta', 'fayette', 'troup', 'haralson', 'meriwether'],
  meriwether: ['coweta', 'fayette', 'heard', 'troup', 'pike', 'upson'],
  floyd: ['gordon', 'bartow', 'polk', 'chattooga', 'cherokee', 'whitfield'],
  gordon: ['floyd', 'bartow', 'pickens', 'murray', 'whitfield', 'cherokee'],
  chattooga: ['floyd', 'walker', 'haralson', 'polk', 'gordon', 'bartow'],
  walker: ['catoosa', 'dade', 'whitfield', 'murray', 'chattooga', 'gordon'],
  whitfield: ['murray', 'gordon', 'walker', 'catoosa', 'floyd', 'bartow'],
  murray: ['whitfield', 'gordon', 'fannin', 'gilmer', 'walker', 'pickens'],
  catoosa: ['walker', 'whitfield', 'dade', 'murray', 'gordon', 'floyd'],
  dade: ['walker', 'catoosa', 'chattooga', 'whitfield', 'murray', 'gordon'],
  appling: ['bacon', 'jeff-davis', 'ware', 'pierce', 'coffee', 'toombs'],
  atkinson: ['coffee', 'berrien', 'clinch', 'ware', 'lanier', 'lowndes'],
  bacon: ['appling', 'coffee', 'pierce', 'ware', 'jeff-davis', 'brantley'],
  baker: ['dougherty', 'mitchell', 'calhoun', 'early', 'decatur', 'miller'],
  baldwin: ['bibb', 'jones', 'putnam', 'hancock', 'washington', 'wilkinson'],
  banks: ['hall', 'jackson', 'barrow', 'franklin', 'habersham', 'stephens'],
  berrien: ['atkinson', 'cook', 'lanier', 'lowndes', 'irwin', 'tift'],
  bibb: ['baldwin', 'jones', 'monroe', 'crawford', 'peach', 'twiggs'],
  bleckley: ['bibb', 'dodge', 'pulaski', 'wilcox', 'laurens', 'twiggs'],
  brantley: ['charlton', 'camden', 'pierce', 'ware', 'glynn', 'bacon'],
  houston: ['peach', 'bibb', 'bleckley', 'pulaski', 'taylor', 'crawford'],
  lowndes: ['brooks', 'lanier', 'berrien', 'atkinson', 'cook', 'echols'],
  bulloch: ['evans', 'candler', 'emanuel', 'screven', 'jenkins', 'bryan'],
  effingham: ['bryan', 'chatham', 'bulloch', 'screven', 'jasper', 'liberty'],
  glynn: ['camden', 'mcintosh', 'wayne', 'brantley', 'pierce', 'ware'],
  dougherty: ['lee', 'worth', 'mitchell', 'baker', 'terrell', 'sumter'],
  troup: ['meriwether', 'coweta', 'heard', 'harris', 'muscogee', 'chattahoochee'],
  liberty: ['chatham', 'bryan', 'effingham', 'mcintosh', 'long', 'evans'],
  camden: ['glynn', 'charlton', 'ware', 'pierce', 'brantley', 'bryan'],
  bryan: ['chatham', 'effingham', 'liberty', 'bulloch', 'evans', 'mcintosh'],
  laurens: ['wilkinson', 'johnson', 'treutlen', 'wheeler', 'dodge', 'bleckley'],
  habersham: ['hall', 'banks', 'white', 'rabun', 'stephens', 'lumpkin'],
  colquitt: ['thomas', 'brooks', 'cook', 'tift', 'mitchell', 'worth'],
  thomas: ['brooks', 'colquitt', 'grady', 'mitchell', 'decatur', 'lowndes'],
  lee: ['dougherty', 'worth', 'terrell', 'mitchell', 'sumter', 'crisp'],
  gilmer: ['fannin', 'pickens', 'dawson', 'murray', 'gordon', 'lumpkin'],
  madison: ['clarke', 'oglethorpe', 'elbert', 'jackson', 'franklin', 'banks'],
  wayne: ['pierce', 'appling', 'brantley', 'ware', 'glynn', 'mcintosh'],
  monroe: ['bibb', 'jones', 'peach', 'crawford', 'lamar', 'upson'],
  peach: ['houston', 'bibb', 'crawford', 'taylor', 'upson', 'monroe'],
  white: ['habersham', 'hall', 'lumpkin', 'towns', 'union', 'banks'],
  decatur: ['grady', 'seminole', 'miller', 'mitchell', 'thomas', 'early'],
  jones: ['bibb', 'monroe', 'putnam', 'jasper', 'twiggs', 'crawford'],
  hart: ['franklin', 'madison', 'elbert', 'banks', 'oconee', 'stephens'],
  upson: ['monroe', 'lamar', 'pike', 'meriwether', 'talbot', 'crawford'],
  sumter: ['lee', 'dougherty', 'terrell', 'webster', 'macon', 'crisp'],
  stephens: ['franklin', 'habersham', 'banks', 'hart', 'oconee', 'rabun'],
  union: ['fannin', 'towns', 'white', 'lumpkin', 'gilmer', 'cherokee'],
  toombs: ['appling', 'coffee', 'jeff-davis', 'tattnall', 'emanuel', 'montgomery'],
  grady: ['thomas', 'decatur', 'mitchell', 'brooks', 'colquitt', 'seminole'],
  franklin: ['hart', 'madison', 'banks', 'stephens', 'oconee', 'elbert'],
  fannin: ['gilmer', 'union', 'murray', 'pickens', 'dawson', 'lumpkin'],
  burke: ['richmond', 'jefferson', 'emanuel', 'jenkins', 'screven', 'mcduffie'],
  tattnall: ['toombs', 'evans', 'candler', 'bulloch', 'montgomery', 'appling'],
  putnam: ['morgan', 'jones', 'greene', 'newton', 'jasper', 'monroe'],
  emanuel: ['candler', 'bulloch', 'jenkins', 'burke', 'tattnall', 'montgomery'],
  long: ['liberty', 'mcintosh', 'wayne', 'bryan', 'effingham', 'chatham'],
  greene: ['putnam', 'morgan', 'taliferro', 'wilkes', 'oconee', 'hancock'],
  mcduffie: ['richmond', 'columbia', 'wilkes', 'lincoln', 'warren', 'burke'],
  lamar: ['monroe', 'upson', 'pike', 'butts', 'spalding', 'fayette'],
  pike: ['lamar', 'upson', 'spalding', 'meriwether', 'henry', 'fayette'],
  pierce: ['bacon', 'appling', 'ware', 'brantley', 'wayne', 'coffee'],
  mitchell: ['baker', 'dougherty', 'worth', 'colquitt', 'decatur', 'grady'],
  elbert: ['hart', 'madison', 'franklin', 'banks', 'wilkes', 'oglethorpe'],
  worth: ['dougherty', 'lee', 'mitchell', 'colquitt', 'tift', 'crisp'],
  dodge: ['bleckley', 'laurens', 'pulaski', 'wilcox', 'twiggs', 'emanuel'],
  washington: ['baldwin', 'johnson', 'hancock', 'wilkinson', 'jefferson', 'glascock'],
  crisp: ['dooly', 'lee', 'sumter', 'turner', 'wilcox', 'worth'],
  cook: ['berrien', 'lowndes', 'tift', 'colquitt', 'brooks', 'atkinson'],
  jasper: ['butts', 'newton', 'morgan', 'putnam', 'jones', 'monroe'],
  rabun: ['habersham', 'stephens', 'white', 'fannin', 'gilmer', 'towns'],
  'ben-hill': ['coffee', 'irwin', 'tift', 'turner', 'wilcox', 'crisp'],
  oglethorpe: ['madison', 'elbert', 'wilkes', 'greene', 'oconee', 'clarke'],
  brooks: ['lowndes', 'lanier', 'thomas', 'colquitt', 'cook', 'grady'],
  'jeff-davis': ['appling', 'coffee', 'toombs', 'tattnall', 'montgomery', 'ware'],
  jefferson: ['richmond', 'burke', 'mcduffie', 'washington', 'glascock', 'warren'],
  screven: ['burke', 'jenkins', 'bulloch', 'effingham', 'chatham', 'emanuel'],
  towns: ['rabun', 'habersham', 'white', 'fannin', 'gilmer', 'union'],
  charlton: ['camden', 'brantley', 'ware', 'bacon', 'glynn', 'pierce'],
  mcintosh: ['liberty', 'glynn', 'wayne', 'long', 'bryan', 'chatham'],
  crawford: ['peach', 'monroe', 'bibb', 'upson', 'jones', 'houston'],
  macon: ['sumter', 'dooly', 'crisp', 'pulaski', 'webster', 'schley'],
  candler: ['bulloch', 'evans', 'tattnall', 'emanuel', 'screven', 'jenkins'],
  telfair: ['wheeler', 'jeff-davis', 'coffee', 'montgomery', 'dodge', 'laurens'],
  dooly: ['crisp', 'worth', 'sumter', 'macon', 'wilcox', 'pulaski'],
  evans: ['bulloch', 'candler', 'tattnall', 'effingham', 'bryan', 'screven'],
  lanier: ['lowndes', 'brooks', 'atkinson', 'berrien', 'echols', 'cook'],
  early: ['baker', 'miller', 'seminole', 'decatur', 'grady', 'mitchell'],
  pulaski: ['bleckley', 'dodge', 'houston', 'dooly', 'wilcox', 'laurens'],
  wilkes: ['oglethorpe', 'greene', 'lincoln', 'mcduffie', 'warren', 'elbert'],
  johnson: ['washington', 'jefferson', 'emanuel', 'treutlen', 'laurens', 'glascock'],
  seminole: ['early', 'decatur', 'miller', 'grady', 'mitchell', 'baker'],
  turner: ['crisp', 'ben-hill', 'wilcox', 'tift', 'irwin', 'dooly'],
  irwin: ['ben-hill', 'coffee', 'tift', 'turner', 'berrien', 'colquitt'],
  jenkins: ['burke', 'screven', 'emanuel', 'bulloch', 'candler', 'jefferson'],
  wilcox: ['dooly', 'pulaski', 'turner', 'ben-hill', 'crisp', 'dodge'],
  montgomery: ['telfair', 'jeff-davis', 'toombs', 'wheeler', 'appling', 'coffee'],
  hancock: ['washington', 'greene', 'taliferro', 'warren', 'baldwin', 'glascock'],
  wilkinson: ['washington', 'laurens', 'johnson', 'twiggs', 'bleckley', 'hancock'],
  wheeler: ['montgomery', 'telfair', 'jeff-davis', 'appling', 'coffee', 'laurens'],
  marion: ['muscogee', 'talbot', 'schley', 'stewart', 'webster', 'chattahoochee'],
  twiggs: ['wilkinson', 'bleckley', 'jones', 'bibb', 'hancock', 'washington'],
  clinch: ['lowndes', 'echols', 'ware', 'atkinson', 'lanier', 'charlton'],
  treutlen: ['emanuel', 'laurens', 'johnson', 'montgomery', 'wheeler', 'jenkins'],
  randolph: ['terrell', 'calhoun', 'stewart', 'quitman', 'clay', 'webster'],
  miller: ['seminole', 'decatur', 'baker', 'early', 'mitchell', 'grady'],
  talbot: ['marion', 'taylor', 'upson', 'meriwether', 'harris', 'muscogee'],
  calhoun: ['early', 'baker', 'miller', 'terrell', 'randolph', 'dougherty'],
  warren: ['mcduffie', 'wilkes', 'hancock', 'glascock', 'jefferson', 'columbia'],
  chattahoochee: ['muscogee', 'marion', 'stewart', 'schley', 'talbot', 'webster'],
  clarke: ['oconee', 'madison', 'oglethorpe', 'jackson', 'barrow', 'elbert'],
  clay: ['randolph', 'quitman', 'early', 'calhoun', 'stewart', 'terrell'],
  echols: ['clinch', 'lowndes', 'lanier', 'atkinson', 'ware', 'charlton'],
  glascock: ['warren', 'jefferson', 'mcduffie', 'hancock', 'washington', 'wilkes'],
  harris: ['muscogee', 'talbot', 'marion', 'upson', 'meriwether', 'chattahoochee'],
  lincoln: ['mcduffie', 'wilkes', 'elbert', 'columbia', 'warren', 'clarke'],
  quitman: ['randolph', 'clay', 'stewart', 'terrell', 'webster', 'calhoun'],
  schley: ['sumter', 'macon', 'marion', 'webster', 'stewart', 'chattahoochee'],
  stewart: ['chattahoochee', 'webster', 'randolph', 'quitman', 'clay', 'schley'],
  taliaferro: ['greene', 'hancock', 'wilkes', 'warren', 'mcduffie', 'washington'],
  taylor: ['upson', 'peach', 'crawford', 'houston', 'talbot', 'marion'],
  terrell: ['dougherty', 'lee', 'sumter', 'crisp', 'worth', 'calhoun'],
  tift: ['berrien', 'irwin', 'turner', 'cook', 'colquitt', 'lowndes'],
  ware: ['pierce', 'appling', 'bacon', 'brantley', 'coffee', 'atkinson'],
  webster: ['sumter', 'macon', 'marion', 'schley', 'randolph', 'quitman'],
};

export function getGeorgiaNearbyCounties(
  countySlug: string,
  limit = 6
): NearbyCountyLink[] {
  const neighbors = GA_COUNTY_NEIGHBORS[countySlug] ?? [];
  return neighbors
    .slice(0, limit)
    .map((slug) => {
      const county = georgiaCounties.find((c) => c.slug === slug);
      return county
        ? { slug: county.slug, name: county.name, seat: county.seat }
        : { slug, name: countyNameBySlug.get(slug) ?? slug };
    })
    .filter(
      (c) =>
        countyNameBySlug.has(c.slug) ||
        georgiaCounties.some((ga) => ga.slug === c.slug)
    );
}