import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** Maryland curated counties plus cross-border DC, VA, and DE metro guides */
const MD_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  montgomery: [
    {
      slug: 'prince-georges',
      name: "Prince George's",
      seat: 'Upper Marlboro',
      href: '/local-movers/maryland/prince-georges',
      displayLabel: "Prince George's County, MD",
    },
    {
      slug: 'howard',
      name: 'Howard',
      seat: 'Ellicott City',
      href: '/local-movers/maryland/howard',
      displayLabel: 'Howard County, MD',
    },
    {
      slug: 'frederick',
      name: 'Frederick',
      seat: 'Frederick',
      href: '/local-movers/maryland/frederick',
      displayLabel: 'Frederick County, MD',
    },
    {
      slug: 'fairfax',
      name: 'Fairfax',
      seat: 'Fairfax',
      href: '/local-movers/virginia/fairfax',
      displayLabel: 'Fairfax County, VA',
    },
    {
      slug: 'arlington',
      name: 'Arlington',
      seat: 'Arlington',
      href: '/local-movers/virginia/arlington',
      displayLabel: 'Arlington, VA',
    },
    {
      slug: 'district-of-columbia',
      name: 'District of Columbia',
      seat: 'Washington',
      href: '/local-movers/district-of-columbia/district-of-columbia',
      displayLabel: 'Washington, DC',
    },
  ],
  'prince-georges': [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Rockville',
      href: '/local-movers/maryland/montgomery',
      displayLabel: 'Montgomery County, MD',
    },
    {
      slug: 'charles',
      name: 'Charles',
      seat: 'La Plata',
      href: '/local-movers/maryland/charles',
      displayLabel: 'Charles County, MD',
    },
    {
      slug: 'anne-arundel',
      name: 'Anne Arundel',
      seat: 'Annapolis',
      href: '/local-movers/maryland/anne-arundel',
      displayLabel: 'Anne Arundel County, MD',
    },
    {
      slug: 'alexandria',
      name: 'Alexandria',
      seat: 'Alexandria',
      href: '/local-movers/virginia/alexandria',
      displayLabel: 'Alexandria, VA',
    },
    {
      slug: 'arlington',
      name: 'Arlington',
      seat: 'Arlington',
      href: '/local-movers/virginia/arlington',
      displayLabel: 'Arlington, VA',
    },
    {
      slug: 'district-of-columbia',
      name: 'District of Columbia',
      seat: 'Washington',
      href: '/local-movers/district-of-columbia/district-of-columbia',
      displayLabel: 'Washington, DC',
    },
  ],
  baltimore: [
    {
      slug: 'baltimore-city',
      name: 'Baltimore City',
      seat: 'Baltimore',
      href: '/local-movers/maryland/baltimore-city',
      displayLabel: 'Baltimore City, MD',
    },
    {
      slug: 'anne-arundel',
      name: 'Anne Arundel',
      seat: 'Annapolis',
      href: '/local-movers/maryland/anne-arundel',
      displayLabel: 'Anne Arundel County, MD',
    },
    {
      slug: 'harford',
      name: 'Harford',
      seat: 'Bel Air',
      href: '/local-movers/maryland/harford',
      displayLabel: 'Harford County, MD',
    },
    {
      slug: 'carroll',
      name: 'Carroll',
      seat: 'Westminster',
      href: '/local-movers/maryland/carroll',
      displayLabel: 'Carroll County, MD',
    },
    {
      slug: 'howard',
      name: 'Howard',
      seat: 'Ellicott City',
      href: '/local-movers/maryland/howard',
      displayLabel: 'Howard County, MD',
    },
    {
      slug: 'cecil',
      name: 'Cecil',
      seat: 'Elkton',
      href: '/local-movers/maryland/cecil',
      displayLabel: 'Cecil County, MD',
    },
    {
      slug: 'new-castle',
      name: 'New Castle',
      seat: 'Wilmington',
      href: '/local-movers/delaware/new-castle',
      displayLabel: 'New Castle County, DE',
    },
  ],
  'anne-arundel': [
    {
      slug: 'baltimore-city',
      name: 'Baltimore City',
      seat: 'Baltimore',
      href: '/local-movers/maryland/baltimore-city',
      displayLabel: 'Baltimore City, MD',
    },
    {
      slug: 'baltimore',
      name: 'Baltimore',
      seat: 'Towson',
      href: '/local-movers/maryland/baltimore',
      displayLabel: 'Baltimore County, MD',
    },
    {
      slug: 'howard',
      name: 'Howard',
      seat: 'Ellicott City',
      href: '/local-movers/maryland/howard',
      displayLabel: 'Howard County, MD',
    },
    {
      slug: 'prince-georges',
      name: "Prince George's",
      seat: 'Upper Marlboro',
      href: '/local-movers/maryland/prince-georges',
      displayLabel: "Prince George's County, MD",
    },
    {
      slug: 'calvert',
      name: 'Calvert',
      seat: 'Prince Frederick',
      href: '/local-movers/maryland/calvert',
      displayLabel: 'Calvert County, MD',
    },
    {
      slug: 'harford',
      name: 'Harford',
      seat: 'Bel Air',
      href: '/local-movers/maryland/harford',
      displayLabel: 'Harford County, MD',
    },
  ],
  'baltimore-city': [
    {
      slug: 'baltimore',
      name: 'Baltimore',
      seat: 'Towson',
      href: '/local-movers/maryland/baltimore',
      displayLabel: 'Baltimore County, MD',
    },
    {
      slug: 'anne-arundel',
      name: 'Anne Arundel',
      seat: 'Annapolis',
      href: '/local-movers/maryland/anne-arundel',
      displayLabel: 'Anne Arundel County, MD',
    },
    {
      slug: 'harford',
      name: 'Harford',
      seat: 'Bel Air',
      href: '/local-movers/maryland/harford',
      displayLabel: 'Harford County, MD',
    },
    {
      slug: 'howard',
      name: 'Howard',
      seat: 'Ellicott City',
      href: '/local-movers/maryland/howard',
      displayLabel: 'Howard County, MD',
    },
    {
      slug: 'carroll',
      name: 'Carroll',
      seat: 'Westminster',
      href: '/local-movers/maryland/carroll',
      displayLabel: 'Carroll County, MD',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Rockville',
      href: '/local-movers/maryland/montgomery',
      displayLabel: 'Montgomery County, MD',
    },
  ],
  howard: [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Rockville',
      href: '/local-movers/maryland/montgomery',
      displayLabel: 'Montgomery County, MD',
    },
    {
      slug: 'baltimore',
      name: 'Baltimore',
      seat: 'Towson',
      href: '/local-movers/maryland/baltimore',
      displayLabel: 'Baltimore County, MD',
    },
    {
      slug: 'anne-arundel',
      name: 'Anne Arundel',
      seat: 'Annapolis',
      href: '/local-movers/maryland/anne-arundel',
      displayLabel: 'Anne Arundel County, MD',
    },
    {
      slug: 'frederick',
      name: 'Frederick',
      seat: 'Frederick',
      href: '/local-movers/maryland/frederick',
      displayLabel: 'Frederick County, MD',
    },
    {
      slug: 'prince-georges',
      name: "Prince George's",
      seat: 'Upper Marlboro',
      href: '/local-movers/maryland/prince-georges',
      displayLabel: "Prince George's County, MD",
    },
    {
      slug: 'carroll',
      name: 'Carroll',
      seat: 'Westminster',
      href: '/local-movers/maryland/carroll',
      displayLabel: 'Carroll County, MD',
    },
  ],
  frederick: [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Rockville',
      href: '/local-movers/maryland/montgomery',
      displayLabel: 'Montgomery County, MD',
    },
    {
      slug: 'howard',
      name: 'Howard',
      seat: 'Ellicott City',
      href: '/local-movers/maryland/howard',
      displayLabel: 'Howard County, MD',
    },
    {
      slug: 'washington',
      name: 'Washington',
      seat: 'Hagerstown',
      href: '/local-movers/maryland/washington',
      displayLabel: 'Washington County, MD',
    },
    {
      slug: 'carroll',
      name: 'Carroll',
      seat: 'Westminster',
      href: '/local-movers/maryland/carroll',
      displayLabel: 'Carroll County, MD',
    },
    {
      slug: 'loudoun',
      name: 'Loudoun',
      seat: 'Leesburg',
      href: '/local-movers/virginia/loudoun',
      displayLabel: 'Loudoun County, VA',
    },
    {
      slug: 'baltimore',
      name: 'Baltimore',
      seat: 'Towson',
      href: '/local-movers/maryland/baltimore',
      displayLabel: 'Baltimore County, MD',
    },
  ],
  harford: [
    {
      slug: 'baltimore',
      name: 'Baltimore',
      seat: 'Towson',
      href: '/local-movers/maryland/baltimore',
      displayLabel: 'Baltimore County, MD',
    },
    {
      slug: 'baltimore-city',
      name: 'Baltimore City',
      seat: 'Baltimore',
      href: '/local-movers/maryland/baltimore-city',
      displayLabel: 'Baltimore City, MD',
    },
    {
      slug: 'cecil',
      name: 'Cecil',
      seat: 'Elkton',
      href: '/local-movers/maryland/cecil',
      displayLabel: 'Cecil County, MD',
    },
    {
      slug: 'york',
      name: 'York',
      seat: 'York',
      href: '/local-movers/pennsylvania/york',
      displayLabel: 'York County, PA',
    },
    {
      slug: 'carroll',
      name: 'Carroll',
      seat: 'Westminster',
      href: '/local-movers/maryland/carroll',
      displayLabel: 'Carroll County, MD',
    },
    {
      slug: 'anne-arundel',
      name: 'Anne Arundel',
      seat: 'Annapolis',
      href: '/local-movers/maryland/anne-arundel',
      displayLabel: 'Anne Arundel County, MD',
    },
  ],
  charles: [
    {
      slug: 'prince-georges',
      name: "Prince George's",
      seat: 'Upper Marlboro',
      href: '/local-movers/maryland/prince-georges',
      displayLabel: "Prince George's County, MD",
    },
    {
      slug: 'calvert',
      name: 'Calvert',
      seat: 'Prince Frederick',
      href: '/local-movers/maryland/calvert',
      displayLabel: 'Calvert County, MD',
    },
    {
      slug: 'st-marys',
      name: "St. Mary's",
      seat: 'Leonardtown',
      href: '/local-movers/maryland/st-marys',
      displayLabel: "St. Mary's County, MD",
    },
    {
      slug: 'fairfax',
      name: 'Fairfax',
      seat: 'Fairfax',
      href: '/local-movers/virginia/fairfax',
      displayLabel: 'Fairfax County, VA',
    },
    {
      slug: 'alexandria',
      name: 'Alexandria',
      seat: 'Alexandria',
      href: '/local-movers/virginia/alexandria',
      displayLabel: 'Alexandria, VA',
    },
    {
      slug: 'district-of-columbia',
      name: 'District of Columbia',
      seat: 'Washington',
      href: '/local-movers/district-of-columbia/district-of-columbia',
      displayLabel: 'Washington, DC',
    },
  ],
  carroll: [
    { slug: 'baltimore', name: 'Baltimore', seat: 'Towson', href: '/local-movers/maryland/baltimore', displayLabel: 'Baltimore County, MD' },
    { slug: 'frederick', name: 'Frederick', seat: 'Frederick', href: '/local-movers/maryland/frederick', displayLabel: 'Frederick County, MD' },
    { slug: 'howard', name: 'Howard', seat: 'Ellicott City', href: '/local-movers/maryland/howard', displayLabel: 'Howard County, MD' },
    { slug: 'baltimore-city', name: 'Baltimore City', seat: 'Baltimore', href: '/local-movers/maryland/baltimore-city', displayLabel: 'Baltimore City, MD' },
    { slug: 'harford', name: 'Harford', seat: 'Bel Air', href: '/local-movers/maryland/harford', displayLabel: 'Harford County, MD' },
    { slug: 'montgomery', name: 'Montgomery', seat: 'Rockville', href: '/local-movers/maryland/montgomery', displayLabel: 'Montgomery County, MD' },
  ],
  washington: [
    { slug: 'frederick', name: 'Frederick', seat: 'Frederick', href: '/local-movers/maryland/frederick', displayLabel: 'Frederick County, MD' },
    { slug: 'allegany', name: 'Allegany', seat: 'Cumberland', href: '/local-movers/maryland/allegany', displayLabel: 'Allegany County, MD' },
    { slug: 'garrett', name: 'Garrett', seat: 'Oakland', href: '/local-movers/maryland/garrett', displayLabel: 'Garrett County, MD' },
    { slug: 'loudoun', name: 'Loudoun', seat: 'Leesburg', href: '/local-movers/virginia/loudoun', displayLabel: 'Loudoun County, VA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Chambersburg', href: '/local-movers/pennsylvania/franklin', displayLabel: 'Franklin County, PA' },
    { slug: 'carroll', name: 'Carroll', seat: 'Westminster', href: '/local-movers/maryland/carroll', displayLabel: 'Carroll County, MD' },
  ],
  'st-marys': [
    { slug: 'charles', name: 'Charles', seat: 'La Plata', href: '/local-movers/maryland/charles', displayLabel: 'Charles County, MD' },
    { slug: 'calvert', name: 'Calvert', seat: 'Prince Frederick', href: '/local-movers/maryland/calvert', displayLabel: 'Calvert County, MD' },
    { slug: 'prince-georges', name: "Prince George's", seat: 'Upper Marlboro', href: '/local-movers/maryland/prince-georges', displayLabel: "Prince George's County, MD" },
    { slug: 'anne-arundel', name: 'Anne Arundel', seat: 'Annapolis', href: '/local-movers/maryland/anne-arundel', displayLabel: 'Anne Arundel County, MD' },
    { slug: 'wicomico', name: 'Wicomico', seat: 'Salisbury', href: '/local-movers/maryland/wicomico', displayLabel: 'Wicomico County, MD' },
    { slug: 'montgomery', name: 'Montgomery', seat: 'Rockville', href: '/local-movers/maryland/montgomery', displayLabel: 'Montgomery County, MD' },
  ],
  cecil: [
    { slug: 'harford', name: 'Harford', seat: 'Bel Air', href: '/local-movers/maryland/harford', displayLabel: 'Harford County, MD' },
    { slug: 'baltimore', name: 'Baltimore', seat: 'Towson', href: '/local-movers/maryland/baltimore', displayLabel: 'Baltimore County, MD' },
    { slug: 'new-castle', name: 'New Castle', seat: 'Wilmington', href: '/local-movers/delaware/new-castle', displayLabel: 'New Castle County, DE' },
    { slug: 'chester', name: 'Chester', seat: 'West Chester', href: '/local-movers/pennsylvania/chester', displayLabel: 'Chester County, PA' },
    { slug: 'kent', name: 'Kent', seat: 'Chestertown', href: '/local-movers/maryland/kent', displayLabel: 'Kent County, MD' },
    { slug: 'carroll', name: 'Carroll', seat: 'Westminster', href: '/local-movers/maryland/carroll', displayLabel: 'Carroll County, MD' },
  ],
  wicomico: [
    { slug: 'worcester', name: 'Worcester', seat: 'Snow Hill', href: '/local-movers/maryland/worcester', displayLabel: 'Worcester County, MD' },
    { slug: 'somerset', name: 'Somerset', seat: 'Princess Anne', href: '/local-movers/maryland/somerset', displayLabel: 'Somerset County, MD' },
    { slug: 'dorchester', name: 'Dorchester', seat: 'Cambridge', href: '/local-movers/maryland/dorchester', displayLabel: 'Dorchester County, MD' },
    { slug: 'sussex', name: 'Sussex', seat: 'Georgetown', href: '/local-movers/delaware/sussex', displayLabel: 'Sussex County, DE' },
    { slug: 'talbot', name: 'Talbot', seat: 'Easton', href: '/local-movers/maryland/talbot', displayLabel: 'Talbot County, MD' },
    { slug: 'caroline', name: 'Caroline', seat: 'Denton', href: '/local-movers/maryland/caroline', displayLabel: 'Caroline County, MD' },
  ],
  calvert: [
    { slug: 'charles', name: 'Charles', seat: 'La Plata', href: '/local-movers/maryland/charles', displayLabel: 'Charles County, MD' },
    { slug: 'prince-georges', name: "Prince George's", seat: 'Upper Marlboro', href: '/local-movers/maryland/prince-georges', displayLabel: "Prince George's County, MD" },
    { slug: 'st-marys', name: "St. Mary's", seat: 'Leonardtown', href: '/local-movers/maryland/st-marys', displayLabel: "St. Mary's County, MD" },
    { slug: 'anne-arundel', name: 'Anne Arundel', seat: 'Annapolis', href: '/local-movers/maryland/anne-arundel', displayLabel: 'Anne Arundel County, MD' },
    { slug: 'wicomico', name: 'Wicomico', seat: 'Salisbury', href: '/local-movers/maryland/wicomico', displayLabel: 'Wicomico County, MD' },
    { slug: 'howard', name: 'Howard', seat: 'Ellicott City', href: '/local-movers/maryland/howard', displayLabel: 'Howard County, MD' },
  ],
  allegany: [
    { slug: 'washington', name: 'Washington', seat: 'Hagerstown', href: '/local-movers/maryland/washington', displayLabel: 'Washington County, MD' },
    { slug: 'garrett', name: 'Garrett', seat: 'Oakland', href: '/local-movers/maryland/garrett', displayLabel: 'Garrett County, MD' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
    { slug: 'mineral', name: 'Mineral', seat: 'Keyser', href: '/local-movers/west-virginia/mineral', displayLabel: 'Mineral County, WV' },
    { slug: 'frederick', name: 'Frederick', seat: 'Frederick', href: '/local-movers/maryland/frederick', displayLabel: 'Frederick County, MD' },
    { slug: 'bedford', name: 'Bedford', seat: 'Bedford', href: '/local-movers/pennsylvania/bedford', displayLabel: 'Bedford County, PA' },
  ],
  'queen-annes': [
    { slug: 'kent', name: 'Kent', seat: 'Chestertown', href: '/local-movers/maryland/kent', displayLabel: 'Kent County, MD' },
    { slug: 'talbot', name: 'Talbot', seat: 'Easton', href: '/local-movers/maryland/talbot', displayLabel: 'Talbot County, MD' },
    { slug: 'anne-arundel', name: 'Anne Arundel', seat: 'Annapolis', href: '/local-movers/maryland/anne-arundel', displayLabel: 'Anne Arundel County, MD' },
    { slug: 'caroline', name: 'Caroline', seat: 'Denton', href: '/local-movers/maryland/caroline', displayLabel: 'Caroline County, MD' },
    { slug: 'cecil', name: 'Cecil', seat: 'Elkton', href: '/local-movers/maryland/cecil', displayLabel: 'Cecil County, MD' },
    { slug: 'harford', name: 'Harford', seat: 'Bel Air', href: '/local-movers/maryland/harford', displayLabel: 'Harford County, MD' },
  ],
  worcester: [
    { slug: 'wicomico', name: 'Wicomico', seat: 'Salisbury', href: '/local-movers/maryland/wicomico', displayLabel: 'Wicomico County, MD' },
    { slug: 'sussex', name: 'Sussex', seat: 'Georgetown', href: '/local-movers/delaware/sussex', displayLabel: 'Sussex County, DE' },
    { slug: 'somerset', name: 'Somerset', seat: 'Princess Anne', href: '/local-movers/maryland/somerset', displayLabel: 'Somerset County, MD' },
    { slug: 'accomack', name: 'Accomack', seat: 'Accomac', href: '/local-movers/virginia/accomack', displayLabel: 'Accomack County, VA' },
    { slug: 'dorchester', name: 'Dorchester', seat: 'Cambridge', href: '/local-movers/maryland/dorchester', displayLabel: 'Dorchester County, MD' },
    { slug: 'kent', name: 'Kent', seat: 'Chestertown', href: '/local-movers/maryland/kent', displayLabel: 'Kent County, MD' },
  ],
  talbot: [
    { slug: 'queen-annes', name: "Queen Anne's", seat: 'Centreville', href: '/local-movers/maryland/queen-annes', displayLabel: "Queen Anne's County, MD" },
    { slug: 'caroline', name: 'Caroline', seat: 'Denton', href: '/local-movers/maryland/caroline', displayLabel: 'Caroline County, MD' },
    { slug: 'dorchester', name: 'Dorchester', seat: 'Cambridge', href: '/local-movers/maryland/dorchester', displayLabel: 'Dorchester County, MD' },
    { slug: 'kent', name: 'Kent', seat: 'Chestertown', href: '/local-movers/maryland/kent', displayLabel: 'Kent County, MD' },
    { slug: 'anne-arundel', name: 'Anne Arundel', seat: 'Annapolis', href: '/local-movers/maryland/anne-arundel', displayLabel: 'Anne Arundel County, MD' },
    { slug: 'wicomico', name: 'Wicomico', seat: 'Salisbury', href: '/local-movers/maryland/wicomico', displayLabel: 'Wicomico County, MD' },
  ],
  caroline: [
    { slug: 'queen-annes', name: "Queen Anne's", seat: 'Centreville', href: '/local-movers/maryland/queen-annes', displayLabel: "Queen Anne's County, MD" },
    { slug: 'talbot', name: 'Talbot', seat: 'Easton', href: '/local-movers/maryland/talbot', displayLabel: 'Talbot County, MD' },
    { slug: 'dorchester', name: 'Dorchester', seat: 'Cambridge', href: '/local-movers/maryland/dorchester', displayLabel: 'Dorchester County, MD' },
    { slug: 'kent', name: 'Kent', seat: 'Chestertown', href: '/local-movers/maryland/kent', displayLabel: 'Kent County, MD' },
    { slug: 'wicomico', name: 'Wicomico', seat: 'Salisbury', href: '/local-movers/maryland/wicomico', displayLabel: 'Wicomico County, MD' },
    { slug: 'dorchester', name: 'Dorchester', seat: 'Cambridge', href: '/local-movers/maryland/dorchester', displayLabel: 'Dorchester County, MD' },
  ],
  dorchester: [
    { slug: 'talbot', name: 'Talbot', seat: 'Easton', href: '/local-movers/maryland/talbot', displayLabel: 'Talbot County, MD' },
    { slug: 'caroline', name: 'Caroline', seat: 'Denton', href: '/local-movers/maryland/caroline', displayLabel: 'Caroline County, MD' },
    { slug: 'wicomico', name: 'Wicomico', seat: 'Salisbury', href: '/local-movers/maryland/wicomico', displayLabel: 'Wicomico County, MD' },
    { slug: 'somerset', name: 'Somerset', seat: 'Princess Anne', href: '/local-movers/maryland/somerset', displayLabel: 'Somerset County, MD' },
    { slug: 'calvert', name: 'Calvert', seat: 'Prince Frederick', href: '/local-movers/maryland/calvert', displayLabel: 'Calvert County, MD' },
    { slug: 'worcester', name: 'Worcester', seat: 'Snow Hill', href: '/local-movers/maryland/worcester', displayLabel: 'Worcester County, MD' },
  ],
  garrett: [
    { slug: 'allegany', name: 'Allegany', seat: 'Cumberland', href: '/local-movers/maryland/allegany', displayLabel: 'Allegany County, MD' },
    { slug: 'washington', name: 'Washington', seat: 'Hagerstown', href: '/local-movers/maryland/washington', displayLabel: 'Washington County, MD' },
    { slug: 'mineral', name: 'Mineral', seat: 'Keyser', href: '/local-movers/west-virginia/mineral', displayLabel: 'Mineral County, WV' },
    { slug: 'preston', name: 'Preston', seat: 'Kingwood', href: '/local-movers/west-virginia/preston', displayLabel: 'Preston County, WV' },
    { slug: 'grant', name: 'Grant', seat: 'Petersburg', href: '/local-movers/west-virginia/grant', displayLabel: 'Grant County, WV' },
    { slug: 'tucker', name: 'Tucker', seat: 'Parsons', href: '/local-movers/west-virginia/tucker', displayLabel: 'Tucker County, WV' },
  ],
  somerset: [
    { slug: 'wicomico', name: 'Wicomico', seat: 'Salisbury', href: '/local-movers/maryland/wicomico', displayLabel: 'Wicomico County, MD' },
    { slug: 'worcester', name: 'Worcester', seat: 'Snow Hill', href: '/local-movers/maryland/worcester', displayLabel: 'Worcester County, MD' },
    { slug: 'dorchester', name: 'Dorchester', seat: 'Cambridge', href: '/local-movers/maryland/dorchester', displayLabel: 'Dorchester County, MD' },
    { slug: 'accomack', name: 'Accomack', seat: 'Accomac', href: '/local-movers/virginia/accomack', displayLabel: 'Accomack County, VA' },
    { slug: 'worcester', name: 'Worcester', seat: 'Snow Hill', href: '/local-movers/maryland/worcester', displayLabel: 'Worcester County, MD' },
    { slug: 'sussex', name: 'Sussex', seat: 'Georgetown', href: '/local-movers/delaware/sussex', displayLabel: 'Sussex County, DE' },
  ],
  kent: [
    { slug: 'queen-annes', name: "Queen Anne's", seat: 'Centreville', href: '/local-movers/maryland/queen-annes', displayLabel: "Queen Anne's County, MD" },
    { slug: 'cecil', name: 'Cecil', seat: 'Elkton', href: '/local-movers/maryland/cecil', displayLabel: 'Cecil County, MD' },
    { slug: 'new-castle', name: 'New Castle', seat: 'Wilmington', href: '/local-movers/delaware/new-castle', displayLabel: 'New Castle County, DE' },
    { slug: 'talbot', name: 'Talbot', seat: 'Easton', href: '/local-movers/maryland/talbot', displayLabel: 'Talbot County, MD' },
    { slug: 'caroline', name: 'Caroline', seat: 'Denton', href: '/local-movers/maryland/caroline', displayLabel: 'Caroline County, MD' },
    { slug: 'harford', name: 'Harford', seat: 'Bel Air', href: '/local-movers/maryland/harford', displayLabel: 'Harford County, MD' },
  ],
};

export function getMarylandNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return MD_COUNTY_NEIGHBORS[countySlug] ?? [];
}