import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** Minnesota curated county corridor links — 37 counties */
const MN_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  hennepin: [
    { slug: "anoka", name: "Anoka", seat: "Anoka", href: "/local-movers/minnesota/anoka", displayLabel: "Anoka County, MN" },
    { slug: "carver", name: "Carver", seat: "Chaska", href: "/local-movers/minnesota/carver", displayLabel: "Carver County, MN" },
    { slug: "dakota", name: "Dakota", seat: "Hastings", href: "/local-movers/minnesota/dakota", displayLabel: "Dakota County, MN" },
    { slug: "ramsey", name: "Ramsey", seat: "Saint Paul", href: "/local-movers/minnesota/ramsey", displayLabel: "Ramsey County, MN" },
    { slug: "scott", name: "Scott", seat: "Shakopee", href: "/local-movers/minnesota/scott", displayLabel: "Scott County, MN" },
  ],
  ramsey: [
    { slug: "anoka", name: "Anoka", seat: "Anoka", href: "/local-movers/minnesota/anoka", displayLabel: "Anoka County, MN" },
    { slug: "dakota", name: "Dakota", seat: "Hastings", href: "/local-movers/minnesota/dakota", displayLabel: "Dakota County, MN" },
    { slug: "hennepin", name: "Hennepin", seat: "Minneapolis", href: "/local-movers/minnesota/hennepin", displayLabel: "Hennepin County, MN" },
    { slug: "washington", name: "Washington", seat: "Stillwater", href: "/local-movers/minnesota/washington", displayLabel: "Washington County, MN" },
  ],
  dakota: [
    { slug: "goodhue", name: "Goodhue", seat: "Red Wing", href: "/local-movers/minnesota/goodhue", displayLabel: "Goodhue County, MN" },
    { slug: "hennepin", name: "Hennepin", seat: "Minneapolis", href: "/local-movers/minnesota/hennepin", displayLabel: "Hennepin County, MN" },
    { slug: "ramsey", name: "Ramsey", seat: "Saint Paul", href: "/local-movers/minnesota/ramsey", displayLabel: "Ramsey County, MN" },
    { slug: "rice", name: "Rice", seat: "Faribault", href: "/local-movers/minnesota/rice", displayLabel: "Rice County, MN" },
    { slug: "pierce", name: "Pierce", seat: "Ellsworth", href: "/local-movers/wisconsin/pierce", displayLabel: "Pierce County, WI" },
  ],
  anoka: [
    { slug: "chisago", name: "Chisago", seat: "Center City", href: "/local-movers/minnesota/chisago", displayLabel: "Chisago County, MN" },
    { slug: "hennepin", name: "Hennepin", seat: "Minneapolis", href: "/local-movers/minnesota/hennepin", displayLabel: "Hennepin County, MN" },
    { slug: "isanti", name: "Isanti", seat: "Cambridge", href: "/local-movers/minnesota/isanti", displayLabel: "Isanti County, MN" },
    { slug: "ramsey", name: "Ramsey", seat: "Saint Paul", href: "/local-movers/minnesota/ramsey", displayLabel: "Ramsey County, MN" },
    { slug: "sherburne", name: "Sherburne", seat: "Elk River", href: "/local-movers/minnesota/sherburne", displayLabel: "Sherburne County, MN" },
  ],
  washington: [
    { slug: "anoka", name: "Anoka", seat: "Anoka", href: "/local-movers/minnesota/anoka", displayLabel: "Anoka County, MN" },
    { slug: "chisago", name: "Chisago", seat: "Center City", href: "/local-movers/minnesota/chisago", displayLabel: "Chisago County, MN" },
    { slug: "dakota", name: "Dakota", seat: "Hastings", href: "/local-movers/minnesota/dakota", displayLabel: "Dakota County, MN" },
    { slug: "ramsey", name: "Ramsey", seat: "Saint Paul", href: "/local-movers/minnesota/ramsey", displayLabel: "Ramsey County, MN" },
    { slug: "pierce", name: "Pierce", seat: "Ellsworth", href: "/local-movers/wisconsin/pierce", displayLabel: "Pierce County, WI" },
  ],
  'st-louis': [
    { slug: "carlton", name: "Carlton", seat: "Carlton", href: "/local-movers/minnesota/carlton", displayLabel: "Carlton County, MN" },
    { slug: "itasca", name: "Itasca", seat: "Grand Rapids", href: "/local-movers/minnesota/itasca", displayLabel: "Itasca County, MN" },
    { slug: "aitkin", name: "Aitkin", seat: "Aitkin", href: "/local-movers/minnesota/aitkin", displayLabel: "Aitkin County, MN" },
    { slug: "koochiching", name: "Koochiching", seat: "International Falls", href: "/local-movers/minnesota/koochiching", displayLabel: "Koochiching County, MN" },
    { slug: "douglas", name: "Douglas", seat: "Superior", href: "/local-movers/wisconsin/douglas", displayLabel: "Douglas County, WI" },
  ],
  olmsted: [
    { slug: "goodhue", name: "Goodhue", seat: "Red Wing", href: "/local-movers/minnesota/goodhue", displayLabel: "Goodhue County, MN" },
    { slug: "mower", name: "Mower", seat: "Austin", href: "/local-movers/minnesota/mower", displayLabel: "Mower County, MN" },
    { slug: "winona", name: "Winona", seat: "Winona", href: "/local-movers/minnesota/winona", displayLabel: "Winona County, MN" },
    { slug: "dodge", name: "Dodge", seat: "Mantorville", href: "/local-movers/minnesota/dodge", displayLabel: "Dodge County, MN" },
    { slug: "fillmore", name: "Fillmore", seat: "Preston", href: "/local-movers/minnesota/fillmore", displayLabel: "Fillmore County, MN" },
  ],
  stearns: [
    { slug: "benton", name: "Benton", seat: "Foley", href: "/local-movers/minnesota/benton", displayLabel: "Benton County, MN" },
    { slug: "douglas", name: "Douglas", seat: "Alexandria", href: "/local-movers/minnesota/douglas", displayLabel: "Douglas County, MN" },
    { slug: "kandiyohi", name: "Kandiyohi", seat: "Willmar", href: "/local-movers/minnesota/kandiyohi", displayLabel: "Kandiyohi County, MN" },
    { slug: "morrison", name: "Morrison", seat: "Little Falls", href: "/local-movers/minnesota/morrison", displayLabel: "Morrison County, MN" },
    { slug: "sherburne", name: "Sherburne", seat: "Elk River", href: "/local-movers/minnesota/sherburne", displayLabel: "Sherburne County, MN" },
  ],
  scott: [
    { slug: "carver", name: "Carver", seat: "Chaska", href: "/local-movers/minnesota/carver", displayLabel: "Carver County, MN" },
    { slug: "dakota", name: "Dakota", seat: "Hastings", href: "/local-movers/minnesota/dakota", displayLabel: "Dakota County, MN" },
    { slug: "hennepin", name: "Hennepin", seat: "Minneapolis", href: "/local-movers/minnesota/hennepin", displayLabel: "Hennepin County, MN" },
    { slug: "rice", name: "Rice", seat: "Faribault", href: "/local-movers/minnesota/rice", displayLabel: "Rice County, MN" },
    { slug: "le-sueur", name: "Le Sueur", seat: "Le Center", href: "/local-movers/minnesota/le-sueur", displayLabel: "Le Sueur County, MN" },
  ],
  wright: [
    { slug: "anoka", name: "Anoka", seat: "Anoka", href: "/local-movers/minnesota/anoka", displayLabel: "Anoka County, MN" },
    { slug: "carver", name: "Carver", seat: "Chaska", href: "/local-movers/minnesota/carver", displayLabel: "Carver County, MN" },
    { slug: "hennepin", name: "Hennepin", seat: "Minneapolis", href: "/local-movers/minnesota/hennepin", displayLabel: "Hennepin County, MN" },
    { slug: "mcleod", name: "McLeod", seat: "Glencoe", href: "/local-movers/minnesota/mcleod", displayLabel: "McLeod County, MN" },
    { slug: "sherburne", name: "Sherburne", seat: "Elk River", href: "/local-movers/minnesota/sherburne", displayLabel: "Sherburne County, MN" },
  ],
  carver: [
    { slug: "hennepin", name: "Hennepin", seat: "Minneapolis", href: "/local-movers/minnesota/hennepin", displayLabel: "Hennepin County, MN" },
    { slug: "mcleod", name: "McLeod", seat: "Glencoe", href: "/local-movers/minnesota/mcleod", displayLabel: "McLeod County, MN" },
    { slug: "scott", name: "Scott", seat: "Shakopee", href: "/local-movers/minnesota/scott", displayLabel: "Scott County, MN" },
    { slug: "wright", name: "Wright", seat: "Buffalo", href: "/local-movers/minnesota/wright", displayLabel: "Wright County, MN" },
    { slug: "sibley", name: "Sibley", seat: "Gaylord", href: "/local-movers/minnesota/sibley", displayLabel: "Sibley County, MN" },
  ],
  sherburne: [
    { slug: "anoka", name: "Anoka", seat: "Anoka", href: "/local-movers/minnesota/anoka", displayLabel: "Anoka County, MN" },
    { slug: "benton", name: "Benton", seat: "Foley", href: "/local-movers/minnesota/benton", displayLabel: "Benton County, MN" },
    { slug: "hennepin", name: "Hennepin", seat: "Minneapolis", href: "/local-movers/minnesota/hennepin", displayLabel: "Hennepin County, MN" },
    { slug: "isanti", name: "Isanti", seat: "Cambridge", href: "/local-movers/minnesota/isanti", displayLabel: "Isanti County, MN" },
    { slug: "stearns", name: "Stearns", seat: "St. Cloud", href: "/local-movers/minnesota/stearns", displayLabel: "Stearns County, MN" },
  ],
  'blue-earth': [
    { slug: "nicollet", name: "Nicollet", seat: "St. Peter", href: "/local-movers/minnesota/nicollet", displayLabel: "Nicollet County, MN" },
    { slug: "brown", name: "Brown", seat: "New Ulm", href: "/local-movers/minnesota/brown", displayLabel: "Brown County, MN" },
    { slug: "faribault", name: "Faribault", seat: "Blue Earth", href: "/local-movers/minnesota/faribault", displayLabel: "Faribault County, MN" },
    { slug: "le-sueur", name: "Le Sueur", seat: "Le Center", href: "/local-movers/minnesota/le-sueur", displayLabel: "Le Sueur County, MN" },
    { slug: "martin", name: "Martin", seat: "Fairmont", href: "/local-movers/minnesota/martin", displayLabel: "Martin County, MN" },
  ],
  rice: [
    { slug: "dakota", name: "Dakota", seat: "Hastings", href: "/local-movers/minnesota/dakota", displayLabel: "Dakota County, MN" },
    { slug: "goodhue", name: "Goodhue", seat: "Red Wing", href: "/local-movers/minnesota/goodhue", displayLabel: "Goodhue County, MN" },
    { slug: "scott", name: "Scott", seat: "Shakopee", href: "/local-movers/minnesota/scott", displayLabel: "Scott County, MN" },
    { slug: "steele", name: "Steele", seat: "Owatonna", href: "/local-movers/minnesota/steele", displayLabel: "Steele County, MN" },
    { slug: "dodge", name: "Dodge", seat: "Mantorville", href: "/local-movers/minnesota/dodge", displayLabel: "Dodge County, MN" },
  ],
  'crow-wing': [
    { slug: "cass", name: "Cass", seat: "Walker", href: "/local-movers/minnesota/cass", displayLabel: "Cass County, MN" },
    { slug: "morrison", name: "Morrison", seat: "Little Falls", href: "/local-movers/minnesota/morrison", displayLabel: "Morrison County, MN" },
    { slug: "aitkin", name: "Aitkin", seat: "Aitkin", href: "/local-movers/minnesota/aitkin", displayLabel: "Aitkin County, MN" },
    { slug: "mille-lacs", name: "Mille Lacs", seat: "Milaca", href: "/local-movers/minnesota/mille-lacs", displayLabel: "Mille Lacs County, MN" },
  ],
  clay: [
    { slug: "becker", name: "Becker", seat: "Detroit Lakes", href: "/local-movers/minnesota/becker", displayLabel: "Becker County, MN" },
    { slug: "otter-tail", name: "Otter Tail", seat: "Fergus Falls", href: "/local-movers/minnesota/otter-tail", displayLabel: "Otter Tail County, MN" },
    { slug: "norman", name: "Norman", seat: "Ada", href: "/local-movers/minnesota/norman", displayLabel: "Norman County, MN" },
    { slug: "wilkin", name: "Wilkin", seat: "Breckenridge", href: "/local-movers/minnesota/wilkin", displayLabel: "Wilkin County, MN" },
    { slug: "cass", name: "Cass", seat: "Fargo", href: "/local-movers/north-dakota/cass", displayLabel: "Cass County, ND" },
  ],
  'otter-tail': [
    { slug: "becker", name: "Becker", seat: "Detroit Lakes", href: "/local-movers/minnesota/becker", displayLabel: "Becker County, MN" },
    { slug: "clay", name: "Clay", seat: "Moorhead", href: "/local-movers/minnesota/clay", displayLabel: "Clay County, MN" },
    { slug: "douglas", name: "Douglas", seat: "Alexandria", href: "/local-movers/minnesota/douglas", displayLabel: "Douglas County, MN" },
    { slug: "grant", name: "Grant", seat: "Elbow Lake", href: "/local-movers/minnesota/grant", displayLabel: "Grant County, MN" },
    { slug: "todd", name: "Todd", seat: "Long Prairie", href: "/local-movers/minnesota/todd", displayLabel: "Todd County, MN" },
  ],
  chisago: [
    { slug: "anoka", name: "Anoka", seat: "Anoka", href: "/local-movers/minnesota/anoka", displayLabel: "Anoka County, MN" },
    { slug: "isanti", name: "Isanti", seat: "Cambridge", href: "/local-movers/minnesota/isanti", displayLabel: "Isanti County, MN" },
    { slug: "pine", name: "Pine", seat: "Pine City", href: "/local-movers/minnesota/pine", displayLabel: "Pine County, MN" },
    { slug: "washington", name: "Washington", seat: "Stillwater", href: "/local-movers/minnesota/washington", displayLabel: "Washington County, MN" },
    { slug: "kanabec", name: "Kanabec", seat: "Mora", href: "/local-movers/minnesota/kanabec", displayLabel: "Kanabec County, MN" },
  ],
  winona: [
    { slug: "olmsted", name: "Olmsted", seat: "Rochester", href: "/local-movers/minnesota/olmsted", displayLabel: "Olmsted County, MN" },
    { slug: "fillmore", name: "Fillmore", seat: "Preston", href: "/local-movers/minnesota/fillmore", displayLabel: "Fillmore County, MN" },
    { slug: "houston", name: "Houston", seat: "Caledonia", href: "/local-movers/minnesota/houston", displayLabel: "Houston County, MN" },
    { slug: "wabasha", name: "Wabasha", seat: "Wabasha", href: "/local-movers/minnesota/wabasha", displayLabel: "Wabasha County, MN" },
  ],
  goodhue: [
    { slug: "dakota", name: "Dakota", seat: "Hastings", href: "/local-movers/minnesota/dakota", displayLabel: "Dakota County, MN" },
    { slug: "olmsted", name: "Olmsted", seat: "Rochester", href: "/local-movers/minnesota/olmsted", displayLabel: "Olmsted County, MN" },
    { slug: "rice", name: "Rice", seat: "Faribault", href: "/local-movers/minnesota/rice", displayLabel: "Rice County, MN" },
    { slug: "steele", name: "Steele", seat: "Owatonna", href: "/local-movers/minnesota/steele", displayLabel: "Steele County, MN" },
    { slug: "pierce", name: "Pierce", seat: "Ellsworth", href: "/local-movers/wisconsin/pierce", displayLabel: "Pierce County, WI" },
  ],
  beltrami: [
    { slug: "cass", name: "Cass", seat: "Walker", href: "/local-movers/minnesota/cass", displayLabel: "Cass County, MN" },
    { slug: "itasca", name: "Itasca", seat: "Grand Rapids", href: "/local-movers/minnesota/itasca", displayLabel: "Itasca County, MN" },
    { slug: "clearwater", name: "Clearwater", seat: "Bagley", href: "/local-movers/minnesota/clearwater", displayLabel: "Clearwater County, MN" },
    { slug: "hubbard", name: "Hubbard", seat: "Park Rapids", href: "/local-movers/minnesota/hubbard", displayLabel: "Hubbard County, MN" },
    { slug: "koochiching", name: "Koochiching", seat: "International Falls", href: "/local-movers/minnesota/koochiching", displayLabel: "Koochiching County, MN" },
  ],
  itasca: [
    { slug: "beltrami", name: "Beltrami", seat: "Bemidji", href: "/local-movers/minnesota/beltrami", displayLabel: "Beltrami County, MN" },
    { slug: "cass", name: "Cass", seat: "Walker", href: "/local-movers/minnesota/cass", displayLabel: "Cass County, MN" },
    { slug: "st-louis", name: "St. Louis", seat: "Duluth", href: "/local-movers/minnesota/st-louis", displayLabel: "St. Louis County, MN" },
    { slug: "aitkin", name: "Aitkin", seat: "Aitkin", href: "/local-movers/minnesota/aitkin", displayLabel: "Aitkin County, MN" },
    { slug: "koochiching", name: "Koochiching", seat: "International Falls", href: "/local-movers/minnesota/koochiching", displayLabel: "Koochiching County, MN" },
  ],
  isanti: [
    { slug: "anoka", name: "Anoka", seat: "Anoka", href: "/local-movers/minnesota/anoka", displayLabel: "Anoka County, MN" },
    { slug: "chisago", name: "Chisago", seat: "Center City", href: "/local-movers/minnesota/chisago", displayLabel: "Chisago County, MN" },
    { slug: "sherburne", name: "Sherburne", seat: "Elk River", href: "/local-movers/minnesota/sherburne", displayLabel: "Sherburne County, MN" },
    { slug: "pine", name: "Pine", seat: "Pine City", href: "/local-movers/minnesota/pine", displayLabel: "Pine County, MN" },
    { slug: "kanabec", name: "Kanabec", seat: "Mora", href: "/local-movers/minnesota/kanabec", displayLabel: "Kanabec County, MN" },
  ],
  kandiyohi: [
    { slug: "stearns", name: "Stearns", seat: "St. Cloud", href: "/local-movers/minnesota/stearns", displayLabel: "Stearns County, MN" },
    { slug: "chippewa", name: "Chippewa", seat: "Montevideo", href: "/local-movers/minnesota/chippewa", displayLabel: "Chippewa County, MN" },
    { slug: "meeker", name: "Meeker", seat: "Litchfield", href: "/local-movers/minnesota/meeker", displayLabel: "Meeker County, MN" },
    { slug: "pope", name: "Pope", seat: "Glenwood", href: "/local-movers/minnesota/pope", displayLabel: "Pope County, MN" },
    { slug: "renville", name: "Renville", seat: "Olivia", href: "/local-movers/minnesota/renville", displayLabel: "Renville County, MN" },
  ],
  benton: [
    { slug: "morrison", name: "Morrison", seat: "Little Falls", href: "/local-movers/minnesota/morrison", displayLabel: "Morrison County, MN" },
    { slug: "sherburne", name: "Sherburne", seat: "Elk River", href: "/local-movers/minnesota/sherburne", displayLabel: "Sherburne County, MN" },
    { slug: "stearns", name: "Stearns", seat: "St. Cloud", href: "/local-movers/minnesota/stearns", displayLabel: "Stearns County, MN" },
    { slug: "mille-lacs", name: "Mille Lacs", seat: "Milaca", href: "/local-movers/minnesota/mille-lacs", displayLabel: "Mille Lacs County, MN" },
  ],
  mower: [
    { slug: "olmsted", name: "Olmsted", seat: "Rochester", href: "/local-movers/minnesota/olmsted", displayLabel: "Olmsted County, MN" },
    { slug: "freeborn", name: "Freeborn", seat: "Albert Lea", href: "/local-movers/minnesota/freeborn", displayLabel: "Freeborn County, MN" },
    { slug: "steele", name: "Steele", seat: "Owatonna", href: "/local-movers/minnesota/steele", displayLabel: "Steele County, MN" },
    { slug: "dodge", name: "Dodge", seat: "Mantorville", href: "/local-movers/minnesota/dodge", displayLabel: "Dodge County, MN" },
    { slug: "fillmore", name: "Fillmore", seat: "Preston", href: "/local-movers/minnesota/fillmore", displayLabel: "Fillmore County, MN" },
  ],
  douglas: [
    { slug: "otter-tail", name: "Otter Tail", seat: "Fergus Falls", href: "/local-movers/minnesota/otter-tail", displayLabel: "Otter Tail County, MN" },
    { slug: "stearns", name: "Stearns", seat: "St. Cloud", href: "/local-movers/minnesota/stearns", displayLabel: "Stearns County, MN" },
    { slug: "grant", name: "Grant", seat: "Elbow Lake", href: "/local-movers/minnesota/grant", displayLabel: "Grant County, MN" },
    { slug: "pope", name: "Pope", seat: "Glenwood", href: "/local-movers/minnesota/pope", displayLabel: "Pope County, MN" },
    { slug: "stevens", name: "Stevens", seat: "Morris", href: "/local-movers/minnesota/stevens", displayLabel: "Stevens County, MN" },
  ],
  steele: [
    { slug: "goodhue", name: "Goodhue", seat: "Red Wing", href: "/local-movers/minnesota/goodhue", displayLabel: "Goodhue County, MN" },
    { slug: "mower", name: "Mower", seat: "Austin", href: "/local-movers/minnesota/mower", displayLabel: "Mower County, MN" },
    { slug: "rice", name: "Rice", seat: "Faribault", href: "/local-movers/minnesota/rice", displayLabel: "Rice County, MN" },
    { slug: "freeborn", name: "Freeborn", seat: "Albert Lea", href: "/local-movers/minnesota/freeborn", displayLabel: "Freeborn County, MN" },
    { slug: "dodge", name: "Dodge", seat: "Mantorville", href: "/local-movers/minnesota/dodge", displayLabel: "Dodge County, MN" },
  ],
  carlton: [
    { slug: "st-louis", name: "St. Louis", seat: "Duluth", href: "/local-movers/minnesota/st-louis", displayLabel: "St. Louis County, MN" },
    { slug: "pine", name: "Pine", seat: "Pine City", href: "/local-movers/minnesota/pine", displayLabel: "Pine County, MN" },
    { slug: "aitkin", name: "Aitkin", seat: "Aitkin", href: "/local-movers/minnesota/aitkin", displayLabel: "Aitkin County, MN" },
  ],
  mcleod: [
    { slug: "carver", name: "Carver", seat: "Chaska", href: "/local-movers/minnesota/carver", displayLabel: "Carver County, MN" },
    { slug: "wright", name: "Wright", seat: "Buffalo", href: "/local-movers/minnesota/wright", displayLabel: "Wright County, MN" },
    { slug: "meeker", name: "Meeker", seat: "Litchfield", href: "/local-movers/minnesota/meeker", displayLabel: "Meeker County, MN" },
    { slug: "renville", name: "Renville", seat: "Olivia", href: "/local-movers/minnesota/renville", displayLabel: "Renville County, MN" },
    { slug: "sibley", name: "Sibley", seat: "Gaylord", href: "/local-movers/minnesota/sibley", displayLabel: "Sibley County, MN" },
  ],
  becker: [
    { slug: "clay", name: "Clay", seat: "Moorhead", href: "/local-movers/minnesota/clay", displayLabel: "Clay County, MN" },
    { slug: "otter-tail", name: "Otter Tail", seat: "Fergus Falls", href: "/local-movers/minnesota/otter-tail", displayLabel: "Otter Tail County, MN" },
    { slug: "clearwater", name: "Clearwater", seat: "Bagley", href: "/local-movers/minnesota/clearwater", displayLabel: "Clearwater County, MN" },
    { slug: "hubbard", name: "Hubbard", seat: "Park Rapids", href: "/local-movers/minnesota/hubbard", displayLabel: "Hubbard County, MN" },
    { slug: "mahnomen", name: "Mahnomen", seat: "Mahnomen", href: "/local-movers/minnesota/mahnomen", displayLabel: "Mahnomen County, MN" },
  ],
  morrison: [
    { slug: "benton", name: "Benton", seat: "Foley", href: "/local-movers/minnesota/benton", displayLabel: "Benton County, MN" },
    { slug: "cass", name: "Cass", seat: "Walker", href: "/local-movers/minnesota/cass", displayLabel: "Cass County, MN" },
    { slug: "crow-wing", name: "Crow Wing", seat: "Brainerd", href: "/local-movers/minnesota/crow-wing", displayLabel: "Crow Wing County, MN" },
    { slug: "stearns", name: "Stearns", seat: "St. Cloud", href: "/local-movers/minnesota/stearns", displayLabel: "Stearns County, MN" },
    { slug: "mille-lacs", name: "Mille Lacs", seat: "Milaca", href: "/local-movers/minnesota/mille-lacs", displayLabel: "Mille Lacs County, MN" },
  ],
  nicollet: [
    { slug: "blue-earth", name: "Blue Earth", seat: "Mankato", href: "/local-movers/minnesota/blue-earth", displayLabel: "Blue Earth County, MN" },
    { slug: "le-sueur", name: "Le Sueur", seat: "Le Center", href: "/local-movers/minnesota/le-sueur", displayLabel: "Le Sueur County, MN" },
    { slug: "renville", name: "Renville", seat: "Olivia", href: "/local-movers/minnesota/renville", displayLabel: "Renville County, MN" },
    { slug: "sibley", name: "Sibley", seat: "Gaylord", href: "/local-movers/minnesota/sibley", displayLabel: "Sibley County, MN" },
    { slug: "brown", name: "Brown", seat: "New Ulm", href: "/local-movers/minnesota/brown", displayLabel: "Brown County, MN" },
  ],
  cass: [
    { slug: "beltrami", name: "Beltrami", seat: "Bemidji", href: "/local-movers/minnesota/beltrami", displayLabel: "Beltrami County, MN" },
    { slug: "becker", name: "Becker", seat: "Detroit Lakes", href: "/local-movers/minnesota/becker", displayLabel: "Becker County, MN" },
    { slug: "crow-wing", name: "Crow Wing", seat: "Brainerd", href: "/local-movers/minnesota/crow-wing", displayLabel: "Crow Wing County, MN" },
    { slug: "itasca", name: "Itasca", seat: "Grand Rapids", href: "/local-movers/minnesota/itasca", displayLabel: "Itasca County, MN" },
    { slug: "morrison", name: "Morrison", seat: "Little Falls", href: "/local-movers/minnesota/morrison", displayLabel: "Morrison County, MN" },
  ],
  pine: [
    { slug: "carlton", name: "Carlton", seat: "Carlton", href: "/local-movers/minnesota/carlton", displayLabel: "Carlton County, MN" },
    { slug: "chisago", name: "Chisago", seat: "Center City", href: "/local-movers/minnesota/chisago", displayLabel: "Chisago County, MN" },
    { slug: "isanti", name: "Isanti", seat: "Cambridge", href: "/local-movers/minnesota/isanti", displayLabel: "Isanti County, MN" },
    { slug: "kanabec", name: "Kanabec", seat: "Mora", href: "/local-movers/minnesota/kanabec", displayLabel: "Kanabec County, MN" },
    { slug: "aitkin", name: "Aitkin", seat: "Aitkin", href: "/local-movers/minnesota/aitkin", displayLabel: "Aitkin County, MN" },
  ],
  freeborn: [
    { slug: "mower", name: "Mower", seat: "Austin", href: "/local-movers/minnesota/mower", displayLabel: "Mower County, MN" },
    { slug: "steele", name: "Steele", seat: "Owatonna", href: "/local-movers/minnesota/steele", displayLabel: "Steele County, MN" },
    { slug: "dodge", name: "Dodge", seat: "Mantorville", href: "/local-movers/minnesota/dodge", displayLabel: "Dodge County, MN" },
    { slug: "faribault", name: "Faribault", seat: "Blue Earth", href: "/local-movers/minnesota/faribault", displayLabel: "Faribault County, MN" },
    { slug: "waseca", name: "Waseca", seat: "Waseca", href: "/local-movers/minnesota/waseca", displayLabel: "Waseca County, MN" },
  ],
  polk: [
    { slug: "clearwater", name: "Clearwater", seat: "Bagley", href: "/local-movers/minnesota/clearwater", displayLabel: "Clearwater County, MN" },
    { slug: "mahnomen", name: "Mahnomen", seat: "Mahnomen", href: "/local-movers/minnesota/mahnomen", displayLabel: "Mahnomen County, MN" },
    { slug: "marshall", name: "Marshall", seat: "Warren", href: "/local-movers/minnesota/marshall", displayLabel: "Marshall County, MN" },
    { slug: "norman", name: "Norman", seat: "Ada", href: "/local-movers/minnesota/norman", displayLabel: "Norman County, MN" },
    { slug: "walsh", name: "Walsh", seat: "Grafton", href: "/local-movers/north-dakota/walsh", displayLabel: "Walsh County, ND" },
  ],
};

export function getMinnesotaNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return MN_COUNTY_NEIGHBORS[countySlug] ?? [];
}
