import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** Nebraska curated county corridor links — all 93 counties */
const NE_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  douglas: [
    { slug: 'dodge', name: 'Dodge', seat: 'Fremont', href: '/local-movers/nebraska/dodge', displayLabel: 'Dodge County, NE' },
    { slug: 'sarpy', name: 'Sarpy', seat: 'Papillion', href: '/local-movers/nebraska/sarpy', displayLabel: 'Sarpy County, NE' },
    { slug: 'saunders', name: 'Saunders', seat: 'Wahoo', href: '/local-movers/nebraska/saunders', displayLabel: 'Saunders County, NE' },
    { slug: 'washington', name: 'Washington', seat: 'Blair', href: '/local-movers/nebraska/washington', displayLabel: 'Washington County, NE' },
    { slug: 'pottawattamie', name: 'Pottawattamie', seat: 'Council Bluffs', href: '/local-movers/iowa/pottawattamie', displayLabel: 'Pottawattamie County, IA' },
  ],
  lancaster: [
    { slug: 'butler', name: 'Butler', seat: 'David City', href: '/local-movers/nebraska/butler', displayLabel: 'Butler County, NE' },
    { slug: 'cass', name: 'Cass', seat: 'Plattsmouth', href: '/local-movers/nebraska/cass', displayLabel: 'Cass County, NE' },
    { slug: 'gage', name: 'Gage', seat: 'Beatrice', href: '/local-movers/nebraska/gage', displayLabel: 'Gage County, NE' },
    { slug: 'johnson', name: 'Johnson', seat: 'Tecumseh', href: '/local-movers/nebraska/johnson', displayLabel: 'Johnson County, NE' },
    { slug: 'otoe', name: 'Otoe', seat: 'Nebraska City', href: '/local-movers/nebraska/otoe', displayLabel: 'Otoe County, NE' },
  ],
  sarpy: [
    { slug: 'cass', name: 'Cass', seat: 'Plattsmouth', href: '/local-movers/nebraska/cass', displayLabel: 'Cass County, NE' },
    { slug: 'douglas', name: 'Douglas', seat: 'Omaha', href: '/local-movers/nebraska/douglas', displayLabel: 'Douglas County, NE' },
    { slug: 'saunders', name: 'Saunders', seat: 'Wahoo', href: '/local-movers/nebraska/saunders', displayLabel: 'Saunders County, NE' },
    { slug: 'pottawattamie', name: 'Pottawattamie', seat: 'Council Bluffs', href: '/local-movers/iowa/pottawattamie', displayLabel: 'Pottawattamie County, IA' },
    { slug: 'mills', name: 'Mills', seat: 'Glenwood', href: '/local-movers/iowa/mills', displayLabel: 'Mills County, IA' },
  ],
  hall: [
    { slug: 'adams', name: 'Adams', seat: 'Hastings', href: '/local-movers/nebraska/adams', displayLabel: 'Adams County, NE' },
    { slug: 'buffalo', name: 'Buffalo', seat: 'Kearney', href: '/local-movers/nebraska/buffalo', displayLabel: 'Buffalo County, NE' },
    { slug: 'clay', name: 'Clay', seat: 'Clay Center', href: '/local-movers/nebraska/clay', displayLabel: 'Clay County, NE' },
    { slug: 'hamilton', name: 'Hamilton', seat: 'Aurora', href: '/local-movers/nebraska/hamilton', displayLabel: 'Hamilton County, NE' },
    { slug: 'howard', name: 'Howard', seat: 'St. Paul', href: '/local-movers/nebraska/howard', displayLabel: 'Howard County, NE' },
  ],
  buffalo: [
    { slug: 'adams', name: 'Adams', seat: 'Hastings', href: '/local-movers/nebraska/adams', displayLabel: 'Adams County, NE' },
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'dawson', name: 'Dawson', seat: 'Lexington', href: '/local-movers/nebraska/dawson', displayLabel: 'Dawson County, NE' },
    { slug: 'hall', name: 'Hall', seat: 'Grand Island', href: '/local-movers/nebraska/hall', displayLabel: 'Hall County, NE' },
    { slug: 'howard', name: 'Howard', seat: 'St. Paul', href: '/local-movers/nebraska/howard', displayLabel: 'Howard County, NE' },
  ],
  dodge: [
    { slug: 'burt', name: 'Burt', seat: 'Tekamah', href: '/local-movers/nebraska/burt', displayLabel: 'Burt County, NE' },
    { slug: 'butler', name: 'Butler', seat: 'David City', href: '/local-movers/nebraska/butler', displayLabel: 'Butler County, NE' },
    { slug: 'colfax', name: 'Colfax', seat: 'Schuyler', href: '/local-movers/nebraska/colfax', displayLabel: 'Colfax County, NE' },
    { slug: 'cuming', name: 'Cuming', seat: 'West Point', href: '/local-movers/nebraska/cuming', displayLabel: 'Cuming County, NE' },
    { slug: 'douglas', name: 'Douglas', seat: 'Omaha', href: '/local-movers/nebraska/douglas', displayLabel: 'Douglas County, NE' },
  ],
  madison: [
    { slug: 'antelope', name: 'Antelope', seat: 'Neligh', href: '/local-movers/nebraska/antelope', displayLabel: 'Antelope County, NE' },
    { slug: 'boone', name: 'Boone', seat: 'Albion', href: '/local-movers/nebraska/boone', displayLabel: 'Boone County, NE' },
    { slug: 'pierce', name: 'Pierce', seat: 'Pierce', href: '/local-movers/nebraska/pierce', displayLabel: 'Pierce County, NE' },
    { slug: 'platte', name: 'Platte', seat: 'Columbus', href: '/local-movers/nebraska/platte', displayLabel: 'Platte County, NE' },
    { slug: 'stanton', name: 'Stanton', seat: 'Stanton', href: '/local-movers/nebraska/stanton', displayLabel: 'Stanton County, NE' },
  ],
  platte: [
    { slug: 'boone', name: 'Boone', seat: 'Albion', href: '/local-movers/nebraska/boone', displayLabel: 'Boone County, NE' },
    { slug: 'butler', name: 'Butler', seat: 'David City', href: '/local-movers/nebraska/butler', displayLabel: 'Butler County, NE' },
    { slug: 'colfax', name: 'Colfax', seat: 'Schuyler', href: '/local-movers/nebraska/colfax', displayLabel: 'Colfax County, NE' },
    { slug: 'madison', name: 'Madison', seat: 'Norfolk', href: '/local-movers/nebraska/madison', displayLabel: 'Madison County, NE' },
    { slug: 'merrick', name: 'Merrick', seat: 'Central City', href: '/local-movers/nebraska/merrick', displayLabel: 'Merrick County, NE' },
  ],
  'scotts-bluff': [
    { slug: 'banner', name: 'Banner', seat: 'Harrisburg', href: '/local-movers/nebraska/banner', displayLabel: 'Banner County, NE' },
    { slug: 'box-butte', name: 'Box Butte', seat: 'Alliance', href: '/local-movers/nebraska/box-butte', displayLabel: 'Box Butte County, NE' },
    { slug: 'morrill', name: 'Morrill', seat: 'Bridgeport', href: '/local-movers/nebraska/morrill', displayLabel: 'Morrill County, NE' },
    { slug: 'sioux', name: 'Sioux', seat: 'Harrison', href: '/local-movers/nebraska/sioux', displayLabel: 'Sioux County, NE' },
    { slug: 'goshen', name: 'Goshen', seat: 'Torrington', href: '/local-movers/wyoming/goshen', displayLabel: 'Goshen County, WY' },
  ],
  lincoln: [
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'dawson', name: 'Dawson', seat: 'Lexington', href: '/local-movers/nebraska/dawson', displayLabel: 'Dawson County, NE' },
    { slug: 'frontier', name: 'Frontier', seat: 'Stockville', href: '/local-movers/nebraska/frontier', displayLabel: 'Frontier County, NE' },
    { slug: 'hayes', name: 'Hayes', seat: 'Hayes Center', href: '/local-movers/nebraska/hayes', displayLabel: 'Hayes County, NE' },
    { slug: 'keith', name: 'Keith', seat: 'Ogallala', href: '/local-movers/nebraska/keith', displayLabel: 'Keith County, NE' },
  ],
  adams: [
    { slug: 'buffalo', name: 'Buffalo', seat: 'Kearney', href: '/local-movers/nebraska/buffalo', displayLabel: 'Buffalo County, NE' },
    { slug: 'clay', name: 'Clay', seat: 'Clay Center', href: '/local-movers/nebraska/clay', displayLabel: 'Clay County, NE' },
    { slug: 'franklin', name: 'Franklin', seat: 'Franklin', href: '/local-movers/nebraska/franklin', displayLabel: 'Franklin County, NE' },
    { slug: 'hall', name: 'Hall', seat: 'Grand Island', href: '/local-movers/nebraska/hall', displayLabel: 'Hall County, NE' },
    { slug: 'hamilton', name: 'Hamilton', seat: 'Aurora', href: '/local-movers/nebraska/hamilton', displayLabel: 'Hamilton County, NE' },
  ],
  cass: [
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lincoln', href: '/local-movers/nebraska/lancaster', displayLabel: 'Lancaster County, NE' },
    { slug: 'otoe', name: 'Otoe', seat: 'Nebraska City', href: '/local-movers/nebraska/otoe', displayLabel: 'Otoe County, NE' },
    { slug: 'sarpy', name: 'Sarpy', seat: 'Papillion', href: '/local-movers/nebraska/sarpy', displayLabel: 'Sarpy County, NE' },
    { slug: 'mills', name: 'Mills', seat: 'Glenwood', href: '/local-movers/iowa/mills', displayLabel: 'Mills County, IA' },
    { slug: 'pottawattamie', name: 'Pottawattamie', seat: 'Council Bluffs', href: '/local-movers/iowa/pottawattamie', displayLabel: 'Pottawattamie County, IA' },
  ],
  dawson: [
    { slug: 'buffalo', name: 'Buffalo', seat: 'Kearney', href: '/local-movers/nebraska/buffalo', displayLabel: 'Buffalo County, NE' },
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'frontier', name: 'Frontier', seat: 'Stockville', href: '/local-movers/nebraska/frontier', displayLabel: 'Frontier County, NE' },
    { slug: 'gosper', name: 'Gosper', seat: 'Elwood', href: '/local-movers/nebraska/gosper', displayLabel: 'Gosper County, NE' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'North Platte', href: '/local-movers/nebraska/lincoln', displayLabel: 'Lincoln County, NE' },
  ],
  saunders: [
    { slug: 'butler', name: 'Butler', seat: 'David City', href: '/local-movers/nebraska/butler', displayLabel: 'Butler County, NE' },
    { slug: 'cass', name: 'Cass', seat: 'Plattsmouth', href: '/local-movers/nebraska/cass', displayLabel: 'Cass County, NE' },
    { slug: 'colfax', name: 'Colfax', seat: 'Schuyler', href: '/local-movers/nebraska/colfax', displayLabel: 'Colfax County, NE' },
    { slug: 'dodge', name: 'Dodge', seat: 'Fremont', href: '/local-movers/nebraska/dodge', displayLabel: 'Dodge County, NE' },
    { slug: 'douglas', name: 'Douglas', seat: 'Omaha', href: '/local-movers/nebraska/douglas', displayLabel: 'Douglas County, NE' },
  ],
  dakota: [
    { slug: 'dixon', name: 'Dixon', seat: 'Ponca', href: '/local-movers/nebraska/dixon', displayLabel: 'Dixon County, NE' },
    { slug: 'thurston', name: 'Thurston', seat: 'Pender', href: '/local-movers/nebraska/thurston', displayLabel: 'Thurston County, NE' },
    { slug: 'woodbury', name: 'Woodbury', seat: 'Sioux City', href: '/local-movers/iowa/woodbury', displayLabel: 'Woodbury County, IA' },
  ],
  gage: [
    { slug: 'jefferson', name: 'Jefferson', seat: 'Fairbury', href: '/local-movers/nebraska/jefferson', displayLabel: 'Jefferson County, NE' },
    { slug: 'johnson', name: 'Johnson', seat: 'Tecumseh', href: '/local-movers/nebraska/johnson', displayLabel: 'Johnson County, NE' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lincoln', href: '/local-movers/nebraska/lancaster', displayLabel: 'Lancaster County, NE' },
    { slug: 'otoe', name: 'Otoe', seat: 'Nebraska City', href: '/local-movers/nebraska/otoe', displayLabel: 'Otoe County, NE' },
    { slug: 'marshall', name: 'Marshall', seat: 'Marysville', href: '/local-movers/kansas/marshall', displayLabel: 'Marshall County, KS' },
  ],
  washington: [
    { slug: 'dodge', name: 'Dodge', seat: 'Fremont', href: '/local-movers/nebraska/dodge', displayLabel: 'Dodge County, NE' },
    { slug: 'douglas', name: 'Douglas', seat: 'Omaha', href: '/local-movers/nebraska/douglas', displayLabel: 'Douglas County, NE' },
    { slug: 'burt', name: 'Burt', seat: 'Tekamah', href: '/local-movers/iowa/burt', displayLabel: 'Burt County, IA' },
  ],
  seward: [
    { slug: 'butler', name: 'Butler', seat: 'David City', href: '/local-movers/nebraska/butler', displayLabel: 'Butler County, NE' },
    { slug: 'fillmore', name: 'Fillmore', seat: 'Geneva', href: '/local-movers/nebraska/fillmore', displayLabel: 'Fillmore County, NE' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lincoln', href: '/local-movers/nebraska/lancaster', displayLabel: 'Lancaster County, NE' },
    { slug: 'polk', name: 'Polk', seat: 'Osceola', href: '/local-movers/nebraska/polk', displayLabel: 'Polk County, NE' },
    { slug: 'saline', name: 'Saline', seat: 'Wilber', href: '/local-movers/nebraska/saline', displayLabel: 'Saline County, NE' },
  ],
  otoe: [
    { slug: 'cass', name: 'Cass', seat: 'Plattsmouth', href: '/local-movers/nebraska/cass', displayLabel: 'Cass County, NE' },
    { slug: 'gage', name: 'Gage', seat: 'Beatrice', href: '/local-movers/nebraska/gage', displayLabel: 'Gage County, NE' },
    { slug: 'johnson', name: 'Johnson', seat: 'Tecumseh', href: '/local-movers/nebraska/johnson', displayLabel: 'Johnson County, NE' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lincoln', href: '/local-movers/nebraska/lancaster', displayLabel: 'Lancaster County, NE' },
    { slug: 'nemaha', name: 'Nemaha', seat: 'Auburn', href: '/local-movers/nebraska/nemaha', displayLabel: 'Nemaha County, NE' },
  ],
  saline: [
    { slug: 'fillmore', name: 'Fillmore', seat: 'Geneva', href: '/local-movers/nebraska/fillmore', displayLabel: 'Fillmore County, NE' },
    { slug: 'gage', name: 'Gage', seat: 'Beatrice', href: '/local-movers/nebraska/gage', displayLabel: 'Gage County, NE' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Fairbury', href: '/local-movers/nebraska/jefferson', displayLabel: 'Jefferson County, NE' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lincoln', href: '/local-movers/nebraska/lancaster', displayLabel: 'Lancaster County, NE' },
    { slug: 'seward', name: 'Seward', seat: 'Seward', href: '/local-movers/nebraska/seward', displayLabel: 'Seward County, NE' },
  ],
  york: [
    { slug: 'butler', name: 'Butler', seat: 'David City', href: '/local-movers/nebraska/butler', displayLabel: 'Butler County, NE' },
    { slug: 'clay', name: 'Clay', seat: 'Clay Center', href: '/local-movers/nebraska/clay', displayLabel: 'Clay County, NE' },
    { slug: 'fillmore', name: 'Fillmore', seat: 'Geneva', href: '/local-movers/nebraska/fillmore', displayLabel: 'Fillmore County, NE' },
    { slug: 'hamilton', name: 'Hamilton', seat: 'Aurora', href: '/local-movers/nebraska/hamilton', displayLabel: 'Hamilton County, NE' },
    { slug: 'polk', name: 'Polk', seat: 'Osceola', href: '/local-movers/nebraska/polk', displayLabel: 'Polk County, NE' },
  ],
  colfax: [
    { slug: 'butler', name: 'Butler', seat: 'David City', href: '/local-movers/nebraska/butler', displayLabel: 'Butler County, NE' },
    { slug: 'cuming', name: 'Cuming', seat: 'West Point', href: '/local-movers/nebraska/cuming', displayLabel: 'Cuming County, NE' },
    { slug: 'dodge', name: 'Dodge', seat: 'Fremont', href: '/local-movers/nebraska/dodge', displayLabel: 'Dodge County, NE' },
    { slug: 'platte', name: 'Platte', seat: 'Columbus', href: '/local-movers/nebraska/platte', displayLabel: 'Platte County, NE' },
    { slug: 'saunders', name: 'Saunders', seat: 'Wahoo', href: '/local-movers/nebraska/saunders', displayLabel: 'Saunders County, NE' },
  ],
  custer: [
    { slug: 'blaine', name: 'Blaine', seat: 'Brewster', href: '/local-movers/nebraska/blaine', displayLabel: 'Blaine County, NE' },
    { slug: 'buffalo', name: 'Buffalo', seat: 'Kearney', href: '/local-movers/nebraska/buffalo', displayLabel: 'Buffalo County, NE' },
    { slug: 'dawson', name: 'Dawson', seat: 'Lexington', href: '/local-movers/nebraska/dawson', displayLabel: 'Dawson County, NE' },
    { slug: 'garfield', name: 'Garfield', seat: 'Burwell', href: '/local-movers/nebraska/garfield', displayLabel: 'Garfield County, NE' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'North Platte', href: '/local-movers/nebraska/lincoln', displayLabel: 'Lincoln County, NE' },
  ],
  'box-butte': [
    { slug: 'dawes', name: 'Dawes', seat: 'Chadron', href: '/local-movers/nebraska/dawes', displayLabel: 'Dawes County, NE' },
    { slug: 'morrill', name: 'Morrill', seat: 'Bridgeport', href: '/local-movers/nebraska/morrill', displayLabel: 'Morrill County, NE' },
    { slug: 'scotts-bluff', name: 'Scotts Bluff', seat: 'Gering', href: '/local-movers/nebraska/scotts-bluff', displayLabel: 'Scotts Bluff County, NE' },
    { slug: 'sheridan', name: 'Sheridan', seat: 'Rushville', href: '/local-movers/nebraska/sheridan', displayLabel: 'Sheridan County, NE' },
    { slug: 'fall-river', name: 'Fall River', seat: 'Hot Springs', href: '/local-movers/south-dakota/fall-river', displayLabel: 'Fall River County, SD' },
  ],
  'red-willow': [
    { slug: 'frontier', name: 'Frontier', seat: 'Stockville', href: '/local-movers/nebraska/frontier', displayLabel: 'Frontier County, NE' },
    { slug: 'furnas', name: 'Furnas', seat: 'Beaver City', href: '/local-movers/nebraska/furnas', displayLabel: 'Furnas County, NE' },
    { slug: 'hitchcock', name: 'Hitchcock', seat: 'Trenton', href: '/local-movers/nebraska/hitchcock', displayLabel: 'Hitchcock County, NE' },
    { slug: 'rawlins', name: 'Rawlins', seat: 'Atwood', href: '/local-movers/kansas/rawlins', displayLabel: 'Rawlins County, KS' },
  ],
  wayne: [
    { slug: 'cedar', name: 'Cedar', seat: 'Hartington', href: '/local-movers/nebraska/cedar', displayLabel: 'Cedar County, NE' },
    { slug: 'cuming', name: 'Cuming', seat: 'West Point', href: '/local-movers/nebraska/cuming', displayLabel: 'Cuming County, NE' },
    { slug: 'dixon', name: 'Dixon', seat: 'Ponca', href: '/local-movers/nebraska/dixon', displayLabel: 'Dixon County, NE' },
    { slug: 'madison', name: 'Madison', seat: 'Norfolk', href: '/local-movers/nebraska/madison', displayLabel: 'Madison County, NE' },
    { slug: 'pierce', name: 'Pierce', seat: 'Pierce', href: '/local-movers/nebraska/pierce', displayLabel: 'Pierce County, NE' },
  ],
  holt: [
    { slug: 'antelope', name: 'Antelope', seat: 'Neligh', href: '/local-movers/nebraska/antelope', displayLabel: 'Antelope County, NE' },
    { slug: 'boyd', name: 'Boyd', seat: 'Butte', href: '/local-movers/nebraska/boyd', displayLabel: 'Boyd County, NE' },
    { slug: 'garfield', name: 'Garfield', seat: 'Burwell', href: '/local-movers/nebraska/garfield', displayLabel: 'Garfield County, NE' },
    { slug: 'keya-paha', name: 'Keya Paha', seat: 'Springview', href: '/local-movers/nebraska/keya-paha', displayLabel: 'Keya Paha County, NE' },
    { slug: 'knox', name: 'Knox', seat: 'Center', href: '/local-movers/nebraska/knox', displayLabel: 'Knox County, NE' },
  ],
  hamilton: [
    { slug: 'adams', name: 'Adams', seat: 'Hastings', href: '/local-movers/nebraska/adams', displayLabel: 'Adams County, NE' },
    { slug: 'clay', name: 'Clay', seat: 'Clay Center', href: '/local-movers/nebraska/clay', displayLabel: 'Clay County, NE' },
    { slug: 'fillmore', name: 'Fillmore', seat: 'Geneva', href: '/local-movers/nebraska/fillmore', displayLabel: 'Fillmore County, NE' },
    { slug: 'hall', name: 'Hall', seat: 'Grand Island', href: '/local-movers/nebraska/hall', displayLabel: 'Hall County, NE' },
    { slug: 'merrick', name: 'Merrick', seat: 'Central City', href: '/local-movers/nebraska/merrick', displayLabel: 'Merrick County, NE' },
  ],
  cheyenne: [
    { slug: 'banner', name: 'Banner', seat: 'Harrisburg', href: '/local-movers/nebraska/banner', displayLabel: 'Banner County, NE' },
    { slug: 'deuel', name: 'Deuel', seat: 'Chappell', href: '/local-movers/nebraska/deuel', displayLabel: 'Deuel County, NE' },
    { slug: 'garden', name: 'Garden', seat: 'Oshkosh', href: '/local-movers/nebraska/garden', displayLabel: 'Garden County, NE' },
    { slug: 'kimball', name: 'Kimball', seat: 'Kimball', href: '/local-movers/nebraska/kimball', displayLabel: 'Kimball County, NE' },
    { slug: 'logan', name: 'Logan', seat: 'Sterling', href: '/local-movers/colorado/logan', displayLabel: 'Logan County, CO' },
  ],
  phelps: [
    { slug: 'buffalo', name: 'Buffalo', seat: 'Kearney', href: '/local-movers/nebraska/buffalo', displayLabel: 'Buffalo County, NE' },
    { slug: 'dawson', name: 'Dawson', seat: 'Lexington', href: '/local-movers/nebraska/dawson', displayLabel: 'Dawson County, NE' },
    { slug: 'franklin', name: 'Franklin', seat: 'Franklin', href: '/local-movers/nebraska/franklin', displayLabel: 'Franklin County, NE' },
    { slug: 'furnas', name: 'Furnas', seat: 'Beaver City', href: '/local-movers/nebraska/furnas', displayLabel: 'Furnas County, NE' },
    { slug: 'gosper', name: 'Gosper', seat: 'Elwood', href: '/local-movers/nebraska/gosper', displayLabel: 'Gosper County, NE' },
  ],
  cuming: [
    { slug: 'burt', name: 'Burt', seat: 'Tekamah', href: '/local-movers/nebraska/burt', displayLabel: 'Burt County, NE' },
    { slug: 'colfax', name: 'Colfax', seat: 'Schuyler', href: '/local-movers/nebraska/colfax', displayLabel: 'Colfax County, NE' },
    { slug: 'dodge', name: 'Dodge', seat: 'Fremont', href: '/local-movers/nebraska/dodge', displayLabel: 'Dodge County, NE' },
    { slug: 'stanton', name: 'Stanton', seat: 'Stanton', href: '/local-movers/nebraska/stanton', displayLabel: 'Stanton County, NE' },
    { slug: 'thurston', name: 'Thurston', seat: 'Pender', href: '/local-movers/nebraska/thurston', displayLabel: 'Thurston County, NE' },
  ],
  butler: [
    { slug: 'colfax', name: 'Colfax', seat: 'Schuyler', href: '/local-movers/nebraska/colfax', displayLabel: 'Colfax County, NE' },
    { slug: 'dodge', name: 'Dodge', seat: 'Fremont', href: '/local-movers/nebraska/dodge', displayLabel: 'Dodge County, NE' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lincoln', href: '/local-movers/nebraska/lancaster', displayLabel: 'Lancaster County, NE' },
    { slug: 'platte', name: 'Platte', seat: 'Columbus', href: '/local-movers/nebraska/platte', displayLabel: 'Platte County, NE' },
    { slug: 'polk', name: 'Polk', seat: 'Osceola', href: '/local-movers/nebraska/polk', displayLabel: 'Polk County, NE' },
  ],
  cedar: [
    { slug: 'dixon', name: 'Dixon', seat: 'Ponca', href: '/local-movers/nebraska/dixon', displayLabel: 'Dixon County, NE' },
    { slug: 'knox', name: 'Knox', seat: 'Center', href: '/local-movers/nebraska/knox', displayLabel: 'Knox County, NE' },
    { slug: 'pierce', name: 'Pierce', seat: 'Pierce', href: '/local-movers/nebraska/pierce', displayLabel: 'Pierce County, NE' },
    { slug: 'wayne', name: 'Wayne', seat: 'Wayne', href: '/local-movers/nebraska/wayne', displayLabel: 'Wayne County, NE' },
    { slug: 'union', name: 'Union', seat: 'Elk Point', href: '/local-movers/south-dakota/union', displayLabel: 'Union County, SD' },
  ],
  knox: [
    { slug: 'antelope', name: 'Antelope', seat: 'Neligh', href: '/local-movers/nebraska/antelope', displayLabel: 'Antelope County, NE' },
    { slug: 'boyd', name: 'Boyd', seat: 'Butte', href: '/local-movers/nebraska/boyd', displayLabel: 'Boyd County, NE' },
    { slug: 'cedar', name: 'Cedar', seat: 'Hartington', href: '/local-movers/nebraska/cedar', displayLabel: 'Cedar County, NE' },
    { slug: 'holt', name: 'Holt', seat: "O'Neill", href: '/local-movers/nebraska/holt', displayLabel: 'Holt County, NE' },
    { slug: 'pierce', name: 'Pierce', seat: 'Pierce', href: '/local-movers/nebraska/pierce', displayLabel: 'Pierce County, NE' },
  ],
  keith: [
    { slug: 'arthur', name: 'Arthur', seat: 'Arthur', href: '/local-movers/nebraska/arthur', displayLabel: 'Arthur County, NE' },
    { slug: 'deuel', name: 'Deuel', seat: 'Chappell', href: '/local-movers/nebraska/deuel', displayLabel: 'Deuel County, NE' },
    { slug: 'garden', name: 'Garden', seat: 'Oshkosh', href: '/local-movers/nebraska/garden', displayLabel: 'Garden County, NE' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'North Platte', href: '/local-movers/nebraska/lincoln', displayLabel: 'Lincoln County, NE' },
    { slug: 'mcpherson', name: 'McPherson', seat: 'Tryon', href: '/local-movers/nebraska/mcpherson', displayLabel: 'McPherson County, NE' },
  ],
  merrick: [
    { slug: 'greeley', name: 'Greeley', seat: 'Greeley', href: '/local-movers/nebraska/greeley', displayLabel: 'Greeley County, NE' },
    { slug: 'hall', name: 'Hall', seat: 'Grand Island', href: '/local-movers/nebraska/hall', displayLabel: 'Hall County, NE' },
    { slug: 'hamilton', name: 'Hamilton', seat: 'Aurora', href: '/local-movers/nebraska/hamilton', displayLabel: 'Hamilton County, NE' },
    { slug: 'howard', name: 'Howard', seat: 'St. Paul', href: '/local-movers/nebraska/howard', displayLabel: 'Howard County, NE' },
    { slug: 'nance', name: 'Nance', seat: 'Fullerton', href: '/local-movers/nebraska/nance', displayLabel: 'Nance County, NE' },
  ],
  dawes: [
    { slug: 'box-butte', name: 'Box Butte', seat: 'Alliance', href: '/local-movers/nebraska/box-butte', displayLabel: 'Box Butte County, NE' },
    { slug: 'sheridan', name: 'Sheridan', seat: 'Rushville', href: '/local-movers/nebraska/sheridan', displayLabel: 'Sheridan County, NE' },
    { slug: 'sioux', name: 'Sioux', seat: 'Harrison', href: '/local-movers/nebraska/sioux', displayLabel: 'Sioux County, NE' },
    { slug: 'fall-river', name: 'Fall River', seat: 'Hot Springs', href: '/local-movers/south-dakota/fall-river', displayLabel: 'Fall River County, SD' },
  ],
  richardson: [
    { slug: 'nemaha', name: 'Nemaha', seat: 'Auburn', href: '/local-movers/nebraska/nemaha', displayLabel: 'Nemaha County, NE' },
    { slug: 'pawnee', name: 'Pawnee', seat: 'Pawnee City', href: '/local-movers/nebraska/pawnee', displayLabel: 'Pawnee County, NE' },
    { slug: 'doniphan', name: 'Doniphan', seat: 'Troy', href: '/local-movers/kansas/doniphan', displayLabel: 'Doniphan County, KS' },
  ],
  pierce: [
    { slug: 'antelope', name: 'Antelope', seat: 'Neligh', href: '/local-movers/nebraska/antelope', displayLabel: 'Antelope County, NE' },
    { slug: 'cedar', name: 'Cedar', seat: 'Hartington', href: '/local-movers/nebraska/cedar', displayLabel: 'Cedar County, NE' },
    { slug: 'knox', name: 'Knox', seat: 'Center', href: '/local-movers/nebraska/knox', displayLabel: 'Knox County, NE' },
    { slug: 'madison', name: 'Madison', seat: 'Norfolk', href: '/local-movers/nebraska/madison', displayLabel: 'Madison County, NE' },
    { slug: 'stanton', name: 'Stanton', seat: 'Stanton', href: '/local-movers/nebraska/stanton', displayLabel: 'Stanton County, NE' },
  ],
  nemaha: [
    { slug: 'johnson', name: 'Johnson', seat: 'Tecumseh', href: '/local-movers/nebraska/johnson', displayLabel: 'Johnson County, NE' },
    { slug: 'otoe', name: 'Otoe', seat: 'Nebraska City', href: '/local-movers/nebraska/otoe', displayLabel: 'Otoe County, NE' },
    { slug: 'pawnee', name: 'Pawnee', seat: 'Pawnee City', href: '/local-movers/nebraska/pawnee', displayLabel: 'Pawnee County, NE' },
    { slug: 'richardson', name: 'Richardson', seat: 'Falls City', href: '/local-movers/nebraska/richardson', displayLabel: 'Richardson County, NE' },
    { slug: 'brown', name: 'Brown', seat: 'Hiawatha', href: '/local-movers/kansas/brown', displayLabel: 'Brown County, KS' },
  ],
  jefferson: [
    { slug: 'fillmore', name: 'Fillmore', seat: 'Geneva', href: '/local-movers/nebraska/fillmore', displayLabel: 'Fillmore County, NE' },
    { slug: 'gage', name: 'Gage', seat: 'Beatrice', href: '/local-movers/nebraska/gage', displayLabel: 'Gage County, NE' },
    { slug: 'saline', name: 'Saline', seat: 'Wilber', href: '/local-movers/nebraska/saline', displayLabel: 'Saline County, NE' },
    { slug: 'thayer', name: 'Thayer', seat: 'Hebron', href: '/local-movers/nebraska/thayer', displayLabel: 'Thayer County, NE' },
    { slug: 'washington', name: 'Washington', seat: 'Washington', href: '/local-movers/kansas/washington', displayLabel: 'Washington County, KS' },
  ],
  thurston: [
    { slug: 'burt', name: 'Burt', seat: 'Tekamah', href: '/local-movers/nebraska/burt', displayLabel: 'Burt County, NE' },
    { slug: 'cuming', name: 'Cuming', seat: 'West Point', href: '/local-movers/nebraska/cuming', displayLabel: 'Cuming County, NE' },
    { slug: 'dakota', name: 'Dakota', seat: 'Dakota City', href: '/local-movers/nebraska/dakota', displayLabel: 'Dakota County, NE' },
    { slug: 'dixon', name: 'Dixon', seat: 'Ponca', href: '/local-movers/nebraska/dixon', displayLabel: 'Dixon County, NE' },
    { slug: 'woodbury', name: 'Woodbury', seat: 'Sioux City', href: '/local-movers/iowa/woodbury', displayLabel: 'Woodbury County, IA' },
  ],
  kearney: [
    { slug: 'adams', name: 'Adams', seat: 'Hastings', href: '/local-movers/nebraska/adams', displayLabel: 'Adams County, NE' },
    { slug: 'buffalo', name: 'Buffalo', seat: 'Kearney', href: '/local-movers/nebraska/buffalo', displayLabel: 'Buffalo County, NE' },
    { slug: 'franklin', name: 'Franklin', seat: 'Franklin', href: '/local-movers/nebraska/franklin', displayLabel: 'Franklin County, NE' },
    { slug: 'harlan', name: 'Harlan', seat: 'Alma', href: '/local-movers/nebraska/harlan', displayLabel: 'Harlan County, NE' },
    { slug: 'phelps', name: 'Phelps', seat: 'Holdrege', href: '/local-movers/nebraska/phelps', displayLabel: 'Phelps County, NE' },
  ],
  burt: [
    { slug: 'cuming', name: 'Cuming', seat: 'West Point', href: '/local-movers/nebraska/cuming', displayLabel: 'Cuming County, NE' },
    { slug: 'dodge', name: 'Dodge', seat: 'Fremont', href: '/local-movers/nebraska/dodge', displayLabel: 'Dodge County, NE' },
    { slug: 'thurston', name: 'Thurston', seat: 'Pender', href: '/local-movers/nebraska/thurston', displayLabel: 'Thurston County, NE' },
    { slug: 'washington', name: 'Washington', seat: 'Blair', href: '/local-movers/nebraska/washington', displayLabel: 'Washington County, NE' },
    { slug: 'burt', name: 'Burt', seat: 'Tekamah', href: '/local-movers/iowa/burt', displayLabel: 'Burt County, IA' },
  ],
  howard: [
    { slug: 'buffalo', name: 'Buffalo', seat: 'Kearney', href: '/local-movers/nebraska/buffalo', displayLabel: 'Buffalo County, NE' },
    { slug: 'greeley', name: 'Greeley', seat: 'Greeley', href: '/local-movers/nebraska/greeley', displayLabel: 'Greeley County, NE' },
    { slug: 'hall', name: 'Hall', seat: 'Grand Island', href: '/local-movers/nebraska/hall', displayLabel: 'Hall County, NE' },
    { slug: 'merrick', name: 'Merrick', seat: 'Central City', href: '/local-movers/nebraska/merrick', displayLabel: 'Merrick County, NE' },
    { slug: 'nance', name: 'Nance', seat: 'Fullerton', href: '/local-movers/nebraska/nance', displayLabel: 'Nance County, NE' },
  ],
  antelope: [
    { slug: 'boone', name: 'Boone', seat: 'Albion', href: '/local-movers/nebraska/boone', displayLabel: 'Boone County, NE' },
    { slug: 'holt', name: 'Holt', seat: "O'Neill", href: '/local-movers/nebraska/holt', displayLabel: 'Holt County, NE' },
    { slug: 'knox', name: 'Knox', seat: 'Center', href: '/local-movers/nebraska/knox', displayLabel: 'Knox County, NE' },
    { slug: 'madison', name: 'Madison', seat: 'Norfolk', href: '/local-movers/nebraska/madison', displayLabel: 'Madison County, NE' },
    { slug: 'pierce', name: 'Pierce', seat: 'Pierce', href: '/local-movers/nebraska/pierce', displayLabel: 'Pierce County, NE' },
  ],
  clay: [
    { slug: 'adams', name: 'Adams', seat: 'Hastings', href: '/local-movers/nebraska/adams', displayLabel: 'Adams County, NE' },
    { slug: 'fillmore', name: 'Fillmore', seat: 'Geneva', href: '/local-movers/nebraska/fillmore', displayLabel: 'Fillmore County, NE' },
    { slug: 'hall', name: 'Hall', seat: 'Grand Island', href: '/local-movers/nebraska/hall', displayLabel: 'Hall County, NE' },
    { slug: 'hamilton', name: 'Hamilton', seat: 'Aurora', href: '/local-movers/nebraska/hamilton', displayLabel: 'Hamilton County, NE' },
    { slug: 'nuckolls', name: 'Nuckolls', seat: 'Nelson', href: '/local-movers/nebraska/nuckolls', displayLabel: 'Nuckolls County, NE' },
  ],
  stanton: [
    { slug: 'colfax', name: 'Colfax', seat: 'Schuyler', href: '/local-movers/nebraska/colfax', displayLabel: 'Colfax County, NE' },
    { slug: 'cuming', name: 'Cuming', seat: 'West Point', href: '/local-movers/nebraska/cuming', displayLabel: 'Cuming County, NE' },
    { slug: 'madison', name: 'Madison', seat: 'Norfolk', href: '/local-movers/nebraska/madison', displayLabel: 'Madison County, NE' },
    { slug: 'pierce', name: 'Pierce', seat: 'Pierce', href: '/local-movers/nebraska/pierce', displayLabel: 'Pierce County, NE' },
    { slug: 'platte', name: 'Platte', seat: 'Columbus', href: '/local-movers/nebraska/platte', displayLabel: 'Platte County, NE' },
  ],
  dixon: [
    { slug: 'cedar', name: 'Cedar', seat: 'Hartington', href: '/local-movers/nebraska/cedar', displayLabel: 'Cedar County, NE' },
    { slug: 'dakota', name: 'Dakota', seat: 'Dakota City', href: '/local-movers/nebraska/dakota', displayLabel: 'Dakota County, NE' },
    { slug: 'thurston', name: 'Thurston', seat: 'Pender', href: '/local-movers/nebraska/thurston', displayLabel: 'Thurston County, NE' },
    { slug: 'wayne', name: 'Wayne', seat: 'Wayne', href: '/local-movers/nebraska/wayne', displayLabel: 'Wayne County, NE' },
    { slug: 'union', name: 'Union', seat: 'Elk Point', href: '/local-movers/south-dakota/union', displayLabel: 'Union County, SD' },
  ],
  cherry: [
    { slug: 'blaine', name: 'Blaine', seat: 'Brewster', href: '/local-movers/nebraska/blaine', displayLabel: 'Blaine County, NE' },
    { slug: 'brown', name: 'Brown', seat: 'Ainsworth', href: '/local-movers/nebraska/brown', displayLabel: 'Brown County, NE' },
    { slug: 'grant', name: 'Grant', seat: 'Hyannis', href: '/local-movers/nebraska/grant', displayLabel: 'Grant County, NE' },
    { slug: 'hooker', name: 'Hooker', seat: 'Mullen', href: '/local-movers/nebraska/hooker', displayLabel: 'Hooker County, NE' },
    { slug: 'keya-paha', name: 'Keya Paha', seat: 'Springview', href: '/local-movers/nebraska/keya-paha', displayLabel: 'Keya Paha County, NE' },
  ],
  fillmore: [
    { slug: 'clay', name: 'Clay', seat: 'Clay Center', href: '/local-movers/nebraska/clay', displayLabel: 'Clay County, NE' },
    { slug: 'hamilton', name: 'Hamilton', seat: 'Aurora', href: '/local-movers/nebraska/hamilton', displayLabel: 'Hamilton County, NE' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Fairbury', href: '/local-movers/nebraska/jefferson', displayLabel: 'Jefferson County, NE' },
    { slug: 'nuckolls', name: 'Nuckolls', seat: 'Nelson', href: '/local-movers/nebraska/nuckolls', displayLabel: 'Nuckolls County, NE' },
    { slug: 'saline', name: 'Saline', seat: 'Wilber', href: '/local-movers/nebraska/saline', displayLabel: 'Saline County, NE' },
  ],
  boone: [
    { slug: 'antelope', name: 'Antelope', seat: 'Neligh', href: '/local-movers/nebraska/antelope', displayLabel: 'Antelope County, NE' },
    { slug: 'greeley', name: 'Greeley', seat: 'Greeley', href: '/local-movers/nebraska/greeley', displayLabel: 'Greeley County, NE' },
    { slug: 'madison', name: 'Madison', seat: 'Norfolk', href: '/local-movers/nebraska/madison', displayLabel: 'Madison County, NE' },
    { slug: 'nance', name: 'Nance', seat: 'Fullerton', href: '/local-movers/nebraska/nance', displayLabel: 'Nance County, NE' },
    { slug: 'platte', name: 'Platte', seat: 'Columbus', href: '/local-movers/nebraska/platte', displayLabel: 'Platte County, NE' },
  ],
  polk: [
    { slug: 'butler', name: 'Butler', seat: 'David City', href: '/local-movers/nebraska/butler', displayLabel: 'Butler County, NE' },
    { slug: 'hamilton', name: 'Hamilton', seat: 'Aurora', href: '/local-movers/nebraska/hamilton', displayLabel: 'Hamilton County, NE' },
    { slug: 'merrick', name: 'Merrick', seat: 'Central City', href: '/local-movers/nebraska/merrick', displayLabel: 'Merrick County, NE' },
    { slug: 'platte', name: 'Platte', seat: 'Columbus', href: '/local-movers/nebraska/platte', displayLabel: 'Platte County, NE' },
    { slug: 'seward', name: 'Seward', seat: 'Seward', href: '/local-movers/nebraska/seward', displayLabel: 'Seward County, NE' },
  ],
  johnson: [
    { slug: 'gage', name: 'Gage', seat: 'Beatrice', href: '/local-movers/nebraska/gage', displayLabel: 'Gage County, NE' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lincoln', href: '/local-movers/nebraska/lancaster', displayLabel: 'Lancaster County, NE' },
    { slug: 'nemaha', name: 'Nemaha', seat: 'Auburn', href: '/local-movers/nebraska/nemaha', displayLabel: 'Nemaha County, NE' },
    { slug: 'otoe', name: 'Otoe', seat: 'Nebraska City', href: '/local-movers/nebraska/otoe', displayLabel: 'Otoe County, NE' },
    { slug: 'pawnee', name: 'Pawnee', seat: 'Pawnee City', href: '/local-movers/nebraska/pawnee', displayLabel: 'Pawnee County, NE' },
  ],
  thayer: [
    { slug: 'clay', name: 'Clay', seat: 'Clay Center', href: '/local-movers/nebraska/clay', displayLabel: 'Clay County, NE' },
    { slug: 'fillmore', name: 'Fillmore', seat: 'Geneva', href: '/local-movers/nebraska/fillmore', displayLabel: 'Fillmore County, NE' },
    { slug: 'nuckolls', name: 'Nuckolls', seat: 'Nelson', href: '/local-movers/nebraska/nuckolls', displayLabel: 'Nuckolls County, NE' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Oskaloosa', href: '/local-movers/kansas/jefferson', displayLabel: 'Jefferson County, KS' },
  ],
  arthur: [
    { slug: 'garden', name: 'Garden', seat: 'Oshkosh', href: '/local-movers/nebraska/garden', displayLabel: 'Garden County, NE' },
    { slug: 'grant', name: 'Grant', seat: 'Hyannis', href: '/local-movers/nebraska/grant', displayLabel: 'Grant County, NE' },
    { slug: 'hooker', name: 'Hooker', seat: 'Mullen', href: '/local-movers/nebraska/hooker', displayLabel: 'Hooker County, NE' },
    { slug: 'keith', name: 'Keith', seat: 'Ogallala', href: '/local-movers/nebraska/keith', displayLabel: 'Keith County, NE' },
    { slug: 'mcpherson', name: 'McPherson', seat: 'Tryon', href: '/local-movers/nebraska/mcpherson', displayLabel: 'McPherson County, NE' },
  ],
  banner: [
    { slug: 'cheyenne', name: 'Cheyenne', seat: 'Sidney', href: '/local-movers/nebraska/cheyenne', displayLabel: 'Cheyenne County, NE' },
    { slug: 'kimball', name: 'Kimball', seat: 'Kimball', href: '/local-movers/nebraska/kimball', displayLabel: 'Kimball County, NE' },
    { slug: 'morrill', name: 'Morrill', seat: 'Bridgeport', href: '/local-movers/nebraska/morrill', displayLabel: 'Morrill County, NE' },
    { slug: 'scotts-bluff', name: 'Scotts Bluff', seat: 'Gering', href: '/local-movers/nebraska/scotts-bluff', displayLabel: 'Scotts Bluff County, NE' },
    { slug: 'goshen', name: 'Goshen', seat: 'Torrington', href: '/local-movers/wyoming/goshen', displayLabel: 'Goshen County, WY' },
  ],
  blaine: [
    { slug: 'brown', name: 'Brown', seat: 'Ainsworth', href: '/local-movers/nebraska/brown', displayLabel: 'Brown County, NE' },
    { slug: 'cherry', name: 'Cherry', seat: 'Valentine', href: '/local-movers/nebraska/cherry', displayLabel: 'Cherry County, NE' },
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'logan', name: 'Logan', seat: 'Stapleton', href: '/local-movers/nebraska/logan', displayLabel: 'Logan County, NE' },
    { slug: 'loup', name: 'Loup', seat: 'Taylor', href: '/local-movers/nebraska/loup', displayLabel: 'Loup County, NE' },
  ],
  boyd: [
    { slug: 'holt', name: 'Holt', seat: "O'Neill", href: '/local-movers/nebraska/holt', displayLabel: 'Holt County, NE' },
    { slug: 'keya-paha', name: 'Keya Paha', seat: 'Springview', href: '/local-movers/nebraska/keya-paha', displayLabel: 'Keya Paha County, NE' },
    { slug: 'knox', name: 'Knox', seat: 'Center', href: '/local-movers/nebraska/knox', displayLabel: 'Knox County, NE' },
    { slug: 'rock', name: 'Rock', seat: 'Bassett', href: '/local-movers/nebraska/rock', displayLabel: 'Rock County, NE' },
  ],
  brown: [
    { slug: 'blaine', name: 'Blaine', seat: 'Brewster', href: '/local-movers/nebraska/blaine', displayLabel: 'Blaine County, NE' },
    { slug: 'cherry', name: 'Cherry', seat: 'Valentine', href: '/local-movers/nebraska/cherry', displayLabel: 'Cherry County, NE' },
    { slug: 'keya-paha', name: 'Keya Paha', seat: 'Springview', href: '/local-movers/nebraska/keya-paha', displayLabel: 'Keya Paha County, NE' },
    { slug: 'loup', name: 'Loup', seat: 'Taylor', href: '/local-movers/nebraska/loup', displayLabel: 'Loup County, NE' },
    { slug: 'rock', name: 'Rock', seat: 'Bassett', href: '/local-movers/nebraska/rock', displayLabel: 'Rock County, NE' },
  ],
  chase: [
    { slug: 'dundy', name: 'Dundy', seat: 'Benkelman', href: '/local-movers/nebraska/dundy', displayLabel: 'Dundy County, NE' },
    { slug: 'hayes', name: 'Hayes', seat: 'Hayes Center', href: '/local-movers/nebraska/hayes', displayLabel: 'Hayes County, NE' },
    { slug: 'perkins', name: 'Perkins', seat: 'Grant', href: '/local-movers/nebraska/perkins', displayLabel: 'Perkins County, NE' },
    { slug: 'yuma', name: 'Yuma', seat: 'Wray', href: '/local-movers/colorado/yuma', displayLabel: 'Yuma County, CO' },
  ],
  deuel: [
    { slug: 'cheyenne', name: 'Cheyenne', seat: 'Sidney', href: '/local-movers/nebraska/cheyenne', displayLabel: 'Cheyenne County, NE' },
    { slug: 'garden', name: 'Garden', seat: 'Oshkosh', href: '/local-movers/nebraska/garden', displayLabel: 'Garden County, NE' },
    { slug: 'keith', name: 'Keith', seat: 'Ogallala', href: '/local-movers/nebraska/keith', displayLabel: 'Keith County, NE' },
    { slug: 'perkins', name: 'Perkins', seat: 'Grant', href: '/local-movers/nebraska/perkins', displayLabel: 'Perkins County, NE' },
    { slug: 'logan', name: 'Logan', seat: 'Sterling', href: '/local-movers/colorado/logan', displayLabel: 'Logan County, CO' },
  ],
  dundy: [
    { slug: 'chase', name: 'Chase', seat: 'Imperial', href: '/local-movers/nebraska/chase', displayLabel: 'Chase County, NE' },
    { slug: 'hayes', name: 'Hayes', seat: 'Hayes Center', href: '/local-movers/nebraska/hayes', displayLabel: 'Hayes County, NE' },
    { slug: 'hitchcock', name: 'Hitchcock', seat: 'Trenton', href: '/local-movers/nebraska/hitchcock', displayLabel: 'Hitchcock County, NE' },
    { slug: 'cheyenne', name: 'Cheyenne', seat: 'St. Francis', href: '/local-movers/kansas/cheyenne', displayLabel: 'Cheyenne County, KS' },
  ],
  franklin: [
    { slug: 'adams', name: 'Adams', seat: 'Hastings', href: '/local-movers/nebraska/adams', displayLabel: 'Adams County, NE' },
    { slug: 'harlan', name: 'Harlan', seat: 'Alma', href: '/local-movers/nebraska/harlan', displayLabel: 'Harlan County, NE' },
    { slug: 'kearney', name: 'Kearney', seat: 'Minden', href: '/local-movers/nebraska/kearney', displayLabel: 'Kearney County, NE' },
    { slug: 'phelps', name: 'Phelps', seat: 'Holdrege', href: '/local-movers/nebraska/phelps', displayLabel: 'Phelps County, NE' },
    { slug: 'phillips', name: 'Phillips', seat: 'Phillipsburg', href: '/local-movers/kansas/phillips', displayLabel: 'Phillips County, KS' },
  ],
  frontier: [
    { slug: 'dawson', name: 'Dawson', seat: 'Lexington', href: '/local-movers/nebraska/dawson', displayLabel: 'Dawson County, NE' },
    { slug: 'furnas', name: 'Furnas', seat: 'Beaver City', href: '/local-movers/nebraska/furnas', displayLabel: 'Furnas County, NE' },
    { slug: 'gosper', name: 'Gosper', seat: 'Elwood', href: '/local-movers/nebraska/gosper', displayLabel: 'Gosper County, NE' },
    { slug: 'hayes', name: 'Hayes', seat: 'Hayes Center', href: '/local-movers/nebraska/hayes', displayLabel: 'Hayes County, NE' },
    { slug: 'hitchcock', name: 'Hitchcock', seat: 'Trenton', href: '/local-movers/nebraska/hitchcock', displayLabel: 'Hitchcock County, NE' },
  ],
  furnas: [
    { slug: 'frontier', name: 'Frontier', seat: 'Stockville', href: '/local-movers/nebraska/frontier', displayLabel: 'Frontier County, NE' },
    { slug: 'gosper', name: 'Gosper', seat: 'Elwood', href: '/local-movers/nebraska/gosper', displayLabel: 'Gosper County, NE' },
    { slug: 'harlan', name: 'Harlan', seat: 'Alma', href: '/local-movers/nebraska/harlan', displayLabel: 'Harlan County, NE' },
    { slug: 'phelps', name: 'Phelps', seat: 'Holdrege', href: '/local-movers/nebraska/phelps', displayLabel: 'Phelps County, NE' },
    { slug: 'norton', name: 'Norton', seat: 'Norton', href: '/local-movers/kansas/norton', displayLabel: 'Norton County, KS' },
  ],
  garden: [
    { slug: 'arthur', name: 'Arthur', seat: 'Arthur', href: '/local-movers/nebraska/arthur', displayLabel: 'Arthur County, NE' },
    { slug: 'cheyenne', name: 'Cheyenne', seat: 'Sidney', href: '/local-movers/nebraska/cheyenne', displayLabel: 'Cheyenne County, NE' },
    { slug: 'deuel', name: 'Deuel', seat: 'Chappell', href: '/local-movers/nebraska/deuel', displayLabel: 'Deuel County, NE' },
    { slug: 'grant', name: 'Grant', seat: 'Hyannis', href: '/local-movers/nebraska/grant', displayLabel: 'Grant County, NE' },
    { slug: 'keith', name: 'Keith', seat: 'Ogallala', href: '/local-movers/nebraska/keith', displayLabel: 'Keith County, NE' },
  ],
  garfield: [
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'greeley', name: 'Greeley', seat: 'Greeley', href: '/local-movers/nebraska/greeley', displayLabel: 'Greeley County, NE' },
    { slug: 'holt', name: 'Holt', seat: "O'Neill", href: '/local-movers/nebraska/holt', displayLabel: 'Holt County, NE' },
    { slug: 'loup', name: 'Loup', seat: 'Taylor', href: '/local-movers/nebraska/loup', displayLabel: 'Loup County, NE' },
    { slug: 'valley', name: 'Valley', seat: 'Ord', href: '/local-movers/nebraska/valley', displayLabel: 'Valley County, NE' },
  ],
  gosper: [
    { slug: 'dawson', name: 'Dawson', seat: 'Lexington', href: '/local-movers/nebraska/dawson', displayLabel: 'Dawson County, NE' },
    { slug: 'frontier', name: 'Frontier', seat: 'Stockville', href: '/local-movers/nebraska/frontier', displayLabel: 'Frontier County, NE' },
    { slug: 'furnas', name: 'Furnas', seat: 'Beaver City', href: '/local-movers/nebraska/furnas', displayLabel: 'Furnas County, NE' },
    { slug: 'phelps', name: 'Phelps', seat: 'Holdrege', href: '/local-movers/nebraska/phelps', displayLabel: 'Phelps County, NE' },
  ],
  grant: [
    { slug: 'arthur', name: 'Arthur', seat: 'Arthur', href: '/local-movers/nebraska/arthur', displayLabel: 'Arthur County, NE' },
    { slug: 'cherry', name: 'Cherry', seat: 'Valentine', href: '/local-movers/nebraska/cherry', displayLabel: 'Cherry County, NE' },
    { slug: 'garden', name: 'Garden', seat: 'Oshkosh', href: '/local-movers/nebraska/garden', displayLabel: 'Garden County, NE' },
    { slug: 'hooker', name: 'Hooker', seat: 'Mullen', href: '/local-movers/nebraska/hooker', displayLabel: 'Hooker County, NE' },
    { slug: 'sheridan', name: 'Sheridan', seat: 'Rushville', href: '/local-movers/nebraska/sheridan', displayLabel: 'Sheridan County, NE' },
  ],
  greeley: [
    { slug: 'boone', name: 'Boone', seat: 'Albion', href: '/local-movers/nebraska/boone', displayLabel: 'Boone County, NE' },
    { slug: 'garfield', name: 'Garfield', seat: 'Burwell', href: '/local-movers/nebraska/garfield', displayLabel: 'Garfield County, NE' },
    { slug: 'howard', name: 'Howard', seat: 'St. Paul', href: '/local-movers/nebraska/howard', displayLabel: 'Howard County, NE' },
    { slug: 'merrick', name: 'Merrick', seat: 'Central City', href: '/local-movers/nebraska/merrick', displayLabel: 'Merrick County, NE' },
    { slug: 'nance', name: 'Nance', seat: 'Fullerton', href: '/local-movers/nebraska/nance', displayLabel: 'Nance County, NE' },
  ],
  harlan: [
    { slug: 'franklin', name: 'Franklin', seat: 'Franklin', href: '/local-movers/nebraska/franklin', displayLabel: 'Franklin County, NE' },
    { slug: 'furnas', name: 'Furnas', seat: 'Beaver City', href: '/local-movers/nebraska/furnas', displayLabel: 'Furnas County, NE' },
    { slug: 'kearney', name: 'Kearney', seat: 'Minden', href: '/local-movers/nebraska/kearney', displayLabel: 'Kearney County, NE' },
    { slug: 'phelps', name: 'Phelps', seat: 'Holdrege', href: '/local-movers/nebraska/phelps', displayLabel: 'Phelps County, NE' },
    { slug: 'norton', name: 'Norton', seat: 'Norton', href: '/local-movers/kansas/norton', displayLabel: 'Norton County, KS' },
  ],
  hayes: [
    { slug: 'chase', name: 'Chase', seat: 'Imperial', href: '/local-movers/nebraska/chase', displayLabel: 'Chase County, NE' },
    { slug: 'dundy', name: 'Dundy', seat: 'Benkelman', href: '/local-movers/nebraska/dundy', displayLabel: 'Dundy County, NE' },
    { slug: 'frontier', name: 'Frontier', seat: 'Stockville', href: '/local-movers/nebraska/frontier', displayLabel: 'Frontier County, NE' },
    { slug: 'hitchcock', name: 'Hitchcock', seat: 'Trenton', href: '/local-movers/nebraska/hitchcock', displayLabel: 'Hitchcock County, NE' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'North Platte', href: '/local-movers/nebraska/lincoln', displayLabel: 'Lincoln County, NE' },
  ],
  hitchcock: [
    { slug: 'dundy', name: 'Dundy', seat: 'Benkelman', href: '/local-movers/nebraska/dundy', displayLabel: 'Dundy County, NE' },
    { slug: 'frontier', name: 'Frontier', seat: 'Stockville', href: '/local-movers/nebraska/frontier', displayLabel: 'Frontier County, NE' },
    { slug: 'hayes', name: 'Hayes', seat: 'Hayes Center', href: '/local-movers/nebraska/hayes', displayLabel: 'Hayes County, NE' },
    { slug: 'red-willow', name: 'Red Willow', seat: 'McCook', href: '/local-movers/nebraska/red-willow', displayLabel: 'Red Willow County, NE' },
    { slug: 'rawlins', name: 'Rawlins', seat: 'Atwood', href: '/local-movers/kansas/rawlins', displayLabel: 'Rawlins County, KS' },
  ],
  hooker: [
    { slug: 'arthur', name: 'Arthur', seat: 'Arthur', href: '/local-movers/nebraska/arthur', displayLabel: 'Arthur County, NE' },
    { slug: 'cherry', name: 'Cherry', seat: 'Valentine', href: '/local-movers/nebraska/cherry', displayLabel: 'Cherry County, NE' },
    { slug: 'grant', name: 'Grant', seat: 'Hyannis', href: '/local-movers/nebraska/grant', displayLabel: 'Grant County, NE' },
    { slug: 'mcpherson', name: 'McPherson', seat: 'Tryon', href: '/local-movers/nebraska/mcpherson', displayLabel: 'McPherson County, NE' },
    { slug: 'thomas', name: 'Thomas', seat: 'Thedford', href: '/local-movers/nebraska/thomas', displayLabel: 'Thomas County, NE' },
  ],
  'keya-paha': [
    { slug: 'boyd', name: 'Boyd', seat: 'Butte', href: '/local-movers/nebraska/boyd', displayLabel: 'Boyd County, NE' },
    { slug: 'brown', name: 'Brown', seat: 'Ainsworth', href: '/local-movers/nebraska/brown', displayLabel: 'Brown County, NE' },
    { slug: 'cherry', name: 'Cherry', seat: 'Valentine', href: '/local-movers/nebraska/cherry', displayLabel: 'Cherry County, NE' },
    { slug: 'holt', name: 'Holt', seat: "O'Neill", href: '/local-movers/nebraska/holt', displayLabel: 'Holt County, NE' },
    { slug: 'rock', name: 'Rock', seat: 'Bassett', href: '/local-movers/nebraska/rock', displayLabel: 'Rock County, NE' },
  ],
  kimball: [
    { slug: 'banner', name: 'Banner', seat: 'Harrisburg', href: '/local-movers/nebraska/banner', displayLabel: 'Banner County, NE' },
    { slug: 'cheyenne', name: 'Cheyenne', seat: 'Cheyenne Wells', href: '/local-movers/colorado/cheyenne', displayLabel: 'Cheyenne County, CO' },
    { slug: 'laramie', name: 'Laramie', seat: 'Cheyenne', href: '/local-movers/wyoming/laramie', displayLabel: 'Laramie County, WY' },
  ],
  logan: [
    { slug: 'blaine', name: 'Blaine', seat: 'Brewster', href: '/local-movers/nebraska/blaine', displayLabel: 'Blaine County, NE' },
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'North Platte', href: '/local-movers/nebraska/lincoln', displayLabel: 'Lincoln County, NE' },
    { slug: 'mcpherson', name: 'McPherson', seat: 'Tryon', href: '/local-movers/nebraska/mcpherson', displayLabel: 'McPherson County, NE' },
    { slug: 'thomas', name: 'Thomas', seat: 'Thedford', href: '/local-movers/nebraska/thomas', displayLabel: 'Thomas County, NE' },
  ],
  loup: [
    { slug: 'blaine', name: 'Blaine', seat: 'Brewster', href: '/local-movers/nebraska/blaine', displayLabel: 'Blaine County, NE' },
    { slug: 'brown', name: 'Brown', seat: 'Ainsworth', href: '/local-movers/nebraska/brown', displayLabel: 'Brown County, NE' },
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'garfield', name: 'Garfield', seat: 'Burwell', href: '/local-movers/nebraska/garfield', displayLabel: 'Garfield County, NE' },
    { slug: 'holt', name: 'Holt', seat: "O'Neill", href: '/local-movers/nebraska/holt', displayLabel: 'Holt County, NE' },
  ],
  mcpherson: [
    { slug: 'arthur', name: 'Arthur', seat: 'Arthur', href: '/local-movers/nebraska/arthur', displayLabel: 'Arthur County, NE' },
    { slug: 'hooker', name: 'Hooker', seat: 'Mullen', href: '/local-movers/nebraska/hooker', displayLabel: 'Hooker County, NE' },
    { slug: 'keith', name: 'Keith', seat: 'Ogallala', href: '/local-movers/nebraska/keith', displayLabel: 'Keith County, NE' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'North Platte', href: '/local-movers/nebraska/lincoln', displayLabel: 'Lincoln County, NE' },
    { slug: 'logan', name: 'Logan', seat: 'Stapleton', href: '/local-movers/nebraska/logan', displayLabel: 'Logan County, NE' },
  ],
  morrill: [
    { slug: 'banner', name: 'Banner', seat: 'Harrisburg', href: '/local-movers/nebraska/banner', displayLabel: 'Banner County, NE' },
    { slug: 'box-butte', name: 'Box Butte', seat: 'Alliance', href: '/local-movers/nebraska/box-butte', displayLabel: 'Box Butte County, NE' },
    { slug: 'cheyenne', name: 'Cheyenne', seat: 'Sidney', href: '/local-movers/nebraska/cheyenne', displayLabel: 'Cheyenne County, NE' },
    { slug: 'garden', name: 'Garden', seat: 'Oshkosh', href: '/local-movers/nebraska/garden', displayLabel: 'Garden County, NE' },
    { slug: 'scotts-bluff', name: 'Scotts Bluff', seat: 'Gering', href: '/local-movers/nebraska/scotts-bluff', displayLabel: 'Scotts Bluff County, NE' },
  ],
  nance: [
    { slug: 'boone', name: 'Boone', seat: 'Albion', href: '/local-movers/nebraska/boone', displayLabel: 'Boone County, NE' },
    { slug: 'greeley', name: 'Greeley', seat: 'Greeley', href: '/local-movers/nebraska/greeley', displayLabel: 'Greeley County, NE' },
    { slug: 'howard', name: 'Howard', seat: 'St. Paul', href: '/local-movers/nebraska/howard', displayLabel: 'Howard County, NE' },
    { slug: 'merrick', name: 'Merrick', seat: 'Central City', href: '/local-movers/nebraska/merrick', displayLabel: 'Merrick County, NE' },
    { slug: 'platte', name: 'Platte', seat: 'Columbus', href: '/local-movers/nebraska/platte', displayLabel: 'Platte County, NE' },
  ],
  nuckolls: [
    { slug: 'adams', name: 'Adams', seat: 'Hastings', href: '/local-movers/nebraska/adams', displayLabel: 'Adams County, NE' },
    { slug: 'clay', name: 'Clay', seat: 'Clay Center', href: '/local-movers/nebraska/clay', displayLabel: 'Clay County, NE' },
    { slug: 'fillmore', name: 'Fillmore', seat: 'Geneva', href: '/local-movers/nebraska/fillmore', displayLabel: 'Fillmore County, NE' },
    { slug: 'thayer', name: 'Thayer', seat: 'Hebron', href: '/local-movers/nebraska/thayer', displayLabel: 'Thayer County, NE' },
    { slug: 'jewell', name: 'Jewell', seat: 'Mankato', href: '/local-movers/kansas/jewell', displayLabel: 'Jewell County, KS' },
  ],
  pawnee: [
    { slug: 'gage', name: 'Gage', seat: 'Beatrice', href: '/local-movers/nebraska/gage', displayLabel: 'Gage County, NE' },
    { slug: 'johnson', name: 'Johnson', seat: 'Tecumseh', href: '/local-movers/nebraska/johnson', displayLabel: 'Johnson County, NE' },
    { slug: 'nemaha', name: 'Nemaha', seat: 'Auburn', href: '/local-movers/nebraska/nemaha', displayLabel: 'Nemaha County, NE' },
    { slug: 'richardson', name: 'Richardson', seat: 'Falls City', href: '/local-movers/nebraska/richardson', displayLabel: 'Richardson County, NE' },
    { slug: 'marshall', name: 'Marshall', seat: 'Marysville', href: '/local-movers/kansas/marshall', displayLabel: 'Marshall County, KS' },
  ],
  perkins: [
    { slug: 'chase', name: 'Chase', seat: 'Imperial', href: '/local-movers/nebraska/chase', displayLabel: 'Chase County, NE' },
    { slug: 'deuel', name: 'Deuel', seat: 'Chappell', href: '/local-movers/nebraska/deuel', displayLabel: 'Deuel County, NE' },
    { slug: 'hayes', name: 'Hayes', seat: 'Hayes Center', href: '/local-movers/nebraska/hayes', displayLabel: 'Hayes County, NE' },
    { slug: 'keith', name: 'Keith', seat: 'Ogallala', href: '/local-movers/nebraska/keith', displayLabel: 'Keith County, NE' },
    { slug: 'sedgwick', name: 'Sedgwick', seat: 'Julesburg', href: '/local-movers/colorado/sedgwick', displayLabel: 'Sedgwick County, CO' },
  ],
  rock: [
    { slug: 'boyd', name: 'Boyd', seat: 'Butte', href: '/local-movers/nebraska/boyd', displayLabel: 'Boyd County, NE' },
    { slug: 'brown', name: 'Brown', seat: 'Ainsworth', href: '/local-movers/nebraska/brown', displayLabel: 'Brown County, NE' },
    { slug: 'holt', name: 'Holt', seat: "O'Neill", href: '/local-movers/nebraska/holt', displayLabel: 'Holt County, NE' },
    { slug: 'keya-paha', name: 'Keya Paha', seat: 'Springview', href: '/local-movers/nebraska/keya-paha', displayLabel: 'Keya Paha County, NE' },
    { slug: 'loup', name: 'Loup', seat: 'Taylor', href: '/local-movers/nebraska/loup', displayLabel: 'Loup County, NE' },
  ],
  sheridan: [
    { slug: 'box-butte', name: 'Box Butte', seat: 'Alliance', href: '/local-movers/nebraska/box-butte', displayLabel: 'Box Butte County, NE' },
    { slug: 'cherry', name: 'Cherry', seat: 'Valentine', href: '/local-movers/nebraska/cherry', displayLabel: 'Cherry County, NE' },
    { slug: 'dawes', name: 'Dawes', seat: 'Chadron', href: '/local-movers/nebraska/dawes', displayLabel: 'Dawes County, NE' },
    { slug: 'garden', name: 'Garden', seat: 'Oshkosh', href: '/local-movers/nebraska/garden', displayLabel: 'Garden County, NE' },
    { slug: 'grant', name: 'Grant', seat: 'Hyannis', href: '/local-movers/nebraska/grant', displayLabel: 'Grant County, NE' },
  ],
  sherman: [
    { slug: 'buffalo', name: 'Buffalo', seat: 'Kearney', href: '/local-movers/nebraska/buffalo', displayLabel: 'Buffalo County, NE' },
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'greeley', name: 'Greeley', seat: 'Greeley', href: '/local-movers/nebraska/greeley', displayLabel: 'Greeley County, NE' },
    { slug: 'howard', name: 'Howard', seat: 'St. Paul', href: '/local-movers/nebraska/howard', displayLabel: 'Howard County, NE' },
    { slug: 'valley', name: 'Valley', seat: 'Ord', href: '/local-movers/nebraska/valley', displayLabel: 'Valley County, NE' },
  ],
  sioux: [
    { slug: 'box-butte', name: 'Box Butte', seat: 'Alliance', href: '/local-movers/nebraska/box-butte', displayLabel: 'Box Butte County, NE' },
    { slug: 'dawes', name: 'Dawes', seat: 'Chadron', href: '/local-movers/nebraska/dawes', displayLabel: 'Dawes County, NE' },
    { slug: 'scotts-bluff', name: 'Scotts Bluff', seat: 'Gering', href: '/local-movers/nebraska/scotts-bluff', displayLabel: 'Scotts Bluff County, NE' },
    { slug: 'fall-river', name: 'Fall River', seat: 'Hot Springs', href: '/local-movers/south-dakota/fall-river', displayLabel: 'Fall River County, SD' },
  ],
  thomas: [
    { slug: 'blaine', name: 'Blaine', seat: 'Brewster', href: '/local-movers/nebraska/blaine', displayLabel: 'Blaine County, NE' },
    { slug: 'cherry', name: 'Cherry', seat: 'Valentine', href: '/local-movers/nebraska/cherry', displayLabel: 'Cherry County, NE' },
    { slug: 'hooker', name: 'Hooker', seat: 'Mullen', href: '/local-movers/nebraska/hooker', displayLabel: 'Hooker County, NE' },
    { slug: 'logan', name: 'Logan', seat: 'Stapleton', href: '/local-movers/nebraska/logan', displayLabel: 'Logan County, NE' },
    { slug: 'mcpherson', name: 'McPherson', seat: 'Tryon', href: '/local-movers/nebraska/mcpherson', displayLabel: 'McPherson County, NE' },
  ],
  valley: [
    { slug: 'custer', name: 'Custer', seat: 'Broken Bow', href: '/local-movers/nebraska/custer', displayLabel: 'Custer County, NE' },
    { slug: 'garfield', name: 'Garfield', seat: 'Burwell', href: '/local-movers/nebraska/garfield', displayLabel: 'Garfield County, NE' },
    { slug: 'greeley', name: 'Greeley', seat: 'Greeley', href: '/local-movers/nebraska/greeley', displayLabel: 'Greeley County, NE' },
    { slug: 'howard', name: 'Howard', seat: 'St. Paul', href: '/local-movers/nebraska/howard', displayLabel: 'Howard County, NE' },
    { slug: 'loup', name: 'Loup', seat: 'Taylor', href: '/local-movers/nebraska/loup', displayLabel: 'Loup County, NE' },
  ],
  webster: [
    { slug: 'adams', name: 'Adams', seat: 'Hastings', href: '/local-movers/nebraska/adams', displayLabel: 'Adams County, NE' },
    { slug: 'clay', name: 'Clay', seat: 'Clay Center', href: '/local-movers/nebraska/clay', displayLabel: 'Clay County, NE' },
    { slug: 'franklin', name: 'Franklin', seat: 'Franklin', href: '/local-movers/nebraska/franklin', displayLabel: 'Franklin County, NE' },
    { slug: 'kearney', name: 'Kearney', seat: 'Minden', href: '/local-movers/nebraska/kearney', displayLabel: 'Kearney County, NE' },
    { slug: 'smith', name: 'Smith', seat: 'Smith Center', href: '/local-movers/kansas/smith', displayLabel: 'Smith County, KS' },
  ],
  wheeler: [
    { slug: 'antelope', name: 'Antelope', seat: 'Neligh', href: '/local-movers/nebraska/antelope', displayLabel: 'Antelope County, NE' },
    { slug: 'boone', name: 'Boone', seat: 'Albion', href: '/local-movers/nebraska/boone', displayLabel: 'Boone County, NE' },
    { slug: 'garfield', name: 'Garfield', seat: 'Burwell', href: '/local-movers/nebraska/garfield', displayLabel: 'Garfield County, NE' },
    { slug: 'greeley', name: 'Greeley', seat: 'Greeley', href: '/local-movers/nebraska/greeley', displayLabel: 'Greeley County, NE' },
    { slug: 'holt', name: 'Holt', seat: "O'Neill", href: '/local-movers/nebraska/holt', displayLabel: 'Holt County, NE' },
  ],
};

export function getNebraskaNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return NE_COUNTY_NEIGHBORS[countySlug] ?? [];
}
