import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** North Dakota curated county corridor links — 53/53 (cross-border MN, SD, MT) */
const ND_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  cass: [
    { slug: 'traill', name: 'Traill', seat: 'Hillsboro', href: '/local-movers/north-dakota/traill', displayLabel: 'Traill County, ND' },
    { slug: 'steele', name: 'Steele', seat: 'Finley', href: '/local-movers/north-dakota/steele', displayLabel: 'Steele County, ND' },
    { slug: 'griggs', name: 'Griggs', seat: 'Cooperstown', href: '/local-movers/north-dakota/griggs', displayLabel: 'Griggs County, ND' },
    { slug: 'clay', name: 'Clay', seat: 'Moorhead', href: '/local-movers/minnesota/clay', displayLabel: 'Clay County, MN' },
    { slug: 'otter-tail', name: 'Otter Tail', seat: 'Fergus Falls', href: '/local-movers/minnesota/otter-tail', displayLabel: 'Otter Tail County, MN' },
  ],
  burleigh: [
    { slug: 'morton', name: 'Morton', seat: 'Mandan', href: '/local-movers/north-dakota/morton', displayLabel: 'Morton County, ND' },
    { slug: 'oliver', name: 'Oliver', seat: 'Center', href: '/local-movers/north-dakota/oliver', displayLabel: 'Oliver County, ND' },
    { slug: 'mclean', name: 'McLean', seat: 'Washburn', href: '/local-movers/north-dakota/mclean', displayLabel: 'McLean County, ND' },
    { slug: 'kidder', name: 'Kidder', seat: 'Steele', href: '/local-movers/north-dakota/kidder', displayLabel: 'Kidder County, ND' },
    { slug: 'campbell', name: 'Campbell', seat: 'Mound City', href: '/local-movers/south-dakota/campbell', displayLabel: 'Campbell County, SD' },
  ],
  'grand-forks': [
    { slug: 'walsh', name: 'Walsh', seat: 'Grafton', href: '/local-movers/north-dakota/walsh', displayLabel: 'Walsh County, ND' },
    { slug: 'pembina', name: 'Pembina', seat: 'Cavalier', href: '/local-movers/north-dakota/pembina', displayLabel: 'Pembina County, ND' },
    { slug: 'steele', name: 'Steele', seat: 'Finley', href: '/local-movers/north-dakota/steele', displayLabel: 'Steele County, ND' },
    { slug: 'traill', name: 'Traill', seat: 'Hillsboro', href: '/local-movers/north-dakota/traill', displayLabel: 'Traill County, ND' },
    { slug: 'polk', name: 'Polk', seat: 'Crookston', href: '/local-movers/minnesota/polk', displayLabel: 'Polk County, MN' },
  ],
  ward: [
    { slug: 'pierce', name: 'Pierce', seat: 'Rugby', href: '/local-movers/north-dakota/pierce', displayLabel: 'Pierce County, ND' },
    { slug: 'bottineau', name: 'Bottineau', seat: 'Bottineau', href: '/local-movers/north-dakota/bottineau', displayLabel: 'Bottineau County, ND' },
    { slug: 'mclean', name: 'McLean', seat: 'Washburn', href: '/local-movers/north-dakota/mclean', displayLabel: 'McLean County, ND' },
    { slug: 'mountrail', name: 'Mountrail', seat: 'Stanley', href: '/local-movers/north-dakota/mountrail', displayLabel: 'Mountrail County, ND' },
    { slug: 'mchenry', name: 'McHenry', seat: 'Towner', href: '/local-movers/north-dakota/mchenry', displayLabel: 'McHenry County, ND' },
  ],
  williams: [
    { slug: 'mckenzie', name: 'McKenzie', seat: 'Watford City', href: '/local-movers/north-dakota/mckenzie', displayLabel: 'McKenzie County, ND' },
    { slug: 'mountrail', name: 'Mountrail', seat: 'Stanley', href: '/local-movers/north-dakota/mountrail', displayLabel: 'Mountrail County, ND' },
    { slug: 'burke', name: 'Burke', seat: 'Bowbells', href: '/local-movers/north-dakota/burke', displayLabel: 'Burke County, ND' },
    { slug: 'divide', name: 'Divide', seat: 'Crosby', href: '/local-movers/north-dakota/divide', displayLabel: 'Divide County, ND' },
    { slug: 'richland', name: 'Richland', seat: 'Sidney', href: '/local-movers/montana/richland', displayLabel: 'Richland County, MT' },
  ],
  morton: [
    { slug: 'burleigh', name: 'Burleigh', seat: 'Bismarck', href: '/local-movers/north-dakota/burleigh', displayLabel: 'Burleigh County, ND' },
    { slug: 'mercer', name: 'Mercer', seat: 'Stanton', href: '/local-movers/north-dakota/mercer', displayLabel: 'Mercer County, ND' },
    { slug: 'stark', name: 'Stark', seat: 'Dickinson', href: '/local-movers/north-dakota/stark', displayLabel: 'Stark County, ND' },
    { slug: 'oliver', name: 'Oliver', seat: 'Center', href: '/local-movers/north-dakota/oliver', displayLabel: 'Oliver County, ND' },
    { slug: 'perkins', name: 'Perkins', seat: 'Bison', href: '/local-movers/south-dakota/perkins', displayLabel: 'Perkins County, SD' },
  ],
  stark: [
    { slug: 'dunn', name: 'Dunn', seat: 'Killdeer', href: '/local-movers/north-dakota/dunn', displayLabel: 'Dunn County, ND' },
    { slug: 'morton', name: 'Morton', seat: 'Mandan', href: '/local-movers/north-dakota/morton', displayLabel: 'Morton County, ND' },
    { slug: 'grant', name: 'Grant', seat: 'Carson', href: '/local-movers/north-dakota/grant', displayLabel: 'Grant County, ND' },
    { slug: 'hettinger', name: 'Hettinger', seat: 'Hettinger', href: '/local-movers/north-dakota/hettinger', displayLabel: 'Hettinger County, ND' },
    { slug: 'harding', name: 'Harding', seat: 'Buffalo', href: '/local-movers/south-dakota/harding', displayLabel: 'Harding County, SD' },
  ],
  stutsman: [
    { slug: 'barnes', name: 'Barnes', seat: 'Valley City', href: '/local-movers/north-dakota/barnes', displayLabel: 'Barnes County, ND' },
    { slug: 'lamoure', name: 'LaMoure', seat: 'LaMoure', href: '/local-movers/north-dakota/lamoure', displayLabel: 'LaMoure County, ND' },
    { slug: 'kidder', name: 'Kidder', seat: 'Steele', href: '/local-movers/north-dakota/kidder', displayLabel: 'Kidder County, ND' },
    { slug: 'foster', name: 'Foster', seat: 'Carrington', href: '/local-movers/north-dakota/foster', displayLabel: 'Foster County, ND' },
    { slug: 'logan', name: 'Logan', seat: 'Napoleon', href: '/local-movers/north-dakota/logan', displayLabel: 'Logan County, ND' },
  ],
  richland: [
    { slug: 'cass', name: 'Cass', seat: 'Fargo', href: '/local-movers/north-dakota/cass', displayLabel: 'Cass County, ND' },
    { slug: 'ransom', name: 'Ransom', seat: 'Lisbon', href: '/local-movers/north-dakota/ransom', displayLabel: 'Ransom County, ND' },
    { slug: 'lamoure', name: 'LaMoure', seat: 'LaMoure', href: '/local-movers/north-dakota/lamoure', displayLabel: 'LaMoure County, ND' },
    { slug: 'sargent', name: 'Sargent', seat: 'Forman', href: '/local-movers/north-dakota/sargent', displayLabel: 'Sargent County, ND' },
    { slug: 'wilkin', name: 'Wilkin', seat: 'Breckenridge', href: '/local-movers/minnesota/wilkin', displayLabel: 'Wilkin County, MN' },
  ],
  mckenzie: [
    { slug: 'williams', name: 'Williams', seat: 'Williston', href: '/local-movers/north-dakota/williams', displayLabel: 'Williams County, ND' },
    { slug: 'mountrail', name: 'Mountrail', seat: 'Stanley', href: '/local-movers/north-dakota/mountrail', displayLabel: 'Mountrail County, ND' },
    { slug: 'dunn', name: 'Dunn', seat: 'Killdeer', href: '/local-movers/north-dakota/dunn', displayLabel: 'Dunn County, ND' },
    { slug: 'mclean', name: 'McLean', seat: 'Washburn', href: '/local-movers/north-dakota/mclean', displayLabel: 'McLean County, ND' },
    { slug: 'billings', name: 'Billings', seat: 'Medora', href: '/local-movers/north-dakota/billings', displayLabel: 'Billings County, ND' },
  ],
  rolette: [
    { slug: 'bottineau', name: 'Bottineau', seat: 'Bottineau', href: '/local-movers/north-dakota/bottineau', displayLabel: 'Bottineau County, ND' },
    { slug: 'pierce', name: 'Pierce', seat: 'Rugby', href: '/local-movers/north-dakota/pierce', displayLabel: 'Pierce County, ND' },
    { slug: 'benson', name: 'Benson', seat: 'Minnewaukan', href: '/local-movers/north-dakota/benson', displayLabel: 'Benson County, ND' },
    { slug: 'towner', name: 'Towner', seat: 'Cando', href: '/local-movers/north-dakota/towner', displayLabel: 'Towner County, ND' },
  ],
  ramsey: [
    { slug: 'benson', name: 'Benson', seat: 'Minnewaukan', href: '/local-movers/north-dakota/benson', displayLabel: 'Benson County, ND' },
    { slug: 'walsh', name: 'Walsh', seat: 'Grafton', href: '/local-movers/north-dakota/walsh', displayLabel: 'Walsh County, ND' },
    { slug: 'pembina', name: 'Pembina', seat: 'Cavalier', href: '/local-movers/north-dakota/pembina', displayLabel: 'Pembina County, ND' },
    { slug: 'nelson', name: 'Nelson', seat: 'Lakota', href: '/local-movers/north-dakota/nelson', displayLabel: 'Nelson County, ND' },
    { slug: 'cavalier', name: 'Cavalier', seat: 'Langdon', href: '/local-movers/north-dakota/cavalier', displayLabel: 'Cavalier County, ND' },
  ],
  barnes: [
    { slug: 'cass', name: 'Cass', seat: 'Fargo', href: '/local-movers/north-dakota/cass', displayLabel: 'Cass County, ND' },
    { slug: 'stutsman', name: 'Stutsman', seat: 'Jamestown', href: '/local-movers/north-dakota/stutsman', displayLabel: 'Stutsman County, ND' },
    { slug: 'ransom', name: 'Ransom', seat: 'Lisbon', href: '/local-movers/north-dakota/ransom', displayLabel: 'Ransom County, ND' },
    { slug: 'steele', name: 'Steele', seat: 'Finley', href: '/local-movers/north-dakota/steele', displayLabel: 'Steele County, ND' },
    { slug: 'griggs', name: 'Griggs', seat: 'Cooperstown', href: '/local-movers/north-dakota/griggs', displayLabel: 'Griggs County, ND' },
  ],
  walsh: [
    { slug: 'pembina', name: 'Pembina', seat: 'Cavalier', href: '/local-movers/north-dakota/pembina', displayLabel: 'Pembina County, ND' },
    { slug: 'grand-forks', name: 'Grand Forks', seat: 'Grand Forks', href: '/local-movers/north-dakota/grand-forks', displayLabel: 'Grand Forks County, ND' },
    { slug: 'ramsey', name: 'Ramsey', seat: 'Devils Lake', href: '/local-movers/north-dakota/ramsey', displayLabel: 'Ramsey County, ND' },
    { slug: 'nelson', name: 'Nelson', seat: 'Lakota', href: '/local-movers/north-dakota/nelson', displayLabel: 'Nelson County, ND' },
    { slug: 'marshall', name: 'Marshall', seat: 'Warren', href: '/local-movers/minnesota/marshall', displayLabel: 'Marshall County, MN' },
  ],
  mclean: [
    { slug: 'burleigh', name: 'Burleigh', seat: 'Bismarck', href: '/local-movers/north-dakota/burleigh', displayLabel: 'Burleigh County, ND' },
    { slug: 'ward', name: 'Ward', seat: 'Minot', href: '/local-movers/north-dakota/ward', displayLabel: 'Ward County, ND' },
    { slug: 'mountrail', name: 'Mountrail', seat: 'Stanley', href: '/local-movers/north-dakota/mountrail', displayLabel: 'Mountrail County, ND' },
    { slug: 'mercer', name: 'Mercer', seat: 'Stanton', href: '/local-movers/north-dakota/mercer', displayLabel: 'Mercer County, ND' },
    { slug: 'mckenzie', name: 'McKenzie', seat: 'Watford City', href: '/local-movers/north-dakota/mckenzie', displayLabel: 'McKenzie County, ND' },
  ],
  mountrail: [
    { slug: 'ward', name: 'Ward', seat: 'Minot', href: '/local-movers/north-dakota/ward', displayLabel: 'Ward County, ND' },
    { slug: 'williams', name: 'Williams', seat: 'Williston', href: '/local-movers/north-dakota/williams', displayLabel: 'Williams County, ND' },
    { slug: 'mckenzie', name: 'McKenzie', seat: 'Watford City', href: '/local-movers/north-dakota/mckenzie', displayLabel: 'McKenzie County, ND' },
    { slug: 'dunn', name: 'Dunn', seat: 'Killdeer', href: '/local-movers/north-dakota/dunn', displayLabel: 'Dunn County, ND' },
    { slug: 'mclean', name: 'McLean', seat: 'Washburn', href: '/local-movers/north-dakota/mclean', displayLabel: 'McLean County, ND' },
  ],
  mercer: [
    { slug: 'morton', name: 'Morton', seat: 'Mandan', href: '/local-movers/north-dakota/morton', displayLabel: 'Morton County, ND' },
    { slug: 'mclean', name: 'McLean', seat: 'Washburn', href: '/local-movers/north-dakota/mclean', displayLabel: 'McLean County, ND' },
    { slug: 'dunn', name: 'Dunn', seat: 'Killdeer', href: '/local-movers/north-dakota/dunn', displayLabel: 'Dunn County, ND' },
    { slug: 'stark', name: 'Stark', seat: 'Dickinson', href: '/local-movers/north-dakota/stark', displayLabel: 'Stark County, ND' },
    { slug: 'oliver', name: 'Oliver', seat: 'Center', href: '/local-movers/north-dakota/oliver', displayLabel: 'Oliver County, ND' },
  ],
  traill: [
    { slug: 'cass', name: 'Cass', seat: 'Fargo', href: '/local-movers/north-dakota/cass', displayLabel: 'Cass County, ND' },
    { slug: 'grand-forks', name: 'Grand Forks', seat: 'Grand Forks', href: '/local-movers/north-dakota/grand-forks', displayLabel: 'Grand Forks County, ND' },
    { slug: 'steele', name: 'Steele', seat: 'Finley', href: '/local-movers/north-dakota/steele', displayLabel: 'Steele County, ND' },
    { slug: 'griggs', name: 'Griggs', seat: 'Cooperstown', href: '/local-movers/north-dakota/griggs', displayLabel: 'Griggs County, ND' },
    { slug: 'norman', name: 'Norman', seat: 'Ada', href: '/local-movers/minnesota/norman', displayLabel: 'Norman County, MN' },
  ],
  pembina: [
    { slug: 'walsh', name: 'Walsh', seat: 'Grafton', href: '/local-movers/north-dakota/walsh', displayLabel: 'Walsh County, ND' },
    { slug: 'cavalier', name: 'Cavalier', seat: 'Langdon', href: '/local-movers/north-dakota/cavalier', displayLabel: 'Cavalier County, ND' },
    { slug: 'ramsey', name: 'Ramsey', seat: 'Devils Lake', href: '/local-movers/north-dakota/ramsey', displayLabel: 'Ramsey County, ND' },
    { slug: 'kittson', name: 'Kittson', seat: 'Hallock', href: '/local-movers/minnesota/kittson', displayLabel: 'Kittson County, MN' },
  ],
  bottineau: [
    { slug: 'pierce', name: 'Pierce', seat: 'Rugby', href: '/local-movers/north-dakota/pierce', displayLabel: 'Pierce County, ND' },
    { slug: 'ward', name: 'Ward', seat: 'Minot', href: '/local-movers/north-dakota/ward', displayLabel: 'Ward County, ND' },
    { slug: 'rolette', name: 'Rolette', seat: 'Rolla', href: '/local-movers/north-dakota/rolette', displayLabel: 'Rolette County, ND' },
    { slug: 'benson', name: 'Benson', seat: 'Minnewaukan', href: '/local-movers/north-dakota/benson', displayLabel: 'Benson County, ND' },
    { slug: 'mchenry', name: 'McHenry', seat: 'Towner', href: '/local-movers/north-dakota/mchenry', displayLabel: 'McHenry County, ND' },
  ],
  benson: [
    { slug: 'ramsey', name: 'Ramsey', seat: 'Devils Lake', href: '/local-movers/north-dakota/ramsey', displayLabel: 'Ramsey County, ND' },
    { slug: 'pierce', name: 'Pierce', seat: 'Rugby', href: '/local-movers/north-dakota/pierce', displayLabel: 'Pierce County, ND' },
    { slug: 'rolette', name: 'Rolette', seat: 'Rolla', href: '/local-movers/north-dakota/rolette', displayLabel: 'Rolette County, ND' },
    { slug: 'nelson', name: 'Nelson', seat: 'Lakota', href: '/local-movers/north-dakota/nelson', displayLabel: 'Nelson County, ND' },
    { slug: 'eddy', name: 'Eddy', seat: 'New Rockford', href: '/local-movers/north-dakota/eddy', displayLabel: 'Eddy County, ND' },
  ],
  ransom: [
    { slug: 'cass', name: 'Cass', seat: 'Fargo', href: '/local-movers/north-dakota/cass', displayLabel: 'Cass County, ND' },
    { slug: 'barnes', name: 'Barnes', seat: 'Valley City', href: '/local-movers/north-dakota/barnes', displayLabel: 'Barnes County, ND' },
    { slug: 'richland', name: 'Richland', seat: 'Wahpeton', href: '/local-movers/north-dakota/richland', displayLabel: 'Richland County, ND' },
    { slug: 'lamoure', name: 'LaMoure', seat: 'LaMoure', href: '/local-movers/north-dakota/lamoure', displayLabel: 'LaMoure County, ND' },
    { slug: 'sargent', name: 'Sargent', seat: 'Forman', href: '/local-movers/north-dakota/sargent', displayLabel: 'Sargent County, ND' },
  ],
  lamoure: [
    { slug: 'ransom', name: 'Ransom', seat: 'Lisbon', href: '/local-movers/north-dakota/ransom', displayLabel: 'Ransom County, ND' },
    { slug: 'richland', name: 'Richland', seat: 'Wahpeton', href: '/local-movers/north-dakota/richland', displayLabel: 'Richland County, ND' },
    { slug: 'stutsman', name: 'Stutsman', seat: 'Jamestown', href: '/local-movers/north-dakota/stutsman', displayLabel: 'Stutsman County, ND' },
    { slug: 'dickey', name: 'Dickey', seat: 'Ellendale', href: '/local-movers/north-dakota/dickey', displayLabel: 'Dickey County, ND' },
    { slug: 'logan', name: 'Logan', seat: 'Napoleon', href: '/local-movers/north-dakota/logan', displayLabel: 'Logan County, ND' },
  ],
  dunn: [
    { slug: 'stark', name: 'Stark', seat: 'Dickinson', href: '/local-movers/north-dakota/stark', displayLabel: 'Stark County, ND' },
    { slug: 'mercer', name: 'Mercer', seat: 'Stanton', href: '/local-movers/north-dakota/mercer', displayLabel: 'Mercer County, ND' },
    { slug: 'mckenzie', name: 'McKenzie', seat: 'Watford City', href: '/local-movers/north-dakota/mckenzie', displayLabel: 'McKenzie County, ND' },
    { slug: 'mountrail', name: 'Mountrail', seat: 'Stanley', href: '/local-movers/north-dakota/mountrail', displayLabel: 'Mountrail County, ND' },
    { slug: 'mclean', name: 'McLean', seat: 'Washburn', href: '/local-movers/north-dakota/mclean', displayLabel: 'McLean County, ND' },
  ],
  pierce: [
    { slug: 'rolette', name: 'Rolette', seat: 'Rolla', href: '/local-movers/north-dakota/rolette', displayLabel: 'Rolette County, ND' },
    { slug: 'benson', name: 'Benson', seat: 'Minnewaukan', href: '/local-movers/north-dakota/benson', displayLabel: 'Benson County, ND' },
    { slug: 'ward', name: 'Ward', seat: 'Minot', href: '/local-movers/north-dakota/ward', displayLabel: 'Ward County, ND' },
    { slug: 'bottineau', name: 'Bottineau', seat: 'Bottineau', href: '/local-movers/north-dakota/bottineau', displayLabel: 'Bottineau County, ND' },
    { slug: 'mchenry', name: 'McHenry', seat: 'Towner', href: '/local-movers/north-dakota/mchenry', displayLabel: 'McHenry County, ND' },
  ],
  sargent: [
    { slug: 'richland', name: 'Richland', seat: 'Wahpeton', href: '/local-movers/north-dakota/richland', displayLabel: 'Richland County, ND' },
    { slug: 'ransom', name: 'Ransom', seat: 'Lisbon', href: '/local-movers/north-dakota/ransom', displayLabel: 'Ransom County, ND' },
    { slug: 'dickey', name: 'Dickey', seat: 'Ellendale', href: '/local-movers/north-dakota/dickey', displayLabel: 'Dickey County, ND' },
    { slug: 'lamoure', name: 'LaMoure', seat: 'LaMoure', href: '/local-movers/north-dakota/lamoure', displayLabel: 'LaMoure County, ND' },
    { slug: 'wilkin', name: 'Wilkin', seat: 'Breckenridge', href: '/local-movers/minnesota/wilkin', displayLabel: 'Wilkin County, MN' },
  ],
  wells: [
    { slug: 'foster', name: 'Foster', seat: 'Carrington', href: '/local-movers/north-dakota/foster', displayLabel: 'Foster County, ND' },
    { slug: 'eddy', name: 'Eddy', seat: 'New Rockford', href: '/local-movers/north-dakota/eddy', displayLabel: 'Eddy County, ND' },
    { slug: 'sheridan', name: 'Sheridan', seat: 'McClusky', href: '/local-movers/north-dakota/sheridan', displayLabel: 'Sheridan County, ND' },
    { slug: 'benson', name: 'Benson', seat: 'Minnewaukan', href: '/local-movers/north-dakota/benson', displayLabel: 'Benson County, ND' },
    { slug: 'ramsey', name: 'Ramsey', seat: 'Devils Lake', href: '/local-movers/north-dakota/ramsey', displayLabel: 'Ramsey County, ND' },
  ],
  sioux: [
    { slug: 'morton', name: 'Morton', seat: 'Mandan', href: '/local-movers/north-dakota/morton', displayLabel: 'Morton County, ND' },
    { slug: 'emmons', name: 'Emmons', seat: 'Linton', href: '/local-movers/north-dakota/emmons', displayLabel: 'Emmons County, ND' },
    { slug: 'grant', name: 'Grant', seat: 'Carson', href: '/local-movers/north-dakota/grant', displayLabel: 'Grant County, ND' },
    { slug: 'burleigh', name: 'Burleigh', seat: 'Bismarck', href: '/local-movers/north-dakota/burleigh', displayLabel: 'Burleigh County, ND' },
    { slug: 'campbell', name: 'Campbell', seat: 'Mound City', href: '/local-movers/south-dakota/campbell', displayLabel: 'Campbell County, SD' },
  ],
  cavalier: [
    { slug: 'walsh', name: 'Walsh', seat: 'Grafton', href: '/local-movers/north-dakota/walsh', displayLabel: 'Walsh County, ND' },
    { slug: 'ramsey', name: 'Ramsey', seat: 'Devils Lake', href: '/local-movers/north-dakota/ramsey', displayLabel: 'Ramsey County, ND' },
    { slug: 'pembina', name: 'Pembina', seat: 'Cavalier', href: '/local-movers/north-dakota/pembina', displayLabel: 'Pembina County, ND' },
    { slug: 'nelson', name: 'Nelson', seat: 'Lakota', href: '/local-movers/north-dakota/nelson', displayLabel: 'Nelson County, ND' },
    { slug: 'towner', name: 'Towner', seat: 'Cando', href: '/local-movers/north-dakota/towner', displayLabel: 'Towner County, ND' },
  ],
  emmons: [
    { slug: 'morton', name: 'Morton', seat: 'Mandan', href: '/local-movers/north-dakota/morton', displayLabel: 'Morton County, ND' },
    { slug: 'burleigh', name: 'Burleigh', seat: 'Bismarck', href: '/local-movers/north-dakota/burleigh', displayLabel: 'Burleigh County, ND' },
    { slug: 'logan', name: 'Logan', seat: 'Napoleon', href: '/local-movers/north-dakota/logan', displayLabel: 'Logan County, ND' },
    { slug: 'mcintosh', name: 'McIntosh', seat: 'Ashley', href: '/local-movers/north-dakota/mcintosh', displayLabel: 'McIntosh County, ND' },
    { slug: 'hettinger', name: 'Hettinger', seat: 'Hettinger', href: '/local-movers/north-dakota/hettinger', displayLabel: 'Hettinger County, ND' },
  ],
  foster: [
    { slug: 'stutsman', name: 'Stutsman', seat: 'Jamestown', href: '/local-movers/north-dakota/stutsman', displayLabel: 'Stutsman County, ND' },
    { slug: 'wells', name: 'Wells', seat: 'Fessenden', href: '/local-movers/north-dakota/wells', displayLabel: 'Wells County, ND' },
    { slug: 'eddy', name: 'Eddy', seat: 'New Rockford', href: '/local-movers/north-dakota/eddy', displayLabel: 'Eddy County, ND' },
    { slug: 'griggs', name: 'Griggs', seat: 'Cooperstown', href: '/local-movers/north-dakota/griggs', displayLabel: 'Griggs County, ND' },
    { slug: 'kidder', name: 'Kidder', seat: 'Steele', href: '/local-movers/north-dakota/kidder', displayLabel: 'Kidder County, ND' },
  ],
  nelson: [
    { slug: 'grand-forks', name: 'Grand Forks', seat: 'Grand Forks', href: '/local-movers/north-dakota/grand-forks', displayLabel: 'Grand Forks County, ND' },
    { slug: 'walsh', name: 'Walsh', seat: 'Grafton', href: '/local-movers/north-dakota/walsh', displayLabel: 'Walsh County, ND' },
    { slug: 'ramsey', name: 'Ramsey', seat: 'Devils Lake', href: '/local-movers/north-dakota/ramsey', displayLabel: 'Ramsey County, ND' },
    { slug: 'benson', name: 'Benson', seat: 'Minnewaukan', href: '/local-movers/north-dakota/benson', displayLabel: 'Benson County, ND' },
    { slug: 'cavalier', name: 'Cavalier', seat: 'Langdon', href: '/local-movers/north-dakota/cavalier', displayLabel: 'Cavalier County, ND' },
  ],
  bowman: [
    { slug: 'slope', name: 'Slope', seat: 'Amidon', href: '/local-movers/north-dakota/slope', displayLabel: 'Slope County, ND' },
    { slug: 'adams', name: 'Adams', seat: 'Hettinger', href: '/local-movers/north-dakota/adams', displayLabel: 'Adams County, ND' },
    { slug: 'hettinger', name: 'Hettinger', seat: 'Hettinger', href: '/local-movers/north-dakota/hettinger', displayLabel: 'Hettinger County, ND' },
    { slug: 'harding', name: 'Harding', seat: 'Buffalo', href: '/local-movers/south-dakota/harding', displayLabel: 'Harding County, SD' },
    { slug: 'fallon', name: 'Fallon', seat: 'Baker', href: '/local-movers/montana/fallon', displayLabel: 'Fallon County, MT' },
  ],
  hettinger: [
    { slug: 'stark', name: 'Stark', seat: 'Dickinson', href: '/local-movers/north-dakota/stark', displayLabel: 'Stark County, ND' },
    { slug: 'adams', name: 'Adams', seat: 'Hettinger', href: '/local-movers/north-dakota/adams', displayLabel: 'Adams County, ND' },
    { slug: 'bowman', name: 'Bowman', seat: 'Bowman', href: '/local-movers/north-dakota/bowman', displayLabel: 'Bowman County, ND' },
    { slug: 'slope', name: 'Slope', seat: 'Amidon', href: '/local-movers/north-dakota/slope', displayLabel: 'Slope County, ND' },
    { slug: 'grant', name: 'Grant', seat: 'Carson', href: '/local-movers/north-dakota/grant', displayLabel: 'Grant County, ND' },
  ],
  mcintosh: [
    { slug: 'emmons', name: 'Emmons', seat: 'Linton', href: '/local-movers/north-dakota/emmons', displayLabel: 'Emmons County, ND' },
    { slug: 'logan', name: 'Logan', seat: 'Napoleon', href: '/local-movers/north-dakota/logan', displayLabel: 'Logan County, ND' },
    { slug: 'lamoure', name: 'LaMoure', seat: 'LaMoure', href: '/local-movers/north-dakota/lamoure', displayLabel: 'LaMoure County, ND' },
    { slug: 'dickey', name: 'Dickey', seat: 'Ellendale', href: '/local-movers/north-dakota/dickey', displayLabel: 'Dickey County, ND' },
    { slug: 'kidder', name: 'Kidder', seat: 'Steele', href: '/local-movers/north-dakota/kidder', displayLabel: 'Kidder County, ND' },
  ],
  kidder: [
    { slug: 'burleigh', name: 'Burleigh', seat: 'Bismarck', href: '/local-movers/north-dakota/burleigh', displayLabel: 'Burleigh County, ND' },
    { slug: 'stutsman', name: 'Stutsman', seat: 'Jamestown', href: '/local-movers/north-dakota/stutsman', displayLabel: 'Stutsman County, ND' },
    { slug: 'foster', name: 'Foster', seat: 'Carrington', href: '/local-movers/north-dakota/foster', displayLabel: 'Foster County, ND' },
    { slug: 'wells', name: 'Wells', seat: 'Fessenden', href: '/local-movers/north-dakota/wells', displayLabel: 'Wells County, ND' },
    { slug: 'mcintosh', name: 'McIntosh', seat: 'Ashley', href: '/local-movers/north-dakota/mcintosh', displayLabel: 'McIntosh County, ND' },
  ],
  renville: [
    { slug: 'ward', name: 'Ward', seat: 'Minot', href: '/local-movers/north-dakota/ward', displayLabel: 'Ward County, ND' },
    { slug: 'bottineau', name: 'Bottineau', seat: 'Bottineau', href: '/local-movers/north-dakota/bottineau', displayLabel: 'Bottineau County, ND' },
    { slug: 'mchenry', name: 'McHenry', seat: 'Towner', href: '/local-movers/north-dakota/mchenry', displayLabel: 'McHenry County, ND' },
    { slug: 'mountrail', name: 'Mountrail', seat: 'Stanley', href: '/local-movers/north-dakota/mountrail', displayLabel: 'Mountrail County, ND' },
    { slug: 'burke', name: 'Burke', seat: 'Bowbells', href: '/local-movers/north-dakota/burke', displayLabel: 'Burke County, ND' },
  ],
  adams: [
    { slug: 'hettinger', name: 'Hettinger', seat: 'Hettinger', href: '/local-movers/north-dakota/hettinger', displayLabel: 'Hettinger County, ND' },
    { slug: 'bowman', name: 'Bowman', seat: 'Bowman', href: '/local-movers/north-dakota/bowman', displayLabel: 'Bowman County, ND' },
    { slug: 'slope', name: 'Slope', seat: 'Amidon', href: '/local-movers/north-dakota/slope', displayLabel: 'Slope County, ND' },
    { slug: 'billings', name: 'Billings', seat: 'Medora', href: '/local-movers/north-dakota/billings', displayLabel: 'Billings County, ND' },
  ],
  eddy: [
    { slug: 'foster', name: 'Foster', seat: 'Carrington', href: '/local-movers/north-dakota/foster', displayLabel: 'Foster County, ND' },
    { slug: 'wells', name: 'Wells', seat: 'Fessenden', href: '/local-movers/north-dakota/wells', displayLabel: 'Wells County, ND' },
    { slug: 'sheridan', name: 'Sheridan', seat: 'McClusky', href: '/local-movers/north-dakota/sheridan', displayLabel: 'Sheridan County, ND' },
    { slug: 'stutsman', name: 'Stutsman', seat: 'Jamestown', href: '/local-movers/north-dakota/stutsman', displayLabel: 'Stutsman County, ND' },
  ],
  griggs: [
    { slug: 'barnes', name: 'Barnes', seat: 'Valley City', href: '/local-movers/north-dakota/barnes', displayLabel: 'Barnes County, ND' },
    { slug: 'steele', name: 'Steele', seat: 'Finley', href: '/local-movers/north-dakota/steele', displayLabel: 'Steele County, ND' },
    { slug: 'traill', name: 'Traill', seat: 'Hillsboro', href: '/local-movers/north-dakota/traill', displayLabel: 'Traill County, ND' },
    { slug: 'cass', name: 'Cass', seat: 'Fargo', href: '/local-movers/north-dakota/cass', displayLabel: 'Cass County, ND' },
  ],
  grant: [
    { slug: 'morton', name: 'Morton', seat: 'Mandan', href: '/local-movers/north-dakota/morton', displayLabel: 'Morton County, ND' },
    { slug: 'mercer', name: 'Mercer', seat: 'Stanton', href: '/local-movers/north-dakota/mercer', displayLabel: 'Mercer County, ND' },
    { slug: 'stark', name: 'Stark', seat: 'Dickinson', href: '/local-movers/north-dakota/stark', displayLabel: 'Stark County, ND' },
    { slug: 'hettinger', name: 'Hettinger', seat: 'Hettinger', href: '/local-movers/north-dakota/hettinger', displayLabel: 'Hettinger County, ND' },
    { slug: 'perkins', name: 'Perkins', seat: 'Bison', href: '/local-movers/south-dakota/perkins', displayLabel: 'Perkins County, SD' },
  ],
  burke: [
    { slug: 'williams', name: 'Williams', seat: 'Williston', href: '/local-movers/north-dakota/williams', displayLabel: 'Williams County, ND' },
    { slug: 'mountrail', name: 'Mountrail', seat: 'Stanley', href: '/local-movers/north-dakota/mountrail', displayLabel: 'Mountrail County, ND' },
    { slug: 'renville', name: 'Renville', seat: 'Mohall', href: '/local-movers/north-dakota/renville', displayLabel: 'Renville County, ND' },
    { slug: 'divide', name: 'Divide', seat: 'Crosby', href: '/local-movers/north-dakota/divide', displayLabel: 'Divide County, ND' },
  ],
  divide: [
    { slug: 'williams', name: 'Williams', seat: 'Williston', href: '/local-movers/north-dakota/williams', displayLabel: 'Williams County, ND' },
    { slug: 'burke', name: 'Burke', seat: 'Bowbells', href: '/local-movers/north-dakota/burke', displayLabel: 'Burke County, ND' },
    { slug: 'mckenzie', name: 'McKenzie', seat: 'Watford City', href: '/local-movers/north-dakota/mckenzie', displayLabel: 'McKenzie County, ND' },
    { slug: 'richland', name: 'Richland', seat: 'Sidney', href: '/local-movers/montana/richland', displayLabel: 'Richland County, MT' },
  ],
  towner: [
    { slug: 'rolette', name: 'Rolette', seat: 'Rolla', href: '/local-movers/north-dakota/rolette', displayLabel: 'Rolette County, ND' },
    { slug: 'benson', name: 'Benson', seat: 'Minnewaukan', href: '/local-movers/north-dakota/benson', displayLabel: 'Benson County, ND' },
    { slug: 'ramsey', name: 'Ramsey', seat: 'Devils Lake', href: '/local-movers/north-dakota/ramsey', displayLabel: 'Ramsey County, ND' },
    { slug: 'cavalier', name: 'Cavalier', seat: 'Langdon', href: '/local-movers/north-dakota/cavalier', displayLabel: 'Cavalier County, ND' },
    { slug: 'mchenry', name: 'McHenry', seat: 'Towner', href: '/local-movers/north-dakota/mchenry', displayLabel: 'McHenry County, ND' },
  ],
  oliver: [
    { slug: 'burleigh', name: 'Burleigh', seat: 'Bismarck', href: '/local-movers/north-dakota/burleigh', displayLabel: 'Burleigh County, ND' },
    { slug: 'morton', name: 'Morton', seat: 'Mandan', href: '/local-movers/north-dakota/morton', displayLabel: 'Morton County, ND' },
    { slug: 'mclean', name: 'McLean', seat: 'Washburn', href: '/local-movers/north-dakota/mclean', displayLabel: 'McLean County, ND' },
    { slug: 'mercer', name: 'Mercer', seat: 'Stanton', href: '/local-movers/north-dakota/mercer', displayLabel: 'Mercer County, ND' },
    { slug: 'grant', name: 'Grant', seat: 'Carson', href: '/local-movers/north-dakota/grant', displayLabel: 'Grant County, ND' },
  ],
  'golden-valley': [
    { slug: 'stark', name: 'Stark', seat: 'Dickinson', href: '/local-movers/north-dakota/stark', displayLabel: 'Stark County, ND' },
    { slug: 'billings', name: 'Billings', seat: 'Medora', href: '/local-movers/north-dakota/billings', displayLabel: 'Billings County, ND' },
    { slug: 'mckenzie', name: 'McKenzie', seat: 'Watford City', href: '/local-movers/north-dakota/mckenzie', displayLabel: 'McKenzie County, ND' },
    { slug: 'slope', name: 'Slope', seat: 'Amidon', href: '/local-movers/north-dakota/slope', displayLabel: 'Slope County, ND' },
  ],
  logan: [
    { slug: 'emmons', name: 'Emmons', seat: 'Linton', href: '/local-movers/north-dakota/emmons', displayLabel: 'Emmons County, ND' },
    { slug: 'mcintosh', name: 'McIntosh', seat: 'Ashley', href: '/local-movers/north-dakota/mcintosh', displayLabel: 'McIntosh County, ND' },
    { slug: 'lamoure', name: 'LaMoure', seat: 'LaMoure', href: '/local-movers/north-dakota/lamoure', displayLabel: 'LaMoure County, ND' },
    { slug: 'kidder', name: 'Kidder', seat: 'Steele', href: '/local-movers/north-dakota/kidder', displayLabel: 'Kidder County, ND' },
  ],
  steele: [
    { slug: 'cass', name: 'Cass', seat: 'Fargo', href: '/local-movers/north-dakota/cass', displayLabel: 'Cass County, ND' },
    { slug: 'grand-forks', name: 'Grand Forks', seat: 'Grand Forks', href: '/local-movers/north-dakota/grand-forks', displayLabel: 'Grand Forks County, ND' },
    { slug: 'traill', name: 'Traill', seat: 'Hillsboro', href: '/local-movers/north-dakota/traill', displayLabel: 'Traill County, ND' },
    { slug: 'griggs', name: 'Griggs', seat: 'Cooperstown', href: '/local-movers/north-dakota/griggs', displayLabel: 'Griggs County, ND' },
    { slug: 'barnes', name: 'Barnes', seat: 'Valley City', href: '/local-movers/north-dakota/barnes', displayLabel: 'Barnes County, ND' },
  ],
  sheridan: [
    { slug: 'burleigh', name: 'Burleigh', seat: 'Bismarck', href: '/local-movers/north-dakota/burleigh', displayLabel: 'Burleigh County, ND' },
    { slug: 'mclean', name: 'McLean', seat: 'Washburn', href: '/local-movers/north-dakota/mclean', displayLabel: 'McLean County, ND' },
    { slug: 'wells', name: 'Wells', seat: 'Fessenden', href: '/local-movers/north-dakota/wells', displayLabel: 'Wells County, ND' },
    { slug: 'eddy', name: 'Eddy', seat: 'New Rockford', href: '/local-movers/north-dakota/eddy', displayLabel: 'Eddy County, ND' },
    { slug: 'kidder', name: 'Kidder', seat: 'Steele', href: '/local-movers/north-dakota/kidder', displayLabel: 'Kidder County, ND' },
  ],
  billings: [
    { slug: 'stark', name: 'Stark', seat: 'Dickinson', href: '/local-movers/north-dakota/stark', displayLabel: 'Stark County, ND' },
    { slug: 'golden-valley', name: 'Golden Valley', seat: 'Beach', href: '/local-movers/north-dakota/golden-valley', displayLabel: 'Golden Valley County, ND' },
    { slug: 'mckenzie', name: 'McKenzie', seat: 'Watford City', href: '/local-movers/north-dakota/mckenzie', displayLabel: 'McKenzie County, ND' },
    { slug: 'slope', name: 'Slope', seat: 'Amidon', href: '/local-movers/north-dakota/slope', displayLabel: 'Slope County, ND' },
  ],
  slope: [
    { slug: 'bowman', name: 'Bowman', seat: 'Bowman', href: '/local-movers/north-dakota/bowman', displayLabel: 'Bowman County, ND' },
    { slug: 'adams', name: 'Adams', seat: 'Hettinger', href: '/local-movers/north-dakota/adams', displayLabel: 'Adams County, ND' },
    { slug: 'hettinger', name: 'Hettinger', seat: 'Hettinger', href: '/local-movers/north-dakota/hettinger', displayLabel: 'Hettinger County, ND' },
    { slug: 'billings', name: 'Billings', seat: 'Medora', href: '/local-movers/north-dakota/billings', displayLabel: 'Billings County, ND' },
    { slug: 'golden-valley', name: 'Golden Valley', seat: 'Beach', href: '/local-movers/north-dakota/golden-valley', displayLabel: 'Golden Valley County, ND' },
  ],
  dickey: [
    { slug: 'richland', name: 'Richland', seat: 'Wahpeton', href: '/local-movers/north-dakota/richland', displayLabel: 'Richland County, ND' },
    { slug: 'sargent', name: 'Sargent', seat: 'Forman', href: '/local-movers/north-dakota/sargent', displayLabel: 'Sargent County, ND' },
    { slug: 'lamoure', name: 'LaMoure', seat: 'LaMoure', href: '/local-movers/north-dakota/lamoure', displayLabel: 'LaMoure County, ND' },
    { slug: 'mcintosh', name: 'McIntosh', seat: 'Ashley', href: '/local-movers/north-dakota/mcintosh', displayLabel: 'McIntosh County, ND' },
  ],
  mchenry: [
    { slug: 'ward', name: 'Ward', seat: 'Minot', href: '/local-movers/north-dakota/ward', displayLabel: 'Ward County, ND' },
    { slug: 'bottineau', name: 'Bottineau', seat: 'Bottineau', href: '/local-movers/north-dakota/bottineau', displayLabel: 'Bottineau County, ND' },
    { slug: 'pierce', name: 'Pierce', seat: 'Rugby', href: '/local-movers/north-dakota/pierce', displayLabel: 'Pierce County, ND' },
    { slug: 'renville', name: 'Renville', seat: 'Mohall', href: '/local-movers/north-dakota/renville', displayLabel: 'Renville County, ND' },
    { slug: 'towner', name: 'Towner', seat: 'Cando', href: '/local-movers/north-dakota/towner', displayLabel: 'Towner County, ND' },
  ],
};

export function getNorthDakotaNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return ND_COUNTY_NEIGHBORS[countySlug] ?? [];
}
