import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** Oregon premium hubs — regional corridor links */
const OR_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  multnomah: [
    { slug: 'washington', name: 'Washington', seat: 'Hillsboro', href: '/local-movers/oregon/washington', displayLabel: 'Washington County, OR' },
    { slug: 'clackamas', name: 'Clackamas', seat: 'Oregon City', href: '/local-movers/oregon/clackamas', displayLabel: 'Clackamas County, OR' },
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
    { slug: 'yamhill', name: 'Yamhill', seat: 'McMinnville', href: '/local-movers/oregon/yamhill', displayLabel: 'Yamhill County, OR' },
    { slug: 'marion', name: 'Marion', seat: 'Salem', href: '/local-movers/oregon/marion', displayLabel: 'Marion County, OR' },
  ],
  washington: [
    { slug: 'multnomah', name: 'Multnomah', seat: 'Portland', href: '/local-movers/oregon/multnomah', displayLabel: 'Multnomah County, OR' },
    { slug: 'clackamas', name: 'Clackamas', seat: 'Oregon City', href: '/local-movers/oregon/clackamas', displayLabel: 'Clackamas County, OR' },
    { slug: 'yamhill', name: 'Yamhill', seat: 'McMinnville', href: '/local-movers/oregon/yamhill', displayLabel: 'Yamhill County, OR' },
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
    { slug: 'marion', name: 'Marion', seat: 'Salem', href: '/local-movers/oregon/marion', displayLabel: 'Marion County, OR' },
  ],
  clackamas: [
    { slug: 'multnomah', name: 'Multnomah', seat: 'Portland', href: '/local-movers/oregon/multnomah', displayLabel: 'Multnomah County, OR' },
    { slug: 'washington', name: 'Washington', seat: 'Hillsboro', href: '/local-movers/oregon/washington', displayLabel: 'Washington County, OR' },
    { slug: 'marion', name: 'Marion', seat: 'Salem', href: '/local-movers/oregon/marion', displayLabel: 'Marion County, OR' },
    { slug: 'yamhill', name: 'Yamhill', seat: 'McMinnville', href: '/local-movers/oregon/yamhill', displayLabel: 'Yamhill County, OR' },
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
  ],
  lane: [
    { slug: 'benton', name: 'Benton', seat: 'Corvallis', href: '/local-movers/oregon/benton', displayLabel: 'Benton County, OR' },
    { slug: 'linn', name: 'Linn', seat: 'Albany', href: '/local-movers/oregon/linn', displayLabel: 'Linn County, OR' },
    { slug: 'douglas', name: 'Douglas', seat: 'Roseburg', href: '/local-movers/oregon/douglas', displayLabel: 'Douglas County, OR' },
    { slug: 'marion', name: 'Marion', seat: 'Salem', href: '/local-movers/oregon/marion', displayLabel: 'Marion County, OR' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
  ],
  marion: [
    { slug: 'clackamas', name: 'Clackamas', seat: 'Oregon City', href: '/local-movers/oregon/clackamas', displayLabel: 'Clackamas County, OR' },
    { slug: 'yamhill', name: 'Yamhill', seat: 'McMinnville', href: '/local-movers/oregon/yamhill', displayLabel: 'Yamhill County, OR' },
    { slug: 'linn', name: 'Linn', seat: 'Albany', href: '/local-movers/oregon/linn', displayLabel: 'Linn County, OR' },
    { slug: 'benton', name: 'Benton', seat: 'Corvallis', href: '/local-movers/oregon/benton', displayLabel: 'Benton County, OR' },
    { slug: 'lane', name: 'Lane', seat: 'Eugene', href: '/local-movers/oregon/lane', displayLabel: 'Lane County, OR' },
  ],
  jackson: [
    { slug: 'douglas', name: 'Douglas', seat: 'Roseburg', href: '/local-movers/oregon/douglas', displayLabel: 'Douglas County, OR' },
    { slug: 'curry', name: 'Curry', seat: 'Gold Beach', href: '/local-movers/oregon/curry', displayLabel: 'Curry County, OR' },
    { slug: 'lane', name: 'Lane', seat: 'Eugene', href: '/local-movers/oregon/lane', displayLabel: 'Lane County, OR' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
  ],
  deschutes: [
    { slug: 'jefferson', name: 'Jefferson', seat: 'Madras', href: '/local-movers/oregon/jefferson', displayLabel: 'Jefferson County, OR' },
    { slug: 'lane', name: 'Lane', seat: 'Eugene', href: '/local-movers/oregon/lane', displayLabel: 'Lane County, OR' },
    { slug: 'linn', name: 'Linn', seat: 'Albany', href: '/local-movers/oregon/linn', displayLabel: 'Linn County, OR' },
    { slug: 'jackson', name: 'Jackson', seat: 'Medford', href: '/local-movers/oregon/jackson', displayLabel: 'Jackson County, OR' },
    { slug: 'harney', name: 'Harney', seat: 'Burns', href: '/local-movers/oregon/harney', displayLabel: 'Harney County, OR' },
  ],
  linn: [
    { slug: 'benton', name: 'Benton', seat: 'Corvallis', href: '/local-movers/oregon/benton', displayLabel: 'Benton County, OR' },
    { slug: 'marion', name: 'Marion', seat: 'Salem', href: '/local-movers/oregon/marion', displayLabel: 'Marion County, OR' },
    { slug: 'lane', name: 'Lane', seat: 'Eugene', href: '/local-movers/oregon/lane', displayLabel: 'Lane County, OR' },
    { slug: 'douglas', name: 'Douglas', seat: 'Roseburg', href: '/local-movers/oregon/douglas', displayLabel: 'Douglas County, OR' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
  ],
  douglas: [
    { slug: 'lane', name: 'Lane', seat: 'Eugene', href: '/local-movers/oregon/lane', displayLabel: 'Lane County, OR' },
    { slug: 'jackson', name: 'Jackson', seat: 'Medford', href: '/local-movers/oregon/jackson', displayLabel: 'Jackson County, OR' },
    { slug: 'curry', name: 'Curry', seat: 'Gold Beach', href: '/local-movers/oregon/curry', displayLabel: 'Curry County, OR' },
    { slug: 'linn', name: 'Linn', seat: 'Albany', href: '/local-movers/oregon/linn', displayLabel: 'Linn County, OR' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
  ],
  yamhill: [
    { slug: 'washington', name: 'Washington', seat: 'Hillsboro', href: '/local-movers/oregon/washington', displayLabel: 'Washington County, OR' },
    { slug: 'clackamas', name: 'Clackamas', seat: 'Oregon City', href: '/local-movers/oregon/clackamas', displayLabel: 'Clackamas County, OR' },
    { slug: 'marion', name: 'Marion', seat: 'Salem', href: '/local-movers/oregon/marion', displayLabel: 'Marion County, OR' },
    { slug: 'multnomah', name: 'Multnomah', seat: 'Portland', href: '/local-movers/oregon/multnomah', displayLabel: 'Multnomah County, OR' },
    { slug: 'benton', name: 'Benton', seat: 'Corvallis', href: '/local-movers/oregon/benton', displayLabel: 'Benton County, OR' },
  ],
  benton: [
    { slug: 'linn', name: 'Linn', seat: 'Albany', href: '/local-movers/oregon/linn', displayLabel: 'Linn County, OR' },
    { slug: 'lane', name: 'Lane', seat: 'Eugene', href: '/local-movers/oregon/lane', displayLabel: 'Lane County, OR' },
    { slug: 'marion', name: 'Marion', seat: 'Salem', href: '/local-movers/oregon/marion', displayLabel: 'Marion County, OR' },
    { slug: 'yamhill', name: 'Yamhill', seat: 'McMinnville', href: '/local-movers/oregon/yamhill', displayLabel: 'Yamhill County, OR' },
    { slug: 'douglas', name: 'Douglas', seat: 'Roseburg', href: '/local-movers/oregon/douglas', displayLabel: 'Douglas County, OR' },
  ],
  wasco: [
    { slug: 'hood-river', name: 'Hood River', seat: 'Hood River', href: '/local-movers/oregon/hood-river', displayLabel: 'Hood River County, OR' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Madras', href: '/local-movers/oregon/jefferson', displayLabel: 'Jefferson County, OR' },
    { slug: 'sherman', name: 'Sherman', seat: 'Moro', href: '/local-movers/oregon/sherman', displayLabel: 'Sherman County, OR' },
    { slug: 'gilliam', name: 'Gilliam', seat: 'Condon', href: '/local-movers/oregon/gilliam', displayLabel: 'Gilliam County, OR' },
    { slug: 'multnomah', name: 'Multnomah', seat: 'Portland', href: '/local-movers/oregon/multnomah', displayLabel: 'Multnomah County, OR' },
  ],
  union: [
    { slug: 'wallowa', name: 'Wallowa', seat: 'Enterprise', href: '/local-movers/oregon/wallowa', displayLabel: 'Wallowa County, OR' },
    { slug: 'baker', name: 'Baker', seat: 'Baker City', href: '/local-movers/oregon/baker', displayLabel: 'Baker County, OR' },
    { slug: 'grant', name: 'Grant', seat: 'Canyon City', href: '/local-movers/oregon/grant', displayLabel: 'Grant County, OR' },
    { slug: 'umatilla', name: 'Umatilla', seat: 'Pendleton', href: '/local-movers/oregon/umatilla' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
  ],
  jefferson: [
    { slug: 'wasco', name: 'Wasco', seat: 'The Dalles', href: '/local-movers/oregon/wasco', displayLabel: 'Wasco County, OR' },
    { slug: 'hood-river', name: 'Hood River', seat: 'Hood River', href: '/local-movers/oregon/hood-river', displayLabel: 'Hood River County, OR' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
    { slug: 'sherman', name: 'Sherman', seat: 'Moro', href: '/local-movers/oregon/sherman', displayLabel: 'Sherman County, OR' },
    { slug: 'marion', name: 'Marion', seat: 'Salem', href: '/local-movers/oregon/marion', displayLabel: 'Marion County, OR' },
  ],
  'hood-river': [
    { slug: 'wasco', name: 'Wasco', seat: 'The Dalles', href: '/local-movers/oregon/wasco', displayLabel: 'Wasco County, OR' },
    { slug: 'multnomah', name: 'Multnomah', seat: 'Portland', href: '/local-movers/oregon/multnomah', displayLabel: 'Multnomah County, OR' },
    { slug: 'washington', name: 'Washington', seat: 'Hillsboro', href: '/local-movers/oregon/washington', displayLabel: 'Washington County, OR' },
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Madras', href: '/local-movers/oregon/jefferson', displayLabel: 'Jefferson County, OR' },
  ],
  curry: [
    { slug: 'jackson', name: 'Jackson', seat: 'Medford', href: '/local-movers/oregon/jackson', displayLabel: 'Jackson County, OR' },
    { slug: 'douglas', name: 'Douglas', seat: 'Roseburg', href: '/local-movers/oregon/douglas', displayLabel: 'Douglas County, OR' },
    { slug: 'coos', name: 'Coos', seat: 'Coquille', href: '/local-movers/oregon/coos' },
    { slug: 'lane', name: 'Lane', seat: 'Eugene', href: '/local-movers/oregon/lane', displayLabel: 'Lane County, OR' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
  ],
  baker: [
    { slug: 'union', name: 'Union', seat: 'La Grande', href: '/local-movers/oregon/union', displayLabel: 'Union County, OR' },
    { slug: 'grant', name: 'Grant', seat: 'Canyon City', href: '/local-movers/oregon/grant', displayLabel: 'Grant County, OR' },
    { slug: 'wallowa', name: 'Wallowa', seat: 'Enterprise', href: '/local-movers/oregon/wallowa', displayLabel: 'Wallowa County, OR' },
    { slug: 'harney', name: 'Harney', seat: 'Burns', href: '/local-movers/oregon/harney', displayLabel: 'Harney County, OR' },
    { slug: 'malheur', name: 'Malheur', seat: 'Ontario', href: '/local-movers/oregon/malheur' },
  ],
  morrow: [
    { slug: 'gilliam', name: 'Gilliam', seat: 'Condon', href: '/local-movers/oregon/gilliam', displayLabel: 'Gilliam County, OR' },
    { slug: 'sherman', name: 'Sherman', seat: 'Moro', href: '/local-movers/oregon/sherman', displayLabel: 'Sherman County, OR' },
    { slug: 'wasco', name: 'Wasco', seat: 'The Dalles', href: '/local-movers/oregon/wasco', displayLabel: 'Wasco County, OR' },
    { slug: 'grant', name: 'Grant', seat: 'Canyon City', href: '/local-movers/oregon/grant', displayLabel: 'Grant County, OR' },
    { slug: 'umatilla', name: 'Umatilla', seat: 'Pendleton', href: '/local-movers/oregon/umatilla' },
  ],
  lake: [
    { slug: 'harney', name: 'Harney', seat: 'Burns', href: '/local-movers/oregon/harney', displayLabel: 'Harney County, OR' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
    { slug: 'jackson', name: 'Jackson', seat: 'Medford', href: '/local-movers/oregon/jackson', displayLabel: 'Jackson County, OR' },
    { slug: 'grant', name: 'Grant', seat: 'Canyon City', href: '/local-movers/oregon/grant', displayLabel: 'Grant County, OR' },
    { slug: 'klamath', name: 'Klamath', seat: 'Klamath Falls', href: '/local-movers/oregon/klamath' },
  ],
  wallowa: [
    { slug: 'union', name: 'Union', seat: 'La Grande', href: '/local-movers/oregon/union', displayLabel: 'Union County, OR' },
    { slug: 'baker', name: 'Baker', seat: 'Baker City', href: '/local-movers/oregon/baker', displayLabel: 'Baker County, OR' },
    { slug: 'grant', name: 'Grant', seat: 'Canyon City', href: '/local-movers/oregon/grant', displayLabel: 'Grant County, OR' },
    { slug: 'umatilla', name: 'Umatilla', seat: 'Pendleton', href: '/local-movers/oregon/umatilla' },
    { slug: 'harney', name: 'Harney', seat: 'Burns', href: '/local-movers/oregon/harney', displayLabel: 'Harney County, OR' },
  ],
  harney: [
    { slug: 'lake', name: 'Lake', seat: 'Lakeview', href: '/local-movers/oregon/lake', displayLabel: 'Lake County, OR' },
    { slug: 'grant', name: 'Grant', seat: 'Canyon City', href: '/local-movers/oregon/grant', displayLabel: 'Grant County, OR' },
    { slug: 'deschutes', name: 'Deschutes', seat: 'Bend', href: '/local-movers/oregon/deschutes', displayLabel: 'Deschutes County, OR' },
    { slug: 'baker', name: 'Baker', seat: 'Baker City', href: '/local-movers/oregon/baker', displayLabel: 'Baker County, OR' },
    { slug: 'malheur', name: 'Malheur', seat: 'Ontario', href: '/local-movers/oregon/malheur' },
  ],
  grant: [
    { slug: 'baker', name: 'Baker', seat: 'Baker City', href: '/local-movers/oregon/baker', displayLabel: 'Baker County, OR' },
    { slug: 'harney', name: 'Harney', seat: 'Burns', href: '/local-movers/oregon/harney', displayLabel: 'Harney County, OR' },
    { slug: 'wheeler', name: 'Wheeler', seat: 'Fossil', href: '/local-movers/oregon/wheeler', displayLabel: 'Wheeler County, OR' },
    { slug: 'union', name: 'Union', seat: 'La Grande', href: '/local-movers/oregon/union', displayLabel: 'Union County, OR' },
    { slug: 'morrow', name: 'Morrow', seat: 'Heppner', href: '/local-movers/oregon/morrow', displayLabel: 'Morrow County, OR' },
  ],
  sherman: [
    { slug: 'wasco', name: 'Wasco', seat: 'The Dalles', href: '/local-movers/oregon/wasco', displayLabel: 'Wasco County, OR' },
    { slug: 'gilliam', name: 'Gilliam', seat: 'Condon', href: '/local-movers/oregon/gilliam', displayLabel: 'Gilliam County, OR' },
    { slug: 'morrow', name: 'Morrow', seat: 'Heppner', href: '/local-movers/oregon/morrow', displayLabel: 'Morrow County, OR' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Madras', href: '/local-movers/oregon/jefferson', displayLabel: 'Jefferson County, OR' },
    { slug: 'hood-river', name: 'Hood River', seat: 'Hood River', href: '/local-movers/oregon/hood-river', displayLabel: 'Hood River County, OR' },
  ],
  gilliam: [
    { slug: 'sherman', name: 'Sherman', seat: 'Moro', href: '/local-movers/oregon/sherman', displayLabel: 'Sherman County, OR' },
    { slug: 'wasco', name: 'Wasco', seat: 'The Dalles', href: '/local-movers/oregon/wasco', displayLabel: 'Wasco County, OR' },
    { slug: 'morrow', name: 'Morrow', seat: 'Heppner', href: '/local-movers/oregon/morrow', displayLabel: 'Morrow County, OR' },
    { slug: 'wheeler', name: 'Wheeler', seat: 'Fossil', href: '/local-movers/oregon/wheeler', displayLabel: 'Wheeler County, OR' },
    { slug: 'grant', name: 'Grant', seat: 'Canyon City', href: '/local-movers/oregon/grant', displayLabel: 'Grant County, OR' },
  ],
  wheeler: [
    { slug: 'grant', name: 'Grant', seat: 'Canyon City', href: '/local-movers/oregon/grant', displayLabel: 'Grant County, OR' },
    { slug: 'gilliam', name: 'Gilliam', seat: 'Condon', href: '/local-movers/oregon/gilliam', displayLabel: 'Gilliam County, OR' },
    { slug: 'morrow', name: 'Morrow', seat: 'Heppner', href: '/local-movers/oregon/morrow', displayLabel: 'Morrow County, OR' },
    { slug: 'wasco', name: 'Wasco', seat: 'The Dalles', href: '/local-movers/oregon/wasco', displayLabel: 'Wasco County, OR' },
    { slug: 'sherman', name: 'Sherman', seat: 'Moro', href: '/local-movers/oregon/sherman', displayLabel: 'Sherman County, OR' },
  ],
};

export function getOregonNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return OR_COUNTY_NEIGHBORS[countySlug] ?? [];
}