import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** Pennsylvania curated counties plus cross-border NJ, DE, and MD metro guides */
const PA_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  philadelphia: [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      seat: 'Media',
      href: '/local-movers/pennsylvania/delaware',
      displayLabel: 'Delaware County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
    {
      slug: 'camden',
      name: 'Camden',
      seat: 'Camden',
      href: '/local-movers/new-jersey/camden',
      displayLabel: 'Camden County, NJ',
    },
    {
      slug: 'gloucester',
      name: 'Gloucester',
      seat: 'Woodbury',
      href: '/local-movers/new-jersey/gloucester',
      displayLabel: 'Gloucester County, NJ',
    },
    {
      slug: 'new-castle',
      name: 'New Castle',
      seat: 'Wilmington',
      href: '/local-movers/delaware/new-castle',
      displayLabel: 'New Castle County, DE',
    },
  ],
  allegheny: [
    {
      slug: 'beaver',
      name: 'Beaver',
      seat: 'Beaver',
      href: '/local-movers/pennsylvania/beaver',
      displayLabel: 'Beaver County, PA',
    },
    {
      slug: 'westmoreland',
      name: 'Westmoreland',
      seat: 'Greensburg',
      href: '/local-movers/pennsylvania/westmoreland',
      displayLabel: 'Westmoreland County, PA',
    },
    {
      slug: 'washington',
      name: 'Washington',
      seat: 'Washington',
      href: '/local-movers/pennsylvania/washington',
      displayLabel: 'Washington County, PA',
    },
    {
      slug: 'butler',
      name: 'Butler',
      seat: 'Butler',
      href: '/local-movers/pennsylvania/butler',
      displayLabel: 'Butler County, PA',
    },
    {
      slug: 'armstrong',
      name: 'Armstrong',
      seat: 'Kittanning',
      href: '/local-movers/pennsylvania/armstrong',
      displayLabel: 'Armstrong County, PA',
    },
    {
      slug: 'lawrence',
      name: 'Lawrence',
      seat: 'New Castle',
      href: '/local-movers/pennsylvania/lawrence',
      displayLabel: 'Lawrence County, PA',
    },
  ],
  montgomery: [
    {
      slug: 'philadelphia',
      name: 'Philadelphia',
      seat: 'Philadelphia',
      href: '/local-movers/pennsylvania/philadelphia',
      displayLabel: 'Philadelphia County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      seat: 'Media',
      href: '/local-movers/pennsylvania/delaware',
      displayLabel: 'Delaware County, PA',
    },
    {
      slug: 'berks',
      name: 'Berks',
      seat: 'Reading',
      href: '/local-movers/pennsylvania/berks',
      displayLabel: 'Berks County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Rockville',
      href: '/local-movers/maryland/montgomery',
      displayLabel: 'Montgomery County, MD',
    },
  ],
  bucks: [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'philadelphia',
      name: 'Philadelphia',
      seat: 'Philadelphia',
      href: '/local-movers/pennsylvania/philadelphia',
      displayLabel: 'Philadelphia County, PA',
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      seat: 'Media',
      href: '/local-movers/pennsylvania/delaware',
      displayLabel: 'Delaware County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'lehigh',
      name: 'Lehigh',
      seat: 'Allentown',
      href: '/local-movers/pennsylvania/lehigh',
      displayLabel: 'Lehigh County, PA',
    },
    {
      slug: 'mercer',
      name: 'Mercer',
      seat: 'Trenton',
      href: '/local-movers/new-jersey/mercer',
      displayLabel: 'Mercer County, NJ',
    },
  ],
  delaware: [
    {
      slug: 'philadelphia',
      name: 'Philadelphia',
      seat: 'Philadelphia',
      href: '/local-movers/pennsylvania/philadelphia',
      displayLabel: 'Philadelphia County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
    {
      slug: 'new-castle',
      name: 'New Castle',
      seat: 'Wilmington',
      href: '/local-movers/delaware/new-castle',
      displayLabel: 'New Castle County, DE',
    },
    {
      slug: 'gloucester',
      name: 'Gloucester',
      seat: 'Woodbury',
      href: '/local-movers/new-jersey/gloucester',
      displayLabel: 'Gloucester County, NJ',
    },
  ],
  lancaster: [
    {
      slug: 'york',
      name: 'York',
      seat: 'York',
      href: '/local-movers/pennsylvania/york',
      displayLabel: 'York County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'berks',
      name: 'Berks',
      seat: 'Reading',
      href: '/local-movers/pennsylvania/berks',
      displayLabel: 'Berks County, PA',
    },
    {
      slug: 'lehigh',
      name: 'Lehigh',
      seat: 'Allentown',
      href: '/local-movers/pennsylvania/lehigh',
      displayLabel: 'Lehigh County, PA',
    },
    {
      slug: 'dauphin',
      name: 'Dauphin',
      seat: 'Harrisburg',
      href: '/local-movers/pennsylvania/dauphin',
      displayLabel: 'Dauphin County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
  ],
  chester: [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      seat: 'Media',
      href: '/local-movers/pennsylvania/delaware',
      displayLabel: 'Delaware County, PA',
    },
    {
      slug: 'lancaster',
      name: 'Lancaster',
      seat: 'Lancaster',
      href: '/local-movers/pennsylvania/lancaster',
      displayLabel: 'Lancaster County, PA',
    },
    {
      slug: 'berks',
      name: 'Berks',
      seat: 'Reading',
      href: '/local-movers/pennsylvania/berks',
      displayLabel: 'Berks County, PA',
    },
    {
      slug: 'philadelphia',
      name: 'Philadelphia',
      seat: 'Philadelphia',
      href: '/local-movers/pennsylvania/philadelphia',
      displayLabel: 'Philadelphia County, PA',
    },
    {
      slug: 'new-castle',
      name: 'New Castle',
      seat: 'Wilmington',
      href: '/local-movers/delaware/new-castle',
      displayLabel: 'New Castle County, DE',
    },
  ],
  york: [
    {
      slug: 'lancaster',
      name: 'Lancaster',
      seat: 'Lancaster',
      href: '/local-movers/pennsylvania/lancaster',
      displayLabel: 'Lancaster County, PA',
    },
    {
      slug: 'adams',
      name: 'Adams',
      seat: 'Gettysburg',
      href: '/local-movers/pennsylvania/adams',
      displayLabel: 'Adams County, PA',
    },
    {
      slug: 'cumberland',
      name: 'Cumberland',
      seat: 'Carlisle',
      href: '/local-movers/pennsylvania/cumberland',
      displayLabel: 'Cumberland County, PA',
    },
    {
      slug: 'dauphin',
      name: 'Dauphin',
      seat: 'Harrisburg',
      href: '/local-movers/pennsylvania/dauphin',
      displayLabel: 'Dauphin County, PA',
    },
    {
      slug: 'carroll',
      name: 'Carroll',
      seat: 'Westminster',
      href: '/local-movers/maryland/carroll',
      displayLabel: 'Carroll County, MD',
    },
    {
      slug: 'harford',
      name: 'Harford',
      seat: 'Bel Air',
      href: '/local-movers/maryland/harford',
      displayLabel: 'Harford County, MD',
    },
  ],
  berks: [
    {
      slug: 'lancaster',
      name: 'Lancaster',
      seat: 'Lancaster',
      href: '/local-movers/pennsylvania/lancaster',
      displayLabel: 'Lancaster County, PA',
    },
    {
      slug: 'lehigh',
      name: 'Lehigh',
      seat: 'Allentown',
      href: '/local-movers/pennsylvania/lehigh',
      displayLabel: 'Lehigh County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'schuylkill',
      name: 'Schuylkill',
      seat: 'Pottsville',
      href: '/local-movers/pennsylvania/schuylkill',
      displayLabel: 'Schuylkill County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
  ],
  lehigh: [
    {
      slug: 'berks',
      name: 'Berks',
      seat: 'Reading',
      href: '/local-movers/pennsylvania/berks',
      displayLabel: 'Berks County, PA',
    },
    {
      slug: 'northampton',
      name: 'Northampton',
      seat: 'Easton',
      href: '/local-movers/pennsylvania/northampton',
      displayLabel: 'Northampton County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'lancaster',
      name: 'Lancaster',
      seat: 'Lancaster',
      href: '/local-movers/pennsylvania/lancaster',
      displayLabel: 'Lancaster County, PA',
    },
    {
      slug: 'warren',
      name: 'Warren',
      seat: 'Belvidere',
      href: '/local-movers/new-jersey/warren',
      displayLabel: 'Warren County, NJ',
    },
  ],
  westmoreland: [
    {
      slug: 'allegheny',
      name: 'Allegheny',
      seat: 'Pittsburgh',
      href: '/local-movers/pennsylvania/allegheny',
      displayLabel: 'Allegheny County, PA',
    },
    {
      slug: 'washington',
      name: 'Washington',
      seat: 'Washington',
      href: '/local-movers/pennsylvania/washington',
      displayLabel: 'Washington County, PA',
    },
    {
      slug: 'butler',
      name: 'Butler',
      seat: 'Butler',
      href: '/local-movers/pennsylvania/butler',
      displayLabel: 'Butler County, PA',
    },
    {
      slug: 'fayette',
      name: 'Fayette',
      seat: 'Uniontown',
      href: '/local-movers/pennsylvania/fayette',
      displayLabel: 'Fayette County, PA',
    },
    {
      slug: 'indiana',
      name: 'Indiana',
      seat: 'Indiana',
      href: '/local-movers/pennsylvania/indiana',
      displayLabel: 'Indiana County, PA',
    },
    {
      slug: 'armstrong',
      name: 'Armstrong',
      seat: 'Kittanning',
      href: '/local-movers/pennsylvania/armstrong',
      displayLabel: 'Armstrong County, PA',
    },
  ],
  luzerne: [
    { slug: 'lackawanna', name: 'Lackawanna', seat: 'Scranton', href: '/local-movers/pennsylvania/lackawanna', displayLabel: 'Lackawanna County, PA' },
    { slug: 'monroe', name: 'Monroe', seat: 'Stroudsburg', href: '/local-movers/pennsylvania/monroe', displayLabel: 'Monroe County, PA' },
    { slug: 'schuylkill', name: 'Schuylkill', seat: 'Pottsville', href: '/local-movers/pennsylvania/schuylkill', displayLabel: 'Schuylkill County, PA' },
    { slug: 'columbia', name: 'Columbia', seat: 'Bloomsburg', href: '/local-movers/pennsylvania/columbia', displayLabel: 'Columbia County, PA' },
    { slug: 'carbon', name: 'Carbon', seat: 'Jim Thorpe', href: '/local-movers/pennsylvania/carbon', displayLabel: 'Carbon County, PA' },
    { slug: 'wyoming', name: 'Wyoming', seat: 'Tunkhannock', href: '/local-movers/pennsylvania/wyoming', displayLabel: 'Wyoming County, PA' },
  ],
  northampton: [
    { slug: 'lehigh', name: 'Lehigh', seat: 'Allentown', href: '/local-movers/pennsylvania/lehigh', displayLabel: 'Lehigh County, PA' },
    { slug: 'berks', name: 'Berks', seat: 'Reading', href: '/local-movers/pennsylvania/berks', displayLabel: 'Berks County, PA' },
    { slug: 'bucks', name: 'Bucks', seat: 'Doylestown', href: '/local-movers/pennsylvania/bucks', displayLabel: 'Bucks County, PA' },
    { slug: 'monroe', name: 'Monroe', seat: 'Stroudsburg', href: '/local-movers/pennsylvania/monroe', displayLabel: 'Monroe County, PA' },
    { slug: 'warren', name: 'Warren', seat: 'Belvidere', href: '/local-movers/new-jersey/warren', displayLabel: 'Warren County, NJ' },
    { slug: 'hunterdon', name: 'Hunterdon', seat: 'Flemington', href: '/local-movers/new-jersey/hunterdon', displayLabel: 'Hunterdon County, NJ' },
  ],
  dauphin: [
    { slug: 'cumberland', name: 'Cumberland', seat: 'Carlisle', href: '/local-movers/pennsylvania/cumberland', displayLabel: 'Cumberland County, PA' },
    { slug: 'york', name: 'York', seat: 'York', href: '/local-movers/pennsylvania/york', displayLabel: 'York County, PA' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lancaster', href: '/local-movers/pennsylvania/lancaster', displayLabel: 'Lancaster County, PA' },
    { slug: 'lebanon', name: 'Lebanon', seat: 'Lebanon', href: '/local-movers/pennsylvania/lebanon', displayLabel: 'Lebanon County, PA' },
    { slug: 'perry', name: 'Perry', seat: 'New Bloomfield', href: '/local-movers/pennsylvania/perry', displayLabel: 'Perry County, PA' },
    { slug: 'northumberland', name: 'Northumberland', seat: 'Sunbury', href: '/local-movers/pennsylvania/northumberland', displayLabel: 'Northumberland County, PA' },
  ],
  cumberland: [
    { slug: 'dauphin', name: 'Dauphin', seat: 'Harrisburg', href: '/local-movers/pennsylvania/dauphin', displayLabel: 'Dauphin County, PA' },
    { slug: 'york', name: 'York', seat: 'York', href: '/local-movers/pennsylvania/york', displayLabel: 'York County, PA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Chambersburg', href: '/local-movers/pennsylvania/franklin', displayLabel: 'Franklin County, PA' },
    { slug: 'adams', name: 'Adams', seat: 'Gettysburg', href: '/local-movers/pennsylvania/adams', displayLabel: 'Adams County, PA' },
    { slug: 'perry', name: 'Perry', seat: 'New Bloomfield', href: '/local-movers/pennsylvania/perry', displayLabel: 'Perry County, PA' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lancaster', href: '/local-movers/pennsylvania/lancaster', displayLabel: 'Lancaster County, PA' },
  ],
  erie: [
    { slug: 'crawford', name: 'Crawford', seat: 'Meadville', href: '/local-movers/pennsylvania/crawford', displayLabel: 'Crawford County, PA' },
    { slug: 'warren', name: 'Warren', seat: 'Warren', href: '/local-movers/pennsylvania/warren', displayLabel: 'Warren County, PA' },
    { slug: 'mercer', name: 'Mercer', seat: 'Mercer', href: '/local-movers/pennsylvania/mercer', displayLabel: 'Mercer County, PA' },
    { slug: 'ashtabula', name: 'Ashtabula', seat: 'Jefferson', href: '/local-movers/ohio/ashtabula', displayLabel: 'Ashtabula County, OH' },
    { slug: 'chautauqua', name: 'Chautauqua', seat: 'Mayville', href: '/local-movers/new-york/chautauqua', displayLabel: 'Chautauqua County, NY' },
    { slug: 'allegheny', name: 'Allegheny', seat: 'Pittsburgh', href: '/local-movers/pennsylvania/allegheny', displayLabel: 'Allegheny County, PA' },
  ],
  lackawanna: [
    { slug: 'luzerne', name: 'Luzerne', seat: 'Wilkes-Barre', href: '/local-movers/pennsylvania/luzerne', displayLabel: 'Luzerne County, PA' },
    { slug: 'wayne', name: 'Wayne', seat: 'Honesdale', href: '/local-movers/pennsylvania/wayne', displayLabel: 'Wayne County, PA' },
    { slug: 'susquehanna', name: 'Susquehanna', seat: 'Montrose', href: '/local-movers/pennsylvania/susquehanna', displayLabel: 'Susquehanna County, PA' },
    { slug: 'monroe', name: 'Monroe', seat: 'Stroudsburg', href: '/local-movers/pennsylvania/monroe', displayLabel: 'Monroe County, PA' },
    { slug: 'wyoming', name: 'Wyoming', seat: 'Tunkhannock', href: '/local-movers/pennsylvania/wyoming', displayLabel: 'Wyoming County, PA' },
    { slug: 'schuylkill', name: 'Schuylkill', seat: 'Pottsville', href: '/local-movers/pennsylvania/schuylkill', displayLabel: 'Schuylkill County, PA' },
  ],
  washington: [
    { slug: 'allegheny', name: 'Allegheny', seat: 'Pittsburgh', href: '/local-movers/pennsylvania/allegheny', displayLabel: 'Allegheny County, PA' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
    { slug: 'beaver', name: 'Beaver', seat: 'Beaver', href: '/local-movers/pennsylvania/beaver', displayLabel: 'Beaver County, PA' },
    { slug: 'greene', name: 'Greene', seat: 'Waynesburg', href: '/local-movers/pennsylvania/greene', displayLabel: 'Greene County, PA' },
    { slug: 'fayette', name: 'Fayette', seat: 'Uniontown', href: '/local-movers/pennsylvania/fayette', displayLabel: 'Fayette County, PA' },
    { slug: 'butler', name: 'Butler', seat: 'Butler', href: '/local-movers/pennsylvania/butler', displayLabel: 'Butler County, PA' },
  ],
  butler: [
    { slug: 'allegheny', name: 'Allegheny', seat: 'Pittsburgh', href: '/local-movers/pennsylvania/allegheny', displayLabel: 'Allegheny County, PA' },
    { slug: 'armstrong', name: 'Armstrong', seat: 'Kittanning', href: '/local-movers/pennsylvania/armstrong', displayLabel: 'Armstrong County, PA' },
    { slug: 'lawrence', name: 'Lawrence', seat: 'New Castle', href: '/local-movers/pennsylvania/lawrence', displayLabel: 'Lawrence County, PA' },
    { slug: 'venango', name: 'Venango', seat: 'Franklin', href: '/local-movers/pennsylvania/venango', displayLabel: 'Venango County, PA' },
    { slug: 'washington', name: 'Washington', seat: 'Washington', href: '/local-movers/pennsylvania/washington', displayLabel: 'Washington County, PA' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
  ],
  monroe: [
    { slug: 'lackawanna', name: 'Lackawanna', seat: 'Scranton', href: '/local-movers/pennsylvania/lackawanna', displayLabel: 'Lackawanna County, PA' },
    { slug: 'luzerne', name: 'Luzerne', seat: 'Wilkes-Barre', href: '/local-movers/pennsylvania/luzerne', displayLabel: 'Luzerne County, PA' },
    { slug: 'pike', name: 'Pike', seat: 'Milford', href: '/local-movers/pennsylvania/pike', displayLabel: 'Pike County, PA' },
    { slug: 'wayne', name: 'Wayne', seat: 'Honesdale', href: '/local-movers/pennsylvania/wayne', displayLabel: 'Wayne County, PA' },
    { slug: 'northampton', name: 'Northampton', seat: 'Easton', href: '/local-movers/pennsylvania/northampton', displayLabel: 'Northampton County, PA' },
    { slug: 'carbon', name: 'Carbon', seat: 'Jim Thorpe', href: '/local-movers/pennsylvania/carbon', displayLabel: 'Carbon County, PA' },
  ],
  beaver: [
    { slug: 'allegheny', name: 'Allegheny', seat: 'Pittsburgh', href: '/local-movers/pennsylvania/allegheny', displayLabel: 'Allegheny County, PA' },
    { slug: 'washington', name: 'Washington', seat: 'Washington', href: '/local-movers/pennsylvania/washington', displayLabel: 'Washington County, PA' },
    { slug: 'lawrence', name: 'Lawrence', seat: 'New Castle', href: '/local-movers/pennsylvania/lawrence', displayLabel: 'Lawrence County, PA' },
    { slug: 'butler', name: 'Butler', seat: 'Butler', href: '/local-movers/pennsylvania/butler', displayLabel: 'Butler County, PA' },
    { slug: 'hancock', name: 'Hancock', seat: 'New Cumberland', href: '/local-movers/west-virginia/hancock', displayLabel: 'Hancock County, WV' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
  ],
  franklin: [
    { slug: 'adams', name: 'Adams', seat: 'Gettysburg', href: '/local-movers/pennsylvania/adams', displayLabel: 'Adams County, PA' },
    { slug: 'cumberland', name: 'Cumberland', seat: 'Carlisle', href: '/local-movers/pennsylvania/cumberland', displayLabel: 'Cumberland County, PA' },
    { slug: 'fulton', name: 'Fulton', seat: 'McConnellsburg', href: '/local-movers/pennsylvania/fulton', displayLabel: 'Fulton County, PA' },
    { slug: 'huntingdon', name: 'Huntingdon', seat: 'Huntingdon', href: '/local-movers/pennsylvania/huntingdon', displayLabel: 'Huntingdon County, PA' },
    { slug: 'washington', name: 'Washington', seat: 'Hagerstown', href: '/local-movers/maryland/washington', displayLabel: 'Washington County, MD' },
    { slug: 'york', name: 'York', seat: 'York', href: '/local-movers/pennsylvania/york', displayLabel: 'York County, PA' },
  ],
  centre: [
    { slug: 'blair', name: 'Blair', seat: 'Hollidaysburg', href: '/local-movers/pennsylvania/blair', displayLabel: 'Blair County, PA' },
    { slug: 'huntingdon', name: 'Huntingdon', seat: 'Huntingdon', href: '/local-movers/pennsylvania/huntingdon', displayLabel: 'Huntingdon County, PA' },
    { slug: 'mifflin', name: 'Mifflin', seat: 'Lewistown', href: '/local-movers/pennsylvania/mifflin', displayLabel: 'Mifflin County, PA' },
    { slug: 'union', name: 'Union', seat: 'Lewisburg', href: '/local-movers/pennsylvania/union', displayLabel: 'Union County, PA' },
    { slug: 'clearfield', name: 'Clearfield', seat: 'Clearfield', href: '/local-movers/pennsylvania/clearfield', displayLabel: 'Clearfield County, PA' },
    { slug: 'clinton', name: 'Clinton', seat: 'Lock Haven', href: '/local-movers/pennsylvania/clinton', displayLabel: 'Clinton County, PA' },
  ],
  lebanon: [
    { slug: 'dauphin', name: 'Dauphin', seat: 'Harrisburg', href: '/local-movers/pennsylvania/dauphin', displayLabel: 'Dauphin County, PA' },
    { slug: 'lancaster', name: 'Lancaster', seat: 'Lancaster', href: '/local-movers/pennsylvania/lancaster', displayLabel: 'Lancaster County, PA' },
    { slug: 'berks', name: 'Berks', seat: 'Reading', href: '/local-movers/pennsylvania/berks', displayLabel: 'Berks County, PA' },
    { slug: 'schuylkill', name: 'Schuylkill', seat: 'Pottsville', href: '/local-movers/pennsylvania/schuylkill', displayLabel: 'Schuylkill County, PA' },
    { slug: 'lehigh', name: 'Lehigh', seat: 'Allentown', href: '/local-movers/pennsylvania/lehigh', displayLabel: 'Lehigh County, PA' },
    { slug: 'york', name: 'York', seat: 'York', href: '/local-movers/pennsylvania/york', displayLabel: 'York County, PA' },
  ],
  schuylkill: [
    { slug: 'berks', name: 'Berks', seat: 'Reading', href: '/local-movers/pennsylvania/berks', displayLabel: 'Berks County, PA' },
    { slug: 'lehigh', name: 'Lehigh', seat: 'Allentown', href: '/local-movers/pennsylvania/lehigh', displayLabel: 'Lehigh County, PA' },
    { slug: 'luzerne', name: 'Luzerne', seat: 'Wilkes-Barre', href: '/local-movers/pennsylvania/luzerne', displayLabel: 'Luzerne County, PA' },
    { slug: 'columbia', name: 'Columbia', seat: 'Bloomsburg', href: '/local-movers/pennsylvania/columbia', displayLabel: 'Columbia County, PA' },
    { slug: 'lebanon', name: 'Lebanon', seat: 'Lebanon', href: '/local-movers/pennsylvania/lebanon', displayLabel: 'Lebanon County, PA' },
    { slug: 'dauphin', name: 'Dauphin', seat: 'Harrisburg', href: '/local-movers/pennsylvania/dauphin', displayLabel: 'Dauphin County, PA' },
  ],
  cambria: [
    { slug: 'somerset', name: 'Somerset', seat: 'Somerset', href: '/local-movers/pennsylvania/somerset', displayLabel: 'Somerset County, PA' },
    { slug: 'indiana', name: 'Indiana', seat: 'Indiana', href: '/local-movers/pennsylvania/indiana', displayLabel: 'Indiana County, PA' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
    { slug: 'blair', name: 'Blair', seat: 'Hollidaysburg', href: '/local-movers/pennsylvania/blair', displayLabel: 'Blair County, PA' },
    { slug: 'clearfield', name: 'Clearfield', seat: 'Clearfield', href: '/local-movers/pennsylvania/clearfield', displayLabel: 'Clearfield County, PA' },
    { slug: 'bedford', name: 'Bedford', seat: 'Bedford', href: '/local-movers/pennsylvania/bedford', displayLabel: 'Bedford County, PA' },
  ],
  fayette: [
    { slug: 'washington', name: 'Washington', seat: 'Washington', href: '/local-movers/pennsylvania/washington', displayLabel: 'Washington County, PA' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
    { slug: 'somerset', name: 'Somerset', seat: 'Somerset', href: '/local-movers/pennsylvania/somerset', displayLabel: 'Somerset County, PA' },
    { slug: 'greene', name: 'Greene', seat: 'Waynesburg', href: '/local-movers/pennsylvania/greene', displayLabel: 'Greene County, PA' },
    { slug: 'allegheny', name: 'Allegheny', seat: 'Pittsburgh', href: '/local-movers/pennsylvania/allegheny', displayLabel: 'Allegheny County, PA' },
    { slug: 'cambria', name: 'Cambria', seat: 'Ebensburg', href: '/local-movers/pennsylvania/cambria', displayLabel: 'Cambria County, PA' },
  ],
  blair: [
    { slug: 'cambria', name: 'Cambria', seat: 'Ebensburg', href: '/local-movers/pennsylvania/cambria', displayLabel: 'Cambria County, PA' },
    { slug: 'centre', name: 'Centre', seat: 'Bellefonte', href: '/local-movers/pennsylvania/centre', displayLabel: 'Centre County, PA' },
    { slug: 'huntingdon', name: 'Huntingdon', seat: 'Huntingdon', href: '/local-movers/pennsylvania/huntingdon', displayLabel: 'Huntingdon County, PA' },
    { slug: 'bedford', name: 'Bedford', seat: 'Bedford', href: '/local-movers/pennsylvania/bedford', displayLabel: 'Bedford County, PA' },
    { slug: 'clearfield', name: 'Clearfield', seat: 'Clearfield', href: '/local-movers/pennsylvania/clearfield', displayLabel: 'Clearfield County, PA' },
    { slug: 'indiana', name: 'Indiana', seat: 'Indiana', href: '/local-movers/pennsylvania/indiana', displayLabel: 'Indiana County, PA' },
  ],
  lycoming: [
    { slug: 'clinton', name: 'Clinton', seat: 'Lock Haven', href: '/local-movers/pennsylvania/clinton', displayLabel: 'Clinton County, PA' },
    { slug: 'sullivan', name: 'Sullivan', seat: 'Laporte', href: '/local-movers/pennsylvania/sullivan', displayLabel: 'Sullivan County, PA' },
    { slug: 'northumberland', name: 'Northumberland', seat: 'Sunbury', href: '/local-movers/pennsylvania/northumberland', displayLabel: 'Northumberland County, PA' },
    { slug: 'union', name: 'Union', seat: 'Lewisburg', href: '/local-movers/pennsylvania/union', displayLabel: 'Union County, PA' },
    { slug: 'centre', name: 'Centre', seat: 'Bellefonte', href: '/local-movers/pennsylvania/centre', displayLabel: 'Centre County, PA' },
    { slug: 'columbia', name: 'Columbia', seat: 'Bloomsburg', href: '/local-movers/pennsylvania/columbia', displayLabel: 'Columbia County, PA' },
  ],
  adams: [
    { slug: 'york', name: 'York', seat: 'York', href: '/local-movers/pennsylvania/york', displayLabel: 'York County, PA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Chambersburg', href: '/local-movers/pennsylvania/franklin', displayLabel: 'Franklin County, PA' },
    { slug: 'cumberland', name: 'Cumberland', seat: 'Carlisle', href: '/local-movers/pennsylvania/cumberland', displayLabel: 'Cumberland County, PA' },
    { slug: 'fulton', name: 'Fulton', seat: 'McConnellsburg', href: '/local-movers/pennsylvania/fulton', displayLabel: 'Fulton County, PA' },
    { slug: 'carroll', name: 'Carroll', seat: 'Westminster', href: '/local-movers/maryland/carroll', displayLabel: 'Carroll County, MD' },
    { slug: 'frederick', name: 'Frederick', seat: 'Frederick', href: '/local-movers/maryland/frederick', displayLabel: 'Frederick County, MD' },
  ],
  mercer: [
    { slug: 'lawrence', name: 'Lawrence', seat: 'New Castle', href: '/local-movers/pennsylvania/lawrence', displayLabel: 'Lawrence County, PA' },
    { slug: 'crawford', name: 'Crawford', seat: 'Meadville', href: '/local-movers/pennsylvania/crawford', displayLabel: 'Crawford County, PA' },
    { slug: 'venango', name: 'Venango', seat: 'Franklin', href: '/local-movers/pennsylvania/venango', displayLabel: 'Venango County, PA' },
    { slug: 'butler', name: 'Butler', seat: 'Butler', href: '/local-movers/pennsylvania/butler', displayLabel: 'Butler County, PA' },
    { slug: 'erie', name: 'Erie', seat: 'Erie', href: '/local-movers/pennsylvania/erie', displayLabel: 'Erie County, PA' },
    { slug: 'mahoning', name: 'Mahoning', seat: 'Youngstown', href: '/local-movers/ohio/mahoning', displayLabel: 'Mahoning County, OH' },
  ],
  northumberland: [
    { slug: 'dauphin', name: 'Dauphin', seat: 'Harrisburg', href: '/local-movers/pennsylvania/dauphin', displayLabel: 'Dauphin County, PA' },
    { slug: 'lycoming', name: 'Lycoming', seat: 'Williamsport', href: '/local-movers/pennsylvania/lycoming', displayLabel: 'Lycoming County, PA' },
    { slug: 'columbia', name: 'Columbia', seat: 'Bloomsburg', href: '/local-movers/pennsylvania/columbia', displayLabel: 'Columbia County, PA' },
    { slug: 'schuylkill', name: 'Schuylkill', seat: 'Pottsville', href: '/local-movers/pennsylvania/schuylkill', displayLabel: 'Schuylkill County, PA' },
    { slug: 'montour', name: 'Montour', seat: 'Danville', href: '/local-movers/pennsylvania/montour', displayLabel: 'Montour County, PA' },
    { slug: 'union', name: 'Union', seat: 'Lewisburg', href: '/local-movers/pennsylvania/union', displayLabel: 'Union County, PA' },
  ],
  lawrence: [
    { slug: 'beaver', name: 'Beaver', seat: 'Beaver', href: '/local-movers/pennsylvania/beaver', displayLabel: 'Beaver County, PA' },
    { slug: 'butler', name: 'Butler', seat: 'Butler', href: '/local-movers/pennsylvania/butler', displayLabel: 'Butler County, PA' },
    { slug: 'mercer', name: 'Mercer', seat: 'Mercer', href: '/local-movers/pennsylvania/mercer', displayLabel: 'Mercer County, PA' },
    { slug: 'allegheny', name: 'Allegheny', seat: 'Pittsburgh', href: '/local-movers/pennsylvania/allegheny', displayLabel: 'Allegheny County, PA' },
    { slug: 'crawford', name: 'Crawford', seat: 'Meadville', href: '/local-movers/pennsylvania/crawford', displayLabel: 'Crawford County, PA' },
    { slug: 'mahoning', name: 'Mahoning', seat: 'Youngstown', href: '/local-movers/ohio/mahoning', displayLabel: 'Mahoning County, OH' },
  ],
  indiana: [
    { slug: 'armstrong', name: 'Armstrong', seat: 'Kittanning', href: '/local-movers/pennsylvania/armstrong', displayLabel: 'Armstrong County, PA' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
    { slug: 'cambria', name: 'Cambria', seat: 'Ebensburg', href: '/local-movers/pennsylvania/cambria', displayLabel: 'Cambria County, PA' },
    { slug: 'blair', name: 'Blair', seat: 'Hollidaysburg', href: '/local-movers/pennsylvania/blair', displayLabel: 'Blair County, PA' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Brookville', href: '/local-movers/pennsylvania/jefferson', displayLabel: 'Jefferson County, PA' },
    { slug: 'clearfield', name: 'Clearfield', seat: 'Clearfield', href: '/local-movers/pennsylvania/clearfield', displayLabel: 'Clearfield County, PA' },
  ],
  crawford: [
    { slug: 'erie', name: 'Erie', seat: 'Erie', href: '/local-movers/pennsylvania/erie', displayLabel: 'Erie County, PA' },
    { slug: 'mercer', name: 'Mercer', seat: 'Mercer', href: '/local-movers/pennsylvania/mercer', displayLabel: 'Mercer County, PA' },
    { slug: 'venango', name: 'Venango', seat: 'Franklin', href: '/local-movers/pennsylvania/venango', displayLabel: 'Venango County, PA' },
    { slug: 'warren', name: 'Warren', seat: 'Warren', href: '/local-movers/pennsylvania/warren', displayLabel: 'Warren County, PA' },
    { slug: 'lawrence', name: 'Lawrence', seat: 'New Castle', href: '/local-movers/pennsylvania/lawrence', displayLabel: 'Lawrence County, PA' },
    { slug: 'ashtabula', name: 'Ashtabula', seat: 'Jefferson', href: '/local-movers/ohio/ashtabula', displayLabel: 'Ashtabula County, OH' },
  ],
  clearfield: [
    { slug: 'centre', name: 'Centre', seat: 'Bellefonte', href: '/local-movers/pennsylvania/centre', displayLabel: 'Centre County, PA' },
    { slug: 'cambria', name: 'Cambria', seat: 'Ebensburg', href: '/local-movers/pennsylvania/cambria', displayLabel: 'Cambria County, PA' },
    { slug: 'blair', name: 'Blair', seat: 'Hollidaysburg', href: '/local-movers/pennsylvania/blair', displayLabel: 'Blair County, PA' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Brookville', href: '/local-movers/pennsylvania/jefferson', displayLabel: 'Jefferson County, PA' },
    { slug: 'clinton', name: 'Clinton', seat: 'Lock Haven', href: '/local-movers/pennsylvania/clinton', displayLabel: 'Clinton County, PA' },
    { slug: 'indiana', name: 'Indiana', seat: 'Indiana', href: '/local-movers/pennsylvania/indiana', displayLabel: 'Indiana County, PA' },
  ],
  somerset: [
    { slug: 'cambria', name: 'Cambria', seat: 'Ebensburg', href: '/local-movers/pennsylvania/cambria', displayLabel: 'Cambria County, PA' },
    { slug: 'fayette', name: 'Fayette', seat: 'Uniontown', href: '/local-movers/pennsylvania/fayette', displayLabel: 'Fayette County, PA' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
    { slug: 'bedford', name: 'Bedford', seat: 'Bedford', href: '/local-movers/pennsylvania/bedford', displayLabel: 'Bedford County, PA' },
    { slug: 'garrett', name: 'Garrett', seat: 'Oakland', href: '/local-movers/maryland/garrett', displayLabel: 'Garrett County, MD' },
    { slug: 'allegany', name: 'Allegany', seat: 'Cumberland', href: '/local-movers/maryland/allegany', displayLabel: 'Allegany County, MD' },
  ],
  columbia: [
    { slug: 'luzerne', name: 'Luzerne', seat: 'Wilkes-Barre', href: '/local-movers/pennsylvania/luzerne', displayLabel: 'Luzerne County, PA' },
    { slug: 'northumberland', name: 'Northumberland', seat: 'Sunbury', href: '/local-movers/pennsylvania/northumberland', displayLabel: 'Northumberland County, PA' },
    { slug: 'lycoming', name: 'Lycoming', seat: 'Williamsport', href: '/local-movers/pennsylvania/lycoming', displayLabel: 'Lycoming County, PA' },
    { slug: 'montour', name: 'Montour', seat: 'Danville', href: '/local-movers/pennsylvania/montour', displayLabel: 'Montour County, PA' },
    { slug: 'schuylkill', name: 'Schuylkill', seat: 'Pottsville', href: '/local-movers/pennsylvania/schuylkill', displayLabel: 'Schuylkill County, PA' },
    { slug: 'snyder', name: 'Snyder', seat: 'Middleburg', href: '/local-movers/pennsylvania/snyder', displayLabel: 'Snyder County, PA' },
  ],
  carbon: [
    { slug: 'luzerne', name: 'Luzerne', seat: 'Wilkes-Barre', href: '/local-movers/pennsylvania/luzerne', displayLabel: 'Luzerne County, PA' },
    { slug: 'monroe', name: 'Monroe', seat: 'Stroudsburg', href: '/local-movers/pennsylvania/monroe', displayLabel: 'Monroe County, PA' },
    { slug: 'schuylkill', name: 'Schuylkill', seat: 'Pottsville', href: '/local-movers/pennsylvania/schuylkill', displayLabel: 'Schuylkill County, PA' },
    { slug: 'lehigh', name: 'Lehigh', seat: 'Allentown', href: '/local-movers/pennsylvania/lehigh', displayLabel: 'Lehigh County, PA' },
    { slug: 'northampton', name: 'Northampton', seat: 'Easton', href: '/local-movers/pennsylvania/northampton', displayLabel: 'Northampton County, PA' },
    { slug: 'bucks', name: 'Bucks', seat: 'Doylestown', href: '/local-movers/pennsylvania/bucks', displayLabel: 'Bucks County, PA' },
  ],
  armstrong: [
    { slug: 'butler', name: 'Butler', seat: 'Butler', href: '/local-movers/pennsylvania/butler', displayLabel: 'Butler County, PA' },
    { slug: 'indiana', name: 'Indiana', seat: 'Indiana', href: '/local-movers/pennsylvania/indiana', displayLabel: 'Indiana County, PA' },
    { slug: 'westmoreland', name: 'Westmoreland', seat: 'Greensburg', href: '/local-movers/pennsylvania/westmoreland', displayLabel: 'Westmoreland County, PA' },
    { slug: 'allegheny', name: 'Allegheny', seat: 'Pittsburgh', href: '/local-movers/pennsylvania/allegheny', displayLabel: 'Allegheny County, PA' },
    { slug: 'clarion', name: 'Clarion', seat: 'Clarion', href: '/local-movers/pennsylvania/clarion', displayLabel: 'Clarion County, PA' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Brookville', href: '/local-movers/pennsylvania/jefferson', displayLabel: 'Jefferson County, PA' },
  ],
  pike: [
    { slug: 'monroe', name: 'Monroe', seat: 'Stroudsburg', href: '/local-movers/pennsylvania/monroe', displayLabel: 'Monroe County, PA' },
    { slug: 'wayne', name: 'Wayne', seat: 'Honesdale', href: '/local-movers/pennsylvania/wayne', displayLabel: 'Wayne County, PA' },
    { slug: 'lackawanna', name: 'Lackawanna', seat: 'Scranton', href: '/local-movers/pennsylvania/lackawanna', displayLabel: 'Lackawanna County, PA' },
    { slug: 'sussex', name: 'Sussex', seat: 'Newton', href: '/local-movers/new-jersey/sussex', displayLabel: 'Sussex County, NJ' },
    { slug: 'orange', name: 'Orange', seat: 'Goshen', href: '/local-movers/new-york/orange', displayLabel: 'Orange County, NY' },
    { slug: 'carbon', name: 'Carbon', seat: 'Jim Thorpe', href: '/local-movers/pennsylvania/carbon', displayLabel: 'Carbon County, PA' },
  ],
};

export function getPennsylvaniaNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return PA_COUNTY_NEIGHBORS[countySlug] ?? [];
}