import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** Pennsylvania curated counties plus cross-border NJ, DE, and MD metro guides */
const PA_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  philadelphia: [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      seat: 'Media',
      href: '/local-movers/pennsylvania/delaware',
      displayLabel: 'Delaware County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
    {
      slug: 'camden',
      name: 'Camden',
      seat: 'Camden',
      href: '/local-movers/new-jersey/camden',
      displayLabel: 'Camden County, NJ',
    },
    {
      slug: 'gloucester',
      name: 'Gloucester',
      seat: 'Woodbury',
      href: '/local-movers/new-jersey/gloucester',
      displayLabel: 'Gloucester County, NJ',
    },
    {
      slug: 'new-castle',
      name: 'New Castle',
      seat: 'Wilmington',
      href: '/local-movers/delaware/new-castle',
      displayLabel: 'New Castle County, DE',
    },
  ],
  allegheny: [
    {
      slug: 'beaver',
      name: 'Beaver',
      seat: 'Beaver',
      href: '/local-movers/pennsylvania/beaver',
      displayLabel: 'Beaver County, PA',
    },
    {
      slug: 'westmoreland',
      name: 'Westmoreland',
      seat: 'Greensburg',
      href: '/local-movers/pennsylvania/westmoreland',
      displayLabel: 'Westmoreland County, PA',
    },
    {
      slug: 'washington',
      name: 'Washington',
      seat: 'Washington',
      href: '/local-movers/pennsylvania/washington',
      displayLabel: 'Washington County, PA',
    },
    {
      slug: 'butler',
      name: 'Butler',
      seat: 'Butler',
      href: '/local-movers/pennsylvania/butler',
      displayLabel: 'Butler County, PA',
    },
    {
      slug: 'armstrong',
      name: 'Armstrong',
      seat: 'Kittanning',
      href: '/local-movers/pennsylvania/armstrong',
      displayLabel: 'Armstrong County, PA',
    },
    {
      slug: 'lawrence',
      name: 'Lawrence',
      seat: 'New Castle',
      href: '/local-movers/pennsylvania/lawrence',
      displayLabel: 'Lawrence County, PA',
    },
  ],
  montgomery: [
    {
      slug: 'philadelphia',
      name: 'Philadelphia',
      seat: 'Philadelphia',
      href: '/local-movers/pennsylvania/philadelphia',
      displayLabel: 'Philadelphia County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      seat: 'Media',
      href: '/local-movers/pennsylvania/delaware',
      displayLabel: 'Delaware County, PA',
    },
    {
      slug: 'berks',
      name: 'Berks',
      seat: 'Reading',
      href: '/local-movers/pennsylvania/berks',
      displayLabel: 'Berks County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Rockville',
      href: '/local-movers/maryland/montgomery',
      displayLabel: 'Montgomery County, MD',
    },
  ],
  bucks: [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'philadelphia',
      name: 'Philadelphia',
      seat: 'Philadelphia',
      href: '/local-movers/pennsylvania/philadelphia',
      displayLabel: 'Philadelphia County, PA',
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      seat: 'Media',
      href: '/local-movers/pennsylvania/delaware',
      displayLabel: 'Delaware County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'lehigh',
      name: 'Lehigh',
      seat: 'Allentown',
      href: '/local-movers/pennsylvania/lehigh',
      displayLabel: 'Lehigh County, PA',
    },
    {
      slug: 'mercer',
      name: 'Mercer',
      seat: 'Trenton',
      href: '/local-movers/new-jersey/mercer',
      displayLabel: 'Mercer County, NJ',
    },
  ],
  delaware: [
    {
      slug: 'philadelphia',
      name: 'Philadelphia',
      seat: 'Philadelphia',
      href: '/local-movers/pennsylvania/philadelphia',
      displayLabel: 'Philadelphia County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
    {
      slug: 'new-castle',
      name: 'New Castle',
      seat: 'Wilmington',
      href: '/local-movers/delaware/new-castle',
      displayLabel: 'New Castle County, DE',
    },
    {
      slug: 'gloucester',
      name: 'Gloucester',
      seat: 'Woodbury',
      href: '/local-movers/new-jersey/gloucester',
      displayLabel: 'Gloucester County, NJ',
    },
  ],
  lancaster: [
    {
      slug: 'york',
      name: 'York',
      seat: 'York',
      href: '/local-movers/pennsylvania/york',
      displayLabel: 'York County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'berks',
      name: 'Berks',
      seat: 'Reading',
      href: '/local-movers/pennsylvania/berks',
      displayLabel: 'Berks County, PA',
    },
    {
      slug: 'lehigh',
      name: 'Lehigh',
      seat: 'Allentown',
      href: '/local-movers/pennsylvania/lehigh',
      displayLabel: 'Lehigh County, PA',
    },
    {
      slug: 'dauphin',
      name: 'Dauphin',
      seat: 'Harrisburg',
      href: '/local-movers/pennsylvania/dauphin',
      displayLabel: 'Dauphin County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
  ],
  chester: [
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      seat: 'Media',
      href: '/local-movers/pennsylvania/delaware',
      displayLabel: 'Delaware County, PA',
    },
    {
      slug: 'lancaster',
      name: 'Lancaster',
      seat: 'Lancaster',
      href: '/local-movers/pennsylvania/lancaster',
      displayLabel: 'Lancaster County, PA',
    },
    {
      slug: 'berks',
      name: 'Berks',
      seat: 'Reading',
      href: '/local-movers/pennsylvania/berks',
      displayLabel: 'Berks County, PA',
    },
    {
      slug: 'philadelphia',
      name: 'Philadelphia',
      seat: 'Philadelphia',
      href: '/local-movers/pennsylvania/philadelphia',
      displayLabel: 'Philadelphia County, PA',
    },
    {
      slug: 'new-castle',
      name: 'New Castle',
      seat: 'Wilmington',
      href: '/local-movers/delaware/new-castle',
      displayLabel: 'New Castle County, DE',
    },
  ],
  york: [
    {
      slug: 'lancaster',
      name: 'Lancaster',
      seat: 'Lancaster',
      href: '/local-movers/pennsylvania/lancaster',
      displayLabel: 'Lancaster County, PA',
    },
    {
      slug: 'adams',
      name: 'Adams',
      seat: 'Gettysburg',
      href: '/local-movers/pennsylvania/adams',
      displayLabel: 'Adams County, PA',
    },
    {
      slug: 'cumberland',
      name: 'Cumberland',
      seat: 'Carlisle',
      href: '/local-movers/pennsylvania/cumberland',
      displayLabel: 'Cumberland County, PA',
    },
    {
      slug: 'dauphin',
      name: 'Dauphin',
      seat: 'Harrisburg',
      href: '/local-movers/pennsylvania/dauphin',
      displayLabel: 'Dauphin County, PA',
    },
    {
      slug: 'carroll',
      name: 'Carroll',
      seat: 'Westminster',
      href: '/local-movers/maryland/carroll',
      displayLabel: 'Carroll County, MD',
    },
    {
      slug: 'harford',
      name: 'Harford',
      seat: 'Bel Air',
      href: '/local-movers/maryland/harford',
      displayLabel: 'Harford County, MD',
    },
  ],
  berks: [
    {
      slug: 'lancaster',
      name: 'Lancaster',
      seat: 'Lancaster',
      href: '/local-movers/pennsylvania/lancaster',
      displayLabel: 'Lancaster County, PA',
    },
    {
      slug: 'lehigh',
      name: 'Lehigh',
      seat: 'Allentown',
      href: '/local-movers/pennsylvania/lehigh',
      displayLabel: 'Lehigh County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'chester',
      name: 'Chester',
      seat: 'West Chester',
      href: '/local-movers/pennsylvania/chester',
      displayLabel: 'Chester County, PA',
    },
    {
      slug: 'schuylkill',
      name: 'Schuylkill',
      seat: 'Pottsville',
      href: '/local-movers/pennsylvania/schuylkill',
      displayLabel: 'Schuylkill County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
  ],
  lehigh: [
    {
      slug: 'berks',
      name: 'Berks',
      seat: 'Reading',
      href: '/local-movers/pennsylvania/berks',
      displayLabel: 'Berks County, PA',
    },
    {
      slug: 'northampton',
      name: 'Northampton',
      seat: 'Easton',
      href: '/local-movers/pennsylvania/northampton',
      displayLabel: 'Northampton County, PA',
    },
    {
      slug: 'bucks',
      name: 'Bucks',
      seat: 'Doylestown',
      href: '/local-movers/pennsylvania/bucks',
      displayLabel: 'Bucks County, PA',
    },
    {
      slug: 'montgomery',
      name: 'Montgomery',
      seat: 'Norristown',
      href: '/local-movers/pennsylvania/montgomery',
      displayLabel: 'Montgomery County, PA',
    },
    {
      slug: 'lancaster',
      name: 'Lancaster',
      seat: 'Lancaster',
      href: '/local-movers/pennsylvania/lancaster',
      displayLabel: 'Lancaster County, PA',
    },
    {
      slug: 'warren',
      name: 'Warren',
      seat: 'Belvidere',
      href: '/local-movers/new-jersey/warren',
      displayLabel: 'Warren County, NJ',
    },
  ],
  westmoreland: [
    {
      slug: 'allegheny',
      name: 'Allegheny',
      seat: 'Pittsburgh',
      href: '/local-movers/pennsylvania/allegheny',
      displayLabel: 'Allegheny County, PA',
    },
    {
      slug: 'washington',
      name: 'Washington',
      seat: 'Washington',
      href: '/local-movers/pennsylvania/washington',
      displayLabel: 'Washington County, PA',
    },
    {
      slug: 'butler',
      name: 'Butler',
      seat: 'Butler',
      href: '/local-movers/pennsylvania/butler',
      displayLabel: 'Butler County, PA',
    },
    {
      slug: 'fayette',
      name: 'Fayette',
      seat: 'Uniontown',
      href: '/local-movers/pennsylvania/fayette',
      displayLabel: 'Fayette County, PA',
    },
    {
      slug: 'indiana',
      name: 'Indiana',
      seat: 'Indiana',
      href: '/local-movers/pennsylvania/indiana',
      displayLabel: 'Indiana County, PA',
    },
    {
      slug: 'armstrong',
      name: 'Armstrong',
      seat: 'Kittanning',
      href: '/local-movers/pennsylvania/armstrong',
      displayLabel: 'Armstrong County, PA',
    },
  ],
};

export function getPennsylvaniaNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return PA_COUNTY_NEIGHBORS[countySlug] ?? [];
}