/**
 * High-traffic metro counties targeted for balanced quality-gate expansion.
 * Each must maintain: explicit assignment, county research, 8+ FMCSA-verified movers, 60%+ USDOT coverage.
 */
export const PREMIUM_METRO_COUNTIES: ReadonlyArray<{ stateSlug: string; countySlug: string }> = [
  // Arizona
  { stateSlug: 'arizona', countySlug: 'maricopa' },
  { stateSlug: 'arizona', countySlug: 'pima' },
  // Washington Core 10
  { stateSlug: 'washington', countySlug: 'king' },
  { stateSlug: 'washington', countySlug: 'pierce' },
  { stateSlug: 'washington', countySlug: 'snohomish' },
  { stateSlug: 'washington', countySlug: 'spokane' },
  { stateSlug: 'washington', countySlug: 'clark' },
  { stateSlug: 'washington', countySlug: 'thurston' },
  { stateSlug: 'washington', countySlug: 'kitsap' },
  { stateSlug: 'washington', countySlug: 'whatcom' },
  { stateSlug: 'washington', countySlug: 'benton' },
  { stateSlug: 'washington', countySlug: 'yakima' },
  // Illinois
  { stateSlug: 'illinois', countySlug: 'cook' },
  { stateSlug: 'illinois', countySlug: 'dupage' },
  { stateSlug: 'illinois', countySlug: 'lake' },
  { stateSlug: 'illinois', countySlug: 'will' },
  { stateSlug: 'illinois', countySlug: 'kane' },
  { stateSlug: 'illinois', countySlug: 'mchenry' },
  { stateSlug: 'illinois', countySlug: 'winnebago' },
  { stateSlug: 'illinois', countySlug: 'madison' },
  { stateSlug: 'illinois', countySlug: 'st-clair' },
  { stateSlug: 'illinois', countySlug: 'sangamon' },
  { stateSlug: 'illinois', countySlug: 'champaign' },
  { stateSlug: 'illinois', countySlug: 'peoria' },
  // Colorado
  { stateSlug: 'colorado', countySlug: 'denver' },
  { stateSlug: 'colorado', countySlug: 'jefferson' },
  { stateSlug: 'colorado', countySlug: 'arapahoe' },
  { stateSlug: 'colorado', countySlug: 'adams' },
  { stateSlug: 'colorado', countySlug: 'douglas' },
  { stateSlug: 'colorado', countySlug: 'el-paso' },
  { stateSlug: 'colorado', countySlug: 'larimer' },
  { stateSlug: 'colorado', countySlug: 'boulder' },
  { stateSlug: 'colorado', countySlug: 'weld' },
  { stateSlug: 'colorado', countySlug: 'pueblo' },
  // Nevada
  { stateSlug: 'nevada', countySlug: 'clark' },
  { stateSlug: 'nevada', countySlug: 'washoe' },
  // Ohio
  { stateSlug: 'ohio', countySlug: 'franklin' },
  { stateSlug: 'ohio', countySlug: 'cuyahoga' },
  { stateSlug: 'ohio', countySlug: 'hamilton' },
  { stateSlug: 'ohio', countySlug: 'summit' },
  // Michigan
  { stateSlug: 'michigan', countySlug: 'wayne' },
  { stateSlug: 'michigan', countySlug: 'oakland' },
  { stateSlug: 'michigan', countySlug: 'macomb' },
  { stateSlug: 'michigan', countySlug: 'kent' },
  { stateSlug: 'michigan', countySlug: 'washtenaw' },
  // Virginia
  { stateSlug: 'virginia', countySlug: 'fairfax' },
  { stateSlug: 'virginia', countySlug: 'prince-william' },
  { stateSlug: 'virginia', countySlug: 'loudoun' },
  { stateSlug: 'virginia', countySlug: 'henrico' },
  { stateSlug: 'virginia', countySlug: 'chesterfield' },
  // Maryland
  { stateSlug: 'maryland', countySlug: 'montgomery' },
  { stateSlug: 'maryland', countySlug: 'prince-georges' },
  { stateSlug: 'maryland', countySlug: 'baltimore' },
  { stateSlug: 'maryland', countySlug: 'anne-arundel' },
  { stateSlug: 'maryland', countySlug: 'howard' },
  // Pennsylvania
  { stateSlug: 'pennsylvania', countySlug: 'philadelphia' },
  { stateSlug: 'pennsylvania', countySlug: 'allegheny' },
  { stateSlug: 'pennsylvania', countySlug: 'montgomery' },
  { stateSlug: 'pennsylvania', countySlug: 'bucks' },
  { stateSlug: 'pennsylvania', countySlug: 'delaware' },
  // California (expand beyond LA)
  { stateSlug: 'california', countySlug: 'orange' },
  { stateSlug: 'california', countySlug: 'san-diego' },
  { stateSlug: 'california', countySlug: 'santa-clara' },
  { stateSlug: 'california', countySlug: 'san-francisco' },
  { stateSlug: 'california', countySlug: 'alameda' },
  { stateSlug: 'california', countySlug: 'sacramento' },
  { stateSlug: 'california', countySlug: 'riverside' },
  { stateSlug: 'california', countySlug: 'san-bernardino' },
  // Georgia
  { stateSlug: 'georgia', countySlug: 'fulton' },
  { stateSlug: 'georgia', countySlug: 'gwinnett' },
  { stateSlug: 'georgia', countySlug: 'cobb' },
  { stateSlug: 'georgia', countySlug: 'dekalb' },
  // North Carolina
  { stateSlug: 'north-carolina', countySlug: 'wake' },
  { stateSlug: 'north-carolina', countySlug: 'mecklenburg' },
  { stateSlug: 'north-carolina', countySlug: 'guilford' },
  { stateSlug: 'north-carolina', countySlug: 'durham' },
  { stateSlug: 'north-carolina', countySlug: 'forsyth' },
  // Tennessee
  { stateSlug: 'tennessee', countySlug: 'davidson' },
  { stateSlug: 'tennessee', countySlug: 'shelby' },
  { stateSlug: 'tennessee', countySlug: 'knox' },
  { stateSlug: 'tennessee', countySlug: 'hamilton' },
  { stateSlug: 'tennessee', countySlug: 'williamson' },
  // Texas Tier 1 cores + Tier 2 Wave 1
  { stateSlug: 'texas', countySlug: 'harris' },
  { stateSlug: 'texas', countySlug: 'dallas' },
  { stateSlug: 'texas', countySlug: 'travis' },
  { stateSlug: 'texas', countySlug: 'tarrant' },
  { stateSlug: 'texas', countySlug: 'bexar' },
  { stateSlug: 'texas', countySlug: 'collin' },
  { stateSlug: 'texas', countySlug: 'denton' },
  { stateSlug: 'texas', countySlug: 'fort-bend' },
  { stateSlug: 'texas', countySlug: 'montgomery' },
  { stateSlug: 'texas', countySlug: 'williamson' },
  { stateSlug: 'texas', countySlug: 'el-paso' },
  { stateSlug: 'texas', countySlug: 'hidalgo' },
  { stateSlug: 'texas', countySlug: 'galveston' },
  { stateSlug: 'texas', countySlug: 'brazoria' },
  { stateSlug: 'texas', countySlug: 'hays' },
  { stateSlug: 'texas', countySlug: 'nueces' },
  { stateSlug: 'texas', countySlug: 'bell' },
  // New York
  { stateSlug: 'new-york', countySlug: 'kings' },
  { stateSlug: 'new-york', countySlug: 'new-york' },
  { stateSlug: 'new-york', countySlug: 'queens' },
  { stateSlug: 'new-york', countySlug: 'nassau' },
  { stateSlug: 'new-york', countySlug: 'westchester' },
  { stateSlug: 'new-york', countySlug: 'suffolk' },
  // New Jersey
  { stateSlug: 'new-jersey', countySlug: 'hudson' },
  { stateSlug: 'new-jersey', countySlug: 'essex' },
  { stateSlug: 'new-jersey', countySlug: 'bergen' },
  { stateSlug: 'new-jersey', countySlug: 'middlesex' },
  { stateSlug: 'new-jersey', countySlug: 'monmouth' },
  // Florida (expand)
  { stateSlug: 'florida', countySlug: 'miami-dade' },
  { stateSlug: 'florida', countySlug: 'broward' },
  { stateSlug: 'florida', countySlug: 'palm-beach' },
  { stateSlug: 'florida', countySlug: 'hillsborough' },
  { stateSlug: 'florida', countySlug: 'orange' },
  { stateSlug: 'florida', countySlug: 'pinellas' },
  { stateSlug: 'florida', countySlug: 'duval' },
  // South Carolina Core 12
  { stateSlug: 'south-carolina', countySlug: 'greenville' },
  { stateSlug: 'south-carolina', countySlug: 'charleston' },
  { stateSlug: 'south-carolina', countySlug: 'richland' },
  { stateSlug: 'south-carolina', countySlug: 'horry' },
  { stateSlug: 'south-carolina', countySlug: 'spartanburg' },
  { stateSlug: 'south-carolina', countySlug: 'york' },
  { stateSlug: 'south-carolina', countySlug: 'lexington' },
  { stateSlug: 'south-carolina', countySlug: 'berkeley' },
  { stateSlug: 'south-carolina', countySlug: 'beaufort' },
  { stateSlug: 'south-carolina', countySlug: 'dorchester' },
  { stateSlug: 'south-carolina', countySlug: 'anderson' },
  { stateSlug: 'south-carolina', countySlug: 'florence' },
  // Virginia Core 12
  { stateSlug: 'virginia', countySlug: 'fairfax' },
  { stateSlug: 'virginia', countySlug: 'prince-william' },
  { stateSlug: 'virginia', countySlug: 'loudoun' },
  { stateSlug: 'virginia', countySlug: 'chesterfield' },
  { stateSlug: 'virginia', countySlug: 'henrico' },
  { stateSlug: 'virginia', countySlug: 'virginia-beach' },
  { stateSlug: 'virginia', countySlug: 'arlington' },
  { stateSlug: 'virginia', countySlug: 'richmond' },
  { stateSlug: 'virginia', countySlug: 'chesapeake' },
  { stateSlug: 'virginia', countySlug: 'norfolk' },
  { stateSlug: 'virginia', countySlug: 'stafford' },
  { stateSlug: 'virginia', countySlug: 'spotsylvania' },
  // Indiana / Missouri / Minnesota
  { stateSlug: 'indiana', countySlug: 'marion' },
  { stateSlug: 'indiana', countySlug: 'hamilton' },
  { stateSlug: 'missouri', countySlug: 'st-louis' },
  { stateSlug: 'missouri', countySlug: 'jackson' },
  { stateSlug: 'minnesota', countySlug: 'hennepin' },
  { stateSlug: 'minnesota', countySlug: 'ramsey' },
  // Oregon / Utah
  { stateSlug: 'oregon', countySlug: 'multnomah' },
  { stateSlug: 'oregon', countySlug: 'washington' },
  { stateSlug: 'utah', countySlug: 'salt-lake' },
  { stateSlug: 'utah', countySlug: 'utah' },
  // Massachusetts Core 10
  { stateSlug: 'massachusetts', countySlug: 'middlesex' },
  { stateSlug: 'massachusetts', countySlug: 'worcester' },
  { stateSlug: 'massachusetts', countySlug: 'essex' },
  { stateSlug: 'massachusetts', countySlug: 'suffolk' },
  { stateSlug: 'massachusetts', countySlug: 'norfolk' },
  { stateSlug: 'massachusetts', countySlug: 'bristol' },
  { stateSlug: 'massachusetts', countySlug: 'plymouth' },
  { stateSlug: 'massachusetts', countySlug: 'hampden' },
  { stateSlug: 'massachusetts', countySlug: 'barnstable' },
  { stateSlug: 'massachusetts', countySlug: 'hampshire' },
  // Minnesota Core 8
  { stateSlug: 'minnesota', countySlug: 'hennepin' },
  { stateSlug: 'minnesota', countySlug: 'ramsey' },
  { stateSlug: 'minnesota', countySlug: 'dakota' },
  { stateSlug: 'minnesota', countySlug: 'anoka' },
  { stateSlug: 'minnesota', countySlug: 'washington' },
  { stateSlug: 'minnesota', countySlug: 'olmsted' },
  { stateSlug: 'minnesota', countySlug: 'st-louis' },
  { stateSlug: 'minnesota', countySlug: 'stearns' },
  // Wisconsin Core 8
  { stateSlug: 'wisconsin', countySlug: 'milwaukee' },
  { stateSlug: 'wisconsin', countySlug: 'dane' },
  { stateSlug: 'wisconsin', countySlug: 'waukesha' },
  { stateSlug: 'wisconsin', countySlug: 'brown' },
  { stateSlug: 'wisconsin', countySlug: 'racine' },
  { stateSlug: 'wisconsin', countySlug: 'kenosha' },
  { stateSlug: 'wisconsin', countySlug: 'outagamie' },
  { stateSlug: 'wisconsin', countySlug: 'winnebago' },
  // Missouri Core 6
  { stateSlug: 'missouri', countySlug: 'st-louis' },
  { stateSlug: 'missouri', countySlug: 'jackson' },
  { stateSlug: 'missouri', countySlug: 'st-charles' },
  { stateSlug: 'missouri', countySlug: 'greene' },
  { stateSlug: 'missouri', countySlug: 'clay' },
  { stateSlug: 'missouri', countySlug: 'jefferson' },
  // Kentucky Core 6
  { stateSlug: 'kentucky', countySlug: 'jefferson' },
  { stateSlug: 'kentucky', countySlug: 'fayette' },
  { stateSlug: 'kentucky', countySlug: 'kenton' },
  { stateSlug: 'kentucky', countySlug: 'boone' },
  { stateSlug: 'kentucky', countySlug: 'warren' },
  { stateSlug: 'kentucky', countySlug: 'hardin' },
  // Nevada Core 5 (clark/washoe already listed above)
  { stateSlug: 'nevada', countySlug: 'carson-city' },
  { stateSlug: 'nevada', countySlug: 'douglas' },
  { stateSlug: 'nevada', countySlug: 'nye' },
  // Oklahoma Core 6
  { stateSlug: 'oklahoma', countySlug: 'oklahoma' },
  { stateSlug: 'oklahoma', countySlug: 'tulsa' },
  { stateSlug: 'oklahoma', countySlug: 'cleveland' },
  { stateSlug: 'oklahoma', countySlug: 'canadian' },
  { stateSlug: 'oklahoma', countySlug: 'comanche' },
  { stateSlug: 'oklahoma', countySlug: 'rogers' },
  // Iowa Core 6
  { stateSlug: 'iowa', countySlug: 'polk' },
  { stateSlug: 'iowa', countySlug: 'linn' },
  { stateSlug: 'iowa', countySlug: 'scott' },
  { stateSlug: 'iowa', countySlug: 'johnson' },
  { stateSlug: 'iowa', countySlug: 'black-hawk' },
  { stateSlug: 'iowa', countySlug: 'woodbury' },
  // Kansas Core 6
  { stateSlug: 'kansas', countySlug: 'johnson' },
  { stateSlug: 'kansas', countySlug: 'sedgwick' },
  { stateSlug: 'kansas', countySlug: 'shawnee' },
  { stateSlug: 'kansas', countySlug: 'wyandotte' },
  { stateSlug: 'kansas', countySlug: 'douglas' },
  { stateSlug: 'kansas', countySlug: 'leavenworth' },
  // Mississippi Core 6
  { stateSlug: 'mississippi', countySlug: 'hinds' },
  { stateSlug: 'mississippi', countySlug: 'harrison' },
  { stateSlug: 'mississippi', countySlug: 'desoto' },
  { stateSlug: 'mississippi', countySlug: 'rankin' },
  { stateSlug: 'mississippi', countySlug: 'madison' },
  { stateSlug: 'mississippi', countySlug: 'jackson' },
  // New Hampshire Core 5
  { stateSlug: 'new-hampshire', countySlug: 'hillsborough' },
  { stateSlug: 'new-hampshire', countySlug: 'rockingham' },
  { stateSlug: 'new-hampshire', countySlug: 'merrimack' },
  { stateSlug: 'new-hampshire', countySlug: 'strafford' },
  { stateSlug: 'new-hampshire', countySlug: 'grafton' },
  // Maine Core 5
  { stateSlug: 'maine', countySlug: 'cumberland' },
  { stateSlug: 'maine', countySlug: 'york' },
  { stateSlug: 'maine', countySlug: 'penobscot' },
  { stateSlug: 'maine', countySlug: 'kennebec' },
  { stateSlug: 'maine', countySlug: 'androscoggin' },
  // West Virginia Core 5
  { stateSlug: 'west-virginia', countySlug: 'kanawha' },
  { stateSlug: 'west-virginia', countySlug: 'berkeley' },
  { stateSlug: 'west-virginia', countySlug: 'monongalia' },
  { stateSlug: 'west-virginia', countySlug: 'cabell' },
  { stateSlug: 'west-virginia', countySlug: 'wood' },
  // Rhode Island Core 5
  { stateSlug: 'rhode-island', countySlug: 'providence' },
  { stateSlug: 'rhode-island', countySlug: 'kent' },
  { stateSlug: 'rhode-island', countySlug: 'washington' },
  { stateSlug: 'rhode-island', countySlug: 'newport' },
  { stateSlug: 'rhode-island', countySlug: 'bristol' },
  // Alaska Core 4
  { stateSlug: 'alaska', countySlug: 'anchorage' },
  { stateSlug: 'alaska', countySlug: 'fairbanks-north-star' },
  { stateSlug: 'alaska', countySlug: 'matanuska-susitna' },
  { stateSlug: 'alaska', countySlug: 'juneau' },
  // Hawaii Core 4
  { stateSlug: 'hawaii', countySlug: 'honolulu' },
  { stateSlug: 'hawaii', countySlug: 'hawaii' },
  { stateSlug: 'hawaii', countySlug: 'maui' },
  { stateSlug: 'hawaii', countySlug: 'kauai' },
  // Montana Core 5
  { stateSlug: 'montana', countySlug: 'yellowstone' },
  { stateSlug: 'montana', countySlug: 'missoula' },
  { stateSlug: 'montana', countySlug: 'gallatin' },
  { stateSlug: 'montana', countySlug: 'cascade' },
  { stateSlug: 'montana', countySlug: 'lewis-and-clark' },
] as const;

const premiumMetroKeySet = new Set(
  PREMIUM_METRO_COUNTIES.map((c) => `${c.stateSlug}/${c.countySlug}`)
);

export function isPremiumMetroCounty(stateSlug: string, countySlug: string): boolean {
  return premiumMetroKeySet.has(`${stateSlug}/${countySlug}`);
}