/** AUTO-GENERATED — run scripts/generate-texas-nearby.ts to refresh */
export const TX_COUNTY_NEIGHBORS_GENERATED: Record<string, string[]> = {
  anderson: ['cherokee', 'freestone', 'henderson', 'houston', 'leon'],
  andrews: ['ector', 'gaines', 'martin', 'midland', 'winkler'],
  angelina: ['cherokee', 'houston', 'jasper', 'nacogdoches', 'polk', 'san-augustine'],
  aransas: ['calhoun', 'kleberg', 'refugio', 'san-patricio'],
  archer: ['baylor', 'clay', 'jack', 'throckmorton', 'wichita', 'wilbarger'],
  armstrong: ['briscoe', 'carson', 'donley', 'gray', 'potter', 'randall'],
  atascosa: ['bexar', 'frio', 'karnes', 'la-salle', 'live-oak', 'mcmullen'],
  austin: ['colorado', 'fayette', 'fort-bend', 'waller', 'washington', 'wharton'],
  bailey: ['cochran', 'hockley', 'lamb', 'parmer'],
  bandera: ['bexar', 'kendall', 'kerr', 'medina', 'real', 'uvalde'],
  bastrop: ['caldwell', 'fayette', 'lee', 'travis', 'williamson'],
  baylor: ['archer', 'foard', 'haskell', 'knox', 'throckmorton', 'wichita'],
  bee: ['goliad', 'karnes', 'live-oak', 'refugio', 'san-patricio'],
  bell: ['burnet', 'coryell', 'falls', 'lampasas', 'mclennan', 'milam'],
  bexar: ['atascosa', 'bandera', 'comal', 'guadalupe', 'kendall', 'medina'],
  blanco: ['burnet', 'comal', 'gillespie', 'hays', 'kendall', 'llano'],
  borden: ['dawson', 'garza', 'howard', 'lynn', 'martin', 'mitchell'],
  bosque: ['coryell', 'erath', 'hamilton', 'hill', 'johnson', 'mclennan'],
  bowie: ['cass', 'morris', 'red-river'],
  brazoria: ['fort-bend', 'galveston', 'harris', 'matagorda', 'wharton'],
  brazos: ['burleson', 'grimes', 'leon', 'madison', 'robertson', 'washington'],
  brewster: ['jeff-davis', 'pecos', 'presidio', 'terrell'],
  briscoe: ['armstrong', 'donley', 'floyd', 'hall', 'motley', 'swisher'],
  brooks: ['duval', 'hidalgo', 'jim-hogg', 'jim-wells', 'kenedy', 'kleberg'],
  brown: ['callahan', 'coleman', 'comanche', 'eastland', 'mcculloch', 'mills'],
  burleson: ['brazos', 'lee', 'milam', 'robertson', 'washington'],
  burnet: ['bell', 'blanco', 'lampasas', 'llano', 'san-saba', 'travis'],
  caldwell: ['bastrop', 'fayette', 'gonzales', 'guadalupe', 'hays', 'travis'],
  calhoun: ['aransas', 'jackson', 'matagorda', 'refugio', 'victoria'],
  callahan: ['brown', 'coleman', 'eastland', 'jones', 'shackelford', 'taylor'],
  cameron: ['hidalgo', 'willacy'],
  camp: ['franklin', 'morris', 'titus', 'upshur', 'wood'],
  carson: ['armstrong', 'donley', 'gray', 'hutchinson', 'moore', 'potter'],
  cass: ['bowie', 'marion', 'morris'],
  castro: ['deaf-smith', 'hale', 'lamb', 'parmer', 'randall', 'swisher'],
  chambers: ['galveston', 'harris', 'jefferson', 'liberty'],
  cherokee: ['anderson', 'angelina', 'henderson', 'houston', 'nacogdoches', 'rusk'],
  childress: ['collingsworth', 'cottle', 'hall', 'hardeman'],
  clay: ['archer', 'jack', 'montague', 'wichita'],
  cochran: ['bailey', 'hockley', 'lamb', 'terry', 'yoakum'],
  coke: ['mitchell', 'nolan', 'runnels', 'sterling', 'tom-green'],
  coleman: ['brown', 'callahan', 'concho', 'mcculloch', 'runnels', 'taylor'],
  collin: ['dallas', 'denton', 'fannin', 'grayson', 'hunt', 'rockwall'],
  collingsworth: ['childress', 'donley', 'gray', 'hall', 'wheeler'],
  colorado: ['austin', 'fayette', 'jackson', 'lavaca', 'wharton'],
  comal: ['bexar', 'blanco', 'guadalupe', 'hays', 'kendall'],
  comanche: ['brown', 'eastland', 'erath', 'hamilton', 'mills'],
  concho: ['coleman', 'mcculloch', 'menard', 'runnels', 'schleicher', 'tom-green'],
  cooke: ['denton', 'grayson', 'montague', 'wise'],
  coryell: ['bell', 'bosque', 'hamilton', 'lampasas', 'mclennan'],
  cottle: ['childress', 'dickens', 'foard', 'hall', 'hardeman', 'king'],
  crane: ['crockett', 'ector', 'pecos', 'upton', 'ward'],
  crockett: ['crane', 'irion', 'pecos', 'reagan', 'schleicher', 'sutton'],
  crosby: ['dickens', 'floyd', 'garza', 'hale', 'kent', 'lubbock'],
  culberson: ['hudspeth', 'jeff-davis', 'reeves'],
  dallam: ['hartley', 'moore', 'sherman'],
  dallas: ['collin', 'denton', 'ellis', 'kaufman', 'rockwall', 'tarrant'],
  dawson: ['borden', 'gaines', 'howard', 'lynn', 'martin', 'terry'],
  'deaf-smith': ['castro', 'oldham', 'parmer', 'potter', 'randall'],
  delta: ['fannin', 'franklin', 'hopkins', 'hunt', 'lamar', 'red-river'],
  denton: ['collin', 'cooke', 'dallas', 'grayson', 'tarrant', 'wise'],
  dewitt: ['goliad', 'gonzales', 'karnes', 'lavaca', 'victoria'],
  dickens: ['cottle', 'crosby', 'floyd', 'garza', 'kent', 'king'],
  dimmit: ['frio', 'la-salle', 'maverick', 'webb', 'zavala'],
  donley: ['armstrong', 'briscoe', 'carson', 'collingsworth', 'gray', 'hall'],
  duval: ['brooks', 'jim-hogg', 'jim-wells', 'la-salle', 'live-oak', 'mcmullen'],
  eastland: ['brown', 'callahan', 'comanche', 'erath', 'palo-pinto', 'shackelford'],
  ector: ['andrews', 'crane', 'midland', 'upton', 'ward', 'winkler'],
  edwards: ['kerr', 'kimble', 'kinney', 'real', 'sutton', 'uvalde'],
  'el-paso': ['hudspeth'],
  ellis: ['dallas', 'henderson', 'hill', 'johnson', 'kaufman', 'navarro'],
  erath: ['bosque', 'comanche', 'eastland', 'hamilton', 'hood', 'palo-pinto'],
  falls: ['bell', 'limestone', 'mclennan', 'milam', 'robertson'],
  fannin: ['collin', 'delta', 'grayson', 'hunt', 'lamar'],
  fayette: ['austin', 'bastrop', 'caldwell', 'colorado', 'gonzales', 'lavaca'],
  fisher: ['jones', 'kent', 'mitchell', 'nolan', 'scurry', 'stonewall'],
  floyd: ['briscoe', 'crosby', 'dickens', 'hale', 'lubbock', 'motley'],
  foard: ['baylor', 'cottle', 'hardeman', 'king', 'knox', 'wilbarger'],
  'fort-bend': ['austin', 'brazoria', 'harris', 'waller', 'wharton'],
  franklin: ['camp', 'delta', 'hopkins', 'red-river', 'titus', 'wood'],
  freestone: ['anderson', 'henderson', 'leon', 'limestone', 'navarro'],
  frio: ['atascosa', 'dimmit', 'la-salle', 'medina', 'uvalde', 'zavala'],
  gaines: ['andrews', 'dawson', 'martin', 'terry', 'yoakum'],
  galveston: ['brazoria', 'chambers', 'harris'],
  garza: ['borden', 'crosby', 'dickens', 'kent', 'lubbock', 'lynn'],
  gillespie: ['blanco', 'kendall', 'kerr', 'kimble', 'llano', 'mason'],
  glasscock: ['howard', 'martin', 'midland', 'reagan', 'sterling', 'upton'],
  goliad: ['bee', 'dewitt', 'karnes', 'refugio', 'victoria'],
  gonzales: ['caldwell', 'dewitt', 'fayette', 'guadalupe', 'karnes', 'lavaca'],
  gray: ['armstrong', 'carson', 'collingsworth', 'donley', 'hemphill', 'roberts'],
  grayson: ['collin', 'cooke', 'denton', 'fannin'],
  gregg: ['harrison', 'rusk', 'smith', 'upshur'],
  grimes: ['brazos', 'madison', 'montgomery', 'walker', 'waller', 'washington'],
  guadalupe: ['bexar', 'caldwell', 'comal', 'gonzales', 'hays', 'wilson'],
  hale: ['castro', 'crosby', 'floyd', 'hockley', 'lamb', 'lubbock'],
  hall: ['briscoe', 'childress', 'collingsworth', 'cottle', 'donley', 'motley'],
  hamilton: ['bosque', 'comanche', 'coryell', 'erath', 'lampasas', 'mills'],
  hansford: ['hutchinson', 'moore', 'ochiltree', 'roberts', 'sherman'],
  hardeman: ['childress', 'cottle', 'foard', 'wilbarger'],
  hardin: ['jasper', 'jefferson', 'liberty', 'orange', 'polk', 'tyler'],
  harris: ['brazoria', 'chambers', 'fort-bend', 'galveston', 'liberty', 'montgomery'],
  harrison: ['gregg', 'marion', 'panola', 'rusk', 'upshur'],
  hartley: ['dallam', 'moore', 'oldham', 'sherman'],
  haskell: ['baylor', 'jones', 'king', 'knox', 'shackelford', 'stonewall'],
  hays: ['blanco', 'caldwell', 'comal', 'guadalupe', 'travis'],
  hemphill: ['gray', 'lipscomb', 'roberts', 'wheeler'],
  henderson: ['anderson', 'cherokee', 'ellis', 'freestone', 'kaufman', 'navarro'],
  hidalgo: ['brooks', 'cameron', 'kenedy', 'starr', 'willacy'],
  hill: ['bosque', 'ellis', 'johnson', 'limestone', 'mclennan', 'navarro'],
  hockley: ['bailey', 'cochran', 'hale', 'lamb', 'lubbock', 'lynn'],
  hood: ['erath', 'johnson', 'palo-pinto', 'parker', 'somervell'],
  hopkins: ['delta', 'franklin', 'hunt', 'rains', 'wood'],
  houston: ['anderson', 'angelina', 'cherokee', 'leon', 'madison', 'trinity'],
  howard: ['borden', 'dawson', 'glasscock', 'martin', 'mitchell', 'sterling'],
  hudspeth: ['culberson', 'el-paso', 'jeff-davis', 'presidio'],
  hunt: ['collin', 'delta', 'fannin', 'hopkins', 'kaufman', 'rains'],
  hutchinson: ['carson', 'hansford', 'moore', 'roberts', 'sherman'],
  irion: ['crockett', 'reagan', 'schleicher', 'tom-green'],
  jack: ['archer', 'clay', 'montague', 'palo-pinto', 'parker', 'wise'],
  jackson: ['calhoun', 'colorado', 'lavaca', 'matagorda', 'victoria', 'wharton'],
  jasper: ['angelina', 'hardin', 'newton', 'orange', 'sabine', 'san-augustine'],
  'jeff-davis': ['brewster', 'culberson', 'hudspeth', 'pecos', 'presidio', 'reeves'],
  jefferson: ['chambers', 'hardin', 'liberty', 'orange'],
  'jim-hogg': ['brooks', 'duval', 'starr', 'webb', 'zapata'],
  'jim-wells': ['brooks', 'duval', 'kleberg', 'live-oak', 'nueces', 'san-patricio'],
  johnson: ['bosque', 'ellis', 'hill', 'hood', 'parker', 'somervell'],
  jones: ['callahan', 'fisher', 'haskell', 'nolan', 'shackelford', 'stonewall'],
  karnes: ['atascosa', 'bee', 'dewitt', 'goliad', 'gonzales', 'live-oak'],
  kaufman: ['dallas', 'ellis', 'henderson', 'hunt', 'rockwall', 'van-zandt'],
  kendall: ['bandera', 'bexar', 'blanco', 'comal', 'gillespie', 'kerr'],
  kenedy: ['brooks', 'hidalgo', 'kleberg', 'willacy'],
  kent: ['crosby', 'dickens', 'fisher', 'garza', 'king', 'scurry'],
  kerr: ['bandera', 'edwards', 'gillespie', 'kendall', 'kimble', 'real'],
  kimble: ['edwards', 'gillespie', 'kerr', 'mason', 'menard', 'schleicher'],
  king: ['cottle', 'dickens', 'foard', 'haskell', 'kent', 'knox'],
  kinney: ['edwards', 'maverick', 'uvalde', 'val-verde', 'zavala'],
  kleberg: ['aransas', 'brooks', 'jim-wells', 'kenedy', 'nueces'],
  knox: ['baylor', 'foard', 'haskell', 'king', 'stonewall', 'throckmorton'],
  'la-salle': ['atascosa', 'dimmit', 'duval', 'frio', 'mcmullen', 'webb'],
  lamar: ['delta', 'fannin', 'red-river'],
  lamb: ['bailey', 'castro', 'cochran', 'hale', 'hockley', 'lubbock'],
  lampasas: ['bell', 'burnet', 'coryell', 'hamilton', 'mills', 'san-saba'],
  lavaca: ['colorado', 'dewitt', 'fayette', 'gonzales', 'jackson', 'victoria'],
  lee: ['bastrop', 'burleson', 'fayette', 'milam', 'washington', 'williamson'],
  leon: ['anderson', 'brazos', 'freestone', 'houston', 'limestone', 'madison'],
  liberty: ['chambers', 'hardin', 'harris', 'jefferson', 'montgomery', 'polk'],
  limestone: ['falls', 'freestone', 'hill', 'leon', 'mclennan', 'navarro'],
  lipscomb: ['hemphill', 'ochiltree', 'roberts'],
  'live-oak': ['atascosa', 'bee', 'duval', 'jim-wells', 'karnes', 'mcmullen'],
  llano: ['blanco', 'burnet', 'gillespie', 'mason', 'san-saba'],
  loving: ['reeves', 'ward', 'winkler'],
  lubbock: ['crosby', 'floyd', 'garza', 'hale', 'hockley', 'lamb'],
  lynn: ['borden', 'crosby', 'dawson', 'garza', 'hockley', 'lubbock'],
  madison: ['brazos', 'grimes', 'houston', 'leon', 'robertson', 'walker'],
  marion: ['cass', 'harrison', 'morris', 'upshur'],
  martin: ['andrews', 'borden', 'dawson', 'gaines', 'glasscock', 'howard'],
  mason: ['gillespie', 'kimble', 'llano', 'mcculloch', 'menard', 'san-saba'],
  matagorda: ['brazoria', 'calhoun', 'jackson', 'wharton'],
  maverick: ['dimmit', 'kinney', 'uvalde', 'webb', 'zavala'],
  mcculloch: ['brown', 'coleman', 'concho', 'mason', 'menard', 'san-saba'],
  mclennan: ['bell', 'bosque', 'coryell', 'falls', 'hill', 'limestone'],
  mcmullen: ['atascosa', 'duval', 'la-salle', 'live-oak', 'webb'],
  medina: ['atascosa', 'bandera', 'bexar', 'frio', 'uvalde', 'zavala'],
  menard: ['concho', 'kimble', 'mason', 'mcculloch', 'schleicher', 'sutton'],
  midland: ['andrews', 'ector', 'glasscock', 'martin', 'reagan', 'upton'],
  milam: ['bell', 'burleson', 'falls', 'lee', 'robertson', 'williamson'],
  mills: ['brown', 'comanche', 'hamilton', 'lampasas', 'san-saba'],
  mitchell: ['borden', 'coke', 'fisher', 'howard', 'nolan', 'scurry'],
  montague: ['clay', 'cooke', 'jack', 'wise'],
  montgomery: ['grimes', 'harris', 'liberty', 'san-jacinto', 'walker', 'waller'],
  moore: ['carson', 'dallam', 'hansford', 'hartley', 'hutchinson', 'oldham'],
  morris: ['bowie', 'camp', 'cass', 'marion', 'red-river', 'titus'],
  motley: ['briscoe', 'cottle', 'crosby', 'dickens', 'floyd', 'hall'],
  nacogdoches: ['angelina', 'cherokee', 'rusk', 'san-augustine', 'shelby'],
  navarro: ['ellis', 'freestone', 'henderson', 'hill', 'limestone'],
  newton: ['jasper', 'orange', 'sabine'],
  nolan: ['coke', 'fisher', 'jones', 'mitchell', 'runnels', 'scurry'],
  nueces: ['jim-wells', 'kleberg', 'san-patricio'],
  ochiltree: ['hansford', 'lipscomb', 'roberts'],
  oldham: ['deaf-smith', 'hartley', 'moore', 'potter', 'randall'],
  orange: ['hardin', 'jasper', 'jefferson', 'newton'],
  'palo-pinto': ['eastland', 'erath', 'hood', 'jack', 'parker', 'stephens'],
  panola: ['harrison', 'rusk', 'shelby'],
  parker: ['hood', 'jack', 'johnson', 'palo-pinto', 'tarrant', 'wise'],
  parmer: ['bailey', 'castro', 'deaf-smith', 'lamb'],
  pecos: ['brewster', 'crane', 'crockett', 'jeff-davis', 'reeves', 'terrell'],
  polk: ['angelina', 'hardin', 'liberty', 'san-jacinto', 'trinity', 'tyler'],
  potter: ['armstrong', 'carson', 'deaf-smith', 'moore', 'oldham', 'randall'],
  presidio: ['brewster', 'hudspeth', 'jeff-davis'],
  rains: ['hopkins', 'hunt', 'van-zandt', 'wood'],
  randall: ['armstrong', 'carson', 'castro', 'deaf-smith', 'oldham', 'potter'],
  reagan: ['crockett', 'glasscock', 'irion', 'midland', 'sterling', 'tom-green'],
  real: ['bandera', 'edwards', 'kerr', 'uvalde'],
  'red-river': ['bowie', 'delta', 'franklin', 'lamar', 'morris', 'titus'],
  reeves: ['culberson', 'jeff-davis', 'loving', 'pecos', 'ward'],
  refugio: ['aransas', 'bee', 'calhoun', 'goliad', 'san-patricio', 'victoria'],
  roberts: ['carson', 'gray', 'hansford', 'hemphill', 'hutchinson', 'lipscomb'],
  robertson: ['brazos', 'burleson', 'falls', 'leon', 'limestone', 'madison'],
  rockwall: ['collin', 'dallas', 'hunt', 'kaufman'],
  runnels: ['coke', 'coleman', 'concho', 'nolan', 'taylor', 'tom-green'],
  rusk: ['cherokee', 'gregg', 'harrison', 'nacogdoches', 'panola', 'shelby'],
  sabine: ['jasper', 'newton', 'san-augustine', 'shelby'],
  'san-augustine': ['angelina', 'jasper', 'nacogdoches', 'sabine', 'shelby'],
  'san-jacinto': ['liberty', 'montgomery', 'polk', 'trinity', 'walker'],
  'san-patricio': ['aransas', 'bee', 'jim-wells', 'live-oak', 'nueces', 'refugio'],
  'san-saba': ['brown', 'burnet', 'lampasas', 'llano', 'mason', 'mcculloch'],
  schleicher: ['concho', 'crockett', 'irion', 'kimble', 'menard', 'sutton'],
  scurry: ['borden', 'fisher', 'garza', 'kent', 'mitchell', 'nolan'],
  shackelford: ['callahan', 'eastland', 'haskell', 'jones', 'stephens', 'throckmorton'],
  shelby: ['nacogdoches', 'panola', 'rusk', 'sabine', 'san-augustine'],
  sherman: ['dallam', 'hansford', 'hartley', 'hutchinson', 'moore'],
  smith: ['cherokee', 'gregg', 'henderson', 'rusk', 'upshur', 'van-zandt'],
  somervell: ['bosque', 'erath', 'hood', 'johnson'],
  starr: ['brooks', 'hidalgo', 'jim-hogg', 'zapata'],
  stephens: ['eastland', 'palo-pinto', 'shackelford', 'throckmorton', 'young'],
  sterling: ['coke', 'glasscock', 'howard', 'mitchell', 'reagan', 'tom-green'],
  stonewall: ['dickens', 'fisher', 'haskell', 'jones', 'kent', 'king'],
  sutton: ['crockett', 'edwards', 'kimble', 'menard', 'schleicher', 'val-verde'],
  swisher: ['armstrong', 'briscoe', 'castro', 'floyd', 'hale', 'randall'],
  tarrant: ['dallas', 'denton', 'ellis', 'johnson', 'parker', 'wise'],
  taylor: ['callahan', 'coleman', 'fisher', 'jones', 'nolan', 'runnels'],
  terrell: ['brewster', 'crockett', 'pecos', 'val-verde'],
  terry: ['cochran', 'dawson', 'gaines', 'hockley', 'lubbock', 'lynn'],
  throckmorton: ['archer', 'baylor', 'haskell', 'knox', 'shackelford', 'stephens'],
  titus: ['camp', 'franklin', 'morris', 'red-river'],
  'tom-green': ['coke', 'concho', 'irion', 'menard', 'reagan', 'runnels'],
  travis: ['bastrop', 'blanco', 'burnet', 'caldwell', 'hays', 'williamson'],
  trinity: ['angelina', 'houston', 'polk', 'san-jacinto', 'walker'],
  tyler: ['angelina', 'hardin', 'jasper', 'polk'],
  upshur: ['camp', 'gregg', 'harrison', 'marion', 'morris', 'smith'],
  upton: ['crane', 'crockett', 'ector', 'glasscock', 'midland', 'reagan'],
  uvalde: ['bandera', 'edwards', 'frio', 'kinney', 'maverick', 'medina'],
  'val-verde': ['crockett', 'edwards', 'kinney', 'sutton', 'terrell'],
  'van-zandt': ['henderson', 'hunt', 'kaufman', 'rains', 'smith', 'wood'],
  victoria: ['calhoun', 'dewitt', 'goliad', 'jackson', 'lavaca', 'refugio'],
  walker: ['grimes', 'houston', 'madison', 'montgomery', 'san-jacinto', 'trinity'],
  waller: ['austin', 'fort-bend', 'grimes', 'harris', 'montgomery', 'washington'],
  ward: ['crane', 'ector', 'loving', 'pecos', 'reeves', 'winkler'],
  washington: ['austin', 'brazos', 'burleson', 'fayette', 'grimes', 'lee'],
  webb: ['dimmit', 'duval', 'jim-hogg', 'la-salle', 'maverick', 'mcmullen'],
  wharton: ['austin', 'brazoria', 'colorado', 'fort-bend', 'jackson', 'matagorda'],
  wheeler: ['collingsworth', 'donley', 'gray', 'hemphill', 'roberts'],
  wichita: ['archer', 'baylor', 'clay', 'wilbarger'],
  wilbarger: ['archer', 'baylor', 'foard', 'hardeman', 'wichita'],
  willacy: ['cameron', 'hidalgo', 'kenedy'],
  williamson: ['bastrop', 'bell', 'burnet', 'lee', 'milam', 'travis'],
  wilson: ['atascosa', 'bexar', 'gonzales', 'guadalupe', 'karnes'],
  winkler: ['andrews', 'ector', 'loving', 'ward'],
  wise: ['cooke', 'denton', 'jack', 'montague', 'parker', 'tarrant'],
  wood: ['camp', 'franklin', 'hopkins', 'rains', 'smith', 'upshur'],
  yoakum: ['cochran', 'gaines', 'hockley', 'terry'],
  young: ['archer', 'baylor', 'jack', 'palo-pinto', 'stephens', 'throckmorton'],
  zapata: ['jim-hogg', 'starr', 'webb'],
  zavala: ['dimmit', 'frio', 'kinney', 'maverick', 'medina', 'uvalde'],
};
