import type { NearbyCountyLink } from '@/lib/local-movers/nearby-types';

export type { NearbyCountyLink };

/** Washington premium hubs — regional corridor links */
const WA_COUNTY_NEIGHBORS: Record<string, NearbyCountyLink[]> = {
  king: [
    { slug: 'snohomish', name: 'Snohomish', seat: 'Everett', href: '/local-movers/washington/snohomish', displayLabel: 'Snohomish County, WA' },
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
    { slug: 'kitsap', name: 'Kitsap', seat: 'Port Orchard', href: '/local-movers/washington/kitsap', displayLabel: 'Kitsap County, WA' },
    { slug: 'island', name: 'Island', seat: 'Coupeville', href: '/local-movers/washington/island', displayLabel: 'Island County, WA' },
    { slug: 'skagit', name: 'Skagit', seat: 'Mount Vernon', href: '/local-movers/washington/skagit', displayLabel: 'Skagit County, WA' },
  ],
  pierce: [
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
    { slug: 'thurston', name: 'Thurston', seat: 'Olympia', href: '/local-movers/washington/thurston', displayLabel: 'Thurston County, WA' },
    { slug: 'kitsap', name: 'Kitsap', seat: 'Port Orchard', href: '/local-movers/washington/kitsap', displayLabel: 'Kitsap County, WA' },
    { slug: 'lewis', name: 'Lewis', seat: 'Chehalis', href: '/local-movers/washington/lewis', displayLabel: 'Lewis County, WA' },
    { slug: 'grays-harbor', name: 'Grays Harbor', seat: 'Montesano', href: '/local-movers/washington/grays-harbor', displayLabel: 'Grays Harbor County, WA' },
  ],
  snohomish: [
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
    { slug: 'skagit', name: 'Skagit', seat: 'Mount Vernon', href: '/local-movers/washington/skagit', displayLabel: 'Skagit County, WA' },
    { slug: 'whatcom', name: 'Whatcom', seat: 'Bellingham', href: '/local-movers/washington/whatcom', displayLabel: 'Whatcom County, WA' },
    { slug: 'island', name: 'Island', seat: 'Coupeville', href: '/local-movers/washington/island', displayLabel: 'Island County, WA' },
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
  ],
  spokane: [
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
    { slug: 'benton', name: 'Benton', seat: 'Kennewick', href: '/local-movers/washington/benton', displayLabel: 'Benton County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
  ],
  clark: [
    { slug: 'cowlitz', name: 'Cowlitz', seat: 'Kelso', href: '/local-movers/washington/cowlitz', displayLabel: 'Cowlitz County, WA' },
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
    { slug: 'lewis', name: 'Lewis', seat: 'Chehalis', href: '/local-movers/washington/lewis', displayLabel: 'Lewis County, WA' },
    { slug: 'thurston', name: 'Thurston', seat: 'Olympia', href: '/local-movers/washington/thurston', displayLabel: 'Thurston County, WA' },
  ],
  thurston: [
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
    { slug: 'kitsap', name: 'Kitsap', seat: 'Port Orchard', href: '/local-movers/washington/kitsap', displayLabel: 'Kitsap County, WA' },
    { slug: 'lewis', name: 'Lewis', seat: 'Chehalis', href: '/local-movers/washington/lewis', displayLabel: 'Lewis County, WA' },
    { slug: 'grays-harbor', name: 'Grays Harbor', seat: 'Montesano', href: '/local-movers/washington/grays-harbor', displayLabel: 'Grays Harbor County, WA' },
  ],
  kitsap: [
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
    { slug: 'island', name: 'Island', seat: 'Coupeville', href: '/local-movers/washington/island', displayLabel: 'Island County, WA' },
    { slug: 'thurston', name: 'Thurston', seat: 'Olympia', href: '/local-movers/washington/thurston', displayLabel: 'Thurston County, WA' },
    { slug: 'snohomish', name: 'Snohomish', seat: 'Everett', href: '/local-movers/washington/snohomish', displayLabel: 'Snohomish County, WA' },
  ],
  yakima: [
    { slug: 'benton', name: 'Benton', seat: 'Kennewick', href: '/local-movers/washington/benton', displayLabel: 'Benton County, WA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Pasco', href: '/local-movers/washington/franklin', displayLabel: 'Franklin County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
  ],
  whatcom: [
    { slug: 'skagit', name: 'Skagit', seat: 'Mount Vernon', href: '/local-movers/washington/skagit', displayLabel: 'Skagit County, WA' },
    { slug: 'snohomish', name: 'Snohomish', seat: 'Everett', href: '/local-movers/washington/snohomish', displayLabel: 'Snohomish County, WA' },
    { slug: 'island', name: 'Island', seat: 'Coupeville', href: '/local-movers/washington/island', displayLabel: 'Island County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
    { slug: 'clallam', name: 'Clallam', seat: 'Port Angeles', href: '/local-movers/washington/clallam', displayLabel: 'Clallam County, WA' },
  ],
  benton: [
    { slug: 'franklin', name: 'Franklin', seat: 'Pasco', href: '/local-movers/washington/franklin', displayLabel: 'Franklin County, WA' },
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
  ],
  skagit: [
    { slug: 'whatcom', name: 'Whatcom', seat: 'Bellingham', href: '/local-movers/washington/whatcom', displayLabel: 'Whatcom County, WA' },
    { slug: 'snohomish', name: 'Snohomish', seat: 'Everett', href: '/local-movers/washington/snohomish', displayLabel: 'Snohomish County, WA' },
    { slug: 'island', name: 'Island', seat: 'Coupeville', href: '/local-movers/washington/island', displayLabel: 'Island County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
  ],
  cowlitz: [
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
    { slug: 'lewis', name: 'Lewis', seat: 'Chehalis', href: '/local-movers/washington/lewis', displayLabel: 'Lewis County, WA' },
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
    { slug: 'grays-harbor', name: 'Grays Harbor', seat: 'Montesano', href: '/local-movers/washington/grays-harbor', displayLabel: 'Grays Harbor County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
  ],
  grant: [
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
    { slug: 'benton', name: 'Benton', seat: 'Kennewick', href: '/local-movers/washington/benton', displayLabel: 'Benton County, WA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Pasco', href: '/local-movers/washington/franklin', displayLabel: 'Franklin County, WA' },
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
  ],
  franklin: [
    { slug: 'benton', name: 'Benton', seat: 'Kennewick', href: '/local-movers/washington/benton', displayLabel: 'Benton County, WA' },
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
  ],
  lewis: [
    { slug: 'thurston', name: 'Thurston', seat: 'Olympia', href: '/local-movers/washington/thurston', displayLabel: 'Thurston County, WA' },
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
    { slug: 'cowlitz', name: 'Cowlitz', seat: 'Kelso', href: '/local-movers/washington/cowlitz', displayLabel: 'Cowlitz County, WA' },
    { slug: 'grays-harbor', name: 'Grays Harbor', seat: 'Montesano', href: '/local-movers/washington/grays-harbor', displayLabel: 'Grays Harbor County, WA' },
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
  ],
  island: [
    { slug: 'snohomish', name: 'Snohomish', seat: 'Everett', href: '/local-movers/washington/snohomish', displayLabel: 'Snohomish County, WA' },
    { slug: 'skagit', name: 'Skagit', seat: 'Mount Vernon', href: '/local-movers/washington/skagit', displayLabel: 'Skagit County, WA' },
    { slug: 'kitsap', name: 'Kitsap', seat: 'Port Orchard', href: '/local-movers/washington/kitsap', displayLabel: 'Kitsap County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
    { slug: 'clallam', name: 'Clallam', seat: 'Port Angeles', href: '/local-movers/washington/clallam', displayLabel: 'Clallam County, WA' },
  ],
  chelan: [
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
    { slug: 'benton', name: 'Benton', seat: 'Kennewick', href: '/local-movers/washington/benton', displayLabel: 'Benton County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
  ],
  clallam: [
    { slug: 'island', name: 'Island', seat: 'Coupeville', href: '/local-movers/washington/island', displayLabel: 'Island County, WA' },
    { slug: 'kitsap', name: 'Kitsap', seat: 'Port Orchard', href: '/local-movers/washington/kitsap', displayLabel: 'Kitsap County, WA' },
    { slug: 'whatcom', name: 'Whatcom', seat: 'Bellingham', href: '/local-movers/washington/whatcom', displayLabel: 'Whatcom County, WA' },
    { slug: 'grays-harbor', name: 'Grays Harbor', seat: 'Montesano', href: '/local-movers/washington/grays-harbor', displayLabel: 'Grays Harbor County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
  ],
  'grays-harbor': [
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
    { slug: 'thurston', name: 'Thurston', seat: 'Olympia', href: '/local-movers/washington/thurston', displayLabel: 'Thurston County, WA' },
    { slug: 'lewis', name: 'Lewis', seat: 'Chehalis', href: '/local-movers/washington/lewis', displayLabel: 'Lewis County, WA' },
    { slug: 'clallam', name: 'Clallam', seat: 'Port Angeles', href: '/local-movers/washington/clallam', displayLabel: 'Clallam County, WA' },
    { slug: 'cowlitz', name: 'Cowlitz', seat: 'Kelso', href: '/local-movers/washington/cowlitz', displayLabel: 'Cowlitz County, WA' },
  ],
  mason: [
    { slug: 'thurston', name: 'Thurston', seat: 'Olympia', href: '/local-movers/washington/thurston', displayLabel: 'Thurston County, WA' },
    { slug: 'kitsap', name: 'Kitsap', seat: 'Port Orchard', href: '/local-movers/washington/kitsap', displayLabel: 'Kitsap County, WA' },
    { slug: 'pierce', name: 'Pierce', seat: 'Tacoma', href: '/local-movers/washington/pierce', displayLabel: 'Pierce County, WA' },
    { slug: 'grays-harbor', name: 'Grays Harbor', seat: 'Montesano', href: '/local-movers/washington/grays-harbor', displayLabel: 'Grays Harbor County, WA' },
    { slug: 'jefferson', name: 'Jefferson', seat: 'Port Townsend', href: '/local-movers/washington/jefferson', displayLabel: 'Jefferson County, WA' },
  ],
  'walla-walla': [
    { slug: 'franklin', name: 'Franklin', seat: 'Pasco', href: '/local-movers/washington/franklin', displayLabel: 'Franklin County, WA' },
    { slug: 'benton', name: 'Benton', seat: 'Kennewick', href: '/local-movers/washington/benton', displayLabel: 'Benton County, WA' },
    { slug: 'columbia', name: 'Columbia', seat: 'Dayton', href: '/local-movers/washington/columbia', displayLabel: 'Columbia County, WA' },
    { slug: 'whitman', name: 'Whitman', seat: 'Colfax', href: '/local-movers/washington/whitman', displayLabel: 'Whitman County, WA' },
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
  ],
  stevens: [
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
    { slug: 'ferry', name: 'Ferry', seat: 'Republic', href: '/local-movers/washington/ferry', displayLabel: 'Ferry County, WA' },
    { slug: 'pend-oreille', name: 'Pend Oreille', seat: 'Newport', href: '/local-movers/washington/pend-oreille', displayLabel: 'Pend Oreille County, WA' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'Davenport', href: '/local-movers/washington/lincoln', displayLabel: 'Lincoln County, WA' },
    { slug: 'okanogan', name: 'Okanogan', seat: 'Okanogan', href: '/local-movers/washington/okanogan', displayLabel: 'Okanogan County, WA' },
  ],
  kittitas: [
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'douglas', name: 'Douglas', seat: 'Waterville', href: '/local-movers/washington/douglas', displayLabel: 'Douglas County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
  ],
  whitman: [
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
    { slug: 'asotin', name: 'Asotin', seat: 'Asotin', href: '/local-movers/washington/asotin', displayLabel: 'Asotin County, WA' },
    { slug: 'columbia', name: 'Columbia', seat: 'Dayton', href: '/local-movers/washington/columbia', displayLabel: 'Columbia County, WA' },
    { slug: 'garfield', name: 'Garfield', seat: 'Pomeroy', href: '/local-movers/washington/garfield', displayLabel: 'Garfield County, WA' },
    { slug: 'walla-walla', name: 'Walla Walla', seat: 'Walla Walla', href: '/local-movers/washington/walla-walla', displayLabel: 'Walla Walla County, WA' },
  ],
  douglas: [
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'okanogan', name: 'Okanogan', seat: 'Okanogan', href: '/local-movers/washington/okanogan', displayLabel: 'Okanogan County, WA' },
    { slug: 'kittitas', name: 'Kittitas', seat: 'Ellensburg', href: '/local-movers/washington/kittitas', displayLabel: 'Kittitas County, WA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Pasco', href: '/local-movers/washington/franklin', displayLabel: 'Franklin County, WA' },
  ],
  okanogan: [
    { slug: 'chelan', name: 'Chelan', seat: 'Wenatchee', href: '/local-movers/washington/chelan', displayLabel: 'Chelan County, WA' },
    { slug: 'douglas', name: 'Douglas', seat: 'Waterville', href: '/local-movers/washington/douglas', displayLabel: 'Douglas County, WA' },
    { slug: 'ferry', name: 'Ferry', seat: 'Republic', href: '/local-movers/washington/ferry', displayLabel: 'Ferry County, WA' },
    { slug: 'stevens', name: 'Stevens', seat: 'Colville', href: '/local-movers/washington/stevens', displayLabel: 'Stevens County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
  ],
  jefferson: [
    { slug: 'clallam', name: 'Clallam', seat: 'Port Angeles', href: '/local-movers/washington/clallam', displayLabel: 'Clallam County, WA' },
    { slug: 'kitsap', name: 'Kitsap', seat: 'Port Orchard', href: '/local-movers/washington/kitsap', displayLabel: 'Kitsap County, WA' },
    { slug: 'island', name: 'Island', seat: 'Coupeville', href: '/local-movers/washington/island', displayLabel: 'Island County, WA' },
    { slug: 'mason', name: 'Mason', seat: 'Shelton', href: '/local-movers/washington/mason', displayLabel: 'Mason County, WA' },
    { slug: 'king', name: 'King', seat: 'Seattle', href: '/local-movers/washington/king', displayLabel: 'King County, WA' },
  ],
  klickitat: [
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
    { slug: 'skamania', name: 'Skamania', seat: 'Stevenson', href: '/local-movers/washington/skamania', displayLabel: 'Skamania County, WA' },
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
    { slug: 'benton', name: 'Benton', seat: 'Kennewick', href: '/local-movers/washington/benton', displayLabel: 'Benton County, WA' },
    { slug: 'cowlitz', name: 'Cowlitz', seat: 'Kelso', href: '/local-movers/washington/cowlitz', displayLabel: 'Cowlitz County, WA' },
  ],
  pacific: [
    { slug: 'grays-harbor', name: 'Grays Harbor', seat: 'Montesano', href: '/local-movers/washington/grays-harbor', displayLabel: 'Grays Harbor County, WA' },
    { slug: 'lewis', name: 'Lewis', seat: 'Chehalis', href: '/local-movers/washington/lewis', displayLabel: 'Lewis County, WA' },
    { slug: 'wahkiakum', name: 'Wahkiakum', seat: 'Cathlamet', href: '/local-movers/washington/wahkiakum', displayLabel: 'Wahkiakum County, WA' },
    { slug: 'clallam', name: 'Clallam', seat: 'Port Angeles', href: '/local-movers/washington/clallam', displayLabel: 'Clallam County, WA' },
    { slug: 'cowlitz', name: 'Cowlitz', seat: 'Kelso', href: '/local-movers/washington/cowlitz', displayLabel: 'Cowlitz County, WA' },
  ],
  asotin: [
    { slug: 'garfield', name: 'Garfield', seat: 'Pomeroy', href: '/local-movers/washington/garfield', displayLabel: 'Garfield County, WA' },
    { slug: 'columbia', name: 'Columbia', seat: 'Dayton', href: '/local-movers/washington/columbia', displayLabel: 'Columbia County, WA' },
    { slug: 'whitman', name: 'Whitman', seat: 'Colfax', href: '/local-movers/washington/whitman', displayLabel: 'Whitman County, WA' },
    { slug: 'walla-walla', name: 'Walla Walla', seat: 'Walla Walla', href: '/local-movers/washington/walla-walla', displayLabel: 'Walla Walla County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
  ],
  adams: [
    { slug: 'lincoln', name: 'Lincoln', seat: 'Davenport', href: '/local-movers/washington/lincoln', displayLabel: 'Lincoln County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Pasco', href: '/local-movers/washington/franklin', displayLabel: 'Franklin County, WA' },
    { slug: 'whitman', name: 'Whitman', seat: 'Colfax', href: '/local-movers/washington/whitman', displayLabel: 'Whitman County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
  ],
  'san-juan': [
    { slug: 'island', name: 'Island', seat: 'Coupeville', href: '/local-movers/washington/island', displayLabel: 'Island County, WA' },
    { slug: 'skagit', name: 'Skagit', seat: 'Mount Vernon', href: '/local-movers/washington/skagit', displayLabel: 'Skagit County, WA' },
    { slug: 'whatcom', name: 'Whatcom', seat: 'Bellingham', href: '/local-movers/washington/whatcom', displayLabel: 'Whatcom County, WA' },
    { slug: 'kitsap', name: 'Kitsap', seat: 'Port Orchard', href: '/local-movers/washington/kitsap', displayLabel: 'Kitsap County, WA' },
    { slug: 'snohomish', name: 'Snohomish', seat: 'Everett', href: '/local-movers/washington/snohomish', displayLabel: 'Snohomish County, WA' },
  ],
  'pend-oreille': [
    { slug: 'stevens', name: 'Stevens', seat: 'Colville', href: '/local-movers/washington/stevens', displayLabel: 'Stevens County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
    { slug: 'ferry', name: 'Ferry', seat: 'Republic', href: '/local-movers/washington/ferry', displayLabel: 'Ferry County, WA' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'Davenport', href: '/local-movers/washington/lincoln', displayLabel: 'Lincoln County, WA' },
    { slug: 'okanogan', name: 'Okanogan', seat: 'Okanogan', href: '/local-movers/washington/okanogan', displayLabel: 'Okanogan County, WA' },
  ],
  skamania: [
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
    { slug: 'klickitat', name: 'Klickitat', seat: 'Goldendale', href: '/local-movers/washington/klickitat', displayLabel: 'Klickitat County, WA' },
    { slug: 'cowlitz', name: 'Cowlitz', seat: 'Kelso', href: '/local-movers/washington/cowlitz', displayLabel: 'Cowlitz County, WA' },
    { slug: 'yakima', name: 'Yakima', seat: 'Yakima', href: '/local-movers/washington/yakima', displayLabel: 'Yakima County, WA' },
    { slug: 'lewis', name: 'Lewis', seat: 'Chehalis', href: '/local-movers/washington/lewis', displayLabel: 'Lewis County, WA' },
  ],
  lincoln: [
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
    { slug: 'stevens', name: 'Stevens', seat: 'Colville', href: '/local-movers/washington/stevens', displayLabel: 'Stevens County, WA' },
    { slug: 'adams', name: 'Adams', seat: 'Ritzville', href: '/local-movers/washington/adams', displayLabel: 'Adams County, WA' },
    { slug: 'grant', name: 'Grant', seat: 'Ephrata', href: '/local-movers/washington/grant', displayLabel: 'Grant County, WA' },
    { slug: 'whitman', name: 'Whitman', seat: 'Colfax', href: '/local-movers/washington/whitman', displayLabel: 'Whitman County, WA' },
  ],
  ferry: [
    { slug: 'stevens', name: 'Stevens', seat: 'Colville', href: '/local-movers/washington/stevens', displayLabel: 'Stevens County, WA' },
    { slug: 'okanogan', name: 'Okanogan', seat: 'Okanogan', href: '/local-movers/washington/okanogan', displayLabel: 'Okanogan County, WA' },
    { slug: 'pend-oreille', name: 'Pend Oreille', seat: 'Newport', href: '/local-movers/washington/pend-oreille', displayLabel: 'Pend Oreille County, WA' },
    { slug: 'lincoln', name: 'Lincoln', seat: 'Davenport', href: '/local-movers/washington/lincoln', displayLabel: 'Lincoln County, WA' },
    { slug: 'spokane', name: 'Spokane', seat: 'Spokane', href: '/local-movers/washington/spokane', displayLabel: 'Spokane County, WA' },
  ],
  wahkiakum: [
    { slug: 'cowlitz', name: 'Cowlitz', seat: 'Kelso', href: '/local-movers/washington/cowlitz', displayLabel: 'Cowlitz County, WA' },
    { slug: 'pacific', name: 'Pacific', seat: 'South Bend', href: '/local-movers/washington/pacific', displayLabel: 'Pacific County, WA' },
    { slug: 'lewis', name: 'Lewis', seat: 'Chehalis', href: '/local-movers/washington/lewis', displayLabel: 'Lewis County, WA' },
    { slug: 'clark', name: 'Clark', seat: 'Vancouver', href: '/local-movers/washington/clark', displayLabel: 'Clark County, WA' },
    { slug: 'grays-harbor', name: 'Grays Harbor', seat: 'Montesano', href: '/local-movers/washington/grays-harbor', displayLabel: 'Grays Harbor County, WA' },
  ],
  columbia: [
    { slug: 'walla-walla', name: 'Walla Walla', seat: 'Walla Walla', href: '/local-movers/washington/walla-walla', displayLabel: 'Walla Walla County, WA' },
    { slug: 'whitman', name: 'Whitman', seat: 'Colfax', href: '/local-movers/washington/whitman', displayLabel: 'Whitman County, WA' },
    { slug: 'garfield', name: 'Garfield', seat: 'Pomeroy', href: '/local-movers/washington/garfield', displayLabel: 'Garfield County, WA' },
    { slug: 'asotin', name: 'Asotin', seat: 'Asotin', href: '/local-movers/washington/asotin', displayLabel: 'Asotin County, WA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Pasco', href: '/local-movers/washington/franklin', displayLabel: 'Franklin County, WA' },
  ],
  garfield: [
    { slug: 'asotin', name: 'Asotin', seat: 'Asotin', href: '/local-movers/washington/asotin', displayLabel: 'Asotin County, WA' },
    { slug: 'columbia', name: 'Columbia', seat: 'Dayton', href: '/local-movers/washington/columbia', displayLabel: 'Columbia County, WA' },
    { slug: 'whitman', name: 'Whitman', seat: 'Colfax', href: '/local-movers/washington/whitman', displayLabel: 'Whitman County, WA' },
    { slug: 'walla-walla', name: 'Walla Walla', seat: 'Walla Walla', href: '/local-movers/washington/walla-walla', displayLabel: 'Walla Walla County, WA' },
    { slug: 'franklin', name: 'Franklin', seat: 'Pasco', href: '/local-movers/washington/franklin', displayLabel: 'Franklin County, WA' },
  ],
};

export function getWashingtonNearbyCounties(countySlug: string): NearbyCountyLink[] {
  return WA_COUNTY_NEIGHBORS[countySlug] ?? [];
}