/**
 * Lender market cluster registry — single source for sitemap, catch-all resolver, and future dynamic route.
 */
export const LENDER_CONTENT_CLUSTERS = [
  'south-florida',
  'central-florida',
  'tampa-bay',
  'jacksonville',
  'panhandle',
  'north-atlanta',
  'metro-outer-ring',
  'coastal-savannah',
  'middle-georgia',
  'grand-strand',
  'upstate',
  'lowcountry',
  'charlotte-metro',
  'research-triangle',
  'piedmont-triad',
  'greater-nashville-metro',
  'knoxville-east-tennessee',
  'west-valley-boomtowns',
  'southeast-valley-pinal-border',
  'silicon-valley-spine',
  'inland-empire-affordability-magnets',
  'central-valley-alternatives',
  'denver-metro-outer-rings-north-suburbs',
  'colorado-springs-stability-volume',
  'foothills-turnkey-mountain-towns',
  'dfw-suburbs-silicon-prairie',
  'greater-houston-metro',
  'san-antonio-value-play',
  'spacex-corridor-sleepy-town-booms',
  'snohomish-transit-corridor',
  'south-sound-tacoma-puyallup',
  'southwest-washington-portland-border',
  'high-velocity-mid-city-core',
  'upper-northwest-value-surge',
  'first-time-buyer-waterfront-hubs',
  'high-demand-boston-neighborhoods',
  'gateway-cities-suburban-alternatives',
  'metrowest-bread-and-butter-markets',
  'transit-oriented-urban-hotspots-somerville-cambridge',
  'worcester-undisputed-growth-leader',
  'nyc-boroughs-brooklyn-queens-manhattan',
  'nyc-suburbs-westchester-putnam',
  'upstate-powerhouses-buffalo-albany',
  'philadelphia-metro-area-collar-counties',
  'greater-pittsburgh-key-suburbs',
  'central-eastern-pa-affordability-havens',
  'highly-competitive-chicago-suburbs',
  'chicago-proper-urban-resurgence',
  'central-illinois-affordability-gems',
  'rockford-national-standout',
  'ann-arbor-kalamazoo-college-town-demand',
  'grand-rapids-fast-moving-core',
  'greater-detroits-value-pockets',
  'lansing-multi-family-investor-magnet',
  'national-superstars-suburban-velocity',
  'sweet-spot-commuter-towns',
  'hudson-river-gold-coast',
  'south-jersey-shore-surge',
] as const;

export type LenderClusterSlug = (typeof LENDER_CONTENT_CLUSTERS)[number];

export const LENDER_CLUSTER_STATE: Record<LenderClusterSlug, string> = {
  'south-florida': 'florida',
  'central-florida': 'florida',
  'tampa-bay': 'florida',
  jacksonville: 'florida',
  panhandle: 'florida',
  'north-atlanta': 'georgia',
  'metro-outer-ring': 'georgia',
  'coastal-savannah': 'georgia',
  'middle-georgia': 'georgia',
  'grand-strand': 'south-carolina',
  upstate: 'south-carolina',
  lowcountry: 'south-carolina',
  'charlotte-metro': 'north-carolina',
  'research-triangle': 'north-carolina',
  'piedmont-triad': 'north-carolina',
  'greater-nashville-metro': 'tennessee',
  'knoxville-east-tennessee': 'tennessee',
  'west-valley-boomtowns': 'arizona',
  'southeast-valley-pinal-border': 'arizona',
  'silicon-valley-spine': 'california',
  'inland-empire-affordability-magnets': 'california',
  'central-valley-alternatives': 'california',
  'denver-metro-outer-rings-north-suburbs': 'colorado',
  'colorado-springs-stability-volume': 'colorado',
  'foothills-turnkey-mountain-towns': 'colorado',
  'dfw-suburbs-silicon-prairie': 'texas',
  'greater-houston-metro': 'texas',
  'san-antonio-value-play': 'texas',
  'spacex-corridor-sleepy-town-booms': 'texas',
  'snohomish-transit-corridor': 'washington',
  'south-sound-tacoma-puyallup': 'washington',
  'southwest-washington-portland-border': 'washington',
  'high-velocity-mid-city-core': 'district-of-columbia',
  'upper-northwest-value-surge': 'district-of-columbia',
  'first-time-buyer-waterfront-hubs': 'district-of-columbia',
  'high-demand-boston-neighborhoods': 'massachusetts',
  'gateway-cities-suburban-alternatives': 'massachusetts',
  'metrowest-bread-and-butter-markets': 'massachusetts',
  'transit-oriented-urban-hotspots-somerville-cambridge': 'massachusetts',
  'worcester-undisputed-growth-leader': 'massachusetts',
  'nyc-boroughs-brooklyn-queens-manhattan': 'new-york',
  'nyc-suburbs-westchester-putnam': 'new-york',
  'upstate-powerhouses-buffalo-albany': 'new-york',
  'philadelphia-metro-area-collar-counties': 'pennsylvania',
  'greater-pittsburgh-key-suburbs': 'pennsylvania',
  'central-eastern-pa-affordability-havens': 'pennsylvania',
  'highly-competitive-chicago-suburbs': 'illinois',
  'chicago-proper-urban-resurgence': 'illinois',
  'central-illinois-affordability-gems': 'illinois',
  'rockford-national-standout': 'illinois',
  'ann-arbor-kalamazoo-college-town-demand': 'michigan',
  'grand-rapids-fast-moving-core': 'michigan',
  'greater-detroits-value-pockets': 'michigan',
  'lansing-multi-family-investor-magnet': 'michigan',
  'national-superstars-suburban-velocity': 'new-jersey',
  'sweet-spot-commuter-towns': 'new-jersey',
  'hudson-river-gold-coast': 'new-jersey',
  'south-jersey-shore-surge': 'new-jersey',
};

const CLUSTER_SET = new Set<string>(LENDER_CONTENT_CLUSTERS);

export function isLenderClusterSlug(slug: string): slug is LenderClusterSlug {
  return CLUSTER_SET.has(slug);
}

export function getClusterState(slug: string): string | undefined {
  if (!isLenderClusterSlug(slug)) return undefined;
  return LENDER_CLUSTER_STATE[slug];
}

export function getAllClusterParams(): { state: string; cluster: string }[] {
  return LENDER_CONTENT_CLUSTERS.map((cluster) => ({
    state: LENDER_CLUSTER_STATE[cluster],
    cluster,
  }));
}