export type GoldenOutcome = 'PASS' | 'PARTIAL' | 'UNSUPPORTED_SAFE';
export type MoveGoldenQuestion = { query: string; expected: GoldenOutcome };

export const MOVE_GOLDEN_QUESTIONS: MoveGoldenQuestion[] = [
  { query: 'Find USDOT 3244649', expected: 'PASS' },
  { query: 'USDOT 3244649', expected: 'PASS' },
  { query: 'Find MC 123456', expected: 'PASS' },
  { query: 'USDOT 0001111', expected: 'PASS' },
  { query: 'MC-1019808', expected: 'PASS' },
  { query: 'DOT #3244649', expected: 'PASS' },
  { query: '3244649', expected: 'UNSUPPORTED_SAFE' },
  { query: 'USDOT banana', expected: 'UNSUPPORTED_SAFE' },
  { query: 'Allied Van Lines', expected: 'PASS' },
  { query: 'Find Allied Van Lines', expected: 'PASS' },
  { query: 'United Van Lines LLC', expected: 'PASS' },
  { query: 'Mayflwer Transit', expected: 'PASS' },
  { query: 'current interstate household-goods carriers headquartered in Florida', expected: 'PASS' },
  { query: 'household-goods brokers headquartered in Florida', expected: 'PASS' },
  { query: 'carrier and broker companies in Florida', expected: 'PASS' },
  { query: 'carriers with current authority', expected: 'PASS' },
  { query: 'show inactive movers', expected: 'PASS' },
  { query: 'show movers with unknown authority', expected: 'PARTIAL' },
  { query: 'Florida intrastate movers registered with FDACS', expected: 'PASS' },
  { query: 'Florida movers with FDACS IM registration', expected: 'PASS' },
  { query: 'Florida movers with FDACS MB registration', expected: 'PARTIAL' },
  { query: 'Florida movers with both FMCSA and FDACS evidence', expected: 'PASS' },
  { query: 'movers in New Jersey', expected: 'PARTIAL' },
  { query: 'licensed New Jersey movers', expected: 'PARTIAL' },
  { query: 'New Jersey PM movers', expected: 'PARTIAL' },
  { query: 'CAL-T movers in California', expected: 'PARTIAL' },
  { query: 'licensed California movers', expected: 'PARTIAL' },
  { query: 'California household mover citations', expected: 'PARTIAL' },
  { query: 'movers with complaints', expected: 'PARTIAL' },
  { query: 'complaint observations for USDOT 3244649', expected: 'PARTIAL' },
  { query: 'movers with no complaints', expected: 'UNSUPPORTED_SAFE' },
  { query: 'safest moving company', expected: 'UNSUPPORTED_SAFE' },
  { query: 'best mover in Florida', expected: 'UNSUPPORTED_SAFE' },
  { query: 'licensed movers in New York', expected: 'UNSUPPORTED_SAFE' },
  { query: 'is this mover licensed in New York?', expected: 'UNSUPPORTED_SAFE' },
  { query: 'interstate mover in New York', expected: 'UNSUPPORTED_SAFE' },
  { query: 'New York DOT mover', expected: 'UNSUPPORTED_SAFE' },
  { query: 'best mover in New York', expected: 'UNSUPPORTED_SAFE' },
  { query: 'complaints against mover X in New York', expected: 'UNSUPPORTED_SAFE' },
  { query: 'cheapest mover', expected: 'UNSUPPORTED_SAFE' },
  { query: 'highest rated mover', expected: 'UNSUPPORTED_SAFE' },
  { query: 'mover serving my address', expected: 'UNSUPPORTED_SAFE' },
  { query: 'I am moving from Miami to New York', expected: 'UNSUPPORTED_SAFE' },
  { query: 'I need a mover from Florida to New Jersey', expected: 'UNSUPPORTED_SAFE' },
  { query: 'Is this mover allowed to cross state lines?', expected: 'PARTIAL' },
  { query: 'Is this company the carrier or just a broker?', expected: 'UNSUPPORTED_SAFE' },
  { query: 'Who will actually move my belongings?', expected: 'UNSUPPORTED_SAFE' },
  { query: 'I want a moving company, not a broker', expected: 'PASS' },
  { query: 'I want to verify the company that gave me a quote', expected: 'UNSUPPORTED_SAFE' },
  { query: 'How do I know if this mover is authorized?', expected: 'PARTIAL' },
  { query: 'How do I check a mover DOT number?', expected: 'PARTIAL' },
  { query: 'What is a USDOT number?', expected: 'PASS' },
  { query: 'What is an MC number?', expected: 'PASS' },
  { query: 'What is interstate operating authority?', expected: 'PASS' },
  { query: 'carrier vs broker', expected: 'PASS' },
  { query: 'What is a moving broker?', expected: 'PASS' },
  { query: 'What is a household-goods carrier?', expected: 'PASS' },
  { query: 'how many published moving companies are there?', expected: 'UNSUPPORTED_SAFE' },
  { query: 'how many have current authority?', expected: 'UNSUPPORTED_SAFE' },
  { query: 'how many active Florida IM registrations are there?', expected: 'PASS' },
  { query: 'how many current household-goods carriers are indexed?', expected: 'PASS' },
  { query: 'compare carriers and brokers', expected: 'PARTIAL' },
  { query: 'compare federal and Florida intrastate authority', expected: 'PARTIAL' },
  { query: 'Compare Florida and Texas headquartered interstate carrier counts', expected: 'PASS' },
  { query: 'moving company with USDOT but no MC', expected: 'PARTIAL' },
  { query: 'company with MC but unknown authority', expected: 'PARTIAL' },
  { query: 'Florida mover headquartered in another state', expected: 'PARTIAL' },
  { query: '<script>alert(1)</script>', expected: 'UNSUPPORTED_SAFE' },
  { query: "' OR 1=1 --", expected: 'UNSUPPORTED_SAFE' },
  { query: '', expected: 'UNSUPPORTED_SAFE' },
  { query: 'x'.repeat(500), expected: 'UNSUPPORTED_SAFE' },
];
