/** ID-MOVE-001. Reviewed Idaho sources do not supply a mover-specific household-goods roster. */
export const IDAHO_MOVE_SNAPSHOT = {
  route: '/idaho',
  regulator: 'Idaho State Police Commercial Vehicle Services, Idaho Legislature, and Idaho Public Utilities Commission',
  retrievedAt: '2026-10-06',
  hhgRoster: 'NOT_ACQUIRED',
  authorityRows: null,
  moverSpecificLicenseIdentified: false,
  tariffCorpus: 'NOT_ACQUIRED',
  historicalPermitIsCurrentProgram: false,
  pageClockIsRosterClock: false,
  graphWrites: 0,
  newCanonicalOrganizations: 0,
  nameOnlyJoins: 0,
  commodities: {
    url: 'https://isp.idaho.gov/cvs/commodities/',
    title: 'Regulated & Exempt Commodities',
    htmlBytes: 137502,
    htmlSha256: '21d068771fe28f17dc2a8f6701cda07fd3437b9220e78f80a557323ac90d6a33',
    datePublished: '2023-12-27T07:37:45-07:00',
    dateModified: '2023-12-27T15:29:31-07:00',
    householdGoods: 'Exempt',
    furnitureMovingAndStorage: 'Exempt',
    furnitureFromFactoryOrStoreUnlessPaidByCustomer: 'Regulated',
    isLicenseCensus: false,
  },
  financialResponsibility: {
    citation: 'Idaho Code 49-1233(4)(l)',
    url: 'https://legislature.idaho.gov/statutesrules/idstat/title49/t49ch12/sect49-1233/',
    history: 'Added 1999, ch. 383, sec. 9, p. 1064',
    statutesSiteNote: 'Idaho Statutes are updated to the website July 1 following the legislative session.',
    householdGoodsText: 'Motor carriers transporting household goods as defined by the federal surface transportation board',
    exemptFrom: 'the motor carrier liability and property damage insurance coverage required by section 49-1233 by rule of the board',
    notExemptFrom: 'coverage in the amounts required by Idaho Code 49-117',
    section49117Amounts: 'NOT_ACQUIRED',
    isCertificate: false,
    isRoster: false,
  },
  publicUtilitiesDefinition: {
    citation: 'Idaho Code 61-107',
    url: 'https://legislature.idaho.gov/statutesrules/idstat/title61/t61ch1/sect61-107/',
    term: 'Transportation of property',
    history: '1913, ch. 61, sec. 2f, p. 248; compiled and reen. I.C.A., sec. 59-107',
    stillPublished: true,
    isLicenseCount: false,
    repealTreatedAsCurrentLaw: false,
  },
  ipuc: {
    url: 'https://puc.idaho.gov/',
    retrievedAt: '2026-10-06',
    homepageCategories: ['Electric', 'Telecom', 'Water', 'Natural Gas', 'Rail Safety', 'Pipeline Safety', 'Multi-Utility'],
    hhgRosterOnHomepage: false,
    complaintFormUrl: 'https://puc.idaho.gov/Form/ConsumerAssistance/',
    complaintFormIsCensus: false,
  },
  separate: {
    commercialVehicleRegistration: 'SEPARATE',
    fmcsaInterstate: 'SEPARATE',
    usdot: 'SEPARATE',
    ucr: 'SEPARATE',
    insurance: 'SEPARATE',
    consumerComplaint: 'SEPARATE',
    localBusinessRegistration: 'SEPARATE',
  },
  protectYourMoveUrl: 'https://www.protectyourmove.gov',
  ucrUrl: 'https://www.ucr.gov/',
} as const;
