/** AL-MOVE-001: APSC household-goods authority requirements. No public HHG roster acquired. */
export const ALABAMA_MOVE_SNAPSHOT = {
  regulator: 'Alabama Public Service Commission, Motor Carrier Services',
  motorCarrierUrl: 'https://psc.alabama.gov/motor-carrier-section/',
  applicationsUrl: 'https://psc.alabama.gov/motor-carrier-applications-forms/',
  insuranceUrl: 'https://psc.alabama.gov/insurance-requirements-for-intrastate-authority/',
  annualReportFormUrl: 'https://psc.alabama.gov/wp-content/uploads/2025/12/2025-HHG-Annual-Report.pdf',
  interstateComplaintUrl: 'https://www.fmcsa.dot.gov/protect-your-move/file-a-complaint',
  retrievedAt: '2026-10-05',
  generatedAt: '2026-10-05T16:30:00Z',
  hhgAuthorityVerification: 'KNOWN',
  hhgRoster: 'NOT_ACQUIRED',
  authorityRows: null,
  distinctCertificateNumbers: null,
  rowsWithUsdot: null,
  distinctUsdots: null,
  rowsWithMc: null,
  distinctMcs: null,
  exactFederalBridges: null,
  unmatchedStateRows: null,
  cargoMinimumUsd: 5000,
  propertyCombinedMinimumUsd: 350000,
  brokerSuretyUsd: 10000,
  providerInsuranceStatus: 'NOT_ACQUIRED',
  tariffRequirement: 'KNOWN',
  tariffCorpus: 'NOT_ACQUIRED',
  annualReportFiledRows: 'NOT_ACQUIRED',
  providerComplaintRows: 'NOT_ACQUIRED',
  complaintOutcomes: 'NOT_ACQUIRED',
  enforcementCapability: 'PARTIAL',
  providerEnforcementRows: 'NOT_ACQUIRED',
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
