import type { Lender } from '@/lib/lender/mockData';

export const CALIFORNIA_LENDERS: Lender[] = [
  // ── Santa Clara County (Silicon Valley Spine — San Jose & Cupertino) ─────────
  {
    id: 'ca-01', slug: 'c2-financial-silicon-valley', name: 'C2 Financial Corporation', nmlsId: '135622', type: 'Broker',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95113'], rating: 4.9, reviewCount: 1850, trustScore: 97, countyExperienceScore: 98,
    nationalVolumeRank: 30, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'ARM', 'Refinance'],
    specialties: ['Jumbo & Cash-Heavy Deals', 'Tech Corridor Expertise', 'Multiple-Offer Strategy'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'California independent broker network — deep Silicon Valley expertise for ultra-competitive San Jose and Cupertino transactions.',
    website: 'https://c2financial.com', phone: '(408) 555-9001',
  },
  {
    id: 'ca-02', slug: 'guild-mortgage-silicon-valley', name: 'Guild Mortgage (Silicon Valley)', nmlsId: '3274', type: 'Lender',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95125'], rating: 4.8, reviewCount: 640, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Net-Worth Focus', 'Full Residential', 'Santa Clara Operations'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Silicon Valley presence — sophisticated jumbo and high-value financing for Santa Clara County.',
    website: 'https://guildmortgage.com', phone: '(408) 555-9002',
  },
  {
    id: 'ca-03', slug: 'new-american-funding-san-jose', name: 'New American Funding (San Jose)', nmlsId: '6606', type: 'Lender',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95113', '95014'], rating: 4.9, reviewCount: 520, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech Professionals', 'Above-List Offers', 'High-Volume Service'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF San Jose team — strong support for tech professionals in multiple-offer, above-list Silicon Valley transactions.',
    website: 'https://newamericanfunding.com', phone: '(408) 555-9003',
  },
  {
    id: 'ca-04', slug: 'crosscountry-mortgage-silicon-valley', name: 'CrossCountry Mortgage (Silicon Valley)', nmlsId: '3029', type: 'Lender',
    city: 'Cupertino', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95014', '95110', '95050'], rating: 4.8, reviewCount: 410, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['AI & Semiconductor Buyers', 'Stock-Liquidity Relocations', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Cupertino teams — experienced lending for AI and semiconductor professionals with RSU-driven income.',
    website: 'https://crosscountrymortgage.com', phone: '(408) 555-9004',
  },
  {
    id: 'ca-05', slug: 'pierpoint-mortgage-bay-area', name: 'PierPoint Mortgage (Bay Area)', nmlsId: '112844', type: 'Broker',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95112'], rating: 4.9, reviewCount: 195, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['12–13 Day DOM Market', 'Fast Closings', 'Wholesale Access'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed-critical closings for Santa Clara\'s blistering 12–13 day on-market pace.',
    website: 'https://pierpointmortgage.com', phone: '(408) 555-9005',
  },
  {
    id: 'ca-06', slug: 'silverton-mortgage-san-jose', name: 'Silverton Mortgage — San Jose', nmlsId: '1561', type: 'Lender',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95125', '95014'], rating: 4.8, reviewCount: 165, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech Expertise', 'Constrained Inventory', 'Retail Local Service'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton San Jose retail lending — professional service for constrained-inventory, cash-competitive deals.',
    website: 'https://silvertonmortgage.com', phone: '(408) 555-9006',
  },
  {
    id: 'ca-07', slug: 'city-national-bank-mortgage', name: 'City National Bank Mortgage', nmlsId: '5369', type: 'Bank',
    city: 'Cupertino', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95014', '95110', '95113'], rating: 4.8, reviewCount: 280, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 45, loanTypes: ['Jumbo', 'Conventional', 'ARM', 'Refinance'],
    specialties: ['Portfolio Loans', 'High-Net-Worth', 'Stock Compensation'],
    creditTiers: ['Excellent'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Private bank mortgage arm — jumbo and portfolio lending tailored for generational wealth and stock-comp buyers.',
    website: 'https://cnb.com', phone: '(408) 555-9007',
  },
  {
    id: 'ca-08', slug: 'veterans-united-silicon-valley', name: 'Veterans United Home Loans (Silicon Valley)', nmlsId: '1907', type: 'Lender',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95112'], rating: 4.9, reviewCount: 1100, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 8, loanTypes: ['VA', 'Refinance'],
    specialties: ['VA Loans', 'Executive Relocations', 'Military-Affiliated Tech'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 32, onTimeCloseRate: 94,
    shortDescription: 'VA and executive relocation programs — support for military-affiliated and high-earning tech migrants in Santa Clara.',
    website: 'https://veteransunited.com', phone: '(408) 555-9008',
  },
  {
    id: 'ca-09', slug: 'first-tech-federal-credit-union', name: 'First Tech Federal Credit Union', nmlsId: '732452', type: 'Credit Union',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95125'], rating: 4.9, reviewCount: 720, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 68, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech-Employee CU', 'Member Rates', 'Constrained Supply Market'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Tech-employee credit union — competitive member rates for qualified professionals in ultra-tight Santa Clara inventory.',
    website: 'https://firsttechfed.com', phone: '(855) 855-8805',
  },
  {
    id: 'ca-10', slug: 'jvm-lending-cupertino', name: 'JVM Lending (Cupertino)', nmlsId: '310167', type: 'Lender',
    city: 'Cupertino', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95014', '95110', '95050'], rating: 4.9, reviewCount: 890, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 40, loanTypes: ['Jumbo', 'Conventional', 'ARM', 'Refinance'],
    specialties: ['Premium Estates', 'Non-Contingent Contracts', 'Modern New Builds'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.9, avgCloseDays: 24, onTimeCloseRate: 96,
    shortDescription: 'Bay Area jumbo specialist — expertise in Cupertino luxury, multiple-offer, and non-contingent contract scenarios.',
    website: 'https://jvmlending.com', phone: '(408) 555-9010',
  },
  {
    id: 'ca-11', slug: 'bank-of-america-mortgage-silicon-valley', name: 'Bank of America Mortgage (Silicon Valley)', nmlsId: '399802', type: 'Bank',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95113'], rating: 4.6, reviewCount: 920, trustScore: 89, countyExperienceScore: 91,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Value Financing', 'Corporate Relocation', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 34, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages for corporate relocation packages and high-value San Jose/Cupertino purchases.',
    website: 'https://bankofamerica.com/mortgage', phone: '(408) 555-9011',
  },
  {
    id: 'ca-12', slug: 'bay-equity-home-loans-silicon-valley', name: 'Bay Equity Home Loans (Silicon Valley)', nmlsId: '76901', type: 'Lender',
    city: 'Cupertino', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95014', '95110', '95112'], rating: 4.9, reviewCount: 540, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['65–68% Above-List Dynamics', 'Personalized Brokerage', 'Ultra-Competitive Deals'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'California-based lender — localized expertise in above-list, ultra-competitive Silicon Valley offer dynamics.',
    website: 'https://bayequityhomeloans.com', phone: '(408) 555-9012',
  },

  // ── Riverside County (Inland Empire Affordability Magnets — Riverside & Moreno Valley) ──
  {
    id: 'ca-13', slug: 'american-pacific-mortgage-inland-empire', name: 'American Pacific Mortgage (Inland Empire)', nmlsId: '1850', type: 'Broker',
    city: 'Riverside', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92501', '92503', '92551'], rating: 4.9, reviewCount: 1240, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 28, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Affordable Family Financing', 'Logistics-Worker Buyers', 'SoCal Affordability Valve'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 96,
    shortDescription: 'California independent broker — deep Inland Empire expertise for middle-income families and logistics workers in Riverside and Moreno Valley.',
    website: 'https://apmortgage.com', phone: '(951) 555-9101',
  },
  {
    id: 'ca-14', slug: 'guild-mortgage-inland-empire', name: 'Guild Mortgage (Inland Empire)', nmlsId: '3274', type: 'Lender',
    city: 'Riverside', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92501', '92503', '92553'], rating: 4.8, reviewCount: 580, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'East Inland Presence', 'High-Volume Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Inland Empire branches — comprehensive financing for Riverside County\'s affordability magnet corridor.',
    website: 'https://guildmortgage.com', phone: '(951) 555-9102',
  },
  {
    id: 'ca-15', slug: 'new-american-funding-riverside', name: 'New American Funding (Riverside)', nmlsId: '6606', type: 'Lender',
    city: 'Riverside', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92501', '92503', '92551'], rating: 4.9, reviewCount: 490, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Middle-Income Volume', 'Purchase & Refinance', 'Coastal Spillover Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Riverside team — excellent ratings for high-volume purchase and refinance among middle-income Inland Empire buyers.',
    website: 'https://newamericanfunding.com', phone: '(951) 555-9103',
  },
  {
    id: 'ca-16', slug: 'crosscountry-mortgage-inland-empire', name: 'CrossCountry Mortgage (Inland Empire)', nmlsId: '3029', type: 'Lender',
    city: 'Moreno Valley', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92551', '92553', '92501'], rating: 4.8, reviewCount: 380, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Distribution & Logistics Employees', 'Job-Driven Relocations', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Inland Empire teams — experienced support for distribution and logistics job-driven relocation demand.',
    website: 'https://crosscountrymortgage.com', phone: '(951) 555-9104',
  },
  {
    id: 'ca-17', slug: 'pierpoint-mortgage-inland-empire', name: 'PierPoint Mortgage (Inland Empire)', nmlsId: '112844', type: 'Broker',
    city: 'Moreno Valley', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92551', '92553', '92503'], rating: 4.9, reviewCount: 210, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'High-Transaction Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed and transparency for Riverside County\'s high-transaction affordability market.',
    website: 'https://pierpointmortgage.com', phone: '(951) 555-9105',
  },
  {
    id: 'ca-18', slug: 'silverton-mortgage-riverside', name: 'Silverton Mortgage — Riverside', nmlsId: '1561', type: 'Lender',
    city: 'Riverside', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92501', '92503', '92551'], rating: 4.8, reviewCount: 175, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Local Retail Expertise', 'Compressed Timelines', 'Middle-Income Service'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Riverside retail lending — professional service for compressed-timeline Inland Empire transactions.',
    website: 'https://silvertonmortgage.com', phone: '(951) 555-9106',
  },
  {
    id: 'ca-19', slug: 'veterans-united-inland-empire', name: 'Veterans United Home Loans (Inland Empire)', nmlsId: '1907', type: 'Lender',
    city: 'Moreno Valley', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92551', '92553', '92501'], rating: 4.9, reviewCount: 980, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'First-Time Buyers', 'Military SoCal Migrants'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and entry-level programs — tailored for military-affiliated and middle-income SoCal migrants in the Inland Empire.',
    website: 'https://veteransunited.com', phone: '(951) 555-9107',
  },
  {
    id: 'ca-20', slug: 'altura-credit-union', name: 'Altura Credit Union', nmlsId: '401403', type: 'Credit Union',
    city: 'Riverside', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92501', '92503', '92551'], rating: 4.9, reviewCount: 640, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 72, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Community Lender', 'Affordable Options'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Riverside-area credit union — community-focused member rates for qualified buyers in the high-volume Inland Empire corridor.',
    website: 'https://alturacu.com', phone: '(800) 822-4812',
  },
  {
    id: 'ca-21', slug: 'lennar-mortgage-inland-empire', name: 'Lennar Mortgage (Inland Empire)', nmlsId: '1058', type: 'Lender',
    city: 'Riverside', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92503', '92551', '92553'], rating: 4.7, reviewCount: 420, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned New Homes', 'Distribution-Adjacent Builds', 'Family Housing Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 32, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Riverside and Moreno Valley master-planned communities and logistics-boom housing.',
    website: 'https://lennar.com/mortgage', phone: '(951) 555-9109',
  },
  {
    id: 'ca-22', slug: 'anchor-home-mortgage-moreno-valley', name: 'Anchor Home Mortgage (Moreno Valley)', nmlsId: '136890', type: 'Broker',
    city: 'Moreno Valley', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92551', '92553', '92501'], rating: 4.9, reviewCount: 310, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['$625K–$710K Median Segment', 'Personalized Brokerage', 'Inland Buyer Focus'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on the $625K–$710K median segment for inland family buyers.',
    website: 'https://anchorhomemortgage.com', phone: '(951) 555-9110',
  },
  {
    id: 'ca-23', slug: 'bank-of-america-mortgage-inland-empire', name: 'Bank of America Mortgage (Inland Empire)', nmlsId: '399802', type: 'Bank',
    city: 'Riverside', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92501', '92503', '92551'], rating: 4.6, reviewCount: 780, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Full-Service Banking', 'SoCal Job Migrants'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 33, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for SoCal job relocations and affordability migrants to Riverside County.',
    website: 'https://bankofamerica.com/mortgage', phone: '(951) 555-9111',
  },
  {
    id: 'ca-24', slug: 'nova-home-loans-inland-empire', name: 'Nova Home Loans (Inland Empire)', nmlsId: '3089', type: 'Lender',
    city: 'Riverside', state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside',
    zipCodes: ['92501', '92551', '92553'], rating: 4.8, reviewCount: 450, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Middle-Income Families', 'Massive Transactional Volume'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'California lender — localized knowledge of Inland Empire investor and family financing amid logistics growth.',
    website: 'https://novahomeloans.com', phone: '(951) 555-9112',
  },

  // ── Central Valley Alternatives (Fresno/Clovis & Kern/Bakersfield) ───────────
  {
    id: 'ca-25', slug: 'american-pacific-mortgage-central-valley', name: 'American Pacific Mortgage (Central Valley)', nmlsId: '1850', type: 'Broker',
    city: 'Clovis', state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno',
    zipCodes: ['93611', '93612', '93720'], rating: 4.9, reviewCount: 890, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 28, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Affordable Family Financing', 'Cash-Flow Investors', 'Suburban Clovis Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 96,
    shortDescription: 'California independent broker — deep Central Valley expertise for affordable family and positive cash-flow investor financing in Clovis.',
    website: 'https://apmortgage.com', phone: '(559) 555-9201',
  },
  {
    id: 'ca-26', slug: 'guild-mortgage-central-valley', name: 'Guild Mortgage (Central Valley)', nmlsId: '3274', type: 'Lender',
    city: 'Clovis', state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno',
    zipCodes: ['93611', '93619', '93710'], rating: 4.8, reviewCount: 420, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Remote Worker Relocations', 'Central Valley Branches'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Central Valley branches — comprehensive financing for Clovis suburban buyers and coastal migrants.',
    website: 'https://guildmortgage.com', phone: '(559) 555-9202',
  },
  {
    id: 'ca-27', slug: 'new-american-funding-clovis', name: 'New American Funding (Clovis)', nmlsId: '6606', type: 'Lender',
    city: 'Clovis', state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno',
    zipCodes: ['93611', '93612', '93720'], rating: 4.9, reviewCount: 380, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Remote Worker Volume', 'First-Time Buyers', 'Purchase & Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Clovis team — excellent ratings for remote worker and first-time buyer volume in elite-school suburbs.',
    website: 'https://newamericanfunding.com', phone: '(559) 555-9203',
  },
  {
    id: 'ca-28', slug: 'pierpoint-mortgage-central-valley', name: 'PierPoint Mortgage (Central Valley)', nmlsId: '112844', type: 'Broker',
    city: 'Clovis', state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno',
    zipCodes: ['93611', '93619', '93710'], rating: 4.9, reviewCount: 165, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['$400K–$430K Medians', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed and transparency for Central Valley\'s $400K–$430K median purchase market.',
    website: 'https://pierpointmortgage.com', phone: '(559) 555-9205',
  },
  {
    id: 'ca-29', slug: 'eecu-fresno', name: 'Educational Employees Credit Union (EECU)', nmlsId: '402788', type: 'Credit Union',
    city: 'Fresno', state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno',
    zipCodes: ['93710', '93611', '93612'], rating: 4.9, reviewCount: 520, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 74, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Community Lender', 'Cash-Flow Investor Options'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Fresno-area credit union — community-focused member rates for qualified buyers and investor cash-flow properties.',
    website: 'https://eecu.org', phone: '(800) 538-3328',
  },
  {
    id: 'ca-30', slug: 'lennar-mortgage-clovis', name: 'Lennar Mortgage (Clovis)', nmlsId: '1058', type: 'Lender',
    city: 'Clovis', state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno',
    zipCodes: ['93619', '93611', '93720'], rating: 4.7, reviewCount: 310, trustScore: 89, countyExperienceScore: 91,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned Suburbs', 'Family Suburban Financing', 'Elite School Districts'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 31, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Clovis master-planned communities and premium low-crime suburban layouts.',
    website: 'https://lennar.com/mortgage', phone: '(559) 555-9209',
  },
  {
    id: 'ca-31', slug: 'crosscountry-mortgage-central-valley', name: 'CrossCountry Mortgage (Central Valley)', nmlsId: '3029', type: 'Lender',
    city: 'Bakersfield', state: 'California', stateSlug: 'california', county: 'Kern', countySlug: 'kern',
    zipCodes: ['93301', '93309', '93311'], rating: 4.8, reviewCount: 340, trustScore: 90, countyExperienceScore: 91,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Bay Area/LA Relocators', 'Cost-of-Living Migration', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Bakersfield teams — experienced support for coastal California cost-of-living migration.',
    website: 'https://crosscountrymortgage.com', phone: '(661) 555-9204',
  },
  {
    id: 'ca-32', slug: 'silverton-mortgage-bakersfield', name: 'Silverton Mortgage — Bakersfield', nmlsId: '1561', type: 'Lender',
    city: 'Bakersfield', state: 'California', stateSlug: 'california', county: 'Kern', countySlug: 'kern',
    zipCodes: ['93301', '93309', '93311'], rating: 4.8, reviewCount: 155, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Agricultural Heartland', 'Local Retail Expertise', 'Affordability Focus'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Bakersfield retail lending — professional service for agricultural heartland and affordability buyers.',
    website: 'https://silvertonmortgage.com', phone: '(661) 555-9206',
  },
  {
    id: 'ca-33', slug: 'veterans-united-central-valley', name: 'Veterans United Home Loans (Central Valley)', nmlsId: '1907', type: 'Lender',
    city: 'Bakersfield', state: 'California', stateSlug: 'california', county: 'Kern', countySlug: 'kern',
    zipCodes: ['93301', '93311', '93611'], rating: 4.9, reviewCount: 860, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Remote Worker Programs', 'Veterans & Military'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and remote relocation programs — tailored for veterans and tech remote workers in the Central Valley.',
    website: 'https://veteransunited.com', phone: '(661) 555-9207',
  },
  {
    id: 'ca-34', slug: 'anchor-home-mortgage-bakersfield', name: 'Anchor Home Mortgage (Bakersfield)', nmlsId: '136890', type: 'Broker',
    city: 'Bakersfield', state: 'California', stateSlug: 'california', county: 'Kern', countySlug: 'kern',
    zipCodes: ['93301', '93309', '93311'], rating: 4.9, reviewCount: 275, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Affordability Focus', 'Investor Cash Flow', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Central Valley affordability and positive cash-flow investor deals.',
    website: 'https://anchorhomemortgage.com', phone: '(661) 555-9210',
  },
  {
    id: 'ca-35', slug: 'bank-of-america-mortgage-central-valley', name: 'Bank of America Mortgage (Central Valley)', nmlsId: '399802', type: 'Bank',
    city: 'Clovis', state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno',
    zipCodes: ['93611', '93301', '93710'], rating: 4.6, reviewCount: 640, trustScore: 87, countyExperienceScore: 89,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Full-Service Banking', 'Bay Area/LA Migrants'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for Bay Area and LA relocators seeking Central Valley affordability.',
    website: 'https://bankofamerica.com/mortgage', phone: '(559) 555-9211',
  },
  {
    id: 'ca-36', slug: 'nova-home-loans-central-valley', name: 'Nova Home Loans (Central Valley)', nmlsId: '3089', type: 'Lender',
    city: 'Bakersfield', state: 'California', stateSlug: 'california', county: 'Kern', countySlug: 'kern',
    zipCodes: ['93301', '93309', '93611'], rating: 4.8, reviewCount: 390, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'First-Time Buyers', 'Traditional Suburban Appeal'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'California lender — localized knowledge of Central Valley investor and first-time buyer financing at half state median prices.',
    website: 'https://novahomeloans.com', phone: '(661) 555-9212',
  },
];

export const SILICON_VALLEY_LENDER_SLUGS = [
  'c2-financial-silicon-valley',
  'guild-mortgage-silicon-valley',
  'new-american-funding-san-jose',
  'crosscountry-mortgage-silicon-valley',
  'pierpoint-mortgage-bay-area',
  'silverton-mortgage-san-jose',
  'city-national-bank-mortgage',
  'veterans-united-silicon-valley',
  'first-tech-federal-credit-union',
  'jvm-lending-cupertino',
  'bank-of-america-mortgage-silicon-valley',
  'bay-equity-home-loans-silicon-valley',
] as const;

export const INLAND_EMPIRE_LENDER_SLUGS = [
  'american-pacific-mortgage-inland-empire',
  'guild-mortgage-inland-empire',
  'new-american-funding-riverside',
  'crosscountry-mortgage-inland-empire',
  'pierpoint-mortgage-inland-empire',
  'silverton-mortgage-riverside',
  'veterans-united-inland-empire',
  'altura-credit-union',
  'lennar-mortgage-inland-empire',
  'anchor-home-mortgage-moreno-valley',
  'bank-of-america-mortgage-inland-empire',
  'nova-home-loans-inland-empire',
] as const;

export const CENTRAL_VALLEY_LENDER_SLUGS = [
  'american-pacific-mortgage-central-valley',
  'guild-mortgage-central-valley',
  'new-american-funding-clovis',
  'pierpoint-mortgage-central-valley',
  'eecu-fresno',
  'lennar-mortgage-clovis',
  'crosscountry-mortgage-central-valley',
  'silverton-mortgage-bakersfield',
  'veterans-united-central-valley',
  'anchor-home-mortgage-bakersfield',
  'bank-of-america-mortgage-central-valley',
  'nova-home-loans-central-valley',
] as const;

const FRESNO_SUPPLEMENTS = [
  'crosscountry-mortgage-central-valley',
  'silverton-mortgage-bakersfield',
  'veterans-united-central-valley',
  'anchor-home-mortgage-bakersfield',
  'nova-home-loans-central-valley',
];

const KERN_SUPPLEMENTS = [
  'american-pacific-mortgage-central-valley',
  'guild-mortgage-central-valley',
  'new-american-funding-clovis',
  'pierpoint-mortgage-central-valley',
  'eecu-fresno',
  'lennar-mortgage-clovis',
  'bank-of-america-mortgage-central-valley',
];

export const CALIFORNIA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  'santa-clara': [],
  'riverside': [],
  'fresno': FRESNO_SUPPLEMENTS,
  'kern': KERN_SUPPLEMENTS,
};

export const SILICON_VALLEY_HUB_AREAS = [
  { name: 'San Jose', slug: 'santa-clara', highlight: 'AI corridor, $1.5M+ medians, 12-day DOM' },
  { name: 'Cupertino', slug: 'santa-clara', highlight: 'Semiconductor hub, premium estates' },
  { name: 'Sunnyvale', slug: 'santa-clara', highlight: 'Tech campuses — coming soon' },
  { name: 'Palo Alto', slug: 'santa-clara', highlight: 'Venture capital corridor — coming soon' },
] as const;

export const INLAND_EMPIRE_HUB_AREAS = [
  { name: 'Riverside', slug: 'riverside', highlight: 'Logistics hub, $625K median, coastal spillover' },
  { name: 'Moreno Valley', slug: 'riverside', highlight: 'Distribution boom, master-planned growth' },
  { name: 'Corona', slug: 'riverside', highlight: 'Family housing corridor — coming soon' },
  { name: 'Temecula', slug: 'riverside', highlight: 'Wine country suburbs — coming soon' },
] as const;

export const CENTRAL_VALLEY_HUB_COUNTIES = [
  { name: 'Fresno', slug: 'fresno', highlight: 'Clovis suburbs, elite schools, $400K–$430K medians' },
  { name: 'Kern', slug: 'kern', highlight: 'Bakersfield affordability, ag heartland, cash flow' },
] as const;