import type { Lender } from '@/lib/lender/mockData';

export const ILLINOIS_LENDERS: Lender[] = [
  // ── Rockford National Standout (Winnebago County) ────────────────────────────
  {
    id: 'il-01', slug: 'local-rockford-independent-mortgage', name: 'Local Rockford Independent Mortgage', nmlsId: '512891', type: 'Broker',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61104', '61107'], rating: 4.9, reviewCount: 720, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 28, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Out-of-Town Buyers', 'First-Time Financing', 'Zillow #1 US Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'Local Rockford independent — strong knowledge of the #1 most popular U.S. market and 11-day median contracts.',
    website: 'https://rockfordindependentmortgage.com', phone: '(815) 555-4101',
  },
  {
    id: 'il-02', slug: 'guild-mortgage-rockford', name: 'Guild Mortgage (Rockford)', nmlsId: '3274', type: 'Lender',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61103', '61108'], rating: 4.8, reviewCount: 480, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Winnebago County', 'Hot Market Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Rockford branches — financing for Chicago spillover and intense Winnebago demand.',
    website: 'https://guildmortgage.com', phone: '(815) 555-4102',
  },
  {
    id: 'il-03', slug: 'new-american-funding-rockford', name: 'New American Funding (Rockford)', nmlsId: '6606', type: 'Lender',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61104', '61109'], rating: 4.9, reviewCount: 420, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', '11-Day Median Contracts', 'Above-List Sales'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'NAF Rockford team — excellent ratings for 11-day median contracts and nearly 50% above-list sales.',
    website: 'https://newamericanfunding.com', phone: '(815) 555-4103',
  },
  {
    id: 'il-04', slug: 'crosscountry-mortgage-northern-illinois-rockford', name: 'CrossCountry Mortgage (Northern IL)', nmlsId: '3029', type: 'Lender',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61107', '61103'], rating: 4.8, reviewCount: 360, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Chicago Spillover Buyers', '60%+ Out-of-Town Views', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Northern IL — experienced support for Chicago-priced-out buyers in Rockford.',
    website: 'https://crosscountrymortgage.com', phone: '(815) 555-4104',
  },
  {
    id: 'il-05', slug: 'pierpoint-mortgage-rockford', name: 'PierPoint Mortgage (Northern IL)', nmlsId: '112844', type: 'Broker',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61104', '61108'], rating: 4.9, reviewCount: 175, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Nearly 50% Above List'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 17, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to nearly 50% above-list sales in Zillow\'s #1 market.',
    website: 'https://pierpointmortgage.com', phone: '(815) 555-4105',
  },
  {
    id: 'il-06', slug: 'silverton-mortgage-rockford', name: 'Silverton Mortgage — Rockford', nmlsId: '1561', type: 'Lender',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61103', '61107'], rating: 4.8, reviewCount: 158, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Intense Demand Market', 'Retail Local Expertise', 'Accessible Entry Point'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'Silverton Rockford retail lending — professional service for national standout demand.',
    website: 'https://silvertonmortgage.com', phone: '(815) 555-4106',
  },
  {
    id: 'il-07', slug: 'veterans-relocation-mortgage-rockford', name: 'Veterans & Relocation Specialists (Rockford)', nmlsId: '523827', type: 'Broker',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61104', '61109'], rating: 4.9, reviewCount: 510, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['VA Loan Programs', 'Out-of-State Relocation', 'Chicago Metro Spillover'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'VA and relocation specialist — tailored for out-of-town shoppers in Zillow\'s #1 market.',
    website: 'https://rockfordrelocationmortgage.com', phone: '(815) 555-4107',
  },
  {
    id: 'il-08', slug: 'winnebago-community-credit-union-rockford', name: 'Winnebago Community Credit Union', nmlsId: '549102', type: 'Credit Union',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61107', '61108'], rating: 4.9, reviewCount: 840, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 56, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Affordable Options', 'Community-Focused Lending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates in Winnebago County\'s national hotspot.',
    website: 'https://winnebagocu.org', phone: '(815) 555-4108',
  },
  {
    id: 'il-09', slug: 'new-construction-mortgage-rockford', name: 'New Construction & Suburban Specialists (Rockford)', nmlsId: '571293', type: 'Broker',
    city: 'Loves Park', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61111', '61101', '61104'], rating: 4.9, reviewCount: 290, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Build Financing', 'Suburban Entry Point', 'Single-Family Homes'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'New construction specialist — accessible single-family homes for Rockford entry-point buyers.',
    website: 'https://rockfordnewbuildmortgage.com', phone: '(815) 555-4109',
  },
  {
    id: 'il-10', slug: 'anchor-home-mortgage-rockford', name: 'Anchor Home Mortgage (Rockford)', nmlsId: '136890', type: 'Broker',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61103', '61107'], rating: 4.9, reviewCount: 265, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['11-Day Median Under Contract', 'Personalized Brokerage', 'Rockford Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Rockford\'s 11-day median under contract velocity.',
    website: 'https://anchorhomemortgage.com', phone: '(815) 555-4110',
  },
  {
    id: 'il-11', slug: 'bank-of-america-mortgage-rockford', name: 'Bank of America Mortgage (Rockford)', nmlsId: '399802', type: 'Bank',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61104', '61108'], rating: 4.6, reviewCount: 560, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Out-of-Town Shoppers', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for out-of-town shoppers in Rockford.',
    website: 'https://bankofamerica.com/mortgage', phone: '(815) 555-4111',
  },
  {
    id: 'il-12', slug: 'nova-home-loans-rockford', name: 'Nova Home Loans (Rockford Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Rockford', state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago',
    zipCodes: ['61101', '61107', '61109'], rating: 4.8, reviewCount: 275, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Zillow #1 Ranking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 23, onTimeCloseRate: 94,
    shortDescription: 'Rockford lender — localized knowledge of intense demand in the national standout market.',
    website: 'https://novahomeloans.com', phone: '(815) 555-4112',
  },

  // ── Highly Competitive Chicago Suburbs (DuPage, Cook & Lake) ───────────────
  {
    id: 'il-13', slug: 'local-chicago-suburb-independent-mortgage', name: 'Local Chicago Suburb Independent Mortgage', nmlsId: '482891', type: 'Broker',
    city: 'Wheaton', state: 'Illinois', stateSlug: 'illinois', county: 'DuPage', countySlug: 'dupage',
    zipCodes: ['60187', '60137', '60515'], rating: 4.9, reviewCount: 810, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 30, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bidding War Financing', 'Top-School Districts', '102.2% Sale-to-List'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Local Chicago suburb independent — strong knowledge of Wheaton 102.2% sale-to-list and 60%+ above-list sales.',
    website: 'https://chicagosuburbindependentmortgage.com', phone: '(630) 555-4213',
  },
  {
    id: 'il-14', slug: 'guild-mortgage-chicago-suburbs', name: 'Guild Mortgage (Chicago Suburbs)', nmlsId: '3274', type: 'Lender',
    city: 'Wheaton', state: 'Illinois', stateSlug: 'illinois', county: 'DuPage', countySlug: 'dupage',
    zipCodes: ['60187', '60137', '60540'], rating: 4.8, reviewCount: 510, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'DuPage County Operations', 'Competitive Suburban Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Wheaton branches — comprehensive financing across DuPage collar counties.',
    website: 'https://guildmortgage.com', phone: '(630) 555-4214',
  },
  {
    id: 'il-15', slug: 'new-american-funding-chicago-west-north', name: 'New American Funding (Chicago West/North)', nmlsId: '6606', type: 'Lender',
    city: 'Glen Ellyn', state: 'Illinois', stateSlug: 'illinois', county: 'DuPage', countySlug: 'dupage',
    zipCodes: ['60137', '60187', '60515'], rating: 4.9, reviewCount: 455, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Wheaton / Glen Ellyn', 'Above-List Sales'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'NAF Glen Ellyn team — excellent ratings for competitive suburban markets with 60%+ above-list sales.',
    website: 'https://newamericanfunding.com', phone: '(630) 555-4215',
  },
  {
    id: 'il-16', slug: 'crosscountry-mortgage-chicago-suburbs', name: 'CrossCountry Mortgage (Chicago Suburbs)', nmlsId: '3029', type: 'Lender',
    city: 'Mount Prospect', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60056', '60302', '60004'], rating: 4.8, reviewCount: 385, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Mount Prospect / Oak Park', 'Immediate Bidding Wars', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Mount Prospect teams — experienced support for 41–44 day market times and bidding wars.',
    website: 'https://crosscountrymortgage.com', phone: '(630) 555-4216',
  },
  {
    id: 'il-17', slug: 'pierpoint-mortgage-chicago-metro-suburbs', name: 'PierPoint Mortgage (Chicago Metro)', nmlsId: '112844', type: 'Broker',
    city: 'Evanston', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60201', '60004', '60056'], rating: 4.9, reviewCount: 190, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Evanston / Arlington Heights', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to 41–44 day suburban market times and low 2-month inventory.',
    website: 'https://pierpointmortgage.com', phone: '(630) 555-4217',
  },
  {
    id: 'il-18', slug: 'silverton-mortgage-chicago-suburbs', name: 'Silverton Mortgage — Chicago Suburbs', nmlsId: '1561', type: 'Lender',
    city: 'Oak Park', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60302', '60187', '60137'], rating: 4.8, reviewCount: 165, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Wheaton / Oak Park', 'Top-School Districts', 'Retail Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Silverton Oak Park retail lending — professional service for well-established school district demand.',
    website: 'https://silvertonmortgage.com', phone: '(630) 555-4218',
  },
  {
    id: 'il-19', slug: 'family-school-specialists-glen-ellyn-arlington-heights', name: 'Family & Top-School Specialists (Glen Ellyn / Arlington Heights)', nmlsId: '493827', type: 'Broker',
    city: 'Arlington Heights', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60004', '60137', '60187'], rating: 4.9, reviewCount: 530, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['School-District Programs', 'Aggressive Bidding', 'Premium Suburbs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'School-district specialist — tailored for aggressive bidding in Glen Ellyn and Arlington Heights.',
    website: 'https://chicagosuburbschoolmortgage.com', phone: '(630) 555-4219',
  },
  {
    id: 'il-20', slug: 'chicago-suburb-community-credit-union', name: 'Chicago Suburb Community Credit Union', nmlsId: '479102', type: 'Credit Union',
    city: 'Glen Ellyn', state: 'Illinois', stateSlug: 'illinois', county: 'DuPage', countySlug: 'dupage',
    zipCodes: ['60137', '60187', '60515'], rating: 4.9, reviewCount: 870, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Suburban Buyers', 'Low-Inventory Areas'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for suburban buyers in low-inventory collar counties.',
    website: 'https://chicagosuburbcu.org', phone: '(630) 555-4220',
  },
  {
    id: 'il-21', slug: 'single-family-suburban-specialists-mount-prospect-wheaton', name: 'Single-Family Suburban Specialists (Mount Prospect / Wheaton)', nmlsId: '501293', type: 'Broker',
    city: 'Mount Prospect', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60056', '60187', '60004'], rating: 4.9, reviewCount: 305, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 37, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Move-In-Ready Single-Family', 'Over-Asking Sales', '2-Month Inventory'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'Single-family specialist — expertise in over-asking sales and tight suburban inventory.',
    website: 'https://mountprospectsuburbanmortgage.com', phone: '(630) 555-4221',
  },
  {
    id: 'il-22', slug: 'anchor-home-mortgage-chicago-suburbs', name: 'Anchor Home Mortgage (Chicago Suburbs)', nmlsId: '136890', type: 'Broker',
    city: 'Evanston', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60201', '60302', '60004'], rating: 4.9, reviewCount: 280, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['50%+ Above List', '102.2% Sale-to-List', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on 50%+ above-list and 102.2% sale-to-list suburban dynamics.',
    website: 'https://anchorhomemortgage.com', phone: '(630) 555-4222',
  },
  {
    id: 'il-23', slug: 'bank-of-america-mortgage-chicago-suburbs', name: 'Bank of America Mortgage (Chicago Suburbs)', nmlsId: '399802', type: 'Bank',
    city: 'Arlington Heights', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60004', '60137', '60187'], rating: 4.6, reviewCount: 620, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Suburban Relocation', 'Top Schools', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for families seeking top suburban school districts.',
    website: 'https://bankofamerica.com/mortgage', phone: '(630) 555-4223',
  },
  {
    id: 'il-24', slug: 'nova-home-loans-chicago-suburbs', name: 'Nova Home Loans (Chicago Suburb Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Lake Forest', state: 'Illinois', stateSlug: 'illinois', county: 'Lake', countySlug: 'lake',
    zipCodes: ['60045', '60056', '60187'], rating: 4.8, reviewCount: 290, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Breakneck Suburban Pace'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 94,
    shortDescription: 'Chicago suburb lender — localized knowledge of breakneck pace and seller control in collar counties.',
    website: 'https://novahomeloans.com', phone: '(630) 555-4224',
  },

  // ── Chicago Proper Urban Resurgence (Cook County) ──────────────────────────
  {
    id: 'il-25', slug: 'local-chicago-neighborhood-independent-mortgage', name: 'Local Chicago Neighborhood Independent Mortgage', nmlsId: '492891', type: 'Broker',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60614', '60622', '60647'], rating: 4.9, reviewCount: 740, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 28, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Urban Rowhome Financing', 'Multiple-Offer Scenarios', 'Calendar-Driven Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 96,
    shortDescription: 'Local Chicago neighborhood independent — strong knowledge of 48-hour bidding wars in Lincoln Park and West Town.',
    website: 'https://chicagoneighborhoodmortgage.com', phone: '(312) 555-4325',
  },
  {
    id: 'il-26', slug: 'guild-mortgage-chicago-proper', name: 'Guild Mortgage (Chicago)', nmlsId: '3274', type: 'Lender',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60614', '60657', '60647'], rating: 4.8, reviewCount: 495, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Cook County Operations', 'Urban Bidding-War Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Chicago branches — comprehensive financing for urban resurgence neighborhoods.',
    website: 'https://guildmortgage.com', phone: '(312) 555-4326',
  },
  {
    id: 'il-27', slug: 'new-american-funding-chicago-proper', name: 'New American Funding (Chicago)', nmlsId: '6606', type: 'Lender',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60614', '60647', '60622'], rating: 4.9, reviewCount: 440, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Lincoln Park / Logan Square', 'High-Volume Urban Purchase', 'Competitive Neighborhoods'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'NAF Chicago team — excellent ratings for competitive neighborhood transactions and multiple offers.',
    website: 'https://newamericanfunding.com', phone: '(312) 555-4327',
  },
  {
    id: 'il-28', slug: 'crosscountry-mortgage-chicago-proper', name: 'CrossCountry Mortgage (Chicago)', nmlsId: '3029', type: 'Lender',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60622', '60657', '60614'], rating: 4.8, reviewCount: 370, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['West Town / Roscoe Village', 'School-Year Deadline Buyers', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Chicago teams — experienced support for calendar-driven families before school year starts.',
    website: 'https://crosscountrymortgage.com', phone: '(312) 555-4328',
  },
  {
    id: 'il-29', slug: 'pierpoint-mortgage-chicago-proper', name: 'PierPoint Mortgage (Chicago)', nmlsId: '112844', type: 'Broker',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60614', '60622', '60657'], rating: 4.9, reviewCount: 180, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Lincoln Park / West Town', 'Fast Closings', '48-Hour Bidding Wars'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 17, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to 48-hour bidding wars in high-competition urban neighborhoods.',
    website: 'https://pierpointmortgage.com', phone: '(312) 555-4329',
  },
  {
    id: 'il-30', slug: 'silverton-mortgage-chicago-proper', name: 'Silverton Mortgage — Chicago Proper', nmlsId: '1561', type: 'Lender',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60647', '60657', '60622'], rating: 4.8, reviewCount: 160, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Logan Square / Roscoe Village', 'Urban Resurgence', 'Retail Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Silverton Chicago retail lending — professional service for urban resurgence and rent-vs-own flip.',
    website: 'https://silvertonmortgage.com', phone: '(312) 555-4330',
  },
  {
    id: 'il-31', slug: 'family-school-age-buyer-specialists-chicago', name: 'Family & School-Age Buyer Specialists (Chicago)', nmlsId: '503827', type: 'Broker',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60614', '60657', '60647'], rating: 4.9, reviewCount: 520, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Calendar-Driven Families', 'Pandemic Stayers', 'School Deadlines'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Family specialist — tailored for pandemic-stayers with hard school-year deadlines in the city.',
    website: 'https://chicagoschoolagemortgage.com', phone: '(312) 555-4331',
  },
  {
    id: 'il-32', slug: 'chicago-proper-community-credit-union', name: 'Chicago Proper Community Credit Union', nmlsId: '489102', type: 'Credit Union',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60614', '60622', '60657'], rating: 4.9, reviewCount: 850, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Chicago Proper Buyers', 'High-Competition Neighborhoods'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for Chicago proper buyers in bidding-war neighborhoods.',
    website: 'https://chicagopropercu.org', phone: '(312) 555-4332',
  },
  {
    id: 'il-33', slug: 'historic-rowhome-condo-specialists-west-town-logan-square', name: 'Historic Rowhome & Condo Specialists (West Town / Logan Square)', nmlsId: '511293', type: 'Broker',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60622', '60647', '60614'], rating: 4.9, reviewCount: 300, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 37, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Renovated Urban Properties', 'Rent-vs-Own Math', 'Rowhome / Condo'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'Historic rowhome specialist — expertise in rising rental-to-own economics in West Town and Logan Square.',
    website: 'https://chicagorowhomemortgage.com', phone: '(312) 555-4333',
  },
  {
    id: 'il-34', slug: 'anchor-home-mortgage-chicago-proper', name: 'Anchor Home Mortgage (Chicago Proper)', nmlsId: '136890', type: 'Broker',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60614', '60622', '60657'], rating: 4.9, reviewCount: 270, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bidding Wars', 'Multiple Offers', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on bidding wars and multiple offers within 48 hours.',
    website: 'https://anchorhomemortgage.com', phone: '(312) 555-4334',
  },
  {
    id: 'il-35', slug: 'bank-of-america-mortgage-chicago-proper', name: 'Bank of America Mortgage (Chicago Proper)', nmlsId: '399802', type: 'Bank',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60647', '60657', '60614'], rating: 4.6, reviewCount: 580, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Urban Financing', 'School-Year Buyers', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for families securing properties before school year starts.',
    website: 'https://bankofamerica.com/mortgage', phone: '(312) 555-4335',
  },
  {
    id: 'il-36', slug: 'nova-home-loans-chicago-proper', name: 'Nova Home Loans (Chicago Proper Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Chicago', state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook',
    zipCodes: ['60657', '60622', '60647'], rating: 4.8, reviewCount: 285, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Rent-vs-Own Economics'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 23, onTimeCloseRate: 94,
    shortDescription: 'Chicago proper lender — localized knowledge of flipped rent-vs-own economics in resurgence areas.',
    website: 'https://novahomeloans.com', phone: '(312) 555-4336',
  },

  // ── Central Illinois Affordability Gems (Peoria & McLean) ──────────────────
  {
    id: 'il-37', slug: 'local-central-illinois-independent-mortgage', name: 'Local Central Illinois Independent Mortgage', nmlsId: '472891', type: 'Broker',
    city: 'Peoria', state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria',
    zipCodes: ['61602', '61614', '61615'], rating: 4.9, reviewCount: 560, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Rent-to-Price', 'University Town Financing', 'High-Value Low Entry'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Local Central IL independent — strong knowledge of Peoria investment appeal and exceptional rent-to-price ratios.',
    website: 'https://centralilindependentmortgage.com', phone: '(309) 555-4437',
  },
  {
    id: 'il-38', slug: 'guild-mortgage-central-illinois', name: 'Guild Mortgage (Central IL)', nmlsId: '3274', type: 'Lender',
    city: 'Peoria', state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria',
    zipCodes: ['61602', '61614', '61604'], rating: 4.8, reviewCount: 400, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Peoria / Normal Operations', 'Affordability Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Peoria branches — comprehensive financing for Central Illinois value hotspots.',
    website: 'https://guildmortgage.com', phone: '(309) 555-4438',
  },
  {
    id: 'il-39', slug: 'new-american-funding-peoria', name: 'New American Funding (Peoria)', nmlsId: '6606', type: 'Lender',
    city: 'Peoria', state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria',
    zipCodes: ['61602', '61615', '61614'], rating: 4.9, reviewCount: 380, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Fast-Moving Investment', '20–26 Day DOM'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 96,
    shortDescription: 'NAF Peoria team — excellent ratings for fast-moving investment properties and rapid sales velocity.',
    website: 'https://newamericanfunding.com', phone: '(309) 555-4439',
  },
  {
    id: 'il-40', slug: 'crosscountry-mortgage-central-illinois', name: 'CrossCountry Mortgage (Central IL)', nmlsId: '3029', type: 'Lender',
    city: 'Normal', state: 'Illinois', stateSlug: 'illinois', county: 'McLean', countySlug: 'mclean',
    zipCodes: ['61761', '61602', '61704'], rating: 4.8, reviewCount: 340, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Normal / Peoria', 'Investors & Families', 'Rent-to-Price Ratios'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Central IL — experienced support for exceptional rent-to-price ratios in Peoria and Normal.',
    website: 'https://crosscountrymortgage.com', phone: '(309) 555-4540',
  },
  {
    id: 'il-41', slug: 'pierpoint-mortgage-central-illinois', name: 'PierPoint Mortgage (Central IL)', nmlsId: '112844', type: 'Broker',
    city: 'Peoria', state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria',
    zipCodes: ['61602', '61614', '61761'], rating: 4.9, reviewCount: 170, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Peoria / Normal', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 17, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to 20–26 day median DOM in Central Illinois affordability gems.',
    website: 'https://pierpointmortgage.com', phone: '(309) 555-4441',
  },
  {
    id: 'il-42', slug: 'silverton-mortgage-central-illinois', name: 'Silverton Mortgage — Central IL', nmlsId: '1561', type: 'Lender',
    city: 'Normal', state: 'Illinois', stateSlug: 'illinois', county: 'McLean', countySlug: 'mclean',
    zipCodes: ['61761', '61704', '61602'], rating: 4.8, reviewCount: 150, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Revitalized Uptown', 'University Demand', 'Retail Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'Silverton Normal retail lending — professional service for Zillow #1 college town demand.',
    website: 'https://silvertonmortgage.com', phone: '(309) 555-4542',
  },
  {
    id: 'il-43', slug: 'investor-rental-specialists-peoria', name: 'Investor & Rental Specialists (Peoria)', nmlsId: '483827', type: 'Broker',
    city: 'Peoria', state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria',
    zipCodes: ['61602', '61614', '61615'], rating: 4.9, reviewCount: 480, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Cash-Flow Programs', 'Multi-Unit Financing', 'Top Midsize Investment City'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Investor specialist — tailored for Peoria as a top midsize city for real estate investment.',
    website: 'https://peoriainvestormortgage.com', phone: '(309) 555-4443',
  },
  {
    id: 'il-44', slug: 'central-illinois-community-credit-union', name: 'Central Illinois Community Credit Union', nmlsId: '469102', type: 'Credit Union',
    city: 'Peoria', state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria',
    zipCodes: ['61602', '61614', '61604'], rating: 4.9, reviewCount: 790, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Central IL Buyers', 'Affordability Gems'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for Central Illinois buyers in high-value markets.',
    website: 'https://centralilcu.org', phone: '(309) 555-4444',
  },
  {
    id: 'il-45', slug: 'university-town-specialists-normal', name: 'University Town Specialists (Normal)', nmlsId: '491293', type: 'Broker',
    city: 'Normal', state: 'Illinois', stateSlug: 'illinois', county: 'McLean', countySlug: 'mclean',
    zipCodes: ['61761', '61704', '61701'], rating: 4.9, reviewCount: 310, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Student/Professional Housing', '#1 College Town', 'Revitalized Uptown'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'University town specialist — expertise in Zillow\'s #1 most popular college town and strong rental demand.',
    website: 'https://normaluniversitymortgage.com', phone: '(309) 555-4545',
  },
  {
    id: 'il-46', slug: 'anchor-home-mortgage-central-illinois', name: 'Anchor Home Mortgage (Central IL)', nmlsId: '136890', type: 'Broker',
    city: 'Peoria', state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria',
    zipCodes: ['61602', '61614', '61615'], rating: 4.9, reviewCount: 255, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Low Entry Costs', 'High Value', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on low entry costs and high value in Central Illinois.',
    website: 'https://anchorhomemortgage.com', phone: '(309) 555-4446',
  },
  {
    id: 'il-47', slug: 'bank-of-america-mortgage-central-illinois', name: 'Bank of America Mortgage (Central IL)', nmlsId: '399802', type: 'Bank',
    city: 'Normal', state: 'Illinois', stateSlug: 'illinois', county: 'McLean', countySlug: 'mclean',
    zipCodes: ['61761', '61704', '61602'], rating: 4.6, reviewCount: 540, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investment Financing', 'Family Financing', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 29, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for local rental demand in Peoria and Normal.',
    website: 'https://bankofamerica.com/mortgage', phone: '(309) 555-4547',
  },
  {
    id: 'il-48', slug: 'nova-home-loans-central-illinois', name: 'Nova Home Loans (Central IL Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Peoria', state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria',
    zipCodes: ['61602', '61614', '61761'], rating: 4.8, reviewCount: 265, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'First-Time Buyers', 'Fast-Moving Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 94,
    shortDescription: 'Central IL lender — localized knowledge of fast-moving and revitalized affordability markets.',
    website: 'https://novahomeloans.com', phone: '(309) 555-4448',
  },
];

export const ROCKFORD_NATIONAL_STANDOUT_LENDER_SLUGS = [
  'local-rockford-independent-mortgage',
  'guild-mortgage-rockford',
  'new-american-funding-rockford',
  'crosscountry-mortgage-northern-illinois-rockford',
  'pierpoint-mortgage-rockford',
  'silverton-mortgage-rockford',
  'veterans-relocation-mortgage-rockford',
  'winnebago-community-credit-union-rockford',
  'new-construction-mortgage-rockford',
  'anchor-home-mortgage-rockford',
  'bank-of-america-mortgage-rockford',
  'nova-home-loans-rockford',
] as const;

export const HIGHLY_COMPETITIVE_CHICAGO_SUBURBS_LENDER_SLUGS = [
  'local-chicago-suburb-independent-mortgage',
  'guild-mortgage-chicago-suburbs',
  'new-american-funding-chicago-west-north',
  'crosscountry-mortgage-chicago-suburbs',
  'pierpoint-mortgage-chicago-metro-suburbs',
  'silverton-mortgage-chicago-suburbs',
  'family-school-specialists-glen-ellyn-arlington-heights',
  'chicago-suburb-community-credit-union',
  'single-family-suburban-specialists-mount-prospect-wheaton',
  'anchor-home-mortgage-chicago-suburbs',
  'bank-of-america-mortgage-chicago-suburbs',
  'nova-home-loans-chicago-suburbs',
] as const;

export const CHICAGO_PROPER_URBAN_RESURGENCE_LENDER_SLUGS = [
  'local-chicago-neighborhood-independent-mortgage',
  'guild-mortgage-chicago-proper',
  'new-american-funding-chicago-proper',
  'crosscountry-mortgage-chicago-proper',
  'pierpoint-mortgage-chicago-proper',
  'silverton-mortgage-chicago-proper',
  'family-school-age-buyer-specialists-chicago',
  'chicago-proper-community-credit-union',
  'historic-rowhome-condo-specialists-west-town-logan-square',
  'anchor-home-mortgage-chicago-proper',
  'bank-of-america-mortgage-chicago-proper',
  'nova-home-loans-chicago-proper',
] as const;

export const CENTRAL_ILLINOIS_AFFORDABILITY_GEMS_LENDER_SLUGS = [
  'local-central-illinois-independent-mortgage',
  'guild-mortgage-central-illinois',
  'new-american-funding-peoria',
  'crosscountry-mortgage-central-illinois',
  'pierpoint-mortgage-central-illinois',
  'silverton-mortgage-central-illinois',
  'investor-rental-specialists-peoria',
  'central-illinois-community-credit-union',
  'university-town-specialists-normal',
  'anchor-home-mortgage-central-illinois',
  'bank-of-america-mortgage-central-illinois',
  'nova-home-loans-central-illinois',
] as const;

const CHICAGO_SUBURBS_DUPAGE_SUPPLEMENTS = [
  'crosscountry-mortgage-chicago-suburbs',
  'pierpoint-mortgage-chicago-metro-suburbs',
  'silverton-mortgage-chicago-suburbs',
  'family-school-specialists-glen-ellyn-arlington-heights',
  'single-family-suburban-specialists-mount-prospect-wheaton',
  'anchor-home-mortgage-chicago-suburbs',
  'bank-of-america-mortgage-chicago-suburbs',
  'nova-home-loans-chicago-suburbs',
];

const CHICAGO_SUBURBS_COOK_SUPPLEMENTS = [
  'local-chicago-suburb-independent-mortgage',
  'guild-mortgage-chicago-suburbs',
  'new-american-funding-chicago-west-north',
  'chicago-suburb-community-credit-union',
  'nova-home-loans-chicago-suburbs',
  'local-chicago-neighborhood-independent-mortgage',
  'guild-mortgage-chicago-proper',
  'new-american-funding-chicago-proper',
  'crosscountry-mortgage-chicago-proper',
  'pierpoint-mortgage-chicago-proper',
  'family-school-age-buyer-specialists-chicago',
  'anchor-home-mortgage-chicago-proper',
];

const CHICAGO_SUBURBS_LAKE_SUPPLEMENTS = [
  'local-chicago-suburb-independent-mortgage',
  'guild-mortgage-chicago-suburbs',
  'new-american-funding-chicago-west-north',
  'crosscountry-mortgage-chicago-suburbs',
  'pierpoint-mortgage-chicago-metro-suburbs',
  'silverton-mortgage-chicago-suburbs',
  'family-school-specialists-glen-ellyn-arlington-heights',
  'chicago-suburb-community-credit-union',
  'single-family-suburban-specialists-mount-prospect-wheaton',
  'anchor-home-mortgage-chicago-suburbs',
  'bank-of-america-mortgage-chicago-suburbs',
];

const CENTRAL_IL_PEORIA_SUPPLEMENTS = [
  'crosscountry-mortgage-central-illinois',
  'silverton-mortgage-central-illinois',
  'university-town-specialists-normal',
  'bank-of-america-mortgage-central-illinois',
];

const CENTRAL_IL_MCLEAN_SUPPLEMENTS = [
  'local-central-illinois-independent-mortgage',
  'guild-mortgage-central-illinois',
  'new-american-funding-peoria',
  'pierpoint-mortgage-central-illinois',
  'investor-rental-specialists-peoria',
  'central-illinois-community-credit-union',
  'anchor-home-mortgage-central-illinois',
  'nova-home-loans-central-illinois',
];

export const ILLINOIS_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  winnebago: [],
  dupage: CHICAGO_SUBURBS_DUPAGE_SUPPLEMENTS,
  cook: CHICAGO_SUBURBS_COOK_SUPPLEMENTS,
  lake: CHICAGO_SUBURBS_LAKE_SUPPLEMENTS,
  peoria: CENTRAL_IL_PEORIA_SUPPLEMENTS,
  mclean: CENTRAL_IL_MCLEAN_SUPPLEMENTS,
};

export const ROCKFORD_NATIONAL_STANDOUT_HUB_AREAS = [
  { name: 'Rockford', slug: 'winnebago', highlight: 'Zillow #1 US market, 11-day median contracts' },
  { name: 'Winnebago County', slug: 'winnebago', highlight: '60%+ out-of-town views, 50% above list' },
  { name: 'Loves Park', slug: 'winnebago', highlight: 'Accessible entry point, Chicago spillover' },
  { name: 'Northern IL Corridor', slug: 'winnebago', highlight: 'National standout affordability magnet' },
] as const;

export const HIGHLY_COMPETITIVE_CHICAGO_SUBURBS_HUB_AREAS = [
  { name: 'Wheaton', slug: 'dupage', highlight: '102.2% sale-to-list, 60%+ above list' },
  { name: 'Glen Ellyn', slug: 'dupage', highlight: 'Top-school district bidding wars' },
  { name: 'Mount Prospect / Oak Park', slug: 'cook', highlight: '41–44 day market times, over-asking sales' },
  { name: 'Evanston / Arlington Heights', slug: 'cook', highlight: '2-month supply, 50%+ above list' },
] as const;

export const CHICAGO_PROPER_URBAN_RESURGENCE_HUB_AREAS = [
  { name: 'Lincoln Park', slug: 'cook', highlight: '48-hour bidding wars, school-age families' },
  { name: 'West Town', slug: 'cook', highlight: 'Historic rowhomes, rent-vs-own flip' },
  { name: 'Logan Square', slug: 'cook', highlight: 'Urban resurgence, multiple offers' },
  { name: 'Roscoe Village', slug: 'cook', highlight: 'Calendar-driven buyers, competitive premiums' },
] as const;

export const CENTRAL_ILLINOIS_AFFORDABILITY_GEMS_HUB_AREAS = [
  { name: 'Peoria', slug: 'peoria', highlight: 'Top midsize investment city, 20–26 day DOM' },
  { name: 'Normal', slug: 'mclean', highlight: 'Zillow #1 college town, revitalized uptown' },
  { name: 'McLean County', slug: 'mclean', highlight: 'University-driven rental demand' },
  { name: 'Peoria County', slug: 'peoria', highlight: 'Exceptional rent-to-price ratios' },
] as const;