import type { Lender } from '@/lib/lender/mockData';

export const MASSACHUSETTS_LENDERS: Lender[] = [
  // ── Undisputed Growth Leader (Worcester — Zip 01608) ─────────────────────────
  {
    id: 'ma-01', slug: 'central-mass-independent-mortgage-worcester', name: 'Local Worcester Independent Mortgage', nmlsId: '284719', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 640, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['First-Time Buyer Programs', 'Life Sciences Relocations', 'Zoom Town & Downtown Revitalization'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Local Worcester independent — strong knowledge of Zoom Town dynamics, downtown revitalization, and life sciences relocation financing.',
    website: 'https://centralmassmortgage.com', phone: '(508) 555-2101',
  },
  {
    id: 'ma-02', slug: 'guild-mortgage-worcester', name: 'Guild Mortgage (Worcester)', nmlsId: '3274', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 410, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'First-Time & Investor Growth', 'Worcester County Operations'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Worcester branches — comprehensive financing for first-time buyers and investors in one of the country\'s hottest markets.',
    website: 'https://guildmortgage.com', phone: '(508) 555-2102',
  },
  {
    id: 'ma-03', slug: 'new-american-funding-worcester', name: 'New American Funding (Worcester)', nmlsId: '6606', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 375, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Commuter Rail Corridor', 'Investor Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Worcester team — excellent ratings for commuter rail corridor buyers and investor demand in fast-moving Worcester County.',
    website: 'https://newamericanfunding.com', phone: '(508) 555-2103',
  },
  {
    id: 'ma-04', slug: 'crosscountry-mortgage-worcester', name: 'CrossCountry Mortgage (Central MA)', nmlsId: '3029', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 320, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Life Sciences Sector', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Central MA teams — experienced support for first-time buyers in Worcester\'s booming life sciences sector.',
    website: 'https://crosscountrymortgage.com', phone: '(508) 555-2104',
  },
  {
    id: 'ma-05', slug: 'pierpoint-mortgage-worcester', name: 'PierPoint Mortgage (Central MA)', nmlsId: '112844', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 155, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Exceptionally Fast-Moving Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Worcester\'s exceptionally fast-moving first-time buyer market.',
    website: 'https://pierpointmortgage.com', phone: '(508) 555-2105',
  },
  {
    id: 'ma-06', slug: 'silverton-mortgage-worcester', name: 'Silverton Mortgage — Worcester', nmlsId: '1561', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 142, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Polar Park Corridor', 'Downtown Revitalization', 'Retail Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Worcester retail lending — professional service for Polar Park and downtown revitalization areas.',
    website: 'https://silvertonmortgage.com', phone: '(508) 555-2106',
  },
  {
    id: 'ma-07', slug: 'young-professional-investor-mortgage-worcester', name: 'Young Professional & Investor Specialists (Worcester)', nmlsId: '518392', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 480, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Remote Worker Programs', 'Life Sciences Professionals', 'Zoom Town Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Young professional and investor specialist — tailored for Zoom Town remote workers and life sciences professionals seeking Worcester affordability.',
    website: 'https://centralmayoungprofmortgage.com', phone: '(508) 555-2107',
  },
  {
    id: 'ma-08', slug: 'dcu-worcester', name: 'Digital Federal Credit Union (Worcester)', nmlsId: '414078', type: 'Credit Union',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.9, reviewCount: 860, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'First-Time Buyer Options', 'Worcester County CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates and first-time buyer options in high-growth Worcester County.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-09', slug: 'downtown-new-construction-mortgage-worcester', name: 'New Construction & Downtown Specialists (Worcester)', nmlsId: '367284', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Downtown Revitalization', 'New-Build Financing', 'Commuter Rail Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'New construction and downtown specialist — expertise in revitalization investments and commuter rail-access properties.',
    website: 'https://worcesterdowntownmortgage.com', phone: '(508) 555-2109',
  },
  {
    id: 'ma-10', slug: 'anchor-home-mortgage-worcester', name: 'Anchor Home Mortgage (Worcester)', nmlsId: '136890', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.9, reviewCount: 230, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Brokerage', 'Central MA Buyers', 'Greater Boston Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on relative affordability vs. Greater Boston for Central MA buyers.',
    website: 'https://anchorhomemortgage.com', phone: '(508) 555-2110',
  },
  {
    id: 'ma-11', slug: 'bank-of-america-mortgage-worcester', name: 'Bank of America Mortgage (Worcester)', nmlsId: '399802', type: 'Bank',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.6, reviewCount: 520, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Relocation Financing', 'Life Sciences Influx', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for life sciences and remote worker relocations to Worcester County.',
    website: 'https://bankofamerica.com/mortgage', phone: '(508) 555-2111',
  },
  {
    id: 'ma-12', slug: 'nova-home-loans-worcester', name: 'Nova Home Loans (Worcester Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 255, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'First-Time Buyer Programs', 'Hottest Market Velocity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Worcester lender — localized knowledge of one of the country\'s hottest markets for investors and first-time buyers.',
    website: 'https://novahomeloans.com', phone: '(508) 555-2112',
  },

  // ── Transit-Oriented Urban Hotspots (Somerville & Cambridge — Middlesex) ──────
  {
    id: 'ma-13', slug: 'local-cambridge-somerville-independent-mortgage', name: 'Local Cambridge/Somerville Independent Mortgage', nmlsId: '392847', type: 'Broker',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02143', '02144'], rating: 4.9, reviewCount: 720, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech/Biotech Financing', 'Transit-Oriented Urban', 'Green Line Extension Impact'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local Cambridge/Somerville independent — strong knowledge of Green Line extension impact and tech/biotech transit-oriented financing.',
    website: 'https://cambridgesomervillemortgage.com', phone: '(617) 555-2201',
  },
  {
    id: 'ma-14', slug: 'guild-mortgage-cambridge-somerville', name: 'Guild Mortgage (Cambridge/Somerville)', nmlsId: '3274', type: 'Lender',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02140', '02143'], rating: 4.8, reviewCount: 465, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Middlesex County Operations', 'Transit & Tech Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Cambridge and Somerville branches — comprehensive financing for tech/biotech professionals and transit-oriented urban properties.',
    website: 'https://guildmortgage.com', phone: '(617) 555-2202',
  },
  {
    id: 'ma-15', slug: 'new-american-funding-cambridge-somerville', name: 'New American Funding (Cambridge)', nmlsId: '6606', type: 'Lender',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02142', '02144'], rating: 4.9, reviewCount: 420, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Premium Urban Transactions', 'Cambridge/Somerville Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'NAF Cambridge team — excellent ratings for premium urban purchase and refinance in fierce-demand transit corridors.',
    website: 'https://newamericanfunding.com', phone: '(617) 555-2203',
  },
  {
    id: 'ma-16', slug: 'crosscountry-mortgage-cambridge-somerville', name: 'CrossCountry Mortgage (Greater Boston)', nmlsId: '3029', type: 'Lender',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02145', '02139'], rating: 4.8, reviewCount: 380, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech/Biotech Professionals', 'Higher Education Corridors', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Greater Boston teams — experienced support for tech/biotech and higher education professionals in Somerville and Cambridge.',
    website: 'https://crosscountrymortgage.com', phone: '(617) 555-2204',
  },
  {
    id: 'ma-17', slug: 'pierpoint-mortgage-cambridge-somerville', name: 'PierPoint Mortgage (Boston Metro)', nmlsId: '112844', type: 'Broker',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02143', '02144'], rating: 4.9, reviewCount: 195, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Transit-Adjacent Properties', 'Fast Closings', 'Fierce Premium Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to fierce demand and premium pricing on transit-adjacent Cambridge and Somerville properties.',
    website: 'https://pierpointmortgage.com', phone: '(617) 555-2205',
  },
  {
    id: 'ma-18', slug: 'silverton-mortgage-cambridge-somerville', name: 'Silverton Mortgage — Somerville/Cambridge', nmlsId: '1561', type: 'Lender',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02145', '02140'], rating: 4.8, reviewCount: 168, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Green Line Neighborhoods', 'Retail Local Expertise', 'Somerville Area'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Silverton Somerville retail lending — professional service for neighborhoods near Green Line extension corridors.',
    website: 'https://silvertonmortgage.com', phone: '(617) 555-2206',
  },
  {
    id: 'ma-19', slug: 'young-professional-biotech-mortgage-cambridge', name: 'Young Professional & Biotech Specialists (Cambridge)', nmlsId: '528194', type: 'Broker',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02142', '02143'], rating: 4.9, reviewCount: 510, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Modern Condo Programs', 'Urban Rowhome Financing', 'High-Earning Tech Transplants'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Young professional and biotech specialist — tailored for high-earning tech/biotech transplants seeking Cambridge and Somerville urban cores.',
    website: 'https://biotechurbanmortgage.com', phone: '(617) 555-2207',
  },
  {
    id: 'ma-20', slug: 'dcu-cambridge-somerville', name: 'Digital Federal Credit Union (Cambridge/Somerville)', nmlsId: '414078', type: 'Credit Union',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02138', '02139'], rating: 4.9, reviewCount: 920, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Member Rates', 'Urban Professional Programs', 'Middlesex County CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates for urban professionals in high-velocity Cambridge and Somerville hotspots.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-21', slug: 'green-line-transit-mortgage-cambridge-somerville', name: 'Green Line Transit Specialists (Somerville/Cambridge)', nmlsId: '384721', type: 'Broker',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02145', '02139'], rating: 4.9, reviewCount: 340, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Green Line Extension', 'Transit Station Proximity', 'Continuously Driven-Up Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'Transit-oriented specialist — expertise in properties near new Green Line stations and continuously driven-up demand areas.',
    website: 'https://greenlinetransitmortgage.com', phone: '(617) 555-2209',
  },
  {
    id: 'ma-22', slug: 'anchor-home-mortgage-cambridge-somerville', name: 'Anchor Home Mortgage (Cambridge/Somerville)', nmlsId: '136890', type: 'Broker',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02143', '02144'], rating: 4.9, reviewCount: 265, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Personalized Brokerage', '$930K+ Somerville Medians', '$1M+ Cambridge Medians'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on premium urban financing for $930K+ Somerville and $1M+ Cambridge median markets.',
    website: 'https://anchorhomemortgage.com', phone: '(617) 555-2210',
  },
  {
    id: 'ma-23', slug: 'bank-of-america-mortgage-cambridge-somerville', name: 'Bank of America Mortgage (Cambridge/Somerville)', nmlsId: '399802', type: 'Bank',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02142', '02143'], rating: 4.6, reviewCount: 680, trustScore: 89, countyExperienceScore: 91,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Professional Relocation Financing', 'Biotech Job Growth', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for biotech and higher education professional relocations to Cambridge and Somerville.',
    website: 'https://bankofamerica.com/mortgage', phone: '(617) 555-2211',
  },
  {
    id: 'ma-24', slug: 'nova-home-loans-cambridge-somerville', name: 'Nova Home Loans (Somerville/Cambridge Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02138', '02139'], rating: 4.8, reviewCount: 310, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Premium Urban Properties', 'Transit-Oriented Hotspots'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 94,
    shortDescription: 'Middlesex lender — localized knowledge of perennially hot transit-oriented Cambridge and Somerville investor markets.',
    website: 'https://novahomeloans.com', phone: '(617) 555-2212',
  },

  // ── High-Demand Boston Neighborhoods (East Boston, Dorchester & Jamaica Plain) ──
  {
    id: 'ma-25', slug: 'local-boston-neighborhood-independent-mortgage', name: 'Local Boston Neighborhood Independent Mortgage', nmlsId: '401283', type: 'Broker',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02128', '02121', '02130'], rating: 4.9, reviewCount: 680, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Waterfront Financing', 'Cultural District Properties', 'Rental-Yield Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local Boston neighborhood independent — strong knowledge of high-competition dynamics in East Boston, Dorchester, and Jamaica Plain.',
    website: 'https://bostonneighborhoodmortgage.com', phone: '(617) 555-2301',
  },
  {
    id: 'ma-26', slug: 'guild-mortgage-boston-neighborhoods', name: 'Guild Mortgage (Boston Neighborhoods)', nmlsId: '3274', type: 'Lender',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02128', '02122', '02130'], rating: 4.8, reviewCount: 490, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Suffolk County Operations', 'Full Residential Spectrum', 'Waterfront & Cultural Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Boston branches — waterfront proximity in East Boston and cultural properties in Dorchester and Jamaica Plain.',
    website: 'https://guildmortgage.com', phone: '(617) 555-2302',
  },
  {
    id: 'ma-27', slug: 'new-american-funding-boston-neighborhoods', name: 'New American Funding (Boston)', nmlsId: '6606', type: 'Lender',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02128', '02124', '02125'], rating: 4.9, reviewCount: 435, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Waterfront Districts', 'East Boston / Dorchester'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Boston team — excellent ratings for waterfront East Boston and cultural Dorchester transactions.',
    website: 'https://newamericanfunding.com', phone: '(617) 555-2303',
  },
  {
    id: 'ma-28', slug: 'crosscountry-mortgage-boston-neighborhoods', name: 'CrossCountry Mortgage (Boston)', nmlsId: '3029', type: 'Lender',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02130', '02121', '02122'], rating: 4.8, reviewCount: 365, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Jamaica Plain / Dorchester', 'Space & Culture', 'Rental Yield Support'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Boston teams — experienced support for Jamaica Plain and Dorchester space, culture, and rental yields.',
    website: 'https://crosscountrymortgage.com', phone: '(617) 555-2304',
  },
  {
    id: 'ma-29', slug: 'pierpoint-mortgage-boston-neighborhoods', name: 'PierPoint Mortgage (Boston)', nmlsId: '112844', type: 'Broker',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02128', '02130', '02124'], rating: 4.9, reviewCount: 185, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['East Boston / Jamaica Plain', 'Fast Closings', 'Competitive Neighborhoods'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to rapid appreciation and high demand in East Boston and Jamaica Plain.',
    website: 'https://pierpointmortgage.com', phone: '(617) 555-2305',
  },
  {
    id: 'ma-30', slug: 'silverton-mortgage-boston-neighborhoods', name: 'Silverton Mortgage — Dorchester/Jamaica Plain', nmlsId: '1561', type: 'Lender',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02121', '02130', '02122'], rating: 4.8, reviewCount: 155, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Mixed-Use Properties', 'Cultural Areas', 'Retail Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Boston retail lending — professional service for mixed-use and cultural Dorchester and Jamaica Plain areas.',
    website: 'https://silvertonmortgage.com', phone: '(617) 555-2306',
  },
  {
    id: 'ma-31', slug: 'waterfront-first-time-mortgage-east-boston', name: 'Waterfront & First-Time Buyer Specialists (East Boston)', nmlsId: '419572', type: 'Broker',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02128', '02129', '02130'], rating: 4.9, reviewCount: 420, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 41, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Waterfront Proximity', 'Entry-Level Programs', 'Back Bay Alternatives'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'Waterfront specialist — tailored for buyers seeking East Boston proximity without Back Bay pricing.',
    website: 'https://eastbostonwaterfrontmortgage.com', phone: '(617) 555-2307',
  },
  {
    id: 'ma-32', slug: 'dcu-boston-neighborhoods', name: 'Digital Federal Credit Union (Boston Neighborhoods)', nmlsId: '414078', type: 'Credit Union',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02128', '02121', '02130'], rating: 4.9, reviewCount: 880, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Suffolk County CU', 'High-Value Neighborhood Pockets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates for high-demand Boston neighborhood buyers.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-33', slug: 'historic-rental-yield-mortgage-boston', name: 'Historic & Rental-Yield Specialists (Dorchester/JP)', nmlsId: '378194', type: 'Broker',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02121', '02130', '02122'], rating: 4.9, reviewCount: 305, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 39, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Rowhome Financing', 'Investment Properties', 'Neighborhood Culture'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Historic and rental-yield specialist — expertise in Dorchester and Jamaica Plain rowhomes and strong rental yields.',
    website: 'https://rentalyieldmortgageboston.com', phone: '(617) 555-2309',
  },
  {
    id: 'ma-34', slug: 'anchor-home-mortgage-boston-neighborhoods', name: 'Anchor Home Mortgage (East Boston / Jamaica Plain)', nmlsId: '136890', type: 'Broker',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02128', '02130', '02124'], rating: 4.9, reviewCount: 245, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Waterfront & Space', 'Personalized Brokerage', 'Competitive Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on waterfront East Boston and spacious Jamaica Plain in competitive markets.',
    website: 'https://anchorhomemortgage.com', phone: '(617) 555-2310',
  },
  {
    id: 'ma-35', slug: 'bank-of-america-mortgage-boston-neighborhoods', name: 'Bank of America Mortgage (Dorchester / East Boston)', nmlsId: '399802', type: 'Bank',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02121', '02128', '02122'], rating: 4.6, reviewCount: 640, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Neighborhood Financing', 'Cultural District Programs', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for local culture and appreciation plays in Dorchester and East Boston.',
    website: 'https://bankofamerica.com/mortgage', phone: '(617) 555-2311',
  },
  {
    id: 'ma-36', slug: 'nova-home-loans-boston-neighborhoods', name: 'Nova Home Loans (Boston Neighborhood Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Boston', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02130', '02128', '02125'], rating: 4.8, reviewCount: 290, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Neighborhood Programs', 'High-Demand Areas'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Boston lender — localized knowledge of cooled luxury segments vs. high-competition Jamaica Plain and East Boston neighborhoods.',
    website: 'https://novahomeloans.com', phone: '(617) 555-2312',
  },

  // ── Gateway Cities & Suburban Alternatives (Lowell, Lynn, Revere & Malden) ───
  {
    id: 'ma-37', slug: 'local-gateway-cities-independent-mortgage', name: 'Local Gateway Cities Independent Mortgage', nmlsId: '412847', type: 'Broker',
    city: 'Lowell', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01852', '01901', '02148'], rating: 4.9, reviewCount: 590, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Transit-Oriented Financing', 'Boston Spillover Affordability', 'Gateway City Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Local gateway cities independent — strong knowledge of Boston-priced-out spillover into Lowell, Lynn, Revere, and Malden.',
    website: 'https://gatewaycitiesmortgage.com', phone: '(781) 555-2401',
  },
  {
    id: 'ma-38', slug: 'guild-mortgage-gateway-cities', name: 'Guild Mortgage (North Suburban & Gateway)', nmlsId: '3274', type: 'Lender',
    city: 'Lynn', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Essex', countySlug: 'essex',
    zipCodes: ['01901', '01852', '02151'], rating: 4.8, reviewCount: 455, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Essex/Middlesex Gateway', 'Transit & Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with gateway city branches — comprehensive financing for transit-oriented buyers priced out of Boston proper.',
    website: 'https://guildmortgage.com', phone: '(781) 555-2402',
  },
  {
    id: 'ma-39', slug: 'new-american-funding-gateway-cities', name: 'New American Funding (North of Boston)', nmlsId: '6606', type: 'Lender',
    city: 'Lowell', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01852', '01902', '02148'], rating: 4.9, reviewCount: 400, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Lowell / Lynn', 'Commuter Transit Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF North of Boston team — excellent ratings for Lowell and Lynn commuter transit buyers.',
    website: 'https://newamericanfunding.com', phone: '(781) 555-2403',
  },
  {
    id: 'ma-40', slug: 'crosscountry-mortgage-gateway-cities', name: 'CrossCountry Mortgage (North Shore)', nmlsId: '3029', type: 'Lender',
    city: 'Lynn', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Essex', countySlug: 'essex',
    zipCodes: ['01901', '02151', '02148'], rating: 4.8, reviewCount: 340, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Revere / Malden', 'Orange/Blue Line Access', 'T-Line Commuters'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry North Shore teams — experienced support for Revere and Malden Orange/Blue Line commuters.',
    website: 'https://crosscountrymortgage.com', phone: '(781) 555-2404',
  },
  {
    id: 'ma-41', slug: 'pierpoint-mortgage-gateway-cities', name: 'PierPoint Mortgage (Greater Boston North)', nmlsId: '112844', type: 'Broker',
    city: 'Lynn', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Essex', countySlug: 'essex',
    zipCodes: ['01901', '01852', '01904'], rating: 4.9, reviewCount: 170, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Lowell / Lynn', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to sharp rises in competitiveness in Lowell and Lynn gateway markets.',
    website: 'https://pierpointmortgage.com', phone: '(781) 555-2405',
  },
  {
    id: 'ma-42', slug: 'silverton-mortgage-gateway-cities', name: 'Silverton Mortgage — Lynn/Revere', nmlsId: '1561', type: 'Lender',
    city: 'Revere', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02151', '01902', '01904'], rating: 4.8, reviewCount: 148, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Urban Amenities', 'Lower-Cost Alternatives', 'Retail Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Lynn/Revere retail lending — professional service for urban amenities at lower cost than Boston proper.',
    website: 'https://silvertonmortgage.com', phone: '(781) 555-2406',
  },
  {
    id: 'ma-43', slug: 'young-professional-gateway-mortgage', name: 'Young Professional & First-Time Buyer Specialists (Malden/Lowell)', nmlsId: '429183', type: 'Broker',
    city: 'Malden', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02148', '01852', '01901'], rating: 4.9, reviewCount: 460, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 43, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Transit-Adjacent Entry-Level', 'Malden / Lowell', 'Boston-Priced-Out Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'First-time specialist — tailored for buyers priced out of immediate Boston metro seeking Malden and Lowell transit access.',
    website: 'https://gatewayfirsttimemortgage.com', phone: '(781) 555-2407',
  },
  {
    id: 'ma-44', slug: 'dcu-gateway-cities', name: 'Digital Federal Credit Union (Gateway Cities)', nmlsId: '414078', type: 'Credit Union',
    city: 'Malden', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02148', '01852', '01901'], rating: 4.9, reviewCount: 900, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Gateway City Buyers', 'Essex/Middlesex CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates for gateway city buyers in high-interest secondary markets.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-45', slug: 'transit-oriented-gateway-mortgage', name: 'Transit-Oriented Development Specialists (Revere/Malden)', nmlsId: '394728', type: 'Broker',
    city: 'Revere', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02151', '02148', '01901'], rating: 4.9, reviewCount: 320, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 37, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Blue/Orange T-Lines', 'Northward Migration', 'Rapid Transit Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'Transit-oriented specialist — expertise in Revere and Malden properties near Blue and Orange T-lines.',
    website: 'https://gatewaytransitmortgage.com', phone: '(781) 555-2409',
  },
  {
    id: 'ma-46', slug: 'anchor-home-mortgage-gateway-cities', name: 'Anchor Home Mortgage (Lowell / Lynn)', nmlsId: '136890', type: 'Broker',
    city: 'Lowell', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01852', '01901', '01904'], rating: 4.9, reviewCount: 235, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Suburban Alternatives', 'Commuting Options', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on urban amenities and commuting options in Lowell and Lynn.',
    website: 'https://anchorhomemortgage.com', phone: '(781) 555-2410',
  },
  {
    id: 'ma-47', slug: 'bank-of-america-mortgage-gateway-cities', name: 'Bank of America Mortgage (Lowell / Revere)', nmlsId: '399802', type: 'Bank',
    city: 'Revere', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk',
    zipCodes: ['02151', '01852', '01902'], rating: 4.6, reviewCount: 560, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Lower Barriers to Entry', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for first-time buyers seeking lower barriers in Lowell and Revere.',
    website: 'https://bankofamerica.com/mortgage', phone: '(781) 555-2411',
  },
  {
    id: 'ma-48', slug: 'nova-home-loans-gateway-cities', name: 'Nova Home Loans (Gateway Cities Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Lynn', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Essex', countySlug: 'essex',
    zipCodes: ['01901', '02148', '02151'], rating: 4.8, reviewCount: 275, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Secondary City Markets', 'Sharp Competitiveness'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Gateway cities lender — localized knowledge of sharp competitiveness and affordability in Malden and Lynn.',
    website: 'https://novahomeloans.com', phone: '(781) 555-2412',
  },

  // ── MetroWest Bread & Butter (Framingham, Hudson, Natick) ────────────────────
  {
    id: 'ma-49', slug: 'local-metrowest-independent-mortgage', name: 'Local MetroWest Independent Mortgage', nmlsId: '438291', type: 'Broker',
    city: 'Framingham', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01701', '01760', '01749'], rating: 4.9, reviewCount: 650, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 33, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Single-Family Homes', 'Hybrid-Commute Financing', 'Top-Tier School Districts'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Local MetroWest independent — strong knowledge of top-tier schools and suburban balance in Framingham, Hudson, and Natick.',
    website: 'https://metrowestmortgage.com', phone: '(508) 555-2501',
  },
  {
    id: 'ma-50', slug: 'guild-mortgage-metrowest', name: 'Guild Mortgage (MetroWest)', nmlsId: '3274', type: 'Lender',
    city: 'Framingham', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01701', '01702', '01760'], rating: 4.8, reviewCount: 475, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Middlesex MetroWest', 'Suburban Family Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with MetroWest branches — comprehensive single-family financing in competitive suburban markets.',
    website: 'https://guildmortgage.com', phone: '(508) 555-2502',
  },
  {
    id: 'ma-51', slug: 'new-american-funding-metrowest', name: 'New American Funding (MetroWest)', nmlsId: '6606', type: 'Lender',
    city: 'Natick', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01760', '01701', '01749'], rating: 4.9, reviewCount: 415, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Framingham / Natick', 'Hybrid-Work Families'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF MetroWest team — excellent ratings for hybrid-work families in Framingham and Natick.',
    website: 'https://newamericanfunding.com', phone: '(508) 555-2503',
  },
  {
    id: 'ma-52', slug: 'crosscountry-mortgage-metrowest', name: 'CrossCountry Mortgage (MetroWest)', nmlsId: '3029', type: 'Lender',
    city: 'Hudson', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01749', '01760', '01702'], rating: 4.8, reviewCount: 355, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Hudson / Natick', 'Professional Commuters', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry MetroWest teams — experienced support for professional commuters in Hudson and Natick.',
    website: 'https://crosscountrymortgage.com', phone: '(508) 555-2504',
  },
  {
    id: 'ma-53', slug: 'pierpoint-mortgage-metrowest', name: 'PierPoint Mortgage (MetroWest)', nmlsId: '112844', type: 'Broker',
    city: 'Framingham', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01701', '01749', '01760'], rating: 4.9, reviewCount: 180, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Framingham / Hudson', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to incredibly competitive single-family markets in Framingham and Hudson.',
    website: 'https://pierpointmortgage.com', phone: '(508) 555-2505',
  },
  {
    id: 'ma-54', slug: 'silverton-mortgage-metrowest', name: 'Silverton Mortgage — Natick/Framingham', nmlsId: '1561', type: 'Lender',
    city: 'Natick', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01760', '01701', '01702'], rating: 4.8, reviewCount: 160, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Top-Tier School Districts', 'Retail Local Expertise', 'Natick / Framingham'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton MetroWest retail lending — professional service for top-tier school district suburban buyers.',
    website: 'https://silvertonmortgage.com', phone: '(508) 555-2506',
  },
  {
    id: 'ma-55', slug: 'young-professional-family-mortgage-metrowest', name: 'Young Professional & Family Specialists (MetroWest)', nmlsId: '448291', type: 'Broker',
    city: 'Framingham', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01701', '01760', '01749'], rating: 4.9, reviewCount: 495, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 41, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Hybrid-Work Programs', 'School-Focused Financing', 'Boston Professional Suburbs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Family specialist — tailored for Boston professionals seeking suburban balance with hybrid-work and top schools.',
    website: 'https://metrowestfamilymortgage.com', phone: '(508) 555-2507',
  },
  {
    id: 'ma-56', slug: 'dcu-metrowest', name: 'Digital Federal Credit Union (MetroWest)', nmlsId: '414078', type: 'Credit Union',
    city: 'Natick', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01760', '01701', '01749'], rating: 4.9, reviewCount: 870, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'MetroWest Buyers', 'Bread & Butter Suburbs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates for MetroWest bread & butter suburban buyers.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-57', slug: 'single-family-suburban-mortgage-metrowest', name: 'Single-Family Suburban Specialists (Natick/Hudson)', nmlsId: '401928', type: 'Broker',
    city: 'Natick', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01760', '01749', '01702'], rating: 4.9, reviewCount: 330, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Classic Suburban Single-Family', 'Competitive Markets', 'Natick / Hudson'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Single-family suburban specialist — expertise in competitive Natick and Hudson home markets.',
    website: 'https://metrowestsuburbanmortgage.com', phone: '(508) 555-2509',
  },
  {
    id: 'ma-58', slug: 'anchor-home-mortgage-metrowest', name: 'Anchor Home Mortgage (Framingham / Natick)', nmlsId: '136890', type: 'Broker',
    city: 'Framingham', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01701', '01760', '01749'], rating: 4.9, reviewCount: 250, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Top Schools & Hybrid Commutes', 'Personalized Brokerage', 'MetroWest Families'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on top schools and manageable hybrid commutes for MetroWest families.',
    website: 'https://anchorhomemortgage.com', phone: '(508) 555-2510',
  },
  {
    id: 'ma-59', slug: 'bank-of-america-mortgage-metrowest', name: 'Bank of America Mortgage (Framingham / Hudson)', nmlsId: '399802', type: 'Bank',
    city: 'Framingham', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01701', '01749', '01760'], rating: 4.6, reviewCount: 600, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Suburban Relocation Financing', 'Hybrid Workers', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for professional hybrid workers relocating to Framingham and Hudson.',
    website: 'https://bankofamerica.com/mortgage', phone: '(508) 555-2511',
  },
  {
    id: 'ma-60', slug: 'nova-home-loans-metrowest', name: 'Nova Home Loans (MetroWest Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Natick', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['01760', '01749', '01702'], rating: 4.8, reviewCount: 300, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Permanent Hybrid-Work Demand', 'Suburban Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'MetroWest lender — localized knowledge of permanent hybrid-work demand in Natick and Hudson suburban markets.',
    website: 'https://novahomeloans.com', phone: '(508) 555-2512',
  },
];

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_LENDER_SLUGS = [
  'central-mass-independent-mortgage-worcester',
  'guild-mortgage-worcester',
  'new-american-funding-worcester',
  'crosscountry-mortgage-worcester',
  'pierpoint-mortgage-worcester',
  'silverton-mortgage-worcester',
  'young-professional-investor-mortgage-worcester',
  'dcu-worcester',
  'downtown-new-construction-mortgage-worcester',
  'anchor-home-mortgage-worcester',
  'bank-of-america-mortgage-worcester',
  'nova-home-loans-worcester',
] as const;

export const TRANSIT_ORIENTED_URBAN_HOTSPOTS_LENDER_SLUGS = [
  'local-cambridge-somerville-independent-mortgage',
  'guild-mortgage-cambridge-somerville',
  'new-american-funding-cambridge-somerville',
  'crosscountry-mortgage-cambridge-somerville',
  'pierpoint-mortgage-cambridge-somerville',
  'silverton-mortgage-cambridge-somerville',
  'young-professional-biotech-mortgage-cambridge',
  'dcu-cambridge-somerville',
  'green-line-transit-mortgage-cambridge-somerville',
  'anchor-home-mortgage-cambridge-somerville',
  'bank-of-america-mortgage-cambridge-somerville',
  'nova-home-loans-cambridge-somerville',
] as const;

export const HIGH_DEMAND_BOSTON_NEIGHBORHOODS_LENDER_SLUGS = [
  'local-boston-neighborhood-independent-mortgage',
  'guild-mortgage-boston-neighborhoods',
  'new-american-funding-boston-neighborhoods',
  'crosscountry-mortgage-boston-neighborhoods',
  'pierpoint-mortgage-boston-neighborhoods',
  'silverton-mortgage-boston-neighborhoods',
  'waterfront-first-time-mortgage-east-boston',
  'dcu-boston-neighborhoods',
  'historic-rental-yield-mortgage-boston',
  'anchor-home-mortgage-boston-neighborhoods',
  'bank-of-america-mortgage-boston-neighborhoods',
  'nova-home-loans-boston-neighborhoods',
] as const;

export const GATEWAY_CITIES_SUBURBAN_ALTERNATIVES_LENDER_SLUGS = [
  'local-gateway-cities-independent-mortgage',
  'guild-mortgage-gateway-cities',
  'new-american-funding-gateway-cities',
  'crosscountry-mortgage-gateway-cities',
  'pierpoint-mortgage-gateway-cities',
  'silverton-mortgage-gateway-cities',
  'young-professional-gateway-mortgage',
  'dcu-gateway-cities',
  'transit-oriented-gateway-mortgage',
  'anchor-home-mortgage-gateway-cities',
  'bank-of-america-mortgage-gateway-cities',
  'nova-home-loans-gateway-cities',
] as const;

export const METROWEST_BREAD_AND_BUTTER_LENDER_SLUGS = [
  'local-metrowest-independent-mortgage',
  'guild-mortgage-metrowest',
  'new-american-funding-metrowest',
  'crosscountry-mortgage-metrowest',
  'pierpoint-mortgage-metrowest',
  'silverton-mortgage-metrowest',
  'young-professional-family-mortgage-metrowest',
  'dcu-metrowest',
  'single-family-suburban-mortgage-metrowest',
  'anchor-home-mortgage-metrowest',
  'bank-of-america-mortgage-metrowest',
  'nova-home-loans-metrowest',
] as const;

const GATEWAY_ESSEX_SUPPLEMENTS = [
  'local-gateway-cities-independent-mortgage',
  'new-american-funding-gateway-cities',
  'silverton-mortgage-gateway-cities',
  'young-professional-gateway-mortgage',
  'dcu-gateway-cities',
  'transit-oriented-gateway-mortgage',
  'anchor-home-mortgage-gateway-cities',
  'bank-of-america-mortgage-gateway-cities',
];

const GATEWAY_MIDDLESEX_SUPPLEMENTS = [
  'guild-mortgage-gateway-cities',
  'crosscountry-mortgage-gateway-cities',
  'pierpoint-mortgage-gateway-cities',
  'silverton-mortgage-gateway-cities',
  'transit-oriented-gateway-mortgage',
  'bank-of-america-mortgage-gateway-cities',
  'nova-home-loans-gateway-cities',
];

const GATEWAY_SUFFOLK_SUPPLEMENTS = [
  'local-gateway-cities-independent-mortgage',
  'guild-mortgage-gateway-cities',
  'new-american-funding-gateway-cities',
  'crosscountry-mortgage-gateway-cities',
  'pierpoint-mortgage-gateway-cities',
  'young-professional-gateway-mortgage',
  'dcu-gateway-cities',
  'anchor-home-mortgage-gateway-cities',
  'nova-home-loans-gateway-cities',
];

export const MASSACHUSETTS_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  worcester: [],
  middlesex: GATEWAY_MIDDLESEX_SUPPLEMENTS,
  suffolk: GATEWAY_SUFFOLK_SUPPLEMENTS,
  essex: GATEWAY_ESSEX_SUPPLEMENTS,
};

export const HIGH_DEMAND_BOSTON_NEIGHBORHOODS_HUB_AREAS = [
  { name: 'East Boston', slug: 'suffolk', highlight: 'Waterfront proximity, Back Bay alternative' },
  { name: 'Dorchester', slug: 'suffolk', highlight: 'Space, culture, strong rental yields' },
  { name: 'Jamaica Plain', slug: 'suffolk', highlight: 'High-competition cultural district' },
  { name: 'Suffolk County', slug: 'suffolk', highlight: 'Cooled luxury vs. neighborhood heat' },
] as const;

export const GATEWAY_CITIES_HUB_AREAS = [
  { name: 'Lowell', slug: 'middlesex', highlight: 'Gateway city, commuter transit, affordability' },
  { name: 'Lynn', slug: 'essex', highlight: 'North Shore urban amenities, sharp demand' },
  { name: 'Revere', slug: 'suffolk', highlight: 'Blue Line access, Boston spillover' },
  { name: 'Malden', slug: 'middlesex', highlight: 'Orange Line, priced-out Boston buyers' },
] as const;

export const METROWEST_BREAD_AND_BUTTER_HUB_AREAS = [
  { name: 'Framingham', slug: 'middlesex', highlight: 'Hybrid commute, competitive single-family' },
  { name: 'Natick', slug: 'middlesex', highlight: 'Top-tier schools, bread & butter suburb' },
  { name: 'Hudson', slug: 'middlesex', highlight: 'Professional commuters, suburban balance' },
  { name: 'MetroWest', slug: 'middlesex', highlight: 'Permanent hybrid-work family demand' },
] as const;

export const TRANSIT_ORIENTED_URBAN_HOTSPOTS_HUB_COUNTIES = [
  { name: 'Middlesex', slug: 'middlesex', highlight: 'Cambridge & Somerville transit-oriented urban core' },
] as const;

export const TRANSIT_ORIENTED_URBAN_HOTSPOTS_HUB_AREAS = [
  { name: 'Cambridge', slug: 'middlesex', highlight: '$1M+ medians, Kendall Square biotech' },
  { name: 'Somerville', slug: 'middlesex', highlight: '$930K+ medians, Green Line extension' },
  { name: 'Union Square', slug: 'middlesex', highlight: 'New transit stations, fierce demand' },
  { name: 'Davis / Porter', slug: 'middlesex', highlight: 'Walkable T-access urban cores' },
] as const;

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_HUB_COUNTIES = [
  { name: 'Worcester', slug: 'worcester', highlight: 'Undisputed Central Mass growth leader' },
] as const;

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_HUB_AREAS = [
  { name: 'Downtown Worcester', slug: 'worcester', highlight: 'Zoom Town revitalization, life sciences boom' },
  { name: 'Polar Park Corridor', slug: 'worcester', highlight: 'Stadium district investment & new demand' },
  { name: 'Commuter Rail Hub', slug: 'worcester', highlight: 'Union Station access, Boston connectivity' },
  { name: 'Worcester County', slug: 'worcester', highlight: 'Relative affordability vs. Greater Boston' },
] as const;