import type { Lender } from '@/lib/lender/mockData';

export const MICHIGAN_LENDERS: Lender[] = [
  // ── Greater Detroit Value Pockets (Dearborn, Lincoln Park & Howell) ──────────
  {
    id: 'mi-01', slug: 'local-greater-detroit-independent-mortgage', name: 'Local Greater Detroit Independent Mortgage', nmlsId: '502891', type: 'Broker',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48146'], rating: 4.9, reviewCount: 680, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Entry-Level Neighborhoods', 'Transitional Markets', 'Purchasing Power'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Local Greater Detroit independent — strong knowledge of entry-level and transitional neighborhood demand across Dearborn and Lincoln Park.',
    website: 'https://greaterdetroitindependentmortgage.com', phone: '(313) 555-5101',
  },
  {
    id: 'mi-02', slug: 'guild-mortgage-greater-detroit', name: 'Guild Mortgage (Greater Detroit)', nmlsId: '3274', type: 'Lender',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48120'], rating: 4.8, reviewCount: 470, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Wayne County Operations', 'Value Pocket Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Dearborn branches — comprehensive financing across Southeast Michigan value pockets.',
    website: 'https://guildmortgage.com', phone: '(313) 555-5102',
  },
  {
    id: 'mi-03', slug: 'new-american-funding-dearborn', name: 'New American Funding (Dearborn)', nmlsId: '6606', type: 'Lender',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48128'], rating: 4.9, reviewCount: 445, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Zillow Top 5 City', 'High-Volume Purchase/Refinance', 'Cultural Community Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'NAF Dearborn team — excellent ratings for one of Zillow\'s top 5 most popular US home shopping cities.',
    website: 'https://newamericanfunding.com', phone: '(313) 555-5103',
  },
  {
    id: 'mi-04', slug: 'crosscountry-mortgage-lincoln-park', name: 'CrossCountry Mortgage (Lincoln Park)', nmlsId: '3029', type: 'Lender',
    city: 'Lincoln Park', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48146', '48126', '48124'], rating: 4.8, reviewCount: 375, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Redfin Top 10 Neighborhood', '40% Over Asking', 'Affordable Price Point'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Lincoln Park — experienced support for Redfin\'s top 10 hottest neighborhood with 14% YoY sales jump.',
    website: 'https://crosscountrymortgage.com', phone: '(313) 555-5104',
  },
  {
    id: 'mi-05', slug: 'pierpoint-mortgage-greater-detroit', name: 'PierPoint Mortgage (Greater Detroit)', nmlsId: '112844', type: 'Broker',
    city: 'Lincoln Park', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48146', '48126', '48124'], rating: 4.9, reviewCount: 178, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Over-Asking Competition'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to nearly 40% over-asking sales in Lincoln Park\'s affordable hot market.',
    website: 'https://pierpointmortgage.com', phone: '(313) 555-5105',
  },
  {
    id: 'mi-06', slug: 'silverton-mortgage-greater-detroit', name: 'Silverton Mortgage — Greater Detroit', nmlsId: '1561', type: 'Lender',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48146', '48124'], rating: 4.8, reviewCount: 162, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Entry-Level Markets', 'Retail Local Expertise', 'Transitional Neighborhoods'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Dearborn retail lending — professional service for maximizing purchasing power in value pockets.',
    website: 'https://silvertonmortgage.com', phone: '(313) 555-5106',
  },
  {
    id: 'mi-07', slug: 'entry-level-transitional-mortgage-greater-detroit', name: 'Entry-Level & Transitional Neighborhood Specialists (Greater Detroit)', nmlsId: '513827', type: 'Broker',
    city: 'Lincoln Park', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48146', '48126', '48124'], rating: 4.9, reviewCount: 495, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Purchasing Power Maximization', 'Transitional Neighborhoods', '14% YoY Sales Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Entry-level specialist — tailored for buyers maximizing value in Lincoln Park and Dearborn hot markets.',
    website: 'https://detroitentrylevelmortgage.com', phone: '(313) 555-5107',
  },
  {
    id: 'mi-08', slug: 'greater-detroit-community-credit-union', name: 'Greater Detroit Community Credit Union', nmlsId: '559102', type: 'Credit Union',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48146'], rating: 4.9, reviewCount: 820, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Affordable Options', 'Community-Focused Lending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for Southeast Michigan value pocket buyers.',
    website: 'https://greaterdetroitcu.org', phone: '(313) 555-5108',
  },
  {
    id: 'mi-09', slug: 'mshda-first-time-mortgage-greater-detroit', name: 'MSHDA & First-Time Buyer Specialists (Dearborn)', nmlsId: '521293', type: 'Broker',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48128'], rating: 4.9, reviewCount: 320, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Michigan MSHDA Programs', 'First-Time Buyers', 'Accessible Median Values'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'MSHDA specialist — expertise in Dearborn\'s accessible median values and Zillow top-5 buyer search explosion.',
    website: 'https://dearbornmshdamortgage.com', phone: '(313) 555-5109',
  },
  {
    id: 'mi-10', slug: 'anchor-home-mortgage-greater-detroit', name: 'Anchor Home Mortgage (Greater Detroit)', nmlsId: '136890', type: 'Broker',
    city: 'Lincoln Park', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48146', '48126', '48124'], rating: 4.9, reviewCount: 260, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['40% Over Asking', 'Personalized Brokerage', 'Value Pocket Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Lincoln Park over-asking competition and affordable hot-market dynamics.',
    website: 'https://anchorhomemortgage.com', phone: '(313) 555-5110',
  },
  {
    id: 'mi-11', slug: 'bank-of-america-mortgage-greater-detroit', name: 'Bank of America Mortgage (Greater Detroit)', nmlsId: '399802', type: 'Bank',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48146'], rating: 4.6, reviewCount: 590, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Full-Service Banking', 'Metro Detroit Value'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for buyers in Dearborn and Lincoln Park value pockets.',
    website: 'https://bankofamerica.com/mortgage', phone: '(313) 555-5111',
  },
  {
    id: 'mi-12', slug: 'nova-home-loans-howell-greater-detroit', name: 'Nova Home Loans (Howell / Greater Detroit)', nmlsId: '3089', type: 'Lender',
    city: 'Howell', state: 'Michigan', stateSlug: 'michigan', county: 'Livingston', countySlug: 'livingston',
    zipCodes: ['48843', '48855', '48146'], rating: 4.8, reviewCount: 270, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Redfin Top 10 Market', 'High-End Bidding Wars', 'Page View Surge'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 94,
    shortDescription: 'Howell lender — localized knowledge of Redfin\'s national top 10 hottest market and rapid-fire bidding wars.',
    website: 'https://novahomeloans.com', phone: '(517) 555-5112',
  },

  // ── Lansing Multi-Family & Investor Magnet (Ingham County) ───────────────────
  {
    id: 'mi-13', slug: 'local-lansing-independent-mortgage', name: 'Local Lansing Independent Mortgage', nmlsId: '522891', type: 'Broker',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48910'], rating: 4.9, reviewCount: 540, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-Family Financing', 'Investor Cash-Flow', 'Rental Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Local Lansing independent — strong knowledge of rental growth, cap rates, and multi-family demand in the capital region.',
    website: 'https://lansingindependentmortgage.com', phone: '(517) 555-5213',
  },
  {
    id: 'mi-14', slug: 'guild-mortgage-lansing', name: 'Guild Mortgage (Lansing)', nmlsId: '3274', type: 'Lender',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48912'], rating: 4.8, reviewCount: 410, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Ingham County Operations', 'Investor Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Lansing branches — comprehensive financing for investors in a top emerging market.',
    website: 'https://guildmortgage.com', phone: '(517) 555-5214',
  },
  {
    id: 'mi-15', slug: 'new-american-funding-lansing', name: 'New American Funding (Lansing)', nmlsId: '6606', type: 'Lender',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48906'], rating: 4.9, reviewCount: 390, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Lansing / East Lansing', 'High-Volume Purchase/Refinance', 'Multi-Family Deals'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'NAF Lansing team — excellent ratings for investor and multi-family transactions in the capital region.',
    website: 'https://newamericanfunding.com', phone: '(517) 555-5215',
  },
  {
    id: 'mi-16', slug: 'crosscountry-mortgage-lansing-metro', name: 'CrossCountry Mortgage (Central MI)', nmlsId: '3029', type: 'Lender',
    city: 'East Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48823', '48933', '48910'], rating: 4.8, reviewCount: 350, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Lansing Metro', 'Investor Portfolios', 'Low Vacancy Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Lansing metro — experienced support for ~6% multi-family vacancy and seller\'s market dynamics.',
    website: 'https://crosscountrymortgage.com', phone: '(517) 555-5216',
  },
  {
    id: 'mi-17', slug: 'pierpoint-mortgage-lansing', name: 'PierPoint Mortgage (Central MI)', nmlsId: '112844', type: 'Broker',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48912'], rating: 4.9, reviewCount: 172, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Fast Closings', 'First-Time Buyers', 'Rapid Turnarounds'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 17, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to rapid turnarounds in Lansing\'s emerging investor magnet market.',
    website: 'https://pierpointmortgage.com', phone: '(517) 555-5217',
  },
  {
    id: 'mi-18', slug: 'silverton-mortgage-lansing', name: 'Silverton Mortgage — Lansing', nmlsId: '1561', type: 'Lender',
    city: 'East Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48823', '48933', '48906'], rating: 4.8, reviewCount: 155, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['University-Adjacent Properties', 'Retail Local Expertise', 'Rental Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Silverton East Lansing retail lending — professional service for university-adjacent rental properties.',
    website: 'https://silvertonmortgage.com', phone: '(517) 555-5218',
  },
  {
    id: 'mi-19', slug: 'investor-multifamily-specialists-lansing', name: 'Investor & Multi-Family Specialists (Lansing)', nmlsId: '533827', type: 'Broker',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48910'], rating: 4.9, reviewCount: 460, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Cash-Flow Programs', '$145K–$160K Values', 'Strong Cap Rates'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 96,
    shortDescription: 'Investor specialist — tailored for $145K–$160K average values and exceptional cap rates in Lansing.',
    website: 'https://lansinginvestormortgage.com', phone: '(517) 555-5219',
  },
  {
    id: 'mi-20', slug: 'lansing-community-credit-union', name: 'Lansing Community Credit Union', nmlsId: '569102', type: 'Credit Union',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48912'], rating: 4.9, reviewCount: 760, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Investor Buyers', 'Emerging Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for investor buyers in the Lansing-East Lansing emerging market.',
    website: 'https://lansingcu.org', phone: '(517) 555-5220',
  },
  {
    id: 'mi-21', slug: 'new-construction-rental-specialists-lansing', name: 'New Construction & Rental Specialists (Lansing)', nmlsId: '531293', type: 'Broker',
    city: 'East Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48823', '48933', '48906'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-Family Housing', 'Student/Professional Housing', '~6% Vacancy'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'Rental specialist — expertise in low vacancy and scorching rent growth across Lansing-East Lansing.',
    website: 'https://lansingrentalmortgage.com', phone: '(517) 555-5221',
  },
  {
    id: 'mi-22', slug: 'anchor-home-mortgage-lansing', name: 'Anchor Home Mortgage (Lansing Metro)', nmlsId: '136890', type: 'Broker',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48910'], rating: 4.9, reviewCount: 250, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['WSJ/Realtor.com Emerging', 'Personalized Brokerage', 'Investor Focus'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Wall Street Journal/Realtor.com emerging market investor demand.',
    website: 'https://anchorhomemortgage.com', phone: '(517) 555-5222',
  },
  {
    id: 'mi-23', slug: 'bank-of-america-mortgage-lansing', name: 'Bank of America Mortgage (Lansing)', nmlsId: '399802', type: 'Bank',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48912'], rating: 4.6, reviewCount: 520, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investment Financing', 'Multi-Family Portfolios', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for multi-family and rental portfolios in Lansing.',
    website: 'https://bankofamerica.com/mortgage', phone: '(517) 555-5223',
  },
  {
    id: 'mi-24', slug: 'nova-home-loans-lansing', name: 'Nova Home Loans (Lansing Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Lansing', state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham',
    zipCodes: ['48933', '48823', '48906'], rating: 4.8, reviewCount: 255, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Seller\'s Market', 'Rent Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 21, onTimeCloseRate: 94,
    shortDescription: 'Lansing lender — localized knowledge of heavy seller leverage and scorching rental markets.',
    website: 'https://novahomeloans.com', phone: '(517) 555-5224',
  },

  // ── Grand Rapids Fast-Moving Core (Kent County) ──────────────────────────────
  {
    id: 'mi-25', slug: 'local-grand-rapids-independent-mortgage', name: 'Local Grand Rapids Independent Mortgage', nmlsId: '532891', type: 'Broker',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49301'], rating: 4.9, reviewCount: 620, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 30, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['6-Day Average DOM', 'Multiple-Offer Financing', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 14, onTimeCloseRate: 97,
    shortDescription: 'Local Grand Rapids independent — strong knowledge of 6-day average under contract and blistering market pace.',
    website: 'https://grandrapidsindependentmortgage.com', phone: '(616) 555-5325',
  },
  {
    id: 'mi-26', slug: 'guild-mortgage-grand-rapids', name: 'Guild Mortgage (Grand Rapids)', nmlsId: '3274', type: 'Lender',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49504'], rating: 4.8, reviewCount: 485, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Kent County Operations', 'Fast-Moving Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Grand Rapids branches — comprehensive financing in a consistent powerhouse market.',
    website: 'https://guildmortgage.com', phone: '(616) 555-5326',
  },
  {
    id: 'mi-27', slug: 'new-american-funding-grand-rapids', name: 'New American Funding (Grand Rapids)', nmlsId: '6606', type: 'Lender',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49301'], rating: 4.9, reviewCount: 430, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Blistering Pace', 'Multiple Offers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 16, onTimeCloseRate: 96,
    shortDescription: 'NAF Grand Rapids team — excellent ratings for blistering 6-day average contract transactions.',
    website: 'https://newamericanfunding.com', phone: '(616) 555-5327',
  },
  {
    id: 'mi-28', slug: 'crosscountry-mortgage-west-michigan', name: 'CrossCountry Mortgage (West Michigan)', nmlsId: '3029', type: 'Lender',
    city: 'East Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49506', '49301', '49503'], rating: 4.8, reviewCount: 365, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['East Grand Rapids / Ada', 'Healthcare Professionals', 'Manufacturing Relocations'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 20, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry West Michigan — experienced support for inventory-crunch bidding wars in wealthier enclaves.',
    website: 'https://crosscountrymortgage.com', phone: '(616) 555-5328',
  },
  {
    id: 'mi-29', slug: 'pierpoint-mortgage-grand-rapids', name: 'PierPoint Mortgage (Grand Rapids)', nmlsId: '112844', type: 'Broker',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49301'], rating: 4.9, reviewCount: 185, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Grand Rapids / Ada', 'First-Time Buyers', 'Under-15-Day Pending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 12, onTimeCloseRate: 98,
    shortDescription: 'Wholesale broker — speed suited to under-15-day pending times in East Grand Rapids and Ada.',
    website: 'https://pierpointmortgage.com', phone: '(616) 555-5329',
  },
  {
    id: 'mi-30', slug: 'silverton-mortgage-grand-rapids', name: 'Silverton Mortgage — Grand Rapids', nmlsId: '1561', type: 'Lender',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49301'], rating: 4.8, reviewCount: 168, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Multiple-Offer Standard', 'Retail Local Expertise', 'Top Job Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Silverton Grand Rapids retail lending — professional service for multiple-offer standard expectations.',
    website: 'https://silvertonmortgage.com', phone: '(616) 555-5330',
  },
  {
    id: 'mi-31', slug: 'young-professional-family-specialists-grand-rapids', name: 'Young Professional & Family Specialists (East Grand Rapids / Ada)', nmlsId: '543827', type: 'Broker',
    city: 'East Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49506', '49301', '49503'], rating: 4.9, reviewCount: 505, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Millennial Relocations', 'Family Programs', 'Top Job Market Influx'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 15, onTimeCloseRate: 96,
    shortDescription: 'Young professional specialist — tailored for millennial influx in Grand Rapids\' top job market.',
    website: 'https://egrprofessionalmortgage.com', phone: '(616) 555-5331',
  },
  {
    id: 'mi-32', slug: 'grand-rapids-community-credit-union', name: 'Grand Rapids Community Credit Union', nmlsId: '579102', type: 'Credit Union',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49301'], rating: 4.9, reviewCount: 830, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Member Rates', 'Fast-Moving Market', 'Community-Focused Lending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for buyers in Grand Rapids\' severe inventory crunch.',
    website: 'https://grandrapidscu.org', phone: '(616) 555-5332',
  },
  {
    id: 'mi-33', slug: 'new-construction-suburban-specialists-ada', name: 'New Construction & Suburban Specialists (Ada / East Grand Rapids)', nmlsId: '541293', type: 'Broker',
    city: 'Ada', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49301', '49506', '49503'], rating: 4.9, reviewCount: 315, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 37, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Wealthier Enclave Financing', 'New Build Programs', 'Inventory Crunch'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 96,
    shortDescription: 'Suburban specialist — expertise in Ada and East Grand Rapids wealthier enclave new-build demand.',
    website: 'https://adasuburbanmortgage.com', phone: '(616) 555-5333',
  },
  {
    id: 'mi-34', slug: 'anchor-home-mortgage-grand-rapids', name: 'Anchor Home Mortgage (Grand Rapids)', nmlsId: '136890', type: 'Broker',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49301'], rating: 4.9, reviewCount: 275, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['6-Day Under Contract', 'Personalized Brokerage', 'West Michigan'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 13, onTimeCloseRate: 97,
    shortDescription: 'Independent broker — strong focus on Grand Rapids\' 6-day average under contract velocity.',
    website: 'https://anchorhomemortgage.com', phone: '(616) 555-5334',
  },
  {
    id: 'mi-35', slug: 'bank-of-america-mortgage-grand-rapids', name: 'Bank of America Mortgage (Grand Rapids)', nmlsId: '399802', type: 'Bank',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49301'], rating: 4.6, reviewCount: 600, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Professional Relocation', 'Healthcare/Manufacturing', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 28, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for healthcare and manufacturing professional relocations.',
    website: 'https://bankofamerica.com/mortgage', phone: '(616) 555-5335',
  },
  {
    id: 'mi-36', slug: 'nova-home-loans-grand-rapids', name: 'Nova Home Loans (Grand Rapids Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Grand Rapids', state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent',
    zipCodes: ['49503', '49506', '49301'], rating: 4.8, reviewCount: 280, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Powerhouse Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 17, onTimeCloseRate: 94,
    shortDescription: 'Grand Rapids lender — localized knowledge of consistent top rankings and inventory crunch.',
    website: 'https://novahomeloans.com', phone: '(616) 555-5336',
  },

  // ── Ann Arbor & Kalamazoo College-Town Demand (Washtenaw & Kalamazoo) ────────
  {
    id: 'mi-37', slug: 'local-university-town-independent-mortgage', name: 'Local University-Town Independent Mortgage', nmlsId: '542891', type: 'Broker',
    city: 'Ann Arbor', state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw',
    zipCodes: ['48104', '48103', '49007'], rating: 4.9, reviewCount: 570, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 33, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Professional Financing', 'Student-Related Properties', 'Insulated Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local university-town independent — strong knowledge of insulated college-town markets in Ann Arbor and Kalamazoo.',
    website: 'https://universitytownindependentmortgage.com', phone: '(734) 555-5437',
  },
  {
    id: 'mi-38', slug: 'guild-mortgage-ann-arbor-kalamazoo', name: 'Guild Mortgage (Ann Arbor & Kalamazoo)', nmlsId: '3274', type: 'Lender',
    city: 'Ann Arbor', state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw',
    zipCodes: ['48104', '48103', '49007'], rating: 4.8, reviewCount: 455, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'University-Town Operations', 'College-Town Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Ann Arbor and Kalamazoo branches — comprehensive college-town financing.',
    website: 'https://guildmortgage.com', phone: '(734) 555-5438',
  },
  {
    id: 'mi-39', slug: 'new-american-funding-ann-arbor', name: 'New American Funding (Ann Arbor)', nmlsId: '6606', type: 'Lender',
    city: 'Ann Arbor', state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw',
    zipCodes: ['48104', '48103', '48108'], rating: 4.9, reviewCount: 415, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Medical/Tech Professionals', 'High-Volume Purchase/Refinance', '$549K Median'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'NAF Ann Arbor team — excellent ratings for medical and tech professional demand in Tree Town.',
    website: 'https://newamericanfunding.com', phone: '(734) 555-5439',
  },
  {
    id: 'mi-40', slug: 'crosscountry-mortgage-southwest-michigan', name: 'CrossCountry Mortgage (Southwest MI)', nmlsId: '3029', type: 'Lender',
    city: 'Kalamazoo', state: 'Michigan', stateSlug: 'michigan', county: 'Kalamazoo', countySlug: 'kalamazoo',
    zipCodes: ['49007', '49008', '48104'], rating: 4.8, reviewCount: 340, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Affordable College-Town', 'Out-of-State Interest', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Southwest MI — experienced support for $245K median Kalamazoo and out-of-state buyer interest.',
    website: 'https://crosscountrymortgage.com', phone: '(269) 555-5540',
  },
  {
    id: 'mi-41', slug: 'pierpoint-mortgage-southeast-michigan', name: 'PierPoint Mortgage (Southeast MI)', nmlsId: '112844', type: 'Broker',
    city: 'Ann Arbor', state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw',
    zipCodes: ['48104', '49007', '48103'], rating: 4.9, reviewCount: 182, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Ann Arbor / Kalamazoo', 'First-Time Buyers', 'Competitive Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to competitive luxury and mid-tier university-town markets.',
    website: 'https://pierpointmortgage.com', phone: '(734) 555-5441',
  },
  {
    id: 'mi-42', slug: 'silverton-mortgage-ann-arbor-kalamazoo', name: 'Silverton Mortgage — Ann Arbor & Kalamazoo', nmlsId: '1561', type: 'Lender',
    city: 'Kalamazoo', state: 'Michigan', stateSlug: 'michigan', county: 'Kalamazoo', countySlug: 'kalamazoo',
    zipCodes: ['49007', '49008', '48104'], rating: 4.8, reviewCount: 158, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Resilient Appreciation', 'Retail Local Expertise', 'College-Town Stability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Kalamazoo retail lending — professional service for steady price appreciation markets.',
    website: 'https://silvertonmortgage.com', phone: '(269) 555-5542',
  },
  {
    id: 'mi-43', slug: 'professional-academic-specialists-ann-arbor', name: 'Professional & Academic Specialists (Ann Arbor)', nmlsId: '553827', type: 'Broker',
    city: 'Ann Arbor', state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw',
    zipCodes: ['48104', '48103', '48108'], rating: 4.9, reviewCount: 490, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Medical/Tech/University', 'Relocation Programs', 'Insulated $549K Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Professional specialist — tailored for medical, tech, and university influx in insulated Ann Arbor.',
    website: 'https://annarborprofessionalmortgage.com', phone: '(734) 555-5443',
  },
  {
    id: 'mi-44', slug: 'university-town-community-credit-union', name: 'University-Town Community Credit Union', nmlsId: '589102', type: 'Credit Union',
    city: 'Ann Arbor', state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw',
    zipCodes: ['48104', '48103', '49007'], rating: 4.9, reviewCount: 800, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Member Rates', 'College-Town Buyers', 'Stable Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for college-town buyers in stable demand areas.',
    website: 'https://universitytowncu.org', phone: '(734) 555-5444',
  },
  {
    id: 'mi-45', slug: 'mid-tier-specialists-kalamazoo', name: 'New Construction & Mid-Tier Specialists (Kalamazoo)', nmlsId: '551293', type: 'Broker',
    city: 'Kalamazoo', state: 'Michigan', stateSlug: 'michigan', county: 'Kalamazoo', countySlug: 'kalamazoo',
    zipCodes: ['49007', '49008', '49009'], rating: 4.9, reviewCount: 305, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 37, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['$245K Median', 'Affordable Single-Family', 'Out-of-State Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Mid-tier specialist — expertise in Kalamazoo\'s affordable alternative and strong out-of-state interest.',
    website: 'https://kalamazoomidtiermortgage.com', phone: '(269) 555-5545',
  },
  {
    id: 'mi-46', slug: 'anchor-home-mortgage-ann-arbor-kalamazoo', name: 'Anchor Home Mortgage (Ann Arbor & Kalamazoo)', nmlsId: '136890', type: 'Broker',
    city: 'Ann Arbor', state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw',
    zipCodes: ['48104', '49007', '48103'], rating: 4.9, reviewCount: 265, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Stability Focus', 'Professional Influx', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on stability and professional influx in premier university towns.',
    website: 'https://anchorhomemortgage.com', phone: '(734) 555-5446',
  },
  {
    id: 'mi-47', slug: 'bank-of-america-mortgage-ann-arbor-kalamazoo', name: 'Bank of America Mortgage (Ann Arbor & Kalamazoo)', nmlsId: '399802', type: 'Bank',
    city: 'Kalamazoo', state: 'Michigan', stateSlug: 'michigan', county: 'Kalamazoo', countySlug: 'kalamazoo',
    zipCodes: ['49007', '48104', '49008'], rating: 4.6, reviewCount: 570, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Professional Relocation', 'Medical & Tech', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for medical and tech professional relocations.',
    website: 'https://bankofamerica.com/mortgage', phone: '(269) 555-5547',
  },
  {
    id: 'mi-48', slug: 'nova-home-loans-ann-arbor-kalamazoo', name: 'Nova Home Loans (Ann Arbor & Kalamazoo Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Ann Arbor', state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw',
    zipCodes: ['48104', '49007', '48103'], rating: 4.8, reviewCount: 275, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Steady Appreciation'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 23, onTimeCloseRate: 94,
    shortDescription: 'University-town lender — localized knowledge of resilience and steady appreciation in college markets.',
    website: 'https://novahomeloans.com', phone: '(734) 555-5448',
  },
];

export const GREATER_DETROITS_VALUE_POCKETS_LENDER_SLUGS = [
  'local-greater-detroit-independent-mortgage',
  'guild-mortgage-greater-detroit',
  'new-american-funding-dearborn',
  'crosscountry-mortgage-lincoln-park',
  'pierpoint-mortgage-greater-detroit',
  'silverton-mortgage-greater-detroit',
  'entry-level-transitional-mortgage-greater-detroit',
  'greater-detroit-community-credit-union',
  'mshda-first-time-mortgage-greater-detroit',
  'anchor-home-mortgage-greater-detroit',
  'bank-of-america-mortgage-greater-detroit',
  'nova-home-loans-howell-greater-detroit',
] as const;

const GREATER_DETROIT_WAYNE_SUPPLEMENTS = [
  'nova-home-loans-howell-greater-detroit',
];

const GREATER_DETROIT_LIVINGSTON_SUPPLEMENTS = [
  'local-greater-detroit-independent-mortgage',
  'guild-mortgage-greater-detroit',
  'new-american-funding-dearborn',
  'crosscountry-mortgage-lincoln-park',
  'pierpoint-mortgage-greater-detroit',
  'silverton-mortgage-greater-detroit',
  'entry-level-transitional-mortgage-greater-detroit',
  'greater-detroit-community-credit-union',
  'mshda-first-time-mortgage-greater-detroit',
  'anchor-home-mortgage-greater-detroit',
  'bank-of-america-mortgage-greater-detroit',
];

export const LANSING_MULTI_FAMILY_INVESTOR_MAGNET_LENDER_SLUGS = [
  'local-lansing-independent-mortgage',
  'guild-mortgage-lansing',
  'new-american-funding-lansing',
  'crosscountry-mortgage-lansing-metro',
  'pierpoint-mortgage-lansing',
  'silverton-mortgage-lansing',
  'investor-multifamily-specialists-lansing',
  'lansing-community-credit-union',
  'new-construction-rental-specialists-lansing',
  'anchor-home-mortgage-lansing',
  'bank-of-america-mortgage-lansing',
  'nova-home-loans-lansing',
] as const;

export const GRAND_RAPIDS_FAST_MOVING_CORE_LENDER_SLUGS = [
  'local-grand-rapids-independent-mortgage',
  'guild-mortgage-grand-rapids',
  'new-american-funding-grand-rapids',
  'crosscountry-mortgage-west-michigan',
  'pierpoint-mortgage-grand-rapids',
  'silverton-mortgage-grand-rapids',
  'young-professional-family-specialists-grand-rapids',
  'grand-rapids-community-credit-union',
  'new-construction-suburban-specialists-ada',
  'anchor-home-mortgage-grand-rapids',
  'bank-of-america-mortgage-grand-rapids',
  'nova-home-loans-grand-rapids',
] as const;

export const ANN_ARBOR_KALAMAZOO_COLLEGE_TOWN_DEMAND_LENDER_SLUGS = [
  'local-university-town-independent-mortgage',
  'guild-mortgage-ann-arbor-kalamazoo',
  'new-american-funding-ann-arbor',
  'crosscountry-mortgage-southwest-michigan',
  'pierpoint-mortgage-southeast-michigan',
  'silverton-mortgage-ann-arbor-kalamazoo',
  'professional-academic-specialists-ann-arbor',
  'university-town-community-credit-union',
  'mid-tier-specialists-kalamazoo',
  'anchor-home-mortgage-ann-arbor-kalamazoo',
  'bank-of-america-mortgage-ann-arbor-kalamazoo',
  'nova-home-loans-ann-arbor-kalamazoo',
] as const;

const COLLEGE_TOWN_WASHTENAW_SUPPLEMENTS = [
  'crosscountry-mortgage-southwest-michigan',
  'silverton-mortgage-ann-arbor-kalamazoo',
  'mid-tier-specialists-kalamazoo',
  'bank-of-america-mortgage-ann-arbor-kalamazoo',
];

const COLLEGE_TOWN_KALAMAZOO_SUPPLEMENTS = [
  'local-university-town-independent-mortgage',
  'guild-mortgage-ann-arbor-kalamazoo',
  'new-american-funding-ann-arbor',
  'pierpoint-mortgage-southeast-michigan',
  'professional-academic-specialists-ann-arbor',
  'university-town-community-credit-union',
  'anchor-home-mortgage-ann-arbor-kalamazoo',
  'nova-home-loans-ann-arbor-kalamazoo',
];

export const MICHIGAN_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  wayne: GREATER_DETROIT_WAYNE_SUPPLEMENTS,
  livingston: GREATER_DETROIT_LIVINGSTON_SUPPLEMENTS,
  ingham: [],
  kent: [],
  washtenaw: COLLEGE_TOWN_WASHTENAW_SUPPLEMENTS,
  kalamazoo: COLLEGE_TOWN_KALAMAZOO_SUPPLEMENTS,
};

export const GREATER_DETROITS_VALUE_POCKETS_HUB_AREAS = [
  { name: 'Dearborn', slug: 'wayne', highlight: 'Zillow top 5 US city, cultural community, accessible values' },
  { name: 'Lincoln Park', slug: 'wayne', highlight: 'Redfin top 10 neighborhood, 40% over asking, 14% YoY sales' },
  { name: 'Howell', slug: 'livingston', highlight: 'Redfin top 10 market, high-end bidding wars, page view surge' },
  { name: 'Wayne County', slug: 'wayne', highlight: 'Entry-level & transitional neighborhood demand' },
] as const;

export const LANSING_MULTI_FAMILY_INVESTOR_MAGNET_HUB_AREAS = [
  { name: 'Lansing', slug: 'ingham', highlight: 'State capital, multi-family magnet, ~6% vacancy' },
  { name: 'East Lansing', slug: 'ingham', highlight: 'University demand, scorching rent growth' },
  { name: 'Ingham County', slug: 'ingham', highlight: '$145K–$160K values, strong cap rates' },
  { name: 'Capital Region', slug: 'ingham', highlight: 'WSJ/Realtor.com top emerging market' },
] as const;

export const GRAND_RAPIDS_FAST_MOVING_CORE_HUB_AREAS = [
  { name: 'Grand Rapids', slug: 'kent', highlight: '6-day average under contract, top job market' },
  { name: 'East Grand Rapids', slug: 'kent', highlight: 'Wealthier enclave, under-15-day pending' },
  { name: 'Ada', slug: 'kent', highlight: 'Severe inventory crunch, multiple offers' },
  { name: 'Kent County', slug: 'kent', highlight: 'Healthcare & manufacturing professional demand' },
] as const;

export const ANN_ARBOR_KALAMAZOO_COLLEGE_TOWN_DEMAND_HUB_AREAS = [
  { name: 'Ann Arbor', slug: 'washtenaw', highlight: '$549K median, medical/tech/university professionals' },
  { name: 'Kalamazoo', slug: 'kalamazoo', highlight: '$245K median, out-of-state buyer surge' },
  { name: 'Washtenaw County', slug: 'washtenaw', highlight: 'Insulated luxury & mid-tier Tree Town market' },
  { name: 'Kalamazoo County', slug: 'kalamazoo', highlight: 'Affordable college-town alternative, steady appreciation' },
] as const;