import type { Lender } from '@/lib/lender/mockData';

export const NEW_JERSEY_LENDERS: Lender[] = [
  // ── National Superstars — Marlton (Burlington) & Wayne (Passaic) ─────────────
  {
    id: 'nj-01', slug: 'local-nj-suburban-independent-mortgage', name: 'Local NJ Suburban Independent Mortgage', nmlsId: '612891', type: 'Broker',
    city: 'Marlton', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Burlington', countySlug: 'burlington',
    zipCodes: ['08053', '08055', '07470'], rating: 4.9, reviewCount: 710, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 28, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Commuter Financing', 'Bidding War Expertise', '#2 Hottest US ZIP'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'Local NJ suburban independent — strong knowledge of Marlton #2 and Wayne #5 national hottest ZIP rankings.',
    website: 'https://njsuburbanindependentmortgage.com', phone: '(856) 555-6101',
  },
  {
    id: 'nj-02', slug: 'guild-mortgage-nj-suburbs', name: 'Guild Mortgage (NJ Suburbs)', nmlsId: '3274', type: 'Lender',
    city: 'Marlton', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Burlington', countySlug: 'burlington',
    zipCodes: ['08053', '08055', '08003'], rating: 4.8, reviewCount: 490, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Burlington/Passaic Operations', 'Suburban Velocity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Marlton branches — comprehensive financing across national superstar ZIPs.',
    website: 'https://guildmortgage.com', phone: '(856) 555-6102',
  },
  {
    id: 'nj-03', slug: 'new-american-funding-marlton-wayne', name: 'New American Funding (NJ)', nmlsId: '6606', type: 'Lender',
    city: 'Marlton', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Burlington', countySlug: 'burlington',
    zipCodes: ['08053', '08055', '07470'], rating: 4.9, reviewCount: 450, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Marlton / Wayne', '17–19 Day Contracts', 'High-Volume Purchase'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 17, onTimeCloseRate: 97,
    shortDescription: 'NAF Marlton team — excellent ratings for 17–19 day contracts in Realtor.com\'s #2 hottest ZIP.',
    website: 'https://newamericanfunding.com', phone: '(856) 555-6103',
  },
  {
    id: 'nj-04', slug: 'crosscountry-mortgage-nj-wayne-marlton', name: 'CrossCountry Mortgage (NJ)', nmlsId: '3029', type: 'Lender',
    city: 'Wayne', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Passaic', countySlug: 'passaic',
    zipCodes: ['07470', '08053', '07450'], rating: 4.8, reviewCount: 380, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Wayne / Marlton', 'Manhattan/Philly Commuters', 'Triple-Average Listing Views'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 19, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Wayne — experienced support for triple-average listing views and immediate bidding wars.',
    website: 'https://crosscountrymortgage.com', phone: '(973) 555-6104',
  },
  {
    id: 'nj-05', slug: 'pierpoint-mortgage-nj-suburbs', name: 'PierPoint Mortgage (NJ)', nmlsId: '112844', type: 'Broker',
    city: 'Wayne', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Passaic', countySlug: 'passaic',
    zipCodes: ['07470', '08053', '07450'], rating: 4.9, reviewCount: 185, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Marlton / Wayne', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 15, onTimeCloseRate: 98,
    shortDescription: 'Wholesale broker — speed suited to immediate bidding wars in #2 and #5 national hottest ZIPs.',
    website: 'https://pierpointmortgage.com', phone: '(973) 555-6105',
  },
  {
    id: 'nj-06', slug: 'silverton-mortgage-wayne-nj', name: 'Silverton Mortgage — Wayne', nmlsId: '1561', type: 'Lender',
    city: 'Wayne', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Passaic', countySlug: 'passaic',
    zipCodes: ['07470', '07450', '08053'], rating: 4.8, reviewCount: 165, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Top-Tier School Districts', 'Retail Local Expertise', 'Severe Under-Supply'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'Silverton Wayne retail lending — professional service for top schools and Manhattan transit access.',
    website: 'https://silvertonmortgage.com', phone: '(973) 555-6106',
  },
  {
    id: 'nj-07', slug: 'commuter-relocation-specialists-marlton-wayne', name: 'Commuter & Family Relocation Specialists (Marlton / Wayne)', nmlsId: '613827', type: 'Broker',
    city: 'Marlton', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Burlington', countySlug: 'burlington',
    zipCodes: ['08053', '07470', '08055'], rating: 4.9, reviewCount: 520, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['I-295 Corridor', 'Manhattan Transit Routes', 'Transit-Route Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 96,
    shortDescription: 'Commuter specialist — tailored for I-295 Philadelphia and Manhattan transit-route buyers.',
    website: 'https://njcommutermortgage.com', phone: '(856) 555-6107',
  },
  {
    id: 'nj-08', slug: 'nj-suburban-community-credit-union', name: 'NJ Suburban Community Credit Union', nmlsId: '659102', type: 'Credit Union',
    city: 'Marlton', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Burlington', countySlug: 'burlington',
    zipCodes: ['08053', '08055', '07470'], rating: 4.9, reviewCount: 840, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Suburban Buyers', 'National Superstar ZIPs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for buyers in national hottest ZIP codes.',
    website: 'https://njsuburbancu.org', phone: '(856) 555-6108',
  },
  {
    id: 'nj-09', slug: 'single-family-suburban-specialists-marlton-wayne', name: 'Single-Family Suburban Specialists (Marlton / Wayne)', nmlsId: '601293', type: 'Broker',
    city: 'Wayne', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Passaic', countySlug: 'passaic',
    zipCodes: ['07470', '08053', '07450'], rating: 4.9, reviewCount: 310, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 37, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Move-In-Ready Single-Family', 'Blistering Speeds', 'Severe Under-Supply'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 16, onTimeCloseRate: 97,
    shortDescription: 'Single-family specialist — expertise in severe under-supply and blistering suburban transaction speeds.',
    website: 'https://njsuburbansinglefamilymortgage.com', phone: '(973) 555-6109',
  },
  {
    id: 'nj-10', slug: 'anchor-home-mortgage-nj-suburbs', name: 'Anchor Home Mortgage (NJ Suburbs)', nmlsId: '136890', type: 'Broker',
    city: 'Wayne', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Passaic', countySlug: 'passaic',
    zipCodes: ['07470', '08053', '07450'], rating: 4.9, reviewCount: 270, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['#2 & #5 Hottest ZIPs', 'Personalized Brokerage', 'Extreme Buyer Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 17, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Realtor.com #2 Marlton and #5 Wayne national superstar ZIPs.',
    website: 'https://anchorhomemortgage.com', phone: '(973) 555-6110',
  },
  {
    id: 'nj-11', slug: 'bank-of-america-mortgage-marlton-wayne', name: 'Bank of America Mortgage (Marlton / Wayne)', nmlsId: '399802', type: 'Bank',
    city: 'Marlton', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Burlington', countySlug: 'burlington',
    zipCodes: ['08053', '07470', '08055'], rating: 4.6, reviewCount: 610, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Commuter Relocation', 'Philly/Manhattan Access', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 28, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for Philadelphia and Manhattan commuter relocations.',
    website: 'https://bankofamerica.com/mortgage', phone: '(856) 555-6111',
  },
  {
    id: 'nj-12', slug: 'nova-home-loans-nj-suburbs', name: 'Nova Home Loans (NJ Suburban Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Wayne', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Passaic', countySlug: 'passaic',
    zipCodes: ['07470', '08053', '07450'], rating: 4.8, reviewCount: 285, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Extreme Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 18, onTimeCloseRate: 94,
    shortDescription: 'NJ suburban lender — localized knowledge of extreme buyer demand and blistering transaction speeds.',
    website: 'https://novahomeloans.com', phone: '(973) 555-6112',
  },

  // ── South Jersey Shore Surge (Cape May County) ───────────────────────────────
  {
    id: 'nj-13', slug: 'local-shore-independent-mortgage', name: 'Local Shore Independent Mortgage', nmlsId: '622891', type: 'Broker',
    city: 'Wildwood', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08260', '08226', '08406'], rating: 4.9, reviewCount: 580, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Luxury Shore Financing', '54–60% YoY Spikes', 'Vacation-Rental Investors'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local shore independent — strong knowledge of Wildwood\'s 54–60% YoY price spike and luxury battlegrounds.',
    website: 'https://njshoreindependentmortgage.com', phone: '(609) 555-6213',
  },
  {
    id: 'nj-14', slug: 'guild-mortgage-south-jersey-shore', name: 'Guild Mortgage (South Jersey Shore)', nmlsId: '3274', type: 'Lender',
    city: 'Ocean City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08226', '08260', '08406'], rating: 4.8, reviewCount: 420, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Cape May Operations', 'Luxury Shore Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Cape May branches — comprehensive shore surge financing.',
    website: 'https://guildmortgage.com', phone: '(609) 555-6214',
  },
  {
    id: 'nj-15', slug: 'new-american-funding-south-jersey-shore', name: 'New American Funding (South Jersey)', nmlsId: '6606', type: 'Lender',
    city: 'Wildwood', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08260', '08226', '08406'], rating: 4.9, reviewCount: 400, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Wildwood / Ocean City', 'Ultra-Luxury Battlegrounds', 'High-Volume Purchase'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'NAF Wildwood team — excellent ratings for ultra-luxury shore transactions and unprecedented growth.',
    website: 'https://newamericanfunding.com', phone: '(609) 555-6215',
  },
  {
    id: 'nj-16', slug: 'crosscountry-mortgage-south-jersey-shore', name: 'CrossCountry Mortgage (South Jersey)', nmlsId: '3029', type: 'Lender',
    city: 'North Wildwood', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08260', '08406', '08226'], rating: 4.8, reviewCount: 355, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['North Wildwood / Ventnor', 'Luxury Investors', 'Second-Home Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry South Jersey — experienced support for vacation-rental and luxury investor demand.',
    website: 'https://crosscountrymortgage.com', phone: '(609) 555-6216',
  },
  {
    id: 'nj-17', slug: 'pierpoint-mortgage-nj-shore', name: 'PierPoint Mortgage (NJ Shore)', nmlsId: '112844', type: 'Broker',
    city: 'Ocean City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08226', '08260', '08406'], rating: 4.9, reviewCount: 175, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Ocean City / Wildwood', 'Premium Properties', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to unprecedented coastal growth and $1.4M+ Ocean City medians.',
    website: 'https://pierpointmortgage.com', phone: '(609) 555-6217',
  },
  {
    id: 'nj-18', slug: 'silverton-mortgage-ocean-city', name: 'Silverton Mortgage — Ocean City', nmlsId: '1561', type: 'Lender',
    city: 'Ocean City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08226', '08260', '08406'], rating: 4.8, reviewCount: 160, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['$1.4M+ Medians', 'Retail Local Expertise', 'Luxury Shore'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'Silverton Ocean City retail lending — professional service for state-leading shore appreciation.',
    website: 'https://silvertonmortgage.com', phone: '(609) 555-6218',
  },
  {
    id: 'nj-19', slug: 'luxury-investor-specialists-ventnor-wildwood', name: 'Luxury & Investor Specialists (Ventnor / Wildwood)', nmlsId: '623827', type: 'Broker',
    city: 'Ventnor City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08406', '08260', '08226'], rating: 4.9, reviewCount: 470, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Vacation-Rental Programs', '60% YoY to $963K', 'Luxury Investors'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Luxury investor specialist — tailored for Ventnor\'s 60% jump and Wildwood\'s top-10 national hot market.',
    website: 'https://njshoreinvestormortgage.com', phone: '(609) 555-6219',
  },
  {
    id: 'nj-20', slug: 'cape-may-community-credit-union', name: 'Cape May Community Credit Union', nmlsId: '669102', type: 'Credit Union',
    city: 'Wildwood', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08260', '08226', '08406'], rating: 4.9, reviewCount: 780, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Member Rates', 'Shore Buyers', 'Surging Coastal Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for buyers in Cape May\'s unprecedented shore surge.',
    website: 'https://capemaycu.org', phone: '(609) 555-6220',
  },
  {
    id: 'nj-21', slug: 'waterfront-second-home-specialists-ocean-city', name: 'Waterfront & Second-Home Specialists (Ocean City)', nmlsId: '621293', type: 'Broker',
    city: 'Ocean City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08226', '08260', '08406'], rating: 4.9, reviewCount: 300, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Waterfront Luxury', 'Investment Financing', 'Top 10 National Hot Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'Waterfront specialist — expertise in Ocean City $1.4M+ medians and North Wildwood investment demand.',
    website: 'https://oceancitywaterfrontmortgage.com', phone: '(609) 555-6221',
  },
  {
    id: 'nj-22', slug: 'anchor-home-mortgage-south-jersey-shore', name: 'Anchor Home Mortgage (South Jersey Shore)', nmlsId: '136890', type: 'Broker',
    city: 'Wildwood', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08260', '08406', '08226'], rating: 4.9, reviewCount: 260, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Luxury Buyer Influx', 'Personalized Brokerage', 'State-Leading Appreciation'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on luxury buyer and investor influx along the South Jersey coast.',
    website: 'https://anchorhomemortgage.com', phone: '(609) 555-6222',
  },
  {
    id: 'nj-23', slug: 'bank-of-america-mortgage-south-jersey-shore', name: 'Bank of America Mortgage (Ocean City / Wildwood)', nmlsId: '399802', type: 'Bank',
    city: 'Ocean City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08226', '08260', '08406'], rating: 4.6, reviewCount: 550, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Luxury Relocation', 'Second Homes', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for high-end shore properties and luxury relocations.',
    website: 'https://bankofamerica.com/mortgage', phone: '(609) 555-6223',
  },
  {
    id: 'nj-24', slug: 'nova-home-loans-south-jersey-shore', name: 'Nova Home Loans (South Jersey Shore Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Ventnor City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may',
    zipCodes: ['08406', '08260', '08226'], rating: 4.8, reviewCount: 270, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Luxury Family Financing', 'Shore Surge'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 21, onTimeCloseRate: 94,
    shortDescription: 'South Jersey shore lender — localized knowledge of state-leading year-over-year appreciation.',
    website: 'https://novahomeloans.com', phone: '(609) 555-6224',
  },

  // ── Sweet Spot Commuter Towns (Union / Middlesex / Essex) ────────────────────
  {
    id: 'nj-25', slug: 'local-commuter-town-independent-mortgage', name: 'Local Commuter-Town Independent Mortgage', nmlsId: '632891', type: 'Broker',
    city: 'Cranford', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Union', countySlug: 'union',
    zipCodes: ['07016', '07065', '07042'], rating: 4.9, reviewCount: 640, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 30, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Rail-Access Financing', '95%+ Above-Ask Sales', 'Tech-Professional Commuters'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 14, onTimeCloseRate: 97,
    shortDescription: 'Local commuter-town independent — strong knowledge of 95%+ above-ask sales across Union, Middlesex, and Essex.',
    website: 'https://njcommutertownmortgage.com', phone: '(908) 555-6325',
  },
  {
    id: 'nj-26', slug: 'guild-mortgage-nj-commuter-towns', name: 'Guild Mortgage (NJ Commuter Towns)', nmlsId: '3274', type: 'Lender',
    city: 'Cranford', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Union', countySlug: 'union',
    zipCodes: ['07016', '07065', '08817'], rating: 4.8, reviewCount: 460, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Union/Middlesex/Essex', 'Commuter Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with commuter-town branches — comprehensive financing across sweet-spot rail corridors.',
    website: 'https://guildmortgage.com', phone: '(908) 555-6326',
  },
  {
    id: 'nj-27', slug: 'new-american-funding-cranford-rahway', name: 'New American Funding (NJ)', nmlsId: '6606', type: 'Lender',
    city: 'Cranford', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Union', countySlug: 'union',
    zipCodes: ['07016', '07065', '07042'], rating: 4.9, reviewCount: 430, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Cranford / Rahway', '13-Day Median Contracts', 'High-Volume Purchase'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 13, onTimeCloseRate: 97,
    shortDescription: 'NAF Cranford team — excellent ratings for 13-day median contracts on the Raritan Valley line.',
    website: 'https://newamericanfunding.com', phone: '(908) 555-6327',
  },
  {
    id: 'nj-28', slug: 'crosscountry-mortgage-north-central-nj-edison', name: 'CrossCountry Mortgage (North/Central NJ)', nmlsId: '3029', type: 'Lender',
    city: 'Edison', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['08817', '08901', '07016'], rating: 4.8, reviewCount: 395, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Edison / New Brunswick', 'Helix Bio-Tech Professionals', 'Multi-Family Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 18, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Edison — experienced support for Helix innovation district and intense multi-family demand.',
    website: 'https://crosscountrymortgage.com', phone: '(732) 555-6328',
  },
  {
    id: 'nj-29', slug: 'pierpoint-mortgage-nj-commuter-towns', name: 'PierPoint Mortgage (NJ)', nmlsId: '112844', type: 'Broker',
    city: 'Montclair', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Essex', countySlug: 'essex',
    zipCodes: ['07042', '07040', '07016'], rating: 4.9, reviewCount: 190, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Montclair / Maplewood', 'Elite School Districts', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 11, onTimeCloseRate: 98,
    shortDescription: 'Wholesale broker — speed suited to 11-day pending times and 105%+ sale-to-list ratios.',
    website: 'https://pierpointmortgage.com', phone: '(973) 555-6329',
  },
  {
    id: 'nj-30', slug: 'silverton-mortgage-cranford-montclair', name: 'Silverton Mortgage — Cranford / Montclair', nmlsId: '1561', type: 'Lender',
    city: 'Cranford', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Union', countySlug: 'union',
    zipCodes: ['07016', '07042', '07040'], rating: 4.8, reviewCount: 170, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Walkable Downtowns', 'Retail Local Expertise', '$795K Cranford Median'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 20, onTimeCloseRate: 95,
    shortDescription: 'Silverton retail lending — professional service for walkable downtowns and elite commuter corridors.',
    website: 'https://silvertonmortgage.com', phone: '(908) 555-6330',
  },
  {
    id: 'nj-31', slug: 'tech-commuter-specialists-edison-nb', name: 'Tech & Commuter Specialists (Edison / New Brunswick)', nmlsId: '633827', type: 'Broker',
    city: 'Edison', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['08817', '08901', '07065'], rating: 4.9, reviewCount: 510, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bio-Tech Programs', 'Helix District', 'Rail-Access Commuters'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 15, onTimeCloseRate: 96,
    shortDescription: 'Tech commuter specialist — tailored for Middlesex innovation district growth past $605K medians.',
    website: 'https://njtechcommutermortgage.com', phone: '(732) 555-6331',
  },
  {
    id: 'nj-32', slug: 'nj-commuter-community-credit-union', name: 'NJ Commuter Community Credit Union', nmlsId: '679102', type: 'Credit Union',
    city: 'Rahway', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Union', countySlug: 'union',
    zipCodes: ['07065', '07016', '07042'], rating: 4.9, reviewCount: 820, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Commuter Buyers', 'High-Momentum Towns'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for buyers in direct-rail commuter sweet spots.',
    website: 'https://njcommutercu.org', phone: '(732) 555-6332',
  },
  {
    id: 'nj-33', slug: 'single-family-arts-cultural-specialists-montclair-maplewood', name: 'Single-Family & Arts-Cultural Specialists (Montclair / Maplewood)', nmlsId: '631293', type: 'Broker',
    city: 'Montclair', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Essex', countySlug: 'essex',
    zipCodes: ['07042', '07040', '07016'], rating: 4.9, reviewCount: 320, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Cultural Scene Financing', 'Elite Schools', '105%+ Sale-to-List'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 12, onTimeCloseRate: 96,
    shortDescription: 'Arts-cultural specialist — expertise in Montclair/Maplewood elite schools and 105%+ sale-to-list ratios.',
    website: 'https://montclairmaplewoodmortgage.com', phone: '(973) 555-6333',
  },
  {
    id: 'nj-34', slug: 'anchor-home-mortgage-rahway-cranford', name: 'Anchor Home Mortgage (Rahway / Cranford)', nmlsId: '136890', type: 'Broker',
    city: 'Rahway', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Union', countySlug: 'union',
    zipCodes: ['07065', '07016', '08817'], rating: 4.9, reviewCount: 275, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 46, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['$525K Rahway Entry', 'Value Play Financing', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 16, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Rahway value play and Cranford Raritan Valley momentum.',
    website: 'https://anchorhomemortgage.com', phone: '(732) 555-6334',
  },
  {
    id: 'nj-35', slug: 'bank-of-america-mortgage-edison-montclair', name: 'Bank of America Mortgage (Edison / Montclair)', nmlsId: '399802', type: 'Bank',
    city: 'Edison', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['08817', '07042', '08901'], rating: 4.6, reviewCount: 580, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Professional Relocation', 'Manhattan Rail Commuters', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 28, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for tech professionals and Manhattan rail commuters.',
    website: 'https://bankofamerica.com/mortgage', phone: '(732) 555-6335',
  },
  {
    id: 'nj-36', slug: 'nova-home-loans-nj-commuter-towns', name: 'Nova Home Loans (NJ Commuter Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Maplewood', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Essex', countySlug: 'essex',
    zipCodes: ['07040', '07042', '07016'], rating: 4.8, reviewCount: 285, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Direct Rail Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 17, onTimeCloseRate: 94,
    shortDescription: 'NJ commuter lender — localized knowledge of direct rail access and sweet-spot town momentum.',
    website: 'https://novahomeloans.com', phone: '(973) 555-6336',
  },

  // ── Hudson River Gold Coast (Jersey City & Hoboken) ──────────────────────────
  {
    id: 'nj-37', slug: 'local-hudson-waterfront-independent-mortgage', name: 'Local Hudson Waterfront Independent Mortgage', nmlsId: '642891', type: 'Broker',
    city: 'Jersey City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07302', '07030', '07310'], rating: 4.9, reviewCount: 690, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 26, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Waterfront Luxury', 'Return-to-Office Demand', 'High-Density Financing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 16, onTimeCloseRate: 97,
    shortDescription: 'Local Hudson waterfront independent — strong knowledge of return-to-office driven Gold Coast demand.',
    website: 'https://hudsonwaterfrontmortgage.com', phone: '(201) 555-6437',
  },
  {
    id: 'nj-38', slug: 'guild-mortgage-hudson-county', name: 'Guild Mortgage (Hudson County)', nmlsId: '3274', type: 'Lender',
    city: 'Jersey City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07302', '07030', '07310'], rating: 4.8, reviewCount: 480, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Hudson County Operations', 'Waterfront Luxury'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 23, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Hudson County branches — comprehensive Gold Coast waterfront financing.',
    website: 'https://guildmortgage.com', phone: '(201) 555-6438',
  },
  {
    id: 'nj-39', slug: 'new-american-funding-jersey-city-hoboken', name: 'New American Funding (Jersey City)', nmlsId: '6606', type: 'Lender',
    city: 'Jersey City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07302', '07030', '07310'], rating: 4.9, reviewCount: 440, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Jersey City / Hoboken', 'High-Density Absorption', 'High-Volume Purchase'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 96,
    shortDescription: 'NAF Jersey City team — excellent ratings for rapid high-density residential absorption.',
    website: 'https://newamericanfunding.com', phone: '(201) 555-6439',
  },
  {
    id: 'nj-40', slug: 'crosscountry-mortgage-hudson-gold-coast', name: 'CrossCountry Mortgage (North NJ)', nmlsId: '3029', type: 'Lender',
    city: 'Hoboken', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07030', '07302', '07310'], rating: 4.8, reviewCount: 370, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Hoboken / Jersey City', 'Manhattan Commuters', '22.6% Luxury Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 19, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Hudson — experienced support for Hoboken\'s 22.6% YoY luxury growth.',
    website: 'https://crosscountrymortgage.com', phone: '(201) 555-6440',
  },
  {
    id: 'nj-41', slug: 'pierpoint-mortgage-hudson-waterfront', name: 'PierPoint Mortgage (Hudson Waterfront)', nmlsId: '112844', type: 'Broker',
    city: 'Jersey City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07302', '07030', '07310'], rating: 4.9, reviewCount: 180, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Jersey City / Hoboken', 'Waterfront Properties', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 14, onTimeCloseRate: 98,
    shortDescription: 'Wholesale broker — speed suited to powerhouse Hudson River waterfront market dynamics.',
    website: 'https://pierpointmortgage.com', phone: '(201) 555-6441',
  },
  {
    id: 'nj-42', slug: 'silverton-mortgage-hoboken', name: 'Silverton Mortgage — Hoboken', nmlsId: '1561', type: 'Lender',
    city: 'Hoboken', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07030', '07302', '07310'], rating: 4.8, reviewCount: 168, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Waterfront Expertise', 'Retail Local Lending', 'New Developments'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 21, onTimeCloseRate: 95,
    shortDescription: 'Silverton Hoboken retail lending — professional service for new residential developments.',
    website: 'https://silvertonmortgage.com', phone: '(201) 555-6442',
  },
  {
    id: 'nj-43', slug: 'luxury-commuter-specialists-jersey-city-hoboken', name: 'Luxury & Commuter Specialists (Jersey City / Hoboken)', nmlsId: '643827', type: 'Broker',
    city: 'Hoboken', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07030', '07302', '07310'], rating: 4.9, reviewCount: 500, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Return-to-Office Programs', 'High-End Commuters', 'Manhattan-Adjacent Luxury'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 15, onTimeCloseRate: 96,
    shortDescription: 'Luxury commuter specialist — tailored for return-to-office mandates and Manhattan-adjacent buyers.',
    website: 'https://hudsonluxurycommutermortgage.com', phone: '(201) 555-6443',
  },
  {
    id: 'nj-44', slug: 'hudson-gold-coast-community-credit-union', name: 'Hudson Gold Coast Community Credit Union', nmlsId: '689102', type: 'Credit Union',
    city: 'Jersey City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07302', '07030', '07310'], rating: 4.9, reviewCount: 860, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Member Rates', 'Gold Coast Buyers', 'High-Growth Waterfront'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for buyers in the Hudson River Gold Coast powerhouse.',
    website: 'https://hudsongoldcoastcu.org', phone: '(201) 555-6444',
  },
  {
    id: 'nj-45', slug: 'high-density-waterfront-specialists-jersey-city', name: 'High-Density & Waterfront Specialists (Jersey City)', nmlsId: '641293', type: 'Broker',
    city: 'Jersey City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07302', '07030', '07310'], rating: 4.9, reviewCount: 335, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['New Developments', 'Luxury Condo Financing', 'Rapid Absorption'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 17, onTimeCloseRate: 96,
    shortDescription: 'High-density specialist — expertise in Jersey City\'s rapid absorption and waterfront luxury condos.',
    website: 'https://jerseycitywaterfrontmortgage.com', phone: '(201) 555-6445',
  },
  {
    id: 'nj-46', slug: 'anchor-home-mortgage-hudson-gold-coast', name: 'Anchor Home Mortgage (Hudson Gold Coast)', nmlsId: '136890', type: 'Broker',
    city: 'Hoboken', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07030', '07302', '07310'], rating: 4.9, reviewCount: 290, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 44, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['22.6% Luxury Surge', 'Personalized Brokerage', 'Waterfront Properties'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 16, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Hoboken luxury surge and Jersey City waterfront demand.',
    website: 'https://anchorhomemortgage.com', phone: '(201) 555-6446',
  },
  {
    id: 'nj-47', slug: 'bank-of-america-mortgage-jersey-city-hoboken', name: 'Bank of America Mortgage (Jersey City / Hoboken)', nmlsId: '399802', type: 'Bank',
    city: 'Jersey City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07302', '07030', '07310'], rating: 4.6, reviewCount: 600, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Commuter Financing', 'Return-to-Office', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 29, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for return-to-office mandates and Gold Coast commuters.',
    website: 'https://bankofamerica.com/mortgage', phone: '(201) 555-6447',
  },
  {
    id: 'nj-48', slug: 'nova-home-loans-hudson-gold-coast', name: 'Nova Home Loans (Hudson Gold Coast Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Jersey City', state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson',
    zipCodes: ['07302', '07030', '07310'], rating: 4.8, reviewCount: 295, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Luxury Family Financing', 'Powerhouse Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 18, onTimeCloseRate: 94,
    shortDescription: 'Hudson Gold Coast lender — localized knowledge of powerhouse waterfront demand and price growth.',
    website: 'https://novahomeloans.com', phone: '(201) 555-6448',
  },
];

export const NATIONAL_SUPERSTARS_SUBURBAN_VELOCITY_LENDER_SLUGS = [
  'local-nj-suburban-independent-mortgage',
  'guild-mortgage-nj-suburbs',
  'new-american-funding-marlton-wayne',
  'crosscountry-mortgage-nj-wayne-marlton',
  'pierpoint-mortgage-nj-suburbs',
  'silverton-mortgage-wayne-nj',
  'commuter-relocation-specialists-marlton-wayne',
  'nj-suburban-community-credit-union',
  'single-family-suburban-specialists-marlton-wayne',
  'anchor-home-mortgage-nj-suburbs',
  'bank-of-america-mortgage-marlton-wayne',
  'nova-home-loans-nj-suburbs',
] as const;

const NATIONAL_SUPERSTARS_BURLINGTON_SUPPLEMENTS = [
  'crosscountry-mortgage-nj-wayne-marlton',
  'pierpoint-mortgage-nj-suburbs',
  'silverton-mortgage-wayne-nj',
  'single-family-suburban-specialists-marlton-wayne',
  'anchor-home-mortgage-nj-suburbs',
  'nova-home-loans-nj-suburbs',
];

const NATIONAL_SUPERSTARS_PASSAIC_SUPPLEMENTS = [
  'local-nj-suburban-independent-mortgage',
  'guild-mortgage-nj-suburbs',
  'new-american-funding-marlton-wayne',
  'commuter-relocation-specialists-marlton-wayne',
  'nj-suburban-community-credit-union',
  'bank-of-america-mortgage-marlton-wayne',
];

export const SOUTH_JERSEY_SHORE_SURGE_LENDER_SLUGS = [
  'local-shore-independent-mortgage',
  'guild-mortgage-south-jersey-shore',
  'new-american-funding-south-jersey-shore',
  'crosscountry-mortgage-south-jersey-shore',
  'pierpoint-mortgage-nj-shore',
  'silverton-mortgage-ocean-city',
  'luxury-investor-specialists-ventnor-wildwood',
  'cape-may-community-credit-union',
  'waterfront-second-home-specialists-ocean-city',
  'anchor-home-mortgage-south-jersey-shore',
  'bank-of-america-mortgage-south-jersey-shore',
  'nova-home-loans-south-jersey-shore',
] as const;

export const SWEET_SPOT_COMMUTER_TOWNS_LENDER_SLUGS = [
  'local-commuter-town-independent-mortgage',
  'guild-mortgage-nj-commuter-towns',
  'new-american-funding-cranford-rahway',
  'crosscountry-mortgage-north-central-nj-edison',
  'pierpoint-mortgage-nj-commuter-towns',
  'silverton-mortgage-cranford-montclair',
  'tech-commuter-specialists-edison-nb',
  'nj-commuter-community-credit-union',
  'single-family-arts-cultural-specialists-montclair-maplewood',
  'anchor-home-mortgage-rahway-cranford',
  'bank-of-america-mortgage-edison-montclair',
  'nova-home-loans-nj-commuter-towns',
] as const;

export const HUDSON_RIVER_GOLD_COAST_LENDER_SLUGS = [
  'local-hudson-waterfront-independent-mortgage',
  'guild-mortgage-hudson-county',
  'new-american-funding-jersey-city-hoboken',
  'crosscountry-mortgage-hudson-gold-coast',
  'pierpoint-mortgage-hudson-waterfront',
  'silverton-mortgage-hoboken',
  'luxury-commuter-specialists-jersey-city-hoboken',
  'hudson-gold-coast-community-credit-union',
  'high-density-waterfront-specialists-jersey-city',
  'anchor-home-mortgage-hudson-gold-coast',
  'bank-of-america-mortgage-jersey-city-hoboken',
  'nova-home-loans-hudson-gold-coast',
] as const;

const COMMUTER_TOWNS_UNION_SUPPLEMENTS = [
  'crosscountry-mortgage-north-central-nj-edison',
  'tech-commuter-specialists-edison-nb',
  'bank-of-america-mortgage-edison-montclair',
  'pierpoint-mortgage-nj-commuter-towns',
  'single-family-arts-cultural-specialists-montclair-maplewood',
  'nova-home-loans-nj-commuter-towns',
];

const COMMUTER_TOWNS_MIDDLESEX_SUPPLEMENTS = [
  'local-commuter-town-independent-mortgage',
  'guild-mortgage-nj-commuter-towns',
  'new-american-funding-cranford-rahway',
  'silverton-mortgage-cranford-montclair',
  'nj-commuter-community-credit-union',
  'anchor-home-mortgage-rahway-cranford',
  'pierpoint-mortgage-nj-commuter-towns',
  'single-family-arts-cultural-specialists-montclair-maplewood',
  'nova-home-loans-nj-commuter-towns',
];

const COMMUTER_TOWNS_ESSEX_SUPPLEMENTS = [
  'local-commuter-town-independent-mortgage',
  'guild-mortgage-nj-commuter-towns',
  'new-american-funding-cranford-rahway',
  'silverton-mortgage-cranford-montclair',
  'nj-commuter-community-credit-union',
  'anchor-home-mortgage-rahway-cranford',
  'crosscountry-mortgage-north-central-nj-edison',
  'tech-commuter-specialists-edison-nb',
  'bank-of-america-mortgage-edison-montclair',
];

export const NEW_JERSEY_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  burlington: NATIONAL_SUPERSTARS_BURLINGTON_SUPPLEMENTS,
  passaic: NATIONAL_SUPERSTARS_PASSAIC_SUPPLEMENTS,
  'cape-may': [],
  union: COMMUTER_TOWNS_UNION_SUPPLEMENTS,
  middlesex: COMMUTER_TOWNS_MIDDLESEX_SUPPLEMENTS,
  essex: COMMUTER_TOWNS_ESSEX_SUPPLEMENTS,
  hudson: [],
};

export const NATIONAL_SUPERSTARS_SUBURBAN_VELOCITY_HUB_AREAS = [
  { name: 'Marlton', slug: 'burlington', highlight: 'Realtor.com #2 hottest US ZIP, 17–19 day contracts' },
  { name: 'Wayne', slug: 'passaic', highlight: '#5 nationally, top schools, Manhattan transit' },
  { name: 'Burlington County', slug: 'burlington', highlight: 'I-295 Philly commuter sweet spot' },
  { name: 'Passaic County', slug: 'passaic', highlight: 'Severe under-supply, immediate bidding wars' },
] as const;

export const SOUTH_JERSEY_SHORE_SURGE_HUB_AREAS = [
  { name: 'Wildwood', slug: 'cape-may', highlight: '54–60% YoY spike, top 10 national hot market' },
  { name: 'North Wildwood', slug: 'cape-may', highlight: 'State-leading appreciation, vacation-rental surge' },
  { name: 'Ocean City', slug: 'cape-may', highlight: '$1.4M+ medians, 25%+ YoY luxury battleground' },
  { name: 'Ventnor City', slug: 'cape-may', highlight: '60% jump to $963K, investor influx' },
] as const;

export const SWEET_SPOT_COMMUTER_TOWNS_HUB_AREAS = [
  { name: 'Cranford', slug: 'union', highlight: '$795K median, 13-day sales, Raritan Valley line' },
  { name: 'Rahway', slug: 'union', highlight: '$525K entry value play, projected 2026 growth' },
  { name: 'Edison', slug: 'middlesex', highlight: 'Helix bio-tech district, $605K+ median surge' },
  { name: 'Montclair', slug: 'essex', highlight: '11-day pending, 105%+ sale-to-list, elite schools' },
] as const;

export const HUDSON_RIVER_GOLD_COAST_HUB_AREAS = [
  { name: 'Jersey City', slug: 'hudson', highlight: 'Rapid high-density absorption, waterfront powerhouse' },
  { name: 'Hoboken', slug: 'hudson', highlight: '22.6% YoY luxury growth, return-to-office demand' },
  { name: 'Hudson County', slug: 'hudson', highlight: 'Manhattan-adjacent Gold Coast momentum' },
  { name: 'Hudson Waterfront', slug: 'hudson', highlight: 'New developments along the Hudson River' },
] as const;