import type { Lender } from '@/lib/lender/mockData';

export const NEW_YORK_LENDERS: Lender[] = [
  // ── Upstate Powerhouses — Buffalo (Erie County) ────────────────────────────
  {
    id: 'ny-01', slug: 'local-buffalo-independent-mortgage', name: 'Local Buffalo Independent Mortgage', nmlsId: '452891', type: 'Broker',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14202', '14203'], rating: 4.9, reviewCount: 620, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Affordable Entry Financing', 'Healthcare/Education Relocation', 'Low-Inventory Bidding Wars'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local Buffalo independent — strong knowledge of low-inventory bidding wars and affordable entry in one of the country\'s hottest markets.',
    website: 'https://buffaloindependentmortgage.com', phone: '(716) 555-3101',
  },
  {
    id: 'ny-02', slug: 'guild-mortgage-buffalo', name: 'Guild Mortgage (Buffalo)', nmlsId: '3274', type: 'Lender',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14214', '14216'], rating: 4.8, reviewCount: 445, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Erie County Operations', 'Affordable & Bidding-War Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Buffalo branches — comprehensive financing for first-time buyers in low-inventory, above-asking markets.',
    website: 'https://guildmortgage.com', phone: '(716) 555-3102',
  },
  {
    id: 'ny-03', slug: 'new-american-funding-buffalo', name: 'New American Funding (Buffalo)', nmlsId: '6606', type: 'Lender',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14202', '14220'], rating: 4.9, reviewCount: 390, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Climate-Refuge Buyers', 'Affordable Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Buffalo team — excellent ratings for climate-refuge and affordable-market purchase volume.',
    website: 'https://newamericanfunding.com', phone: '(716) 555-3103',
  },
  {
    id: 'ny-04', slug: 'crosscountry-mortgage-western-ny', name: 'CrossCountry Mortgage (Western NY)', nmlsId: '3029', type: 'Lender',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14203', '14214'], rating: 4.8, reviewCount: 335, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Above-Asking Sales Support', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Western NY teams — experienced support for first-time buyers where 65% of homes sell above asking.',
    website: 'https://crosscountrymortgage.com', phone: '(716) 555-3104',
  },
  {
    id: 'ny-05', slug: 'pierpoint-mortgage-upstate-ny', name: 'PierPoint Mortgage (Upstate NY)', nmlsId: '112844', type: 'Broker',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14202', '14216'], rating: 4.9, reviewCount: 165, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Low DOM Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to low DOM and low inventory in Buffalo\'s top-hot market.',
    website: 'https://pierpointmortgage.com', phone: '(716) 555-3105',
  },
  {
    id: 'ny-06', slug: 'silverton-mortgage-buffalo', name: 'Silverton Mortgage — Buffalo', nmlsId: '1561', type: 'Lender',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14214', '14220'], rating: 4.8, reviewCount: 148, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Healthcare/Education Hub', 'Retail Local Expertise', 'Hot-Market Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Buffalo retail lending — professional service for healthcare and education hub relocations.',
    website: 'https://silvertonmortgage.com', phone: '(716) 555-3106',
  },
  {
    id: 'ny-07', slug: 'veterans-first-time-mortgage-buffalo', name: 'Veterans & First-Time Buyer Specialists (Buffalo)', nmlsId: '463827', type: 'Broker',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14202', '14203'], rating: 4.9, reviewCount: 510, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['VA Loan Programs', 'Entry-Level Buyers', 'Affordable Median Price'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'VA and first-time specialist — tailored for affordable median price buyers in Buffalo\'s competitive market.',
    website: 'https://buffalovafirstmortgage.com', phone: '(716) 555-3107',
  },
  {
    id: 'ny-08', slug: 'erie-community-credit-union-buffalo', name: 'Erie Community Credit Union (Buffalo)', nmlsId: '449102', type: 'Credit Union',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14214', '14216'], rating: 4.9, reviewCount: 820, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 56, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Erie County CU', 'Affordable Options'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates and affordable options in one of the country\'s top-hot markets.',
    website: 'https://eriecommunitycu.org', phone: '(716) 555-3108',
  },
  {
    id: 'ny-09', slug: 'new-construction-climate-refuge-mortgage-buffalo', name: 'New Construction & Climate-Refuge Specialists (Buffalo)', nmlsId: '471293', type: 'Broker',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14220', '14203'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Build Financing', 'Climate Refuge Migration', '40% Fewer Homes for Sale'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'New construction specialist — expertise in lifestyle migration and tight Buffalo inventory.',
    website: 'https://buffaloclimatemortgage.com', phone: '(716) 555-3109',
  },
  {
    id: 'ny-10', slug: 'anchor-home-mortgage-buffalo', name: 'Anchor Home Mortgage (Buffalo)', nmlsId: '136890', type: 'Broker',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14202', '14214'], rating: 4.9, reviewCount: 255, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['$227K–$277K Affordability', 'Personalized Brokerage', 'Upstate Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on median affordability and personalized Upstate buyer service.',
    website: 'https://anchorhomemortgage.com', phone: '(716) 555-3110',
  },
  {
    id: 'ny-11', slug: 'bank-of-america-mortgage-buffalo', name: 'Bank of America Mortgage (Buffalo)', nmlsId: '399802', type: 'Bank',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14203', '14216'], rating: 4.6, reviewCount: 580, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Education/Healthcare Jobs', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for education and healthcare relocation in Buffalo.',
    website: 'https://bankofamerica.com/mortgage', phone: '(716) 555-3111',
  },
  {
    id: 'ny-12', slug: 'nova-home-loans-buffalo', name: 'Nova Home Loans (Buffalo Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Buffalo', state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie',
    zipCodes: ['14201', '14202', '14220'], rating: 4.8, reviewCount: 265, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Bidding War Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Buffalo lender — localized knowledge of investor and family financing in one of the country\'s hottest markets.',
    website: 'https://novahomeloans.com', phone: '(716) 555-3112',
  },

  // ── Upstate Powerhouses — Albany (Capital District) ────────────────────────
  {
    id: 'ny-13', slug: 'local-albany-capital-district-independent-mortgage', name: 'Local Capital District Independent Mortgage', nmlsId: '458192', type: 'Broker',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12208', '12210'], rating: 4.9, reviewCount: 540, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Capital District Financing', 'Supply-Demand Imbalance', 'Low DOM Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Local Capital District independent — strong knowledge of supply-and-demand imbalance and steady Albany activity.',
    website: 'https://capitaldistrictmortgage.com', phone: '(518) 555-3201',
  },
  {
    id: 'ny-14', slug: 'guild-mortgage-albany', name: 'Guild Mortgage (Albany)', nmlsId: '3274', type: 'Lender',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12205', '12208'], rating: 4.8, reviewCount: 410, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Albany County Operations', 'Capital District Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Albany branches — comprehensive Capital District financing for steady, competitive markets.',
    website: 'https://guildmortgage.com', phone: '(518) 555-3202',
  },
  {
    id: 'ny-15', slug: 'new-american-funding-albany', name: 'New American Funding (Albany)', nmlsId: '6606', type: 'Lender',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12210', '12205'], rating: 4.9, reviewCount: 365, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Government & Education Hub', 'Low Inventory'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Albany team — excellent ratings for Capital District purchase and refinance volume.',
    website: 'https://newamericanfunding.com', phone: '(518) 555-3203',
  },
  {
    id: 'ny-16', slug: 'crosscountry-mortgage-capital-district', name: 'CrossCountry Mortgage (Capital District)', nmlsId: '3029', type: 'Lender',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12208', '12210'], rating: 4.8, reviewCount: 310, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Steady Activity Markets', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Capital District teams — experienced support for first-time buyers in low-DOM Albany markets.',
    website: 'https://crosscountrymortgage.com', phone: '(518) 555-3204',
  },
  {
    id: 'ny-17', slug: 'pierpoint-mortgage-albany', name: 'PierPoint Mortgage (Albany)', nmlsId: '112844', type: 'Broker',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12205', '12208'], rating: 4.9, reviewCount: 155, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Capital District Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to supply-and-demand imbalance in Albany\'s steady hot market.',
    website: 'https://pierpointmortgage.com', phone: '(518) 555-3205',
  },
  {
    id: 'ny-18', slug: 'silverton-mortgage-albany', name: 'Silverton Mortgage — Albany', nmlsId: '1561', type: 'Lender',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12210', '12205'], rating: 4.8, reviewCount: 138, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Government Sector Hub', 'Retail Local Expertise', 'Low DOM Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Albany retail lending — professional service for Capital District government and education hub buyers.',
    website: 'https://silvertonmortgage.com', phone: '(518) 555-3206',
  },
  {
    id: 'ny-19', slug: 'veterans-first-time-mortgage-albany', name: 'Veterans & First-Time Buyer Specialists (Albany)', nmlsId: '467384', type: 'Broker',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12208', '12210'], rating: 4.9, reviewCount: 445, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 41, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['VA Loan Programs', 'Entry-Level Programs', 'Affordable Capital District'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'VA and first-time specialist — tailored for affordable entry in Albany\'s competitive Capital District.',
    website: 'https://albanyvafirstmortgage.com', phone: '(518) 555-3207',
  },
  {
    id: 'ny-20', slug: 'capital-district-community-credit-union', name: 'Capital District Community Credit Union', nmlsId: '451829', type: 'Credit Union',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12205', '12208'], rating: 4.9, reviewCount: 760, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 57, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Albany County CU', 'Community-Focused Lending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for Capital District buyers in steady, high-activity markets.',
    website: 'https://capitaldistrictcu.org', phone: '(518) 555-3208',
  },
  {
    id: 'ny-21', slug: 'supply-demand-specialist-mortgage-albany', name: 'Supply-Demand & New Construction Specialists (Albany)', nmlsId: '474618', type: 'Broker',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12210', '12205'], rating: 4.9, reviewCount: 275, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 39, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Build Financing', 'Supply-Demand Imbalance', 'Low DOM Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Supply-demand specialist — expertise in new construction and tight Albany County inventory.',
    website: 'https://albanysupplymortgage.com', phone: '(518) 555-3209',
  },
  {
    id: 'ny-22', slug: 'anchor-home-mortgage-albany', name: 'Anchor Home Mortgage (Albany)', nmlsId: '136890', type: 'Broker',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12208', '12210'], rating: 4.9, reviewCount: 230, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Brokerage', 'Capital District Buyers', 'Steady Activity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — personalized Capital District service for Upstate powerhouse buyers.',
    website: 'https://anchorhomemortgage.com', phone: '(518) 555-3210',
  },
  {
    id: 'ny-23', slug: 'bank-of-america-mortgage-albany', name: 'Bank of America Mortgage (Albany)', nmlsId: '399802', type: 'Bank',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12205', '12208'], rating: 4.6, reviewCount: 520, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Government Sector Jobs', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for Capital District government and education relocations.',
    website: 'https://bankofamerica.com/mortgage', phone: '(518) 555-3211',
  },
  {
    id: 'ny-24', slug: 'nova-home-loans-albany', name: 'Nova Home Loans (Albany Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Albany', state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany',
    zipCodes: ['12203', '12210', '12205'], rating: 4.8, reviewCount: 245, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Low DOM Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Albany lender — localized knowledge of investor and family financing in steady Capital District demand.',
    website: 'https://novahomeloans.com', phone: '(518) 555-3212',
  },

  // ── NYC Suburbs — Westchester & Putnam (Tri-State Surge) ───────────────────
  {
    id: 'ny-25', slug: 'local-westchester-putnam-independent-mortgage', name: 'Local Westchester/Putnam Independent Mortgage', nmlsId: '481293', type: 'Broker',
    city: 'White Plains', state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester',
    zipCodes: ['10601', '10801', '10512'], rating: 4.9, reviewCount: 710, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 31, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Suburban Relocation', 'Over-Asking Financing', 'Tri-State Surge'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local Westchester/Putnam independent — strong knowledge of Tri-State surge and low suburban inventory.',
    website: 'https://westchesterputnammortgage.com', phone: '(914) 555-3301',
  },
  {
    id: 'ny-26', slug: 'guild-mortgage-nyc-suburbs', name: 'Guild Mortgage (Westchester)', nmlsId: '3274', type: 'Lender',
    city: 'White Plains', state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester',
    zipCodes: ['10601', '10605', '10801'], rating: 4.8, reviewCount: 520, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'White Plains / New Rochelle', 'Suburban Relocation Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Westchester branches — financing for buyers priced out of Manhattan and Brooklyn.',
    website: 'https://guildmortgage.com', phone: '(914) 555-3302',
  },
  {
    id: 'ny-27', slug: 'new-american-funding-nyc-suburbs', name: 'New American Funding (Westchester)', nmlsId: '6606', type: 'Lender',
    city: 'White Plains', state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester',
    zipCodes: ['10601', '10801', '10805'], rating: 4.9, reviewCount: 455, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Competitive Suburban Markets', 'White Plains / New Rochelle'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Westchester team — excellent ratings for White Plains and New Rochelle competitive suburban markets.',
    website: 'https://newamericanfunding.com', phone: '(914) 555-3303',
  },
  {
    id: 'ny-28', slug: 'crosscountry-mortgage-hudson-valley-nyc-suburbs', name: 'CrossCountry Mortgage (Hudson Valley)', nmlsId: '3029', type: 'Lender',
    city: 'Carmel', state: 'New York', stateSlug: 'new-york', county: 'Putnam', countySlug: 'putnam',
    zipCodes: ['10512', '10601', '10801'], rating: 4.8, reviewCount: 380, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Putnam / Westchester', 'Manhattan/Brooklyn Relocators', 'Double-Digit Price Jumps'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Hudson Valley teams — experienced support for relocators facing double-digit Putnam price jumps.',
    website: 'https://crosscountrymortgage.com', phone: '(914) 555-3304',
  },
  {
    id: 'ny-29', slug: 'pierpoint-mortgage-nyc-suburbs', name: 'PierPoint Mortgage (NYC Suburbs)', nmlsId: '112844', type: 'Broker',
    city: 'New Rochelle', state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester',
    zipCodes: ['10801', '10805', '10601'], rating: 4.9, reviewCount: 195, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Westchester / Putnam', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to 56%+ over-asking sales in White Plains and New Rochelle.',
    website: 'https://pierpointmortgage.com', phone: '(914) 555-3305',
  },
  {
    id: 'ny-30', slug: 'silverton-mortgage-nyc-suburbs', name: 'Silverton Mortgage — New Rochelle/White Plains', nmlsId: '1561', type: 'Lender',
    city: 'New Rochelle', state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester',
    zipCodes: ['10801', '10601', '10605'], rating: 4.8, reviewCount: 162, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Competition Suburbs', 'Retail Local Expertise', '102%+ Sale-to-List'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Westchester retail lending — professional service for high-competition suburban transactions.',
    website: 'https://silvertonmortgage.com', phone: '(914) 555-3306',
  },
  {
    id: 'ny-31', slug: 'young-professional-relocation-mortgage-nyc-suburbs', name: 'Young Professional & Family Relocation Specialists (Putnam/Westchester)', nmlsId: '492847', type: 'Broker',
    city: 'Carmel', state: 'New York', stateSlug: 'new-york', county: 'Putnam', countySlug: 'putnam',
    zipCodes: ['10512', '10509', '10601'], rating: 4.9, reviewCount: 490, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Relocation Programs', 'Family Financing', 'Manhattan/Brooklyn Priced-Out'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'Relocation specialist — tailored for young professionals and families priced out of Manhattan and Brooklyn.',
    website: 'https://nycsuburbrelocationmortgage.com', phone: '(914) 555-3307',
  },
  {
    id: 'ny-32', slug: 'westchester-putnam-community-credit-union', name: 'Westchester/Putnam Community Credit Union', nmlsId: '448291', type: 'Credit Union',
    city: 'White Plains', state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester',
    zipCodes: ['10601', '10801', '10512'], rating: 4.9, reviewCount: 840, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Member Rates', 'Suburban Buyers', 'Tri-State Surge'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for suburban buyers in the Tri-State surge markets.',
    website: 'https://westchesterputnamcu.org', phone: '(914) 555-3308',
  },
  {
    id: 'ny-33', slug: 'single-family-suburban-mortgage-nyc-suburbs', name: 'Single-Family Suburban Specialists (White Plains/Putnam)', nmlsId: '476829', type: 'Broker',
    city: 'White Plains', state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester',
    zipCodes: ['10601', '10605', '10512'], rating: 4.9, reviewCount: 340, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Classic Suburban Single-Family', 'Limited Inventory', 'High Sale-to-List'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Single-family suburban specialist — expertise in limited inventory and 102%+ sale-to-list percentages.',
    website: 'https://westchestersinglefamilymortgage.com', phone: '(914) 555-3309',
  },
  {
    id: 'ny-34', slug: 'anchor-home-mortgage-nyc-suburbs', name: 'Anchor Home Mortgage (New Rochelle / Putnam)', nmlsId: '136890', type: 'Broker',
    city: 'Carmel', state: 'New York', stateSlug: 'new-york', county: 'Putnam', countySlug: 'putnam',
    zipCodes: ['10512', '10801', '10509'], rating: 4.9, reviewCount: 265, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Personalized Brokerage', '11%+ YoY Gains', 'NYC Suburb Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Putnam affordability alternatives and New Rochelle suburban demand.',
    website: 'https://anchorhomemortgage.com', phone: '(914) 555-3310',
  },
  {
    id: 'ny-35', slug: 'bank-of-america-mortgage-nyc-suburbs', name: 'Bank of America Mortgage (White Plains / New Rochelle)', nmlsId: '399802', type: 'Bank',
    city: 'White Plains', state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester',
    zipCodes: ['10601', '10801', '10805'], rating: 4.6, reviewCount: 680, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Relocation Financing', 'Tri-State Commuters', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for Tri-State commuters relocating to Westchester suburbs.',
    website: 'https://bankofamerica.com/mortgage', phone: '(914) 555-3311',
  },
  {
    id: 'ny-36', slug: 'nova-home-loans-nyc-suburbs', name: 'Nova Home Loans (NYC Suburb Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Carmel', state: 'New York', stateSlug: 'new-york', county: 'Putnam', countySlug: 'putnam',
    zipCodes: ['10801', '10512', '10601'], rating: 4.8, reviewCount: 290, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Over-Asking Premiums', 'Competitive Suburbs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'NYC suburbs lender — localized knowledge of over-asking premiums and demand surge in Westchester and Putnam.',
    website: 'https://novahomeloans.com', phone: '(914) 555-3312',
  },

  // ── NYC Boroughs (Brooklyn, Queens & Manhattan) ─────────────────────────────
  {
    id: 'ny-37', slug: 'local-nyc-borough-independent-mortgage', name: 'Local NYC Borough Independent Mortgage', nmlsId: '493827', type: 'Broker',
    city: 'Brooklyn', state: 'New York', stateSlug: 'new-york', county: 'Kings', countySlug: 'kings',
    zipCodes: ['11201', '11215', '11234'], rating: 4.9, reviewCount: 820, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 28, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Multi-Family Financing', 'Condo & Co-op Programs', 'Borough Hot Pockets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local NYC borough independent — strong knowledge of borough-specific hot pockets across Brooklyn, Queens, and Manhattan.',
    website: 'https://nycboroughmortgage.com', phone: '(718) 555-3401',
  },
  {
    id: 'ny-38', slug: 'guild-mortgage-nyc-boroughs', name: 'Guild Mortgage (NYC Boroughs)', nmlsId: '3274', type: 'Lender',
    city: 'Queens', state: 'New York', stateSlug: 'new-york', county: 'Queens', countySlug: 'queens',
    zipCodes: ['11101', '11106', '11354'], rating: 4.8, reviewCount: 580, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Multi-Borough Operations', 'Full Residential Spectrum', 'Urban Core Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with NYC borough branches — multi-family, condo, and co-op financing across Kings, Queens, and New York Counties.',
    website: 'https://guildmortgage.com', phone: '(718) 555-3402',
  },
  {
    id: 'ny-39', slug: 'new-american-funding-nyc-boroughs', name: 'New American Funding (NYC — Brooklyn / Queens)', nmlsId: '6606', type: 'Lender',
    city: 'Brooklyn', state: 'New York', stateSlug: 'new-york', county: 'Kings', countySlug: 'kings',
    zipCodes: ['11215', '11234', '11106'], rating: 4.9, reviewCount: 495, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Southern Brooklyn', 'Queens Growth Corridors'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF NYC team — excellent ratings for Southern Brooklyn and Queens aggressive price growth markets.',
    website: 'https://newamericanfunding.com', phone: '(718) 555-3403',
  },
  {
    id: 'ny-40', slug: 'crosscountry-mortgage-nyc-boroughs', name: 'CrossCountry Mortgage (NYC — Manhattan / Brooklyn)', nmlsId: '3029', type: 'Lender',
    city: 'Manhattan', state: 'New York', stateSlug: 'new-york', county: 'New York', countySlug: 'new-york-county',
    zipCodes: ['10001', '10014', '11201'], rating: 4.8, reviewCount: 420, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Luxury Co-op & Condo', 'Urban Professionals', 'Manhattan / Brooklyn'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry NYC teams — experienced support for luxury co-op and condo trends in Manhattan and Brooklyn.',
    website: 'https://crosscountrymortgage.com', phone: '(212) 555-3404',
  },
  {
    id: 'ny-41', slug: 'pierpoint-mortgage-nyc-boroughs', name: 'PierPoint Mortgage (NYC — Queens / Brooklyn)', nmlsId: '112844', type: 'Broker',
    city: 'Queens', state: 'New York', stateSlug: 'new-york', county: 'Queens', countySlug: 'queens',
    zipCodes: ['11101', '11234', '11354'], rating: 4.9, reviewCount: 210, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Queens / Brooklyn', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to lean inventory and bidding wars in Queens and Brooklyn.',
    website: 'https://pierpointmortgage.com', phone: '(718) 555-3405',
  },
  {
    id: 'ny-42', slug: 'silverton-mortgage-southern-brooklyn', name: 'Silverton Mortgage — Southern Brooklyn', nmlsId: '1561', type: 'Lender',
    city: 'Brooklyn', state: 'New York', stateSlug: 'new-york', county: 'Kings', countySlug: 'kings',
    zipCodes: ['11234', '11215', '11201'], rating: 4.8, reviewCount: 175, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Multi-Family Rental Income', 'Southern Brooklyn', 'Borough Retail Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Southern Brooklyn retail lending — professional service for multi-family rental income plays.',
    website: 'https://silvertonmortgage.com', phone: '(718) 555-3406',
  },
  {
    id: 'ny-43', slug: 'young-professional-investor-mortgage-nyc-boroughs', name: 'Young Professional & Investor Specialists (Astoria / LIC)', nmlsId: '502847', type: 'Broker',
    city: 'Queens', state: 'New York', stateSlug: 'new-york', county: 'Queens', countySlug: 'queens',
    zipCodes: ['11106', '11101', '11354'], rating: 4.9, reviewCount: 560, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 37, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Modern Condo Programs', 'Multi-Family Investors', 'Astoria / Long Island City'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'Young professional and investor specialist — tailored for aggressive price growth in Astoria and Long Island City.',
    website: 'https://nycinvestormortgage.com', phone: '(718) 555-3407',
  },
  {
    id: 'ny-44', slug: 'nyc-borough-community-credit-union', name: 'NYC Borough Community Credit Union', nmlsId: '458291', type: 'Credit Union',
    city: 'Queens', state: 'New York', stateSlug: 'new-york', county: 'Queens', countySlug: 'queens',
    zipCodes: ['11101', '11201', '10001'], rating: 4.9, reviewCount: 920, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 53, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Member Rates', 'All Boroughs', 'High-Competition Pockets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for NYC buyers in high-competition borough pockets.',
    website: 'https://nycboroughcu.org', phone: '(718) 555-3408',
  },
  {
    id: 'ny-45', slug: 'waterfront-historic-mortgage-nyc-boroughs', name: 'Waterfront & Historic Specialists (Brooklyn / Manhattan)', nmlsId: '486729', type: 'Broker',
    city: 'Brooklyn', state: 'New York', stateSlug: 'new-york', county: 'Kings', countySlug: 'kings',
    zipCodes: ['11201', '11215', '10014'], rating: 4.9, reviewCount: 385, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Waterfront Properties', 'Historic Rowhomes', 'Southern Brooklyn / Manhattan'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Waterfront and historic specialist — expertise in Southern Brooklyn rowhomes and Manhattan luxury trends.',
    website: 'https://nycwaterfrontmortgage.com', phone: '(718) 555-3409',
  },
  {
    id: 'ny-46', slug: 'anchor-home-mortgage-nyc-boroughs', name: 'Anchor Home Mortgage (Queens / Brooklyn)', nmlsId: '136890', type: 'Broker',
    city: 'Queens', state: 'New York', stateSlug: 'new-york', county: 'Queens', countySlug: 'queens',
    zipCodes: ['11354', '11234', '11106'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Value Tiers', 'Lean Inventory', 'Personalized Borough Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on value tiers and lean inventory in Queens and Brooklyn.',
    website: 'https://anchorhomemortgage.com', phone: '(718) 555-3410',
  },
  {
    id: 'ny-47', slug: 'bank-of-america-mortgage-nyc-boroughs', name: 'Bank of America Mortgage (Manhattan / Queens)', nmlsId: '399802', type: 'Bank',
    city: 'Manhattan', state: 'New York', stateSlug: 'new-york', county: 'New York', countySlug: 'new-york-county',
    zipCodes: ['10001', '10021', '11101'], rating: 4.6, reviewCount: 740, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Co-op/Condo Financing', 'Urban Professional Buyers', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for co-op, condo, and professional buyers in Manhattan and Queens.',
    website: 'https://bankofamerica.com/mortgage', phone: '(212) 555-3411',
  },
  {
    id: 'ny-48', slug: 'nova-home-loans-nyc-boroughs', name: 'Nova Home Loans (NYC Borough Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Brooklyn', state: 'New York', stateSlug: 'new-york', county: 'Kings', countySlug: 'kings',
    zipCodes: ['11234', '11106', '10001'], rating: 4.8, reviewCount: 310, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'First-Time Buyers', 'Borough Appreciation'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'NYC borough lender — localized knowledge of borough-specific appreciation and investor demand.',
    website: 'https://novahomeloans.com', phone: '(718) 555-3412',
  },
];

export const UPSTATE_BUFFALO_LENDER_SLUGS = [
  'local-buffalo-independent-mortgage',
  'guild-mortgage-buffalo',
  'new-american-funding-buffalo',
  'crosscountry-mortgage-western-ny',
  'pierpoint-mortgage-upstate-ny',
  'silverton-mortgage-buffalo',
  'veterans-first-time-mortgage-buffalo',
  'erie-community-credit-union-buffalo',
  'new-construction-climate-refuge-mortgage-buffalo',
  'anchor-home-mortgage-buffalo',
  'bank-of-america-mortgage-buffalo',
  'nova-home-loans-buffalo',
] as const;

export const UPSTATE_ALBANY_LENDER_SLUGS = [
  'local-albany-capital-district-independent-mortgage',
  'guild-mortgage-albany',
  'new-american-funding-albany',
  'crosscountry-mortgage-capital-district',
  'pierpoint-mortgage-albany',
  'silverton-mortgage-albany',
  'veterans-first-time-mortgage-albany',
  'capital-district-community-credit-union',
  'supply-demand-specialist-mortgage-albany',
  'anchor-home-mortgage-albany',
  'bank-of-america-mortgage-albany',
  'nova-home-loans-albany',
] as const;

export const UPSTATE_POWERHOUSES_BUFFALO_ALBANY_LENDER_SLUGS = [
  ...UPSTATE_BUFFALO_LENDER_SLUGS,
  ...UPSTATE_ALBANY_LENDER_SLUGS,
] as const;

export const NYC_SUBURBS_WESTCHESTER_PUTNAM_LENDER_SLUGS = [
  'local-westchester-putnam-independent-mortgage',
  'guild-mortgage-nyc-suburbs',
  'new-american-funding-nyc-suburbs',
  'crosscountry-mortgage-hudson-valley-nyc-suburbs',
  'pierpoint-mortgage-nyc-suburbs',
  'silverton-mortgage-nyc-suburbs',
  'young-professional-relocation-mortgage-nyc-suburbs',
  'westchester-putnam-community-credit-union',
  'single-family-suburban-mortgage-nyc-suburbs',
  'anchor-home-mortgage-nyc-suburbs',
  'bank-of-america-mortgage-nyc-suburbs',
  'nova-home-loans-nyc-suburbs',
] as const;

const NYC_SUBURBS_PUTNAM_SUPPLEMENTS = [
  'local-westchester-putnam-independent-mortgage',
  'guild-mortgage-nyc-suburbs',
  'new-american-funding-nyc-suburbs',
  'pierpoint-mortgage-nyc-suburbs',
  'silverton-mortgage-nyc-suburbs',
  'westchester-putnam-community-credit-union',
  'single-family-suburban-mortgage-nyc-suburbs',
  'bank-of-america-mortgage-nyc-suburbs',
];

const NYC_SUBURBS_WESTCHESTER_SUPPLEMENTS = [
  'crosscountry-mortgage-hudson-valley-nyc-suburbs',
  'young-professional-relocation-mortgage-nyc-suburbs',
  'anchor-home-mortgage-nyc-suburbs',
  'nova-home-loans-nyc-suburbs',
];

export const NYC_BOROUGHS_BROOKLYN_QUEENS_MANHATTAN_LENDER_SLUGS = [
  'local-nyc-borough-independent-mortgage',
  'guild-mortgage-nyc-boroughs',
  'new-american-funding-nyc-boroughs',
  'crosscountry-mortgage-nyc-boroughs',
  'pierpoint-mortgage-nyc-boroughs',
  'silverton-mortgage-southern-brooklyn',
  'young-professional-investor-mortgage-nyc-boroughs',
  'nyc-borough-community-credit-union',
  'waterfront-historic-mortgage-nyc-boroughs',
  'anchor-home-mortgage-nyc-boroughs',
  'bank-of-america-mortgage-nyc-boroughs',
  'nova-home-loans-nyc-boroughs',
] as const;

const NYC_BOROUGHS_KINGS_SUPPLEMENTS = [
  'guild-mortgage-nyc-boroughs',
  'pierpoint-mortgage-nyc-boroughs',
  'young-professional-investor-mortgage-nyc-boroughs',
  'nyc-borough-community-credit-union',
  'anchor-home-mortgage-nyc-boroughs',
  'crosscountry-mortgage-nyc-boroughs',
  'bank-of-america-mortgage-nyc-boroughs',
];

const NYC_BOROUGHS_QUEENS_SUPPLEMENTS = [
  'local-nyc-borough-independent-mortgage',
  'new-american-funding-nyc-boroughs',
  'silverton-mortgage-southern-brooklyn',
  'waterfront-historic-mortgage-nyc-boroughs',
  'nova-home-loans-nyc-boroughs',
  'crosscountry-mortgage-nyc-boroughs',
  'bank-of-america-mortgage-nyc-boroughs',
];

const NYC_BOROUGHS_NEW_YORK_COUNTY_SUPPLEMENTS = [
  'local-nyc-borough-independent-mortgage',
  'guild-mortgage-nyc-boroughs',
  'new-american-funding-nyc-boroughs',
  'pierpoint-mortgage-nyc-boroughs',
  'silverton-mortgage-southern-brooklyn',
  'young-professional-investor-mortgage-nyc-boroughs',
  'nyc-borough-community-credit-union',
  'waterfront-historic-mortgage-nyc-boroughs',
  'anchor-home-mortgage-nyc-boroughs',
  'nova-home-loans-nyc-boroughs',
];

export const NEW_YORK_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  erie: [],
  albany: [],
  westchester: NYC_SUBURBS_WESTCHESTER_SUPPLEMENTS,
  putnam: NYC_SUBURBS_PUTNAM_SUPPLEMENTS,
  kings: NYC_BOROUGHS_KINGS_SUPPLEMENTS,
  queens: NYC_BOROUGHS_QUEENS_SUPPLEMENTS,
  'new-york-county': NYC_BOROUGHS_NEW_YORK_COUNTY_SUPPLEMENTS,
};

export const UPSTATE_POWERHOUSES_HUB_AREAS = [
  { name: 'Buffalo', slug: 'erie', highlight: 'Top-3 hot market, bidding wars, $227K–$277K median' },
  { name: 'Albany', slug: 'albany', highlight: 'Capital District, supply-demand imbalance, low DOM' },
  { name: 'Erie County', slug: 'erie', highlight: 'Climate refuge, healthcare/education hub' },
  { name: 'Albany County', slug: 'albany', highlight: 'Steady activity, government sector demand' },
] as const;

export const NYC_SUBURBS_HUB_AREAS = [
  { name: 'White Plains', slug: 'westchester', highlight: '56%+ over-asking, 102%+ sale-to-list' },
  { name: 'New Rochelle', slug: 'westchester', highlight: 'National market heat index leader' },
  { name: 'Putnam County', slug: 'putnam', highlight: '11%+ YoY gains, affordability alternative' },
  { name: 'Westchester County', slug: 'westchester', highlight: 'Tri-State surge safety valve' },
] as const;

export const NYC_BOROUGHS_HUB_AREAS = [
  { name: 'Brooklyn', slug: 'kings', highlight: 'Southern Brooklyn multi-family rental plays' },
  { name: 'Queens', slug: 'queens', highlight: 'Astoria, LIC & Flushing aggressive growth' },
  { name: 'Manhattan', slug: 'new-york-county', highlight: 'Luxury co-op resurgence, lean inventory' },
  { name: 'Kings County', slug: 'kings', highlight: 'Waterfront & historic rowhome demand' },
] as const;