import type { Lender } from '@/lib/lender/mockData';

export const NORTH_CAROLINA_LENDERS: Lender[] = [
  // ── Mecklenburg County (Charlotte Metro) ─────────────────────────────────────
  {
    id: 'nc-01', slug: 'mortgageright-charlotte', name: 'MortgageRight — Charlotte', nmlsId: '2229723', type: 'Lender',
    city: 'Charlotte', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Mecklenburg', countySlug: 'mecklenburg',
    zipCodes: ['28202', '28205', '28203'], rating: 4.9, reviewCount: 285, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Corporate Relocations', 'Banking & Tech Influx', 'Direct Lender'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 96,
    shortDescription: 'Charlotte MortgageRight branch — direct lending for corporate relocations in Huntersville, Concord, and Gastonia corridors.',
    website: 'https://charlotte.mortgageright.com', phone: '(704) 999-6646',
  },
  {
    id: 'nc-02', slug: 'guild-mortgage-charlotte', name: 'Guild Mortgage (Charlotte Branches)', nmlsId: '3274', type: 'Lender',
    city: 'Charlotte', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Mecklenburg', countySlug: 'mecklenburg',
    zipCodes: ['28202', '28269', '28277'], rating: 4.8, reviewCount: 620, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Multiple Charlotte Branches', 'Full-Spectrum Lending', 'Suburban Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with strong Charlotte presence for $425K median suburban and corporate relocation volume.',
    website: 'https://guildmortgage.com', phone: '(704) 555-5001',
  },
  {
    id: 'nc-03', slug: 'new-american-funding-charlotte', name: 'New American Funding (Charlotte)', nmlsId: '6606', type: 'Lender',
    city: 'Charlotte', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Mecklenburg', countySlug: 'mecklenburg',
    zipCodes: ['28202', '28078', '28269'], rating: 4.9, reviewCount: 540, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Huntersville Suburbs', 'High-Volume Service', 'Fast Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'High-volume Charlotte NAF team — excellent ratings for fast suburban transactions in Mecklenburg and Concord reach.',
    website: 'https://newamericanfunding.com', phone: '(704) 555-5002',
  },
  {
    id: 'nc-04', slug: 'crosscountry-mortgage-charlotte', name: 'CrossCountry Mortgage (Charlotte)', nmlsId: '3029', type: 'Lender',
    city: 'Charlotte', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Mecklenburg', countySlug: 'mecklenburg',
    zipCodes: ['28202', '28277', '28027'], rating: 4.8, reviewCount: 480, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Concord & Gastonia', 'Professional Buyers', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Charlotte — broad products for professionals in rapid-growth Mecklenburg suburbs.',
    website: 'https://crosscountrymortgage.com', phone: '(704) 555-5003',
  },
  {
    id: 'nc-05', slug: 'pierpoint-mortgage-charlotte', name: 'PierPoint Mortgage (Charlotte Metro)', nmlsId: '112844', type: 'Broker',
    city: 'Charlotte', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Mecklenburg', countySlug: 'mecklenburg',
    zipCodes: ['28202', '28052', '28269'], rating: 4.9, reviewCount: 195, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Wholesale Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 96,
    shortDescription: 'Wholesale broker with transparent fees — suited to high-velocity Charlotte and Gastonia offer timelines.',
    website: 'https://pierpointmortgage.com', phone: '(704) 555-5004',
  },

  // ── Wake County (Research Triangle) ──────────────────────────────────────────
  {
    id: 'nc-06', slug: 'martini-mortgage-group', name: 'Martini Mortgage Group', nmlsId: '3446', type: 'Lender',
    city: 'Raleigh', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Wake', countySlug: 'wake',
    zipCodes: ['27601', '27604', '27511'], rating: 4.9, reviewCount: 890, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Refinance'],
    specialties: ['Tech & Education Relocations', 'Same-As-Cash Approval', 'Fiduciary-Style Advisory'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.9, avgCloseDays: 24, onTimeCloseRate: 97,
    shortDescription: 'Raleigh mortgage advisors since 2006 — strategy-first financing for Cary, Apex, and Triangle tech professionals.',
    website: 'https://martinimortgagegroup.com', phone: '(919) 238-4934',
  },
  {
    id: 'nc-07', slug: 'guild-mortgage-research-triangle', name: 'Guild Mortgage (Research Triangle)', nmlsId: '3274', type: 'Lender',
    city: 'Raleigh', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Wake', countySlug: 'wake',
    zipCodes: ['27601', '27513', '27502'], rating: 4.8, reviewCount: 510, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Wake & Durham Reach', 'Full Residential', 'High-Volume Triangle'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Guild Triangle teams — local officers serving Raleigh-Durham-Chapel Hill corporate and university relocations.',
    website: 'https://guildmortgage.com', phone: '(919) 555-5101',
  },
  {
    id: 'nc-08', slug: 'new-american-funding-research-triangle', name: 'New American Funding (Research Triangle)', nmlsId: '6606', type: 'Lender',
    city: 'Cary', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Wake', countySlug: 'wake',
    zipCodes: ['27513', '27502', '27601'], rating: 4.9, reviewCount: 465, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Cary & Apex', 'Millennial Professionals', 'Purchase & Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'NAF Cary/Apex focus — strong support for millennial and professional buyers in competitive Triangle suburbs.',
    website: 'https://newamericanfunding.com', phone: '(919) 555-5102',
  },
  {
    id: 'nc-09', slug: 'crosscountry-mortgage-research-triangle', name: 'CrossCountry Mortgage (Triangle)', nmlsId: '3029', type: 'Lender',
    city: 'Raleigh', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Wake', countySlug: 'wake',
    zipCodes: ['27601', '27526', '27511'], rating: 4.8, reviewCount: 420, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Job Relocations', 'Fuquay-Varina Growth', 'Broad Lending'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Triangle branches — experienced teams for fast-moving suburban rings around Raleigh.',
    website: 'https://crosscountrymortgage.com', phone: '(919) 555-5103',
  },
  {
    id: 'nc-10', slug: 'pierpoint-mortgage-research-triangle', name: 'PierPoint Mortgage (Research Triangle)', nmlsId: '112844', type: 'Broker',
    city: 'Raleigh', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Wake', countySlug: 'wake',
    zipCodes: ['27601', '27502', '27539'], rating: 4.9, reviewCount: 175, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Fast Closings', 'Wholesale Rates', 'Competitive Triangle Offers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 96,
    shortDescription: 'Triangle wholesale broker — fast closings for education and tech-driven competitive Wake County demand.',
    website: 'https://pierpointmortgage.com', phone: '(919) 555-5104',
  },

  // ── Guilford County (Piedmont Triad) ─────────────────────────────────────────
  {
    id: 'nc-11', slug: 'helms-mortgage-greensboro', name: 'Helms Mortgage LLC', nmlsId: '1283399', type: 'Broker',
    city: 'Greensboro', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Guilford', countySlug: 'guilford',
    zipCodes: ['27401', '27410', '27407'], rating: 4.9, reviewCount: 210, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Affordable Entry-Level', 'Equity Building', '12.5%+ Appreciation Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Greensboro independent broker — affordable $283K–$315K entry and equity growth expertise in the Triad.',
    website: 'https://helmsmortgage.com', phone: '(336) 555-5201',
  },
  {
    id: 'nc-12', slug: 'guild-mortgage-piedmont-triad', name: 'Guild Mortgage (Piedmont Triad)', nmlsId: '3274', type: 'Lender',
    city: 'Greensboro', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Guilford', countySlug: 'guilford',
    zipCodes: ['27401', '27455', '27265'], rating: 4.8, reviewCount: 340, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Affordability Surge', 'Full Residential', 'High Point Reach'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Guild Triad support for first-time buyers and retirees in discounted metro vs. Charlotte and Triangle.',
    website: 'https://guildmortgage.com', phone: '(336) 555-5202',
  },
  {
    id: 'nc-13', slug: 'new-american-funding-greensboro', name: 'New American Funding (Greensboro)', nmlsId: '6606', type: 'Lender',
    city: 'Greensboro', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Guilford', countySlug: 'guilford',
    zipCodes: ['27401', '27410', '27265'], rating: 4.8, reviewCount: 280, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Competitive Triad Rates', 'High-Volume Service', 'Investor Activity'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 29, onTimeCloseRate: 94,
    shortDescription: 'NAF Greensboro — competitive options in the Triad\'s high-absorption affordable housing market.',
    website: 'https://newamericanfunding.com', phone: '(336) 555-5203',
  },
  {
    id: 'nc-15', slug: 'pierpoint-mortgage-piedmont-triad', name: 'PierPoint Mortgage (Piedmont Triad)', nmlsId: '112844', type: 'Broker',
    city: 'High Point', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Guilford', countySlug: 'guilford',
    zipCodes: ['27265', '27401', '27407'], rating: 4.9, reviewCount: 145, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Speed & Transparency', 'Investor-Friendly', 'Rapid Absorption'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Fast-closing wholesale broker for Guilford and High Point investor and first-time buyer activity.',
    website: 'https://pierpointmortgage.com', phone: '(336) 555-5204',
  },

  // ── Forsyth County (Winston-Salem / Triad) ───────────────────────────────────
  {
    id: 'nc-14', slug: 'silverton-mortgage-winston-salem', name: 'Silverton Mortgage — Winston-Salem', nmlsId: '2318729', type: 'Lender',
    city: 'Winston-Salem', state: 'North Carolina', stateSlug: 'north-carolina', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['27104', '27101', '27103'], rating: 4.8, reviewCount: 165, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Winston-Salem Retail', 'Triad Local Presence'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 29, onTimeCloseRate: 95,
    shortDescription: 'Silverton Winston-Salem branch — strong local retail lending for Forsyth County first-time buyers.',
    website: 'https://silvertonmortgage.com/greensboro', phone: '(336) 555-5205',
  },
];

export const NORTH_CAROLINA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  mecklenburg: [],
  wake: [],
  guilford: [],
  forsyth: ['helms-mortgage-greensboro', 'guild-mortgage-piedmont-triad', 'new-american-funding-greensboro', 'pierpoint-mortgage-piedmont-triad'],
  durham: ['martini-mortgage-group', 'guild-mortgage-research-triangle', 'new-american-funding-research-triangle', 'crosscountry-mortgage-research-triangle', 'pierpoint-mortgage-research-triangle'],
};

export const CHARLOTTE_METRO_HUB_COUNTIES = [
  { name: 'Mecklenburg', slug: 'mecklenburg', highlight: 'Charlotte, corporate relocations, $425K median' },
  { name: 'Union', slug: 'union', highlight: 'Indian Trail, Waxhaw — coming soon' },
  { name: 'Cabarrus', slug: 'cabarrus', highlight: 'Concord, Huntersville border — coming soon' },
] as const;

export const RESEARCH_TRIANGLE_HUB_COUNTIES = [
  { name: 'Wake', slug: 'wake', highlight: 'Raleigh, Cary, Apex, $447K median' },
  { name: 'Durham', slug: 'durham', highlight: 'Durham, RTP, tech & healthcare hubs' },
  { name: 'Orange', slug: 'orange', highlight: 'Chapel Hill — coming soon' },
] as const;

export const PIEDMONT_TRIAD_HUB_COUNTIES = [
  { name: 'Guilford', slug: 'guilford', highlight: 'Greensboro, High Point, affordability' },
  { name: 'Forsyth', slug: 'forsyth', highlight: 'Winston-Salem, first-time buyers' },
] as const;