import type { Lender } from '@/lib/lender/mockData';

export const PENNSYLVANIA_LENDERS: Lender[] = [
  // ── Philadelphia Metro — Philadelphia, Montgomery, Chester & Bucks ───────────
  {
    id: 'pa-01', slug: 'local-philadelphia-metro-independent-mortgage', name: 'Local Philadelphia Metro Independent Mortgage', nmlsId: '452891', type: 'Broker',
    city: 'Philadelphia', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Philadelphia', countySlug: 'philadelphia',
    zipCodes: ['19102', '19103', '19107'], rating: 4.9, reviewCount: 780, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 30, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Above-Asking Financing', 'Move-In-Ready Demand', '#6 Hottest US Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local Philadelphia Metro independent — strong knowledge of 41%+ above-asking sales and collar-county bidding wars.',
    website: 'https://phillymetroindependentmortgage.com', phone: '(215) 555-3101',
  },
  {
    id: 'pa-02', slug: 'guild-mortgage-philadelphia-metro', name: 'Guild Mortgage (Philadelphia Metro)', nmlsId: '3274', type: 'Lender',
    city: 'King of Prussia', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Montgomery', countySlug: 'montgomery',
    zipCodes: ['19406', '19460', '19001'], rating: 4.8, reviewCount: 520, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Montgomery County Operations', 'Collar County Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Philadelphia Metro branches — comprehensive financing across Montgomery and collar counties.',
    website: 'https://guildmortgage.com', phone: '(610) 555-3102',
  },
  {
    id: 'pa-03', slug: 'new-american-funding-philly-collar-counties', name: 'New American Funding (Chester County)', nmlsId: '6606', type: 'Lender',
    city: 'West Chester', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Chester', countySlug: 'chester',
    zipCodes: ['19380', '19382', '19341'], rating: 4.9, reviewCount: 465, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Move-In-Ready Homes', 'Chester County Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Chester County team — excellent ratings for move-in-ready purchase volume in one of America\'s hottest markets.',
    website: 'https://newamericanfunding.com', phone: '(610) 555-3103',
  },
  {
    id: 'pa-04', slug: 'crosscountry-mortgage-philadelphia-metro', name: 'CrossCountry Mortgage (Bucks County)', nmlsId: '3029', type: 'Lender',
    city: 'Doylestown', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Bucks', countySlug: 'bucks',
    zipCodes: ['18940', '18951', '19047'], rating: 4.8, reviewCount: 395, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['NYC/DC Relocators', 'Collar County Bidding Wars', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Bucks County teams — experienced support for NYC and DC relocators seeking Philadelphia Metro affordability.',
    website: 'https://crosscountrymortgage.com', phone: '(215) 555-3104',
  },
  {
    id: 'pa-05', slug: 'pierpoint-mortgage-philadelphia-metro', name: 'PierPoint Mortgage (Montgomery County)', nmlsId: '112844', type: 'Broker',
    city: 'Norristown', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Montgomery', countySlug: 'montgomery',
    zipCodes: ['19401', '19406', '19003'], rating: 4.9, reviewCount: 185, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Collar County Competition'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Montgomery County bidding wars and lean move-in-ready inventory.',
    website: 'https://pierpointmortgage.com', phone: '(610) 555-3105',
  },
  {
    id: 'pa-06', slug: 'silverton-mortgage-philadelphia-metro', name: 'Silverton Mortgage — Philadelphia', nmlsId: '1561', type: 'Lender',
    city: 'Philadelphia', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Philadelphia', countySlug: 'philadelphia',
    zipCodes: ['19123', '19146', '19147'], rating: 4.8, reviewCount: 172, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Urban Core Expertise', 'Retail Local Expertise', 'Above-Asking Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Philadelphia retail lending — professional service for buyers competing in the #6 hottest US market.',
    website: 'https://silvertonmortgage.com', phone: '(215) 555-3106',
  },
  {
    id: 'pa-07', slug: 'nyc-dc-relocation-mortgage-philadelphia-metro', name: 'NYC & DC Relocation Specialists (Bucks County)', nmlsId: '463827', type: 'Broker',
    city: 'Yardley', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Bucks', countySlug: 'bucks',
    zipCodes: ['19067', '18974', '19020'], rating: 4.9, reviewCount: 540, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['NYC/DC Affordability', 'Relocation Programs', 'Collar County Alternatives'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'Relocation specialist — tailored for NYC and DC buyers priced into Bucks County\'s competitive collar markets.',
    website: 'https://phillymetrorelocationmortgage.com', phone: '(215) 555-3107',
  },
  {
    id: 'pa-08', slug: 'philadelphia-metro-community-credit-union', name: 'Philadelphia Metro Community Credit Union', nmlsId: '449102', type: 'Credit Union',
    city: 'Abington', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Montgomery', countySlug: 'montgomery',
    zipCodes: ['19001', '19004', '19401'], rating: 4.9, reviewCount: 860, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Montgomery County CU', 'Collar County Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for Philadelphia Metro buyers in high-competition collar counties.',
    website: 'https://phillymetrocu.org', phone: '(610) 555-3108',
  },
  {
    id: 'pa-09', slug: 'move-in-ready-mortgage-philadelphia-metro', name: 'Move-In-Ready Home Specialists (Chester County)', nmlsId: '471293', type: 'Broker',
    city: 'Malvern', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Chester', countySlug: 'chester',
    zipCodes: ['19355', '19425', '19348'], rating: 4.9, reviewCount: 310, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 37, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Move-In-Ready Financing', 'Chester County Demand', '41%+ Above-Asking Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Move-in-ready specialist — expertise in Chester County turn-key demand and collar-county bidding wars.',
    website: 'https://chestercountymoveinmortgage.com', phone: '(610) 555-3109',
  },
  {
    id: 'pa-10', slug: 'anchor-home-mortgage-philadelphia-metro', name: 'Anchor Home Mortgage (Bucks County)', nmlsId: '136890', type: 'Broker',
    city: 'Newtown', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Bucks', countySlug: 'bucks',
    zipCodes: ['18940', '19067', '19047'], rating: 4.9, reviewCount: 275, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Brokerage', 'NYC/DC Affordability', 'Collar County Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Bucks County affordability alternatives for NYC and DC relocators.',
    website: 'https://anchorhomemortgage.com', phone: '(215) 555-3110',
  },
  {
    id: 'pa-11', slug: 'bank-of-america-mortgage-philadelphia-metro', name: 'Bank of America Mortgage (Philadelphia)', nmlsId: '399802', type: 'Bank',
    city: 'Philadelphia', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Philadelphia', countySlug: 'philadelphia',
    zipCodes: ['19102', '19103', '19146'], rating: 4.6, reviewCount: 640, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'NYC/DC Commuters', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for Philadelphia Metro relocators from NYC and DC corridors.',
    website: 'https://bankofamerica.com/mortgage', phone: '(215) 555-3111',
  },
  {
    id: 'pa-12', slug: 'nova-home-loans-philadelphia-metro', name: 'Nova Home Loans (Philadelphia Metro Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Conshohocken', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Montgomery', countySlug: 'montgomery',
    zipCodes: ['19428', '19406', '19004'], rating: 4.8, reviewCount: 285, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Above-Asking Premiums', 'Collar County Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Philadelphia Metro lender — localized knowledge of collar-county appreciation and move-in-ready demand.',
    website: 'https://novahomeloans.com', phone: '(610) 555-3112',
  },

  // ── Greater Pittsburgh — Allegheny & Beaver ────────────────────────────────
  {
    id: 'pa-13', slug: 'local-greater-pittsburgh-independent-mortgage', name: 'Local Greater Pittsburgh Independent Mortgage', nmlsId: '458192', type: 'Broker',
    city: 'Pittsburgh', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Allegheny', countySlug: 'allegheny',
    zipCodes: ['15201', '15213', '15222'], rating: 4.9, reviewCount: 590, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Market Stability', 'Remote Worker Financing', 'Fast-Pending Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Local Greater Pittsburgh independent — strong knowledge of 8–14 day pending markets and remote-worker demand.',
    website: 'https://pittsburghindependentmortgage.com', phone: '(412) 555-3201',
  },
  {
    id: 'pa-14', slug: 'guild-mortgage-greater-pittsburgh', name: 'Guild Mortgage (Greater Pittsburgh)', nmlsId: '3274', type: 'Lender',
    city: 'Pittsburgh', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Allegheny', countySlug: 'allegheny',
    zipCodes: ['15213', '15232', '15237'], rating: 4.8, reviewCount: 430, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Allegheny County Operations', 'Pittsburgh Metro Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Pittsburgh branches — comprehensive financing for stable Allegheny County markets.',
    website: 'https://guildmortgage.com', phone: '(412) 555-3202',
  },
  {
    id: 'pa-15', slug: 'new-american-funding-greater-pittsburgh', name: 'New American Funding (Beaver County)', nmlsId: '6606', type: 'Lender',
    city: 'Baden', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Beaver', countySlug: 'beaver',
    zipCodes: ['15005', '15009', '15010'], rating: 4.9, reviewCount: 380, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Baden Hot Suburb', '8–14 Day Pending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 96,
    shortDescription: 'NAF Beaver County team — excellent ratings for Baden, the #3 hottest suburb with ultra-fast pending times.',
    website: 'https://newamericanfunding.com', phone: '(412) 555-3203',
  },
  {
    id: 'pa-16', slug: 'crosscountry-mortgage-greater-pittsburgh', name: 'CrossCountry Mortgage (Allegheny County)', nmlsId: '3029', type: 'Lender',
    city: 'Pittsburgh', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Allegheny', countySlug: 'allegheny',
    zipCodes: ['15201', '15212', '15222'], rating: 4.8, reviewCount: 345, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Remote Worker Relocation', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Pittsburgh teams — experienced support for remote workers and first-time buyers in stable Allegheny markets.',
    website: 'https://crosscountrymortgage.com', phone: '(412) 555-3204',
  },
  {
    id: 'pa-17', slug: 'pierpoint-mortgage-greater-pittsburgh', name: 'PierPoint Mortgage (Beaver County)', nmlsId: '112844', type: 'Broker',
    city: 'Beaver', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Beaver', countySlug: 'beaver',
    zipCodes: ['15009', '15061', '15066'], rating: 4.9, reviewCount: 158, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Beaver County', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Beaver County\'s 8–14 day pending velocity and Baden demand surge.',
    website: 'https://pierpointmortgage.com', phone: '(412) 555-3205',
  },
  {
    id: 'pa-18', slug: 'silverton-mortgage-greater-pittsburgh', name: 'Silverton Mortgage — Pittsburgh', nmlsId: '1561', type: 'Lender',
    city: 'Pittsburgh', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Allegheny', countySlug: 'allegheny',
    zipCodes: ['15213', '15232', '15237'], rating: 4.8, reviewCount: 145, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Market Stability', 'Retail Local Expertise', 'Remote Worker Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'Silverton Pittsburgh retail lending — professional service for remote workers and stable Allegheny transactions.',
    website: 'https://silvertonmortgage.com', phone: '(412) 555-3206',
  },
  {
    id: 'pa-19', slug: 'remote-worker-mortgage-greater-pittsburgh', name: 'Remote Worker & Stability Specialists (Beaver County)', nmlsId: '467384', type: 'Broker',
    city: 'Ambridge', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Beaver', countySlug: 'beaver',
    zipCodes: ['15003', '15010', '15001'], rating: 4.9, reviewCount: 420, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Remote Worker Programs', 'Market Stability', 'Beaver County Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Remote worker specialist — tailored for buyers drawn to Beaver County stability and Pittsburgh metro affordability.',
    website: 'https://pittsburghremoteworkermortgage.com', phone: '(412) 555-3207',
  },
  {
    id: 'pa-20', slug: 'greater-pittsburgh-community-credit-union', name: 'Greater Pittsburgh Community Credit Union', nmlsId: '451829', type: 'Credit Union',
    city: 'Pittsburgh', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Allegheny', countySlug: 'allegheny',
    zipCodes: ['15201', '15213', '15222'], rating: 4.9, reviewCount: 740, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 56, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Allegheny County CU', 'Community-Focused Lending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for Greater Pittsburgh buyers in stable, fast-pending markets.',
    website: 'https://greaterpittsburghcu.org', phone: '(412) 555-3208',
  },
  {
    id: 'pa-21', slug: 'baden-hot-suburb-mortgage-greater-pittsburgh', name: 'Baden Hot-Suburb Specialists (Beaver County)', nmlsId: '474618', type: 'Broker',
    city: 'Baden', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Beaver', countySlug: 'beaver',
    zipCodes: ['15005', '15009', '15066'], rating: 4.9, reviewCount: 265, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Baden #3 Hot Suburb', '8–14 Day Pending', 'Fast-Market Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 16, onTimeCloseRate: 97,
    shortDescription: 'Baden specialist — expertise in the #3 hottest suburb with 8–14 day pending velocity.',
    website: 'https://badenhotmarketmortgage.com', phone: '(412) 555-3209',
  },
  {
    id: 'pa-22', slug: 'anchor-home-mortgage-greater-pittsburgh', name: 'Anchor Home Mortgage (Allegheny County)', nmlsId: '136890', type: 'Broker',
    city: 'Mount Lebanon', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Allegheny', countySlug: 'allegheny',
    zipCodes: ['15228', '15232', '15237'], rating: 4.9, reviewCount: 240, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Brokerage', 'Remote Worker Buyers', 'Market Stability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — personalized Greater Pittsburgh service for remote workers and stability-focused buyers.',
    website: 'https://anchorhomemortgage.com', phone: '(412) 555-3210',
  },
  {
    id: 'pa-23', slug: 'bank-of-america-mortgage-greater-pittsburgh', name: 'Bank of America Mortgage (Beaver County)', nmlsId: '399802', type: 'Bank',
    city: 'Monaca', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Beaver', countySlug: 'beaver',
    zipCodes: ['15061', '15009', '15010'], rating: 4.6, reviewCount: 510, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Remote Worker Buyers', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for remote workers relocating to Beaver County\'s hot suburbs.',
    website: 'https://bankofamerica.com/mortgage', phone: '(412) 555-3211',
  },
  {
    id: 'pa-24', slug: 'nova-home-loans-greater-pittsburgh', name: 'Nova Home Loans (Greater Pittsburgh Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Pittsburgh', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Allegheny', countySlug: 'allegheny',
    zipCodes: ['15201', '15212', '15237'], rating: 4.8, reviewCount: 255, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Financing', 'Fast-Pending Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 94,
    shortDescription: 'Greater Pittsburgh lender — localized knowledge of investor and family financing in stable Allegheny markets.',
    website: 'https://novahomeloans.com', phone: '(412) 555-3212',
  },

  // ── Central/Eastern PA — Dauphin, Lehigh & York ────────────────────────────
  {
    id: 'pa-25', slug: 'local-central-eastern-pa-independent-mortgage', name: 'Local Central/Eastern PA Independent Mortgage', nmlsId: '481293', type: 'Broker',
    city: 'Harrisburg', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Dauphin', countySlug: 'dauphin',
    zipCodes: ['17101', '17102', '17109'], rating: 4.9, reviewCount: 560, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 33, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Harrisburg 16% YoY', 'Affordability Havens', 'Government Hub Financing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Local Central/Eastern PA independent — strong knowledge of Harrisburg\'s 16% YoY growth and affordability corridors.',
    website: 'https://centraleasternpamortgage.com', phone: '(717) 555-3301',
  },
  {
    id: 'pa-26', slug: 'guild-mortgage-central-eastern-pa', name: 'Guild Mortgage (Lehigh Valley)', nmlsId: '3274', type: 'Lender',
    city: 'Allentown', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Lehigh', countySlug: 'lehigh',
    zipCodes: ['18101', '18102', '18103'], rating: 4.8, reviewCount: 415, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Lehigh Valley Operations', '22–31 Day Pending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Lehigh Valley branches — comprehensive financing for fast-pending Allentown markets.',
    website: 'https://guildmortgage.com', phone: '(610) 555-3302',
  },
  {
    id: 'pa-27', slug: 'new-american-funding-central-eastern-pa', name: 'New American Funding (York County)', nmlsId: '6606', type: 'Lender',
    city: 'York', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'York', countySlug: 'york',
    zipCodes: ['17401', '17402', '17403'], rating: 4.9, reviewCount: 370, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Wrightsville Hot Market', 'Affordability Havens'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'NAF York County team — excellent ratings for Wrightsville and York affordability-haven purchase volume.',
    website: 'https://newamericanfunding.com', phone: '(717) 555-3303',
  },
  {
    id: 'pa-28', slug: 'crosscountry-mortgage-central-eastern-pa', name: 'CrossCountry Mortgage (Harrisburg)', nmlsId: '3029', type: 'Lender',
    city: 'Harrisburg', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Dauphin', countySlug: 'dauphin',
    zipCodes: ['17101', '17110', '17111'], rating: 4.8, reviewCount: 325, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', '16% YoY Growth', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Harrisburg teams — experienced support for first-time buyers in Dauphin County\'s 16% YoY market.',
    website: 'https://crosscountrymortgage.com', phone: '(717) 555-3304',
  },
  {
    id: 'pa-29', slug: 'pierpoint-mortgage-central-eastern-pa', name: 'PierPoint Mortgage (Lehigh Valley)', nmlsId: '112844', type: 'Broker',
    city: 'Bethlehem', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Lehigh', countySlug: 'lehigh',
    zipCodes: ['18015', '18104', '18109'], rating: 4.9, reviewCount: 168, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Lehigh Valley', 'First-Time Buyers', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Lehigh Valley\'s 22–31 day pending velocity and competitive inventory.',
    website: 'https://pierpointmortgage.com', phone: '(610) 555-3305',
  },
  {
    id: 'pa-30', slug: 'silverton-mortgage-central-eastern-pa', name: 'Silverton Mortgage — York County', nmlsId: '1561', type: 'Lender',
    city: 'Wrightsville', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'York', countySlug: 'york',
    zipCodes: ['17370', '17404', '17408'], rating: 4.8, reviewCount: 142, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Wrightsville #12 Hot Market', 'Retail Local Expertise', 'Affordability Havens'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'Silverton York County retail lending — professional service for Wrightsville\'s #12 national hot-market demand.',
    website: 'https://silvertonmortgage.com', phone: '(717) 555-3306',
  },
  {
    id: 'pa-31', slug: 'lehigh-valley-first-time-mortgage-central-eastern-pa', name: 'Lehigh Valley First-Time Buyer Specialists', nmlsId: '492847', type: 'Broker',
    city: 'Allentown', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Lehigh', countySlug: 'lehigh',
    zipCodes: ['18101', '18103', '18105'], rating: 4.9, reviewCount: 475, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 39, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyer Programs', '22–31 Day Pending', 'Lehigh Valley Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'First-time buyer specialist — tailored for Lehigh Valley\'s fast-pending affordability corridors.',
    website: 'https://lehighvalleyfirstmortgage.com', phone: '(610) 555-3307',
  },
  {
    id: 'pa-32', slug: 'central-eastern-pa-community-credit-union', name: 'Central/Eastern PA Community Credit Union', nmlsId: '448291', type: 'Credit Union',
    city: 'Harrisburg', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Dauphin', countySlug: 'dauphin',
    zipCodes: ['17102', '17109', '17112'], rating: 4.9, reviewCount: 710, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Dauphin County CU', 'Affordability Havens'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for Harrisburg and Central PA buyers in high-growth affordability markets.',
    website: 'https://centraleasternpacu.org', phone: '(717) 555-3308',
  },
  {
    id: 'pa-33', slug: 'wrightsville-hot-market-mortgage-central-eastern-pa', name: 'Wrightsville Hot-Market Specialists (York County)', nmlsId: '476829', type: 'Broker',
    city: 'Wrightsville', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'York', countySlug: 'york',
    zipCodes: ['17370', '17401', '17402'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Wrightsville #12 Hot Market', 'Susquehanna Corridor', 'Affordability Haven Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Wrightsville specialist — expertise in the #12 national hot market along the Susquehanna affordability corridor.',
    website: 'https://wrightsvillehotmarketmortgage.com', phone: '(717) 555-3309',
  },
  {
    id: 'pa-34', slug: 'anchor-home-mortgage-central-eastern-pa', name: 'Anchor Home Mortgage (Lehigh Valley)', nmlsId: '136890', type: 'Broker',
    city: 'Emmaus', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Lehigh', countySlug: 'lehigh',
    zipCodes: ['18049', '18104', '18102'], rating: 4.9, reviewCount: 248, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Brokerage', 'Lehigh Valley Buyers', '22–31 Day Pending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — personalized Lehigh Valley service for fast-pending affordability-haven buyers.',
    website: 'https://anchorhomemortgage.com', phone: '(610) 555-3310',
  },
  {
    id: 'pa-35', slug: 'bank-of-america-mortgage-central-eastern-pa', name: 'Bank of America Mortgage (Harrisburg)', nmlsId: '399802', type: 'Bank',
    city: 'Harrisburg', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Dauphin', countySlug: 'dauphin',
    zipCodes: ['17101', '17102', '17110'], rating: 4.6, reviewCount: 495, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Government Sector Jobs', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for Harrisburg government and education hub relocations.',
    website: 'https://bankofamerica.com/mortgage', phone: '(717) 555-3311',
  },
  {
    id: 'pa-36', slug: 'nova-home-loans-central-eastern-pa', name: 'Nova Home Loans (Central/Eastern PA Independents)', nmlsId: '3089', type: 'Lender',
    city: 'York', state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'York', countySlug: 'york',
    zipCodes: ['17403', '17404', '17408'], rating: 4.8, reviewCount: 238, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Affordability Havens', 'York County Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 94,
    shortDescription: 'Central/Eastern PA lender — localized knowledge of York County investor and family financing in hot affordability markets.',
    website: 'https://novahomeloans.com', phone: '(717) 555-3312',
  },
];

export const PHILADELPHIA_METRO_AREA_LENDER_SLUGS = [
  'local-philadelphia-metro-independent-mortgage',
  'guild-mortgage-philadelphia-metro',
  'new-american-funding-philly-collar-counties',
  'crosscountry-mortgage-philadelphia-metro',
  'pierpoint-mortgage-philadelphia-metro',
  'silverton-mortgage-philadelphia-metro',
  'nyc-dc-relocation-mortgage-philadelphia-metro',
  'philadelphia-metro-community-credit-union',
  'move-in-ready-mortgage-philadelphia-metro',
  'anchor-home-mortgage-philadelphia-metro',
  'bank-of-america-mortgage-philadelphia-metro',
  'nova-home-loans-philadelphia-metro',
] as const;

export const GREATER_PITTSBURGH_KEY_SUBURBS_LENDER_SLUGS = [
  'local-greater-pittsburgh-independent-mortgage',
  'guild-mortgage-greater-pittsburgh',
  'new-american-funding-greater-pittsburgh',
  'crosscountry-mortgage-greater-pittsburgh',
  'pierpoint-mortgage-greater-pittsburgh',
  'silverton-mortgage-greater-pittsburgh',
  'remote-worker-mortgage-greater-pittsburgh',
  'greater-pittsburgh-community-credit-union',
  'baden-hot-suburb-mortgage-greater-pittsburgh',
  'anchor-home-mortgage-greater-pittsburgh',
  'bank-of-america-mortgage-greater-pittsburgh',
  'nova-home-loans-greater-pittsburgh',
] as const;

export const CENTRAL_EASTERN_PA_AFFORDABILITY_HAVENS_LENDER_SLUGS = [
  'local-central-eastern-pa-independent-mortgage',
  'guild-mortgage-central-eastern-pa',
  'new-american-funding-central-eastern-pa',
  'crosscountry-mortgage-central-eastern-pa',
  'pierpoint-mortgage-central-eastern-pa',
  'silverton-mortgage-central-eastern-pa',
  'lehigh-valley-first-time-mortgage-central-eastern-pa',
  'central-eastern-pa-community-credit-union',
  'wrightsville-hot-market-mortgage-central-eastern-pa',
  'anchor-home-mortgage-central-eastern-pa',
  'bank-of-america-mortgage-central-eastern-pa',
  'nova-home-loans-central-eastern-pa',
] as const;

const PHILADELPHIA_METRO_PHILADELPHIA_SUPPLEMENTS = [
  'guild-mortgage-philadelphia-metro',
  'new-american-funding-philly-collar-counties',
  'crosscountry-mortgage-philadelphia-metro',
  'pierpoint-mortgage-philadelphia-metro',
  'nyc-dc-relocation-mortgage-philadelphia-metro',
  'philadelphia-metro-community-credit-union',
  'move-in-ready-mortgage-philadelphia-metro',
  'anchor-home-mortgage-philadelphia-metro',
  'nova-home-loans-philadelphia-metro',
];

const PHILADELPHIA_METRO_MONTGOMERY_SUPPLEMENTS = [
  'new-american-funding-philly-collar-counties',
  'crosscountry-mortgage-philadelphia-metro',
  'nyc-dc-relocation-mortgage-philadelphia-metro',
  'move-in-ready-mortgage-philadelphia-metro',
  'anchor-home-mortgage-philadelphia-metro',
];

const PHILADELPHIA_METRO_CHESTER_SUPPLEMENTS = [
  'guild-mortgage-philadelphia-metro',
  'pierpoint-mortgage-philadelphia-metro',
  'philadelphia-metro-community-credit-union',
  'nova-home-loans-philadelphia-metro',
  'bank-of-america-mortgage-philadelphia-metro',
];

const PHILADELPHIA_METRO_BUCKS_SUPPLEMENTS = [
  'local-philadelphia-metro-independent-mortgage',
  'silverton-mortgage-philadelphia-metro',
  'pierpoint-mortgage-philadelphia-metro',
  'philadelphia-metro-community-credit-union',
  'nova-home-loans-philadelphia-metro',
];

const GREATER_PITTSBURGH_ALLEGHENY_SUPPLEMENTS = [
  'new-american-funding-greater-pittsburgh',
  'pierpoint-mortgage-greater-pittsburgh',
  'remote-worker-mortgage-greater-pittsburgh',
  'baden-hot-suburb-mortgage-greater-pittsburgh',
  'bank-of-america-mortgage-greater-pittsburgh',
];

const GREATER_PITTSBURGH_BEAVER_SUPPLEMENTS = [
  'guild-mortgage-greater-pittsburgh',
  'crosscountry-mortgage-greater-pittsburgh',
  'silverton-mortgage-greater-pittsburgh',
  'greater-pittsburgh-community-credit-union',
  'anchor-home-mortgage-greater-pittsburgh',
  'nova-home-loans-greater-pittsburgh',
];

const CENTRAL_EASTERN_PA_DAUPHIN_SUPPLEMENTS = [
  'guild-mortgage-central-eastern-pa',
  'new-american-funding-central-eastern-pa',
  'pierpoint-mortgage-central-eastern-pa',
  'lehigh-valley-first-time-mortgage-central-eastern-pa',
  'wrightsville-hot-market-mortgage-central-eastern-pa',
  'anchor-home-mortgage-central-eastern-pa',
  'nova-home-loans-central-eastern-pa',
];

const CENTRAL_EASTERN_PA_LEHIGH_SUPPLEMENTS = [
  'new-american-funding-central-eastern-pa',
  'crosscountry-mortgage-central-eastern-pa',
  'wrightsville-hot-market-mortgage-central-eastern-pa',
  'bank-of-america-mortgage-central-eastern-pa',
];

const CENTRAL_EASTERN_PA_YORK_SUPPLEMENTS = [
  'guild-mortgage-central-eastern-pa',
  'pierpoint-mortgage-central-eastern-pa',
  'lehigh-valley-first-time-mortgage-central-eastern-pa',
  'central-eastern-pa-community-credit-union',
  'anchor-home-mortgage-central-eastern-pa',
  'nova-home-loans-central-eastern-pa',
];

export const PENNSYLVANIA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  philadelphia: PHILADELPHIA_METRO_PHILADELPHIA_SUPPLEMENTS,
  montgomery: PHILADELPHIA_METRO_MONTGOMERY_SUPPLEMENTS,
  chester: PHILADELPHIA_METRO_CHESTER_SUPPLEMENTS,
  bucks: PHILADELPHIA_METRO_BUCKS_SUPPLEMENTS,
  allegheny: GREATER_PITTSBURGH_ALLEGHENY_SUPPLEMENTS,
  beaver: GREATER_PITTSBURGH_BEAVER_SUPPLEMENTS,
  dauphin: CENTRAL_EASTERN_PA_DAUPHIN_SUPPLEMENTS,
  lehigh: CENTRAL_EASTERN_PA_LEHIGH_SUPPLEMENTS,
  york: CENTRAL_EASTERN_PA_YORK_SUPPLEMENTS,
};

export const PHILADELPHIA_METRO_HUB_AREAS = [
  { name: 'Philadelphia', slug: 'philadelphia', highlight: '#6 hottest US market, 41%+ above asking' },
  { name: 'Montgomery County', slug: 'montgomery', highlight: 'Collar county bidding wars, move-in-ready demand' },
  { name: 'Chester County', slug: 'chester', highlight: 'Turn-key homes, NYC/DC affordability alternative' },
  { name: 'Bucks County', slug: 'bucks', highlight: 'NYC/DC relocator safety valve, competitive premiums' },
] as const;

export const GREATER_PITTSBURGH_HUB_AREAS = [
  { name: 'Pittsburgh', slug: 'allegheny', highlight: 'Market stability, remote-worker appeal' },
  { name: 'Baden', slug: 'beaver', highlight: '#3 hottest suburb, 8–14 day pending' },
  { name: 'Beaver County', slug: 'beaver', highlight: 'Fast-pending suburbs, family affordability' },
  { name: 'Allegheny County', slug: 'allegheny', highlight: 'Stable volume, remote-worker relocation hub' },
] as const;

export const CENTRAL_EASTERN_PA_HUB_AREAS = [
  { name: 'Harrisburg', slug: 'dauphin', highlight: '16% YoY growth, government hub demand' },
  { name: 'Lehigh Valley', slug: 'lehigh', highlight: '22–31 day pending, first-time buyer corridor' },
  { name: 'Wrightsville', slug: 'york', highlight: '#12 national hot market, Susquehanna corridor' },
  { name: 'York County', slug: 'york', highlight: 'Affordability haven, investor and family demand' },
] as const;