import type { Lender } from '@/lib/lender/mockData';

export const SOUTH_CAROLINA_LENDERS: Lender[] = [
  // ── Horry County (Grand Strand) ──────────────────────────────────────────────
  {
    id: 'sc-01', slug: 'silverton-mortgage-myrtle-beach', name: 'Silverton Mortgage — Myrtle Beach', nmlsId: '1730897', type: 'Lender',
    city: 'Myrtle Beach', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Horry', countySlug: 'horry',
    zipCodes: ['29577', '29579', '29526'], rating: 4.9, reviewCount: 310, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Retiree Relocations', 'Condo & Beach Financing', 'Flood Zone Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 95,
    shortDescription: 'Grand Strand branch — warrantable and non-warrantable condo lending for Northeast and Midwest retiree relocations.',
    website: 'https://silvertonmortgage.com/myrtlebeach', phone: '(843) 555-4001',
  },
  {
    id: 'sc-02', slug: 'gateway-mortgage-myrtle-beach', name: 'Gateway Mortgage — Myrtle Beach', nmlsId: '7233', type: 'Lender',
    city: 'Myrtle Beach', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Horry', countySlug: 'horry',
    zipCodes: ['29577', '29526', '29527'], rating: 4.8, reviewCount: 245, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'USDA', 'Refinance'],
    specialties: ['Manufactured Homes', 'Conway Suburbs', 'First-Time Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 31, onTimeCloseRate: 94,
    shortDescription: 'Bank-backed Gateway branch — manufactured and modular home financing in affordable Conway and Myrtle Beach suburbs.',
    website: 'https://gatewayfirst.com/locations-atms/myrtle-beach-sc', phone: '(843) 213-3380',
  },
  {
    id: 'sc-03', slug: 'union-home-mortgage-myrtle-beach', name: 'Union Home Mortgage — Oak St Team', nmlsId: '2424694', type: 'Lender',
    city: 'Myrtle Beach', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Horry', countySlug: 'horry',
    zipCodes: ['29577', '29579', '29582'], rating: 4.9, reviewCount: 198, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['FHA/VA Specialists', 'Builder Connections', 'Fast Resale Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 96,
    shortDescription: 'Myrtle Beach UHM Oak St branch — responsive FHA/VA and competitive coastal resale timelines.',
    website: 'https://uhm.com/branches/myrtle-beach', phone: '(843) 410-3932',
  },
  {
    id: 'sc-04', slug: 'guild-mortgage-grand-strand', name: 'Guild Mortgage — Grand Strand Branch', nmlsId: '3274', type: 'Lender',
    city: 'Myrtle Beach', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Horry', countySlug: 'horry',
    zipCodes: ['29577', '29582', '29526'], rating: 4.8, reviewCount: 420, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Down Payment Assistance', 'Remote Workers', 'State Grant Integration'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Grand Strand Guild team — SC housing grants and DPA for remote workers relocating to Horry County.',
    website: 'https://guildmortgage.com', phone: '(843) 555-4002',
  },
  {
    id: 'sc-05', slug: 'movement-mortgage-myrtle-beach', name: 'Movement Mortgage — Myrtle Beach', nmlsId: '39179', type: 'Lender',
    city: 'Myrtle Beach', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Horry', countySlug: 'horry',
    zipCodes: ['29577', '29579', '29526'], rating: 4.9, reviewCount: 380, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 18, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['7-Day Underwriting', 'Upfront Processing', 'Coastal Resales'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 97,
    shortDescription: 'Movement Myrtle Beach — upfront underwriting and ~7-day cycles for competitive Grand Strand listings.',
    website: 'https://movement.com', phone: '(843) 555-4003',
  },

  // ── Greenville County (Upstate) ──────────────────────────────────────────────
  {
    id: 'sc-06', slug: 'primelending-greenville', name: 'PrimeLending — Greenville Core', nmlsId: '864754', type: 'Lender',
    city: 'Greenville', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Greenville', countySlug: 'greenville',
    zipCodes: ['29615', '29601', '29607'], rating: 4.9, reviewCount: 295, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Single-Close Renovation', 'Construction Loans', 'Upstate Embedded'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Greenville PrimeLending — renovation and single-close construction for booming Upstate manufacturing corridor.',
    website: 'https://lo.primelending.com/greenville', phone: '(864) 349-0160',
  },
  {
    id: 'sc-07', slug: 'silverton-mortgage-greenville', name: 'Silverton Mortgage — Greenville/Greer', nmlsId: '2551060', type: 'Lender',
    city: 'Greer', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Greenville', countySlug: 'greenville',
    zipCodes: ['29651', '29615', '29650'], rating: 4.8, reviewCount: 175, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['BMW & Michelin Relocations', 'Manufacturing Corridor', 'Corporate Transferees'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 29, onTimeCloseRate: 95,
    shortDescription: 'Greer Silverton branch — corporate relocation pipelines for Upstate manufacturing employers.',
    website: 'https://silvertonmortgage.com/greenville', phone: '(864) 555-4101',
  },
  {
    id: 'sc-08', slug: 'fairway-mortgage-upstate', name: 'Fairway Independent Mortgage — Upstate', nmlsId: '2289', type: 'Lender',
    city: 'Greenville', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Greenville', countySlug: 'greenville',
    zipCodes: ['29601', '29615', '29607'], rating: 4.9, reviewCount: 340, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 28, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Tech Workforce', 'First-Time Buyers', 'High Purchase Volume'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 27, onTimeCloseRate: 96,
    shortDescription: 'Upstate Fairway — digital-first apps and VA/conventional for Greenville tech and manufacturing professionals.',
    website: 'https://fairway.com', phone: '(864) 555-4102',
  },
  {
    id: 'sc-09', slug: 'movement-mortgage-greenville', name: 'Movement Mortgage — Greenville Hub', nmlsId: '39179', type: 'Lender',
    city: 'Greenville', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Greenville', countySlug: 'greenville',
    zipCodes: ['29601', '29615', '29605'], rating: 4.9, reviewCount: 410, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 18, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Velocity Purchases', 'Young Professionals', 'Upfront Underwriting'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 96,
    shortDescription: 'Movement Greenville — rapid upfront underwriting for competitive downtown and suburban Upstate offers.',
    website: 'https://movement.com', phone: '(864) 555-4103',
  },

  // ── Spartanburg County (Upstate) ─────────────────────────────────────────────
  {
    id: 'sc-10', slug: 'guild-mortgage-upstate-spartanburg', name: 'Guild Mortgage — Spartanburg/Greenville', nmlsId: '3274', type: 'Lender',
    city: 'Spartanburg', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Spartanburg', countySlug: 'spartanburg',
    zipCodes: ['29301', '29302', '29306'], rating: 4.8, reviewCount: 280, trustScore: 92, countyExperienceScore: 94,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['USDA Rural Housing', 'Industrial Subdivisions', 'Zero-Down USDA'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Upstate Guild — USDA zero-down expertise for Spartanburg and Pickens outer-ring suburban growth.',
    website: 'https://guildmortgage.com', phone: '(864) 555-4104',
  },

  // ── Charleston County (Lowcountry) ───────────────────────────────────────────
  {
    id: 'sc-11', slug: 'first-home-mortgage-mt-pleasant', name: 'First Home Mortgage — Mt. Pleasant', nmlsId: '261288', type: 'Lender',
    city: 'Mount Pleasant', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Charleston', countySlug: 'charleston',
    zipCodes: ['29464', '29466', '29401'], rating: 4.9, reviewCount: 365, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Non-Warrantable Condos', 'Luxury Jumbo', 'Coastal HOA Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 32, onTimeCloseRate: 95,
    shortDescription: 'Mt. Pleasant First Home — jumbo and non-warrantable condo approvals for Charleston luxury coastal market.',
    website: 'https://firsthome.com/location/charleston-sc', phone: '(843) 216-3535',
  },
  {
    id: 'sc-12', slug: 'atlantic-bay-mortgage-charleston', name: 'Atlantic Bay Mortgage Group', nmlsId: '72043', type: 'Lender',
    city: 'Charleston', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Charleston', countySlug: 'charleston',
    zipCodes: ['29401', '29464', '29483'], rating: 4.9, reviewCount: 520, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Corporate Relocations', 'Port & Aerospace', 'Summerville Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 29, onTimeCloseRate: 95,
    shortDescription: 'Atlantic Bay Lowcountry — streamlined purchase for Boeing, Volvo, and port sector corporate transferees.',
    website: 'https://atlanticbay.com', phone: '(843) 555-4201',
  },
  {
    id: 'sc-13', slug: 'carolina-one-mortgage', name: 'Carolina One Mortgage', nmlsId: '1086435', type: 'Lender',
    city: 'Charleston', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Charleston', countySlug: 'charleston',
    zipCodes: ['29401', '29464', '29483'], rating: 4.8, reviewCount: 290, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Real Estate Integrated', 'Multi-Market Charleston', 'Flood & Wind Pool'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Carolina One — integrated with local realty networks for Mt. Pleasant, Summerville, and Charleston metro.',
    website: 'https://carolinaonemortgage.com', phone: '(843) 555-4202',
  },
  {
    id: 'sc-14', slug: 'guild-mortgage-charleston-coastal', name: 'Guild Mortgage — Charleston Coastal', nmlsId: '3274', type: 'Lender',
    city: 'Charleston', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Charleston', countySlug: 'charleston',
    zipCodes: ['29401', '29464', '29466'], rating: 4.8, reviewCount: 380, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Boeing & Volvo Transferees', 'High-Balance Conforming', 'Corporate Relocation'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 31, onTimeCloseRate: 94,
    shortDescription: 'Charleston Guild — corporate relocation tracks for aerospace and manufacturing workforce expansion.',
    website: 'https://guildmortgage.com', phone: '(843) 555-4203',
  },
  {
    id: 'sc-15', slug: 'movement-mortgage-lowcountry', name: 'Movement Mortgage — Lowcountry Team', nmlsId: '39179', type: 'Lender',
    city: 'Mount Pleasant', state: 'South Carolina', stateSlug: 'south-carolina', county: 'Charleston', countySlug: 'charleston',
    zipCodes: ['29464', '29483', '29401'], rating: 4.9, reviewCount: 445, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 18, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Rapid Coastal Closes', 'Flood Underwriting Early', 'VA/Military'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 97,
    shortDescription: 'Movement Lowcountry — upfront processing for competitive Summerville and Charleston resale markets.',
    website: 'https://movement.com', phone: '(843) 555-4204',
  },
];

export const SOUTH_CAROLINA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  spartanburg: ['primelending-greenville', 'silverton-mortgage-greenville', 'fairway-mortgage-upstate', 'movement-mortgage-greenville'],
  berkeley: ['first-home-mortgage-mt-pleasant', 'atlantic-bay-mortgage-charleston', 'carolina-one-mortgage', 'guild-mortgage-charleston-coastal', 'movement-mortgage-lowcountry'],
  dorchester: ['first-home-mortgage-mt-pleasant', 'atlantic-bay-mortgage-charleston', 'carolina-one-mortgage', 'guild-mortgage-charleston-coastal', 'movement-mortgage-lowcountry'],
  horry: [],
  greenville: [],
  charleston: [],
};

export const GRAND_STRAND_HUB_COUNTIES = [
  { name: 'Horry', slug: 'horry', highlight: 'Myrtle Beach, retirees, condo & beach financing' },
  { name: 'Georgetown', slug: 'georgetown', highlight: 'Pawleys Island, coastal reach — coming soon' },
] as const;

export const UPSTATE_SC_HUB_COUNTIES = [
  { name: 'Greenville', slug: 'greenville', highlight: 'Greenville, Greer, manufacturing & tech' },
  { name: 'Spartanburg', slug: 'spartanburg', highlight: 'USDA outer-ring, industrial subdivisions' },
  { name: 'Pickens', slug: 'pickens', highlight: 'Easley corridor — coming soon' },
] as const;

export const LOWCOUNTRY_HUB_COUNTIES = [
  { name: 'Charleston', slug: 'charleston', highlight: 'Mt. Pleasant, downtown, luxury condos' },
  { name: 'Berkeley', slug: 'berkeley', highlight: 'Summerville, Goose Creek, corporate growth' },
  { name: 'Dorchester', slug: 'dorchester', highlight: 'North Charleston suburbs — coming soon' },
] as const;