import type { Lender } from '@/lib/lender/mockData';

export const TEXAS_LENDERS: Lender[] = [
  // ── DFW Suburbs & Silicon Prairie (Collin, Denton & Grayson Counties) ─────────
  {
    id: 'tx-01', slug: 'supreme-lending-north-texas', name: 'Supreme Lending (North Texas)', nmlsId: '2129', type: 'Broker',
    city: 'Frisco', state: 'Texas', stateSlug: 'texas', county: 'Collin', countySlug: 'collin',
    zipCodes: ['75034', '75070', '75078'], rating: 4.9, reviewCount: 1680, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 26, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Corporate Relocations', 'New Construction', 'Silicon Prairie Corridor'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Texas independent broker — deep expertise in Frisco, McKinney, and Prosper corporate relocation and new-construction financing.',
    website: 'https://supremelending.com', phone: '(972) 555-9601',
  },
  {
    id: 'tx-02', slug: 'guild-mortgage-north-dfw', name: 'Guild Mortgage (North DFW)', nmlsId: '3274', type: 'Lender',
    city: 'McKinney', state: 'Texas', stateSlug: 'texas', county: 'Collin', countySlug: 'collin',
    zipCodes: ['75070', '75034', '75078'], rating: 4.8, reviewCount: 540, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'North Suburban Offices', 'Corporate Packages'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with North DFW branches — comprehensive financing for Silicon Prairie suburban boom.',
    website: 'https://guildmortgage.com', phone: '(972) 555-9602',
  },
  {
    id: 'tx-03', slug: 'new-american-funding-north-texas', name: 'New American Funding (North Texas)', nmlsId: '6606', type: 'Lender',
    city: 'Frisco', state: 'Texas', stateSlug: 'texas', county: 'Collin', countySlug: 'collin',
    zipCodes: ['75034', '75035', '75090'], rating: 4.9, reviewCount: 480, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Tech Relocations', 'Manufacturing Workforce', 'High-Volume Service'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Frisco team — excellent ratings for tech and manufacturing relocations across North Texas.',
    website: 'https://newamericanfunding.com', phone: '(972) 555-9603',
  },
  {
    id: 'tx-04', slug: 'pierpoint-mortgage-north-texas', name: 'PierPoint Mortgage (North Texas)', nmlsId: '112844', type: 'Broker',
    city: 'Frisco', state: 'Texas', stateSlug: 'texas', county: 'Collin', countySlug: 'collin',
    zipCodes: ['75034', '75070', '75078'], rating: 4.9, reviewCount: 195, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Suburban Boom Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Frisco and McKinney high-transaction suburban boom.',
    website: 'https://pierpointmortgage.com', phone: '(972) 555-9605',
  },
  {
    id: 'tx-05', slug: 'silverton-mortgage-north-dfw', name: 'Silverton Mortgage — North DFW', nmlsId: '1561', type: 'Lender',
    city: 'McKinney', state: 'Texas', stateSlug: 'texas', county: 'Denton', countySlug: 'denton',
    zipCodes: ['75078', '75070', '75034'], rating: 4.8, reviewCount: 175, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned Communities', 'North Suburban Retail', 'Prosper Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton McKinney retail lending — professional service for Prosper and north suburban master-planned communities.',
    website: 'https://silvertonmortgage.com', phone: '(972) 555-9606',
  },
  {
    id: 'tx-06', slug: 'texans-credit-union', name: 'Texans Credit Union', nmlsId: '469500', type: 'Credit Union',
    city: 'Prosper', state: 'Texas', stateSlug: 'texas', county: 'Denton', countySlug: 'denton',
    zipCodes: ['75078', '75034', '75070'], rating: 4.9, reviewCount: 620, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 72, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Community Lender', 'Affordable Suburban Options'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'DFW credit union — community-focused member rates in the high-growth Silicon Prairie corridor.',
    website: 'https://texanscu.org', phone: '(800) 843-0875',
  },
  {
    id: 'tx-07', slug: 'lennar-mortgage-north-dfw', name: 'Lennar Mortgage (North DFW)', nmlsId: '1058', type: 'Lender',
    city: 'Prosper', state: 'Texas', stateSlug: 'texas', county: 'Denton', countySlug: 'denton',
    zipCodes: ['75078', '75034', '75070'], rating: 4.7, reviewCount: 410, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned Financing', 'Frisco/McKinney New Builds', 'Northern Suburb Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Frisco, McKinney, and Prosper master-planned community financing.',
    website: 'https://lennar.com/mortgage', phone: '(972) 555-9609',
  },
  {
    id: 'tx-08', slug: 'bank-of-america-mortgage-north-dfw', name: 'Bank of America Mortgage (North DFW)', nmlsId: '399802', type: 'Bank',
    city: 'McKinney', state: 'Texas', stateSlug: 'texas', county: 'Denton', countySlug: 'denton',
    zipCodes: ['75070', '75034', '75090'], rating: 4.6, reviewCount: 740, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Corporate Relocation', 'Full-Service Banking', 'Endless Relocation Wave'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for corporate relocation packages to Frisco and McKinney.',
    website: 'https://bankofamerica.com/mortgage', phone: '(972) 555-9611',
  },
  {
    id: 'tx-09', slug: 'crosscountry-mortgage-north-dfw', name: 'CrossCountry Mortgage (North DFW)', nmlsId: '3029', type: 'Lender',
    city: 'Sherman', state: 'Texas', stateSlug: 'texas', county: 'Grayson', countySlug: 'grayson',
    zipCodes: ['75090', '75020', '75078'], rating: 4.8, reviewCount: 360, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Texas Instruments Corridor', 'Workforce Housing', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Sherman-Denison teams — experienced support for Texas Instruments and manufacturing expansions.',
    website: 'https://crosscountrymortgage.com', phone: '(903) 555-9604',
  },
  {
    id: 'tx-10', slug: 'veterans-united-north-texas', name: 'Veterans United Home Loans (North Texas)', nmlsId: '1907', type: 'Lender',
    city: 'Sherman', state: 'Texas', stateSlug: 'texas', county: 'Grayson', countySlug: 'grayson',
    zipCodes: ['75090', '75020', '75034'], rating: 4.9, reviewCount: 880, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Executive Relocations', 'Manufacturing Job Influx'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and executive relocation programs — tailored for Sherman-Denison and Frisco manufacturing/tech job influx.',
    website: 'https://veteransunited.com', phone: '(903) 555-9607',
  },
  {
    id: 'tx-11', slug: 'anchor-home-mortgage-sherman-denison', name: 'Anchor Home Mortgage (Sherman-Denison)', nmlsId: '136890', type: 'Broker',
    city: 'Sherman', state: 'Texas', stateSlug: 'texas', county: 'Grayson', countySlug: 'grayson',
    zipCodes: ['75090', '75020', '75078'], rating: 4.9, reviewCount: 285, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Workforce Housing', 'Silicon Prairie Equity', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Sherman-Denison workforce housing and Prosper equity gains.',
    website: 'https://anchorhomemortgage.com', phone: '(903) 555-9610',
  },
  {
    id: 'tx-12', slug: 'nova-home-loans-north-texas', name: 'Nova Home Loans (North Texas)', nmlsId: '3089', type: 'Lender',
    city: 'Sherman', state: 'Texas', stateSlug: 'texas', county: 'Grayson', countySlug: 'grayson',
    zipCodes: ['75078', '75090', '75070'], rating: 4.8, reviewCount: 395, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Infrastructure Growth', 'Transactional Volume'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Texas lender — localized knowledge of Prosper and Sherman growth suburbs amid infrastructure expansions.',
    website: 'https://novahomeloans.com', phone: '(972) 555-9612',
  },

  // ── Greater Houston Metro (Harris, Fort Bend & Montgomery Counties) ─────────
  {
    id: 'tx-13', slug: 'mortgage-financial-services-houston', name: 'Mortgage Financial Services (Houston)', nmlsId: '43021', type: 'Broker',
    city: 'Katy', state: 'Texas', stateSlug: 'texas', county: 'Harris', countySlug: 'harris',
    zipCodes: ['77494', '77380', '77479'], rating: 4.9, reviewCount: 1420, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned Communities', 'Family Suburban Financing', 'Resilient Houston Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 96,
    shortDescription: 'Texas independent broker — deep expertise in Katy, The Woodlands, and Sugar Land master-planned suburban financing.',
    website: 'https://mfsmortgage.com', phone: '(281) 555-9701',
  },
  {
    id: 'tx-14', slug: 'guild-mortgage-greater-houston', name: 'Guild Mortgage (Greater Houston)', nmlsId: '3274', type: 'Lender',
    city: 'Katy', state: 'Texas', stateSlug: 'texas', county: 'Harris', countySlug: 'harris',
    zipCodes: ['77494', '77380', '77304'], rating: 4.8, reviewCount: 560, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Suburban Branches', 'Stability & Family Focus'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Greater Houston branches — comprehensive financing for resilient suburban growth.',
    website: 'https://guildmortgage.com', phone: '(281) 555-9702',
  },
  {
    id: 'tx-15', slug: 'new-american-funding-greater-houston', name: 'New American Funding (Greater Houston)', nmlsId: '6606', type: 'Lender',
    city: 'Katy', state: 'Texas', stateSlug: 'texas', county: 'Harris', countySlug: 'harris',
    zipCodes: ['77494', '77380', '77479'], rating: 4.9, reviewCount: 450, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Steady Transactional Volume', 'Katy & Woodlands', 'Purchase & Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Katy team — excellent ratings for steady purchase and refinance across Greater Houston suburbs.',
    website: 'https://newamericanfunding.com', phone: '(281) 555-9703',
  },
  {
    id: 'tx-16', slug: 'pierpoint-mortgage-greater-houston', name: 'PierPoint Mortgage (Greater Houston)', nmlsId: '112844', type: 'Broker',
    city: 'Katy', state: 'Texas', stateSlug: 'texas', county: 'Harris', countySlug: 'harris',
    zipCodes: ['77494', '77304', '77479'], rating: 4.9, reviewCount: 185, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Master-Planned Absorption'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Katy and Conroe master-planned community absorption.',
    website: 'https://pierpointmortgage.com', phone: '(281) 555-9705',
  },
  {
    id: 'tx-17', slug: 'crosscountry-mortgage-greater-houston', name: 'CrossCountry Mortgage (Greater Houston)', nmlsId: '3029', type: 'Lender',
    city: 'Sugar Land', state: 'Texas', stateSlug: 'texas', county: 'Fort Bend', countySlug: 'fort-bend',
    zipCodes: ['77479', '77494', '77304'], rating: 4.8, reviewCount: 370, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Medical Sector Families', 'School-District Demand', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Sugar Land teams — experienced support for medical sector and school-district driven demand.',
    website: 'https://crosscountrymortgage.com', phone: '(281) 555-9704',
  },
  {
    id: 'tx-18', slug: 'anchor-home-mortgage-greater-houston', name: 'Anchor Home Mortgage (Greater Houston)', nmlsId: '136890', type: 'Broker',
    city: 'Sugar Land', state: 'Texas', stateSlug: 'texas', county: 'Fort Bend', countySlug: 'fort-bend',
    zipCodes: ['77479', '77380', '77494'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Manageable Price Points', 'Family Buyers', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Sugar Land and The Woodlands family buyers at manageable price points.',
    website: 'https://anchorhomemortgage.com', phone: '(281) 555-9710',
  },
  {
    id: 'tx-19', slug: 'bank-of-america-mortgage-greater-houston', name: 'Bank of America Mortgage (Greater Houston)', nmlsId: '399802', type: 'Bank',
    city: 'Sugar Land', state: 'Texas', stateSlug: 'texas', county: 'Fort Bend', countySlug: 'fort-bend',
    zipCodes: ['77479', '77494', '77380'], rating: 4.6, reviewCount: 720, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Medical Sector Relocations', 'Full-Service Banking', 'Family Moves'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for medical sector and family relocations to Katy and Sugar Land.',
    website: 'https://bankofamerica.com/mortgage', phone: '(281) 555-9711',
  },
  {
    id: 'tx-20', slug: 'first-service-credit-union-houston', name: 'First Service Credit Union', nmlsId: '411602', type: 'Credit Union',
    city: 'Sugar Land', state: 'Texas', stateSlug: 'texas', county: 'Fort Bend', countySlug: 'fort-bend',
    zipCodes: ['77479', '77304', '77494'], rating: 4.9, reviewCount: 540, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 70, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Community Lender', 'Affordable Suburban Options'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Houston-area credit union — community-focused member rates in the resilient Greater Houston metro.',
    website: 'https://fscu.com', phone: '(281) 555-9708',
  },
  {
    id: 'tx-21', slug: 'silverton-mortgage-greater-houston', name: 'Silverton Mortgage — Greater Houston', nmlsId: '1561', type: 'Lender',
    city: 'The Woodlands', state: 'Texas', stateSlug: 'texas', county: 'Montgomery', countySlug: 'montgomery',
    zipCodes: ['77380', '77304', '77479'], rating: 4.8, reviewCount: 165, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Top-Rated School Districts', 'Suburban Retail Expertise', 'The Woodlands Focus'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Woodlands retail lending — professional service for highly rated school-district suburban buyers.',
    website: 'https://silvertonmortgage.com', phone: '(281) 555-9706',
  },
  {
    id: 'tx-22', slug: 'veterans-united-greater-houston', name: 'Veterans United Home Loans (Greater Houston)', nmlsId: '1907', type: 'Lender',
    city: 'Conroe', state: 'Texas', stateSlug: 'texas', county: 'Montgomery', countySlug: 'montgomery',
    zipCodes: ['77304', '77494', '77380'], rating: 4.9, reviewCount: 920, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Energy Sector Relocations', 'Medical & Energy Jobs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and energy sector programs — tailored for Conroe and Katy buyers in Houston\'s diverse job base.',
    website: 'https://veteransunited.com', phone: '(936) 555-9707',
  },
  {
    id: 'tx-23', slug: 'lennar-mortgage-greater-houston', name: 'Lennar Mortgage (Greater Houston)', nmlsId: '1058', type: 'Lender',
    city: 'Conroe', state: 'Texas', stateSlug: 'texas', county: 'Montgomery', countySlug: 'montgomery',
    zipCodes: ['77304', '77494', '77380'], rating: 4.7, reviewCount: 380, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned New Builds', 'Katy & Conroe', 'High-Absorption Markets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Katy and Conroe master-planned community new construction.',
    website: 'https://lennar.com/mortgage', phone: '(936) 555-9709',
  },
  {
    id: 'tx-24', slug: 'nova-home-loans-greater-houston', name: 'Nova Home Loans (Greater Houston)', nmlsId: '3089', type: 'Lender',
    city: 'Conroe', state: 'Texas', stateSlug: 'texas', county: 'Montgomery', countySlug: 'montgomery',
    zipCodes: ['77304', '77494', '77479'], rating: 4.8, reviewCount: 410, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Suburban Family Growth', 'Year-Over-Year Resilience'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Texas lender — localized knowledge of Conroe and Katy suburban family financing amid positive Houston growth.',
    website: 'https://novahomeloans.com', phone: '(936) 555-9712',
  },

  // ── SpaceX Corridor / Sleepy Town Booms (Bastrop & Cameron Counties) ─────────
  {
    id: 'tx-25', slug: 'supreme-lending-spacex-corridor', name: 'Supreme Lending (SpaceX Corridor)', nmlsId: '2129', type: 'Broker',
    city: 'Bastrop', state: 'Texas', stateSlug: 'texas', county: 'Bastrop', countySlug: 'bastrop',
    zipCodes: ['78602', '78520', '78521'], rating: 4.9, reviewCount: 520, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 26, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech Relocations', 'Rural-to-Boom Financing', 'SpaceX Ecosystem Workers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Texas independent broker — deep expertise in Bastrop and Brownsville SpaceX-driven market transformation.',
    website: 'https://supremelending.com', phone: '(512) 555-9801',
  },
  {
    id: 'tx-26', slug: 'guild-mortgage-spacex-corridor', name: 'Guild Mortgage (Central & South Texas)', nmlsId: '3274', type: 'Lender',
    city: 'Bastrop', state: 'Texas', stateSlug: 'texas', county: 'Bastrop', countySlug: 'bastrop',
    zipCodes: ['78602', '78520', '78521'], rating: 4.8, reviewCount: 310, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Emerging Employment Hubs', 'Tech Relocation Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Central and South Texas reach — financing for sleepy-town-to-boom transformations.',
    website: 'https://guildmortgage.com', phone: '(512) 555-9802',
  },
  {
    id: 'tx-27', slug: 'crosscountry-mortgage-spacex-corridor', name: 'CrossCountry Mortgage (Central Texas)', nmlsId: '3029', type: 'Lender',
    city: 'Bastrop', state: 'Texas', stateSlug: 'texas', county: 'Bastrop', countySlug: 'bastrop',
    zipCodes: ['78602', '78520', '78521'], rating: 4.8, reviewCount: 265, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['SpaceX/Starlink Relocations', 'High-Earning Tech Workers', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Bastrop teams — experienced support for SpaceX, Starlink, and Boring Company engineering relocations.',
    website: 'https://crosscountrymortgage.com', phone: '(512) 555-9804',
  },
  {
    id: 'tx-28', slug: 'pierpoint-mortgage-spacex-corridor', name: 'PierPoint Mortgage (SpaceX Corridor)', nmlsId: '112844', type: 'Broker',
    city: 'Bastrop', state: 'Texas', stateSlug: 'texas', county: 'Bastrop', countySlug: 'bastrop',
    zipCodes: ['78602', '78520', '78521'], rating: 4.9, reviewCount: 140, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Hyper-Dense Hub Transitions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Bastrop and Brownsville hyper-dense employment hub transitions.',
    website: 'https://pierpointmortgage.com', phone: '(512) 555-9805',
  },
  {
    id: 'tx-29', slug: 'lennar-mortgage-spacex-corridor', name: 'Lennar Mortgage (SpaceX Corridor)', nmlsId: '1058', type: 'Lender',
    city: 'Bastrop', state: 'Texas', stateSlug: 'texas', county: 'Bastrop', countySlug: 'bastrop',
    zipCodes: ['78602', '78520', '78521'], rating: 4.7, reviewCount: 220, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Workforce Housing', 'Master-Planned Builds', 'Industrial-Adjacent Housing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Bastrop and Brownsville workforce and master-planned housing transitions.',
    website: 'https://lennar.com/mortgage', phone: '(512) 555-9809',
  },
  {
    id: 'tx-30', slug: 'rbfcu-spacex-corridor', name: 'Randolph-Brooks Federal Credit Union', nmlsId: '583215', type: 'Credit Union',
    city: 'Bastrop', state: 'Texas', stateSlug: 'texas', county: 'Bastrop', countySlug: 'bastrop',
    zipCodes: ['78602', '78520', '78521'], rating: 4.9, reviewCount: 680, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 66, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Community Lender', 'Affordable Transition Options'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Central Texas credit union — community-focused member rates in rapidly changing Bastrop and Cameron markets.',
    website: 'https://rbfcu.org', phone: '(800) 580-3300',
  },
  {
    id: 'tx-31', slug: 'new-american-funding-spacex-corridor', name: 'New American Funding (South Texas)', nmlsId: '6606', type: 'Lender',
    city: 'Brownsville', state: 'Texas', stateSlug: 'texas', county: 'Cameron', countySlug: 'cameron',
    zipCodes: ['78520', '78521', '78602'], rating: 4.9, reviewCount: 340, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Starbase Job Influx', 'High-Volume Service', 'Industrial Relocations'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Brownsville team — excellent ratings for Starbase and industrial job-driven purchase volume.',
    website: 'https://newamericanfunding.com', phone: '(956) 555-9803',
  },
  {
    id: 'tx-32', slug: 'silverton-mortgage-spacex-corridor', name: 'Silverton Mortgage — SpaceX Corridor', nmlsId: '1561', type: 'Lender',
    city: 'Brownsville', state: 'Texas', stateSlug: 'texas', county: 'Cameron', countySlug: 'cameron',
    zipCodes: ['78520', '78521', '78602'], rating: 4.8, reviewCount: 125, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Rural-to-Boom Shifts', 'Local Retail Expertise', 'Southmost Corridor'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Brownsville retail lending — professional service for Cameron County market transformation.',
    website: 'https://silvertonmortgage.com', phone: '(956) 555-9806',
  },
  {
    id: 'tx-33', slug: 'veterans-united-spacex-corridor', name: 'Veterans United (SpaceX Corridor)', nmlsId: '1907', type: 'Lender',
    city: 'Brownsville', state: 'Texas', stateSlug: 'texas', county: 'Cameron', countySlug: 'cameron',
    zipCodes: ['78520', '78521', '78602'], rating: 4.9, reviewCount: 640, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Engineering Relocations', 'Tech Workforce Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and engineering relocation programs — tailored for high-earning workers transforming Bastrop and Brownsville.',
    website: 'https://veteransunited.com', phone: '(956) 555-9807',
  },
  {
    id: 'tx-34', slug: 'anchor-home-mortgage-spacex-corridor', name: 'Anchor Home Mortgage (SpaceX Corridor)', nmlsId: '136890', type: 'Broker',
    city: 'Brownsville', state: 'Texas', stateSlug: 'texas', county: 'Cameron', countySlug: 'cameron',
    zipCodes: ['78521', '78520', '78602'], rating: 4.9, reviewCount: 210, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Engineering Workforce Housing', 'Southmost Focus', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Bastrop and Southmost SpaceX corridor engineering workforce demand.',
    website: 'https://anchorhomemortgage.com', phone: '(956) 555-9810',
  },
  {
    id: 'tx-35', slug: 'bank-of-america-mortgage-spacex-corridor', name: 'Bank of America Mortgage (SpaceX Corridor)', nmlsId: '399802', type: 'Bank',
    city: 'Brownsville', state: 'Texas', stateSlug: 'texas', county: 'Cameron', countySlug: 'cameron',
    zipCodes: ['78520', '78602', '78521'], rating: 4.6, reviewCount: 480, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Corporate Relocation', 'Full-Service Banking', 'Empire Expansion Financing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for corporate expansions to Brownsville and Bastrop corridors.',
    website: 'https://bankofamerica.com/mortgage', phone: '(956) 555-9811',
  },
  {
    id: 'tx-36', slug: 'nova-home-loans-spacex-corridor', name: 'Nova Home Loans (SpaceX Corridor)', nmlsId: '3089', type: 'Lender',
    city: 'Brownsville', state: 'Texas', stateSlug: 'texas', county: 'Cameron', countySlug: 'cameron',
    zipCodes: ['78520', '78521', '78602'], rating: 4.8, reviewCount: 275, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Boomtown Velocity', 'Rural Transformation'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Texas lender — localized knowledge of Cameron and Bastrop boomtown financing amid immense transactional velocity.',
    website: 'https://novahomeloans.com', phone: '(956) 555-9812',
  },

  // ── San Antonio Value Play (Bexar County) ─────────────────────────────────────
  {
    id: 'tx-37', slug: 'prime-lending-san-antonio', name: 'PrimeLending (San Antonio)', nmlsId: '13649', type: 'Broker',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78209', '78230', '78249'], rating: 4.9, reviewCount: 1240, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 28, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Cash-Flow Investors', 'Military Family Financing', 'Stable Renter Pool'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'San Antonio independent broker — deep expertise in cash-flow investor deals and military family financing in Bexar County.',
    website: 'https://primelending.com', phone: '(210) 555-9901',
  },
  {
    id: 'tx-38', slug: 'guild-mortgage-san-antonio', name: 'Guild Mortgage (San Antonio)', nmlsId: '3274', type: 'Lender',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78209', '78230', '78216'], rating: 4.8, reviewCount: 520, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Military & Investor Expertise', 'Bexar County Branches'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with San Antonio branches — comprehensive financing for investors and military families in the stable Bexar market.',
    website: 'https://guildmortgage.com', phone: '(210) 555-9902',
  },
  {
    id: 'tx-39', slug: 'new-american-funding-san-antonio', name: 'New American Funding (San Antonio)', nmlsId: '6606', type: 'Lender',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78230', '78249', '78209'], rating: 4.9, reviewCount: 465, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Investor Transactions', 'Military Relocations'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF San Antonio team — excellent ratings for investor and military transactions across the leveled Bexar County market.',
    website: 'https://newamericanfunding.com', phone: '(210) 555-9903',
  },
  {
    id: 'tx-40', slug: 'crosscountry-mortgage-san-antonio', name: 'CrossCountry Mortgage (San Antonio)', nmlsId: '3029', type: 'Lender',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78209', '78216', '78230'], rating: 4.8, reviewCount: 385, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Defense-Related Buyers', 'Broad Product Menu', '240K+ Defense Jobs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry San Antonio teams — experienced support for defense-related buyers and the massive military renter pool.',
    website: 'https://crosscountrymortgage.com', phone: '(210) 555-9904',
  },
  {
    id: 'tx-41', slug: 'pierpoint-mortgage-san-antonio', name: 'PierPoint Mortgage (San Antonio)', nmlsId: '112844', type: 'Broker',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78230', '78249', '78209'], rating: 4.9, reviewCount: 210, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Investor Cash-Flow', 'Transparent Pricing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed and transparency in San Antonio\'s leveled-off pricing market for investors and first-time buyers.',
    website: 'https://pierpointmortgage.com', phone: '(210) 555-9905',
  },
  {
    id: 'tx-42', slug: 'silverton-mortgage-san-antonio', name: 'Silverton Mortgage — San Antonio', nmlsId: '1561', type: 'Lender',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78209', '78216', '78230'], rating: 4.8, reviewCount: 165, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail Lending', 'Local Expertise', 'Stable Metro Financing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton San Antonio retail lending — professional service for the stable, accessible Bexar County metro.',
    website: 'https://silvertonmortgage.com', phone: '(210) 555-9906',
  },
  {
    id: 'tx-43', slug: 'veterans-united-san-antonio', name: 'Veterans United (San Antonio)', nmlsId: '1907', type: 'Lender',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78209', '78230', '78249'], rating: 4.9, reviewCount: 920, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Defense Community Programs', 'Military Footprint'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and defense community programs — tailored for San Antonio\'s massive military footprint and stable renter demand.',
    website: 'https://veteransunited.com', phone: '(210) 555-9907',
  },
  {
    id: 'tx-44', slug: 'security-service-fcu-san-antonio', name: 'Security Service Federal Credit Union', nmlsId: '458903', type: 'Credit Union',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78230', '78249', '78216'], rating: 4.9, reviewCount: 780, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 68, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Cash-Flow Investor Options', 'Community Lender'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'San Antonio credit union — community-focused member rates for value-oriented buyers and cash-flow investors.',
    website: 'https://ssfcu.org', phone: '(800) 525-9623',
  },
  {
    id: 'tx-45', slug: 'lennar-mortgage-san-antonio', name: 'Lennar Mortgage (San Antonio)', nmlsId: '1058', type: 'Lender',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78249', '78258', '78230'], rating: 4.7, reviewCount: 395, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Construction', 'Workforce Housing', 'Military-Adjacent Builds'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in San Antonio suburb new construction with built-in renter demand from defense jobs.',
    website: 'https://lennar.com/mortgage', phone: '(210) 555-9909',
  },
  {
    id: 'tx-46', slug: 'anchor-home-mortgage-san-antonio', name: 'Anchor Home Mortgage (San Antonio)', nmlsId: '136890', type: 'Broker',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78209', '78230', '78249'], rating: 4.9, reviewCount: 265, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Cash-Flow Investors', 'Personalized Brokerage', 'Positive Cash Flow'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on immediate positive cash-flow opportunities in the leveled San Antonio market.',
    website: 'https://anchorhomemortgage.com', phone: '(210) 555-9910',
  },
  {
    id: 'tx-47', slug: 'bank-of-america-mortgage-san-antonio', name: 'Bank of America Mortgage (San Antonio)', nmlsId: '399802', type: 'Bank',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78230', '78216', '78209'], rating: 4.6, reviewCount: 690, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Military Relocation', 'Full-Service Banking', 'Defense Stability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for military and relocation financing in defense-anchored San Antonio.',
    website: 'https://bankofamerica.com/mortgage', phone: '(210) 555-9911',
  },
  {
    id: 'tx-48', slug: 'nova-home-loans-san-antonio', name: 'Nova Home Loans (San Antonio)', nmlsId: '3089', type: 'Lender',
    city: 'San Antonio', state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar',
    zipCodes: ['78249', '78230', '78209'], rating: 4.8, reviewCount: 340, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Value-Play', 'Leveled Pricing Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Texas lender — localized knowledge of Bexar County value-play financing and the massive built-in renter pool.',
    website: 'https://novahomeloans.com', phone: '(210) 555-9912',
  },
];

export const DFW_SILICON_PRAIRIE_LENDER_SLUGS = [
  'supreme-lending-north-texas',
  'guild-mortgage-north-dfw',
  'new-american-funding-north-texas',
  'crosscountry-mortgage-north-dfw',
  'pierpoint-mortgage-north-texas',
  'silverton-mortgage-north-dfw',
  'veterans-united-north-texas',
  'texans-credit-union',
  'lennar-mortgage-north-dfw',
  'anchor-home-mortgage-sherman-denison',
  'bank-of-america-mortgage-north-dfw',
  'nova-home-loans-north-texas',
] as const;

const COLLIN_SUPPLEMENTS = [
  'silverton-mortgage-north-dfw',
  'texans-credit-union',
  'lennar-mortgage-north-dfw',
  'bank-of-america-mortgage-north-dfw',
  'crosscountry-mortgage-north-dfw',
  'veterans-united-north-texas',
  'anchor-home-mortgage-sherman-denison',
  'nova-home-loans-north-texas',
];

const DENTON_SUPPLEMENTS = [
  'supreme-lending-north-texas',
  'guild-mortgage-north-dfw',
  'new-american-funding-north-texas',
  'pierpoint-mortgage-north-texas',
  'crosscountry-mortgage-north-dfw',
  'veterans-united-north-texas',
  'anchor-home-mortgage-sherman-denison',
  'nova-home-loans-north-texas',
];

const GRAYSON_SUPPLEMENTS = [
  'supreme-lending-north-texas',
  'guild-mortgage-north-dfw',
  'new-american-funding-north-texas',
  'pierpoint-mortgage-north-texas',
  'silverton-mortgage-north-dfw',
  'texans-credit-union',
  'lennar-mortgage-north-dfw',
  'bank-of-america-mortgage-north-dfw',
];

export const GREATER_HOUSTON_LENDER_SLUGS = [
  'mortgage-financial-services-houston',
  'guild-mortgage-greater-houston',
  'new-american-funding-greater-houston',
  'crosscountry-mortgage-greater-houston',
  'pierpoint-mortgage-greater-houston',
  'silverton-mortgage-greater-houston',
  'veterans-united-greater-houston',
  'first-service-credit-union-houston',
  'lennar-mortgage-greater-houston',
  'anchor-home-mortgage-greater-houston',
  'bank-of-america-mortgage-greater-houston',
  'nova-home-loans-greater-houston',
] as const;

const HARRIS_SUPPLEMENTS = [
  'crosscountry-mortgage-greater-houston',
  'anchor-home-mortgage-greater-houston',
  'bank-of-america-mortgage-greater-houston',
  'first-service-credit-union-houston',
  'silverton-mortgage-greater-houston',
  'veterans-united-greater-houston',
  'lennar-mortgage-greater-houston',
  'nova-home-loans-greater-houston',
];

const FORT_BEND_SUPPLEMENTS = [
  'mortgage-financial-services-houston',
  'guild-mortgage-greater-houston',
  'new-american-funding-greater-houston',
  'pierpoint-mortgage-greater-houston',
  'silverton-mortgage-greater-houston',
  'veterans-united-greater-houston',
  'lennar-mortgage-greater-houston',
  'nova-home-loans-greater-houston',
];

const MONTGOMERY_SUPPLEMENTS = [
  'mortgage-financial-services-houston',
  'guild-mortgage-greater-houston',
  'new-american-funding-greater-houston',
  'pierpoint-mortgage-greater-houston',
  'crosscountry-mortgage-greater-houston',
  'anchor-home-mortgage-greater-houston',
  'bank-of-america-mortgage-greater-houston',
  'first-service-credit-union-houston',
];

export const SPACEX_CORRIDOR_LENDER_SLUGS = [
  'supreme-lending-spacex-corridor',
  'guild-mortgage-spacex-corridor',
  'new-american-funding-spacex-corridor',
  'crosscountry-mortgage-spacex-corridor',
  'pierpoint-mortgage-spacex-corridor',
  'silverton-mortgage-spacex-corridor',
  'veterans-united-spacex-corridor',
  'rbfcu-spacex-corridor',
  'lennar-mortgage-spacex-corridor',
  'anchor-home-mortgage-spacex-corridor',
  'bank-of-america-mortgage-spacex-corridor',
  'nova-home-loans-spacex-corridor',
] as const;

const BASTROP_SUPPLEMENTS = [
  'new-american-funding-spacex-corridor',
  'silverton-mortgage-spacex-corridor',
  'veterans-united-spacex-corridor',
  'anchor-home-mortgage-spacex-corridor',
  'bank-of-america-mortgage-spacex-corridor',
  'nova-home-loans-spacex-corridor',
];

const CAMERON_SUPPLEMENTS = [
  'supreme-lending-spacex-corridor',
  'guild-mortgage-spacex-corridor',
  'crosscountry-mortgage-spacex-corridor',
  'pierpoint-mortgage-spacex-corridor',
  'lennar-mortgage-spacex-corridor',
  'rbfcu-spacex-corridor',
];

export const SAN_ANTONIO_VALUE_PLAY_LENDER_SLUGS = [
  'prime-lending-san-antonio',
  'guild-mortgage-san-antonio',
  'new-american-funding-san-antonio',
  'crosscountry-mortgage-san-antonio',
  'pierpoint-mortgage-san-antonio',
  'silverton-mortgage-san-antonio',
  'veterans-united-san-antonio',
  'security-service-fcu-san-antonio',
  'lennar-mortgage-san-antonio',
  'anchor-home-mortgage-san-antonio',
  'bank-of-america-mortgage-san-antonio',
  'nova-home-loans-san-antonio',
] as const;

export const TEXAS_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  collin: COLLIN_SUPPLEMENTS,
  denton: DENTON_SUPPLEMENTS,
  grayson: GRAYSON_SUPPLEMENTS,
  harris: HARRIS_SUPPLEMENTS,
  'fort-bend': FORT_BEND_SUPPLEMENTS,
  montgomery: MONTGOMERY_SUPPLEMENTS,
  bastrop: BASTROP_SUPPLEMENTS,
  cameron: CAMERON_SUPPLEMENTS,
  bexar: [],
};

export const DFW_SILICON_PRAIRIE_HUB_COUNTIES = [
  { name: 'Collin', slug: 'collin', highlight: 'Frisco, McKinney & Prosper suburban boom' },
  { name: 'Denton', slug: 'denton', highlight: 'Prosper growth, master-planned volume' },
  { name: 'Grayson', slug: 'grayson', highlight: 'Sherman-Denison, Texas Instruments corridor' },
] as const;

export const DFW_SILICON_PRAIRIE_HUB_AREAS = [
  { name: 'Frisco', slug: 'collin', highlight: 'Corporate relocations, Silicon Prairie HQ' },
  { name: 'McKinney', slug: 'collin', highlight: 'Master-planned, high-transaction volume' },
  { name: 'Prosper', slug: 'denton', highlight: 'Infrastructure expansion, equity gains' },
  { name: 'Sherman-Denison', slug: 'grayson', highlight: 'Manufacturing & workforce housing' },
] as const;

export const GREATER_HOUSTON_HUB_COUNTIES = [
  { name: 'Harris', slug: 'harris', highlight: 'Katy master-planned, resilient suburban core' },
  { name: 'Fort Bend', slug: 'fort-bend', highlight: 'Sugar Land, top schools & medical sector' },
  { name: 'Montgomery', slug: 'montgomery', highlight: 'The Woodlands & Conroe growth corridor' },
] as const;

export const GREATER_HOUSTON_HUB_AREAS = [
  { name: 'Katy', slug: 'harris', highlight: 'Master-planned, high-absorption new builds' },
  { name: 'The Woodlands', slug: 'montgomery', highlight: 'Top-rated schools, family stability' },
  { name: 'Sugar Land', slug: 'fort-bend', highlight: 'Medical sector, manageable pricing' },
  { name: 'Conroe', slug: 'montgomery', highlight: 'Energy sector, positive YoY growth' },
] as const;

export const SPACEX_CORRIDOR_HUB_COUNTIES = [
  { name: 'Bastrop', slug: 'bastrop', highlight: 'SpaceX, Starlink & Boring Company corridor' },
  { name: 'Cameron', slug: 'cameron', highlight: 'Starbase, Brownsville & Southmost boom' },
] as const;

export const SPACEX_CORRIDOR_HUB_AREAS = [
  { name: 'Bastrop', slug: 'bastrop', highlight: 'Austin-adjacent sleepy town transformation' },
  { name: 'Brownsville', slug: 'cameron', highlight: 'Starbase industrial job influx' },
  { name: 'Southmost', slug: 'cameron', highlight: 'Workforce housing, rural-to-boom' },
  { name: 'Starbase Corridor', slug: 'cameron', highlight: 'Hyper-dense employment hub growth' },
] as const;

export const SAN_ANTONIO_VALUE_PLAY_HUB_COUNTIES = [
  { name: 'Bexar', slug: 'bexar', highlight: 'San Antonio metro, defense-anchored value play' },
] as const;

export const SAN_ANTONIO_VALUE_PLAY_HUB_AREAS = [
  { name: 'Alamo Heights', slug: 'bexar', highlight: 'Established neighborhoods, stable renter demand' },
  { name: 'Medical Center', slug: 'bexar', highlight: 'Healthcare jobs, cash-flow duplexes' },
  { name: 'Stone Oak', slug: 'bexar', highlight: 'Suburban workforce housing, new builds' },
  { name: 'UTSA Corridor', slug: 'bexar', highlight: 'Military-adjacent, leveled pricing' },
] as const;