import type { Lender } from '@/lib/lender/mockData';

export const WASHINGTON_LENDERS: Lender[] = [
  // ── Snohomish County Transit Corridor (Lynnwood & Everett) ───────────────────
  {
    id: 'wa-01', slug: 'summit-mortgage-snohomish', name: 'Summit Mortgage (Snohomish)', nmlsId: '2561', type: 'Broker',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98037', '98201'], rating: 4.9, reviewCount: 890, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Light Rail Commuter Financing', 'Aerospace Buyers', 'Transit-Driven Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Pacific Northwest independent broker — deep expertise in light rail commuter and Boeing-area financing across Snohomish County.',
    website: 'https://summitmortgage.com', phone: '(425) 555-9701',
  },
  {
    id: 'wa-02', slug: 'guild-mortgage-snohomish', name: 'Guild Mortgage (Snohomish)', nmlsId: '3274', type: 'Lender',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98201', '98203'], rating: 4.8, reviewCount: 485, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Commuter & Aerospace Expertise', 'North Corridor Branches'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Lynnwood and Everett branches — comprehensive financing for light rail commuters and aerospace professionals.',
    website: 'https://guildmortgage.com', phone: '(425) 555-9702',
  },
  {
    id: 'wa-03', slug: 'new-american-funding-snohomish', name: 'New American Funding (Snohomish)', nmlsId: '6606', type: 'Lender',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98037', '98201', '98208'], rating: 4.9, reviewCount: 420, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Commuter Buyers', 'Boeing-Area Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Lynnwood team — excellent ratings for commuter and Boeing-area buyers in the north Sound corridor.',
    website: 'https://newamericanfunding.com', phone: '(425) 555-9703',
  },
  {
    id: 'wa-04', slug: 'crosscountry-mortgage-snohomish', name: 'CrossCountry Mortgage (Snohomish)', nmlsId: '3029', type: 'Lender',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98203', '98036'], rating: 4.8, reviewCount: 365, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Tech & Aerospace Professionals', 'Light Rail Corridor', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Everett-Lynnwood teams — experienced support for light rail proximity demand and Boeing job corridor buyers.',
    website: 'https://crosscountrymortgage.com', phone: '(425) 555-9704',
  },
  {
    id: 'wa-05', slug: 'pierpoint-mortgage-north-sound', name: 'PierPoint Mortgage (North Sound)', nmlsId: '112844', type: 'Broker',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98201', '98208'], rating: 4.9, reviewCount: 195, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Transit-Station Proximity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Lynnwood and Everett transit-station proximity demand and rapid absorption.',
    website: 'https://pierpointmortgage.com', phone: '(425) 555-9705',
  },
  {
    id: 'wa-06', slug: 'silverton-mortgage-snohomish', name: 'Silverton Mortgage — Snohomish', nmlsId: '1561', type: 'Lender',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98203', '98037'], rating: 4.8, reviewCount: 155, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail Lending', 'Water Views & Single-Family', 'Snohomish Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Everett retail lending — professional service for water views and single-family options below Seattle medians.',
    website: 'https://silvertonmortgage.com', phone: '(425) 555-9706',
  },
  {
    id: 'wa-07', slug: 'veterans-united-snohomish', name: 'Veterans United (Snohomish)', nmlsId: '1907', type: 'Lender',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98208', '98036'], rating: 4.9, reviewCount: 720, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Boeing Relocation Programs', 'Aerospace Job Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and Boeing-related relocation programs — tailored for Everett\'s robust aerospace job market and defense-adjacent buyers.',
    website: 'https://veteransunited.com', phone: '(425) 555-9707',
  },
  {
    id: 'wa-08', slug: 'becu-snohomish', name: 'BECU (Boeing Employees Credit Union)', nmlsId: '409610', type: 'Credit Union',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98201', '98203'], rating: 4.9, reviewCount: 1120, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Commuter Financing', 'Aerospace Community CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Washington credit union — community-focused member rates for commuters and aerospace professionals near light rail stations.',
    website: 'https://becu.org', phone: '(800) 233-2328',
  },
  {
    id: 'wa-09', slug: 'lennar-mortgage-snohomish', name: 'Lennar Mortgage (Snohomish)', nmlsId: '1058', type: 'Lender',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98037', '98208', '98036'], rating: 4.7, reviewCount: 380, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Transit-Oriented Development', 'Station-Area Housing', 'New Construction'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Lynnwood transit-adjacent new construction with rapidly absorbing station-area demand.',
    website: 'https://lennar.com/mortgage', phone: '(425) 555-9709',
  },
  {
    id: 'wa-10', slug: 'anchor-home-mortgage-snohomish', name: 'Anchor Home Mortgage (Snohomish)', nmlsId: '136890', type: 'Broker',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98036', '98203'], rating: 4.9, reviewCount: 245, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['North Corridor Buyers', 'Single-Family Below Seattle', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on single-family options below Seattle medians in the Lynnwood-Everett north corridor.',
    website: 'https://anchorhomemortgage.com', phone: '(425) 555-9710',
  },
  {
    id: 'wa-11', slug: 'bank-of-america-mortgage-snohomish', name: 'Bank of America Mortgage (Snohomish)', nmlsId: '399802', type: 'Bank',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98201', '98208'], rating: 4.6, reviewCount: 620, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech/Aerospace Relocation', 'Full-Service Banking', 'Commuter Financing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for tech and aerospace commuters relocating to Lynnwood and Everett.',
    website: 'https://bankofamerica.com/mortgage', phone: '(425) 555-9711',
  },
  {
    id: 'wa-12', slug: 'nova-home-loans-snohomish', name: 'Nova Home Loans (Snohomish)', nmlsId: '3089', type: 'Lender',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98203', '98037'], rating: 4.8, reviewCount: 310, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Transit Corridor', 'Light Rail Effect'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Washington lender — localized knowledge of Snohomish light rail effect and steady north corridor family demand.',
    website: 'https://novahomeloans.com', phone: '(425) 555-9712',
  },

  // ── South Sound (Pierce County — Tacoma & Puyallup) ──────────────────────────
  {
    id: 'wa-13', slug: 'heritage-home-mortgage-south-sound', name: 'Heritage Home Mortgage (South Sound)', nmlsId: '124684', type: 'Broker',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98403', '98405', '98373'], rating: 4.9, reviewCount: 760, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Commuter-Rail Financing', 'Family Suburban Buyers', 'Affordability Safety Valve'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'South Sound independent broker — deep expertise in Sounder commuter and family suburban financing across Pierce County.',
    website: 'https://heritagehomemortgage.com', phone: '(253) 555-9801',
  },
  {
    id: 'wa-14', slug: 'guild-mortgage-south-sound', name: 'Guild Mortgage (South Sound)', nmlsId: '3274', type: 'Lender',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98403', '98374', '98405'], rating: 4.8, reviewCount: 470, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Commuter & Military Expertise', 'Pierce County Branches'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Tacoma and Puyallup branches — comprehensive financing for historic districts and suburban growth.',
    website: 'https://guildmortgage.com', phone: '(253) 555-9802',
  },
  {
    id: 'wa-15', slug: 'new-american-funding-tacoma', name: 'New American Funding (Tacoma)', nmlsId: '6606', type: 'Lender',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98403', '98406', '98373'], rating: 4.9, reviewCount: 405, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'North End/Proctor Demand', 'Puyallup Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Tacoma team — excellent ratings for North End/Proctor and Puyallup purchase demand in the safety-valve market.',
    website: 'https://newamericanfunding.com', phone: '(253) 555-9803',
  },
  {
    id: 'wa-16', slug: 'crosscountry-mortgage-south-sound', name: 'CrossCountry Mortgage (South Sound)', nmlsId: '3029', type: 'Lender',
    city: 'Puyallup', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98373', '98405', '98403'], rating: 4.8, reviewCount: 355, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['JBLM Military Families', 'Sounder Train Corridor', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Puyallup-Tacoma teams — experienced support for JBLM families and Sounder train commuter corridor buyers.',
    website: 'https://crosscountrymortgage.com', phone: '(253) 555-9804',
  },
  {
    id: 'wa-17', slug: 'pierpoint-mortgage-south-sound', name: 'PierPoint Mortgage (South Sound)', nmlsId: '112844', type: 'Broker',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98403', '98374', '98405'], rating: 4.9, reviewCount: 185, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Competitive Mid-Sized Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Tacoma and Puyallup\'s competitive mid-sized city purchase market.',
    website: 'https://pierpointmortgage.com', phone: '(253) 555-9805',
  },
  {
    id: 'wa-18', slug: 'silverton-mortgage-south-sound', name: 'Silverton Mortgage — South Sound', nmlsId: '1561', type: 'Lender',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98405', '98403', '98373'], rating: 4.8, reviewCount: 148, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail Lending', 'Historic Charm & New Subdivisions', 'Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Tacoma retail lending — professional service for historic charm districts and newer Puyallup subdivisions.',
    website: 'https://silvertonmortgage.com', phone: '(253) 555-9806',
  },
  {
    id: 'wa-19', slug: 'veterans-united-south-sound', name: 'Veterans United (South Sound)', nmlsId: '1907', type: 'Lender',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98418', '98405', '98373'], rating: 4.9, reviewCount: 840, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'JBLM Proximity', 'Defense Community Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and defense community programs — tailored for Joint Base Lewis-McChord proximity and military families in Pierce County.',
    website: 'https://veteransunited.com', phone: '(253) 555-9807',
  },
  {
    id: 'wa-20', slug: 'sound-credit-union-south-sound', name: 'Sound Credit Union', nmlsId: '402075', type: 'Credit Union',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98403', '98374', '98405'], rating: 4.9, reviewCount: 920, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 70, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Affordable Commuter Options', 'Community Lender'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Pierce County credit union — community-focused member rates in the high-value affordability safety-valve market.',
    website: 'https://soundcu.com', phone: '(800) 556-9400',
  },
  {
    id: 'wa-21', slug: 'lennar-mortgage-south-sound', name: 'Lennar Mortgage (South Sound)', nmlsId: '1058', type: 'Lender',
    city: 'Puyallup', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98374', '98373', '98403'], rating: 4.7, reviewCount: 365, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned Communities', 'Puyallup Suburban Growth', 'New Construction'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Puyallup master-planned community financing and suburban powerhouse growth.',
    website: 'https://lennar.com/mortgage', phone: '(253) 555-9809',
  },
  {
    id: 'wa-22', slug: 'anchor-home-mortgage-south-sound', name: 'Anchor Home Mortgage (South Sound)', nmlsId: '136890', type: 'Broker',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98403', '98373', '98405'], rating: 4.9, reviewCount: 255, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['North End/Proctor Buyers', 'Personalized Brokerage', '$564K Median Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Tacoma North End and Puyallup buyers at roughly $300K below King County medians.',
    website: 'https://anchorhomemortgage.com', phone: '(253) 555-9810',
  },
  {
    id: 'wa-23', slug: 'bank-of-america-mortgage-south-sound', name: 'Bank of America Mortgage (South Sound)', nmlsId: '399802', type: 'Bank',
    city: 'Tacoma', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98405', '98373', '98403'], rating: 4.6, reviewCount: 580, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Seattle Commuter Relocation', 'Military Families', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for Seattle commuters and military families relocating to Tacoma and Puyallup.',
    website: 'https://bankofamerica.com/mortgage', phone: '(253) 555-9811',
  },
  {
    id: 'wa-24', slug: 'nova-home-loans-south-sound', name: 'Nova Home Loans (South Sound)', nmlsId: '3089', type: 'Lender',
    city: 'Puyallup', state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce',
    zipCodes: ['98374', '98403', '98373'], rating: 4.8, reviewCount: 295, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Historic Charm & Schools', 'Sounder Rail Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Washington lender — localized knowledge of Pierce County commuter corridor, historic charm, and steady South Sound demand.',
    website: 'https://novahomeloans.com', phone: '(253) 555-9812',
  },

  // ── Southwest Washington / Portland Border (Clark County — Vancouver) ─────────
  {
    id: 'wa-25', slug: 'columbia-river-mortgage-vancouver', name: 'Columbia River Mortgage (Vancouver)', nmlsId: '178942', type: 'Broker',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98660', '98661', '98662'], rating: 4.9, reviewCount: 680, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tax-Advantage Relocation', 'Waterfront Financing', 'Portland-Border Dynamics'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Vancouver independent broker — deep expertise in tax-advantage relocation and waterfront financing across the Portland border.',
    website: 'https://columbiarivermortgage.com', phone: '(360) 555-9901',
  },
  {
    id: 'wa-26', slug: 'guild-mortgage-vancouver', name: 'Guild Mortgage (Vancouver)', nmlsId: '3274', type: 'Lender',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98660', '98663', '98661'], rating: 4.8, reviewCount: 455, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Tax-Advantage Relocation', 'Clark County Branches'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Vancouver branches — comprehensive financing for tax-haven lifestyle migration across the Columbia River.',
    website: 'https://guildmortgage.com', phone: '(360) 555-9902',
  },
  {
    id: 'wa-27', slug: 'new-american-funding-vancouver', name: 'New American Funding (Vancouver)', nmlsId: '6606', type: 'Lender',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98662', '98660', '98664'], rating: 4.9, reviewCount: 395, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Remote Worker Relocations', 'Retiree Moves'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Vancouver team — excellent ratings for remote worker and retiree relocations in the Portland-border tax corridor.',
    website: 'https://newamericanfunding.com', phone: '(360) 555-9903',
  },
  {
    id: 'wa-28', slug: 'crosscountry-mortgage-southwest-wa', name: 'CrossCountry Mortgage (Southwest WA)', nmlsId: '3029', type: 'Lender',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98660', '98661', '98663'], rating: 4.8, reviewCount: 340, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Cross-River Commuters', 'Waterfront Revitalization', 'Tax Advantage Products'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Vancouver teams — experienced support for waterfront revitalization and tax-advantaged cross-river relocations.',
    website: 'https://crosscountrymortgage.com', phone: '(360) 555-9904',
  },
  {
    id: 'wa-29', slug: 'pierpoint-mortgage-northwest', name: 'PierPoint Mortgage (Northwest)', nmlsId: '112844', type: 'Broker',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98662', '98660', '98661'], rating: 4.9, reviewCount: 175, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Portland Spillover Volume'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Vancouver\'s high transactional volume from Portland cost-of-living spillover.',
    website: 'https://pierpointmortgage.com', phone: '(360) 555-9905',
  },
  {
    id: 'wa-30', slug: 'silverton-mortgage-vancouver', name: 'Silverton Mortgage — Vancouver', nmlsId: '1561', type: 'Lender',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98660', '98663', '98662'], rating: 4.8, reviewCount: 142, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail Lending', 'Lifestyle Migration Buyers', 'Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Vancouver retail lending — professional service for lifestyle migration buyers in the tax-haven corridor.',
    website: 'https://silvertonmortgage.com', phone: '(360) 555-9906',
  },
  {
    id: 'wa-31', slug: 'veterans-united-vancouver', name: 'Veterans United (Vancouver)', nmlsId: '1907', type: 'Lender',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98661', '98660', '98664'], rating: 4.9, reviewCount: 680, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Retirement Relocation', 'Tax-Savings Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and retirement relocation programs — tailored for families and retirees seeking Washington tax advantages near Portland.',
    website: 'https://veteransunited.com', phone: '(360) 555-9907',
  },
  {
    id: 'wa-32', slug: 'iq-credit-union-vancouver', name: 'iQ Credit Union', nmlsId: '411617', type: 'Credit Union',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98660', '98662', '98663'], rating: 4.9, reviewCount: 850, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 65, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Cross-Border Financing', 'Community Lender'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Clark County credit union — community-focused member rates for cross-border buyers in the Portland tax-haven corridor.',
    website: 'https://iqcu.com', phone: '(800) 233-2328',
  },
  {
    id: 'wa-33', slug: 'lennar-mortgage-vancouver', name: 'Lennar Mortgage (Vancouver)', nmlsId: '1058', type: 'Lender',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98660', '98661', '98664'], rating: 4.7, reviewCount: 340, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Waterfront Properties', 'Urban Infill', 'Downtown Revitalization'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in downtown Vancouver waterfront and urban-infill revitalization projects.',
    website: 'https://lennar.com/mortgage', phone: '(360) 555-9909',
  },
  {
    id: 'wa-34', slug: 'anchor-home-mortgage-vancouver', name: 'Anchor Home Mortgage (Vancouver)', nmlsId: '136890', type: 'Broker',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98660', '98662', '98661'], rating: 4.9, reviewCount: 235, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Portland-Border Buyers', 'No Income Tax Advantage', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on no-income-tax and no-sales-tax financial advantages for Portland-border relocations.',
    website: 'https://anchorhomemortgage.com', phone: '(360) 555-9910',
  },
  {
    id: 'wa-35', slug: 'bank-of-america-mortgage-vancouver', name: 'Bank of America Mortgage (Vancouver)', nmlsId: '399802', type: 'Bank',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98660', '98663', '98662'], rating: 4.6, reviewCount: 540, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Remote Worker Relocation', 'Cross-River Commuters', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for remote workers and cross-river commuters relocating to Vancouver.',
    website: 'https://bankofamerica.com/mortgage', phone: '(360) 555-9911',
  },
  {
    id: 'wa-36', slug: 'nova-home-loans-vancouver', name: 'Nova Home Loans (Vancouver)', nmlsId: '3089', type: 'Lender',
    city: 'Vancouver', state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark',
    zipCodes: ['98664', '98660', '98661'], rating: 4.8, reviewCount: 280, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Border Boom Market', 'Lifestyle Appeal'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Washington lender — localized knowledge of Clark County border boom, high transactional volume, and Columbia River lifestyle appeal.',
    website: 'https://novahomeloans.com', phone: '(360) 555-9912',
  },
];

export const SNOHOMISH_TRANSIT_CORRIDOR_LENDER_SLUGS = [
  'summit-mortgage-snohomish',
  'guild-mortgage-snohomish',
  'new-american-funding-snohomish',
  'crosscountry-mortgage-snohomish',
  'pierpoint-mortgage-north-sound',
  'silverton-mortgage-snohomish',
  'veterans-united-snohomish',
  'becu-snohomish',
  'lennar-mortgage-snohomish',
  'anchor-home-mortgage-snohomish',
  'bank-of-america-mortgage-snohomish',
  'nova-home-loans-snohomish',
] as const;

export const SOUTH_SOUND_TACOMA_PUYALLUP_LENDER_SLUGS = [
  'heritage-home-mortgage-south-sound',
  'guild-mortgage-south-sound',
  'new-american-funding-tacoma',
  'crosscountry-mortgage-south-sound',
  'pierpoint-mortgage-south-sound',
  'silverton-mortgage-south-sound',
  'veterans-united-south-sound',
  'sound-credit-union-south-sound',
  'lennar-mortgage-south-sound',
  'anchor-home-mortgage-south-sound',
  'bank-of-america-mortgage-south-sound',
  'nova-home-loans-south-sound',
] as const;

export const SOUTHWEST_WA_PORTLAND_BORDER_LENDER_SLUGS = [
  'columbia-river-mortgage-vancouver',
  'guild-mortgage-vancouver',
  'new-american-funding-vancouver',
  'crosscountry-mortgage-southwest-wa',
  'pierpoint-mortgage-northwest',
  'silverton-mortgage-vancouver',
  'veterans-united-vancouver',
  'iq-credit-union-vancouver',
  'lennar-mortgage-vancouver',
  'anchor-home-mortgage-vancouver',
  'bank-of-america-mortgage-vancouver',
  'nova-home-loans-vancouver',
] as const;

export const WASHINGTON_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  snohomish: [],
  pierce: [],
  clark: [],
};

export const SNOHOMISH_TRANSIT_CORRIDOR_HUB_COUNTIES = [
  { name: 'Snohomish', slug: 'snohomish', highlight: 'Lynnwood & Everett light rail commuter corridor' },
] as const;

export const SNOHOMISH_TRANSIT_CORRIDOR_HUB_AREAS = [
  { name: 'Lynnwood', slug: 'snohomish', highlight: 'Link light rail stations, transit-oriented absorption' },
  { name: 'Everett', slug: 'snohomish', highlight: 'Boeing aerospace hub, water views & single-family' },
  { name: 'Mountlake Terrace', slug: 'snohomish', highlight: 'Light rail effect, below-Seattle pricing' },
  { name: 'Mukilteo', slug: 'snohomish', highlight: 'Ferry corridor, steady commuter demand' },
] as const;

export const SOUTH_SOUND_TACOMA_PUYALLUP_HUB_COUNTIES = [
  { name: 'Pierce', slug: 'pierce', highlight: 'Tacoma & Puyallup affordability safety valve' },
] as const;

export const SOUTH_SOUND_TACOMA_PUYALLUP_HUB_AREAS = [
  { name: 'Tacoma North End', slug: 'pierce', highlight: 'Proctor historic charm, $564K median pricing' },
  { name: 'Puyallup', slug: 'pierce', highlight: 'Master-planned growth, excellent schools' },
  { name: 'Lakewood', slug: 'pierce', highlight: 'JBLM proximity, military family demand' },
  { name: 'Sounder Corridor', slug: 'pierce', highlight: 'Seattle commuter rail, King County safety valve' },
] as const;

export const SOUTHWEST_WA_PORTLAND_BORDER_HUB_COUNTIES = [
  { name: 'Clark', slug: 'clark', highlight: 'Vancouver Portland-border tax-haven corridor' },
] as const;

export const SOUTHWEST_WA_PORTLAND_BORDER_HUB_AREAS = [
  { name: 'Downtown Vancouver', slug: 'clark', highlight: 'Waterfront revitalization, urban infill' },
  { name: 'Fisher\'s Landing', slug: 'clark', highlight: 'Portland spillover, high transaction volume' },
  { name: 'Hazel Dell', slug: 'clark', highlight: 'Family relocations, tax-advantage appeal' },
  { name: 'Columbia River', slug: 'clark', highlight: 'Cross-river lifestyle, no income tax' },
] as const;