import{createHash}from"node:crypto";import{readFileSync,statSync}from"node:fs";import{Client}from"pg";import{countyRelationship,DERIVED_MODEL_VERSION,radiusForPowerUnits}from"../../../lib/move-v2/geography/derived-placement";import{databaseUrl,ssl}from"../db/connection";
const endpoint="https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/82";
async function main(){const c=new Client({connectionString:databaseUrl(),ssl});await c.connect();try{await c.query("begin");for(const state of["FL","WA"]){const path=`artifacts/move-v2/geography/tigerweb-2025-counties-${state}.geojson`,body=readFileSync(path),json=JSON.parse(body.toString());const sha=createHash("sha256").update(body).digest("hex");const rel=await c.query(`insert into move_v2.geography_source_release(source_name,source_url,vintage,retrieved_at,sha256,feature_count) values('US Census TIGERweb Counties',$1,'January 1 2025',$2,$3,$4) on conflict(source_url,sha256) do update set feature_count=excluded.feature_count returning geography_source_release_id`,[`${endpoint}?state=${state}`,statSync(path).mtime.toISOString(),sha,json.features.length]);for(const f of json.features)await c.query(`insert into move_v2.county_geometry(county_geoid,geography_source_release_id,state,county_name,geometry,land_area_sq_m,centroid_lat,centroid_lon) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict(county_geoid) do update set geography_source_release_id=excluded.geography_source_release_id,geometry=excluded.geometry,land_area_sq_m=excluded.land_area_sq_m,centroid_lat=excluded.centroid_lat,centroid_lon=excluded.centroid_lon`,[f.properties.GEOID,rel.rows[0].geography_source_release_id,state,f.properties.NAME,JSON.stringify(f.geometry),f.properties.AREALAND,f.properties.CENTLAT,f.properties.CENTLON]);}
 await c.query(`insert into move_v2.derived_area_model(model_version,formula,minimum_radius_miles,maximum_radius_miles,meaningful_county_overlap,input_contract,created_at) values($1,'clamp(45 + 22 * ln(max(1,power_units)),45,185)',45,185,0.15,$2,now()) on conflict(model_version) do nothing`,[DERIVED_MODEL_VERSION,JSON.stringify({inputs:['verified_hq','fmcsa_power_units','current_state_authority'],excludes:['ratings','reviews','billing','popularity'],branchPolicy:'35% of company radius capped at 50 miles when branch allocation unknown'})]);
 await c.query(`update move_v2.provider_county_placement p set active=false,superseded_at=now() from move_v2.provider_derived_area a join move_v2.provider_geography_evidence g on g.provider_id=a.provider_id where p.provider_derived_area_id=a.provider_derived_area_id and a.superseded_at is null and g.evidence_status in('SERVICE_AREA_EXPLICIT','SERVICE_AREA_PARTIAL')`);
 await c.query(`update move_v2.provider_derived_area a set superseded_at=now() from move_v2.provider_geography_evidence g where g.provider_id=a.provider_id and a.superseded_at is null and g.evidence_status in('SERVICE_AREA_EXPLICIT','SERVICE_AREA_PARTIAL')`);
 const providers=await c.query(`select e.provider_id,e.state,f.power_units,g.latitude,g.longitude,s.retrieved_at
 from move_v2.provider_local_eligibility e join move_v2.provider_geography_evidence ge using(provider_id)
 join move_v2.google_place_cache g using(provider_id) join move_v2.fmcsa_provider_fact f using(provider_id)
 join lateral(select r.retrieved_at from move_v2.provider_state_authority_match m join move_v2.state_authority_source_record sr using(state_authority_source_record_id) join move_v2.state_source_release r using(state_source_release_id) where m.provider_id=e.provider_id order by r.retrieved_at desc limit 1)s on true
 where e.superseded_at is null and e.eligibility='STATE_VERIFIED_LOCAL_MOVER' and ge.derived_service_area_required=true and e.state in('FL','WA') and g.latitude is not null and g.longitude is not null and s.retrieved_at>now()-interval '90 days'`);
 let areas=0,placements=0;for(const p of providers.rows){const radius=radiusForPowerUnits(p.power_units),snapshot={powerUnits:p.power_units,stateAuthorityRetrievedAt:p.retrieved_at,hqSource:'GOOGLE_HIGH_CONFIDENCE',state:p.state};const current=await c.query(`select provider_derived_area_id from move_v2.provider_derived_area where provider_id=$1 and model_version=$2 and input_snapshot=$3::jsonb and superseded_at is null`,[p.provider_id,DERIVED_MODEL_VERSION,JSON.stringify(snapshot)]);let areaId;if(current.rowCount)areaId=current.rows[0].provider_derived_area_id;else{await c.query(`update move_v2.provider_derived_area set superseded_at=now() where provider_id=$1 and superseded_at is null`,[p.provider_id]);const a=await c.query(`insert into move_v2.provider_derived_area(provider_id,model_version,state,center_lat,center_lon,radius_miles,input_snapshot,reason_code,created_at) values($1,$2,$3,$4,$5,$6,$7,'NO_USEFUL_EXPLICIT_SERVICE_AREA',now()) returning provider_derived_area_id`,[p.provider_id,DERIVED_MODEL_VERSION,p.state,p.latitude,p.longitude,radius,JSON.stringify(snapshot)]);areaId=a.rows[0].provider_derived_area_id;areas++}
 await c.query(`delete from move_v2.provider_county_placement where provider_derived_area_id=$1`,[areaId]);const counties=await c.query(`select county_geoid,geometry from move_v2.county_geometry where state=$1`,[p.state]);for(const county of counties.rows){const rel=countyRelationship([Number(p.longitude),Number(p.latitude)],radius,county.geometry);if(!rel.intersects)continue;await c.query(`insert into move_v2.provider_county_placement(provider_derived_area_id,provider_id,state,county_geoid,placement_type,estimated_overlap,reason_code,created_at) values($1,$2,$3,$4,$5,$6,'GEOMETRY_OVERLAP_15_PERCENT_V1',now()) on conflict(provider_derived_area_id,county_geoid) do update set placement_type=excluded.placement_type,estimated_overlap=excluded.estimated_overlap,active=true,superseded_at=null`,[areaId,p.provider_id,p.state,county.county_geoid,rel.placementType,rel.overlap]);placements++}}
 const calibration=await c.query(`select ge.provider_id,ge.explicit_observation_count,f.power_units from move_v2.provider_geography_evidence ge join move_v2.fmcsa_provider_fact f using(provider_id) join move_v2.provider_local_eligibility e using(provider_id) where e.superseded_at is null and e.state in('FL','WA') and ge.evidence_status in('SERVICE_AREA_EXPLICIT','SERVICE_AREA_PARTIAL')`);
 for(const row of calibration.rows)await c.query(`insert into move_v2.derived_area_calibration_result(provider_id,model_version,mode,explicit_area_count,metrics,evaluated_at) values($1,$2,'SHADOW',$3,$4,now()) on conflict(provider_id,model_version,mode) do update set explicit_area_count=excluded.explicit_area_count,metrics=excluded.metrics,evaluated_at=excluded.evaluated_at`,[row.provider_id,DERIVED_MODEL_VERSION,row.explicit_observation_count,JSON.stringify({powerUnits:row.power_units,hypotheticalRadiusMiles:radiusForPowerUnits(row.power_units),result:'INSUFFICIENT_STRUCTURED_EXPLICIT_GEOGRAPHY_FOR_DISTANCE_ERROR'})]);
 await c.query("commit");console.log(JSON.stringify({eligibleProviders:providers.rowCount,newAreas:areas,countyPlacements:placements,calibrationProviders:calibration.rowCount,model:DERIVED_MODEL_VERSION}));}catch(e){await c.query("rollback");throw e}finally{await c.end()}}
void main();
