import{milesBetween}from"../geography/derived-placement";import type{ConsumerProvider,DiscoveryResult,DiscoveryTier,MoveRoute,ZipResolution}from"./types";
export const SUPPORTED_LOCAL_STATES=["FL","WA"] as const;
export function routeMove(origin?:ZipResolution,destination?:ZipResolution):MoveRoute{if(!origin)return"INVALID";if(destination&&destination.state!==origin.state)return"INTERSTATE";if(!SUPPORTED_LOCAL_STATES.includes(origin.state as never))return"UNSUPPORTED_LOCAL";return destination?"LOCAL_INTRASTATE":"LOCAL_ORIGIN_RESEARCH"}
export function tierFor(input:{explicitMatch:boolean;distanceMiles:number|null;nearbyWindowMiles?:number}):DiscoveryTier{if(input.explicitMatch)return"TIER_A";if(input.distanceMiles!==null&&input.distanceMiles<=(input.nearbyWindowMiles??75))return"TIER_B";return"TIER_C"}
export function whyThisResult(provider:ConsumerProvider,tier:DiscoveryTier,distance:number|null,claim?:ConsumerProvider["explicitClaims"][number]){if(tier==="TIER_A"&&claim)return`This company has current ${provider.state==="FL"?"Florida mover registration":"Washington household-goods authority"} and its published service information includes ${claim.normalizedLabel}.`;if(distance!==null)return`This company has current ${provider.state==="FL"?"Florida mover registration":"Washington household-goods authority"} and its verified business location is approximately ${Math.round(distance)} miles from your origin. We have not independently confirmed that it serves your exact pickup address.`;return`This company has current ${provider.state==="FL"?"Florida mover registration":"Washington household-goods authority"}. Its service area and a sufficiently resolved business location have not been independently confirmed.`}
export function discoverLocal(origin:ZipResolution,providers:ConsumerProvider[],options:{initialLimit?:number;nearbyWindowMiles?:number}={}):DiscoveryResult[]{const rows=providers.filter(p=>p.state===origin.state&&p.authorityStatus.match(/^(ACTIVE|REGISTERED)/i)).map(p=>{const evidence=(p.serviceEvidence??[]).filter(e=>e.geographyType==="COUNTY"?origin.countyGeoids.includes(e.normalizedGeographyId):e.geographyType==="CENSUS_PLACE"?(origin.placeGeoids??[]).includes(e.normalizedGeographyId)||(e.matchingZctas??[]).includes(origin.zcta):e.geographyType==="ZIP"?e.zipClaim===origin.zip:false);const legacy=p.explicitClaims.filter((_,i)=>origin.countyGeoids.includes(p.explicitCountyGeoids[i]??""));const explicitMatch=(evidence.length?evidence:legacy).map(e=>({rawText:e.rawText,normalizedLabel:e.normalizedLabel,sourceUrl:e.sourceUrl,claimType:e.claimType}));const distance=p.locationStatus==="VERIFIED"&&p.latitude!==null&&p.longitude!==null?milesBetween([origin.longitude,origin.latitude],[p.longitude,p.latitude]):null;const tier=tierFor({explicitMatch:explicitMatch.length>0,distanceMiles:distance,nearbyWindowMiles:options.nearbyWindowMiles});return{...p,tier,distanceMiles:distance,explicitMatch,why:whyThisResult(p,tier,distance,explicitMatch[0]),serviceLanguage:explicitMatch.length?"Company states it serves this area":"Service area not independently confirmed"}});return rows.sort((a,b)=>tierOrder(a.tier)-tierOrder(b.tier)||(a.distanceMiles??Infinity)-(b.distanceMiles??Infinity)||a.displayName.localeCompare(b.displayName)||a.providerId.localeCompare(b.providerId)).slice(0,options.initialLimit??25)}
const tierOrder=(tier:DiscoveryTier)=>tier==="TIER_A"?1:tier==="TIER_B"?2:3;
export function compareProviders(rows:DiscoveryResult[]){return rows.slice(0,4).map(({providerId,displayName,legalName,authorityLabel,authorityStatus,distanceMiles,serviceLanguage,powerUnits,phone,website})=>({providerId,displayName,legalName,authorityLabel,authorityStatus,distanceMiles,serviceLanguage,powerUnits,phone,website}));}
export const compareHasWinner=()=>false;
