import data from"./release-v2.json";import{discoverLocal,routeMove}from"./discovery";import type{ConsumerProvider,ZipResolution}from"./types";
const release=data as unknown as{version:string;generatedAt:string;inputFingerprint:string;freshness:{geographyVintage:string;experimentalDerivedIncluded:false};providers:ConsumerProvider[];zips:ZipResolution[];interstate:Array<Record<string,unknown>&{providerId:string}>};const zipMap=new Map(release.zips.map(z=>[z.zip,z]));
export type SearchLocalMoversInput={originZip:string;destinationZip?:string};
export const discoveryFreshness=()=>({releaseVersion:release.version,generatedAt:release.generatedAt,inputFingerprint:release.inputFingerprint,geographyVintage:release.freshness.geographyVintage,experimentalDerivedIncluded:false as const});
export function resolveOriginZip(zip:string){const normalized=zip.replace(/\D/g,"").slice(0,5);return{resolution:zipMap.get(normalized)??null,freshness:discoveryFreshness()}}
export function searchLocalMovers(input:SearchLocalMoversInput){const origin=zipMap.get(input.originZip),destination=input.destinationZip?zipMap.get(input.destinationZip):undefined;const movePath=routeMove(origin,destination);if(movePath==="INTERSTATE")return{movePath,results:release.interstate.map(p=>({...p,evidenceTier:null,whyResultReasonCode:"FEDERAL_INTERSTATE_AUTHORITY",freshness:discoveryFreshness()})),freshness:discoveryFreshness()};if(!origin||movePath==="UNSUPPORTED_LOCAL"||movePath==="INVALID")return{movePath,results:[],freshness:discoveryFreshness()};const results=discoverLocal(origin,release.providers,{initialLimit:86}).map(p=>({provider_id:p.providerId,display_name:p.displayName,legal_name:p.legalName,dba_name:p.dbaName,move_path:movePath,eligibility:"STATE_VERIFIED_LOCAL_MOVER",authority:{source:p.authorityLabel,number:p.authorityNumber,status:p.authorityStatus},evidence_tier:p.tier,approximate_distance_miles:p.distanceMiles,service_evidence:p.serviceEvidence??[],phone:p.phone,website:p.website,power_units:p.powerUnits,source_count:p.sourceCount,why_result_reason_code:p.tier==="TIER_A"?"EXPLICIT_OR_REGULATORY_ORIGIN_MATCH":p.distanceMiles!==null?"STATE_VERIFIED_LOCATION_PROXIMITY":"STATE_VERIFIED_OTHER",freshness:discoveryFreshness()}));return{movePath,origin,results,freshness:discoveryFreshness()}}
export function getProviderTrustReport(providerId:string){const p=release.providers.find(x=>x.providerId===providerId);if(!p)return null;return{provider_id:p.providerId,display_name:p.displayName,legal_name:p.legalName,dba_name:p.dbaName,authority:{source:p.authorityLabel,number:p.authorityNumber,status:p.authorityStatus},location:{status:p.locationStatus,city:p.locationCity,latitude:p.latitude,longitude:p.longitude,decision:p.locationDecision},service_evidence:p.serviceEvidence??[],contacts:p.contacts??[],website:p.website,power_units:p.powerUnits,usdot:p.usdot,sources:p.sourceCount,freshness:discoveryFreshness()}}
export function compareProviderReports(providerIds:string[]){const ids=[...new Set(providerIds)].slice(0,4);return{providers:release.providers.filter(p=>ids.includes(p.providerId)).map(p=>getProviderTrustReport(p.providerId)),winner:null,contract:"FACTUAL_COMPARISON_NO_WINNER",freshness:discoveryFreshness()}}
export function getDiscoveryRelease(){return release}
