import type { CountyMoverAssignment } from '@/lib/local-movers/types';

/**
 * Delaware county → ACTIVE directory movers only.
 *
 * Source: Supabase companies with admin-active status
 * (not out_of_service, authority_active !== false) + destination assignments
 * + national carriers.
 * Generated by: npx tsx scripts/rebuild-state-from-active-db.ts delaware
 *
 * Order on every county: local → Delaware-focused → national.
 */
const CURATED_DELAWARE_COUNTIES: Record<string, string[]> = {
  kent: [
    'directory-safebound-logistics-llc',
    'directory-allied-van-lines',
    'american-van-lines',
    'directory-american-van-lines-of-sf-llc',
    'amerisafe-van-lines',
    'directory-amex-moving-and-storage-llc',
    'directory-arpin-van-lines',
    'directory-atlas-van-lines',
    'directory-cirta-moving-llc',
    'colonial-van-lines',
    'directory-gentle-giant-moving',
    'directory-graebel-van-lines',
    'directory-home-and-office-movers-llc',
    'directory-jk-moving-services',
    'directory-jr-brown-inc',
    'directory-mayflower-transit',
    'directory-national-van-lines',
    'directory-north-american-van-lines',
    'directory-ocean-moving-storage-corp',
    'directory-royal-hawaiian-movers-inc',
    'directory-stanford-van-lines-inc',
    'directory-stevens-worldwide',
    'directory-two-men-and-a-truck',
    'directory-we-move-u',
    'directory-wheaton-world-wide',
  ],
  'new-castle': [
    'directory-safebound-logistics-llc',
    'directory-allied-van-lines',
    'american-van-lines',
    'directory-american-van-lines-of-sf-llc',
    'amerisafe-van-lines',
    'directory-amex-moving-and-storage-llc',
    'directory-arpin-van-lines',
    'directory-atlas-van-lines',
    'directory-cirta-moving-llc',
    'colonial-van-lines',
    'directory-gentle-giant-moving',
    'directory-graebel-van-lines',
    'directory-home-and-office-movers-llc',
    'directory-jk-moving-services',
    'directory-jr-brown-inc',
    'directory-mayflower-transit',
    'directory-national-van-lines',
    'directory-north-american-van-lines',
    'directory-ocean-moving-storage-corp',
    'directory-royal-hawaiian-movers-inc',
    'directory-stanford-van-lines-inc',
    'directory-stevens-worldwide',
    'directory-two-men-and-a-truck',
    'directory-we-move-u',
    'directory-wheaton-world-wide',
  ],
  sussex: [
    'directory-safebound-logistics-llc',
    'directory-allied-van-lines',
    'american-van-lines',
    'directory-american-van-lines-of-sf-llc',
    'amerisafe-van-lines',
    'directory-amex-moving-and-storage-llc',
    'directory-arpin-van-lines',
    'directory-atlas-van-lines',
    'directory-cirta-moving-llc',
    'colonial-van-lines',
    'directory-gentle-giant-moving',
    'directory-graebel-van-lines',
    'directory-home-and-office-movers-llc',
    'directory-jk-moving-services',
    'directory-jr-brown-inc',
    'directory-mayflower-transit',
    'directory-national-van-lines',
    'directory-north-american-van-lines',
    'directory-ocean-moving-storage-corp',
    'directory-royal-hawaiian-movers-inc',
    'directory-stanford-van-lines-inc',
    'directory-stevens-worldwide',
    'directory-two-men-and-a-truck',
    'directory-we-move-u',
    'directory-wheaton-world-wide',
  ],
};

export const delawareCountyMoverAssignments: CountyMoverAssignment[] = Object.entries(
  CURATED_DELAWARE_COUNTIES
).map(([countySlug, moverIds]) => ({
  stateSlug: 'delaware',
  countySlug,
  moverIds,
}));
