import { createHash } from 'node:crypto';import { createReadStream,createWriteStream,mkdirSync,writeFileSync } from 'node:fs';import { resolve } from 'node:path';import { parse } from 'csv-parse';
import { classifyAutoTransport } from '../../../lib/move-v2/auto-transport/classifier';import type { AutoAuthority } from '../../../lib/move-v2/auto-transport/types';
type Row=Record<string,string>;const root=resolve('.data/fmcsa/2026-08-16');const out=resolve(root,'auto-normalized');mkdirSync(out,{recursive:true});
const usdot=(v?:string)=>(v??'').replace(/\D/g,'').replace(/^0+(?=\d)/,'');const docket=(v?:string)=>(v??'').toUpperCase().replace(/[\s-]/g,'');const num=(v?:string)=>v?.trim()&&Number.isFinite(Number(v))?Math.trunc(Number(v)):null;const yes=(v?:string)=>v==='Y'?true:v==='N'?false:null;
const key=(dataset:string,row:Row)=>`${dataset}:${createHash('sha256').update(JSON.stringify(row)).digest('hex')}`;
const providerId=(dot:string)=>{const b=createHash('sha1').update(`movetrusthub:fmcsa:usdot:${dot}`).digest().subarray(0,16);b[6]=(b[6]&15)|80;b[8]=(b[8]&63)|128;const h=b.toString('hex');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`};
const cell=(v:unknown)=>`"${(v==null?'':typeof v==='string'?v:JSON.stringify(v)).replace(/"/g,'""')}"`;const line=(v:unknown[])=>v.map(cell).join(',')+'\n';
async function read(file:string,fn:(r:Row)=>void){let n=0;for await(const raw of createReadStream(resolve(root,file)).pipe(parse({columns:true,bom:true,skip_empty_lines:true}))){n++;fn(raw as Row);}return n;}
async function main(){const maps={authority:new Map<string,Row[]>(),insurance:new Map<string,Row[]>(),history:new Map<string,Row[]>(),revoke:new Map<string,Row[]>()};for(const [m,file] of [['authority','motus-carrier.csv'],['insurance','motus-insurance.csv'],['history','motus-authhist.csv'],['revoke','motus-revoke-suspend.csv']] as const)await read(file,r=>{const d=usdot(r.usdot_number);if(!d)return;const a=maps[m].get(d)??[];a.push(r);maps[m].set(d,a)});
 const stream=createWriteStream(resolve(out,'auto-provider-roles.csv'));stream.write(line(['provider_id','usdot','display_name','legal_name','dba_name','status_code','carrier_operation','state','city','phone','email','physical_street','physical_zip','physical_country','mailing_street','mailing_city','mailing_state','mailing_zip','mailing_country','power_units','drivers','relevance','classification','rule_version','reason_codes','conflict_codes','supporting_source_keys','source_release_date']));const counts:Record<string,number>={};let rows=0,dba=0,phone=0,email=0,address=0,dockets=0;
 await read('company-census-auto.csv',r=>{rows++;const dot=usdot(r.dot_number);const auth=maps.authority.get(dot)??[];const authorities:AutoAuthority[]=auth.map(a=>({sourceRecordKey:key('inys-ebih',a),type:a.op_auth_type??'',status:a.op_auth_status??'',docket:docket(a.docket_number),bipdRequired:num(a.min_cov_amount),bipdOnFile:num(a.bipd_file),bondRequired:yes(a.bond_req),bondOnFile:yes(a.bond_file)}));const forms=(maps.insurance.get(dot)??[]).map(x=>x.ins_form_code).filter(Boolean);const activeHistory=(maps.history.get(dot)??[]).filter(x=>/property \(except household goods\)/i.test(x.op_auth_type??'')&&/active/i.test(x.op_auth_status??'')).map(x=>Date.parse(x.status_change_date||'')).filter(Number.isFinite);const revokes=(maps.revoke.get(dot)??[]).filter(x=>/property \(except household goods\)/i.test(x.op_auth_type??'')).map(x=>Date.parse(x.order1_effective_date||'')).filter(Number.isFinite);const conflict=revokes.length>0&&Math.max(...revokes)>Math.max(0,...activeHistory)&&!auth.some(x=>/property \(except household goods\)/i.test(x.op_auth_type??'')&&/active/i.test(x.op_auth_status??''));const result=classifyAutoTransport({providerId:providerId(dot),usdot:dot,legalName:r.legal_name,motorVehiclesCargoReported:r.crgo_motoveh==='X',censusStatus:r.status_code,authorities,insuranceForms:forms,currentSuspensionOrRevocation:conflict,historicalAutoEvidence:auth.length>0});const display=r.dba_name?.trim()||r.legal_name?.trim();counts[result.classification??'NONE']=(counts[result.classification??'NONE']??0)+1;if(r.dba_name)dba++;if(r.phone)phone++;if(r.email_address)email++;if(r.phy_state||r.phy_city||r.phy_street)address++;if(['1','2','3'].some(n=>r[`docket${n}`]))dockets++;stream.write(line([result.providerId,dot,display,r.legal_name,r.dba_name,r.status_code,r.carrier_operation,r.phy_state,r.phy_city,r.phone,r.email_address,r.phy_street,r.phy_zip,r.phy_country,r.carrier_mailing_street,r.carrier_mailing_city,r.carrier_mailing_state,r.carrier_mailing_zip,r.carrier_mailing_country,num(r.power_units),num(r.total_drivers),result.relevance,result.classification,result.ruleVersion,result.reasonCodes,result.conflicts,result.supportingSourceKeys,'2026-08-16']));});await new Promise<void>((ok,no)=>{stream.on('error',no);stream.end(ok)});const report={rows,counts,coverage:{dba,phone,email,address,dockets},completedAt:new Date().toISOString()};writeFileSync(resolve(out,'auto-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));}
void main();
