import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MOVE_HOMEPAGE_STATE_CARDS } from '../lib/intelligence/move-home-evidence-inventory';

const page = readFileSync('app/(move)/oregon/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/OregonMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/oregon-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const interpret = readFileSync('lib/move-ask/interpret.ts', 'utf8');

assert.match(page, /OREGON_INTELLIGENCE_GATE.path|path: '\/oregon'/);
assert.match(page, /getOregonMoveIntelligence/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /Oregon Household-Goods Mover Authority Research/);
assert.match(ui, /not a USDOT number/i);
assert.match(ui, /not an MC number/i);
assert.match(ui, /Local cartage is not other-than-local/);
assert.match(ui, /Missing bulk complaints is not zero complaints/);
assert.match(ui, /Missing adverse evidence is not a clean history/);
assert.match(ui, /fmtInt\(s.current_hhg_roster.rows\)/);
assert.doesNotMatch(ui, /best mover|safest mover|Trust Score ranking/);
assert.doesNotMatch(ui, /AggregateRating/);
assert.match(sitemap, /['"]\/oregon['"]/);
assert.ok(MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/oregon'));
assert.match(nav, /href: '\/oregon'/);
assert.equal(existsSync('app/(move)/oregon/portland'), false);
assert.equal(existsSync('app/(move)/oregon/multnomah'), false);
assert.equal(snap.current_hhg_roster.rows, 113);
assert.equal(snap.current_hhg_roster.distinctAuthorityIds, 113);
assert.equal(snap.expansion_ledger.NET_NEW_CANONICAL_ORGANIZATIONS, 0);
assert.equal(snap.expansion_ledger.NET_NEW_PUBLIC_MOVE_PROFILES, 0);
assert.equal(snap.federal.name_only, 'UNSAFE');
assert.equal(snap.complaints.OR_STATE_COMPLAINT_OBSERVATIONS, null);
assert.equal(snap.enforcement.OR_STATE_ENFORCEMENT_OBSERVATIONS, null);
assert.equal(snap.claimEligibilityBroadened, false);
assert.equal(snap.fingerprint, '88315442cd5207330e94ded88c4eb882ef4694817737479e6f26153100ec8423');
assert.match(claim, /usdotNumber/);
assert.doesNotMatch(claim, /odot-hhg|or-odot-hhg|certificateNumber/i);
assert.match(interpret, /licensed in oregon|odot ccd|oregon household-goods certificate/i);
console.log('OR-MOVE-001 publication assert: PASS');
