import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MOVE_HOMEPAGE_STATE_CARDS } from '../lib/intelligence/move-home-evidence-inventory';

const page = readFileSync('app/(move)/virginia/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/VirginiaMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/virginia-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const interpret = readFileSync('lib/move-ask/interpret.ts', 'utf8');

assert.match(page, /VIRGINIA_INTELLIGENCE_GATE.path|path: '\/virginia'/);
assert.match(page, /getVirginiaMoveIntelligence/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /Virginia Household-Goods Moving Intelligence/);
assert.match(ui, /further than 30 miles/);
assert.match(ui, /less than 31 road-miles/);
assert.match(ui, /Household Goods Carrier certificate is not a Property Carrier permit/);
assert.match(ui, /All Property Carrier authority listings/);
assert.match(ui, /USDOT number alone is not proof/);
assert.doesNotMatch(ui, /best mover|safest mover|Trust Score ranking|Virginia movers need a household-goods license/);
assert.match(sitemap, /['"]\/virginia['"]/);
assert.ok(MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/virginia'));
assert.match(nav, /href: '\/virginia'/);
assert.equal(existsSync('app/(move)/virginia/richmond'), false);
assert.equal(existsSync('app/(move)/virginia/[county]'), false);
assert.equal(snap.hhg_roster.rows, 192);
assert.equal(snap.property_roster.rows, 4916);
assert.equal(snap.hhg_roster.legal_authority_document, 'Certificate');
assert.equal(snap.identity.hhg_namespace, 'VA-DMV-HHG:{authorityNumber}');
assert.equal(snap.federal.name_only, 'UNSAFE');
assert.equal(snap.applications.applicant_ne_authorized_carrier, true);
assert.equal(snap.insurance_bond.roster_presence_ne_insured_true, true);
assert.equal(snap.gate.passed, true);
assert.doesNotMatch(ui, /AggregateRating/);
assert.match(claim, /usdotNumber/);
assert.doesNotMatch(claim, /va-dmv-hhg|VA-DMV-HHG/);
assert.match(interpret, /virginia: 'VA'/);
assert.match(interpret, /distance-sensitive/);
console.log('VA-MOVE-001 publication assert: PASS');
