import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MOVE_HOMEPAGE_STATE_CARDS } from '../lib/intelligence/move-home-evidence-inventory';

const page = readFileSync('app/(move)/new-york/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/NewYorkMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/new-york-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const interpret = readFileSync('lib/move-ask/interpret.ts', 'utf8');

assert.match(page, /NEW_YORK_INTELLIGENCE_GATE.path|path: '\/new-york'/);
assert.match(page, /getNewYorkMoveIntelligence/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /New York Household-Goods Moving Intelligence/);
assert.match(ui, /Application is not authorization|application is not current operating authority/i);
assert.match(ui, /Search only/);
assert.match(ui, /108|hhgApplicationObservations/);
assert.match(ui, /USDOT number alone does not prove/);
assert.doesNotMatch(ui, /best mover|safest mover|Trust Score ranking/);
assert.match(sitemap, /['"]\/new-york['"]/);
assert.ok(MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/new-york'));
assert.match(nav, /href: '\/new-york'/);
assert.equal(existsSync('app/(move)/new-york/manhattan'), false);
assert.equal(existsSync('app/(move)/new-york/brooklyn'), false);
assert.equal(snap.bulletin_2026.issues, 36);
assert.equal(snap.bulletin_2026.hhgApplicationObservations, 108);
assert.equal(snap.current_hhg_roster.rows, null);
assert.equal(snap.expansion_ledger.NET_NEW_CANONICAL_ORGANIZATIONS, 0);
assert.equal(snap.expansion_ledger.NET_NEW_PUBLIC_MOVE_PROFILES, 0);
assert.equal(snap.expansion_ledger.EXACT_NY_STATE_TO_FEDERAL_CROSSWALKS, 0);
assert.equal(snap.federal.name_only, 'UNSAFE');
assert.equal(snap.fingerprint, '41ea8c6ce56b578e21efad51046248012cc7482f23ed2af8865fad753fefa4f6');
assert.doesNotMatch(ui, /AggregateRating/);
assert.match(claim, /usdotNumber/);
assert.match(interpret, /licensed movers in New York|nydot|new york/i);
console.log('NY-MOVE-001 publication assert: PASS');
