import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MOVE_HOMEPAGE_STATE_CARDS } from '../lib/intelligence/move-home-evidence-inventory';

const page = readFileSync('app/(move)/virginia/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/VirginiaMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/virginia-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const interpret = readFileSync('lib/move-ask/interpret.ts', 'utf8');

assert.match(page, /VIRGINIA_INTELLIGENCE_GATE.path|path: '\/virginia'/);
assert.match(page, /getVirginiaMoveIntelligence/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /Virginia Household-Goods Moving Intelligence/);
assert.match(ui, /further than 30 miles/);
assert.match(ui, /less than 31 road-miles/);
assert.match(ui, /Household Goods Carrier certificate is not a Property Carrier permit/);
assert.match(ui, /All Property Carrier authority listings/);
assert.match(ui, /listing-row grain/);
assert.match(ui, /identity grain/);
assert.match(ui, /source-identifier conflict/);
assert.match(ui, /does not uniquely resolve a carrier/);
assert.match(ui, /USDOT number alone is not proof/);
assert.doesNotMatch(ui, /best mover|safest mover|Trust Score ranking|Virginia movers need a household-goods license/);
assert.match(sitemap, /['"]\/virginia['"]/);
assert.ok(MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/virginia'));
assert.match(nav, /href: '\/virginia'/);
assert.equal(existsSync('app/(move)/virginia/richmond'), false);
assert.equal(existsSync('app/(move)/virginia/[county]'), false);
assert.equal(snap.hhg_roster.rows, 192);
assert.equal(snap.hhg_roster.distinct_non_null_authority_numbers, 192);
assert.equal(snap.hhg_roster.distinct_labels, 192);
assert.equal(snap.property_roster.rows, 4916);
assert.equal(snap.property_roster.non_null_authority_rows, 4915);
assert.equal(snap.property_roster.distinct_non_null_authority_numbers, 4914);
assert.equal(snap.property_roster.null_identifiers, 1);
assert.equal(snap.expansion_ledger.NEW_VA_HHG_AUTHORITY_IDENTITIES, 192);
assert.equal(snap.expansion_ledger.NEW_VA_PROPERTY_AUTHORITY_IDENTITIES, 4914);
assert.equal(snap.expansion_ledger.NEW_VA_STATE_IDENTITIES, 5106);
assert.equal(snap.expansion_ledger.NEW_STATE_CREDENTIAL_ROWS, 5108);
assert.equal(snap.expansion_ledger.identity_grain, 'distinct_non_null_authority_number');
assert.equal(snap.expansion_ledger.credential_row_grain, 'authorized_listing_row');
assert.notEqual(snap.expansion_ledger.identity_grain, snap.expansion_ledger.credential_row_grain);
assert.equal(snap.expansion_ledger.credential_rows_are_not_authority_identities, true);
assert.equal(snap.identity.property_1276_status, 'SOURCE_IDENTIFIER_CONFLICT');
assert.equal(snap.expansion_ledger.NET_NEW_CANONICAL_ORGANIZATIONS, 0);
assert.equal(snap.expansion_ledger.NET_NEW_PUBLIC_MOVE_PROFILES, 0);
assert.equal(snap.expansion_ledger.EXISTING_ORGANIZATIONS_ENRICHED, 0);
assert.equal(snap.expansion_ledger.EXACT_STATE_TO_FEDERAL_CROSSWALKS, 0);
assert.equal(snap.expansion_ledger.EXACT_PROFILE_ATTACHMENTS, 0);
assert.equal(snap.hhg_roster.legal_authority_document, 'Certificate');
assert.equal(snap.identity.hhg_namespace, 'VA-DMV-HHG:{authorityNumber}');
assert.equal(snap.federal.name_only, 'UNSAFE');
assert.equal(snap.applications.applicant_ne_authorized_carrier, true);
assert.equal(snap.insurance_bond.roster_presence_ne_insured_true, true);
assert.equal(snap.gate.passed, true);
assert.doesNotMatch(ui, /AggregateRating/);
assert.match(claim, /usdotNumber/);
assert.doesNotMatch(claim, /va-dmv-hhg|VA-DMV-HHG|VA-DMV-PROP|va-dmv-prop/);
assert.match(interpret, /virginia: 'VA'/);
assert.match(interpret, /distance-sensitive/);
console.log('VA-MOVE-001 publication assert: PASS');
