import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

const page = readFileSync('app/(move)/washington/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/WashingtonMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const home = readFileSync('components/home-page.tsx', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/washington-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const probe = JSON.parse(readFileSync('data/washington/wa-move-001/utc-bounded-probe.json', 'utf8'));

assert.match(page, /WASHINGTON_INTELLIGENCE_GATE.path|path: '\/washington'/);
assert.match(page, /buildMovePageMetadata/);
assert.match(page, /getWashingtonMoveIntelligenceSnapshot/);
assert.doesNotMatch(page, /robots:\s*\{\s*index:\s*false/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /Washington Moving &amp; Household-Goods Intelligence/);
assert.match(ui, /FMCSA interstate records with a Washington business\/HQ location/);
assert.match(ui, /Not acquired/);
assert.match(ui, /284/);
assert.doesNotMatch(ui, /best movers|safest movers|top mover|Trust Score ranking/);
assert.match(ui, /does not authorize interstate/);
assert.match(sitemap, /['"]\/washington['"]/);
assert.match(home, /href="\/washington"/);
assert.match(nav, /href: '\/washington'/);
assert.equal(existsSync('app/(move)/washington/[county]'), false);
assert.equal(existsSync('app/(move)/washington/seattle'), false);
assert.equal(existsSync('app/(move)/washington/king'), false);
assert.equal(existsSync('app/(move)/washington/tacoma'), false);
assert.equal(existsSync('app/(move)/washington/pierce'), false);
assert.equal(existsSync('app/(move)/washington/spokane'), false);
assert.equal(existsSync('app/(move)/washington/snohomish'), false);
assert.equal(existsSync('app/(move)/washington/bellevue'), false);
assert.equal(snap.directory.active_result_count, 284);
assert.equal(snap.bulk.utc_hhg_bulk_roster, 'SOURCE_NOT_ACQUIRED');
assert.equal(snap.crosswalk.coverage, 'PARTIAL_RECORD_LEVEL');
assert.equal(snap.directory.not_scraped, true);
assert.equal(snap.authority.utc_state_authority_is_not_fmcsa, true);
assert.equal(snap.gate.passed, true);
assert.equal(probe.no_pagination_crawl, true);
assert.equal(probe.no_id_bruteforce, true);
assert.equal(probe.directory.has_csv_export, false);
assert.match(ui, /Missing is not zero/);
assert.match(ui, /complaint is not a violation/i);
assert.match(ui, /Tariff 15-C/);
assert.doesNotMatch(ui, /fetch-utc-registry|utc-hhg-active-raw/);
assert.doesNotMatch(page, /fetch-utc-registry/);
assert.match(claim, /usdotNumber/);
assert.doesNotMatch(claim, /utcId|wa-utc/i);
assert.match(readFileSync('app/(move)/texas/page.tsx', 'utf8'), /texas/);
assert.match(readFileSync('app/(move)/california/page.tsx', 'utf8'), /california/);
assert.match(readFileSync('app/(move)/new-jersey/page.tsx', 'utf8'), /new-jersey/);
assert.match(readFileSync('app/(move)/florida/page.tsx', 'utf8'), /florida/);
console.log('WA-MOVE-001 publication assertions: PASS');
