import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MOVE_HOMEPAGE_STATE_CARDS } from '../lib/intelligence/move-home-evidence-inventory';

const page = readFileSync('app/(move)/ohio/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/OhioMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/ohio-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const interpret = readFileSync('lib/move-ask/interpret.ts', 'utf8');

assert.match(page, /OHIO_INTELLIGENCE_GATE.path|path: '\/ohio'/);
assert.match(page, /getOhioMoveIntelligence/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /Ohio Moving/);
assert.match(ui, /not a USDOT number and not an MC number/i);
assert.match(ui, /does not have North Carolina/i);
assert.match(ui, /OPEN_SEARCH_ONLY|Search only/i);
assert.match(ui, /tariff is not a quote/i);
assert.doesNotMatch(ui, /best mover|safest mover|Trust Score ranking/);
assert.doesNotMatch(ui, /AggregateRating/);
assert.doesNotMatch(ui, /Utility Code|Carrier ID \/ A-number|NCUC C-number|ODOT|ILCC|NYSDOT|HICPA/);
assert.match(sitemap, /['"]\/ohio['"]/);
assert.doesNotMatch(sitemap, /\/ohio\/columbus/);
assert.doesNotMatch(sitemap, /\/ohio\/cleveland/);
assert.ok(MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/ohio'));
assert.match(nav, /href: '\/ohio'/);
assert.equal(existsSync('app/(move)/ohio/columbus'), false);
assert.equal(existsSync('app/(move)/ohio/cleveland'), false);
assert.equal(existsSync('app/(move)/ohio/cincinnati'), false);
assert.equal(existsSync('app/(move)/ohio/toledo'), false);
assert.equal(existsSync('app/(move)/ohio/dayton'), false);
assert.equal(existsSync('app/(move)/ohio/akron'), false);
assert.equal(snap.current_hhg_roster.OH_PUCO_HHG_ROSTER_STATUS, 'OPEN_SEARCH_ONLY');
assert.equal(snap.current_hhg_roster.OH_PUCO_HHG_ROWS, null);
assert.equal(snap.current_hhg_roster.OH_PUCO_DISTINCT_CERTIFICATE_NUMBERS, null);
assert.equal(snap.tariff.not_nc_statewide_maximum_rate_tariff, true);
assert.equal(snap.expansion_ledger.NET_NEW_CANONICAL_ORGANIZATIONS, 0);
assert.equal(snap.expansion_ledger.NET_NEW_PUBLIC_MOVE_PROFILES, 0);
assert.equal(snap.expansion_ledger.GRAPH_WRITES, 0);
assert.equal(snap.federal.name_only, 'UNSAFE');
assert.equal(snap.complaints.OH_PUCO_HHG_COMPLAINT_ROWS, null);
assert.equal(snap.enforcement.OH_PUCO_HHG_ENFORCEMENT_ROWS, null);
assert.equal(snap.claimEligibilityBroadened, false);
assert.equal(snap.fingerprint, '24cfc71aacbec3837b7c06c5b291d8cde1548673712e91888c8378b99f7d7a44');
assert.match(claim, /usdotNumber/);
assert.doesNotMatch(claim, /puco|oh-puco-hhg/i);
assert.match(interpret, /ohio|puco/i);
console.log('OH-MOVE-001 publication assert: PASS');
