import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MOVE_HOMEPAGE_STATE_CARDS } from '../lib/intelligence/move-home-evidence-inventory';

const page = readFileSync('app/(move)/north-carolina/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/NorthCarolinaMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/north-carolina-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const interpret = readFileSync('lib/move-ask/interpret.ts', 'utf8');

assert.match(page, /NORTH_CAROLINA_INTELLIGENCE_GATE.path|path: '\/north-carolina'/);
assert.match(page, /getNorthCarolinaMoveIntelligence/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /North Carolina Moving/);
assert.match(ui, /not FMCSA interstate authority/i);
assert.match(ui, /C-number is not a T-number/);
assert.match(ui, /Maximum Rate Tariff is not a quote/);
assert.match(ui, /Insurance requirement is not current coverage/);
assert.match(ui, /OPEN_SEARCH_ONLY|Unknown|not acquired/i);
assert.doesNotMatch(ui, /best mover|safest mover|Trust Score ranking/);
assert.doesNotMatch(ui, /AggregateRating/);
assert.doesNotMatch(ui, /Utility Code|Carrier ID \/ A-number|PA PUC|ODOT|ILCC|NYSDOT|HICPA/);
assert.match(sitemap, /['"]\/north-carolina['"]/);
assert.doesNotMatch(sitemap, /\/north-carolina\/charlotte/);
assert.doesNotMatch(sitemap, /\/north-carolina\/raleigh/);
assert.ok(MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/north-carolina'));
assert.match(nav, /href: '\/north-carolina'/);
assert.equal(existsSync('app/(move)/north-carolina/charlotte'), false);
assert.equal(existsSync('app/(move)/north-carolina/raleigh'), false);
assert.equal(snap.current_hhg_roster.NC_NCUC_DISTINCT_C_NUMBERS, 362);
assert.equal(snap.current_hhg_roster.NC_NCUC_HHG_SOURCE_ANNOUNCED_TOTAL, 361);
assert.equal(snap.expansion_ledger.NET_NEW_CANONICAL_ORGANIZATIONS, 0);
assert.equal(snap.expansion_ledger.NET_NEW_PUBLIC_MOVE_PROFILES, 0);
assert.equal(snap.federal.name_only, 'UNSAFE');
assert.equal(snap.complaints.NC_NCUC_HHG_COMPLAINT_ROWS, null);
assert.equal(snap.enforcement.NC_NCUC_HHG_ENFORCEMENT_ROWS, null);
assert.equal(snap.claimEligibilityBroadened, false);
assert.equal(snap.fingerprint, '9b4becfd1d99f78abdbe79daabb0ba61571e6b6fc3e13f8fb1dc439661e46bec');
assert.match(claim, /usdotNumber/);
assert.doesNotMatch(claim, /nc-ncuc|cNumber/i);
assert.match(interpret, /north carolina|ncuc|c-number/i);
console.log('NC-MOVE-001 publication assert: PASS');
