import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MOVE_HOMEPAGE_STATE_CARDS } from '../lib/intelligence/move-home-evidence-inventory';

const page = readFileSync('app/(move)/colorado/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/ColoradoMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/colorado-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const interpret = readFileSync('lib/move-ask/interpret.ts', 'utf8');
const definitions = readFileSync('lib/move-ask/contract.ts', 'utf8');

assert.match(page, /COLORADO_INTELLIGENCE_GATE.path|path: '\/colorado'/);
assert.match(page, /buildMovePageMetadata/);
assert.match(page, /getColoradoMoveIntelligence/);
assert.doesNotMatch(page, /robots:\s*\{\s*index:\s*false/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /Colorado Moving &amp; Household-Goods Intelligence/);
assert.match(ui, /Active Colorado PUC household-goods permit listings/);
assert.match(ui, /FMCSA interstate records with a Colorado business\/HQ location/);
assert.match(ui, /203/);
assert.doesNotMatch(ui, /best movers|safest movers|top mover|Trust Score ranking/);
assert.doesNotMatch(ui, /no state universe|Arizona-style/);
assert.match(ui, /Colorado ACTIVE is not quality and is not FMCSA ACTIVE/);
assert.match(sitemap, /['"]\/colorado['"]/);
assert.ok(MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/colorado'));
assert.ok(!MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/arizona'));
assert.match(nav, /href: '\/colorado'/);
assert.equal(existsSync('app/(move)/colorado/denver'), false);
assert.equal(existsSync('app/(move)/colorado/[county]'), false);
assert.equal(existsSync('app/(move)/arizona'), false);
assert.equal(snap.active_universe.official_total_permits, 203);
assert.equal(snap.identity.namespace, 'CO-PUC-HHG:{permitNumber}');
assert.equal(snap.authority.hhg_permit_is_not_usdot, true);
assert.equal(snap.authority.colorado_active_is_not_fmcsa_active, true);
assert.equal(snap.federal.federal_profile_ne_state_permit, true);
assert.equal(snap.status_classes.inactive_ne_revoked, true);
assert.equal(snap.status_classes.revoked_ne_criminal_conviction, true);
assert.equal(snap.complaints.missing_ne_zero, true);
assert.equal(snap.crosswalk.name_only, 'UNSAFE');
assert.equal(snap.enforcement.name_only, 'UNSAFE');
assert.equal(snap.gate.passed, true);
assert.match(ui, /Missing is not zero/);
assert.match(ui, /complaint is not a violation/i);
assert.doesNotMatch(ui, /AggregateRating/);
assert.match(claim, /usdotNumber/);
assert.doesNotMatch(claim, /co-puc-hhg|hhgPermit/i);
assert.match(interpret, /colorado: 'CO'/);
assert.match(definitions, /carrier_vs_broker/);
assert.match(readFileSync('app/(move)/texas/page.tsx', 'utf8'), /texas/);
assert.match(readFileSync('app/(move)/california/page.tsx', 'utf8'), /california/);
assert.match(readFileSync('app/(move)/new-jersey/page.tsx', 'utf8'), /new-jersey/);
assert.match(readFileSync('app/(move)/florida/page.tsx', 'utf8'), /florida/);
assert.match(readFileSync('app/(move)/washington/page.tsx', 'utf8'), /washington/);
console.log('CO-MOVE-001 publication assertions: PASS');
