import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MOVE_HOMEPAGE_STATE_CARDS } from '../lib/intelligence/move-home-evidence-inventory';

const page = readFileSync('app/(move)/pennsylvania/page.tsx', 'utf8');
const ui = readFileSync('components/intelligence/PennsylvaniaMoveIntelligence.tsx', 'utf8');
const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const nav = readFileSync('lib/nav/move-nav-config.ts', 'utf8');
const snap = JSON.parse(readFileSync('lib/pennsylvania-intelligence/accepted-snapshot.json', 'utf8'));
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const interpret = readFileSync('lib/move-ask/interpret.ts', 'utf8');

assert.match(page, /PENNSYLVANIA_INTELLIGENCE_GATE.path|path: '\/pennsylvania'/);
assert.match(page, /getPennsylvaniaMoveIntelligence/);
assert.equal((ui.match(/<h1\b/g) ?? []).length, 1);
assert.match(ui, /Pennsylvania Moving/);
assert.match(ui, /not FMCSA interstate authority/i);
assert.match(ui, /Utility Code is not automatically Carrier ID/);
assert.match(ui, /Carriers are not brokers/);
assert.match(ui, /docketed\s+case is not an adverse finding/i);
assert.match(ui, /OPEN_SEARCH_ONLY|Unknown/);
assert.doesNotMatch(ui, /best mover|safest mover|Trust Score ranking/);
assert.doesNotMatch(ui, /AggregateRating/);
assert.doesNotMatch(ui, /ODOT|ILCC|NYSDOT|FDACS/);
assert.match(sitemap, /['"]\/pennsylvania['"]/);
assert.doesNotMatch(sitemap, /\/pennsylvania\/philadelphia/);
assert.doesNotMatch(sitemap, /\/pennsylvania\/pittsburgh/);
assert.ok(MOVE_HOMEPAGE_STATE_CARDS.some((state) => state.href === '/pennsylvania'));
assert.match(nav, /href: '\/pennsylvania'/);
assert.equal(existsSync('app/(move)/pennsylvania/philadelphia'), false);
assert.equal(existsSync('app/(move)/pennsylvania/pittsburgh'), false);
assert.equal(snap.current_hhg_roster.PA_PUC_HHG_CARRIER_ROWS, 269);
assert.equal(snap.current_hhg_roster.PA_PUC_HHG_DISTINCT_UTILITY_CODES, 267);
assert.equal(snap.expansion_ledger.NET_NEW_CANONICAL_ORGANIZATIONS, 0);
assert.equal(snap.expansion_ledger.NET_NEW_PUBLIC_MOVE_PROFILES, 0);
assert.equal(snap.federal.name_only, 'UNSAFE');
assert.equal(snap.complaints.PA_PUC_FORMAL_COMPLAINT_ROWS, null);
assert.equal(snap.enforcement.PA_PUC_ENFORCEMENT_ROWS, null);
assert.equal(snap.claimEligibilityBroadened, false);
assert.equal(snap.fingerprint, '1f8b97db78233d0a89fcab02bb92c8ff51633ba69da993ecc6eea79c985d88b3');
assert.match(claim, /usdotNumber/);
assert.doesNotMatch(claim, /pa-puc-hhg|utilityCode/i);
assert.match(interpret, /pennsylvania|pa puc|utility code/i);
console.log('PA-MOVE-001 publication assert: PASS');
