import { type PackDef, z, s, b } from './az-tier2-render';

/** AZ Tier 2 Wave 1 packs 7–11: Navajo, Santa Cruz, Gila, Graham, Apache */
export const packsB: PackDef[] = [
  {
    file: 'navajo-az.ts',
    exportName: 'navajoCountyAzTier2Intelligence',
    slug: 'navajo',
    hubTitle: 'Navajo County Moving Intelligence Hub',
    eyebrow: 'Navajo · Show Low / Winslow / Holbrook — NE AZ high country',
    h1: 'Moving in Navajo County: Show Low, Winslow & High-Country I-40 Access',
    heroOpener:
      'Navajo County is northeast Arizona high-country and I-40 product — Show Low multi-family and recreation stock, Winslow multi-story and seat corridors, Holbrook edges, and freeflow that still means long empty miles between discontinuous towns. Expect elevation weather, tourism peaks, and rural logistics under one county. This guide is for people moving in Navajo as independent NE AZ — not Phoenix or Tucson defaults.',
    heroCredibility:
      'NE AZ high country · Show Low / I-40 towns · Long empty miles · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-40 · AZ-77 · AZ-260 · AZ-87 · US-180 edges',
    parentLabel: 'independent NE Arizona (vs Maricopa / Coconino defaults)',
    parentHref: '/local-movers/arizona/coconino',
    compareIntro:
      'Navajo is independent NE AZ high-country multi-town product — not Flagstaff university density and not Phoenix desert Loop product.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Coconino crews fight Flagstaff arterials and NAU peaks. Navajo pairs ride I-40, AZ-77, and AZ-260 across discontinuous towns — freer mid-day between seats, still peak-heavy on Show Low tourism weekends and Winslow arterials.'),
      b('Housing stock differences', 'Coconino mixes Flagstaff multi-story and NAU multi-family. Navajo mixes Show Low multi-unit, Winslow multi-story, and Holbrook SFH — more multi-town rural product, less continuous university density.'),
      b('Truck access & density', 'Elevation weather rewrites staging; long empty miles dominate town pairs; soft shoulders appear on rural edges.'),
      b('Rough cost posture (qualitative)', 'Local Navajo quotes often sit at NE secondary rates for driveway SFH — tourism peaks and long empty-mile pairs still push prices up.'),
      b('Role difference', 'Navajo is independent NE AZ multi-town high country — not Flagstaff or Phoenix product renamed.'),
    ],
    whatIntro: 'Long empty miles, high-country weather, and I-40 freeflow — not interchangeable Flagstaff or Valley boilerplate.',
    whatBullets: [
      b('Town-to-town empty miles are first-class cost drivers', 'Show Low ↔ Winslow pairs fail when crews assume continuous metro density.'),
      b('Elevation weather rewrites winter and monsoon staging', 'Ice, snow, and storms reshape morning curb plans.'),
      b('I-40 freeflow is still billable', 'NE pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Tourism and recreation peaks rewrite weekends', 'Show Low area volume stacks around seasonal windows.'),
    ],
    zonesHeading: 'Navajo zones: Show Low multi-family, Winslow multi-story, Holbrook edges & rural lots',
    zonesIntro: 'Two to four sharp products — recreation multi-family, seat multi-story, corridor edges, and rural lots.',
    zones: [
      z('show-low', 'Show Low multi-family & recreation stock', 'Show Low', ['Show Low', 'Pinetop-Lakeside edges', 'recreation multi-family'], 'Multi-family, SFH, tourism stock', ['Tourism peaks', 'Elevation weather', 'HOA packets'], ['show low', 'pinetop'], 'Book around tourism peaks; survey driveway grades.'),
      z('winslow', 'Winslow multi-story & I-40 seat corridors', 'Winslow', ['Winslow', 'downtown edges', 'I-40 multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-40 freeflow'], ['winslow'], 'Inventory stairs; plan temporary no-parking.'),
      z('holbrook', 'Holbrook / AZ-77 corridor edges', 'Holbrook', ['Holbrook', 'corridor multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['holbrook'], 'Prefer early starts for long pairs.'),
      z('rural-lots', 'Southern & rural high-country lots', 'Rural lots', ['Heber-Overgaard edges', 'rural tracts'], 'Larger lots, rural approaches', ['Long empty miles', 'Soft shoulders', 'Winter ice'], ['heber', 'rural navajo'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('long-empty', 'NE multi-town empty-mile module', 'Discontinuous towns dominate pricing.', ['Price portal-to-portal between seats honestly.', 'Do not recycle Flagstaff day rates alone.']),
      s('high-country-weather', 'High-country weather module', 'Elevation rewrites desert staging assumptions.', ['Build winter morning flexibility into plans.', 'Monsoon and snow windows both matter.']),
      s('i40-ne', 'I-40 NE freeflow', 'NE pairs still peak hard on arterials.', ['Build corridor buffers for freight and tourism peaks.', 'Clarify Coconino second addresses for drive-time assumptions.']),
    ],
    schoolsIntro: 'Navajo families compare Show Low, Winslow, Holbrook, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Summit Healthcare (Show Low) and regional specialty spillover serve the county; map peak freeflow across discontinuous towns.',
    costIntro: 'Town-to-town empty miles, multi-story access, tourism peaks, and elevation weather often matter more than raw miles.',
    seasonalIntro: 'Tourism summers, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'santa-cruz-az.ts',
    exportName: 'santaCruzCountyAzTier2Intelligence',
    slug: 'santa-cruz',
    hubTitle: 'Santa Cruz County Moving Intelligence Hub',
    eyebrow: 'Santa Cruz · Nogales — border county',
    h1: 'Moving in Santa Cruz County: Nogales, Rio Rico & Border Logistics Access',
    heroOpener:
      'Santa Cruz County is southern Arizona border product — Nogales multi-story and multi-family stock, Rio Rico growth edges, Patagonia and rural approaches, and freeflow on I-19 that is not Tucson basin density with different labels. Expect border logistics, commercial-adjacent residential, and long empty miles under one small county. This guide is for people moving in Santa Cruz as border secondary — not a Tucson rename.',
    heroCredibility:
      'Border county · Nogales multi-story · I-19 freeflow · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-19 · AZ-82 · AZ-83 · Grand Avenue corridor',
    parentLabel: 'Pima County',
    parentHref: '/local-movers/arizona/pima',
    compareIntro:
      'Santa Cruz is border logistics product on I-19 — not Pima Tucson metro density and not pure rural desert freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Pima crews fight Tucson arterials and I-10 peaks. Santa Cruz pairs ride I-19 and AZ-82 — freer mid-day south of the basin, still peak-heavy on Nogales arterials and border commercial windows.'),
      b('Housing stock differences', 'Pima mixes Tucson multi-story and foothill HOAs. Santa Cruz mixes Nogales multi-unit, Rio Rico SFH, and rural edges — more border-town product, less continuous Tucson metro density.'),
      b('Truck access & density', 'Border-adjacent streets need curb plans; multi-family elevators appear on growth edges; rural lots add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Santa Cruz quotes often sit at border secondary rates for multi-story access — commercial freeflow and empty miles still push prices up.'),
      b('Role difference', 'Santa Cruz is border county secondary — not Tucson product renamed.'),
    ],
    whatIntro: 'Border freeflow, Nogales multi-story, and I-19 empty miles — not interchangeable Tucson boilerplate.',
    whatBullets: [
      b('I-19 freeflow is still billable', 'Santa Cruz ↔ Pima pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Nogales multi-story is first-class product', 'Stairs and curb plans need inventories different from pure Rio Rico cul-de-sacs.'),
      b('Border commercial windows reshape staging', 'Freight and port traffic rewrite pure residential Saturday assumptions.'),
      b('Empty miles from Tucson yards are real', 'Even “local” Santa Cruz pairs can price as distance work for Tucson-based crews.'),
    ],
    zonesHeading: 'Santa Cruz zones: Nogales multi-story, Rio Rico growth, Patagonia edges & rural lots',
    zonesIntro: 'Two to four sharp products — border multi-story, growth SFH, mountain edges, and rural lots.',
    zones: [
      z('nogales', 'Nogales multi-story & multi-unit', 'Nogales', ['Nogales', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Border freeflow'], ['nogales'], 'Inventory stairs; plan temporary no-parking.'),
      z('rio-rico', 'Rio Rico growth SFH & multi-family', 'Rio Rico', ['Rio Rico', 'growth villages'], 'HOA SFH, multi-family, townhomes', ['HOA packets', 'I-19 freeflow'], ['rio rico'], 'Collect HOA COIs; build I-19 buffer for Pima pairs.'),
      z('patagonia', 'Patagonia / mountain-edge approaches', 'Patagonia', ['Patagonia', 'AZ-82 edges'], 'SFH, multi-family, mixed stock', ['Narrow approaches', 'Empty miles'], ['patagonia'], 'Photo last-mile; prefer early starts.'),
      z('rural-lots', 'Rural Santa Cruz lots', 'Rural lots', ['rural tracts', 'eastern edges'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['rural santa cruz'], 'Survey approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('border-logistics', 'Border logistics module', 'Commercial freeflow reshapes residential staging.', ['Build buffers for port and freight peaks.', 'Do not recycle pure Tucson Saturday rates.']),
      s('i19-freeflow', 'I-19 freeflow to Pima', 'South pairs still peak hard toward Tucson.', ['Price portal-to-portal honestly.', 'Clarify Pima second addresses early.']),
      s('nogales-seat', 'Nogales multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Santa Cruz families compare Nogales Unified, Santa Cruz Valley, and related district feeders — verify address boundaries; do not assume Tucson maps apply.',
    hospitalsDetail: 'Holy Cross Hospital and Tucson specialty spillover serve the county; map peak I-19 times for ER access.',
    costIntro: 'Border freeflow, multi-story access, and empty miles from Tucson yards often matter more than raw miles.',
    seasonalIntro: 'School years, monsoon weather, and extreme heat reshape demand by pocket.',
  },
  {
    file: 'gila-az.ts',
    exportName: 'gilaCountyAzTier2Intelligence',
    slug: 'gila',
    hubTitle: 'Gila County Moving Intelligence Hub',
    eyebrow: 'Gila · Payson / Globe — rim country',
    h1: 'Moving in Gila County: Payson, Globe & Rim-Country Access',
    heroOpener:
      'Gila County is Arizona rim-country product — Payson multi-family and recreation stock, Globe multi-story and mining-town fabric, Miami and rural edges, and freeflow on AZ-87 / US-60 that is not Phoenix desert HOA sprawl with elevation labels. Expect grades, tourism peaks, and long empty miles under one county. This guide is for people moving in Gila as independent rim country — not a Maricopa rename.',
    heroCredibility:
      'Rim country independent · Payson / Globe · Elevation recreation · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'AZ-87 · US-60 · AZ-188 · AZ-260 · AZ-77',
    parentLabel: 'independent rim country (nearest desert hub: Maricopa)',
    parentHref: '/local-movers/arizona/maricopa',
    compareIntro:
      'Gila is independent rim-country recreation and mining-town product — not Maricopa desert Loop density and not pure rural forest freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Maricopa crews fight Loop peaks in extreme heat. Gila pairs ride AZ-87, US-60, and AZ-188 — freer mid-day rim freeflow, still peak-heavy on Payson tourism weekends and Globe arterials.'),
      b('Housing stock differences', 'Maricopa mixes towers and master plans. Gila mixes Payson multi-family, Globe multi-story, and rural lots — more elevation and mining-town product, less continuous desert HOA density.'),
      b('Truck access & density', 'Grades rewrite truck size; tourism multi-family needs packets; mining-town streets need curb plans.'),
      b('Rough cost posture (qualitative)', 'Local Gila quotes often track rim secondary rates for multi-story access — grades and tourism peaks can price above quiet off-season lots.'),
      b('Role difference', 'Gila is independent rim country — not Phoenix product renamed.'),
    ],
    whatIntro: 'Rim elevation, Payson recreation peaks, and Globe multi-story — not interchangeable Valley boilerplate.',
    whatBullets: [
      b('Rim grades rewrite truck size assumptions', 'Approaches reject full-trailer Valley day rates more often than map miles suggest.'),
      b('Payson tourism peaks rewrite weekends', 'Recreation seasons fill crews and parking first.'),
      b('Globe multi-story is first-class product', 'Mining-town stairs and curb plans need inventories different from pure cabin lots.'),
      b('Long empty miles between towns are real', 'Payson ↔ Globe pairs fail when crews assume continuous density.'),
    ],
    zonesHeading: 'Gila zones: Payson multi-family, Globe multi-story, Miami edges & rural rim lots',
    zonesIntro: 'Two to four sharp products — recreation multi-family, mining multi-story, corridor edges, and rural lots.',
    zones: [
      z('payson', 'Payson multi-family & recreation stock', 'Payson', ['Payson', 'recreation multi-family', 'growth edges'], 'Multi-family, SFH, tourism stock', ['Tourism peaks', 'Grades', 'HOA packets'], ['payson'], 'Book around tourism peaks; survey driveway grades.'),
      z('globe', 'Globe multi-story & mining-town stock', 'Globe', ['Globe', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'US-60 freeflow'], ['globe'], 'Inventory stairs; plan temporary no-parking.'),
      z('miami', 'Miami / US-60 corridor edges', 'Miami', ['Miami', 'corridor multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['miami az'], 'Prefer early starts for long pairs.'),
      z('rural-rim', 'Rural rim & forest-edge lots', 'Rural rim', ['forest-edge tracts', 'rural approaches'], 'Larger lots, rural approaches', ['Long empty miles', 'Soft shoulders', 'Winter ice'], ['rural gila'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('rim-grades', 'Rim-country grade module', 'Elevation approaches rewrite desert truck assumptions.', ['Photo the final approach before promising a 26-foot truck.', 'Do not recycle Phoenix flat-cul-de-sac day rates.']),
      s('payson-tourism', 'Payson recreation peak module', 'Tourism weekends dominate volume.', ['Book capacity early for peak seasons.', 'Confirm multi-family packets early.']),
      s('globe-seat', 'Globe multi-story access', 'Mining-town stairs are first-class cost drivers.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Gila families compare Payson, Globe, Miami, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Banner Payson and Cobre Valley Regional (Globe) anchor acute care; map peak AZ-87 / US-60 times for ER access.',
    costIntro: 'Grades, multi-story access, tourism peaks, and town-to-town empty miles often matter more than raw miles.',
    seasonalIntro: 'Tourism summers, school years, monsoon weather, and winter ice reshape demand by pocket.',
  },
  {
    file: 'graham-az.ts',
    exportName: 'grahamCountyAzTier2Intelligence',
    slug: 'graham',
    hubTitle: 'Graham County Moving Intelligence Hub',
    eyebrow: 'Graham · Safford — upper Gila valley',
    h1: 'Moving in Graham County: Safford, Thatcher & Upper Gila Valley Access',
    heroOpener:
      'Graham County is southeast Arizona interior valley product — Safford multi-story and seat stock, Thatcher multi-family and college edges, Pima town and rural valley lots, and freeflow on US-70 that is not Phoenix or Tucson metro density with different labels. Expect small regional-hub logistics, long empty miles, and extreme heat under one county. This guide is for people moving in Graham as independent SE interior — not Phoenix/Tucson defaults.',
    heroCredibility:
      'SE interior independent · Safford regional hub · US-70 freeflow · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-70 · US-191 · AZ-366 · AZ-266',
    parentLabel: 'independent SE interior (vs Pima / Maricopa defaults)',
    parentHref: '/local-movers/arizona/pima',
    compareIntro:
      'Graham is independent SE interior small regional-hub product — not Tucson metro density and not Phoenix Loop sprawl.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Pima crews fight Tucson arterials. Graham pairs ride US-70 and US-191 — freer mid-day valley freeflow, still peak-heavy on Safford arterials and long empty-mile approaches from metro yards.'),
      b('Housing stock differences', 'Pima mixes Tucson multi-story and foothill HOAs. Graham mixes Safford multi-unit, Thatcher multi-family, and rural valley lots — more small-hub product, less continuous metro density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; rural valley lots add soft shoulders; long empty miles dominate.'),
      b('Rough cost posture (qualitative)', 'Local Graham quotes often sit at SE secondary rates for driveway SFH — multi-story access and long empty-mile pairs still push prices up.'),
      b('Role difference', 'Graham is independent SE interior hub — not Tucson or Phoenix product renamed.'),
    ],
    whatIntro: 'Small regional-hub multi-story, US-70 freeflow, and long empty miles — not interchangeable metro boilerplate.',
    whatBullets: [
      b('Safford multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('Long empty miles from metro yards are real', 'Even “regional” pairs can price as distance work for Tucson- or Phoenix-based crews.'),
      b('US-70 freeflow is still billable', 'Valley pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Extreme heat still governs summer open carries', 'Early starts outperform noon load-outs May–September.'),
    ],
    zonesHeading: 'Graham zones: Safford multi-story, Thatcher multi-family, Pima town edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, college multi-family, town edges, and rural lots.',
    zones: [
      z('safford', 'Safford multi-story & seat stock', 'Safford', ['Safford', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'US-70 freeflow'], ['safford'], 'Inventory stairs; plan temporary no-parking.'),
      z('thatcher', 'Thatcher multi-family & college edges', 'Thatcher', ['Thatcher', 'college multi-family'], 'Multi-family, SFH, townhomes', ['Lease clusters', 'Elevators/stairs', 'Arterial timing'], ['thatcher'], 'Book around term windows when near campus; confirm access type.'),
      z('pima-town', 'Pima town & valley edges', 'Pima town', ['Pima', 'valley multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['pima az town'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-valley', 'Rural upper Gila valley lots', 'Rural valley', ['rural tracts', 'eastern lots'], 'Larger lots, rural approaches', ['Long empty miles', 'Soft shoulders', 'Heat staging'], ['rural graham'], 'Photo approaches; early starts beat heat peaks.'),
    ],
    specialized: [
      s('small-hub', 'Safford small regional-hub module', 'Seat multi-story dominates hub volume.', ['Inventory stairs and curb width.', 'Do not recycle Tucson or Phoenix day rates alone.']),
      s('us70-freeflow', 'US-70 valley freeflow', 'Interior pairs still peak hard; empty miles matter.', ['Price portal-to-portal honestly.', 'Clarify Pima or Cochise second addresses early.']),
      s('heat-pacing', 'Desert heat pacing module', 'Summer open carries are first-class labor-hours drivers.', ['Prefer early starts May–September.', 'Pace crews and protect inventories.']),
    ],
    schoolsIntro: 'Graham families compare Safford, Thatcher, Pima, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Mt. Graham Regional Medical Center and Tucson specialty spillover serve the county; map peak US-70 times for ER access.',
    costIntro: 'Multi-story access, long empty miles, and heat pacing often matter more than raw miles.',
    seasonalIntro: 'School years, college calendars, monsoon weather, and extreme heat reshape demand by pocket.',
  },
  {
    file: 'apache-az.ts',
    exportName: 'apacheCountyAzTier2Intelligence',
    slug: 'apache',
    hubTitle: 'Apache County Moving Intelligence Hub',
    eyebrow: 'Apache · St. Johns / Window Rock edge — far NE AZ',
    h1: 'Moving in Apache County: St. Johns, Eagar & Far NE Rural Access',
    heroOpener:
      'Apache County is far northeast Arizona long-distance rural product — St. Johns multi-story and seat stock, Eagar/Springerville multi-family edges, Window Rock–adjacent approaches, and freeflow that still means very long empty miles between discontinuous communities. Expect elevation weather, tribal-adjacent logistics sensitivity, and sparse staging under one large county. This guide is for people moving in Apache as independent far NE AZ — not Phoenix or Flagstaff defaults.',
    heroCredibility:
      'Far NE AZ independent · Long rural empty miles · Elevation weather · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-191 · US-180 · AZ-61 · AZ-260 · I-40 northern approaches',
    parentLabel: 'independent far NE Arizona (vs Navajo / Coconino defaults)',
    parentHref: '/local-movers/arizona/navajo',
    compareIntro:
      'Apache is independent far NE AZ long-distance rural product — not Navajo Show Low recreation density alone and not Flagstaff university product.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Navajo crews still fight multi-town empty miles on I-40. Apache pairs ride US-191, US-180, and AZ-260 across even sparser seats — freer mid-day between towns, still peak-heavy on rare arterial windows and long staging from metro yards.'),
      b('Housing stock differences', 'Navajo mixes Show Low multi-family and Winslow multi-story. Apache mixes St. Johns multi-unit, Eagar edges, and rural lots — more sparse long-distance rural product, less continuous recreation multi-family density.'),
      b('Truck access & density', 'Long empty miles dominate; elevation weather rewrites staging; soft shoulders appear on rural approaches.'),
      b('Rough cost posture (qualitative)', 'Local Apache quotes often sit at far-NE secondary rates for driveway SFH — long empty-mile pairs and weather windows still push prices up vs map miles alone.'),
      b('Role difference', 'Apache is independent far NE AZ rural market — not Show Low or Flagstaff product renamed.'),
    ],
    whatIntro: 'Very long empty miles, elevation weather, and sparse multi-story seats — not interchangeable Show Low or Valley boilerplate.',
    whatBullets: [
      b('Long empty miles are the default pricing risk', 'Town pairs fail when crews assume continuous density or metro day rates.'),
      b('Elevation weather rewrites winter and monsoon staging', 'Ice, snow, and storms reshape morning curb plans.'),
      b('St. Johns multi-story is first-class product where present', 'Seat stairs need inventories different from pure rural lots.'),
      b('Tribal-adjacent logistics require careful address clarity', 'Confirm jurisdiction and access rules early; do not assume metro playbooks.'),
    ],
    zonesHeading: 'Apache zones: St. Johns multi-story, Eagar/Springerville edges, northern approaches & rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, mountain edges, northern approaches, and rural lots.',
    zones: [
      z('st-johns', 'St. Johns multi-story & seat stock', 'St. Johns', ['St. Johns', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Empty miles'], ['st johns'], 'Inventory stairs; plan temporary no-parking.'),
      z('eagar', 'Eagar / Springerville multi-family edges', 'Eagar / Springerville', ['Eagar', 'Springerville', 'multi-family edges'], 'SFH, multi-family, mixed stock', ['Elevation weather', 'Arterial timing', 'Empty miles'], ['eagar', 'springerville'], 'Prefer early starts; survey driveway grades.'),
      z('north-approaches', 'Northern / Window Rock–adjacent approaches', 'North approaches', ['northern corridors', 'Window Rock edges'], 'SFH, multi-family, mixed stock', ['Long empty miles', 'Access clarity', 'Weather staging'], ['window rock edges', 'north apache'], 'Clarify jurisdiction and access early; photo last-mile.'),
      z('rural-lots', 'Rural far-NE lots', 'Rural lots', ['rural tracts', 'forest-edge lots'], 'Larger lots, rural approaches', ['Very long empty miles', 'Soft shoulders', 'Winter ice'], ['rural apache'], 'Photo approaches; price empty miles honestly.'),
    ],
    specialized: [
      s('far-ne-empty', 'Far NE long empty-mile module', 'Sparse towns dominate pricing.', ['Price portal-to-portal between seats honestly.', 'Do not recycle Show Low or Flagstaff day rates alone.']),
      s('elevation-weather', 'Elevation weather module', 'Ice and storms rewrite desert staging assumptions.', ['Build winter morning flexibility into plans.', 'Monsoon and snow windows both matter.']),
      s('access-clarity', 'Tribal-adjacent access clarity', 'Jurisdiction and approach rules are first-class survey inputs.', ['Confirm access and address jurisdiction early.', 'Photo last-mile before promising truck size.']),
    ],
    schoolsIntro: 'Apache families compare St. Johns, Round Valley, and related district feeders — verify address boundaries; do not assume Navajo or Coconino maps apply.',
    hospitalsDetail: 'Summit Healthcare spillover and regional clinics serve the county; map peak freeflow across discontinuous towns for ER access.',
    costIntro: 'Very long empty miles, multi-story access where present, and elevation weather often matter more than raw miles.',
    seasonalIntro: 'School years, tourism edges, monsoon weather, and winter ice reshape demand by pocket.',
  },
];
