import { type PackDef, z, s, b } from './az-tier2-render';

/**
 * AZ Tier 2 Wave 1 packs 1–6 (Pima SKIPPED — existing Tier-1-depth pack preserved).
 * Counties: Pinal, Yavapai, Mohave, Yuma, Coconino, Cochise
 */
export const packsA: PackDef[] = [
  {
    file: 'pinal-az.ts',
    exportName: 'pinalCountyAzTier2Intelligence',
    slug: 'pinal',
    hubTitle: 'Pinal County Moving Intelligence Hub',
    eyebrow: 'Pinal · San Tan Valley / Casa Grande — Phoenix–Tucson corridor',
    h1: 'Moving in Pinal County: San Tan Valley, Casa Grande & I-10 Corridor Growth',
    heroOpener:
      'Pinal County is the Phoenix–Tucson Sun Corridor growth market — San Tan Valley and Queen Creek-edge HOA density, Casa Grande multi-family and industrial-adjacent stock, Florence and Arizona City edges, and freeflow on I-10 / AZ-347 that is not Maricopa East Valley product with different labels. Expect master-plan gate lists, longer empty miles from Valley yards, and extreme heat pacing under one county. This guide is for people moving in Pinal as outer-corridor growth — not a Maricopa rename.',
    heroCredibility:
      'Phoenix–Tucson corridor growth · HOA master plans · I-10 freeflow · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-10 · AZ-347 · AZ-79 · US-60 · AZ-287 · AZ-87',
    parentLabel: 'Maricopa County',
    parentHref: '/local-movers/arizona/maricopa',
    compareIntro:
      'Pinal is outer-corridor HOA and industrial-edge growth on I-10 — not Maricopa Loop multi-family density and not pure rural Sonoran freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Maricopa crews fight Loop 101/202 peaks into East and West Valley. Pinal pairs ride I-10, AZ-347, and US-60 — freer mid-day further south/east of the Valley, still peak-heavy toward San Tan commute windows and Casa Grande industrial shifts. Portal-to-portal time is real; it is not a Scottsdale elevator day.'),
      b('Housing stock differences', 'Maricopa mixes towers, East Valley multi-family, and West Valley HOAs. Pinal mixes San Tan planned SFH, Casa Grande multi-unit, and Florence/Arizona City edges — more continuous outer-corridor HOA product, less continuous Valley vertical density.'),
      b('Truck access & density', 'HOA COIs, gate lists, and approved hours dominate more often than central Phoenix dock permits. Rural southern lots add soft shoulders and longer empty miles.'),
      b('Rough cost posture (qualitative)', 'Local Pinal quotes often track outer-Valley suburb rates for driveway SFH — empty miles from Maricopa staging and HOA soft costs still push prices up vs map miles alone.'),
      b('Role difference', 'Pinal is Phoenix–Tucson corridor growth — not Maricopa core product renamed.'),
    ],
    whatIntro: 'Outer-corridor HOA density, I-10 freeflow, and empty miles from Valley yards — not interchangeable East Valley boilerplate.',
    whatBullets: [
      b('I-10 / AZ-347 peaks rewrite short-looking locals', 'Pinal ↔ Maricopa pairs freer mid-day still burn clock at commute peaks. Ask portal-to-portal.'),
      b('Master-plan HOA is first-class product', 'Gate lists, truck limits, and approved hours are standard on San Tan growth villages.'),
      b('Empty miles from Maricopa yards are real', 'Even “local” Pinal pairs can price as distance work for East Valley-based crews.'),
      b('Extreme heat still governs summer open carries', 'Early starts and paced labor outperform noon load-outs from May through September.'),
    ],
    zonesHeading: 'Pinal zones: San Tan growth, Casa Grande multi-unit, Florence corridor & southern rural edges',
    zonesIntro: 'Two to four sharp products — HOA growth, multi-unit corridors, seat edges, and rural lots.',
    zones: [
      z('san-tan', 'San Tan Valley / Queen Creek-edge HOA growth', 'San Tan growth', ['San Tan Valley', 'Queen Creek edges', 'HOA villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'AZ-347 peaks', 'Long cul-de-sacs'], ['san tan', 'queen creek'], 'Collect HOA COIs; build AZ-347 buffer for Maricopa pairs.'),
      z('casa-grande', 'Casa Grande multi-unit & industrial-adjacent stock', 'Casa Grande', ['Casa Grande', 'industrial multi-family', 'downtown edges'], 'Multi-family, older SFH, townhomes', ['Elevators/stairs', 'I-10 freeflow', 'Shift traffic'], ['casa grande'], 'Confirm elevator rules; prefer early starts near industrial corridors.'),
      z('florence', 'Florence / AZ-79 corridor edges', 'Florence', ['Florence', 'AZ-79 edges'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['florence'], 'Prefer early starts; confirm driveway depth.'),
      z('south-rural', 'Arizona City / southern rural edges', 'South rural', ['Arizona City', 'southern tracts'], 'SFH, rural-edge lots', ['Empty miles', 'Soft shoulders', 'Heat staging'], ['arizona city', 'south pinal'], 'Survey approaches; early starts beat heat peaks.'),
    ],
    specialized: [
      s('hoa-corridor', 'Outer-corridor HOA growth module', 'Master-plan rules dominate San Tan family volume.', ['Collect COI and gate lists before the estimate is final.', 'Saturday HOA windows push demand into peak crew slots.']),
      s('i10-freeflow', 'I-10 / AZ-347 freeflow', 'Corridor pairs still peak hard toward Maricopa.', ['Price portal-to-portal honestly.', 'Clarify Maricopa second addresses for drive-time assumptions.']),
      s('heat-pacing', 'Desert heat pacing module', 'Summer open carries are first-class labor-hours drivers.', ['Prefer early starts May–September.', 'Pace crews and protect cardboard inventories.']),
    ],
    schoolsIntro: 'Pinal families compare J.O. Combs, Florence Unified, Casa Grande Elementary/Union, and related district feeders — verify address boundaries; do not assume Maricopa maps apply.',
    hospitalsDetail: 'Banner and regional campuses with Valley specialty spillover serve the county; map peak I-10 / AZ-347 times for ER access.',
    costIntro: 'HOA soft costs, I-10 freeflow, empty miles from Valley yards, and heat pacing often matter more than raw miles.',
    seasonalIntro: 'School years, summer heat, and winter snowbird edges reshape demand more than pure Valley corporate calendars alone.',
  },
  {
    file: 'yavapai-az.ts',
    exportName: 'yavapaiCountyAzTier2Intelligence',
    slug: 'yavapai',
    hubTitle: 'Yavapai County Moving Intelligence Hub',
    eyebrow: 'Yavapai · Prescott / Prescott Valley / Sedona edge — high country',
    h1: 'Moving in Yavapai County: Prescott, Prescott Valley & High-Country Access',
    heroOpener:
      'Yavapai County is central Arizona high-country product — Prescott multi-story and historic stock, Prescott Valley HOA growth, Sedona-edge and Verde Valley approaches, and freeflow on I-17 / AZ-69 that is not Phoenix desert HOA sprawl with different elevation labels. Expect cooler seasons, grades, and longer empty miles under one county. This guide is for people moving in Yavapai as independent high-country — not desert-Phoenix defaults.',
    heroCredibility:
      'High-country independent · Prescott / PV growth · Elevation seasonality · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-17 · AZ-69 · AZ-89 · AZ-89A · AZ-169 · AZ-260 edges',
    parentLabel: 'independent high-country (nearest desert hub: Maricopa)',
    parentHref: '/local-movers/arizona/maricopa',
    compareIntro:
      'Yavapai is high-country independent product on I-17 / AZ-69 — not Maricopa desert Loop density and not pure rural forest freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Maricopa crews fight Loop peaks in extreme heat. Yavapai pairs ride I-17, AZ-69, and AZ-89 — freer mid-day high-country freeflow, still peak-heavy on Prescott arterials and weekend tourism windows toward Sedona edges.'),
      b('Housing stock differences', 'Maricopa mixes towers and master-plan HOAs. Yavapai mixes Prescott multi-story, PV planned SFH, and Verde/Sedona-edge stock — more elevation and tourism product, less continuous desert multi-family density.'),
      b('Truck access & density', 'Historic streets need curb plans; grades rewrite truck size; HOA packets appear on PV growth.'),
      b('Rough cost posture (qualitative)', 'Local Yavapai quotes often track high-country secondary rates for multi-story access — grades and tourism peaks can price above quiet PV driveway jobs.'),
      b('Role difference', 'Yavapai is independent high-country — not Phoenix desert product renamed.'),
    ],
    whatIntro: 'Elevation seasonality, Prescott multi-story, and I-17 freeflow — not interchangeable Valley boilerplate.',
    whatBullets: [
      b('Elevation rewrites summer and winter staging', 'Cooler summers help heat pacing; winter ice on grades rewrites morning curb plans.'),
      b('Prescott multi-story is first-class product', 'Historic stairs and curb plans need inventories different from pure PV cul-de-sacs.'),
      b('I-17 / AZ-69 freeflow is still billable', 'High-country pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Sedona-edge last-mile rejects Valley day rates', 'Tourism and narrow approaches rewrite truck size assumptions.'),
    ],
    zonesHeading: 'Yavapai zones: Prescott multi-story, Prescott Valley growth, Verde/Sedona edges & rural lots',
    zonesIntro: 'Two to four sharp products — historic multi-story, HOA growth, tourism edges, and rural lots.',
    zones: [
      z('prescott', 'Prescott multi-story & historic stock', 'Prescott', ['Prescott', 'downtown', 'historic multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Grades'], ['prescott'], 'Inventory stairs; plan temporary no-parking.'),
      z('pv-growth', 'Prescott Valley HOA growth', 'Prescott Valley', ['Prescott Valley', 'growth villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'AZ-69 freeflow'], ['prescott valley'], 'Collect HOA COIs; prefer early starts.'),
      z('verde-sedona', 'Verde Valley / Sedona-edge approaches', 'Verde / Sedona edge', ['Cottonwood edges', 'Sedona approaches', 'Camp Verde edges'], 'SFH, multi-family, tourism stock', ['Narrow approaches', 'Tourism peaks', 'Grades'], ['sedona', 'cottonwood', 'camp verde'], 'Photo last-mile; build tourism-weekend buffers.'),
      z('rural-lots', 'Northern & rural larger lots', 'Rural lots', ['Chino Valley edges', 'rural tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Winter ice'], ['chino valley', 'north yavapai'], 'Survey approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('high-country', 'High-country elevation module', 'Seasonality and grades rewrite desert day rates.', ['Plan winter ice and summer cooler starts honestly.', 'Do not recycle Phoenix heat-only playbooks.']),
      s('prescott-seat', 'Prescott multi-story access', 'Historic stairs are first-class cost drivers.', ['Inventory floor counts and curb width.', 'Temporary no-parking often beats long carries.']),
      s('i17-freeflow', 'I-17 / AZ-69 freeflow', 'High-country pairs still peak hard toward Maricopa.', ['Price portal-to-portal honestly.', 'Clarify Phoenix second addresses for long empty-mile assumptions.']),
    ],
    schoolsIntro: 'Yavapai families compare Prescott, Humboldt, Chino Valley, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Yavapai Regional Medical Center campuses and regional specialty spillover serve the county; map peak AZ-69 / I-17 times for ER access.',
    costIntro: 'Elevation grades, multi-story access, and corridor freeflow often matter more than raw miles.',
    seasonalIntro: 'Tourism weekends, school years, and winter ice reshape demand more than pure desert heat calendars.',
  },
  {
    file: 'mohave-az.ts',
    exportName: 'mohaveCountyAzTier2Intelligence',
    slug: 'mohave',
    hubTitle: 'Mohave County Moving Intelligence Hub',
    eyebrow: 'Mohave · Lake Havasu City / Kingman / Bullhead — NW AZ',
    h1: 'Moving in Mohave County: Lake Havasu, Kingman & Colorado River Access',
    heroOpener:
      'Mohave County is northwest Arizona river and I-40 product — Lake Havasu City multi-family and recreation stock, Kingman multi-story and seat corridors, Bullhead City river-edge density, and freeflow that still peaks toward CA/NV interstate legs. Expect tourism calendars, extreme heat, and border-adjacent authority questions under one county. This guide is for people moving in Mohave as independent NW AZ — not a Phoenix rename.',
    heroCredibility:
      'NW AZ independent · Colorado River recreation · I-40 / CA-NV edge · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-40 · US-93 · AZ-95 · AZ-68 · I-15 northwest edge',
    parentLabel: 'independent NW Arizona (vs Maricopa desert defaults)',
    parentHref: '/local-movers/arizona/maricopa',
    compareIntro:
      'Mohave is independent NW AZ river/recreation and I-40 product — not Maricopa Loop density and not pure rural desert freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Maricopa crews fight Valley Loop peaks. Mohave pairs ride I-40, US-93, and AZ-95 — freer mid-day NW freeflow, still peak-heavy on Lake Havasu tourism weekends and Kingman arterials.'),
      b('Housing stock differences', 'Maricopa mixes towers and master plans. Mohave mixes Havasu multi-family, Kingman multi-story, and Bullhead river-edge stock — more recreation and long empty-mile product, less continuous Valley HOA density.'),
      b('Truck access & density', 'River-edge and multi-family need curb plans; CA/NV addresses flip authority; rural edges add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Mohave quotes often track secondary NW rates for driveway SFH — tourism peaks and interstate legs can price above quiet inland lots.'),
      b('Role difference', 'Mohave is independent NW AZ river/I-40 market — not Phoenix product renamed.'),
    ],
    whatIntro: 'River recreation peaks, I-40 freeflow, and CA/NV interstate risk — not interchangeable Valley boilerplate.',
    whatBullets: [
      b('Tourism and recreation peaks rewrite weekends', 'Lake Havasu and river towns fill crews and parking at peak season.'),
      b('CA / NV adjacency creates interstate legs', 'Out-of-state addresses require FMCSA authority even on short-looking hops.'),
      b('I-40 / US-93 freeflow is still billable', 'NW pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Extreme heat still governs summer open carries', 'Early starts outperform noon load-outs on open river-edge streets.'),
    ],
    zonesHeading: 'Mohave zones: Lake Havasu multi-family, Kingman seat, Bullhead river edge & rural lots',
    zonesIntro: 'Two to four sharp products — recreation multi-family, seat multi-story, river edge, and rural lots.',
    zones: [
      z('havasu', 'Lake Havasu City multi-family & recreation stock', 'Lake Havasu', ['Lake Havasu City', 'recreation multi-family', 'waterfront edges'], 'Multi-family, SFH, tourism stock', ['Tourism peaks', 'Elevators/stairs', 'Heat staging'], ['lake havasu'], 'Book around tourism peaks; collect building rules.'),
      z('kingman', 'Kingman multi-story & I-40 seat corridors', 'Kingman', ['Kingman', 'downtown edges', 'I-40 multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-40 freeflow'], ['kingman'], 'Inventory stairs; plan temporary no-parking.'),
      z('bullhead', 'Bullhead City river-edge density', 'Bullhead', ['Bullhead City', 'river multi-family', 'AZ-95 corridors'], 'Multi-family, SFH, mixed stock', ['River freeflow', 'NV adjacency', 'Heat staging'], ['bullhead city'], 'Clarify NV second addresses; prefer early starts.'),
      z('rural-lots', 'Golden Valley / rural NW lots', 'Rural lots', ['Golden Valley', 'rural tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['golden valley', 'rural mohave'], 'Survey approaches; early starts beat heat peaks.'),
    ],
    specialized: [
      s('river-tourism', 'Colorado River recreation module', 'Tourism peaks dominate Havasu and river access.', ['Book and stage around major recreation weekends.', 'Confirm multi-family packets early.']),
      s('ca-nv-edge', 'CA / NV interstate edge module', 'Short map miles can still be interstate jobs.', ['Match ACC diligence vs FMCSA to exact addresses.', 'Do not recycle Phoenix day rates for river product.']),
      s('i40-freeflow', 'I-40 / US-93 freeflow', 'NW pairs still peak hard on arterials.', ['Price portal-to-portal honestly.', 'Build buffers for tourism and freight peaks.']),
    ],
    schoolsIntro: 'Mohave families compare Lake Havasu, Kingman, Bullhead City, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Havasu Regional, Kingman Regional, and Western Arizona Regional (Bullhead) anchor acute care; map peak AZ-95 / I-40 times for ER access.',
    costIntro: 'Tourism peaks, multi-family access, interstate authority risk, and heat pacing often matter more than raw miles.',
    seasonalIntro: 'Recreation summers, school years, and extreme heat reshape demand by pocket.',
  },
  {
    file: 'yuma-az.ts',
    exportName: 'yumaCountyAzTier2Intelligence',
    slug: 'yuma',
    hubTitle: 'Yuma County Moving Intelligence Hub',
    eyebrow: 'Yuma · southwest border agriculture / military',
    h1: 'Moving in Yuma County: Yuma City, Snowbird Season & I-8 Border Access',
    heroOpener:
      'Yuma County is southwest Arizona border and agriculture product — Yuma multi-story and multi-family stock, Foothills and Fortuna edges, agricultural-edge residential, and freeflow on I-8 that is not Phoenix desert HOA sprawl with different labels. Expect winter snowbird peaks, military/ag calendars, CA/MX-adjacent logistics, and extreme heat under one county. This guide is for people moving in Yuma as independent SW AZ — not a Valley rename.',
    heroCredibility:
      'SW AZ independent · Snowbird season · I-8 border logistics · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-8 · US-95 · AZ-195 · Business 8 · 4th Avenue corridor',
    parentLabel: 'independent SW Arizona (vs Maricopa desert defaults)',
    parentHref: '/local-movers/arizona/maricopa',
    compareIntro:
      'Yuma is independent SW AZ border/agriculture/snowbird product on I-8 — not Maricopa Loop density and not pure rural desert freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Maricopa crews fight Valley Loop peaks. Yuma pairs ride I-8, US-95, and local arterials — freer mid-day SW freeflow, still peak-heavy on winter snowbird windows and agricultural shift traffic.'),
      b('Housing stock differences', 'Maricopa mixes towers and master plans. Yuma mixes city multi-story, Foothills multi-family, and ag-edge SFH — more seasonal and border product, less continuous Valley HOA density.'),
      b('Truck access & density', 'Multi-family elevators appear on growth edges; CA addresses flip authority; rural ag edges add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Yuma quotes often track SW secondary rates for driveway SFH — snowbird peaks and heat can price above quiet off-season lots.'),
      b('Role difference', 'Yuma is independent SW AZ border market — not Phoenix product renamed.'),
    ],
    whatIntro: 'Snowbird calendars, I-8 freeflow, and border logistics — not interchangeable Valley boilerplate.',
    whatBullets: [
      b('Winter snowbird peaks rewrite demand', 'Seasonal inventories and short windows fill crews first from late fall through early spring.'),
      b('CA adjacency creates interstate legs', 'California addresses require FMCSA authority even on short-looking hops.'),
      b('I-8 freeflow is still billable', 'SW pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Extreme heat still governs summer open carries', 'Early starts outperform noon load-outs May–September.'),
    ],
    zonesHeading: 'Yuma zones: city multi-story, Foothills multi-family, ag-edge residential & rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, growth multi-family, ag-edge SFH, and rural lots.',
    zones: [
      z('yuma-city', 'Yuma city multi-story & multi-unit', 'Yuma city', ['Yuma', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-8 freeflow'], ['yuma'], 'Inventory stairs; plan temporary no-parking.'),
      z('foothills', 'Foothills / Fortuna multi-family growth', 'Foothills', ['Foothills', 'Fortuna Foothills', 'growth multi-family'], 'Multi-family, HOA SFH, townhomes', ['HOA packets', 'Elevators', 'Snowbird peaks'], ['foothills', 'fortuna'], 'Collect HOA COIs; book winter peaks early.'),
      z('ag-edge', 'Agricultural-edge residential', 'Ag edge', ['ag-adjacent SFH', 'US-95 edges'], 'SFH, multi-family, mixed stock', ['Shift traffic', 'Dust/soft shoulders'], ['south yuma'], 'Prefer early starts; survey last-mile on ag streets.'),
      z('rural-lots', 'Eastern & rural larger lots', 'Rural lots', ['Wellton edges', 'eastern tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Heat staging'], ['wellton', 'east yuma'], 'Photo approaches; early starts beat heat peaks.'),
    ],
    specialized: [
      s('snowbird', 'Snowbird seasonal module', 'Winter peaks dominate volume.', ['Book capacity early for Nov–Mar windows.', 'Inventory profiles differ from pure year-round family SFH.']),
      s('i8-border', 'I-8 border freeflow & CA legs', 'SW pairs still peak hard; CA legs need FMCSA.', ['Price portal-to-portal honestly.', 'Clarify California second addresses for interstate authority.']),
      s('heat-pacing', 'Desert heat pacing module', 'Summer open carries are first-class labor-hours drivers.', ['Prefer early starts May–September.', 'Pace crews and protect inventories.']),
    ],
    schoolsIntro: 'Yuma families compare Yuma Elementary/Union, Crane, Gadsden, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Yuma Regional Medical Center anchors acute care; map peak I-8 / arterial times for ER access.',
    costIntro: 'Snowbird peaks, multi-family access, interstate authority risk, and heat pacing often matter more than raw miles.',
    seasonalIntro: 'Snowbird winters, ag calendars, school years, and extreme heat reshape demand by pocket.',
  },
  {
    file: 'coconino-az.ts',
    exportName: 'coconinoCountyAzTier2Intelligence',
    slug: 'coconino',
    hubTitle: 'Coconino County Moving Intelligence Hub',
    eyebrow: 'Coconino · Flagstaff — high country / I-40',
    h1: 'Moving in Coconino County: Flagstaff, NAU Cycles & High-Country I-40 Access',
    heroOpener:
      'Coconino County is northern Arizona high-country product — Flagstaff multi-story and NAU-adjacent density, canyon-region and forest-edge approaches, Page and rural long empty miles, and freeflow on I-40 / I-17 that is not Phoenix desert HOA sprawl with pine labels. Expect elevation weather, university calendars, and tourism peaks under one county. This guide is for people moving in Coconino as independent northern AZ — not desert-Phoenix defaults.',
    heroCredibility:
      'Northern AZ high country · NAU cycles · I-40 / elevation · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-40 · I-17 · US-89 · US-180 · AZ-89A · Milton Road corridor',
    parentLabel: 'independent northern Arizona (vs Maricopa desert defaults)',
    parentHref: '/local-movers/arizona/maricopa',
    compareIntro:
      'Coconino is independent northern high-country product on I-40 / I-17 — not Maricopa desert Loop density and not pure rural canyon freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Maricopa crews fight Loop peaks in extreme heat. Coconino pairs ride I-40, I-17, and US-89 — freer mid-day high-country freeflow, still peak-heavy on Flagstaff arterials, NAU term windows, and tourism weekends.'),
      b('Housing stock differences', 'Maricopa mixes towers and master plans. Coconino mixes Flagstaff multi-story, NAU multi-family, and forest-edge SFH — more elevation and university product, less continuous desert HOA density.'),
      b('Truck access & density', 'Snow and grades rewrite truck size; campus multi-family needs COIs; long rural empty miles dominate outer pockets.'),
      b('Rough cost posture (qualitative)', 'Local Coconino quotes often track high-country secondary-premium rates for multi-story access — snow windows and tourism peaks can price above quiet off-season lots.'),
      b('Role difference', 'Coconino is independent northern high-country — not Phoenix product renamed.'),
    ],
    whatIntro: 'Elevation weather, NAU term calendars, and I-40 freeflow — not interchangeable Valley boilerplate.',
    whatBullets: [
      b('NAU term calendars drive Flagstaff demand spikes', 'Move-in/out weekends fill crews and parking near campus. Book early.'),
      b('Elevation snow and ice rewrite winter curb plans', 'Morning staging can fail when crews assume desert freeflow.'),
      b('I-40 / I-17 freeflow is still billable', 'High-country pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Canyon-region and forest edges rewrite truck size', 'Narrow approaches reject full-trailer assumptions from Valley rates.'),
    ],
    zonesHeading: 'Coconino zones: Flagstaff multi-story, NAU multi-family, forest edges & long rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, campus multi-family, forest edges, and long rural lots.',
    zones: [
      z('flagstaff', 'Flagstaff multi-story & seat stock', 'Flagstaff', ['Flagstaff', 'downtown', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Winter ice'], ['flagstaff'], 'Inventory stairs; winter mornings need flexibility.'),
      z('nau', 'NAU campus-edge multi-family', 'NAU edge', ['campus multi-family', 'student stock'], 'Multi-family, apartments, some SFH', ['Term parking', 'COI packets', 'Elevators'], ['nau', 'northern arizona university'], 'Book around term calendars; collect building rules.'),
      z('forest-edge', 'Forest-edge / mountain approaches', 'Forest edge', ['Kachina Village edges', 'mountain SFH'], 'SFH, forest-edge lots', ['Grades', 'Narrow approaches', 'Snow staging'], ['kachina', 'forest edge'], 'Photo last-mile; discuss smaller trucks early.'),
      z('rural-long', 'Page / long rural empty-mile edges', 'Long rural', ['Page edges', 'eastern rural tracts'], 'SFH, rural approaches', ['Long empty miles', 'Soft shoulders'], ['page', 'east coconino'], 'Price empty miles honestly; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('nau-cycles', 'NAU university move-cycle module', 'Term calendars drive demand spikes.', ['Book early around move-in/out weekends.', 'Price campus-edge curb time honestly.']),
      s('elevation-weather', 'High-country weather module', 'Snow and ice rewrite desert staging assumptions.', ['Build winter morning flexibility into plans.', 'Do not recycle Phoenix heat-only playbooks.']),
      s('i40-high', 'I-40 / I-17 high-country freeflow', 'Northern pairs still peak hard on arterials.', ['Price portal-to-portal honestly.', 'Clarify Phoenix second addresses for long empty-mile assumptions.']),
    ],
    schoolsIntro: 'Coconino families compare Flagstaff Unified and related district feeders — verify address boundaries; do not assume Valley maps apply.',
    hospitalsDetail: 'Flagstaff Medical Center and regional specialty spillover serve the county; map peak I-40 / arterial times for ER access.',
    costIntro: 'Term peaks, multi-story access, elevation weather, and long empty miles often matter more than raw miles.',
    seasonalIntro: 'University calendars, tourism summers, school years, and winter snow reshape demand by pocket.',
  },
  {
    file: 'cochise-az.ts',
    exportName: 'cochiseCountyAzTier2Intelligence',
    slug: 'cochise',
    hubTitle: 'Cochise County Moving Intelligence Hub',
    eyebrow: 'Cochise · Sierra Vista / Bisbee / Douglas — SE AZ',
    h1: 'Moving in Cochise County: Sierra Vista, Fort Huachuca & SE Border Access',
    heroOpener:
      'Cochise County is southeast Arizona military and border-town product — Sierra Vista multi-family and Fort Huachuca PCS calendars, Bisbee multi-story and hill stock, Douglas border-edge density, and freeflow that is not Tucson basin product with different labels. Expect order-driven report dates, long empty miles between discontinuous towns, and MX-adjacent logistics under one county. This guide is for people moving in Cochise as independent SE AZ — not a Tucson rename.',
    heroCredibility:
      'SE AZ independent · Fort Huachuca PCS · Border towns · ACC entity diligence · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-10 · AZ-90 · AZ-80 · AZ-92 · US-191',
    parentLabel: 'independent SE Arizona (vs Pima / Tucson defaults)',
    parentHref: '/local-movers/arizona/pima',
    compareIntro:
      'Cochise is independent SE AZ military/border-town product — not Pima Tucson basin density and not pure rural desert freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Pima crews fight Tucson arterials and I-10 peaks. Cochise pairs ride AZ-90, AZ-80, and I-10 links — freer mid-day SE freeflow, still peak-heavy on Sierra Vista arterials and PCS lease-end clusters.'),
      b('Housing stock differences', 'Pima mixes Tucson multi-story and foothill HOAs. Cochise mixes Sierra Vista multi-family, Bisbee hills, and Douglas border stock — more military and discontinuous town product, less continuous Tucson metro density.'),
      b('Truck access & density', 'Base-adjacent apartments need COIs; Bisbee hills need grade surveys; long empty miles dominate town-to-town pairs.'),
      b('Rough cost posture (qualitative)', 'Local Cochise quotes often track SE secondary rates for multi-family access — PCS peaks and hill last-mile can price above quiet rural lots.'),
      b('Role difference', 'Cochise is independent SE AZ Fort Huachuca / border market — not Tucson product renamed.'),
    ],
    whatIntro: 'PCS report dates, Sierra Vista multi-family, and SE empty miles — not interchangeable Tucson boilerplate.',
    whatBullets: [
      b('Fort Huachuca PCS orders compress calendars', 'Report dates drive surveys more than preferred Saturdays.'),
      b('Sierra Vista multi-family is first-class product', 'Elevators and parking need inventories different from pure SFH lots.'),
      b('Bisbee hill last-mile rewrites truck size', 'Grades and narrow streets reject full-trailer assumptions.'),
      b('Discontinuous towns add empty miles', 'Douglas and rural pairs fail when crews assume continuous Tucson density.'),
    ],
    zonesHeading: 'Cochise zones: Sierra Vista multi-family, Fort Huachuca edge, Bisbee hills & Douglas border',
    zonesIntro: 'Two to four sharp products — multi-family seat, base edge, hill multi-story, and border stock.',
    zones: [
      z('sierra-vista', 'Sierra Vista multi-family & seat stock', 'Sierra Vista', ['Sierra Vista', 'multi-family corridors'], 'Multi-family, SFH, townhomes', ['Elevators', 'PCS clusters', 'Arterial freeflow'], ['sierra vista'], 'Book around report dates; collect building rules.'),
      z('huachuca', 'Fort Huachuca–adjacent multi-family', 'Base edge', ['base-adjacent apartments', 'Huachuca City edges'], 'Multi-family, apartments', ['PCS peaks', 'Parking limits', 'COI packets'], ['fort huachuca', 'huachuca city'], 'Align surveys with report dates; document inventories carefully.'),
      z('bisbee', 'Bisbee multi-story & hill stock', 'Bisbee', ['Bisbee', 'hill multi-story', 'historic edges'], 'Multi-story, multi-unit, older SFH', ['Grades', 'Narrow streets', 'Stairs'], ['bisbee'], 'Photo last-mile; discuss smaller trucks early.'),
      z('douglas', 'Douglas border-edge & rural SE lots', 'Douglas / rural', ['Douglas', 'southern rural tracts'], 'SFH, multi-family, rural approaches', ['Empty miles', 'Border freeflow'], ['douglas'], 'Prefer early starts for long pairs; survey approaches.'),
    ],
    specialized: [
      s('pcs-cycles', 'Fort Huachuca PCS cycle module', 'Order-driven calendars dominate volume.', ['Align surveys with report dates.', 'Document inventory carefully for military claims processes.']),
      s('sv-multi', 'Sierra Vista multi-family access', 'Elevators and parking are first-class cost drivers.', ['Collect COI and elevator reservations early.', 'Month-end clusters stack; book capacity early.']),
      s('bisbee-hills', 'Bisbee hill last-mile', 'Grades reject full-trailer assumptions from Tucson rates.', ['Photo the final approach before promising a 26-foot truck.', 'Long carries often beat forced full-trailer staging.']),
    ],
    schoolsIntro: 'Cochise families compare Sierra Vista, Bisbee, Douglas, and related district feeders — verify address boundaries; do not assume Tucson maps apply.',
    hospitalsDetail: 'Canyon Vista Medical Center and regional specialty spillover serve the county; map peak AZ-90 times for ER access.',
    costIntro: 'PCS peaks, multi-family access, hill last-mile, and town-to-town empty miles often matter more than raw miles.',
    seasonalIntro: 'PCS cycles, school years, monsoon weather, and extreme heat reshape demand by pocket.',
  },
];
