import { type PackDef, z, s, b } from './co-tier2-render';

/** CO Tier 2 Wave 1 packs 7–12 */
export const packsB: PackDef[] = [
  {
    file: 'garfield-co.ts',
    exportName: 'garfieldCountyCoTier2Intelligence',
    slug: 'garfield',
    hubTitle: 'Garfield County Moving Intelligence Hub',
    eyebrow: 'Garfield · Glenwood Springs / Rifle — mid-Western Slope',
    h1: 'Moving in Garfield County: Glenwood Springs, Rifle & Mid-Slope I-70 Access',
    heroOpener:
      'Garfield County is mid-Western Slope I-70 product — Glenwood Springs multi-story and seat density, Rifle multi-family and industrial-edge stock, Carbondale and New Castle edges, and freeflow that is not Vail/Eagle resort-core product with different labels. Expect canyon approaches, energy calendars, and longer empty miles under one county. This guide is for people moving in Garfield as mid-slope secondary — not an Eagle rename.',
    heroCredibility:
      'Mid-Western Slope · Glenwood / Rifle · I-70 mid-slope · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-70 · CO-82 · CO-13 · US-6 · Grand Avenue corridor',
    parentLabel: 'Eagle County',
    parentHref: '/local-movers/colorado/eagle',
    compareIntro:
      'Garfield is mid-slope Glenwood/Rifle product on I-70 — not Eagle Vail/Edwards resort-core density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Eagle crews fight Vail/Edwards tourism peaks. Garfield pairs ride I-70 and CO-82 — freer mid-day mid-slope freeflow, still peak-heavy on Glenwood arterials and Rifle industrial windows.'),
      b('Housing stock differences', 'Eagle mixes resort multi-story and planned multi-family. Garfield mixes Glenwood multi-story, Rifle multi-unit, and canyon-edge SFH — more mid-slope working-town product, less continuous resort-association density.'),
      b('Truck access & density', 'Canyon streets need curb plans; multi-family elevators appear on growth edges; industrial streets rewrite truck type.'),
      b('Rough cost posture (qualitative)', 'Local Garfield quotes often track mid-slope secondary rates for driveway SFH — multi-story Glenwood access and empty miles still push prices up.'),
      b('Role difference', 'Garfield is mid-Western Slope secondary — not Eagle resort core renamed.'),
    ],
    whatIntro: 'Glenwood multi-story, Rifle industrial edges, and I-70 mid-slope freeflow — not interchangeable Vail boilerplate.',
    whatBullets: [
      b('Distinct from Eagle/Vail resort-core assumptions', 'Do not recycle Vail association day rates alone.'),
      b('Glenwood multi-story is first-class product', 'Seat stairs need inventories different from pure Rifle lots.'),
      b('I-70 freeflow is still billable', 'Mid-slope pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Energy calendars reshape mid-week demand in Rifle corridors', 'Shift patterns rewrite pure Saturday residential assumptions.'),
    ],
    zonesHeading: 'Garfield zones: Glenwood multi-story, Rifle multi-family, Carbondale edges & rural canyon lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, industrial multi-family, valley edges, and rural lots.',
    zones: [
      z('glenwood', 'Glenwood Springs multi-story & seat stock', 'Glenwood', ['Glenwood Springs', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-70 freeflow'], ['glenwood springs'], 'Inventory stairs; plan temporary no-parking.'),
      z('rifle', 'Rifle multi-family & industrial-edge stock', 'Rifle', ['Rifle', 'industrial multi-family'], 'Multi-family, SFH, mixed stock', ['Shift traffic', 'Elevators/stairs', 'Arterial timing'], ['rifle'], 'Prefer early starts; survey last-mile on industrial streets.'),
      z('carbondale', 'Carbondale / New Castle valley edges', 'Carbondale edges', ['Carbondale', 'New Castle', 'CO-82 edges'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Tourism freeflow'], ['carbondale', 'new castle'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-canyon', 'Rural canyon & mountain lots', 'Rural canyon', ['rural tracts', 'canyon approaches'], 'Larger lots, mountain approaches', ['Empty miles', 'Grades', 'Winter ice'], ['rural garfield'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('vs-eagle', 'Garfield vs Eagle resort-core', 'Mid-slope working towns differ from Vail/Edwards association density.', ['Do not recycle Vail association day rates alone.', 'Clarify Eagle second addresses for drive-time assumptions.']),
      s('glenwood-seat', 'Glenwood multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('i70-mid', 'I-70 mid-slope freeflow', 'Mid-slope pairs still peak hard on arterials.', ['Price portal-to-portal honestly.', 'Monitor canyon and pass conditions in season.']),
    ],
    schoolsIntro: 'Garfield families compare Roaring Fork, Rifle RE-2, and related district feeders — verify address boundaries; do not assume Eagle maps apply.',
    hospitalsDetail: 'Valley View Hospital and Grand River Health (Rifle) anchor acute care; map peak I-70 times for ER access.',
    costIntro: 'Multi-story access, I-70 freeflow, and industrial empty miles often matter more than raw miles.',
    seasonalIntro: 'Tourism shoulders, energy calendars, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'routt-co.ts',
    exportName: 'routtCountyCoTier2Intelligence',
    slug: 'routt',
    hubTitle: 'Routt County Moving Intelligence Hub',
    eyebrow: 'Routt · Steamboat Springs — northwest ski hub',
    h1: 'Moving in Routt County: Steamboat Springs, Yampa Valley & NW Resort Access',
    heroOpener:
      'Routt County is northwest Colorado Yampa Valley resort product — Steamboat Springs multi-story and resort density, multi-family growth edges, Hayden and rural valley approaches, and freeflow that is not I-70 Eagle/Summit corridor product with different labels. Expect elevation weather, association truck limits, and seasonal calendars under one county. This guide is for people moving in Routt as independent NW mountain hub — not a Summit or Eagle rename.',
    heroCredibility:
      'NW mountain independent · Steamboat / Yampa Valley · Seasonal logistics · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-40 · CO-131 · CO-14 · Lincoln Avenue corridor',
    parentLabel: 'independent NW mountain (vs Eagle / Summit)',
    parentHref: '/local-movers/colorado/eagle',
    parentAltLabel: 'Summit County',
    parentAltHref: '/local-movers/colorado/summit',
    compareIntro:
      'Routt is independent Yampa Valley Steamboat resort product — not Eagle Vail corridor and not Summit high-country basin product alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Eagle/Summit crews fight I-70 pass peaks. Routt pairs ride US-40 and valley arterials — freer mid-day Yampa freeflow, still peak-heavy on Steamboat tourism weekends and winter weather windows.'),
      b('Housing stock differences', 'I-70 resorts mix corridor multi-story and lake-basin multi-family. Routt mixes Steamboat multi-story, valley multi-family, and rural lots — more Yampa Valley product, less continuous I-70 corridor density.'),
      b('Truck access & density', 'Resort associations limit truck size; grades rewrite staging; winter weather is first-class.'),
      b('Rough cost posture (qualitative)', 'Local Routt quotes often track premium NW mountain secondary rates when associations require shuttles — clean valley driveway SFH can price lower than resort multi-story jobs.'),
      b('Role difference', 'Routt is independent NW Yampa Valley resort hub — not Eagle or Summit product renamed.'),
    ],
    whatIntro: 'Steamboat multi-story, Yampa freeflow, and seasonal peaks — not interchangeable I-70 resort boilerplate.',
    whatBullets: [
      b('Ski-season peaks rewrite weekends', 'Steamboat volume stacks around major tourism windows. Book early.'),
      b('Resort association access is first-class product', 'Truck limits and elevators rewrite pure driveway rates.'),
      b('Distinct from Eagle and Summit I-70 products', 'Do not recycle Vail or Breckenridge day rates alone.'),
      b('US-40 freeflow is still billable', 'Valley pairs freer mid-day still peak hard. Ask portal-to-portal.'),
    ],
    zonesHeading: 'Routt zones: Steamboat multi-story, multi-family growth, Hayden edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — resort multi-story, multi-family growth, corridor edges, and rural lots.',
    zones: [
      z('steamboat', 'Steamboat Springs multi-story & resort density', 'Steamboat', ['Steamboat Springs', 'resort multi-family', 'village edges'], 'Multi-story, multi-unit, elevators', ['Association packets', 'Tourism peaks', 'Grades'], ['steamboat springs'], 'Collect association rules; book around peak weekends.'),
      z('multi-growth', 'Steamboat multi-family growth edges', 'Multi-family growth', ['growth multi-family', 'valley multi-unit'], 'Multi-family, apartments, townhomes', ['Elevators', 'HOA packets', 'Lease clusters'], ['steamboat multi'], 'Collect building rules; build tourism buffers.'),
      z('hayden', 'Hayden / US-40 corridor edges', 'Hayden', ['Hayden', 'US-40 multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['hayden'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-yampa', 'Rural Yampa valley lots', 'Rural valley', ['rural tracts', 'mountain approaches'], 'Larger lots, rural approaches', ['Long empty miles', 'Soft shoulders', 'Winter ice'], ['rural routt'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('vs-i70', 'Routt vs Eagle/Summit distinction', 'Yampa Valley product differs from I-70 corridor resorts.', ['Do not recycle Vail or Breckenridge day rates alone.', 'Clarify Eagle/Summit second addresses for long empty-mile assumptions.']),
      s('resort-assoc', 'Steamboat resort association last-mile', 'Association truck limits are first-class cost drivers.', ['Confirm size limits and elevator rules early.', 'Build tourism peak buffers.']),
      s('us40-freeflow', 'US-40 Yampa freeflow', 'Valley pairs still peak hard on arterials.', ['Price portal-to-portal honestly.', 'Monitor winter weather windows.']),
    ],
    schoolsIntro: 'Routt families compare Steamboat Springs RE-2 and related district feeders — verify address boundaries.',
    hospitalsDetail: 'UCHealth Yampa Valley Medical Center anchors acute care; map peak US-40 times for ER access.',
    costIntro: 'Association last-mile, seasonal peaks, and valley freeflow often matter more than raw miles.',
    seasonalIntro: 'Ski season, summer tourism, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'elbert-co.ts',
    exportName: 'elbertCountyCoTier2Intelligence',
    slug: 'elbert',
    hubTitle: 'Elbert County Moving Intelligence Hub',
    eyebrow: 'Elbert · Elizabeth / Kiowa — outer SE Denver plains collar',
    h1: 'Moving in Elbert County: Elizabeth, Kiowa & Outer Plains Collar Access',
    heroOpener:
      'Elbert County is outer southeast Denver plains collar product — Elizabeth multi-family and growth edges, Kiowa seat stock, acreage and exurban lots, and freeflow on CO-86 / E-470 approaches that is not Douglas County Highlands Ranch product with different labels. Expect longer empty miles, soft-shoulder last-mile, and lower density under one county. This guide is for people moving in Elbert as outer plains collar — not a Douglas rename.',
    heroCredibility:
      'Outer SE plains collar · Elizabeth / Kiowa · Acreage exurban · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'CO-86 · CO-86/CO-83 links · E-470 approaches · Kiowa–Bennett corridors',
    parentLabel: 'Douglas County',
    parentHref: '/local-movers/colorado/douglas',
    parentAltLabel: 'Arapahoe County',
    parentAltHref: '/local-movers/colorado/arapahoe',
    compareIntro:
      'Elbert is outer SE plains acreage/exurban collar — not Douglas continuous Highlands Ranch HOA density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Douglas crews fight I-25 and C-470 peaks into Castle Rock/HR. Elbert pairs ride CO-86 and E-470 approaches — freer mid-day further east, still peak-heavy toward metro portals and Elizabeth commute windows.'),
      b('Housing stock differences', 'Douglas mixes master-plan HOAs and multi-family. Elbert mixes Elizabeth multi-unit, Kiowa seat stock, and acreage lots — more continuous exurban product, less continuous planned-suburb density.'),
      b('Truck access & density', 'Acreage driveways and soft shoulders dominate; HOA packets appear on growth edges; long empty miles from metro yards are first-class.'),
      b('Rough cost posture (qualitative)', 'Local Elbert quotes often track outer-collar secondary rates for driveway SFH — empty miles from Douglas/Arapahoe staging still push prices up vs map miles alone.'),
      b('Role difference', 'Elbert is outer SE plains collar — not Douglas product renamed.'),
    ],
    whatIntro: 'Acreage last-mile, CO-86 freeflow, and empty miles from metro yards — not interchangeable Highlands Ranch boilerplate.',
    whatBullets: [
      b('Empty miles from Douglas/Arapahoe yards are real', 'Even “local” Elbert pairs can price as distance work for metro-based crews.'),
      b('Acreage approaches rewrite truck size', 'Long drives and soft shoulders reject pure HOA cul-de-sac assumptions.'),
      b('Elizabeth multi-family differs from pure acreage lots', 'Elevators and curb plans need inventories different from rural driveways.'),
      b('CO-86 freeflow is still billable', 'Outer-collar pairs freer mid-day still peak hard. Ask portal-to-portal.'),
    ],
    zonesHeading: 'Elbert zones: Elizabeth growth, Kiowa seat, acreage belts & eastern rural lots',
    zonesIntro: 'Two to four sharp products — growth multi-family, seat stock, acreage belts, and rural lots.',
    zones: [
      z('elizabeth', 'Elizabeth multi-family & growth edges', 'Elizabeth', ['Elizabeth', 'growth multi-family', 'HOA edges'], 'Multi-family, HOA SFH, townhomes', ['HOA packets', 'CO-86 freeflow', 'Lease clusters'], ['elizabeth'], 'Collect HOA COIs; build metro-commute buffers.'),
      z('kiowa', 'Kiowa seat multi-story & older stock', 'Kiowa', ['Kiowa', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking'], ['kiowa'], 'Inventory stairs; plan temporary no-parking.'),
      z('acreage', 'Acreage / exurban belts', 'Acreage belts', ['acreage lots', 'exurban SFH'], 'Larger lots, long driveways', ['Long carries', 'Soft shoulders', 'Empty miles'], ['elbert acreage'], 'Photo approaches; confirm truck turnaround.'),
      z('east-rural', 'Eastern rural plains lots', 'East rural', ['eastern tracts', 'rural approaches'], 'Larger lots, rural approaches', ['Long empty miles', 'Soft shoulders', 'Winter ice'], ['east elbert'], 'Survey approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('outer-collar', 'Outer SE plains collar freeflow', 'Outer pairs still peak hard toward Douglas/Arapahoe.', ['Price portal-to-portal honestly.', 'Clarify Douglas or Arapahoe second addresses early.']),
      s('acreage-last', 'Acreage last-mile module', 'Long drives and soft shoulders rewrite HOA day rates.', ['Photo the final approach before promising a 26-foot truck.', 'Do not recycle Highlands Ranch cul-de-sac assumptions.']),
      s('elizabeth-growth', 'Elizabeth growth multi-family', 'Elevators and HOA packets are first-class cost drivers.', ['Collect COI and elevator rules early.', 'Lease clusters stack around school calendars.']),
    ],
    schoolsIntro: 'Elbert families compare Elizabeth C-1, Kiowa C-2, and related district feeders — verify address boundaries; do not assume Douglas maps apply.',
    hospitalsDetail: 'Parker/Arapahoe specialty spillover and regional clinics serve the county; map peak CO-86 / E-470 times for ER access.',
    costIntro: 'Empty miles, acreage last-mile, and HOA soft costs often matter more than raw miles.',
    seasonalIntro: 'School years, summer family closings, and winter ice reshape demand by pocket.',
  },
  {
    file: 'teller-co.ts',
    exportName: 'tellerCountyCoTier2Intelligence',
    slug: 'teller',
    hubTitle: 'Teller County Moving Intelligence Hub',
    eyebrow: 'Teller · Woodland Park — Colorado Springs west mountain edge',
    h1: 'Moving in Teller County: Woodland Park, Mountain-West COS Collar Access',
    heroOpener:
      'Teller County is Colorado Springs’ western mountain collar — Woodland Park multi-family and growth stock, Divide and Florissant edges, Cripple Creek tourism approaches, and freeflow on US-24 that is not El Paso continuous Springs multi-family with different labels. Expect elevation grades, tourism peaks, and longer empty miles under one county. This guide is for people moving in Teller as COS mountain-west collar — not an El Paso rename.',
    heroCredibility:
      'COS mountain-west collar · Woodland Park · US-24 freeflow · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-24 · CO-67 · CO-67/CO-9 links · Woodland Park arterials',
    parentLabel: 'El Paso County',
    parentHref: '/local-movers/colorado/el-paso',
    compareIntro:
      'Teller is Colorado Springs mountain-west collar on US-24 — not El Paso continuous Springs multi-family density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'El Paso crews fight I-25 and Powers peaks into Colorado Springs. Teller pairs ride US-24 west — freer mid-day further into the mountains, still peak-heavy on Woodland Park arterials and tourism weekends.'),
      b('Housing stock differences', 'El Paso mixes Springs multi-family and north-growth HOAs. Teller mixes Woodland Park multi-unit, mountain SFH, and tourism stock — more elevation product, less continuous Springs density.'),
      b('Truck access & density', 'Grades rewrite truck size; multi-family elevators appear on growth edges; soft shoulders appear on rural approaches.'),
      b('Rough cost posture (qualitative)', 'Local Teller quotes often track mountain-collar secondary rates for multi-story access — grades and empty miles from Springs yards still push prices up.'),
      b('Role difference', 'Teller is COS mountain-west collar — not El Paso product renamed.'),
    ],
    whatIntro: 'US-24 freeflow, mountain grades, and Woodland Park multi-family — not interchangeable Springs boilerplate.',
    whatBullets: [
      b('Empty miles from El Paso yards are real', 'Even “local” Teller pairs can price as distance work for Springs-based crews.'),
      b('Mountain grades rewrite truck size', 'Approaches reject pure flat-suburb assumptions.'),
      b('Woodland Park multi-family is first-class product', 'Elevators and curb plans need inventories different from pure cabin lots.'),
      b('US-24 freeflow is still billable', 'Mountain-collar pairs freer mid-day still peak hard. Ask portal-to-portal.'),
    ],
    zonesHeading: 'Teller zones: Woodland Park multi-family, Divide edges, Cripple Creek tourism & rural mountain lots',
    zonesIntro: 'Two to four sharp products — multi-family growth, mountain edges, tourism stock, and rural lots.',
    zones: [
      z('woodland-park', 'Woodland Park multi-family & growth stock', 'Woodland Park', ['Woodland Park', 'growth multi-family', 'HOA edges'], 'Multi-family, HOA SFH, townhomes', ['Elevators', 'US-24 freeflow', 'HOA packets'], ['woodland park'], 'Collect HOA COIs; build US-24 buffer for El Paso pairs.'),
      z('divide', 'Divide / mountain-edge SFH', 'Divide', ['Divide', 'mountain SFH'], 'SFH, multi-family, mixed stock', ['Grades', 'Empty miles'], ['divide'], 'Photo last-mile; prefer early starts.'),
      z('cripple-creek', 'Cripple Creek tourism approaches', 'Cripple Creek', ['Cripple Creek', 'tourism multi-family'], 'Multi-story, multi-unit, tourism stock', ['Tourism peaks', 'Narrow streets', 'Grades'], ['cripple creek'], 'Book around tourism peaks; inventory stairs.'),
      z('rural-mtn', 'Rural mountain lots', 'Rural mountain', ['rural tracts', 'forest-edge lots'], 'Larger lots, mountain approaches', ['Long empty miles', 'Soft shoulders', 'Winter ice'], ['rural teller'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('cos-collar', 'US-24 COS mountain-west freeflow', 'West-collar pairs still peak hard toward El Paso.', ['Price portal-to-portal honestly.', 'Clarify Colorado Springs second addresses early.']),
      s('grades', 'Mountain grade last-mile', 'Grades rewrite flat-suburb truck assumptions.', ['Photo the final approach before promising a 26-foot truck.', 'Do not recycle Powers Blvd day rates alone.']),
      s('wp-multi', 'Woodland Park multi-family access', 'Elevators and HOA packets are first-class cost drivers.', ['Collect COI and elevator rules early.', 'Build tourism and commute peak buffers.']),
    ],
    schoolsIntro: 'Teller families compare Woodland Park RE-2, Cripple Creek-Victor, and related district feeders — verify address boundaries; do not assume El Paso maps apply.',
    hospitalsDetail: 'UCHealth Pikes Peak Regional and Colorado Springs specialty spillover serve the county; map peak US-24 times for ER access.',
    costIntro: 'Grades, multi-family access, and empty miles from Springs yards often matter more than raw miles.',
    seasonalIntro: 'Tourism summers, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'fremont-co.ts',
    exportName: 'fremontCountyCoTier2Intelligence',
    slug: 'fremont',
    hubTitle: 'Fremont County Moving Intelligence Hub',
    eyebrow: 'Fremont · Cañon City — Arkansas River valley',
    h1: 'Moving in Fremont County: Cañon City, Arkansas Valley & US-50 Access',
    heroOpener:
      'Fremont County is south-central Arkansas River valley product — Cañon City multi-story and seat stock, Florence multi-family edges, Penrose and rural valley lots, and freeflow on US-50 that is not Pueblo continuous city product with different labels. Expect tourism and institutional calendars, canyon approaches, and longer empty miles under one county. This guide is for people moving in Fremont as south-central valley secondary — not a Pueblo rename.',
    heroCredibility:
      'Arkansas Valley · Cañon City · US-50 freeflow · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-50 · CO-115 · CO-67 · CO-9 · Royal Gorge corridors',
    parentLabel: 'Pueblo County',
    parentHref: '/local-movers/colorado/pueblo',
    compareIntro:
      'Fremont is south-central Arkansas Valley multi-story product on US-50 — not Pueblo continuous industrial city density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Pueblo crews fight I-25 and city arterials. Fremont pairs ride US-50 and CO-115 — freer mid-day west of Pueblo, still peak-heavy on Cañon City arterials and tourism weekends.'),
      b('Housing stock differences', 'Pueblo mixes city multi-story and industrial-edge SFH. Fremont mixes Cañon multi-unit, Florence multi-family, and valley lots — more discontinuous valley product, less continuous industrial density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; canyon approaches rewrite truck size; rural lots add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Fremont quotes often sit at south-central secondary rates for driveway SFH — multi-story access and empty miles still push prices up.'),
      b('Role difference', 'Fremont is Arkansas Valley secondary — not Pueblo product renamed.'),
    ],
    whatIntro: 'Cañon multi-story, US-50 freeflow, and valley empty miles — not interchangeable Pueblo boilerplate.',
    whatBullets: [
      b('US-50 freeflow is still billable', 'Fremont ↔ Pueblo pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Cañon City multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('Tourism peaks rewrite weekends near gorge corridors', 'Seasonal volume stacks around major tourism windows.'),
      b('Empty miles from Pueblo yards are real', 'Even “local” Fremont pairs can price as distance work for Pueblo-based crews.'),
    ],
    zonesHeading: 'Fremont zones: Cañon multi-story, Florence multi-family, Penrose edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, multi-family edges, corridor towns, and rural lots.',
    zones: [
      z('canon-city', 'Cañon City multi-story & seat stock', 'Cañon City', ['Cañon City', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'US-50 freeflow'], ['canon city', 'cañon city'], 'Inventory stairs; plan temporary no-parking.'),
      z('florence', 'Florence multi-family edges', 'Florence', ['Florence', 'multi-family corridors'], 'Multi-family, SFH, mixed stock', ['Elevators/stairs', 'Arterial timing'], ['florence co'], 'Confirm elevator rules; prefer early starts.'),
      z('penrose', 'Penrose / CO-115 corridor edges', 'Penrose', ['Penrose', 'CO-115 multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['penrose'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-valley', 'Rural Arkansas valley lots', 'Rural valley', ['rural tracts', 'canyon approaches'], 'Larger lots, rural approaches', ['Long empty miles', 'Soft shoulders', 'Winter ice'], ['rural fremont'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('vs-pueblo', 'Fremont vs Pueblo distinction', 'Arkansas Valley product differs from continuous Pueblo industrial density.', ['Do not recycle Pueblo day rates alone.', 'Clarify Pueblo second addresses for drive-time assumptions.']),
      s('canon-seat', 'Cañon City multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('us50-freeflow', 'US-50 valley freeflow', 'Valley pairs still peak hard on arterials.', ['Price portal-to-portal honestly.', 'Build tourism-weekend buffers near gorge corridors.']),
    ],
    schoolsIntro: 'Fremont families compare Cañon City RE-1, Florence RE-2, and related district feeders — verify address boundaries; do not assume Pueblo maps apply.',
    hospitalsDetail: 'St. Thomas More Hospital and Pueblo specialty spillover serve the county; map peak US-50 times for ER access.',
    costIntro: 'Multi-story access, US-50 freeflow, and empty miles from Pueblo yards often matter more than raw miles.',
    seasonalIntro: 'Tourism summers, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'broomfield-co.ts',
    exportName: 'broomfieldCountyCoTier2Intelligence',
    slug: 'broomfield',
    hubTitle: 'Broomfield City and County Moving Intelligence Hub',
    eyebrow: 'Broomfield · north-metro city-county',
    h1: 'Moving in Broomfield: North-Metro Employment Corridors & Dual-Carriage Access',
    heroOpener:
      'Broomfield is a compact north-metro city-county — multi-family and HOA growth along US-36 / I-25 edges, employment-corridor density, and freeflow that is not Adams continuous Brighton/Commerce City product with different labels. Expect COI multi-family, HOA packets, and short but peak-heavy portal times under one consolidated jurisdiction. This guide is for people moving in Broomfield as compact north-metro product — not an Adams rename.',
    heroCredibility:
      'North-metro city-county · US-36 / I-25 corridors · Compact multi-family · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-36 · I-25 · CO-121 · CO-128 · 120th / Midway corridors',
    parentLabel: 'Adams County',
    parentHref: '/local-movers/colorado/adams',
    parentAltLabel: 'Jefferson County',
    parentAltHref: '/local-movers/colorado/jefferson',
    compareIntro:
      'Broomfield is compact north-metro multi-family/HOA city-county product — not Adams continuous north-metro industrial-residential density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Adams crews fight I-76/I-270 and Tower Road peaks. Broomfield pairs ride US-36, I-25, and Midway corridors — freer mid-day inside a compact footprint, still peak-heavy on Flatiron/US-36 commute windows.'),
      b('Housing stock differences', 'Adams mixes Brighton multi-family and industrial-edge stock. Broomfield mixes planned multi-family, HOA SFH, and employment-corridor apartments — more continuous compact north-metro product, less continuous industrial-residential fabric.'),
      b('Truck access & density', 'Multi-family elevators and HOA packets dominate; staging is compact but highly rule-bound.'),
      b('Rough cost posture (qualitative)', 'Local Broomfield quotes often track north-metro suburb rates for multi-family access — COI soft costs and peak freeflow still push prices up vs map miles alone.'),
      b('Role difference', 'Broomfield is compact north-metro city-county — not Adams product renamed.'),
    ],
    whatIntro: 'Compact multi-family COIs, US-36 freeflow, and HOA soft costs — not interchangeable Adams boilerplate.',
    whatBullets: [
      b('US-36 / I-25 peaks rewrite short-looking locals', 'Broomfield ↔ Adams/Boulder pairs freer mid-day still burn clock. Ask portal-to-portal.'),
      b('Multi-family elevators are first-class product', 'COI and elevator reservations need inventories different from pure SFH lots.'),
      b('HOA soft costs dominate planned villages', 'Gate lists and approved hours are standard survey inputs.'),
      b('Compact footprint still has empty-mile edges to Adams yards', 'Clarify staging origin on every estimate.'),
    ],
    zonesHeading: 'Broomfield zones: employment multi-family, HOA growth, US-36 corridor & open-space edges',
    zonesIntro: 'Two to four sharp products — multi-family cores, HOA growth, corridor stock, and open-space edges.',
    zones: [
      z('employment-multi', 'Employment-corridor multi-family', 'Employment multi', ['Interlocken edges', 'employment multi-family', 'apartment corridors'], 'Multi-family, elevators, townhomes', ['COI packets', 'Elevators', 'US-36 peaks'], ['broomfield multi', 'interlocken'], 'Collect elevator COIs; build commute peak buffers.'),
      z('hoa-growth', 'HOA SFH growth villages', 'HOA growth', ['planned villages', 'HOA SFH'], 'HOA SFH, townhomes', ['HOA packets', 'Cul-de-sac staging'], ['broomfield hoa'], 'Collect COI and gate lists early.'),
      z('us36-corridor', 'US-36 / Midway corridor stock', 'US-36 corridor', ['Midway multi-family', 'corridor mixed stock'], 'Multi-family, SFH, mixed stock', ['Arterial freeflow', 'Lease clusters'], ['midway broomfield'], 'Prefer early starts; confirm driveway depth.'),
      z('open-edge', 'Open-space / edge lots', 'Open edges', ['open-space edges', 'edge SFH'], 'SFH, larger lots', ['Empty miles', 'Soft shoulders'], ['edge broomfield'], 'Survey approaches; clarify Adams second addresses.'),
    ],
    specialized: [
      s('north-metro', 'Compact north-metro freeflow', 'US-36/I-25 pairs still peak hard toward Adams/Boulder/Jefferson.', ['Price portal-to-portal honestly.', 'Clarify Adams, Jefferson, or Boulder second addresses early.']),
      s('multi-coi', 'Employment multi-family COI module', 'Elevators and building packets are first-class cost drivers.', ['Collect COI and elevator reservations early.', 'Do not quote pure Adams industrial-edge rates for COI multi-family.']),
      s('hoa-soft', 'HOA soft-cost module', 'Planned villages dominate family volume.', ['Collect gate lists and approved hours before the estimate is final.', 'Saturday HOA windows push demand into peak crew slots.']),
    ],
    schoolsIntro: 'Broomfield families compare Boulder Valley, Adams 12, Jefferson County, and related district feeders that cross the city-county — verify address boundaries carefully.',
    hospitalsDetail: 'SCL Health / Intermountain Broomfield and north-metro specialty spillover serve the city-county; map peak US-36 times for ER access.',
    costIntro: 'Multi-family COIs, HOA soft costs, and US-36 freeflow often matter more than raw miles.',
    seasonalIntro: 'School years, lease ends, and winter ice reshape demand by pocket.',
  },
];
