import { type PackDef, z, s, b } from './co-tier2-render';

/** CO Tier 2 Wave 1 packs 1–6 */
export const packsA: PackDef[] = [
  {
    file: 'weld-co.ts',
    exportName: 'weldCountyCoTier2Intelligence',
    slug: 'weld',
    hubTitle: 'Weld County Moving Intelligence Hub',
    eyebrow: 'Weld · Greeley / Windsor edge — northern Front Range growth',
    h1: 'Moving in Weld County: Greeley, Windsor Edge & I-25 North Growth',
    heroOpener:
      'Weld County is northern Front Range growth and energy/ag product — Greeley multi-story and seat stock, Windsor and Firestone HOA edges, Fort Lupton and Milliken corridors, and freeflow on I-25 / US-34 / US-85 that is not Adams County Denver-north suburb product with different labels. Expect energy calendars, longer empty miles, and mixed industrial-residential fabric under one large county. This guide is for people moving in Weld as northern Front Range growth — not a Denver-suburb rename.',
    heroCredibility:
      'Northern Front Range growth · Greeley / Windsor · I-25 energy/ag · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-25 · US-34 · US-85 · CO-257 · CO-66 · CO-392',
    parentLabel: 'Adams County',
    parentHref: '/local-movers/colorado/adams',
    parentAltLabel: 'Larimer County',
    parentAltHref: '/local-movers/colorado/larimer',
    compareIntro:
      'Weld is northern Front Range energy/ag growth on I-25 — not Adams continuous Denver-north multi-family density and not pure rural plains freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Adams crews fight I-76/I-270 and Tower Road peaks into the metro. Weld pairs ride I-25, US-34, and US-85 — freer mid-day further north, still peak-heavy on Greeley arterials and Windsor commute windows. Portal-to-portal time is real; it is not a Thornton elevator day.'),
      b('Housing stock differences', 'Adams mixes Northglenn multi-family and Brighton HOAs. Weld mixes Greeley multi-story, Windsor planned SFH, and ag/industrial-edge stock — more energy-corridor product, less continuous metro density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; HOA packets dominate Windsor growth; rural eastern lots add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Weld quotes often track northern Front Range secondary rates for driveway SFH — multi-story access and long empty-mile pairs still push prices up.'),
      b('Role difference', 'Weld is northern Front Range growth collar — not Adams Denver-north product renamed.'),
    ],
    whatIntro: 'I-25 freeflow, Greeley multi-story, and Windsor HOA growth — not interchangeable Adams boilerplate.',
    whatBullets: [
      b('I-25 / US-34 peaks rewrite short-looking locals', 'Weld ↔ Adams pairs freer mid-day still burn clock. Ask portal-to-portal.'),
      b('Greeley multi-story is first-class product', 'Seat stairs need inventories different from pure Windsor cul-de-sacs.'),
      b('Energy and plant calendars reshape mid-week demand', 'Shift patterns rewrite pure Saturday residential assumptions.'),
      b('Empty miles from metro yards are real', 'Even “local” Weld pairs can price as distance work for Adams-based crews.'),
    ],
    zonesHeading: 'Weld zones: Greeley multi-story, Windsor growth, I-25 corridor towns & eastern rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, HOA growth, corridor stock, and rural lots.',
    zones: [
      z('greeley', 'Greeley multi-story & seat stock', 'Greeley', ['Greeley', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'US-34 freeflow'], ['greeley'], 'Inventory stairs; plan temporary no-parking.'),
      z('windsor', 'Windsor / Firestone HOA growth', 'Windsor growth', ['Windsor', 'Firestone', 'growth villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'I-25 peaks', 'Lease clusters'], ['windsor', 'firestone'], 'Collect HOA COIs; build I-25 buffer.'),
      z('i25-corridor', 'Fort Lupton / Milliken I-25 corridor', 'I-25 corridor', ['Fort Lupton', 'Milliken', 'Johnstown edges'], 'SFH, multi-family, mixed stock', ['Arterial timing', 'Empty miles'], ['fort lupton', 'milliken', 'johnstown'], 'Prefer early starts; confirm driveway depth.'),
      z('east-rural', 'Eastern Weld rural / ag edges', 'East rural', ['eastern tracts', 'ag-edge lots'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Winter ice'], ['east weld'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('i25-north', 'I-25 northern Front Range freeflow', 'North pairs still peak hard toward Adams/Larimer.', ['Price portal-to-portal honestly.', 'Clarify Adams or Larimer second addresses early.']),
      s('windsor-hoa', 'Windsor / Firestone HOA growth module', 'Planned suburbs dominate family volume on the west edge.', ['Collect COI and gate lists early.', 'Do not quote Greeley multi-story rates for driveway SFH.']),
      s('greeley-seat', 'Greeley multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Weld families compare Greeley-Evans, Windsor, Valley RE-1, and related district feeders — verify address boundaries; do not assume Adams or Larimer maps apply.',
    hospitalsDetail: 'UCHealth Greeley and Banner/North Colorado Medical Center campuses anchor acute care; map peak I-25 / US-34 times for ER access.',
    costIntro: 'I-25 freeflow, multi-story access, HOA soft costs, and empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, energy calendars, and winter ice reshape demand by pocket.',
  },
  {
    file: 'pueblo-co.ts',
    exportName: 'puebloCountyCoTier2Intelligence',
    slug: 'pueblo',
    hubTitle: 'Pueblo County Moving Intelligence Hub',
    eyebrow: 'Pueblo · southern Front Range independent city-region',
    h1: 'Moving in Pueblo County: Pueblo City, Industrial Edges & I-25 South Access',
    heroOpener:
      'Pueblo County is southern Front Range independent city-region product — Pueblo multi-story and seat stock, industrial-residential edges, Pueblo West growth, and freeflow on I-25 / US-50 that is not Colorado Springs El Paso product with different labels. Expect steel/industrial calendars, river-adjacent approaches, and longer empty miles under one county. This guide is for people moving in Pueblo as southern Front Range hub — not a Colorado Springs rename.',
    heroCredibility:
      'Southern Front Range independent · Pueblo city multi-story · I-25 south · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-25 · US-50 · CO-47 · Pueblo Blvd · Northern Ave corridors',
    parentLabel: 'El Paso County',
    parentHref: '/local-movers/colorado/el-paso',
    compareIntro:
      'Pueblo is southern Front Range industrial/residential independent product on I-25 — not El Paso Colorado Springs multi-family density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'El Paso crews fight I-25 peaks into Colorado Springs and Powers corridors. Pueblo pairs ride I-25 and US-50 — freer mid-day further south, still peak-heavy on Pueblo arterials and industrial shift windows.'),
      b('Housing stock differences', 'El Paso mixes Springs multi-family and north-growth HOAs. Pueblo mixes city multi-story, industrial-edge SFH, and Pueblo West planned stock — more discontinuous industrial city product, less continuous Springs growth density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; industrial streets rewrite truck type; Pueblo West HOAs add packets.'),
      b('Rough cost posture (qualitative)', 'Local Pueblo quotes often sit at southern Front Range secondary rates for driveway SFH — multi-story access and empty miles still push prices up.'),
      b('Role difference', 'Pueblo is southern Front Range independent city-region — not Colorado Springs product renamed.'),
    ],
    whatIntro: 'Industrial calendars, city multi-story, and I-25 south freeflow — not interchangeable Springs boilerplate.',
    whatBullets: [
      b('I-25 freeflow is still billable', 'Pueblo ↔ El Paso pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Pueblo multi-story is first-class product', 'Seat stairs need inventories different from Pueblo West cul-de-sacs.'),
      b('Industrial calendars reshape mid-week demand', 'Shift patterns rewrite pure Saturday residential assumptions.'),
      b('Pueblo West HOA growth differs from pure city stock', 'Gate lists and approved hours are standard survey inputs.'),
    ],
    zonesHeading: 'Pueblo zones: city multi-story, industrial edges, Pueblo West growth & rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, industrial-residential, HOA growth, and rural lots.',
    zones: [
      z('pueblo-city', 'Pueblo multi-story & seat stock', 'Pueblo city', ['Pueblo', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-25 freeflow'], ['pueblo'], 'Inventory stairs; plan temporary no-parking.'),
      z('industrial', 'Industrial-edge residential', 'Industrial edge', ['industrial multi-family', 'steel-edge SFH'], 'SFH, multi-family, mixed stock', ['Shift traffic', 'Arterial timing'], ['pueblo industrial'], 'Prefer early starts; survey last-mile on industrial streets.'),
      z('pueblo-west', 'Pueblo West HOA growth', 'Pueblo West', ['Pueblo West', 'growth villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'US-50 freeflow'], ['pueblo west'], 'Collect HOA COIs; prefer early starts.'),
      z('rural-lots', 'Southern & rural lots', 'Rural lots', ['southern tracts', 'rural approaches'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['south pueblo'], 'Photo approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('i25-south', 'I-25 southern Front Range freeflow', 'South pairs still peak hard toward El Paso.', ['Price portal-to-portal honestly.', 'Clarify Colorado Springs second addresses early.']),
      s('city-multi', 'Pueblo multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('industrial-calendars', 'Industrial calendar module', 'Plant windows reshape mid-week demand.', ['Clarify hard report dates early.', 'Do not quote pure Springs HOA Saturday rates for industrial-edge jobs.']),
    ],
    schoolsIntro: 'Pueblo families compare Pueblo City 60, Pueblo County 70, and related district feeders — verify address boundaries; do not assume El Paso maps apply.',
    hospitalsDetail: 'Parkview Medical Center and UCHealth Parkview campuses anchor acute care; map peak I-25 times for ER access.',
    costIntro: 'Multi-story access, I-25 freeflow, and industrial empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, industrial calendars, and winter ice reshape demand by pocket.',
  },
  {
    file: 'mesa-co.ts',
    exportName: 'mesaCountyCoTier2Intelligence',
    slug: 'mesa',
    hubTitle: 'Mesa County Moving Intelligence Hub',
    eyebrow: 'Mesa · Grand Junction — Western Slope hub',
    h1: 'Moving in Mesa County: Grand Junction, Western Slope Hub & I-70 West Access',
    heroOpener:
      'Mesa County is Western Slope independent hub product — Grand Junction multi-story and multi-family stock, Fruita and Clifton edges, Palisade and orchard-edge approaches, and freeflow on I-70 that is not Front Range Denver-metro product with different labels. Expect regional medical/employment calendars, desert-valley heat, and longer empty miles under one county. This guide is for people moving in Mesa as Western Slope hub — not Front Range defaults.',
    heroCredibility:
      'Western Slope independent · Grand Junction hub · I-70 west · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-70 · US-50 · US-6 · CO-340 · 24 Road / Horizon Drive corridors',
    parentLabel: 'independent Western Slope (vs Front Range defaults)',
    parentHref: '/local-movers/colorado/denver',
    compareIntro:
      'Mesa is independent Western Slope regional hub on I-70 — not Denver Front Range multi-family density and not pure mountain resort product.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Front Range crews fight I-25 metro peaks. Mesa pairs ride I-70, US-50, and local arterials — freer mid-day valley freeflow, still peak-heavy on Grand Junction arterials and Horizon Drive corridors.'),
      b('Housing stock differences', 'Denver mixes elevators and dense multi-family. Mesa mixes GJ multi-story, Fruita SFH, and orchard-edge lots — more regional hub product, less continuous metro density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; multi-family elevators appear on growth edges; rural mesas add grades and soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Mesa quotes often track Western Slope secondary rates for multi-story access — long empty-mile pairs from Front Range yards price as distance work.'),
      b('Role difference', 'Mesa is independent Western Slope hub — not Front Range product renamed.'),
    ],
    whatIntro: 'Western Slope hub multi-story, I-70 freeflow, and valley empty miles — not interchangeable Denver boilerplate.',
    whatBullets: [
      b('Grand Junction multi-story is first-class product', 'Seat stairs need inventories different from pure Fruita cul-de-sacs.'),
      b('I-70 freeflow is still billable', 'Valley pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Long empty miles from Front Range yards are real', 'Even “in-state” pairs can price as multi-day distance work.'),
      b('Desert-valley heat still governs summer open carries', 'Early starts outperform noon load-outs June–August.'),
    ],
    zonesHeading: 'Mesa zones: Grand Junction multi-story, Fruita/Clifton edges, Palisade orchard edge & rural lots',
    zonesIntro: 'Two to four sharp products — hub multi-story, edge multi-family, orchard edges, and rural lots.',
    zones: [
      z('gj-core', 'Grand Junction multi-story & multi-unit', 'Grand Junction', ['Grand Junction', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-70 freeflow'], ['grand junction'], 'Inventory stairs; plan temporary no-parking.'),
      z('fruita-clifton', 'Fruita / Clifton multi-family edges', 'Fruita / Clifton', ['Fruita', 'Clifton', 'edge multi-family'], 'SFH, multi-family, townhomes', ['HOA packets', 'Arterial timing'], ['fruita', 'clifton'], 'Collect HOA docs where applicable; prefer early starts.'),
      z('palisade', 'Palisade / orchard-edge approaches', 'Palisade', ['Palisade', 'orchard edges'], 'SFH, multi-family, mixed stock', ['Narrow approaches', 'Seasonal traffic'], ['palisade'], 'Photo last-mile; build harvest-season buffers.'),
      z('rural-lots', 'Desert mesa rural lots', 'Rural lots', ['rural tracts', 'mesa approaches'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Heat staging'], ['rural mesa'], 'Survey approaches; early starts beat heat peaks.'),
    ],
    specialized: [
      s('ws-hub', 'Western Slope hub module', 'GJ multi-story and regional employment dominate volume.', ['Inventory stairs and curb width.', 'Do not recycle Front Range day rates alone.']),
      s('i70-west', 'I-70 west freeflow', 'Valley pairs still peak hard; Front Range legs are distance work.', ['Price portal-to-portal honestly.', 'Clarify Denver second addresses for long empty-mile assumptions.']),
      s('heat-pacing', 'Desert-valley heat pacing', 'Summer open carries are first-class labor-hours drivers.', ['Prefer early starts June–August.', 'Pace crews and protect inventories.']),
    ],
    schoolsIntro: 'Mesa families compare District 51 feeders across Grand Junction, Fruita, and related communities — verify address boundaries.',
    hospitalsDetail: 'Community Hospital and St. Mary’s Medical Center anchor acute care; map peak I-70 / arterial times for ER access.',
    costIntro: 'Hub multi-story, I-70 freeflow, and long empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, harvest edges, tourism shoulders, and summer heat reshape demand by pocket.',
  },
  {
    file: 'eagle-co.ts',
    exportName: 'eagleCountyCoTier2Intelligence',
    slug: 'eagle',
    hubTitle: 'Eagle County Moving Intelligence Hub',
    eyebrow: 'Eagle · Vail / Edwards / Eagle — mountain resort corridor',
    h1: 'Moving in Eagle County: Vail, Edwards & I-70 Mountain Resort Access',
    heroOpener:
      'Eagle County is I-70 mountain resort corridor product — Vail multi-story and resort density, Edwards multi-family and HOA growth, Eagle seat stock, and freeflow that still peaks hard on winter tourism windows. Expect elevation weather, association truck limits, and seasonal calendars under one county. This guide is for people moving in Eagle as independent mountain resort — not Front Range defaults and not a Summit County rename.',
    heroCredibility:
      'I-70 resort corridor · Vail / Edwards · Seasonal logistics · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-70 · US-6 · US-24 · CO-131 · Avon Road / Edwards corridors',
    parentLabel: 'independent mountain resort (vs Front Range / Summit)',
    parentHref: '/local-movers/colorado/denver',
    parentAltLabel: 'Summit County',
    parentAltHref: '/local-movers/colorado/summit',
    compareIntro:
      'Eagle is I-70 Vail/Edwards resort-corridor product — not Denver Front Range density and not Summit high-country Breckenridge/Frisco product alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Front Range crews fight metro peaks. Eagle pairs ride I-70 mountain corridors — freer mid-day off-peak freeflow, still peak-heavy on ski weekends, pass closures, and Avon/Edwards arterials.'),
      b('Housing stock differences', 'Front Range mixes elevators and plains HOAs. Eagle mixes Vail multi-story, Edwards planned multi-family, and Eagle seat stock — more resort-association product, less continuous metro density.'),
      b('Truck access & density', 'Resort associations limit truck size; grades rewrite staging; winter chain/closure risk is first-class.'),
      b('Rough cost posture (qualitative)', 'Local Eagle quotes often track premium mountain secondary rates when associations require shuttles — clean Eagle driveway SFH can price lower than Vail multi-story jobs.'),
      b('Role difference', 'Eagle is I-70 mountain resort corridor — not Summit high-country product renamed.'),
    ],
    whatIntro: 'Resort association last-mile, I-70 mountain freeflow, and seasonal peaks — not interchangeable Summit or Front Range boilerplate.',
    whatBullets: [
      b('Ski-season peaks rewrite weekends', 'Vail/Edwards volume stacks around major tourism windows. Book early.'),
      b('Resort association access is first-class product', 'Truck limits and elevators rewrite pure driveway rates.'),
      b('I-70 mountain freeflow is still billable', 'Pass conditions and peaks rewrite short-looking pairs. Ask portal-to-portal.'),
      b('Distinct from Summit high-country product', 'Do not recycle Breckenridge/Frisco day rates alone.'),
    ],
    zonesHeading: 'Eagle zones: Vail multi-story, Edwards multi-family, Eagle seat & rural mountain lots',
    zonesIntro: 'Two to four sharp products — resort multi-story, corridor multi-family, seat stock, and rural lots.',
    zones: [
      z('vail', 'Vail multi-story & resort density', 'Vail', ['Vail', 'resort multi-family', 'village edges'], 'Multi-story, multi-unit, elevators', ['Association packets', 'Tourism peaks', 'Grades'], ['vail'], 'Collect association rules; book around peak weekends.'),
      z('edwards', 'Edwards multi-family & HOA growth', 'Edwards', ['Edwards', 'Avon edges', 'growth multi-family'], 'Multi-family, HOA SFH, townhomes', ['HOA packets', 'I-70 freeflow', 'Lease clusters'], ['edwards', 'avon'], 'Collect HOA COIs; build I-70 peak buffers.'),
      z('eagle-seat', 'Eagle seat multi-story & older stock', 'Eagle', ['Eagle', 'downtown edges'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking'], ['eagle'], 'Inventory stairs; plan temporary no-parking.'),
      z('rural-mtn', 'Rural mountain lots & Gypsum edges', 'Rural mountain', ['Gypsum edges', 'rural tracts'], 'Larger lots, mountain approaches', ['Empty miles', 'Grades', 'Winter ice'], ['gypsum', 'rural eagle'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('resort-assoc', 'Vail resort association last-mile', 'Association truck limits are first-class cost drivers.', ['Confirm size limits and elevator rules early.', 'Build tourism peak buffers.']),
      s('i70-mtn', 'I-70 mountain freeflow', 'Pass conditions rewrite freeflow assumptions.', ['Price portal-to-portal honestly.', 'Monitor closures and chain laws in season.']),
      s('vs-summit', 'Eagle vs Summit product distinction', 'I-70 Vail corridor differs from Summit high-country towns.', ['Do not recycle Breckenridge/Frisco day rates alone.', 'Clarify second-county addresses for drive-time assumptions.']),
    ],
    schoolsIntro: 'Eagle families compare Eagle County Schools feeders across Vail, Edwards, Eagle, and related communities — verify address boundaries.',
    hospitalsDetail: 'Vail Health and regional specialty spillover serve the county; map peak I-70 times for ER access.',
    costIntro: 'Association last-mile, I-70 freeflow, and seasonal peaks often matter more than raw miles.',
    seasonalIntro: 'Ski season, summer tourism, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'summit-co.ts',
    exportName: 'summitCountyCoTier2Intelligence',
    slug: 'summit',
    hubTitle: 'Summit County Moving Intelligence Hub',
    eyebrow: 'Summit · Breckenridge / Frisco / Silverthorne — high-country resorts',
    h1: 'Moving in Summit County: Breckenridge, Frisco & High-Country Resort Access',
    heroOpener:
      'Summit County is high-country resort product — Breckenridge multi-story and resort density, Frisco multi-family and lake-edge stock, Silverthorne and Dillon corridor approaches, and freeflow that still peaks hard on I-70 and CO-9 tourism windows. Expect elevation weather, association truck limits, and seasonal calendars under one county. This guide is for people moving in Summit as independent high-country resort — not an Eagle/Vail rename.',
    heroCredibility:
      'High-country resorts · Breckenridge / Frisco · Seasonal logistics · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-70 · CO-9 · US-6 · Swan Mountain Road · Main Street corridors',
    parentLabel: 'independent high-country (vs Eagle / Front Range)',
    parentHref: '/local-movers/colorado/eagle',
    parentAltLabel: 'Denver County',
    parentAltHref: '/local-movers/colorado/denver',
    compareIntro:
      'Summit is high-country Breckenridge/Frisco/Silverthorne product — not Eagle Vail/Edwards I-70 corridor product alone and not Front Range density.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Eagle crews fight Vail/Edwards I-70 peaks. Summit pairs ride I-70, CO-9, and lake-corridor arterials — freer mid-day off-peak freeflow, still peak-heavy on Breckenridge tourism weekends and Frisco arterials.'),
      b('Housing stock differences', 'Eagle mixes Vail multi-story and Edwards planned multi-family. Summit mixes Breckenridge multi-story, Frisco multi-unit, and Silverthorne corridor stock — more high-country lake-basin product, less continuous Vail village density.'),
      b('Truck access & density', 'Resort associations limit truck size; lake approaches can be narrow; winter chain/closure risk is first-class.'),
      b('Rough cost posture (qualitative)', 'Local Summit quotes often track premium high-country secondary rates when associations require shuttles — clean Frisco driveway SFH can price lower than Breckenridge multi-story jobs.'),
      b('Role difference', 'Summit is high-country multi-town resort basin — not Eagle Vail corridor renamed.'),
    ],
    whatIntro: 'High-country multi-town resort density, CO-9 freeflow, and seasonal peaks — not interchangeable Eagle boilerplate.',
    whatBullets: [
      b('Ski-season peaks rewrite weekends', 'Breckenridge/Frisco volume stacks around major tourism windows. Book early.'),
      b('Resort association access is first-class product', 'Truck limits and elevators rewrite pure driveway rates.'),
      b('Distinct from Eagle/Vail corridor product', 'Do not recycle Vail/Edwards day rates alone.'),
      b('I-70 / CO-9 freeflow is still billable', 'Pass conditions and peaks rewrite short-looking pairs. Ask portal-to-portal.'),
    ],
    zonesHeading: 'Summit zones: Breckenridge multi-story, Frisco multi-family, Silverthorne/Dillon corridors & rural lots',
    zonesIntro: 'Two to four sharp products — resort multi-story, lake multi-family, corridor stock, and rural lots.',
    zones: [
      z('breckenridge', 'Breckenridge multi-story & resort density', 'Breckenridge', ['Breckenridge', 'resort multi-family', 'village edges'], 'Multi-story, multi-unit, elevators', ['Association packets', 'Tourism peaks', 'Grades'], ['breckenridge'], 'Collect association rules; book around peak weekends.'),
      z('frisco', 'Frisco multi-family & lake-edge stock', 'Frisco', ['Frisco', 'lake multi-family', 'Main Street edges'], 'Multi-family, SFH, townhomes', ['Elevators/stairs', 'Tourism freeflow', 'Street parking'], ['frisco'], 'Confirm elevator rules; build tourism-weekend buffers.'),
      z('silverthorne', 'Silverthorne / Dillon corridor stock', 'Silverthorne / Dillon', ['Silverthorne', 'Dillon', 'corridor multi-family'], 'SFH, multi-family, mixed stock', ['I-70 freeflow', 'HOA packets'], ['silverthorne', 'dillon'], 'Collect HOA docs; prefer early starts.'),
      z('rural-high', 'Rural high-country lots', 'Rural high', ['rural tracts', 'mountain approaches'], 'Larger lots, mountain approaches', ['Empty miles', 'Grades', 'Winter ice'], ['rural summit'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('vs-eagle', 'Summit vs Eagle product distinction', 'High-country basin towns differ from Vail/Edwards corridor density.', ['Do not recycle Vail/Edwards day rates alone.', 'Clarify Eagle second addresses for drive-time assumptions.']),
      s('resort-assoc', 'Breckenridge resort association last-mile', 'Association truck limits are first-class cost drivers.', ['Confirm size limits and elevator rules early.', 'Build tourism peak buffers.']),
      s('i70-co9', 'I-70 / CO-9 freeflow', 'Pass conditions rewrite freeflow assumptions.', ['Price portal-to-portal honestly.', 'Monitor closures and chain laws in season.']),
    ],
    schoolsIntro: 'Summit families compare Summit School District feeders across Breckenridge, Frisco, Silverthorne, and related communities — verify address boundaries.',
    hospitalsDetail: 'St. Anthony Summit Medical Center and regional specialty spillover serve the county; map peak I-70 / CO-9 times for ER access.',
    costIntro: 'Association last-mile, seasonal peaks, and mountain freeflow often matter more than raw miles.',
    seasonalIntro: 'Ski season, summer tourism, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'la-plata-co.ts',
    exportName: 'laPlataCountyCoTier2Intelligence',
    slug: 'la-plata',
    hubTitle: 'La Plata County Moving Intelligence Hub',
    eyebrow: 'La Plata · Durango — southwest mountain hub',
    h1: 'Moving in La Plata County: Durango, SW Mountain Hub & US-160 Access',
    heroOpener:
      'La Plata County is southwest Colorado regional mountain hub product — Durango multi-story and multi-family stock, Bayfield and rural valley edges, tourism and university calendars, and freeflow on US-160 / US-550 that is not I-70 resort-corridor product with different labels. Expect elevation weather, longer empty miles from Front Range, and discontinuous valley approaches under one county. This guide is for people moving in La Plata as independent SW CO hub — not an I-70 resort clone.',
    heroCredibility:
      'SW CO independent · Durango hub · Tourism + residential · CO PUC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-160 · US-550 · CO-172 · CO-151 · Camino del Rio corridor',
    parentLabel: 'independent SW Colorado (vs I-70 resort defaults)',
    parentHref: '/local-movers/colorado/eagle',
    parentAltLabel: 'Denver County',
    parentAltHref: '/local-movers/colorado/denver',
    compareIntro:
      'La Plata is independent SW mountain regional hub on US-160/550 — not Eagle/Summit I-70 resort density and not Front Range multi-family.',
    compareBullets: [
      b('Drive time & corridor relationship', 'I-70 resort crews fight pass peaks into Vail/Breckenridge. La Plata pairs ride US-160 and US-550 — freer mid-day valley freeflow, still peak-heavy on Durango arterials and tourism weekends.'),
      b('Housing stock differences', 'I-70 resorts mix association multi-story and corridor multi-family. La Plata mixes Durango multi-story, Bayfield SFH, and rural valley lots — more regional hub product, less continuous ski-village density.'),
      b('Truck access & density', 'Historic streets need curb plans; multi-family elevators appear on growth edges; mountain approaches rewrite truck size.'),
      b('Rough cost posture (qualitative)', 'Local La Plata quotes often track SW secondary rates for multi-story access — long empty-mile pairs from Front Range yards price as distance work.'),
      b('Role difference', 'La Plata is independent SW mountain hub — not I-70 resort product renamed.'),
    ],
    whatIntro: 'Durango multi-story, tourism calendars, and long empty miles — not interchangeable I-70 resort boilerplate.',
    whatBullets: [
      b('Tourism peaks rewrite weekends', 'Durango volume stacks around major tourism windows. Book early.'),
      b('Durango multi-story is first-class product', 'Historic stairs need inventories different from pure Bayfield lots.'),
      b('Long empty miles from Front Range yards are real', 'Even “in-state” pairs can price as multi-day distance work.'),
      b('Distinct from I-70 resort corridor product', 'Do not recycle Vail or Breckenridge day rates alone.'),
    ],
    zonesHeading: 'La Plata zones: Durango multi-story, multi-family growth, Bayfield edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — hub multi-story, multi-family growth, edge towns, and rural lots.',
    zones: [
      z('durango', 'Durango multi-story & seat stock', 'Durango', ['Durango', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Tourism peaks'], ['durango'], 'Inventory stairs; avoid peak tourism weekends when possible.'),
      z('multi-growth', 'Durango multi-family growth edges', 'Multi-family growth', ['growth multi-family', 'university edges'], 'Multi-family, apartments, townhomes', ['Elevators', 'Lease clusters', 'COI packets'], ['durango multi'], 'Collect building rules; book around term and tourism windows.'),
      z('bayfield', 'Bayfield / valley-edge SFH', 'Bayfield', ['Bayfield', 'valley SFH'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['bayfield'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-valley', 'Rural SW valley lots', 'Rural valley', ['rural tracts', 'mountain approaches'], 'Larger lots, rural approaches', ['Long empty miles', 'Soft shoulders', 'Winter ice'], ['rural la plata'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('sw-hub', 'Durango SW mountain hub module', 'Hub multi-story and tourism calendars dominate volume.', ['Inventory stairs and curb width.', 'Do not recycle I-70 resort day rates alone.']),
      s('tourism-peaks', 'Tourism peak module', 'Seasonal weekends rewrite staging.', ['Book capacity early for peak seasons.', 'Build arterial buffers for festival windows.']),
      s('long-empty', 'Front Range long empty-mile module', 'In-state pairs can still be distance work.', ['Price portal-to-portal from Front Range staging honestly.', 'Clarify Denver second addresses for drive-time assumptions.']),
    ],
    schoolsIntro: 'La Plata families compare Durango 9-R, Bayfield 10 Jt-R, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Mercy Hospital and regional specialty spillover serve the county; map peak US-160 / US-550 times for ER access.',
    costIntro: 'Hub multi-story, tourism peaks, and long empty miles often matter more than raw miles.',
    seasonalIntro: 'Tourism summers, school years, and winter ice reshape demand by pocket.',
  },
];
