$outDir = Join-Path $PSScriptRoot 'nebraska-batch2-output'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

function Quote-Ts([string]$s) {
  if ($s -match "'") { return '"' + $s + '"' }
  return "'" + $s + "'"
}

$counties = @(
  @{ slug='colfax'; city='Schuyler'; citySlug='schuyler'; label='Schuyler Metro'; poolId='colfax-metro-ne'; regional1='schuyler-corridor'; regional2='platte-river-upper'; topId='regional-colfax-ne-movers'; topName='Regional Schuyler / Colfax Providers'; topDesc='Reliable movers serving Colfax County residential needs across Schuyler and upper Platte River corridor communities.'; countyMovingName='Colfax County Moving'; regional1Name='Schuyler Corridor Moving'; regional2Name='Platte River Upper Moving'; countyLabel='Colfax County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='custer'; city='Broken Bow'; citySlug='broken-bow'; label='Broken Bow Metro'; poolId='custer-metro-ne'; regional1='broken-bow-corridor'; regional2='sandhills-central'; topId='regional-custer-ne-movers'; topName='Regional Broken Bow / Custer Providers'; topDesc='Reliable movers serving Custer County, NE residential needs across Broken Bow and central Sandhills communities.'; countyMovingName='Custer County Moving'; regional1Name='Broken Bow Corridor Moving'; regional2Name='Sandhills Central Moving'; countyLabel='Custer County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='box-butte'; city='Alliance'; citySlug='alliance'; label='Alliance Metro'; poolId='box-butte-metro-ne'; regional1='alliance-corridor'; regional2='panhandle-north'; topId='regional-boxbutte-ne-movers'; topName='Regional Alliance / Box Butte Providers'; topDesc='Reliable movers serving Box Butte County, NE residential needs across Alliance and northern Panhandle communities.'; countyMovingName='Box Butte County Moving'; regional1Name='Alliance Corridor Moving'; regional2Name='Panhandle North Moving'; countyLabel='Box Butte County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='red-willow'; city='McCook'; citySlug='mccook'; label='McCook Metro'; poolId='red-willow-metro-ne'; regional1='mccook-corridor'; regional2='republican-river-southwest'; topId='regional-redwillow-ne-movers'; topName='Regional McCook / Red Willow Providers'; topDesc='Reliable movers serving Red Willow County, NE residential needs across McCook and southwestern Republican River valley communities.'; countyMovingName='Red Willow County Moving'; regional1Name='McCook Corridor Moving'; regional2Name='Republican River Southwest Moving'; countyLabel='Red Willow County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='wayne'; city='Wayne'; citySlug='wayne'; label='Wayne Metro'; poolId='wayne-metro-ne'; regional1='wayne-corridor'; regional2='elkhorn-valley-east'; topId='regional-wayne-ne-movers'; topName='Regional Wayne / Wayne Providers'; topDesc='Reliable movers serving Wayne County, NE residential needs across Wayne and eastern Elkhorn Valley communities.'; countyMovingName='Wayne County Moving'; regional1Name='Wayne Corridor Moving'; regional2Name='Elkhorn Valley East Moving'; countyLabel='Wayne County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='holt'; city="O'Neill"; citySlug='oneill'; label="O'Neill Metro"; poolId='holt-metro-ne'; regional1='oneill-corridor'; regional2='niobrara-plateau'; topId='regional-holt-ne-movers'; topName="Regional O'Neill / Holt Providers"; topDesc="Reliable movers serving Holt County residential needs across O'Neill and Niobrara plateau communities."; countyMovingName='Holt County Moving'; regional1Name="O'Neill Corridor Moving"; regional2Name='Niobrara Plateau Moving'; countyLabel='Holt County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='hamilton'; city='Aurora'; citySlug='aurora'; label='Aurora Metro'; poolId='hamilton-metro-ne'; regional1='aurora-corridor'; regional2='platte-valley-east'; topId='regional-hamilton-ne-movers'; topName='Regional Aurora / Hamilton Providers'; topDesc='Reliable movers serving Hamilton County, NE residential needs across Aurora and eastern Platte Valley communities.'; countyMovingName='Hamilton County Moving'; regional1Name='Aurora Corridor Moving'; regional2Name='Platte Valley East Moving'; countyLabel='Hamilton County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='cheyenne'; city='Sidney'; citySlug='sidney'; label='Sidney Metro'; poolId='cheyenne-metro-ne'; regional1='sidney-corridor'; regional2='high-plains-east'; topId='regional-cheyenne-ne-movers'; topName='Regional Sidney / Cheyenne Providers'; topDesc='Reliable movers serving Cheyenne County, NE residential needs across Sidney and eastern High Plains communities.'; countyMovingName='Cheyenne County Moving'; regional1Name='Sidney Corridor Moving'; regional2Name='High Plains East Moving'; countyLabel='Cheyenne County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='phelps'; city='Holdrege'; citySlug='holdrege'; label='Holdrege Metro'; poolId='phelps-metro-ne'; regional1='holdrege-corridor'; regional2='platte-valley-south'; topId='regional-phelps-ne-movers'; topName='Regional Holdrege / Phelps Providers'; topDesc='Reliable movers serving Phelps County residential needs across Holdrege and southern Platte Valley communities.'; countyMovingName='Phelps County Moving'; regional1Name='Holdrege Corridor Moving'; regional2Name='Platte Valley South Moving'; countyLabel='Phelps County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='cuming'; city='West Point'; citySlug='west-point'; label='West Point Metro'; poolId='cuming-metro-ne'; regional1='west-point-corridor'; regional2='elkhorn-river-mid'; topId='regional-cuming-ne-movers'; topName='Regional West Point / Cuming Providers'; topDesc='Reliable movers serving Cuming County residential needs across West Point and mid Elkhorn River corridor communities.'; countyMovingName='Cuming County Moving'; regional1Name='West Point Corridor Moving'; regional2Name='Elkhorn River Mid Moving'; countyLabel='Cuming County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='butler'; city='David City'; citySlug='david-city'; label='David City Metro'; poolId='butler-metro-ne'; regional1='david-city-corridor'; regional2='platte-river-mid'; topId='regional-butler-ne-movers'; topName='Regional David City / Butler Providers'; topDesc='Reliable movers serving Butler County, NE residential needs across David City and mid Platte River corridor communities.'; countyMovingName='Butler County Moving'; regional1Name='David City Corridor Moving'; regional2Name='Platte River Mid Moving'; countyLabel='Butler County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='cedar'; city='Hartington'; citySlug='hartington'; label='Hartington Metro'; poolId='cedar-metro-ne'; regional1='hartington-corridor'; regional2='missouri-bluff-north'; topId='regional-cedar-ne-movers'; topName='Regional Hartington / Cedar Providers'; topDesc='Reliable movers serving Cedar County residential needs across Hartington and northern Missouri River bluff communities.'; countyMovingName='Cedar County Moving'; regional1Name='Hartington Corridor Moving'; regional2Name='Missouri Bluff North Moving'; countyLabel='Cedar County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='knox'; city='Center'; citySlug='center'; label='Center Metro'; poolId='knox-metro-ne'; regional1='center-corridor'; regional2='missouri-plateau'; topId='regional-knox-ne-movers'; topName='Regional Center / Knox Providers'; topDesc='Reliable movers serving Knox County residential needs across Center and Missouri plateau communities.'; countyMovingName='Knox County Moving'; regional1Name='Center Corridor Moving'; regional2Name='Missouri Plateau Moving'; countyLabel='Knox County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='keith'; city='Ogallala'; citySlug='ogallala'; label='Ogallala Metro'; poolId='keith-metro-ne'; regional1='ogallala-corridor'; regional2='north-platte-valley-mid'; topId='regional-keith-ne-movers'; topName='Regional Ogallala / Keith Providers'; topDesc='Reliable movers serving Keith County residential needs across Ogallala and mid North Platte Valley communities.'; countyMovingName='Keith County Moving'; regional1Name='Ogallala Corridor Moving'; regional2Name='North Platte Valley Mid Moving'; countyLabel='Keith County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='merrick'; city='Central City'; citySlug='central-city'; label='Central City Metro'; poolId='merrick-metro-ne'; regional1='central-city-corridor'; regional2='loup-river-upper'; topId='regional-merrick-ne-movers'; topName='Regional Central City / Merrick Providers'; topDesc='Reliable movers serving Merrick County residential needs across Central City and upper Loup River valley communities.'; countyMovingName='Merrick County Moving'; regional1Name='Central City Corridor Moving'; regional2Name='Loup River Upper Moving'; countyLabel='Merrick County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='dawes'; city='Chadron'; citySlug='chadron'; label='Chadron Metro'; poolId='dawes-metro-ne'; regional1='chadron-corridor'; regional2='pine-ridge-foothills'; topId='regional-dawes-ne-movers'; topName='Regional Chadron / Dawes Providers'; topDesc='Reliable movers serving Dawes County residential needs across Chadron and Pine Ridge foothills communities.'; countyMovingName='Dawes County Moving'; regional1Name='Chadron Corridor Moving'; regional2Name='Pine Ridge Foothills Moving'; countyLabel='Dawes County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='richardson'; city='Falls City'; citySlug='falls-city'; label='Falls City Metro'; poolId='richardson-metro-ne'; regional1='falls-city-corridor'; regional2='nemaha-river-valley'; topId='regional-richardson-ne-movers'; topName='Regional Falls City / Richardson Providers'; topDesc='Reliable movers serving Richardson County residential needs across Falls City and Nemaha River valley communities.'; countyMovingName='Richardson County Moving'; regional1Name='Falls City Corridor Moving'; regional2Name='Nemaha River Valley Moving'; countyLabel='Richardson County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='pierce'; city='Pierce'; citySlug='pierce'; label='Pierce Metro'; poolId='pierce-metro-ne'; regional1='pierce-corridor'; regional2='elkhorn-valley-central'; topId='regional-pierce-ne-movers'; topName='Regional Pierce / Pierce Providers'; topDesc='Reliable movers serving Pierce County, NE residential needs across Pierce and central Elkhorn Valley communities.'; countyMovingName='Pierce County Moving'; regional1Name='Pierce Corridor Moving'; regional2Name='Elkhorn Valley Central Moving'; countyLabel='Pierce County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='nemaha'; city='Auburn'; citySlug='auburn'; label='Auburn Metro'; poolId='nemaha-metro-ne'; regional1='auburn-corridor'; regional2='nemaha-river-basin'; topId='regional-nemaha-ne-movers'; topName='Regional Auburn / Nemaha Providers'; topDesc='Reliable movers serving Nemaha County, NE residential needs across Auburn and Nemaha River basin communities.'; countyMovingName='Nemaha County Moving'; regional1Name='Auburn Corridor Moving'; regional2Name='Nemaha River Basin Moving'; countyLabel='Nemaha County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='jefferson'; city='Fairbury'; citySlug='fairbury'; label='Fairbury Metro'; poolId='jefferson-metro-ne'; regional1='fairbury-corridor'; regional2='little-blue-valley'; topId='regional-jefferson-ne-movers'; topName='Regional Fairbury / Jefferson Providers'; topDesc='Reliable movers serving Jefferson County, NE residential needs across Fairbury and Little Blue River valley communities.'; countyMovingName='Jefferson County Moving'; regional1Name='Fairbury Corridor Moving'; regional2Name='Little Blue Valley Moving'; countyLabel='Jefferson County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='thurston'; city='Pender'; citySlug='pender'; label='Pender Metro'; poolId='thurston-metro-ne'; regional1='pender-corridor'; regional2='omaha-nation-corridor'; topId='regional-thurston-ne-movers'; topName='Regional Pender / Thurston Providers'; topDesc='Reliable movers serving Thurston County residential needs across Pender and Omaha Nation corridor communities.'; countyMovingName='Thurston County Moving'; regional1Name='Pender Corridor Moving'; regional2Name='Omaha Nation Corridor Moving'; countyLabel='Thurston County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='kearney'; city='Minden'; citySlug='minden'; label='Minden Metro'; poolId='kearney-metro-ne'; regional1='minden-corridor'; regional2='platte-valley-lower'; topId='regional-kearney-ne-movers'; topName='Regional Minden / Kearney County Providers'; topDesc='Reliable movers serving Kearney County, NE residential needs across Minden and lower Platte Valley communities.'; countyMovingName='Kearney County Moving'; regional1Name='Minden Corridor Moving'; regional2Name='Platte Valley Lower Moving'; countyLabel='Kearney County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='burt'; city='Tekamah'; citySlug='tekamah'; label='Tekamah Metro'; poolId='burt-metro-ne'; regional1='tekamah-corridor'; regional2='missouri-bluff-west'; topId='regional-burt-ne-movers'; topName='Regional Tekamah / Burt Providers'; topDesc='Reliable movers serving Burt County residential needs across Tekamah and western Missouri River bluff communities.'; countyMovingName='Burt County Moving'; regional1Name='Tekamah Corridor Moving'; regional2Name='Missouri Bluff West Moving'; countyLabel='Burt County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='howard'; city='St. Paul'; citySlug='st-paul'; label='St. Paul Metro'; poolId='howard-metro-ne'; regional1='st-paul-corridor'; regional2='loup-river-mid'; topId='regional-howard-ne-movers'; topName='Regional St. Paul / Howard Providers'; topDesc='Reliable movers serving Howard County residential needs across St. Paul and mid Loup River valley communities.'; countyMovingName='Howard County Moving'; regional1Name='St. Paul Corridor Moving'; regional2Name='Loup River Mid Moving'; countyLabel='Howard County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='antelope'; city='Neligh'; citySlug='neligh'; label='Neligh Metro'; poolId='antelope-metro-ne'; regional1='neligh-corridor'; regional2='elkhorn-valley-south'; topId='regional-antelope-ne-movers'; topName='Regional Neligh / Antelope Providers'; topDesc='Reliable movers serving Antelope County residential needs across Neligh and southern Elkhorn Valley communities.'; countyMovingName='Antelope County Moving'; regional1Name='Neligh Corridor Moving'; regional2Name='Elkhorn Valley South Moving'; countyLabel='Antelope County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='clay'; city='Clay Center'; citySlug='clay-center'; label='Clay Center Metro'; poolId='clay-metro-ne'; regional1='clay-center-corridor'; regional2='republican-river-upper'; topId='regional-clay-ne-movers'; topName='Regional Clay Center / Clay Providers'; topDesc='Reliable movers serving Clay County, NE residential needs across Clay Center and upper Republican River valley communities.'; countyMovingName='Clay County Moving'; regional1Name='Clay Center Corridor Moving'; regional2Name='Republican River Upper Moving'; countyLabel='Clay County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='stanton'; city='Stanton'; citySlug='stanton'; label='Stanton Metro'; poolId='stanton-metro-ne'; regional1='stanton-corridor'; regional2='elkhorn-river-south'; topId='regional-stanton-ne-movers'; topName='Regional Stanton / Stanton Providers'; topDesc='Reliable movers serving Stanton County, NE residential needs across Stanton and southern Elkhorn River corridor communities.'; countyMovingName='Stanton County Moving'; regional1Name='Stanton Corridor Moving'; regional2Name='Elkhorn River South Moving'; countyLabel='Stanton County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='dixon'; city='Ponca'; citySlug='ponca'; label='Ponca Metro'; poolId='dixon-metro-ne'; regional1='ponca-corridor'; regional2='missouri-river-northwest'; topId='regional-dixon-ne-movers'; topName='Regional Ponca / Dixon Providers'; topDesc='Reliable movers serving Dixon County residential needs across Ponca and northwestern Missouri River corridor communities.'; countyMovingName='Dixon County Moving'; regional1Name='Ponca Corridor Moving'; regional2Name='Missouri River Northwest Moving'; countyLabel='Dixon County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='cherry'; city='Valentine'; citySlug='valentine'; label='Valentine Metro'; poolId='cherry-metro-ne'; regional1='valentine-corridor'; regional2='sandhills-north'; topId='regional-cherry-ne-movers'; topName='Regional Valentine / Cherry Providers'; topDesc='Reliable movers serving Cherry County residential needs across Valentine and northern Sandhills communities.'; countyMovingName='Cherry County Moving'; regional1Name='Valentine Corridor Moving'; regional2Name='Sandhills North Moving'; countyLabel='Cherry County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='fillmore'; city='Geneva'; citySlug='geneva'; label='Geneva Metro'; poolId='fillmore-metro-ne'; regional1='geneva-corridor'; regional2='big-blue-west'; topId='regional-fillmore-ne-movers'; topName='Regional Geneva / Fillmore Providers'; topDesc='Reliable movers serving Fillmore County residential needs across Geneva and western Big Blue River valley communities.'; countyMovingName='Fillmore County Moving'; regional1Name='Geneva Corridor Moving'; regional2Name='Big Blue West Moving'; countyLabel='Fillmore County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='boone'; city='Albion'; citySlug='albion'; label='Albion Metro'; poolId='boone-metro-ne'; regional1='albion-corridor'; regional2='elkhorn-river-basin'; topId='regional-boone-ne-movers'; topName='Regional Albion / Boone Providers'; topDesc='Reliable movers serving Boone County, NE residential needs across Albion and Elkhorn River basin communities.'; countyMovingName='Boone County Moving'; regional1Name='Albion Corridor Moving'; regional2Name='Elkhorn River Basin Moving'; countyLabel='Boone County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='polk'; city='Osceola'; citySlug='osceola'; label='Osceola Metro'; poolId='polk-metro-ne'; regional1='osceola-corridor'; regional2='platte-river-looped'; topId='regional-polk-ne-movers'; topName='Regional Osceola / Polk Providers'; topDesc='Reliable movers serving Polk County, NE residential needs across Osceola and looped Platte River corridor communities.'; countyMovingName='Polk County Moving'; regional1Name='Osceola Corridor Moving'; regional2Name='Platte River Looped Moving'; countyLabel='Polk County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='johnson'; city='Tecumseh'; citySlug='tecumseh'; label='Tecumseh Metro'; poolId='johnson-metro-ne'; regional1='tecumseh-corridor'; regional2='indian-creek-valley'; topId='regional-johnson-ne-movers'; topName='Regional Tecumseh / Johnson Providers'; topDesc='Reliable movers serving Johnson County, NE residential needs across Tecumseh and Indian Creek valley communities.'; countyMovingName='Johnson County Moving'; regional1Name='Tecumseh Corridor Moving'; regional2Name='Indian Creek Valley Moving'; countyLabel='Johnson County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='thayer'; city='Hebron'; citySlug='hebron'; label='Hebron Metro'; poolId='thayer-metro-ne'; regional1='hebron-corridor'; regional2='little-blue-south'; topId='regional-thayer-ne-movers'; topName='Regional Hebron / Thayer Providers'; topDesc='Reliable movers serving Thayer County residential needs across Hebron and southern Little Blue River valley communities.'; countyMovingName='Thayer County Moving'; regional1Name='Hebron Corridor Moving'; regional2Name='Little Blue South Moving'; countyLabel='Thayer County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='arthur'; city='Arthur'; citySlug='arthur'; label='Arthur Metro'; poolId='arthur-metro-ne'; regional1='arthur-corridor'; regional2='sandhills-east'; topId='regional-arthur-ne-movers'; topName='Regional Arthur / Arthur Providers'; topDesc='Reliable movers serving Arthur County residential needs across Arthur and eastern Sandhills communities.'; countyMovingName='Arthur County Moving'; regional1Name='Arthur Corridor Moving'; regional2Name='Sandhills East Moving'; countyLabel='Arthur County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='banner'; city='Harrisburg'; citySlug='harrisburg'; label='Harrisburg Metro'; poolId='banner-metro-ne'; regional1='harrisburg-corridor'; regional2='panhandle-gateway'; topId='regional-banner-ne-movers'; topName='Regional Harrisburg / Banner Providers'; topDesc='Reliable movers serving Banner County residential needs across Harrisburg and Panhandle gateway communities.'; countyMovingName='Banner County Moving'; regional1Name='Harrisburg Corridor Moving'; regional2Name='Panhandle Gateway Moving'; countyLabel='Banner County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='blaine'; city='Brewster'; citySlug='brewster'; label='Brewster Metro'; poolId='blaine-metro-ne'; regional1='brewster-corridor'; regional2='sandhills-northeast'; topId='regional-blaine-ne-movers'; topName='Regional Brewster / Blaine Providers'; topDesc='Reliable movers serving Blaine County residential needs across Brewster and northeastern Sandhills communities.'; countyMovingName='Blaine County Moving'; regional1Name='Brewster Corridor Moving'; regional2Name='Sandhills Northeast Moving'; countyLabel='Blaine County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='boyd'; city='Butte'; citySlug='butte'; label='Butte Metro'; poolId='boyd-metro-ne'; regional1='butte-corridor'; regional2='missouri-niobrara'; topId='regional-boyd-ne-movers'; topName='Regional Butte / Boyd Providers'; topDesc='Reliable movers serving Boyd County residential needs across Butte and Missouri-Niobrara confluence communities.'; countyMovingName='Boyd County Moving'; regional1Name='Butte Corridor Moving'; regional2Name='Missouri Niobrara Moving'; countyLabel='Boyd County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='brown'; city='Ainsworth'; citySlug='ainsworth'; label='Ainsworth Metro'; poolId='brown-metro-ne'; regional1='ainsworth-corridor'; regional2='niobrara-valley'; topId='regional-brown-ne-movers'; topName='Regional Ainsworth / Brown Providers'; topDesc='Reliable movers serving Brown County, NE residential needs across Ainsworth and Niobrara River valley communities.'; countyMovingName='Brown County Moving'; regional1Name='Ainsworth Corridor Moving'; regional2Name='Niobrara Valley Moving'; countyLabel='Brown County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='chase'; city='Imperial'; citySlug='imperial'; label='Imperial Metro'; poolId='chase-metro-ne'; regional1='imperial-corridor'; regional2='republican-river-mid'; topId='regional-chase-ne-movers'; topName='Regional Imperial / Chase Providers'; topDesc='Reliable movers serving Chase County residential needs across Imperial and mid Republican River valley communities.'; countyMovingName='Chase County Moving'; regional1Name='Imperial Corridor Moving'; regional2Name='Republican River Mid Moving'; countyLabel='Chase County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='deuel'; city='Chappell'; citySlug='chappell'; label='Chappell Metro'; poolId='deuel-metro-ne'; regional1='chappell-corridor'; regional2='high-plains-southwest'; topId='regional-deuel-ne-movers'; topName='Regional Chappell / Deuel Providers'; topDesc='Reliable movers serving Deuel County residential needs across Chappell and southwestern High Plains communities.'; countyMovingName='Deuel County Moving'; regional1Name='Chappell Corridor Moving'; regional2Name='High Plains Southwest Moving'; countyLabel='Deuel County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='dundy'; city='Benkelman'; citySlug='benkelman'; label='Benkelman Metro'; poolId='dundy-metro-ne'; regional1='benkelman-corridor'; regional2='republican-river-far-west'; topId='regional-dundy-ne-movers'; topName='Regional Benkelman / Dundy Providers'; topDesc='Reliable movers serving Dundy County residential needs across Benkelman and far western Republican River valley communities.'; countyMovingName='Dundy County Moving'; regional1Name='Benkelman Corridor Moving'; regional2Name='Republican River Far West Moving'; countyLabel='Dundy County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='franklin'; city='Franklin'; citySlug='franklin'; label='Franklin Metro'; poolId='franklin-metro-ne'; regional1='franklin-corridor'; regional2='republican-river-lower'; topId='regional-franklin-ne-movers'; topName='Regional Franklin / Franklin Providers'; topDesc='Reliable movers serving Franklin County, NE residential needs across Franklin and lower Republican River valley communities.'; countyMovingName='Franklin County Moving'; regional1Name='Franklin Corridor Moving'; regional2Name='Republican River Lower Moving'; countyLabel='Franklin County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='frontier'; city='Stockville'; citySlug='stockville'; label='Stockville Metro'; poolId='frontier-metro-ne'; regional1='stockville-corridor'; regional2='republican-river-upper-mid'; topId='regional-frontier-ne-movers'; topName='Regional Stockville / Frontier Providers'; topDesc='Reliable movers serving Frontier County residential needs across Stockville and upper mid Republican River valley communities.'; countyMovingName='Frontier County Moving'; regional1Name='Stockville Corridor Moving'; regional2Name='Republican River Upper Mid Moving'; countyLabel='Frontier County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='furnas'; city='Beaver City'; citySlug='beaver-city'; label='Beaver City Metro'; poolId='furnas-metro-ne'; regional1='beaver-city-corridor'; regional2='republican-river-central'; topId='regional-furnas-ne-movers'; topName='Regional Beaver City / Furnas Providers'; topDesc='Reliable movers serving Furnas County residential needs across Beaver City and central Republican River valley communities.'; countyMovingName='Furnas County Moving'; regional1Name='Beaver City Corridor Moving'; regional2Name='Republican River Central Moving'; countyLabel='Furnas County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='garden'; city='Oshkosh'; citySlug='oshkosh'; label='Oshkosh Metro'; poolId='garden-metro-ne'; regional1='oshkosh-corridor'; regional2='north-platte-valley-north'; topId='regional-garden-ne-movers'; topName='Regional Oshkosh / Garden Providers'; topDesc='Reliable movers serving Garden County residential needs across Oshkosh and northern North Platte Valley communities.'; countyMovingName='Garden County Moving'; regional1Name='Oshkosh Corridor Moving'; regional2Name='North Platte Valley North Moving'; countyLabel='Garden County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='garfield'; city='Burwell'; citySlug='burwell'; label='Burwell Metro'; poolId='garfield-metro-ne'; regional1='burwell-corridor'; regional2='sandhills-loup'; topId='regional-garfield-ne-movers'; topName='Regional Burwell / Garfield Providers'; topDesc='Reliable movers serving Garfield County, NE residential needs across Burwell and Sandhills-Loup divide communities.'; countyMovingName='Garfield County Moving'; regional1Name='Burwell Corridor Moving'; regional2Name='Sandhills Loup Moving'; countyLabel='Garfield County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='gosper'; city='Elwood'; citySlug='elwood'; label='Elwood Metro'; poolId='gosper-metro-ne'; regional1='elwood-corridor'; regional2='platte-valley-southwest'; topId='regional-gosper-ne-movers'; topName='Regional Elwood / Gosper Providers'; topDesc='Reliable movers serving Gosper County residential needs across Elwood and southwestern Platte Valley communities.'; countyMovingName='Gosper County Moving'; regional1Name='Elwood Corridor Moving'; regional2Name='Platte Valley Southwest Moving'; countyLabel='Gosper County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='grant'; city='Hyannis'; citySlug='hyannis'; label='Hyannis Metro'; poolId='grant-metro-ne'; regional1='hyannis-corridor'; regional2='sandhills-grant'; topId='regional-grant-ne-movers'; topName='Regional Hyannis / Grant Providers'; topDesc='Reliable movers serving Grant County, NE residential needs across Hyannis and Grant County Sandhills communities.'; countyMovingName='Grant County Moving'; regional1Name='Hyannis Corridor Moving'; regional2Name='Sandhills Grant Moving'; countyLabel='Grant County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='greeley'; city='Greeley'; citySlug='greeley'; label='Greeley Metro'; poolId='greeley-metro-ne'; regional1='greeley-corridor'; regional2='sandhills-central-north'; topId='regional-greeley-ne-movers'; topName='Regional Greeley / Greeley Providers'; topDesc='Reliable movers serving Greeley County, NE residential needs across Greeley and north central Sandhills communities.'; countyMovingName='Greeley County Moving'; regional1Name='Greeley Corridor Moving'; regional2Name='Sandhills Central North Moving'; countyLabel='Greeley County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='harlan'; city='Alma'; citySlug='alma'; label='Alma Metro'; poolId='harlan-metro-ne'; regional1='alma-corridor'; regional2='republican-river-harlan'; topId='regional-harlan-ne-movers'; topName='Regional Alma / Harlan Providers'; topDesc='Reliable movers serving Harlan County, NE residential needs across Alma and Republican River Harlan basin communities.'; countyMovingName='Harlan County Moving'; regional1Name='Alma Corridor Moving'; regional2Name='Republican River Harlan Moving'; countyLabel='Harlan County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='hayes'; city='Hayes Center'; citySlug='hayes-center'; label='Hayes Center Metro'; poolId='hayes-metro-ne'; regional1='hayes-center-corridor'; regional2='platte-valley-hayes'; topId='regional-hayes-ne-movers'; topName='Regional Hayes Center / Hayes Providers'; topDesc='Reliable movers serving Hayes County residential needs across Hayes Center and Platte Valley Hayes corridor communities.'; countyMovingName='Hayes County Moving'; regional1Name='Hayes Center Corridor Moving'; regional2Name='Platte Valley Hayes Moving'; countyLabel='Hayes County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='hitchcock'; city='Trenton'; citySlug='trenton'; label='Trenton Metro'; poolId='hitchcock-metro-ne'; regional1='trenton-corridor'; regional2='republican-river-hitchcock'; topId='regional-hitchcock-ne-movers'; topName='Regional Trenton / Hitchcock Providers'; topDesc='Reliable movers serving Hitchcock County residential needs across Trenton and Republican River Hitchcock basin communities.'; countyMovingName='Hitchcock County Moving'; regional1Name='Trenton Corridor Moving'; regional2Name='Republican River Hitchcock Moving'; countyLabel='Hitchcock County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='hooker'; city='Mullen'; citySlug='mullen'; label='Mullen Metro'; poolId='hooker-metro-ne'; regional1='mullen-corridor'; regional2='sandhills-hooker'; topId='regional-hooker-ne-movers'; topName='Regional Mullen / Hooker Providers'; topDesc='Reliable movers serving Hooker County residential needs across Mullen and Hooker County Sandhills communities.'; countyMovingName='Hooker County Moving'; regional1Name='Mullen Corridor Moving'; regional2Name='Sandhills Hooker Moving'; countyLabel='Hooker County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='keya-paha'; city='Springview'; citySlug='springview'; label='Springview Metro'; poolId='keya-paha-metro-ne'; regional1='springview-corridor'; regional2='niobrara-keya-paha'; topId='regional-keyapaha-ne-movers'; topName='Regional Springview / Keya Paha Providers'; topDesc='Reliable movers serving Keya Paha County residential needs across Springview and Niobrara-Keya Paha valley communities.'; countyMovingName='Keya Paha County Moving'; regional1Name='Springview Corridor Moving'; regional2Name='Niobrara Keya Paha Moving'; countyLabel='Keya Paha County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='kimball'; city='Kimball'; citySlug='kimball'; label='Kimball Metro'; poolId='kimball-metro-ne'; regional1='kimball-corridor'; regional2='high-plains-kimball'; topId='regional-kimball-ne-movers'; topName='Regional Kimball / Kimball Providers'; topDesc='Reliable movers serving Kimball County, NE residential needs across Kimball and Kimball High Plains communities.'; countyMovingName='Kimball County Moving'; regional1Name='Kimball Corridor Moving'; regional2Name='High Plains Kimball Moving'; countyLabel='Kimball County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='logan'; city='Stapleton'; citySlug='stapleton'; label='Stapleton Metro'; poolId='logan-metro-ne'; regional1='stapleton-corridor'; regional2='sandhills-logan'; topId='regional-logan-ne-movers'; topName='Regional Stapleton / Logan Providers'; topDesc='Reliable movers serving Logan County, NE residential needs across Stapleton and Logan County Sandhills communities.'; countyMovingName='Logan County Moving'; regional1Name='Stapleton Corridor Moving'; regional2Name='Sandhills Logan Moving'; countyLabel='Logan County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='loup'; city='Taylor'; citySlug='taylor'; label='Taylor Metro'; poolId='loup-metro-ne'; regional1='taylor-corridor'; regional2='loup-river-lower'; topId='regional-loup-ne-movers'; topName='Regional Taylor / Loup Providers'; topDesc='Reliable movers serving Loup County residential needs across Taylor and lower Loup River valley communities.'; countyMovingName='Loup County Moving'; regional1Name='Taylor Corridor Moving'; regional2Name='Loup River Lower Moving'; countyLabel='Loup County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='mcpherson'; city='Tryon'; citySlug='tryon'; label='Tryon Metro'; poolId='mcpherson-metro-ne'; regional1='tryon-corridor'; regional2='sandhills-mcpherson'; topId='regional-mcpherson-ne-movers'; topName='Regional Tryon / McPherson Providers'; topDesc='Reliable movers serving McPherson County residential needs across Tryon and McPherson County Sandhills communities.'; countyMovingName='McPherson County Moving'; regional1Name='Tryon Corridor Moving'; regional2Name='Sandhills McPherson Moving'; countyLabel='McPherson County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='morrill'; city='Bridgeport'; citySlug='bridgeport'; label='Bridgeport Metro'; poolId='morrill-metro-ne'; regional1='bridgeport-corridor'; regional2='north-platte-scottsbluff-east'; topId='regional-morrill-ne-movers'; topName='Regional Bridgeport / Morrill Providers'; topDesc='Reliable movers serving Morrill County residential needs across Bridgeport and eastern North Platte-Scottsbluff corridor communities.'; countyMovingName='Morrill County Moving'; regional1Name='Bridgeport Corridor Moving'; regional2Name='North Platte Scottsbluff East Moving'; countyLabel='Morrill County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='nance'; city='Fullerton'; citySlug='fullerton'; label='Fullerton Metro'; poolId='nance-metro-ne'; regional1='fullerton-corridor'; regional2='loup-river-nance'; topId='regional-nance-ne-movers'; topName='Regional Fullerton / Nance Providers'; topDesc='Reliable movers serving Nance County residential needs across Fullerton and Nance County Loup River communities.'; countyMovingName='Nance County Moving'; regional1Name='Fullerton Corridor Moving'; regional2Name='Loup River Nance Moving'; countyLabel='Nance County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='nuckolls'; city='Nelson'; citySlug='nelson'; label='Nelson Metro'; poolId='nuckolls-metro-ne'; regional1='nelson-corridor'; regional2='republican-river-nuckolls'; topId='regional-nuckolls-ne-movers'; topName='Regional Nelson / Nuckolls Providers'; topDesc='Reliable movers serving Nuckolls County, NE residential needs across Nelson and Republican River Nuckolls basin communities.'; countyMovingName='Nuckolls County Moving'; regional1Name='Nelson Corridor Moving'; regional2Name='Republican River Nuckolls Moving'; countyLabel='Nuckolls County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='pawnee'; city='Pawnee City'; citySlug='pawnee-city'; label='Pawnee City Metro'; poolId='pawnee-metro-ne'; regional1='pawnee-city-corridor'; regional2='nemaha-river-pawnee'; topId='regional-pawnee-ne-movers'; topName='Regional Pawnee City / Pawnee Providers'; topDesc='Reliable movers serving Pawnee County, NE residential needs across Pawnee City and Nemaha River Pawnee basin communities.'; countyMovingName='Pawnee County Moving'; regional1Name='Pawnee City Corridor Moving'; regional2Name='Nemaha River Pawnee Moving'; countyLabel='Pawnee County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='perkins'; city='Grant'; citySlug='grant'; label='Grant Metro'; poolId='perkins-metro-ne'; regional1='grant-corridor'; regional2='platte-valley-perkins'; topId='regional-perkins-ne-movers'; topName='Regional Grant / Perkins Providers'; topDesc='Reliable movers serving Perkins County, NE residential needs across Grant and Perkins County Platte Valley communities.'; countyMovingName='Perkins County Moving'; regional1Name='Grant Corridor Moving'; regional2Name='Platte Valley Perkins Moving'; countyLabel='Perkins County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='rock'; city='Bassett'; citySlug='bassett'; label='Bassett Metro'; poolId='rock-metro-ne'; regional1='bassett-corridor'; regional2='niobrara-rock'; topId='regional-rock-ne-movers'; topName='Regional Bassett / Rock Providers'; topDesc='Reliable movers serving Rock County residential needs across Bassett and Rock County Niobrara corridor communities.'; countyMovingName='Rock County Moving'; regional1Name='Bassett Corridor Moving'; regional2Name='Niobrara Rock Moving'; countyLabel='Rock County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='sheridan'; city='Rushville'; citySlug='rushville'; label='Rushville Metro'; poolId='sheridan-metro-ne'; regional1='rushville-corridor'; regional2='sandhills-sheridan'; topId='regional-sheridan-ne-movers'; topName='Regional Rushville / Sheridan Providers'; topDesc='Reliable movers serving Sheridan County, NE residential needs across Rushville and Sheridan County Sandhills communities.'; countyMovingName='Sheridan County Moving'; regional1Name='Rushville Corridor Moving'; regional2Name='Sandhills Sheridan Moving'; countyLabel='Sheridan County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='sherman'; city='Loup City'; citySlug='loup-city'; label='Loup City Metro'; poolId='sherman-metro-ne'; regional1='loup-city-corridor'; regional2='loup-river-sherman'; topId='regional-sherman-ne-movers'; topName='Regional Loup City / Sherman Providers'; topDesc='Reliable movers serving Sherman County residential needs across Loup City and Sherman County Loup River communities.'; countyMovingName='Sherman County Moving'; regional1Name='Loup City Corridor Moving'; regional2Name='Loup River Sherman Moving'; countyLabel='Sherman County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='sioux'; city='Harrison'; citySlug='harrison'; label='Harrison Metro'; poolId='sioux-metro-ne'; regional1='harrison-corridor'; regional2='high-plains-sioux'; topId='regional-sioux-ne-movers'; topName='Regional Harrison / Sioux Providers'; topDesc='Reliable movers serving Sioux County, NE residential needs across Harrison and Sioux County High Plains communities.'; countyMovingName='Sioux County Moving'; regional1Name='Harrison Corridor Moving'; regional2Name='High Plains Sioux Moving'; countyLabel='Sioux County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='thomas'; city='Thedford'; citySlug='thedford'; label='Thedford Metro'; poolId='thomas-metro-ne'; regional1='thedford-corridor'; regional2='sandhills-thomas'; topId='regional-thomas-ne-movers'; topName='Regional Thedford / Thomas Providers'; topDesc='Reliable movers serving Thomas County residential needs across Thedford and Thomas County Sandhills communities.'; countyMovingName='Thomas County Moving'; regional1Name='Thedford Corridor Moving'; regional2Name='Sandhills Thomas Moving'; countyLabel='Thomas County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='valley'; city='Ord'; citySlug='ord'; label='Ord Metro'; poolId='valley-metro-ne'; regional1='ord-corridor'; regional2='loup-valley-ord'; topId='regional-valley-ne-movers'; topName='Regional Ord / Valley Providers'; topDesc='Reliable movers serving Valley County residential needs across Ord and Ord Loup Valley communities.'; countyMovingName='Valley County Moving'; regional1Name='Ord Corridor Moving'; regional2Name='Loup Valley Ord Moving'; countyLabel='Valley County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='webster'; city='Red Cloud'; citySlug='red-cloud'; label='Red Cloud Metro'; poolId='webster-metro-ne'; regional1='red-cloud-corridor'; regional2='republican-river-webster'; topId='regional-webster-ne-movers'; topName='Regional Red Cloud / Webster Providers'; topDesc='Reliable movers serving Webster County, NE residential needs across Red Cloud and Republican River Webster basin communities.'; countyMovingName='Webster County Moving'; regional1Name='Red Cloud Corridor Moving'; regional2Name='Republican River Webster Moving'; countyLabel='Webster County, NE'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='wheeler'; city='Bartlett'; citySlug='bartlett'; label='Bartlett Metro'; poolId='wheeler-metro-ne'; regional1='bartlett-corridor'; regional2='elkhorn-river-wheeler'; topId='regional-wheeler-ne-movers'; topName='Regional Bartlett / Wheeler Providers'; topDesc='Reliable movers serving Wheeler County, NE residential needs across Bartlett and Wheeler County Elkhorn River communities.'; countyMovingName='Wheeler County Moving'; regional1Name='Bartlett Corridor Moving'; regional2Name='Elkhorn River Wheeler Moving'; countyLabel='Wheeler County, NE'; franchise=$false; topSpecialties="['Residential']" }
)


function Format-MoverBlock($m) {
  $nameQ = Quote-Ts $m.name
  $descQ = Quote-Ts $m.desc
  $cityQ = Quote-Ts $m.city
  $bbb = if ($m.bbb) { "bbbRating: '$($m.bbb)'," } else { '' }
@"
  '$($m.id)': {
    id: '$($m.id)',
    name: $nameQ,
    rating: $($m.rating),
    reviewCount: $($m.reviews),
    shortDescription:
      $descQ,
    services: $($m.services),
    specialties: $($m.specialties),
    fmcsaSafetyRating: 'Not Rated',
    $bbb
    city: $cityQ,
  },
"@
}

$allCatalog = @()
$allPools = @()

foreach ($c in $counties) {
  $slug = $c.slug
  $citySlug = $c.citySlug
  $ids = @(
    $c.topId,
    "all-my-sons-$citySlug-ne",
    "$citySlug-moving-$slug-ne",
    "$slug-county-moving-$slug-ne",
    "college-hunks-moving-$citySlug-ne",
    "budd-van-lines-$citySlug-ne",
    "$($c.regional1)-moving-$slug-ne",
    "$($c.regional2)-moving-$slug-ne",
    "hercules-movers-$citySlug-ne",
    "krupp-moving-$citySlug-ne"
  )

  $topServices = if ($c.franchise) { "['Local Moving', 'Packing', 'Storage']" } else { "['Local Moving', 'Packing']" }
  $topReviews = if ($c.franchise) { 2140 } else { 340 }
  $topBbb = if ($c.franchise) { 'A+' } else { 'A' }

  $movers = @(
    @{ id=$ids[0]; name=$c.topName; rating=4.7; reviews=$topReviews; desc=$c.topDesc; services=$topServices; specialties=$c.topSpecialties; bbb=$topBbb; city=$c.city }
    @{ id=$ids[1]; name="All My Sons Moving & Storage $($c.city)"; rating=4.6; reviews=1580; desc="Established mover known for reliable local and long-distance services in $($c.city) and $($c.countyLabel)."; services="['Local Moving', 'Long Distance', 'Packing']"; specialties="['Residential', 'Commercial']"; bbb='A'; city=$c.city }
    @{ id=$ids[2]; name="$($c.city) Moving"; rating=4.7; reviews=1120; desc="Full-service local mover serving $($c.city) and $($c.countyLabel) with careful residential relocations."; services="['Local Moving', 'Packing']"; specialties="['Residential']"; bbb='A+'; city=$c.city }
    @{ id=$ids[3]; name=$c.countyMovingName; rating=4.6; reviews=840; desc="County-focused mover with experience across $($c.city) and surrounding $($c.countyLabel) neighborhoods."; services="['Local Moving', 'Packing', 'Storage']"; specialties="['Residential', 'Commercial']"; bbb='A'; city=$c.city }
    @{ id=$ids[4]; name="College Hunks Moving $($c.city)"; rating=4.6; reviews=1420; desc="National franchise with strong local presence for residential and light commercial moves in $($c.city)."; services="['Local Moving', 'Packing', 'Junk Removal']"; specialties="['Residential', 'Commercial']"; bbb='A'; city=$c.city }
    @{ id=$ids[5]; name="Budd Van Lines $($c.city)"; rating=4.5; reviews=620; desc="Established van line agent serving $($c.city) with careful handling for local and regional relocations."; services="['Local Moving', 'Long Distance', 'Packing']"; specialties="['Residential', 'Commercial']"; bbb='A'; city=$c.city }
    @{ id=$ids[6]; name=$c.regional1Name; rating=4.7; reviews=510; desc="Regional mover serving $($c.city) and $($c.countyLabel) communities with steady scheduling and careful handling."; services="['Local Moving', 'Packing']"; specialties="['Residential']"; bbb='A+'; city=$c.city }
    @{ id=$ids[7]; name=$c.regional2Name; rating=4.6; reviews=440; desc="Local specialist for $($c.countyLabel) residential moves with punctual arrival and professional crew coordination."; services="['Local Moving', 'Packing']"; specialties="['Residential']"; bbb='A'; city=$c.city }
    @{ id=$ids[8]; name="Hercules Movers $($c.city)"; rating=4.5; reviews=380; desc="Local $($c.city) mover with careful residential relocations and packing services."; services="['Local Moving', 'Packing', 'Storage']"; specialties="['Residential', 'Commercial']"; bbb='A+'; city=$c.city }
    @{ id=$ids[9]; name="Krupp Moving $($c.city)"; rating=4.5; reviews=340; desc="Full-service local mover serving $($c.city) and $($c.countyLabel)."; services="['Local Moving', 'Packing', 'Storage']"; specialties="['Residential', 'Commercial']"; bbb='A+'; city=$c.city }
  )

  $allCatalog += ($movers | ForEach-Object { Format-MoverBlock $_ })
  $poolIds = ($ids | ForEach-Object { "      '$_'," }) -join "`n"
  $labelQ = Quote-Ts $c.label
  $allPools += @"
  '$($c.poolId)': {
    id: '$($c.poolId)',
    label: $labelQ,
    moverIds: [
$poolIds
    ],
  },
"@
}

Set-Content (Join-Path $outDir 'catalog-movers.txt') ($allCatalog -join "`n") -Encoding UTF8
Set-Content (Join-Path $outDir 'metro-pools.txt') ($allPools -join "`n") -Encoding UTF8
Write-Host 'Generated 720 catalog entries, 72 metro pools for Nebraska batch 2'