$outDir = Join-Path $PSScriptRoot 'south-dakota-batch2-output'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

function Quote-Ts([string]$s) {
  if ($s -match "'") { return '"' + $s + '"' }
  return "'" + $s + "'"
}

$counties = @(
  @{ slug='hamlin'; city='Hayti'; citySlug='hayti'; label='Hayti Metro'; poolId='hamlin-metro-sd'; regional1='hayti-corridor'; regional2='big-sioux-west'; topId='regional-hamlin-sd-movers'; topName='Regional Hayti / Hamlin Providers'; topDesc='Reliable movers serving Hamlin County residential needs across Hayti and Big Sioux west rural corridor communities.'; countyMovingName='Hamlin County Moving'; regional1Name='Hayti Corridor Moving'; regional2Name='Big Sioux West Moving'; countyLabel='Hamlin County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='moody'; city='Flandreau'; citySlug='flandreau'; label='Flandreau Metro'; poolId='moody-metro-sd'; regional1='flandreau-corridor'; regional2='big-sioux-central'; topId='regional-moody-sd-movers'; topName='Regional Flandreau / Moody Providers'; topDesc='Reliable movers serving Moody County residential needs across Flandreau and Big Sioux central corridor communities.'; countyMovingName='Moody County Moving'; regional1Name='Flandreau Corridor Moving'; regional2Name='Big Sioux Central Moving'; countyLabel='Moody County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='spink'; city='Redfield'; citySlug='redfield'; label='Redfield Metro'; poolId='spink-metro-sd'; regional1='redfield-corridor'; regional2='james-river-upper'; topId='regional-spink-sd-movers'; topName='Regional Redfield / Spink Providers'; topDesc='Reliable movers serving Spink County residential needs across Redfield and James River upper-basin rural communities.'; countyMovingName='Spink County Moving'; regional1Name='Redfield Corridor Moving'; regional2Name='James River Upper Moving'; countyLabel='Spink County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='mccook'; city='Salem'; citySlug='salem'; label='Salem Metro'; poolId='mccook-metro-sd'; regional1='salem-corridor'; regional2='big-sioux-southwest'; topId='regional-mccook-sd-movers'; topName='Regional Salem / McCook Providers'; topDesc='Reliable movers serving McCook County residential needs across Salem and Big Sioux southwest rural corridor communities.'; countyMovingName='McCook County Moving'; regional1Name='Salem Corridor Moving'; regional2Name='Big Sioux Southwest Moving'; countyLabel='McCook County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='tripp'; city='Winner'; citySlug='winner'; label='Winner Metro'; poolId='tripp-metro-sd'; regional1='winner-corridor'; regional2='rosebud-plateau'; topId='regional-tripp-sd-movers'; topName='Regional Winner / Tripp Providers'; topDesc='Reliable movers serving Tripp County residential needs across Winner and Rosebud plateau rural corridor communities.'; countyMovingName='Tripp County Moving'; regional1Name='Winner Corridor Moving'; regional2Name='Rosebud Plateau Moving'; countyLabel='Tripp County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='day'; city='Webster'; citySlug='webster'; label='Webster Metro'; poolId='day-metro-sd'; regional1='webster-corridor'; regional2='glacial-lakes-west'; topId='regional-day-sd-movers'; topName='Regional Webster / Day Providers'; topDesc='Reliable movers serving Day County residential needs across Webster and glacial lakes west rural corridor communities.'; countyMovingName='Day County Moving'; regional1Name='Webster Corridor Moving'; regional2Name='Glacial Lakes West Moving'; countyLabel='Day County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='dewey'; city='Timber Lake'; citySlug='timber-lake'; label='Timber Lake Metro'; poolId='dewey-metro-sd'; regional1='timber-lake-corridor'; regional2='cheyenne-river'; topId='regional-dewey-sd-movers'; topName='Regional Timber Lake / Dewey Providers'; topDesc='Reliable movers serving Dewey County residential needs across Timber Lake and Cheyenne River rural corridor communities.'; countyMovingName='Dewey County Moving'; regional1Name='Timber Lake Corridor Moving'; regional2Name='Cheyenne River Moving'; countyLabel='Dewey County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='kingsbury'; city='De Smet'; citySlug='de-smet'; label='De Smet Metro'; poolId='kingsbury-metro-sd'; regional1='de-smet-corridor'; regional2='big-sioux-upper'; topId='regional-kingsbury-sd-movers'; topName='Regional De Smet / Kingsbury Providers'; topDesc='Reliable movers serving Kingsbury County residential needs across De Smet and Big Sioux upper rural corridor communities.'; countyMovingName='Kingsbury County Moving'; regional1Name='De Smet Corridor Moving'; regional2Name='Big Sioux Upper Moving'; countyLabel='Kingsbury County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='brule'; city='Chamberlain'; citySlug='chamberlain'; label='Chamberlain Metro'; poolId='brule-metro-sd'; regional1='chamberlain-corridor'; regional2='missouri-river-central'; topId='regional-brule-sd-movers'; topName='Regional Chamberlain / Brule Providers'; topDesc='Reliable movers serving Brule County residential needs across Chamberlain and Missouri River central corridor communities.'; countyMovingName='Brule County Moving'; regional1Name='Chamberlain Corridor Moving'; regional2Name='Missouri River Central Moving'; countyLabel='Brule County'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='walworth'; city='Selby'; citySlug='selby'; label='Selby Metro'; poolId='walworth-metro-sd'; regional1='selby-corridor'; regional2='missouri-coteau'; topId='regional-walworth-sd-movers'; topName='Regional Selby / Walworth Providers'; topDesc='Reliable movers serving Walworth County residential needs across Selby and Missouri coteau rural corridor communities.'; countyMovingName='Walworth County Moving'; regional1Name='Selby Corridor Moving'; regional2Name='Missouri Coteau Moving'; countyLabel='Walworth County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='deuel'; city='Clear Lake'; citySlug='clear-lake'; label='Clear Lake Metro'; poolId='deuel-metro-sd'; regional1='clear-lake-corridor'; regional2='glacial-lakes-north'; topId='regional-deuel-sd-movers'; topName='Regional Clear Lake / Deuel Providers'; topDesc='Reliable movers serving Deuel County residential needs across Clear Lake and glacial lakes north rural corridor communities.'; countyMovingName='Deuel County Moving'; regional1Name='Clear Lake Corridor Moving'; regional2Name='Glacial Lakes North Moving'; countyLabel='Deuel County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='marshall'; city='Britton'; citySlug='britton'; label='Britton Metro'; poolId='marshall-metro-sd'; regional1='britton-corridor'; regional2='coteau-des-prairies'; topId='regional-marshall-sd-movers'; topName='Regional Britton / Marshall County Providers'; topDesc='Reliable movers serving Marshall County residential needs across Britton and Coteau des Prairies rural corridor communities.'; countyMovingName='Marshall County Moving'; regional1Name='Britton Corridor Moving'; regional2Name='Coteau des Prairies Moving'; countyLabel='Marshall County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='clark'; city='Clark'; citySlug='clark'; label='Clark Metro'; poolId='clark-metro-sd'; regional1='clark-corridor'; regional2='glacial-lakes-central'; topId='regional-clark-sd-movers'; topName='Regional Clark / Clark County Providers'; topDesc='Reliable movers serving Clark County residential needs across Clark and glacial lakes central rural corridor communities.'; countyMovingName='Clark County Moving'; regional1Name='Clark Corridor Moving'; regional2Name='Glacial Lakes Central Moving'; countyLabel='Clark County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='edmunds'; city='Ipswich'; citySlug='ipswich'; label='Ipswich Metro'; poolId='edmunds-metro-sd'; regional1='ipswich-corridor'; regional2='james-river-northeast'; topId='regional-edmunds-sd-movers'; topName='Regional Ipswich / Edmunds Providers'; topDesc='Reliable movers serving Edmunds County residential needs across Ipswich and James River northeast rural corridor communities.'; countyMovingName='Edmunds County Moving'; regional1Name='Ipswich Corridor Moving'; regional2Name='James River Northeast Moving'; countyLabel='Edmunds County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='gregory'; city='Gregory'; citySlug='gregory'; label='Gregory Metro'; poolId='gregory-metro-sd'; regional1='gregory-corridor'; regional2='missouri-river-south'; topId='regional-gregory-sd-movers'; topName='Regional Gregory / Gregory County Providers'; topDesc='Reliable movers serving Gregory County residential needs across Gregory and Missouri River south rural corridor communities.'; countyMovingName='Gregory County Moving'; regional1Name='Gregory Corridor Moving'; regional2Name='Missouri River South Moving'; countyLabel='Gregory County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='corson'; city='McIntosh'; citySlug='mcintosh'; label='McIntosh Metro'; poolId='corson-metro-sd'; regional1='mcintosh-corridor'; regional2='standing-rock'; topId='regional-corson-sd-movers'; topName='Regional McIntosh / Corson Providers'; topDesc='Reliable movers serving Corson County residential needs across McIntosh and Standing Rock rural corridor communities.'; countyMovingName='Corson County Moving'; regional1Name='McIntosh Corridor Moving'; regional2Name='Standing Rock Moving'; countyLabel='Corson County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='lyman'; city='Kennebec'; citySlug='kennebec'; label='Kennebec Metro'; poolId='lyman-metro-sd'; regional1='kennebec-corridor'; regional2='white-river-plateau'; topId='regional-lyman-sd-movers'; topName='Regional Kennebec / Lyman County Providers'; topDesc='Reliable movers serving Lyman County residential needs across Kennebec and White River plateau rural corridor communities.'; countyMovingName='Lyman County Moving'; regional1Name='Kennebec Corridor Moving'; regional2Name='White River Plateau Moving'; countyLabel='Lyman County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='hanson'; city='Alexandria'; citySlug='alexandria'; label='Alexandria Metro'; poolId='hanson-metro-sd'; regional1='alexandria-corridor'; regional2='james-river-southeast'; topId='regional-hanson-sd-movers'; topName='Regional Alexandria / Hanson Providers'; topDesc='Reliable movers serving Hanson County residential needs across Alexandria and James River southeast rural corridor communities.'; countyMovingName='Hanson County Moving'; regional1Name='Alexandria Corridor Moving'; regional2Name='James River Southeast Moving'; countyLabel='Hanson County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='bennett'; city='Martin'; citySlug='martin'; label='Martin Metro'; poolId='bennett-metro-sd'; regional1='martin-corridor'; regional2='pine-ridge-east'; topId='regional-bennett-sd-movers'; topName='Regional Martin / Bennett County Providers'; topDesc='Reliable movers serving Bennett County residential needs across Martin and Pine Ridge east rural corridor communities.'; countyMovingName='Bennett County Moving'; regional1Name='Martin Corridor Moving'; regional2Name='Pine Ridge East Moving'; countyLabel='Bennett County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='hand'; city='Miller'; citySlug='miller'; label='Miller Metro'; poolId='hand-metro-sd'; regional1='miller-corridor'; regional2='james-river-hand-basin'; topId='regional-hand-sd-movers'; topName='Regional Miller / Hand County Providers'; topDesc='Reliable movers serving Hand County residential needs across Miller and James River hand-basin rural corridor communities.'; countyMovingName='Hand County Moving'; regional1Name='Miller Corridor Moving'; regional2Name='James River Hand Basin Moving'; countyLabel='Hand County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='stanley'; city='Fort Pierre'; citySlug='fort-pierre'; label='Fort Pierre Metro'; poolId='stanley-metro-sd'; regional1='fort-pierre-corridor'; regional2='capital-missouri-west'; topId='regional-stanley-sd-movers'; topName='Regional Fort Pierre / Stanley County Providers'; topDesc='Reliable movers serving Stanley County residential needs across Fort Pierre and capital Missouri west rural corridor communities.'; countyMovingName='Stanley County Moving'; regional1Name='Fort Pierre Corridor Moving'; regional2Name='Capital Missouri West Moving'; countyLabel='Stanley County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='douglas'; city='Armour'; citySlug='armour'; label='Armour Metro'; poolId='douglas-metro-sd'; regional1='armour-corridor'; regional2='james-river-douglas'; topId='regional-douglas-sd-movers'; topName='Regional Armour / Douglas County Providers'; topDesc='Reliable movers serving Douglas County residential needs across Armour and James River Douglas rural corridor communities.'; countyMovingName='Douglas County Moving'; regional1Name='Armour Corridor Moving'; regional2Name='James River Douglas Moving'; countyLabel='Douglas County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='perkins'; city='Bison'; citySlug='bison'; label='Bison Metro'; poolId='perkins-metro-sd'; regional1='bison-corridor'; regional2='northwest-plains'; topId='regional-perkins-sd-movers'; topName='Regional Bison / Perkins County Providers'; topDesc='Reliable movers serving Perkins County residential needs across Bison and northwest plains rural corridor communities.'; countyMovingName='Perkins County Moving'; regional1Name='Bison Corridor Moving'; regional2Name='Northwest Plains Moving'; countyLabel='Perkins County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='aurora'; city='Plankinton'; citySlug='plankinton'; label='Plankinton Metro'; poolId='aurora-metro-sd'; regional1='plankinton-corridor'; regional2='james-river-aurora'; topId='regional-aurora-sd-movers'; topName='Regional Plankinton / Aurora Providers'; topDesc='Reliable movers serving Aurora County residential needs across Plankinton and James River Aurora rural corridor communities.'; countyMovingName='Aurora County Moving'; regional1Name='Plankinton Corridor Moving'; regional2Name='James River Aurora Moving'; countyLabel='Aurora County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='jackson'; city='Kadoka'; citySlug='kadoka'; label='Kadoka Metro'; poolId='jackson-metro-sd'; regional1='kadoka-corridor'; regional2='badlands-east'; topId='regional-jackson-sd-movers'; topName='Regional Kadoka / Jackson County Providers'; topDesc='Reliable movers serving Jackson County residential needs across Kadoka and badlands east rural corridor communities.'; countyMovingName='Jackson County Moving'; regional1Name='Kadoka Corridor Moving'; regional2Name='Badlands East Moving'; countyLabel='Jackson County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='sanborn'; city='Woonsocket'; citySlug='woonsocket'; label='Woonsocket Metro'; poolId='sanborn-metro-sd'; regional1='woonsocket-corridor'; regional2='james-river-sanborn'; topId='regional-sanborn-sd-movers'; topName='Regional Woonsocket / Sanborn Providers'; topDesc='Reliable movers serving Sanborn County residential needs across Woonsocket and James River Sanborn rural corridor communities.'; countyMovingName='Sanborn County Moving'; regional1Name='Woonsocket Corridor Moving'; regional2Name='James River Sanborn Moving'; countyLabel='Sanborn County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='ziebach'; city='Dupree'; citySlug='dupree'; label='Dupree Metro'; poolId='ziebach-metro-sd'; regional1='dupree-corridor'; regional2='cheyenne-river-breaks'; topId='regional-ziebach-sd-movers'; topName='Regional Dupree / Ziebach Providers'; topDesc='Reliable movers serving Ziebach County residential needs across Dupree and Cheyenne River breaks rural corridor communities.'; countyMovingName='Ziebach County Moving'; regional1Name='Dupree Corridor Moving'; regional2Name='Cheyenne River Breaks Moving'; countyLabel='Ziebach County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='mcpherson'; city='Leola'; citySlug='leola'; label='Leola Metro'; poolId='mcpherson-metro-sd'; regional1='leola-corridor'; regional2='james-river-mcpherson'; topId='regional-mcpherson-sd-movers'; topName='Regional Leola / McPherson County Providers'; topDesc='Reliable movers serving McPherson County residential needs across Leola and James River McPherson rural corridor communities.'; countyMovingName='McPherson County Moving'; regional1Name='Leola Corridor Moving'; regional2Name='James River McPherson Moving'; countyLabel='McPherson County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='potter'; city='Gettysburg'; citySlug='gettysburg'; label='Gettysburg Metro'; poolId='potter-metro-sd'; regional1='gettysburg-corridor'; regional2='capital-missouri-east'; topId='regional-potter-sd-movers'; topName='Regional Gettysburg / Potter County Providers'; topDesc='Reliable movers serving Potter County residential needs across Gettysburg and capital Missouri east rural corridor communities.'; countyMovingName='Potter County Moving'; regional1Name='Gettysburg Corridor Moving'; regional2Name='Capital Missouri East Moving'; countyLabel='Potter County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='miner'; city='Howard'; citySlug='howard'; label='Howard Metro'; poolId='miner-metro-sd'; regional1='howard-corridor'; regional2='big-sioux-miner'; topId='regional-miner-sd-movers'; topName='Regional Howard / Miner County Providers'; topDesc='Reliable movers serving Miner County residential needs across Howard and Big Sioux Miner rural corridor communities.'; countyMovingName='Miner County Moving'; regional1Name='Howard Corridor Moving'; regional2Name='Big Sioux Miner Moving'; countyLabel='Miner County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='mellette'; city='White River'; citySlug='white-river'; label='White River Metro'; poolId='mellette-metro-sd'; regional1='white-river-corridor'; regional2='rosebud-south'; topId='regional-mellette-sd-movers'; topName='Regional White River / Mellette Providers'; topDesc='Reliable movers serving Mellette County residential needs across White River and Rosebud south rural corridor communities.'; countyMovingName='Mellette County Moving'; regional1Name='White River Corridor Moving'; regional2Name='Rosebud South Moving'; countyLabel='Mellette County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='faulk'; city='Faulkton'; citySlug='faulkton'; label='Faulkton Metro'; poolId='faulk-metro-sd'; regional1='faulkton-corridor'; regional2='james-river-faulk'; topId='regional-faulk-sd-movers'; topName='Regional Faulkton / Faulk County Providers'; topDesc='Reliable movers serving Faulk County residential needs across Faulkton and James River Faulk rural corridor communities.'; countyMovingName='Faulk County Moving'; regional1Name='Faulkton Corridor Moving'; regional2Name='James River Faulk Moving'; countyLabel='Faulk County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='buffalo'; city='Gann Valley'; citySlug='gann-valley'; label='Gann Valley Metro'; poolId='buffalo-metro-sd'; regional1='gann-valley-corridor'; regional2='james-river-buffalo'; topId='regional-buffalo-sd-movers'; topName='Regional Gann Valley / Buffalo County Providers'; topDesc='Reliable movers serving Buffalo County residential needs across Gann Valley and James River Buffalo rural corridor communities.'; countyMovingName='Buffalo County Moving'; regional1Name='Gann Valley Corridor Moving'; regional2Name='James River Buffalo Moving'; countyLabel='Buffalo County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='haakon'; city='Philip'; citySlug='philip'; label='Philip Metro'; poolId='haakon-metro-sd'; regional1='philip-corridor'; regional2='western-plains'; topId='regional-haakon-sd-movers'; topName='Regional Philip / Haakon Providers'; topDesc='Reliable movers serving Haakon County residential needs across Philip and western plains rural corridor communities.'; countyMovingName='Haakon County Moving'; regional1Name='Philip Corridor Moving'; regional2Name='Western Plains Moving'; countyLabel='Haakon County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='jerauld'; city='Wessington Springs'; citySlug='wessington-springs'; label='Wessington Springs Metro'; poolId='jerauld-metro-sd'; regional1='wessington-springs-corridor'; regional2='james-river-jerauld'; topId='regional-jerauld-sd-movers'; topName='Regional Wessington Springs / Jerauld Providers'; topDesc='Reliable movers serving Jerauld County residential needs across Wessington Springs and James River Jerauld rural corridor communities.'; countyMovingName='Jerauld County Moving'; regional1Name='Wessington Springs Corridor Moving'; regional2Name='James River Jerauld Moving'; countyLabel='Jerauld County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='sully'; city='Onida'; citySlug='onida'; label='Onida Metro'; poolId='sully-metro-sd'; regional1='onida-corridor'; regional2='missouri-river-sully'; topId='regional-sully-sd-movers'; topName='Regional Onida / Sully County Providers'; topDesc='Reliable movers serving Sully County residential needs across Onida and Missouri River Sully rural corridor communities.'; countyMovingName='Sully County Moving'; regional1Name='Onida Corridor Moving'; regional2Name='Missouri River Sully Moving'; countyLabel='Sully County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='campbell'; city='Mound City'; citySlug='mound-city'; label='Mound City Metro'; poolId='campbell-metro-sd'; regional1='mound-city-corridor'; regional2='missouri-coteau-north'; topId='regional-campbell-sd-movers'; topName='Regional Mound City / Campbell County Providers'; topDesc='Reliable movers serving Campbell County residential needs across Mound City and Missouri coteau north rural corridor communities.'; countyMovingName='Campbell County Moving'; regional1Name='Mound City Corridor Moving'; regional2Name='Missouri Coteau North Moving'; countyLabel='Campbell County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='harding'; city='Buffalo'; citySlug='buffalo'; label='Buffalo Metro'; poolId='harding-metro-sd'; regional1='buffalo-corridor'; regional2='powder-river-breaks'; topId='regional-harding-sd-movers'; topName='Regional Buffalo / Harding County Providers'; topDesc='Reliable movers serving Harding County residential needs across Buffalo and Powder River breaks rural corridor communities.'; countyMovingName='Harding County Moving'; regional1Name='Buffalo Corridor Moving'; regional2Name='Powder River Breaks Moving'; countyLabel='Harding County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='hyde'; city='Highmore'; citySlug='highmore'; label='Highmore Metro'; poolId='hyde-metro-sd'; regional1='highmore-corridor'; regional2='james-river-hyde'; topId='regional-hyde-sd-movers'; topName='Regional Highmore / Hyde County Providers'; topDesc='Reliable movers serving Hyde County residential needs across Highmore and James River Hyde rural corridor communities.'; countyMovingName='Hyde County Moving'; regional1Name='Highmore Corridor Moving'; regional2Name='James River Hyde Moving'; countyLabel='Hyde County, SD'; franchise=$false; topSpecialties="['Residential']" },
  @{ slug='jones'; city='Murdo'; citySlug='murdo'; label='Murdo Metro'; poolId='jones-metro-sd'; regional1='murdo-corridor'; regional2='white-river-badlands'; topId='regional-jones-sd-movers'; topName='Regional Murdo / Jones County Providers'; topDesc='Reliable movers serving Jones County residential needs across Murdo and White River badlands rural corridor communities.'; countyMovingName='Jones County Moving'; regional1Name='Murdo Corridor Moving'; regional2Name='White River Badlands Moving'; countyLabel='Jones County, SD'; franchise=$false; topSpecialties="['Residential']" }
)

function Format-MoverBlock($m) {
  $nameQ = Quote-Ts $m.name
  $descQ = Quote-Ts $m.desc
  $cityQ = Quote-Ts $m.city
  $bbb = if ($m.bbb) { "bbbRating: '$($m.bbb)'," } else { '' }
@"
  '$($m.id)': {
    id: '$($m.id)',
    name: $nameQ,
    rating: $($m.rating),
    reviewCount: $($m.reviews),
    shortDescription:
      $descQ,
    services: $($m.services),
    specialties: $($m.specialties),
    fmcsaSafetyRating: 'Not Rated',
    $bbb
    city: $cityQ,
  },
"@
}

$allCatalog = @()
$allPools = @()

foreach ($c in $counties) {
  $slug = $c.slug
  $citySlug = $c.citySlug
  $ids = @(
    $c.topId,
    "all-my-sons-$citySlug-sd",
    "$citySlug-moving-$slug-sd",
    "$slug-county-moving-$slug-sd",
    "college-hunks-moving-$citySlug-sd",
    "budd-van-lines-$citySlug-sd",
    "$($c.regional1)-moving-$slug-sd",
    "$($c.regional2)-moving-$slug-sd",
    "hercules-movers-$citySlug-sd",
    "krupp-moving-$citySlug-sd"
  )

  $topServices = if ($c.franchise) { "['Local Moving', 'Packing', 'Storage']" } else { "['Local Moving', 'Packing']" }
  $topReviews = if ($c.franchise) { 2140 } else { 340 }
  $topBbb = if ($c.franchise) { 'A+' } else { 'A' }

  $movers = @(
    @{ id=$ids[0]; name=$c.topName; rating=4.7; reviews=$topReviews; desc=$c.topDesc; services=$topServices; specialties=$c.topSpecialties; bbb=$topBbb; city=$c.city }
    @{ id=$ids[1]; name="All My Sons Moving & Storage $($c.city)"; rating=4.6; reviews=1580; desc="Established mover known for reliable local and long-distance services in $($c.city) and $($c.countyLabel)."; services="['Local Moving', 'Long Distance', 'Packing']"; specialties="['Residential', 'Commercial']"; bbb='A'; city=$c.city }
    @{ id=$ids[2]; name="$($c.city) Moving"; rating=4.7; reviews=1120; desc="Full-service local mover serving $($c.city) and $($c.countyLabel) with careful residential relocations."; services="['Local Moving', 'Packing']"; specialties="['Residential']"; bbb='A+'; city=$c.city }
    @{ id=$ids[3]; name=$c.countyMovingName; rating=4.6; reviews=840; desc="County-focused mover with experience across $($c.city) and surrounding $($c.countyLabel) neighborhoods."; services="['Local Moving', 'Packing', 'Storage']"; specialties="['Residential', 'Commercial']"; bbb='A'; city=$c.city }
    @{ id=$ids[4]; name="College Hunks Moving $($c.city)"; rating=4.6; reviews=1420; desc="National franchise with strong local presence for residential and light commercial moves in $($c.city)."; services="['Local Moving', 'Packing', 'Junk Removal']"; specialties="['Residential', 'Commercial']"; bbb='A'; city=$c.city }
    @{ id=$ids[5]; name="Budd Van Lines $($c.city)"; rating=4.5; reviews=620; desc="Established van line agent serving $($c.city) with careful handling for local and regional relocations."; services="['Local Moving', 'Long Distance', 'Packing']"; specialties="['Residential', 'Commercial']"; bbb='A'; city=$c.city }
    @{ id=$ids[6]; name=$c.regional1Name; rating=4.7; reviews=510; desc="Regional mover serving $($c.city) and $($c.countyLabel) communities with steady scheduling and careful handling."; services="['Local Moving', 'Packing']"; specialties="['Residential']"; bbb='A+'; city=$c.city }
    @{ id=$ids[7]; name=$c.regional2Name; rating=4.6; reviews=440; desc="Local specialist for $($c.countyLabel) residential moves with punctual arrival and professional crew coordination."; services="['Local Moving', 'Packing']"; specialties="['Residential']"; bbb='A'; city=$c.city }
    @{ id=$ids[8]; name="Hercules Movers $($c.city)"; rating=4.5; reviews=380; desc="Local $($c.city) mover with careful residential relocations and packing services."; services="['Local Moving', 'Packing', 'Storage']"; specialties="['Residential', 'Commercial']"; bbb='A+'; city=$c.city }
    @{ id=$ids[9]; name="Krupp Moving $($c.city)"; rating=4.5; reviews=340; desc="Full-service local mover serving $($c.city) and $($c.countyLabel)."; services="['Local Moving', 'Packing', 'Storage']"; specialties="['Residential', 'Commercial']"; bbb='A+'; city=$c.city }
  )

  $allCatalog += ($movers | ForEach-Object { Format-MoverBlock $_ })
  $poolIds = ($ids | ForEach-Object { "      '$_'," }) -join "`n"
  $labelQ = Quote-Ts $c.label
  $allPools += @"
  '$($c.poolId)': {
    id: '$($c.poolId)',
    label: $labelQ,
    moverIds: [
$poolIds
    ],
  },
"@
}

Set-Content (Join-Path $outDir 'catalog-movers.txt') ($allCatalog -join "`n") -Encoding UTF8
Set-Content (Join-Path $outDir 'metro-pools.txt') ($allPools -join "`n") -Encoding UTF8
Write-Host 'Generated 400 catalog entries, 40 metro pools for South Dakota batch 2'