/**
 * Task 011A — emit 50-state + DC regulatory source matrix artifact.
 * Research-backed where known; UNKNOWN / RESEARCH_REQUIRED otherwise.
 * No Google Places. No publication.
 */
import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import type { StateRegulatorySourceMatrixRow } from '../lib/state-hhg/types';

const UNKNOWN_FIELDS: StateRegulatorySourceMatrixRow['fields'] = {
  currentStatus: 'UNKNOWN',
  issueDate: 'UNKNOWN',
  expirationDate: 'UNKNOWN',
  legalName: 'UNKNOWN',
  dba: 'UNKNOWN',
  usdotLinkage: 'UNKNOWN',
  physicalAddress: 'UNKNOWN',
  mailingAddress: 'UNKNOWN',
  phone: 'UNKNOWN',
  email: 'UNKNOWN',
  website: 'UNKNOWN',
  ownersOfficers: 'UNKNOWN',
  registeredAgent: 'UNKNOWN',
  insurance: 'UNKNOWN',
  bond: 'UNKNOWN',
  complaints: 'UNKNOWN',
  enforcement: 'UNKNOWN',
  disciplinaryActions: 'UNKNOWN',
  fines: 'UNKNOWN',
  suspensions: 'UNKNOWN',
  revocations: 'UNKNOWN',
  historicalNames: 'UNKNOWN',
};

function row(
  partial: Omit<StateRegulatorySourceMatrixRow, 'fields'> & {
    fields?: Partial<StateRegulatorySourceMatrixRow['fields']>;
  }
): StateRegulatorySourceMatrixRow {
  return {
    ...partial,
    fields: { ...UNKNOWN_FIELDS, ...(partial.fields ?? {}) },
  };
}

/** Documented research snapshot for Task 011A (Aug 2026). */
const MATRIX: StateRegulatorySourceMatrixRow[] = [
  row({
    stateCode: 'AL',
    stateName: 'Alabama',
    primaryRegulator: 'Alabama Public Service Commission (research continuity)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'D',
    researchNotes: 'Needs official confirmation of current intrastate HHG certificate program.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'AK',
    stateName: 'Alaska',
    primaryRegulator: 'Alaska Department of Transportation / Consumer protection (fragmented)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'UNKNOWN',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'UNKNOWN',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume; fragmented sources.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'AZ',
    stateName: 'Arizona',
    primaryRegulator: 'Arizona Department of Public Safety / Corporation Commission (confirm HHG-specific)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Confirm whether statewide HHG certificate still applies vs municipal.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'AR',
    stateName: 'Arkansas',
    primaryRegulator: 'Arkansas Department of Transportation',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'Intrastate Authority Permit',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: 'https://www.ardot.gov/',
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Intrastate Authority Permit historically required; confirm bulk access.',
    researchStatus: 'DOCUMENTED',
    fields: { legalName: true, currentStatus: 'UNKNOWN', usdotLinkage: 'UNKNOWN' },
  }),
  row({
    stateCode: 'CA',
    stateName: 'California',
    primaryRegulator: 'CA Department of Consumer Affairs — Bureau of Household Goods and Services (BHGS)',
    secondaryRegulator: 'Caltrans (truck access exemptions context only)',
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'BHGS household mover permit / Cal-T lineage',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: 'BHGS may cover related HHG services',
    licenseIdFormat: 'Cal-T / BHGS license number',
    publicLookupUrl: 'https://bhgs.dca.ca.gov/licensee/index.shtml',
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: 'Official lookup live (2026)',
    dataRestrictions: 'Web lookup oriented; bulk may need PRA',
    publicationConfidence: 'HIGH',
    regulatoryValue: 5,
    customClientFileYield: 4,
    accessTier: 'B',
    researchNotes: 'Strong consumer regulator; prefer BHGS over legacy CPUC references.',
    researchStatus: 'DOCUMENTED',
    fields: {
      currentStatus: true,
      legalName: true,
      dba: true,
      physicalAddress: true,
      insurance: true,
      usdotLinkage: 'UNKNOWN',
    },
  }),
  row({
    stateCode: 'CO',
    stateName: 'Colorado',
    primaryRegulator: 'Colorado Public Utilities Commission (confirm current HHG scope)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Verify whether statewide HHG authority remains after historical changes.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'CT',
    stateName: 'Connecticut',
    primaryRegulator: 'Connecticut Department of Transportation / DCP (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official source confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'DE',
    stateName: 'Delaware',
    primaryRegulator: 'No statewide HHG mover license commonly cited; consumer protection / municipal',
    secondaryRegulator: 'Delaware Division of Motor Vehicles (general carrier context)',
    intrastateHhgAuthorityRequired: 'NO',
    moverSpecificLicense: 'Often none statewide for HHG',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: null,
    dataRestrictions: 'Absence of license ≠ publication green light',
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Frequently described as no statewide mover license; fail closed on auto-publish.',
    researchStatus: 'DOCUMENTED',
  }),
  row({
    stateCode: 'DC',
    stateName: 'District of Columbia',
    primaryRegulator: 'DC Department of For-Hire Vehicles / DMV / consumer affairs (confirm HHG)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Federal district; single-jurisdiction but source clarity needed.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'FL',
    stateName: 'Florida',
    primaryRegulator: 'Florida Department of Agriculture and Consumer Services (FDACS)',
    secondaryRegulator: 'Local/municipal licenses may also apply',
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'Intrastate mover / moving broker registration (Ch. 507 FS)',
    brokerRegulation: 'Moving brokers must register with FDACS',
    warehouseRegulation: null,
    licenseIdFormat: 'FDACS registration number',
    publicLookupUrl: 'https://www.fdacs.gov/Business-Services/Moving-Companies',
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: 'Official consumer registration pages live (2026)',
    dataRestrictions: 'State registration does not replace local licenses',
    publicationConfidence: 'HIGH',
    regulatoryValue: 5,
    customClientFileYield: 5,
    accessTier: 'A',
    researchNotes: 'Pilot #1. Strong consumer mandate; biennial registration; insurance minimums.',
    researchStatus: 'DOCUMENTED',
    fields: {
      currentStatus: true,
      legalName: true,
      dba: true,
      physicalAddress: true,
      phone: true,
      insurance: true,
      complaints: true,
      usdotLinkage: 'UNKNOWN',
    },
  }),
  row({
    stateCode: 'GA',
    stateName: 'Georgia',
    primaryRegulator: 'Georgia Department of Public Safety / PSC lineage (confirm current)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 3,
    accessTier: 'C',
    researchNotes: 'Large market; confirm active statewide HHG certificate source.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'HI',
    stateName: 'Hawaii',
    primaryRegulator: 'Hawaii PUC / consumer protection (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'D',
    researchNotes: 'Island market; low early priority.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'ID',
    stateName: 'Idaho',
    primaryRegulator: 'Idaho Public Utilities Commission / Transportation (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'IL',
    stateName: 'Illinois',
    primaryRegulator: 'Illinois Commerce Commission (ICC)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'Household Goods License / Certificate of Public Convenience and Necessity',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: 'ICC HHG authority number',
    publicLookupUrl: 'https://www.icc.illinois.gov/authority/household-goods-movers',
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: 'Official ICC authority pages live',
    dataRestrictions: null,
    publicationConfidence: 'HIGH',
    regulatoryValue: 5,
    customClientFileYield: 4,
    accessTier: 'B',
    researchNotes: 'Strong certificate program; tariff/bond historically required.',
    researchStatus: 'DOCUMENTED',
    fields: {
      currentStatus: true,
      legalName: true,
      insurance: true,
      bond: true,
      usdotLinkage: 'UNKNOWN',
    },
  }),
  row({
    stateCode: 'IN',
    stateName: 'Indiana',
    primaryRegulator: 'Indiana Department of Revenue / DOR motor carrier (confirm HHG-specific)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Confirm HHG-specific vs general intrastate motor carrier.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'IA',
    stateName: 'Iowa',
    primaryRegulator: 'Iowa DOT / Utilities Board lineage (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'KS',
    stateName: 'Kansas',
    primaryRegulator: 'Kansas Corporation Commission (confirm HHG)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'KY',
    stateName: 'Kentucky',
    primaryRegulator: 'Kentucky Transportation Cabinet / KYTC (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'LA',
    stateName: 'Louisiana',
    primaryRegulator: 'Louisiana Public Service Commission (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'ME',
    stateName: 'Maine',
    primaryRegulator: 'Maine Bureau of Motor Vehicles / PUC lineage (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume early.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'MD',
    stateName: 'Maryland',
    primaryRegulator: 'Maryland Public Service Commission / MDOT (confirm HHG)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 3,
    accessTier: 'C',
    researchNotes: 'Dense consumer market; confirm certificate source.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'MA',
    stateName: 'Massachusetts',
    primaryRegulator: 'Massachusetts Department of Public Utilities — Transportation Oversight Division',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'DPU household goods license',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: 'DPU license number',
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 4,
    customClientFileYield: 3,
    accessTier: 'B',
    researchNotes: 'License required for local/intrastate HHG; confirm digital registry export.',
    researchStatus: 'DOCUMENTED',
    fields: { legalName: true, currentStatus: 'UNKNOWN' },
  }),
  row({
    stateCode: 'MI',
    stateName: 'Michigan',
    primaryRegulator: 'Michigan Public Service Commission (MPSC)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'MPSC household goods authority',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 4,
    customClientFileYield: 3,
    accessTier: 'B',
    researchNotes: 'MPSC regulates in-state HHG movers; confirm bulk lookup.',
    researchStatus: 'DOCUMENTED',
  }),
  row({
    stateCode: 'MN',
    stateName: 'Minnesota',
    primaryRegulator: 'Minnesota Department of Transportation / DOC (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'MS',
    stateName: 'Mississippi',
    primaryRegulator: 'Mississippi Public Service Commission / MDOT (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'MO',
    stateName: 'Missouri',
    primaryRegulator: 'Missouri Department of Transportation / PSC lineage (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'MT',
    stateName: 'Montana',
    primaryRegulator: 'Montana PSC / MDT (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'NE',
    stateName: 'Nebraska',
    primaryRegulator: 'Nebraska PSC (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 1,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'NV',
    stateName: 'Nevada',
    primaryRegulator: 'Nevada Transportation Authority / NTA (confirm HHG)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 3,
    accessTier: 'C',
    researchNotes: 'NTA often regulates household movers; confirm digital registry.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'NH',
    stateName: 'New Hampshire',
    primaryRegulator: 'New Hampshire Department of Safety / DOT (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'NJ',
    stateName: 'New Jersey',
    primaryRegulator: 'New Jersey Division of Consumer Affairs',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'Public mover / warehouseman license (confirm current statute)',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: 'Often paired with warehouseman licensing',
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 5,
    customClientFileYield: 4,
    accessTier: 'B',
    researchNotes: 'High consumer value; confirm machine-readable license search export.',
    researchStatus: 'DOCUMENTED',
    fields: { legalName: true, currentStatus: 'UNKNOWN', complaints: true },
  }),
  row({
    stateCode: 'NM',
    stateName: 'New Mexico',
    primaryRegulator: 'New Mexico PRC / DOT (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'NY',
    stateName: 'New York',
    primaryRegulator: 'New York State Department of Transportation (NYSDOT)',
    secondaryRegulator: 'NYC DCA for New York City local rules',
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'NYSDOT household goods authority; NYC may require separate license',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: null,
    dataRestrictions: 'NYC overlay adds complexity',
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 5,
    customClientFileYield: 4,
    accessTier: 'B',
    researchNotes: 'Large market; dual state/city evidence possible.',
    researchStatus: 'DOCUMENTED',
  }),
  row({
    stateCode: 'NC',
    stateName: 'North Carolina',
    primaryRegulator: 'North Carolina Utilities Commission / NCDOT (confirm active HHG program)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 4,
    customClientFileYield: 3,
    accessTier: 'B',
    researchNotes: 'High mover population; confirm current certificate source before Wave A.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'ND',
    stateName: 'North Dakota',
    primaryRegulator: 'North Dakota PSC / DOT (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'OH',
    stateName: 'Ohio',
    primaryRegulator: 'Public Utilities Commission of Ohio (PUCO) — confirm HHG certificate status',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 4,
    customClientFileYield: 3,
    accessTier: 'B',
    researchNotes: 'Large market; verify whether HHG certificates remain active post-reforms.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'OK',
    stateName: 'Oklahoma',
    primaryRegulator: 'Oklahoma Corporation Commission (OCC)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'Household Goods Certificate',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl:
      'https://oklahoma.gov/occ/divisions/transportation/household-goods-movers.html',
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: 'Official OCC pages live',
    dataRestrictions: null,
    publicationConfidence: 'HIGH',
    regulatoryValue: 4,
    customClientFileYield: 3,
    accessTier: 'B',
    researchNotes: 'Intrastate HHG certificate required even within city limits per OCC.',
    researchStatus: 'DOCUMENTED',
    fields: { legalName: true, currentStatus: true },
  }),
  row({
    stateCode: 'OR',
    stateName: 'Oregon',
    primaryRegulator: 'Oregon Department of Transportation / ODOT (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    primaryRegulator: 'Pennsylvania Public Utility Commission (PUC)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'PUC household goods certificate of public convenience',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 4,
    customClientFileYield: 3,
    accessTier: 'B',
    researchNotes: 'PUC historically certifies HHG carriers; confirm digital export.',
    researchStatus: 'DOCUMENTED',
  }),
  row({
    stateCode: 'RI',
    stateName: 'Rhode Island',
    primaryRegulator: 'Rhode Island Division of Public Utilities / DMV (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'SC',
    stateName: 'South Carolina',
    primaryRegulator: 'South Carolina Office of Regulatory Staff / PSC (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'SD',
    stateName: 'South Dakota',
    primaryRegulator: 'South Dakota PUC (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'TN',
    stateName: 'Tennessee',
    primaryRegulator: 'Tennessee Department of Safety / TDOT (confirm HHG)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'TX',
    stateName: 'Texas',
    primaryRegulator: 'Texas Department of Motor Vehicles (TxDMV)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'Motor carrier certificate / TxDMV number',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: '10-digit TxDMV number (commonly cited)',
    publicLookupUrl: 'https://www.txdmv.gov/',
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: 'Official TxDMV program pages live',
    dataRestrictions: null,
    publicationConfidence: 'HIGH',
    regulatoryValue: 5,
    customClientFileYield: 5,
    accessTier: 'A',
    researchNotes: 'Large market; intrastate movers licensed by TxDMV.',
    researchStatus: 'DOCUMENTED',
    fields: {
      currentStatus: true,
      legalName: true,
      usdotLinkage: true,
      physicalAddress: true,
      insurance: true,
    },
  }),
  row({
    stateCode: 'UT',
    stateName: 'Utah',
    primaryRegulator: 'Utah Department of Transportation / PSC lineage (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'VT',
    stateName: 'Vermont',
    primaryRegulator: 'Vermont DMV / Agency of Transportation (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'VA',
    stateName: 'Virginia',
    primaryRegulator: 'Virginia DMV / SCC lineage (confirm HHG)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'MEDIUM',
    regulatoryValue: 4,
    customClientFileYield: 3,
    accessTier: 'B',
    researchNotes: 'High consumer value; confirm certificate source.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'WA',
    stateName: 'Washington',
    primaryRegulator: 'Washington Utilities and Transportation Commission (UTC)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'YES',
    moverSpecificLicense: 'UTC household goods carrier permit',
    brokerRegulation: 'RESEARCH_REQUIRED',
    warehouseRegulation: null,
    licenseIdFormat: 'UTC company / permit id',
    publicLookupUrl:
      'https://www.utc.wa.gov/companies?combine=&usdot=&exposed_select_industry=568&regulatory_status=1',
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: false,
    publicRecordsRequestAvailable: true,
    sourceFreshness: 'Official UTC HHG carrier lookup live (2026)',
    dataRestrictions: 'Tariff 15-C governs rates/terms',
    publicationConfidence: 'HIGH',
    regulatoryValue: 5,
    customClientFileYield: 4,
    accessTier: 'A',
    researchNotes: 'Pilot #2. Strong permit lookup; annual reports/fees; enforcement reporting.',
    researchStatus: 'DOCUMENTED',
    fields: {
      currentStatus: true,
      legalName: true,
      usdotLinkage: true,
      physicalAddress: true,
      insurance: true,
      enforcement: true,
    },
  }),
  row({
    stateCode: 'WV',
    stateName: 'West Virginia',
    primaryRegulator: 'West Virginia PSC (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 2,
    customClientFileYield: 1,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'WI',
    stateName: 'Wisconsin',
    primaryRegulator: 'Wisconsin Department of Transportation / PSC lineage (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: 'UNKNOWN',
    machineReadableAccess: 'UNKNOWN',
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 3,
    customClientFileYield: 2,
    accessTier: 'C',
    researchNotes: 'Needs official confirmation.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
  row({
    stateCode: 'WY',
    stateName: 'Wyoming',
    primaryRegulator: 'Wyoming DOT / PSC (confirm)',
    secondaryRegulator: null,
    intrastateHhgAuthorityRequired: 'CONDITIONAL',
    moverSpecificLicense: 'RESEARCH_REQUIRED',
    brokerRegulation: null,
    warehouseRegulation: null,
    licenseIdFormat: null,
    publicLookupUrl: null,
    bulkCsvApiAvailable: false,
    machineReadableAccess: false,
    publicRecordsRequestAvailable: 'UNKNOWN',
    sourceFreshness: null,
    dataRestrictions: null,
    publicationConfidence: 'LOW',
    regulatoryValue: 1,
    customClientFileYield: 1,
    accessTier: 'D',
    researchNotes: 'Low volume.',
    researchStatus: 'RESEARCH_REQUIRED',
  }),
];

function main() {
  if (MATRIX.length !== 51) {
    throw new Error(`Expected 51 jurisdictions, got ${MATRIX.length}`);
  }
  const codes = new Set(MATRIX.map((r) => r.stateCode));
  if (codes.size !== 51) throw new Error('Duplicate or missing state codes');

  const tierCounts = { A: 0, B: 0, C: 0, D: 0 };
  for (const r of MATRIX) tierCounts[r.accessTier] += 1;

  const priority = [...MATRIX]
    .map((r) => ({
      stateCode: r.stateCode,
      accessTier: r.accessTier,
      regulatoryValue: r.regulatoryValue,
      customClientFileYield: r.customClientFileYield,
      publicationConfidence: r.publicationConfidence,
      score:
        (typeof r.regulatoryValue === 'number' ? r.regulatoryValue : 0) * 2 +
        (typeof r.customClientFileYield === 'number' ? r.customClientFileYield : 0) +
        (r.accessTier === 'A' ? 5 : r.accessTier === 'B' ? 3 : r.accessTier === 'C' ? 1 : 0),
    }))
    .sort((a, b) => b.score - a.score);

  const artifact = {
    google_places_requests: 0,
    task: '011A',
    generated_at: new Date().toISOString(),
    jurisdictions: 51,
    tier_counts: tierCounts,
    priority_rank_top_15: priority.slice(0, 15),
    pilot_recommendation: {
      state_1: 'FL',
      state_2: 'WA',
      rationale:
        'Florida (FDACS) and Washington (UTC) combine YES authority requirement, HIGH confidence, Tier A access, strong consumer demand, and usable official lookups without Google Places.',
    },
    states: MATRIX,
  };

  const docs = resolve(process.cwd(), 'docs');
  if (!existsSync(docs)) mkdirSync(docs, { recursive: true });
  writeFileSync(
    resolve(docs, 'task-011a-50-state-mover-regulatory-matrix.json'),
    JSON.stringify(artifact, null, 2) + '\n'
  );
  console.log(
    JSON.stringify(
      {
        wrote: 'docs/task-011a-50-state-mover-regulatory-matrix.json',
        jurisdictions: 51,
        tier_counts: tierCounts,
        top_15: artifact.priority_rank_top_15.map((r) => r.stateCode),
        pilot: artifact.pilot_recommendation,
        google_places_requests: 0,
      },
      null,
      2
    )
  );
}

main();
