import { type PackDef, z, s, b } from './il-tier2-render';

/** IL Tier 2 Wave 1 packs 7–12 */
export const packsB: PackDef[] = [
  {
    file: 'tazewell-il.ts',
    exportName: 'tazewellCountyIlTier2Intelligence',
    slug: 'tazewell',
    hubTitle: 'Tazewell County Moving Intelligence Hub',
    eyebrow: 'Tazewell · Pekin / East Peoria / Morton — Peoria south/east',
    h1: 'Moving in Tazewell County: East Peoria, Pekin & River-South Collar Access',
    heroOpener:
      'Tazewell County is Peoria’s river-south and east collar — East Peoria multi-family and retail-corridor stock, Pekin multi-story and seat density, Morton HOA growth, and freeflow that is not Peoria medical-core elevators with different labels. Expect bridge freeflow, industrial-residential mix, and discontinuous towns under one county. This guide is for people moving in Tazewell as Peoria south/east collar — not a Peoria core rename.',
    heroCredibility:
      'Peoria river-south collar · East Peoria / Pekin / Morton · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-74 · I-474 · IL-29 · IL-9 · IL-98 · US-24',
    parentLabel: 'Peoria County',
    parentHref: '/local-movers/illinois/peoria',
    compareIntro:
      'Tazewell is Peoria river-south collar on bridge freeflow — not Peoria medical-core multi-story alone and not pure rural prairie freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Peoria crews fight medical-corridor peaks and bluff approaches. Tazewell pairs ride I-74 bridges, IL-29, and IL-9 — freer mid-day south/east of the river, still peak-heavy on East Peoria retail corridors and Pekin arterials.'),
      b('Housing stock differences', 'Peoria mixes medical elevators and Heights bluffs. Tazewell mixes East Peoria multi-family, Pekin multi-story, and Morton HOA — more continuous collar product south of the river, less continuous Peoria medical density.'),
      b('Truck access & density', 'Bridge freeflow is first-class; multi-family elevators appear on East Peoria corridors; Morton HOAs add packets.'),
      b('Rough cost posture (qualitative)', 'Local Tazewell quotes often sit near river-collar suburb rates for driveway SFH — multi-story Pekin access and bridge peaks still push prices up.'),
      b('Role difference', 'Tazewell is Peoria river-south/east collar — not Peoria core renamed.'),
    ],
    whatIntro: 'Bridge freeflow, East Peoria multi-family, and Pekin multi-story — not interchangeable Peoria medical-core boilerplate.',
    whatBullets: [
      b('River-bridge freeflow is still billable', 'Tazewell ↔ Peoria pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('East Peoria multi-family is first-class product', 'Elevators and retail-corridor parking need inventories different from Morton cul-de-sacs.'),
      b('Pekin multi-story differs from pure HOA growth', 'Seat stairs and curb plans are real cost drivers.'),
      b('Morton HOA soft costs are standard survey inputs', 'Gate lists and approved hours push demand into peak windows.'),
    ],
    zonesHeading: 'Tazewell zones: East Peoria multi-family, Pekin seat, Morton growth & southern lots',
    zonesIntro: 'Two to four sharp products — river multi-family, seat multi-story, growth HOAs, and southern lots.',
    zones: [
      z('east-peoria', 'East Peoria multi-family & retail corridors', 'East Peoria', ['East Peoria', 'retail multi-family', 'bridge approaches'], 'Multi-family, townhomes, SFH', ['Elevators', 'Bridge freeflow', 'Parking limits'], ['east peoria'], 'Confirm elevator rules; build bridge-peak buffers.'),
      z('pekin', 'Pekin multi-story & seat stock', 'Pekin', ['Pekin', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'IL-29 freeflow'], ['pekin'], 'Inventory stairs; plan temporary no-parking.'),
      z('morton', 'Morton HOA growth & multi-family', 'Morton', ['Morton', 'growth villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'I-74 freeflow'], ['morton'], 'Collect HOA COIs; prefer early starts.'),
      z('south-lots', 'Southern Tazewell larger lots', 'South lots', ['Delavan edges', 'southern tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['delavan', 'south tazewell'], 'Photo approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('bridge-freeflow', 'River-bridge freeflow to Peoria', 'South/east collar pairs still peak hard toward Peoria.', ['Price portal-to-portal honestly.', 'Clarify Peoria second addresses for drive-time assumptions.']),
      s('east-peoria-multi', 'East Peoria multi-family access', 'Elevators and parking are first-class cost drivers.', ['Collect COI and elevator reservations early.', 'Retail-corridor peaks rewrite quiet unload assumptions.']),
      s('pekin-seat', 'Pekin multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Tazewell families compare East Peoria, Pekin, Morton, Washington, and related district feeders — verify address boundaries; do not assume Peoria maps apply.',
    hospitalsDetail: 'OSF Saint Francis spillover, Pekin-area campuses, and Peoria specialty care serve the county; map peak bridge and I-74 times for ER access.',
    costIntro: 'Bridge freeflow, multi-family access, and HOA soft costs often matter more than raw miles.',
    seasonalIntro: 'School years, lease ends, and winter bridge ice reshape demand by pocket.',
  },
  {
    file: 'mclean-il.ts',
    exportName: 'mcleanCountyIlTier2Intelligence',
    slug: 'mclean',
    hubTitle: 'McLean County Moving Intelligence Hub',
    eyebrow: 'McLean · Bloomington–Normal — twin cities / I-55',
    h1: 'Moving in McLean County: Bloomington–Normal, Twin-City Access & I-55 / I-74 Logistics',
    heroOpener:
      'McLean County is central Illinois’s insurance and university twin-city market — Bloomington multi-story and professional stock, Normal multi-family and ISU-adjacent density, and freeflow on I-55 / I-74 that is not Springfield capital product or Champaign UIUC cycles with different labels. Expect twin-city empty miles, corporate calendars, and discontinuous outer towns under one county. This guide is for people moving in McLean as independent twin-city hub — not generic central IL boilerplate.',
    heroCredibility:
      'Bloomington–Normal twin cities · Insurance/university · I-55 / I-74 · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-55 · I-74 · I-39 · US-51 · Veterans Pkwy · College Avenue corridor',
    parentLabel: 'independent central Illinois (nearest hubs: Sangamon / Champaign)',
    parentHref: '/local-movers/illinois/sangamon',
    parentAltLabel: 'Champaign County',
    parentAltHref: '/local-movers/illinois/champaign',
    compareIntro:
      'McLean is Bloomington–Normal insurance/university twin-city product — not Springfield capital density and not Champaign UIUC campus cycles alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Springfield crews fight capital arterials and I-55 session peaks. McLean pairs ride I-55, I-74, and Veterans Parkway — freer mid-day twin-city freeflow, still peak-heavy on Normal university windows and Bloomington professional corridors.'),
      b('Housing stock differences', 'Springfield mixes capital multi-story and Chatham HOAs. McLean mixes Bloomington professional multi-unit, Normal student multi-family, and twin-city HOA growth — more continuous twin-city product, less continuous capital session density.'),
      b('Truck access & density', 'Campus multi-family needs COIs; professional multi-story needs curb plans; outer towns add empty miles.'),
      b('Rough cost posture (qualitative)', 'Local McLean quotes often track twin-city secondary-premium rates for multi-family access — term and corporate peaks push prices above quiet rural lots.'),
      b('Role difference', 'McLean is independent Bloomington–Normal twin-city hub — not capital or UIUC product renamed.'),
    ],
    whatIntro: 'Twin-city freeflow, ISU term calendars, and insurance/professional multi-family — not interchangeable capital or Champaign boilerplate.',
    whatBullets: [
      b('ISU and academic calendars drive Normal demand spikes', 'Move-in/out weekends fill crews near campus. Book early.'),
      b('Bloomington professional multi-story is first-class product', 'Elevators and curb plans need inventories different from pure SFH lots.'),
      b('I-55 / I-74 freeflow is still billable', 'Twin-city and long central IL pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Twin-city empty miles rewrite single-core rates', 'Bloomington ↔ Normal pairs fail when crews assume continuous single-city density.'),
    ],
    zonesHeading: 'McLean zones: Bloomington core, Normal campus edge, twin-city HOA growth & outer towns',
    zonesIntro: 'Two to four sharp products — professional multi-story, campus multi-family, HOA growth, and outer towns.',
    zones: [
      z('bloomington', 'Bloomington multi-story & professional stock', 'Bloomington', ['Bloomington', 'downtown edges', 'professional multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs/elevators', 'Street parking', 'I-55 freeflow'], ['bloomington'], 'Inventory access type; plan temporary no-parking.'),
      z('normal-campus', 'Normal / ISU campus-edge multi-family', 'Normal campus', ['Normal', 'campus multi-family', 'student stock'], 'Multi-family, apartments, some SFH', ['Term parking', 'COI packets', 'Elevators'], ['normal', 'illinois state'], 'Book around term calendars; collect building rules.'),
      z('twin-hoa', 'Twin-city HOA growth edges', 'HOA growth', ['growth villages', 'Veterans Pkwy edges'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'Arterial freeflow'], ['bloomington normal hoa'], 'Collect HOA COIs; prefer early starts.'),
      z('outer-towns', 'Outer McLean towns & rural lots', 'Outer towns', ['Heyworth edges', 'Lexington edges', 'rural tracts'], 'SFH, rural approaches', ['Empty miles', 'Soft shoulders'], ['heyworth', 'lexington il'], 'Survey approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('twin-city', 'Bloomington–Normal twin-city freeflow', 'Twin-city pairs still peak hard on arterials.', ['Price portal-to-portal honestly between cores.', 'Do not quote single-city day rates for cross-town pairs.']),
      s('isu-terms', 'ISU / university move-cycle module', 'Term calendars drive Normal demand spikes.', ['Book early around move-in/out weekends.', 'Price campus-edge curb time honestly.']),
      s('professional-multi', 'Bloomington professional multi-story', 'Elevators and curb plans are first-class cost drivers.', ['Collect COI and elevator reservations early.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'McLean families compare Unit 5, District 87, and related district feeders across Bloomington–Normal — verify address boundaries.',
    hospitalsDetail: 'Carle BroMenn, OSF St. Joseph, and related campuses anchor acute care; map peak twin-city arterial times for ER access.',
    costIntro: 'Twin-city freeflow, multi-family access, and term peaks often matter more than raw miles.',
    seasonalIntro: 'University calendars, corporate onboarding, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'champaign-il.ts',
    exportName: 'champaignCountyIlTier2Intelligence',
    slug: 'champaign',
    hubTitle: 'Champaign County Moving Intelligence Hub',
    eyebrow: 'Champaign · Champaign–Urbana — UIUC university independent',
    h1: 'Moving in Champaign County: Champaign–Urbana, UIUC Cycles & I-57 / I-74 Access',
    heroOpener:
      'Champaign County is central Illinois’s UIUC university twin-city market — Champaign multi-family and research-edge stock, Urbana multi-story and faculty housing, Savoy and Mahomet growth, and freeflow on I-57 / I-74 that is not Bloomington insurance twin-city product or Springfield capital density with different labels. Expect August lease spikes, campus walk-ups, and discontinuous outer towns under one county. This guide is for people moving in Champaign as independent UIUC market — not a McLean rename.',
    heroCredibility:
      'UIUC university market · Term calendars · I-57 / I-74 · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-57 · I-74 · US-45 · University Ave · Neil Street · Prospect Avenue',
    parentLabel: 'independent UIUC market (nearest hubs: McLean / Sangamon)',
    parentHref: '/local-movers/illinois/mclean',
    parentAltLabel: 'Sangamon County',
    parentAltHref: '/local-movers/illinois/sangamon',
    compareIntro:
      'Champaign is UIUC university twin-city product — not Bloomington–Normal insurance density and not Springfield capital calendars alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'McLean crews fight twin-city professional peaks. Champaign pairs ride I-57, I-74, and university arterials — freer mid-day between twin cities, still peak-heavy on August lease weekends and Campus Town windows.'),
      b('Housing stock differences', 'McLean mixes Bloomington professional multi-unit and Normal ISU multi-family. Champaign mixes Campus Town walk-ups, Urbana faculty stock, and Savoy HOA — more continuous UIUC product, less continuous insurance-hub density.'),
      b('Truck access & density', 'Campus walk-ups need stair inventories and parking permits; multi-family elevators appear on research edges; outer towns add empty miles.'),
      b('Rough cost posture (qualitative)', 'Local Champaign quotes often track university secondary-premium rates for multi-story access — August spikes push prices above quiet Mahomet driveway jobs.'),
      b('Role difference', 'Champaign is independent UIUC university market — not McLean or capital product renamed.'),
    ],
    whatIntro: 'UIUC lease cycles, Campus Town walk-ups, and I-57/I-74 freeflow — not interchangeable Bloomington or Springfield boilerplate.',
    whatBullets: [
      b('UIUC lease cycles dominate summer and mid-year demand', 'August move-in and May move-out fill campus-adjacent crews first. Book early.'),
      b('Campus Town multi-story is first-class product', 'Stairs, parking permits, and COIs need inventories different from pure SFH lots.'),
      b('I-57 / I-74 freeflow is still billable', 'Twin-city and long central IL pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Savoy / Mahomet growth differs from pure campus product', 'HOA packets rewrite Campus Town day-rate assumptions.'),
    ],
    zonesHeading: 'Champaign zones: Campus Town multi-story, Urbana multi-unit, Savoy/Mahomet growth & outer towns',
    zonesIntro: 'Two to four sharp products — campus multi-story, Urbana multi-unit, growth HOAs, and outer towns.',
    zones: [
      z('campus-town', 'Campus Town / Champaign multi-story', 'Campus Town', ['Campus Town', 'student multi-family', 'research-edge apartments'], 'Multi-story, multi-unit, elevators', ['Term parking', 'Stairs/elevators', 'COI packets'], ['champaign campus', 'uiuc'], 'Book around term calendars; collect building rules.'),
      z('urbana', 'Urbana multi-unit & faculty stock', 'Urbana', ['Urbana', 'faculty bungalows', 'multi-family'], 'Multi-unit, older SFH, townhomes', ['Stairs', 'Street parking', 'Mixed curb'], ['urbana'], 'Inventory stairs; prefer mid-week mornings when possible.'),
      z('savoy-mahomet', 'Savoy / Mahomet growth HOA', 'Savoy / Mahomet', ['Savoy', 'Mahomet', 'growth villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'I-57 freeflow'], ['savoy', 'mahomet'], 'Collect HOA COIs; prefer early starts.'),
      z('outer-towns', 'Rantoul / outer towns & rural lots', 'Outer towns', ['Rantoul', 'outer tracts'], 'SFH, multi-family, rural approaches', ['Empty miles', 'Soft shoulders'], ['rantoul'], 'Survey approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('uiuc-cycles', 'UIUC university move-cycle module', 'Term calendars drive demand spikes.', ['Book early around August and May windows.', 'Price campus-edge curb time honestly.']),
      s('campus-walkups', 'Campus Town multi-story access', 'Stairs and parking permits are first-class cost drivers.', ['Collect COI and elevator/stair inventories early.', 'Temporary no-parking often beats long carries.']),
      s('i57-i74', 'I-57 / I-74 freeflow', 'Twin-city and long pairs still peak hard.', ['Price portal-to-portal honestly.', 'Clarify McLean or Sangamon second addresses for long empty-mile assumptions.']),
    ],
    schoolsIntro: 'Champaign families compare Unit 4, Urbana, Mahomet-Seymour, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Carle Foundation Hospital, OSF Heart of Mary, and related campuses anchor acute care; map peak campus and I-74 times for ER access.',
    costIntro: 'Term peaks, multi-story access, and twin-city freeflow often matter more than raw miles.',
    seasonalIntro: 'University calendars, school years, and winter ice reshape demand more than pure corporate central IL patterns.',
  },
  {
    file: 'sangamon-il.ts',
    exportName: 'sangamonCountyIlTier2Intelligence',
    slug: 'sangamon',
    hubTitle: 'Sangamon County Moving Intelligence Hub',
    eyebrow: 'Sangamon · Springfield — state capital',
    h1: 'Moving in Sangamon County: Springfield Capital Access, Government Calendars & I-55 Logistics',
    heroOpener:
      'Sangamon County is central Illinois’s state capital market — Springfield multi-story and government-corridor density, Chatham and Rochester family growth, Sherman edges, and freeflow on I-55 / I-72 that is not Bloomington twin-city insurance product or Champaign UIUC cycles with different labels. Expect session-week demand, medical corridors, and discontinuous outer towns under one county. This guide is for people moving in Sangamon as independent capital — not generic central IL boilerplate.',
    heroCredibility:
      'Springfield capital · Government calendars · I-55 / I-72 · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-55 · I-72 · IL-4 · Clear Lake Ave · Wabash Ave · Dirksen Parkway',
    parentLabel: 'independent capital (nearest hubs: McLean / Peoria)',
    parentHref: '/local-movers/illinois/mclean',
    parentAltLabel: 'Peoria County',
    parentAltHref: '/local-movers/illinois/peoria',
    compareIntro:
      'Sangamon is Springfield capital government/residential product — not Bloomington–Normal twin-city density and not Peoria medical/industrial river product alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Twin-city and river-hub crews fight their own arterial peaks. Sangamon pairs ride I-55, I-72, and Clear Lake corridors — freer mid-day capital freeflow, still peak-heavy on session weeks and medical corridors.'),
      b('Housing stock differences', 'McLean mixes professional multi-unit and ISU multi-family. Sangamon mixes capital multi-story, West Side SFH, and Chatham HOA — more continuous government-city product, less continuous twin-city university density.'),
      b('Truck access & density', 'Downtown walk-ups need curb plans; medical multi-family needs COIs; Chatham HOAs add packets.'),
      b('Rough cost posture (qualitative)', 'Local Sangamon quotes often track capital secondary rates for multi-story access — session peaks push prices above quiet township driveway jobs.'),
      b('Role difference', 'Sangamon is independent Springfield capital — not twin-city or river-hub product renamed.'),
    ],
    whatIntro: 'Government calendars, capital multi-story, and I-55 freeflow — not interchangeable twin-city or university boilerplate.',
    whatBullets: [
      b('State government calendars reshape mid-week demand', 'Legislative session weeks and agency start dates create hard windows that compete with Saturday family demand.'),
      b('Springfield multi-story is first-class product', 'Walk-ups and medical multi-family need inventories different from pure Chatham cul-de-sacs.'),
      b('I-55 / I-72 freeflow is still billable', 'Capital pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Chatham / Rochester growth differs from pure capital core', 'HOA packets rewrite downtown day-rate assumptions.'),
    ],
    zonesHeading: 'Sangamon zones: capital multi-story, medical corridors, Chatham/Rochester growth & outer edges',
    zonesIntro: 'Two to four sharp products — capital multi-story, medical multi-family, growth HOAs, and outer edges.',
    zones: [
      z('capital-core', 'Springfield capital multi-story', 'Capital core', ['Downtown Springfield', 'near-capital multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Session peaks'], ['springfield capital'], 'Inventory stairs; avoid peak session-week curb when possible.'),
      z('medical', 'Medical multi-family corridors', 'Medical corridors', ['medical multi-family', 'Clear Lake edges'], 'Multi-family, apartments, townhomes', ['Elevators', 'COI packets', 'Shift windows'], ['springfield medical'], 'Confirm elevator reservations; allow flexible start times.'),
      z('chatham-rochester', 'Chatham / Rochester growth HOA', 'Growth HOA', ['Chatham', 'Rochester', 'growth villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'I-55 freeflow'], ['chatham', 'rochester il'], 'Collect HOA COIs; prefer early starts.'),
      z('outer-edges', 'Sherman / outer edges & rural lots', 'Outer edges', ['Sherman', 'Riverton edges', 'rural tracts'], 'SFH, rural approaches', ['Empty miles', 'Soft shoulders'], ['sherman', 'riverton'], 'Survey approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('gov-calendars', 'State government calendar module', 'Session weeks reshape mid-week demand.', ['Align surveys with agency start dates when possible.', 'Do not quote pure Saturday HOA rates for capital-core jobs.']),
      s('capital-multi', 'Springfield multi-story access', 'Walk-ups and elevators are first-class cost drivers.', ['Inventory floor counts and curb width.', 'Temporary no-parking often beats long carries.']),
      s('i55-capital', 'I-55 / I-72 capital freeflow', 'Capital pairs still peak hard on arterials.', ['Price portal-to-portal honestly.', 'Clarify McLean or Peoria second addresses for long empty-mile assumptions.']),
    ],
    schoolsIntro: 'Sangamon families compare Springfield, Ball-Chatham, Rochester, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Memorial Health, HSHS St. John’s, and related campuses anchor acute care; map peak capital and Clear Lake times for ER access.',
    costIntro: 'Session peaks, multi-story access, and I-55 freeflow often matter more than raw miles.',
    seasonalIntro: 'Legislative calendars, school years, and winter ice reshape demand more than pure university patterns.',
  },
  {
    file: 'rock-island-il.ts',
    exportName: 'rockIslandCountyIlTier2Intelligence',
    slug: 'rock-island',
    hubTitle: 'Rock Island County Moving Intelligence Hub',
    eyebrow: 'Rock Island · Rock Island / Moline — Quad Cities IL',
    h1: 'Moving in Rock Island County: Moline, Rock Island & Quad Cities River Access',
    heroOpener:
      'Rock Island County is the Illinois side of the Quad Cities river metro — Rock Island multi-story and older stock, Moline multi-family and professional corridors, East Moline and Silvis edges, and freeflow on I-74 / I-280 that is not Chicago collar product with different labels. Expect Mississippi bridge freeflow, Iowa-adjacent interstate risk, and discontinuous river-town stock under one county. This guide is for people moving in Rock Island as independent Quad Cities — not Chicago defaults.',
    heroCredibility:
      'Quad Cities IL · Mississippi river metro · I-74 / I-280 · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-74 · I-280 · I-88 · IL-5 · IL-92 · Avenue of the Cities',
    parentLabel: 'independent Quad Cities (vs Chicago / central IL defaults)',
    parentHref: '/local-movers/illinois/cook',
    parentAltLabel: 'Peoria County',
    parentAltHref: '/local-movers/illinois/peoria',
    compareIntro:
      'Rock Island is independent Quad Cities river-metro product — not Chicago elevator density and not Peoria central IL river product alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Chicago crews fight I-90/I-294 peaks. Rock Island pairs ride I-74, I-280, and river bridges — freer mid-day Quad Cities freeflow, still peak-heavy on Moline arterials and bridge windows into Iowa.'),
      b('Housing stock differences', 'Chicago mixes high-rises and dense multi-family. Rock Island mixes river-town multi-story, Moline multi-unit, and Silvis/East Moline SFH — more continuous river-metro product, less continuous Chicago vertical density.'),
      b('Truck access & density', 'River-town streets need curb plans; multi-family elevators appear on Moline corridors; IA addresses flip authority.'),
      b('Rough cost posture (qualitative)', 'Local Rock Island quotes often track Quad Cities secondary rates for multi-story access — bridge peaks and interstate legs can price above quiet inland driveway jobs.'),
      b('Role difference', 'Rock Island is independent Quad Cities IL — not Chicago or Peoria product renamed.'),
    ],
    whatIntro: 'River-bridge freeflow, Quad Cities multi-story, and IA interstate risk — not interchangeable Chicago boilerplate.',
    whatBullets: [
      b('Mississippi bridge freeflow is still billable', 'Quad Cities pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Rock Island / Moline multi-story is first-class product', 'Stairs and curb plans need inventories different from pure SFH lots.'),
      b('Iowa adjacency creates interstate legs', 'IA addresses require FMCSA authority even on short-looking hops.'),
      b('Discontinuous river towns add empty miles', 'Silvis and rural edges fail when crews assume continuous Moline density.'),
    ],
    zonesHeading: 'Rock Island zones: Rock Island multi-story, Moline multi-family, East Moline/Silvis edges & rural lots',
    zonesIntro: 'Two to four sharp products — river multi-story, multi-family corridors, east edges, and rural lots.',
    zones: [
      z('rock-island', 'Rock Island multi-story & older stock', 'Rock Island', ['Rock Island', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Bridge freeflow'], ['rock island'], 'Inventory stairs; plan temporary no-parking.'),
      z('moline', 'Moline multi-family & professional corridors', 'Moline', ['Moline', 'Avenue of the Cities multi-family'], 'Multi-family, apartments, townhomes, SFH', ['Elevators', 'Parking limits', 'I-74 freeflow'], ['moline'], 'Confirm elevator rules; build arterial buffers.'),
      z('east-moline', 'East Moline / Silvis edges', 'East Moline / Silvis', ['East Moline', 'Silvis', 'edge multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['east moline', 'silvis'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-lots', 'Southern & rural lots', 'Rural lots', ['southern tracts', 'rural approaches'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['south rock island'], 'Photo approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('qc-bridges', 'Quad Cities bridge freeflow', 'River pairs still peak hard; IA legs need FMCSA.', ['Price portal-to-portal honestly.', 'Clarify Iowa second addresses for interstate authority.']),
      s('river-multi', 'Rock Island / Moline multi-story access', 'Stairs and elevators are first-class cost drivers.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('ia-edge', 'Iowa-edge interstate module', 'Short map miles can still be interstate jobs.', ['Match ICC vs FMCSA to exact addresses.', 'Do not recycle Chicago day rates for Quad Cities product.']),
    ],
    schoolsIntro: 'Rock Island families compare Rock Island, Moline-Coal Valley, East Moline, Silvis, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'UnityPoint Health Quad Cities campuses and related specialty care serve the county; map peak bridge and I-74 times for ER access.',
    costIntro: 'Bridge freeflow, multi-story access, and interstate authority risk often matter more than raw miles.',
    seasonalIntro: 'School years, lease ends, river flood windows, and winter ice reshape demand by pocket.',
  },
  {
    file: 'lasalle-il.ts',
    exportName: 'lasalleCountyIlTier2Intelligence',
    slug: 'lasalle',
    hubTitle: 'LaSalle County Moving Intelligence Hub',
    eyebrow: 'LaSalle · Ottawa / Peru / LaSalle — Illinois Valley',
    h1: 'Moving in LaSalle County: Ottawa, Peru & Illinois Valley I-80 Access',
    heroOpener:
      'LaSalle County is Illinois Valley town product on I-80 — Ottawa multi-story and seat stock, Peru and LaSalle multi-unit corridors, Streator and Mendota edges, and freeflow that is not Grundy Morris industrial-edge product with different labels. Expect discontinuous valley towns, longer empty miles between seats, and mixed industrial-residential fabric under one county. This guide is for people moving in LaSalle as Illinois Valley secondary — not a Grundy rename.',
    heroCredibility:
      'Illinois Valley · Ottawa / Peru / LaSalle · I-80 valley towns · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-80 · I-39 · US-6 · US-51 · IL-23 · IL-71 · IL-251',
    parentLabel: 'Grundy County',
    parentHref: '/local-movers/illinois/grundy',
    compareIntro:
      'LaSalle is Illinois Valley multi-town product on I-80 — not Grundy Morris industrial-edge density alone and not pure rural prairie freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Grundy crews fight Morris arterials and I-80 industrial peaks. LaSalle pairs ride I-80, US-6, and IL-23 across discontinuous valley towns — freer mid-day between towns, still peak-heavy on Ottawa and Peru arterials.'),
      b('Housing stock differences', 'Grundy mixes Morris multi-story and industrial-edge SFH. LaSalle mixes Ottawa multi-unit, Peru/LaSalle multi-story, and Streator/Mendota stock — more multi-town valley product, less continuous single-seat industrial density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; town-to-town empty miles dominate; rural edges add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local LaSalle quotes often sit at valley secondary rates for driveway SFH — multi-story access and long empty-mile town pairs still push prices up.'),
      b('Role difference', 'LaSalle is Illinois Valley multi-town secondary — not Grundy/Morris product renamed.'),
    ],
    whatIntro: 'Valley multi-story, I-80 freeflow, and town-to-town empty miles — not interchangeable Morris boilerplate.',
    whatBullets: [
      b('Ottawa multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('Discontinuous valley towns add empty miles', 'Peru ↔ Ottawa pairs fail when crews assume continuous single-seat density.'),
      b('I-80 freeflow is still billable', 'Valley pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Distinct from Grundy industrial-edge assumptions', 'Do not recycle Morris energy-corridor day rates alone.'),
    ],
    zonesHeading: 'LaSalle zones: Ottawa seat, Peru/LaSalle multi-unit, Streator/Mendota edges & rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, twin multi-unit, outer towns, and rural lots.',
    zones: [
      z('ottawa', 'Ottawa multi-story & seat stock', 'Ottawa', ['Ottawa', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-80 freeflow'], ['ottawa'], 'Inventory stairs; plan temporary no-parking.'),
      z('peru-lasalle', 'Peru / LaSalle multi-unit corridors', 'Peru / LaSalle', ['Peru', 'LaSalle', 'multi-family corridors'], 'Multi-unit, twins, older SFH', ['Mixed curb', 'Arterial timing', 'Empty miles'], ['peru', 'lasalle'], 'Survey street width; prefer early starts for town pairs.'),
      z('streator-mendota', 'Streator / Mendota outer towns', 'Outer towns', ['Streator', 'Mendota', 'outer multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['streator', 'mendota'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-lots', 'Rural valley lots & edges', 'Rural lots', ['rural tracts', 'valley edges'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['rural lasalle'], 'Photo approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('valley-distinct', 'Illinois Valley vs Grundy/Morris', 'LaSalle is a multi-town valley market, not a single industrial seat.', ['Do not recycle Morris energy-corridor day rates alone.', 'Price town-to-town empty miles honestly.']),
      s('i80-valley', 'I-80 valley freeflow', 'Valley pairs still peak hard between discontinuous towns.', ['Build corridor buffers for morning and evening peaks.', 'Clarify Grundy second addresses for drive-time assumptions.']),
      s('ottawa-seat', 'Ottawa multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts and hill approaches where present.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'LaSalle families compare Ottawa, LaSalle-Peru, Streator, Mendota, and related district feeders — verify address boundaries; do not assume Grundy maps apply.',
    hospitalsDetail: 'OSF Saint Elizabeth and regional specialty spillover serve the county; map peak freeflow across discontinuous valley towns.',
    costIntro: 'Town multi-story, I-80 freeflow, and valley empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, lease ends, and winter ice reshape demand by pocket.',
  },
];
