import { type PackDef, z, s, b } from './il-tier2-render';

/** IL Tier 2 Wave 1 packs 1–6 */
export const packsA: PackDef[] = [
  {
    file: 'kendall-il.ts',
    exportName: 'kendallCountyIlTier2Intelligence',
    slug: 'kendall',
    hubTitle: 'Kendall County Moving Intelligence Hub',
    eyebrow: 'Kendall · Oswego / Yorkville — southwest collar growth',
    h1: 'Moving in Kendall County: Oswego, Yorkville & Outer-Collar US-34 Growth',
    heroOpener:
      'Kendall County is Chicagoland’s southwest outer-collar growth market — Oswego multi-family and HOA spillover, Yorkville seat stock, Montgomery edges, and freeflow on US-34 / I-88 links that is not Will County Joliet product with different labels. Expect master-plan gate lists, longer empty miles from Will/Kane yards, and driveway HOA density that prices differently from continuous Will industrial-residential corridors. This guide is for people moving in Kendall as outer-collar growth — not a Will rename.',
    heroCredibility:
      'Southwest outer collar · HOA growth · US-34 / I-88 · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-34 · IL-47 · IL-71 · I-88 links · IL-126',
    parentLabel: 'Will County',
    parentHref: '/local-movers/illinois/will',
    parentAltLabel: 'Kane County',
    parentAltHref: '/local-movers/illinois/kane',
    compareIntro:
      'Kendall is outer-collar HOA growth on US-34 — not Will Joliet industrial-residential density and not pure rural prairie freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Will crews fight I-55/I-80 peaks into Joliet and south-collar arterials. Kendall pairs ride US-34, IL-47, and I-88 links — freer mid-day further southwest, still peak-heavy toward Will/Kane portals and Oswego commute windows. Portal-to-portal time is real; it is not a Joliet multi-story day.'),
      b('Housing stock differences', 'Will mixes Joliet multi-story, industrial multi-family, and south-collar HOAs. Kendall mixes Oswego planned SFH, Yorkville multi-family, and Montgomery edges — more continuous outer-collar HOA product, less continuous Will industrial density.'),
      b('Truck access & density', 'HOA COIs, gate lists, and approved hours dominate more often than older Will seat curb plans. Rural southern lots add soft shoulders uncommon on dense Will arterials.'),
      b('Rough cost posture (qualitative)', 'Local Kendall quotes often track outer-collar suburb rates for driveway SFH — empty miles from Will/Kane staging and HOA soft costs still push prices up vs map miles alone.'),
      b('Role difference', 'Kendall is southwest outer-collar growth — not Will County product renamed.'),
    ],
    whatIntro: 'Outer-collar HOA density, US-34 freeflow, and empty miles from Will/Kane yards — not interchangeable Joliet boilerplate.',
    whatBullets: [
      b('US-34 / I-88 peaks rewrite short-looking locals', 'Kendall ↔ Will pairs freer mid-day still burn clock at commute peaks. Ask portal-to-portal.'),
      b('Master-plan HOA is first-class product', 'Gate lists, truck limits, and approved hours are standard on Oswego growth villages.'),
      b('Empty miles from Will/Kane yards are real', 'Even “local” Kendall pairs can price as distance work for Joliet- or Aurora-based crews.'),
      b('Yorkville multi-family differs from pure HOA cul-de-sacs', 'Seat stairs and curb plans need inventories different from brand-new villages.'),
    ],
    zonesHeading: 'Kendall zones: Oswego growth, Yorkville seat, Montgomery edges & southern rural lots',
    zonesIntro: 'Two to four sharp products — growth HOAs, seat multi-family, edge stock, and rural lots.',
    zones: [
      z('oswego-growth', 'Oswego multi-family & HOA growth', 'Oswego', ['Oswego', 'growth villages', 'US-34 multi-family'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'US-34 peaks', 'Lease clusters'], ['oswego'], 'Collect HOA COIs; build US-34 buffer for Will pairs.'),
      z('yorkville', 'Yorkville seat multi-family & older stock', 'Yorkville', ['Yorkville', 'downtown edges', 'seat multi-family'], 'Multi-family, older SFH, townhomes', ['Stairs', 'Street parking', 'Mixed curb'], ['yorkville'], 'Photo curb; confirm elevator vs stair access.'),
      z('montgomery', 'Montgomery / northern edges toward Kane', 'Montgomery edge', ['Montgomery edges', 'northern tracts'], 'HOA SFH, multi-family', ['IL-47 freeflow', 'HOA rules'], ['montgomery'], 'Clarify Kane or Will second addresses early.'),
      z('south-rural', 'Southern Kendall rural-edge lots', 'South rural', ['southern tracts', 'Plano edges'], 'SFH, rural-edge lots', ['Empty miles', 'Soft shoulders'], ['plano', 'south kendall'], 'Survey truck access; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('hoa-outer', 'Outer-collar HOA growth module', 'Master-plan rules dominate Kendall family volume.', ['Collect COI and gate lists before the estimate is final.', 'Saturday HOA windows push demand into peak crew slots.']),
      s('us34-freeflow', 'US-34 / I-88 freeflow', 'Outer-collar pairs still peak hard toward Will and Kane.', ['Price portal-to-portal honestly.', 'Clarify Will or Kane second addresses for drive-time assumptions.']),
      s('yorkville-access', 'Yorkville seat multi-family access', 'Seat density differs from pure cul-de-sac HOAs.', ['Inventory stairs and street width.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Kendall families compare Oswego, Yorkville, Plano, and related district feeders — verify address boundaries; do not assume Will or Kane maps apply.',
    hospitalsDetail: 'Rush Copley edges, Morris Hospital spillover, and Chicago specialty access serve the county; map peak US-34 / I-88 times for ER access.',
    costIntro: 'HOA soft costs, US-34 freeflow, and empty miles from Will/Kane yards often matter more than raw miles.',
    seasonalIntro: 'School years and summer family closings reshape demand more than Will industrial calendars alone.',
  },
  {
    file: 'dekalb-il.ts',
    exportName: 'dekalbCountyIlTier2Intelligence',
    slug: 'dekalb',
    hubTitle: 'DeKalb County Moving Intelligence Hub',
    eyebrow: 'DeKalb · DeKalb / Sycamore — NIU university',
    h1: 'Moving in DeKalb County: DeKalb, NIU Cycles & I-88 West University Access',
    heroOpener:
      'DeKalb County is an I-88 west university market — DeKalb multi-story and near-NIU density, Sycamore seat multi-family, Genoa and Sandwich edges, and freeflow that is not Kane County Aurora HOA product with different labels. Expect term calendars, student multi-family COIs, and longer empty miles under one county. This guide is for people moving in DeKalb as NIU university secondary — not a Chicago-suburb rename.',
    heroCredibility:
      'NIU university market · Term calendars · I-88 west · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-88 · IL-23 · IL-38 · IL-64 · Peace Road corridor',
    parentLabel: 'Kane County',
    parentHref: '/local-movers/illinois/kane',
    compareIntro:
      'DeKalb is NIU university-town product on I-88 west — not Kane Aurora/Elgin multi-family growth alone and not pure rural prairie freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Kane crews fight Randall Road and I-88 peaks into Aurora/Elgin. DeKalb pairs ride I-88, IL-23, and IL-38 — freer mid-day further west, still peak-heavy on DeKalb arterials and term weekends. Portal-to-portal time is real; it is not a pure Kane HOA day.'),
      b('Housing stock differences', 'Kane mixes Aurora multi-family and west-collar HOAs. DeKalb mixes near-campus multi-story, Sycamore multi-unit, and rural-edge lots — more university-town product, less continuous Kane growth density.'),
      b('Truck access & density', 'Campus-adjacent streets need curb plans and temporary no-parking; term weekends rewrite staging; rural edges add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local DeKalb quotes often track secondary west-corridor rates for multi-story access — term peaks push prices above quiet Sycamore driveway jobs.'),
      b('Role difference', 'DeKalb is NIU university independent secondary — not Kane collar product renamed.'),
    ],
    whatIntro: 'University term calendars, near-campus multi-story, and I-88 freeflow — not interchangeable Kane boilerplate.',
    whatBullets: [
      b('NIU term calendars drive demand spikes', 'Move-in/out weekends fill crews and parking near campus. Book early.'),
      b('Near-campus multi-story is first-class product', 'Stairs, elevators, and COIs need inventories different from pure SFH lots.'),
      b('Sycamore seat density differs from pure growth HOAs', 'Mixed curb plans rewrite truck type assumptions.'),
      b('I-88 freeflow is still billable', 'DeKalb ↔ Kane pairs freer mid-day still peak hard. Ask portal-to-portal.'),
    ],
    zonesHeading: 'DeKalb zones: NIU campus edge, DeKalb multi-unit, Sycamore seat & rural edges',
    zonesIntro: 'Two to four sharp products — campus multi-story, city multi-unit, seat stock, and rural edges.',
    zones: [
      z('niu-edge', 'NIU campus-edge multi-story', 'NIU edge', ['DeKalb near campus', 'student multi-family'], 'Multi-story, multi-unit', ['Term parking', 'Stairs/elevators', 'COI packets'], ['dekalb niu', 'northern illinois'], 'Book around term calendars; collect building rules.'),
      z('dekalb-core', 'DeKalb multi-unit & older stock', 'DeKalb core', ['DeKalb', 'downtown edges', 'mixed multi-family'], 'Multi-unit, older SFH, townhomes', ['Stairs', 'Street parking', 'I-88 freeflow'], ['dekalb'], 'Inventory access type; prefer mid-week mornings when possible.'),
      z('sycamore', 'Sycamore seat multi-family & SFH', 'Sycamore', ['Sycamore', 'seat multi-family', 'growth edges'], 'SFH, multi-family, mixed stock', ['Arterial timing', 'HOA packets'], ['sycamore'], 'Prefer early starts; collect HOA docs where applicable.'),
      z('rural-edge', 'Genoa / Sandwich / rural edges', 'Rural edge', ['Genoa', 'Sandwich edges', 'rural tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['genoa', 'sandwich'], 'Survey approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('niu-terms', 'NIU university move-cycle module', 'Term calendars drive demand spikes.', ['Book early around move-in/out weekends.', 'Price campus-edge curb time honestly.']),
      s('campus-multi', 'Near-campus multi-story access', 'Elevators and stairs are first-class cost drivers.', ['Collect COI and elevator reservations early.', 'Temporary no-parking often beats long carries.']),
      s('i88-west', 'I-88 west freeflow', 'West-corridor pairs still peak hard toward Kane.', ['Price portal-to-portal honestly.', 'Clarify Kane second addresses early.']),
    ],
    schoolsIntro: 'DeKalb families compare DeKalb, Sycamore, Genoa-Kingston, and related district feeders — verify address boundaries; do not assume Kane maps apply.',
    hospitalsDetail: 'Northwestern Medicine Kishwaukee Hospital and regional specialty spillover serve the county; map peak term and I-88 times for ER access.',
    costIntro: 'Term peaks, multi-story access, and I-88 freeflow often matter more than raw miles.',
    seasonalIntro: 'University calendars, school years, and winter ice reshape demand more than pure collar HOA patterns.',
  },
  {
    file: 'grundy-il.ts',
    exportName: 'grundyCountyIlTier2Intelligence',
    slug: 'grundy',
    hubTitle: 'Grundy County Moving Intelligence Hub',
    eyebrow: 'Grundy · Morris — I-80 southwest industrial/residential',
    h1: 'Moving in Grundy County: Morris, I-80 Energy Edge & Southwest Industrial Access',
    heroOpener:
      'Grundy County is I-80 southwest industrial-residential product — Morris multi-story and seat stock, energy/industrial corridor freeflow, Coal City and Minooka edges, and empty miles that are not Will County continuous suburb with different labels. Expect plant and energy calendars, mixed mill-era stock, and I-80 portal time under one county. This guide is for people moving in Grundy as I-80 industrial edge — not a Will rename.',
    heroCredibility:
      'I-80 industrial edge · Morris seat · Energy/residential mix · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-80 · IL-47 · IL-113 · US-6 · IL-170',
    parentLabel: 'Will County',
    parentHref: '/local-movers/illinois/will',
    compareIntro:
      'Grundy is I-80 energy/industrial edge residential — not Will continuous south-collar HOA density and not pure rural prairie freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Will crews fight I-55/I-80 peaks into Joliet. Grundy pairs ride I-80, IL-47, and US-6 — freer mid-day west of Will density, still peak-heavy on Morris arterials and industrial shift windows.'),
      b('Housing stock differences', 'Will mixes Joliet multi-story and south-collar HOAs. Grundy mixes Morris multi-unit, industrial-edge SFH, and Coal City/Minooka stock — more energy-corridor product, less continuous Will growth density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; industrial-adjacent streets rewrite truck type; rural edges add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Grundy quotes often sit at I-80 secondary rates for driveway SFH — multi-story access and industrial freeflow still push prices up.'),
      b('Role difference', 'Grundy is I-80 southwest industrial/residential edge — not Will product renamed.'),
    ],
    whatIntro: 'I-80 freeflow, Morris multi-story, and energy-corridor calendars — not interchangeable Will boilerplate.',
    whatBullets: [
      b('I-80 freeflow is still billable', 'Grundy ↔ Will pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Morris multi-story is first-class product', 'Seat stairs need inventories different from pure industrial-edge lots.'),
      b('Energy and plant calendars reshape mid-week demand', 'Shift patterns rewrite pure Saturday residential assumptions.'),
      b('Discontinuous towns add empty miles', 'Coal City and Minooka pairs fail when crews assume continuous Will density.'),
    ],
    zonesHeading: 'Grundy zones: Morris seat, industrial corridor, Minooka/Coal City edges & rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, industrial edges, corridor towns, and rural lots.',
    zones: [
      z('morris-seat', 'Morris multi-story & seat stock', 'Morris', ['Morris', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-80 freeflow'], ['morris'], 'Inventory stairs; plan temporary no-parking.'),
      z('industrial', 'I-80 industrial / energy-edge residential', 'Industrial edge', ['industrial-adjacent SFH', 'energy corridor edges'], 'SFH, multi-family, mixed stock', ['Shift traffic', 'Arterial timing', 'Mixed access'], ['grundy industrial'], 'Prefer early starts; survey last-mile on industrial streets.'),
      z('minooka-coal', 'Minooka / Coal City corridor towns', 'Minooka / Coal City', ['Minooka edges', 'Coal City', 'corridor multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['minooka', 'coal city'], 'Prefer early starts for long pairs; confirm driveway depth.'),
      z('rural-lots', 'Southern & western rural lots', 'Rural lots', ['southern tracts', 'western lots'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['south grundy', 'west grundy'], 'Photo approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('i80-edge', 'I-80 industrial-edge freeflow', 'Southwest pairs still peak hard toward Will.', ['Price portal-to-portal honestly.', 'Build buffers for industrial shift windows.']),
      s('morris-seat', 'Morris multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('energy-calendars', 'Energy / plant calendar module', 'Industrial calendars reshape mid-week demand.', ['Clarify hard report dates early.', 'Do not quote pure Will HOA Saturday rates for plant-adjacent jobs.']),
    ],
    schoolsIntro: 'Grundy families compare Morris, Minooka, Coal City, and related district feeders — verify address boundaries; do not assume Will maps apply.',
    hospitalsDetail: 'Morris Hospital and Joliet specialty spillover serve the county; map peak I-80 times for ER access.',
    costIntro: 'I-80 freeflow, multi-story access, and industrial empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, plant calendars, and winter ice reshape demand by pocket.',
  },
  {
    file: 'kankakee-il.ts',
    exportName: 'kankakeeCountyIlTier2Intelligence',
    slug: 'kankakee',
    hubTitle: 'Kankakee County Moving Intelligence Hub',
    eyebrow: 'Kankakee · Kankakee / Bradley — south of Will',
    h1: 'Moving in Kankakee County: Kankakee, Bradley & I-57 South Regional Access',
    heroOpener:
      'Kankakee County is I-57 south regional product — Kankakee multi-story and seat stock, Bradley multi-family, Bourbonnais edges, and freeflow that is not Will continuous south-collar suburb with different labels. Expect river-city stairs, regional empty miles, and medical/industrial calendars under one county. This guide is for people moving in Kankakee as I-57 south regional hub — not a south-Cook or Will rename.',
    heroCredibility:
      'I-57 south regional · Kankakee / Bradley · River-city access · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-57 · US-45 · US-52 · IL-17 · IL-50 · IL-113',
    parentLabel: 'Will County',
    parentHref: '/local-movers/illinois/will',
    compareIntro:
      'Kankakee is I-57 south regional river-city product — not Will continuous HOA growth and not pure rural prairie freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Will crews fight I-55/I-80 south-collar peaks. Kankakee pairs ride I-57, US-45, and IL-50 — freer mid-day further south, still peak-heavy on Kankakee arterials and Bradley multi-family corridors.'),
      b('Housing stock differences', 'Will mixes Joliet multi-story and south-collar HOAs. Kankakee mixes seat multi-story, Bradley multi-unit, and Bourbonnais SFH — more discontinuous regional product, less continuous Will growth density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; multi-family elevators appear on Bradley corridors; rural edges add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Kankakee quotes often sit at I-57 secondary rates for driveway SFH — multi-story access and long empty-mile pairs still push prices up.'),
      b('Role difference', 'Kankakee is I-57 south regional hub — not Will or south-Cook product renamed.'),
    ],
    whatIntro: 'I-57 freeflow, river-city multi-story, and Bradley multi-family — not interchangeable Will boilerplate.',
    whatBullets: [
      b('I-57 freeflow is still billable', 'Kankakee ↔ Will pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Kankakee multi-story is first-class product', 'Seat stairs need inventories different from Bourbonnais cul-de-sacs.'),
      b('Bradley multi-family differs from pure SFH lots', 'Elevators and parking plans rewrite day-rate assumptions.'),
      b('Regional empty miles rewrite continuous-suburb rates', 'Far edges fail when crews assume Will collar density.'),
    ],
    zonesHeading: 'Kankakee zones: Kankakee seat, Bradley multi-family, Bourbonnais edges & rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, multi-family corridor, growth edges, and rural lots.',
    zones: [
      z('kankakee-seat', 'Kankakee multi-story & river-city stock', 'Kankakee', ['Kankakee', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-57 freeflow'], ['kankakee'], 'Inventory stairs; plan temporary no-parking.'),
      z('bradley', 'Bradley multi-family corridors', 'Bradley', ['Bradley', 'multi-family corridors'], 'Multi-family, apartments, townhomes', ['Elevators', 'Parking limits', 'Lease clusters'], ['bradley'], 'Confirm elevator rules; collect building packets.'),
      z('bourbonnais', 'Bourbonnais / growth edges', 'Bourbonnais', ['Bourbonnais', 'growth SFH', 'college edges'], 'SFH, multi-family, mixed stock', ['HOA packets', 'Arterial timing'], ['bourbonnais'], 'Collect HOA docs where applicable; prefer early starts.'),
      z('rural-lots', 'Southern & eastern rural lots', 'Rural lots', ['Manteno edges', 'southern tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['manteno', 'south kankakee'], 'Photo approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('i57-south', 'I-57 south regional freeflow', 'South pairs still peak hard toward Will.', ['Price portal-to-portal honestly.', 'Clarify Will second addresses early.']),
      s('seat-multi', 'Kankakee river-city multi-story', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('bradley-multi', 'Bradley multi-family access', 'Elevators and parking are first-class cost drivers.', ['Collect COI and elevator reservations early.', 'Lease clusters stack around month-end.']),
    ],
    schoolsIntro: 'Kankakee families compare Kankakee, Bradley, Bourbonnais, Manteno, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Riverside Medical Center / Ascendium and Joliet specialty spillover serve the county; map peak I-57 times for ER access.',
    costIntro: 'I-57 freeflow, multi-story access, and multi-family soft costs often matter more than raw miles.',
    seasonalIntro: 'School years, lease ends, and winter ice reshape demand by pocket.',
  },
  {
    file: 'boone-il.ts',
    exportName: 'booneCountyIlTier2Intelligence',
    slug: 'boone',
    hubTitle: 'Boone County Moving Intelligence Hub',
    eyebrow: 'Boone · Belvidere — Rockford east / I-90',
    h1: 'Moving in Boone County: Belvidere, Auto Manufacturing Edge & I-90 East Access',
    heroOpener:
      'Boone County is Rockford’s eastern I-90 manufacturing collar — Belvidere multi-story and seat stock, auto/industrial calendars, Poplar Grove and Capron edges, and freeflow that is not Winnebago continuous Rockford core with different labels. Expect plant report dates, mixed industrial-residential fabric, and Wisconsin-adjacent interstate risk under one county. This guide is for people moving in Boone as Rockford east collar — not a Rockford rename.',
    heroCredibility:
      'Rockford east collar · Belvidere manufacturing · I-90 · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-90 · US-20 · IL-76 · IL-173 · Business 20',
    parentLabel: 'Winnebago County',
    parentHref: '/local-movers/illinois/winnebago',
    compareIntro:
      'Boone is Rockford east I-90 manufacturing collar — not Winnebago Rockford core multi-story alone and not pure rural northern freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Winnebago crews fight Rockford arterials and I-39/I-90 peaks. Boone pairs ride I-90, US-20, and IL-76 — freer mid-day east of the city, still peak-heavy on Belvidere arterials and plant shift windows.'),
      b('Housing stock differences', 'Winnebago mixes Rockford multi-story and north/west HOAs. Boone mixes Belvidere multi-unit, manufacturing-edge SFH, and rural lots — more auto-corridor product, less continuous Rockford core density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; industrial-adjacent streets rewrite truck type; WI adjacency flips authority.'),
      b('Rough cost posture (qualitative)', 'Local Boone quotes often sit near Rockford-east secondary rates for driveway SFH — multi-story access and empty miles still push prices up.'),
      b('Role difference', 'Boone is Rockford east manufacturing collar — not Winnebago core renamed.'),
    ],
    whatIntro: 'I-90 freeflow, Belvidere multi-story, and auto-plant calendars — not interchangeable Rockford boilerplate.',
    whatBullets: [
      b('I-90 freeflow is still billable', 'Boone ↔ Winnebago pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Belvidere multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('Auto/manufacturing calendars reshape mid-week demand', 'Plant report dates compete with Saturday family windows.'),
      b('Wisconsin adjacency creates interstate legs', 'WI addresses require FMCSA authority even on short-looking hops.'),
    ],
    zonesHeading: 'Boone zones: Belvidere seat, manufacturing edge, Poplar Grove corridor & rural lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, industrial edges, corridor towns, and rural lots.',
    zones: [
      z('belvidere', 'Belvidere multi-story & seat stock', 'Belvidere', ['Belvidere', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-90 freeflow'], ['belvidere'], 'Inventory stairs; plan temporary no-parking.'),
      z('auto-edge', 'Auto / manufacturing-edge residential', 'Auto edge', ['plant-adjacent SFH', 'industrial multi-family'], 'SFH, multi-family, mixed stock', ['Shift traffic', 'Arterial timing'], ['belvidere industrial'], 'Prefer early starts; clarify hard report dates.'),
      z('poplar-grove', 'Poplar Grove / Capron corridor', 'Poplar Grove', ['Poplar Grove', 'Capron edges'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['poplar grove', 'capron'], 'Prefer early starts for long pairs.'),
      z('rural-lots', 'Northern & eastern rural lots', 'Rural lots', ['northern tracts', 'eastern lots'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Winter ice'], ['north boone', 'east boone'], 'Photo approaches; winter mornings need flexibility.'),
    ],
    specialized: [
      s('i90-east', 'I-90 Rockford-east freeflow', 'East-collar pairs still peak hard toward Winnebago.', ['Price portal-to-portal honestly.', 'Clarify WI second addresses for interstate authority.']),
      s('auto-calendars', 'Auto manufacturing calendar module', 'Plant windows reshape mid-week demand.', ['Align surveys with report dates when possible.', 'Do not quote pure Rockford Saturday rates for plant-adjacent jobs.']),
      s('belvidere-seat', 'Belvidere multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Boone families compare Belvidere, North Boone, and related district feeders — verify address boundaries; do not assume Rockford maps apply.',
    hospitalsDetail: 'Belvidere-area clinics and Rockford specialty spillover serve the county; map peak I-90 times for ER access.',
    costIntro: 'I-90 freeflow, multi-story access, and manufacturing empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, plant calendars, and winter ice reshape demand by pocket.',
  },
  {
    file: 'peoria-il.ts',
    exportName: 'peoriaCountyIlTier2Intelligence',
    slug: 'peoria',
    hubTitle: 'Peoria County Moving Intelligence Hub',
    eyebrow: 'Peoria · central Illinois medical/industrial river hub',
    h1: 'Moving in Peoria County: River Medical Hub, Bluff Access & I-74 Logistics',
    heroOpener:
      'Peoria County is central Illinois’s medical and manufacturing river hub — Peoria multi-story and medical-corridor density, Peoria Heights bluff access, Dunlap growth HOAs, and freeflow on I-74 / I-474 that is not Chicago collar product with different labels. Expect hospital calendars, river-bridge freeflow toward Tazewell, and discontinuous stock under one county. This guide is for people moving in Peoria as independent central IL hub — not Chicago defaults.',
    heroCredibility:
      'Central IL river hub · Medical/industrial · I-74 / bluffs · ICC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-74 · I-474 · IL-29 · US-24 · IL-6 · War Memorial Drive',
    parentLabel: 'independent central Illinois (nearest downstate hubs: Sangamon / McLean)',
    parentHref: '/local-movers/illinois/sangamon',
    parentAltLabel: 'McLean County',
    parentAltHref: '/local-movers/illinois/mclean',
    compareIntro:
      'Peoria is independent central IL medical/industrial river product — not Springfield capital density and not Bloomington twin-city insurance product alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Capital and twin-city crews fight I-55 peaks. Peoria pairs ride I-74, I-474, and IL-29 — freer mid-day river-metro freeflow, still peak-heavy on medical corridors and bluff approaches. Portal-to-portal time is real; it is not a Chicago elevator day.'),
      b('Housing stock differences', 'Springfield mixes capital multi-story and Chatham HOAs. Peoria mixes medical multi-family, Heights bluff stock, and Dunlap HOA — more river-bluff product, less continuous capital session density.'),
      b('Truck access & density', 'Bluff streets need grade surveys and smaller trucks; medical multi-family needs COIs; Dunlap HOAs add packets.'),
      b('Rough cost posture (qualitative)', 'Local Peoria quotes often track central IL hub rates for multi-story access — bluff shuttles and hospital windows can price above quiet Dunlap driveway jobs.'),
      b('Role difference', 'Peoria is independent central IL river medical/industrial hub — not Chicago or capital product renamed.'),
    ],
    whatIntro: 'Medical calendars, river bluffs, and I-74 freeflow — not interchangeable Chicago or capital boilerplate.',
    whatBullets: [
      b('Medical and manufacturing calendars reshape mid-week demand', 'Hospital onboarding and plant report dates create hard windows that compete with Saturday family demand.'),
      b('Peoria Heights bluff streets rewrite truck assumptions', 'Steep grade and limited turn radius need driveway photos and sometimes smaller equipment.'),
      b('I-74 / I-474 freeflow is still billable', 'Peoria pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Cross-river Tazewell pairs are routine', 'Clarify county lines so ICC vs FMCSA and drive-time assumptions stay accurate for East Peoria destinations.'),
    ],
    zonesHeading: 'Peoria zones: medical/downtown multi-story, Heights bluffs, Dunlap growth & north river edges',
    zonesIntro: 'Two to four sharp products — medical multi-story, bluff stock, growth HOAs, and river edges.',
    zones: [
      z('medical-core', 'Medical / downtown multi-story', 'Medical core', ['Downtown Peoria', 'medical corridor multi-family'], 'Multi-story, multi-unit, elevators', ['COI packets', 'Elevators', 'Street parking'], ['peoria medical', 'downtown peoria'], 'Collect building packets; inventory elevators vs stairs.'),
      z('heights-bluff', 'Peoria Heights / bluff access', 'Heights bluffs', ['Peoria Heights', 'bluff streets'], 'SFH, multi-story, hillside stock', ['Grades', 'Limited turn radius', 'Long carries'], ['peoria heights'], 'Photo driveway and grade; discuss smaller trucks early.'),
      z('dunlap-growth', 'Dunlap / north growth HOA', 'Dunlap growth', ['Dunlap', 'north growth villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'I-74 freeflow'], ['dunlap'], 'Collect HOA COIs; build I-74 buffer.'),
      z('north-river', 'Chillicothe / north river edges', 'North river', ['Chillicothe', 'north river SFH'], 'SFH, multi-family, mixed stock', ['Empty miles', 'River freeflow'], ['chillicothe'], 'Prefer early starts for long pairs.'),
    ],
    specialized: [
      s('medical-hub', 'Medical multi-family & calendar module', 'Hospital corridors dominate mid-week volume.', ['Align surveys with hard onboarding dates.', 'Collect elevator COIs early.']),
      s('bluff-access', 'River bluff last-mile', 'Heights grades reject full-trailer assumptions.', ['Photo the final approach before promising a 26-foot truck.', 'Long carries often beat forced full-trailer staging.']),
      s('i74-freeflow', 'I-74 / I-474 freeflow', 'River-metro pairs still peak hard; Tazewell legs need clear county lines.', ['Price portal-to-portal honestly.', 'Clarify East Peoria / Tazewell second addresses early.']),
    ],
    schoolsIntro: 'Peoria families compare Peoria Public Schools, Dunlap, Peoria Heights, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'OSF Saint Francis, Carle Health Peoria campuses, and related specialty care anchor acute care; map peak medical-corridor and I-74 times for ER access.',
    costIntro: 'Medical multi-family access, bluff last-mile, and I-74 freeflow often matter more than raw miles.',
    seasonalIntro: 'Hospital calendars, school years, and winter bluff ice reshape demand by pocket.',
  },
];
