import { type PackDef, z, s, b } from './nc-tier2-render';

/** NC Tier 2 Wave 1 packs 1–6 */
export const packsA: PackDef[] = [
  {
    file: 'union-nc.ts',
    exportName: 'unionCountyNcTier2Intelligence',
    slug: 'union',
    hubTitle: 'Union County Moving Intelligence Hub',
    eyebrow: 'Union · Charlotte south collar · Monroe / Indian Trail / Weddington',
    h1: 'Moving in Union County: Monroe, Indian Trail & South-Metro US-74 Growth',
    heroOpener:
      'Union County is Charlotte’s south collar — Monroe seat multi-family, Indian Trail and Wesley Chapel HOA growth, Weddington and Waxhaw edges, and US-74 / I-485 freeflow that is not Uptown elevators with different suburb labels. Expect master-plan gate lists, longer empty miles from Mecklenburg yards, and driveway HOA product that prices differently from South End COIs. This guide is for people moving in Union as south-metro growth collar — not a Mecklenburg rename.',
    heroCredibility:
      'Charlotte south collar · HOA growth · US-74 freeflow · NCUC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-74 · I-485 links · NC-16 · NC-84 · Providence Road corridor',
    parentLabel: 'Mecklenburg County',
    parentHref: '/local-movers/north-carolina/mecklenburg',
    compareIntro:
      'Union is Charlotte south-collar HOA growth on US-74 — not Mecklenburg Uptown/South End vertical product and not pure rural Piedmont freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Mecklenburg crews fight I-77/I-85 peaks and elevator freights. Union pairs ride US-74, I-485 links, and NC-16 — freer mid-day south of the ring, still peak-heavy toward Mecklenburg portals and Providence corridors. Portal-to-portal time is real; it is not a South End elevator day.'),
      b('Housing stock differences', 'Mecklenburg mixes towers, South End mid-rises, and Ballantyne HOAs. Union mixes Monroe multi-family, Indian Trail/Wesley Chapel planned SFH, and Waxhaw larger lots — more continuous south-collar HOA product, less freight-elevator density.'),
      b('Truck access & density', 'HOA COIs, gate lists, and approved hours dominate more often than Uptown street permits. Rural-edge eastern lots add soft shoulders uncommon on Myers Park stairs.'),
      b('Rough cost posture (qualitative)', 'Local Union quotes often sit near south-metro suburb rates for driveway SFH — empty miles from Charlotte yards and HOA soft costs still push prices up vs map miles alone.'),
      b('Role difference', 'Union is Charlotte south collar growth — not Mecklenburg core product renamed.'),
    ],
    whatIntro: 'South-collar HOA density, US-74 freeflow, and empty miles from Charlotte yards — not interchangeable Uptown boilerplate.',
    whatBullets: [
      b('US-74 / I-485 peaks rewrite short locals', 'Union ↔ Mecklenburg pairs freer mid-day still burn billable time at commute peaks. Ask portal-to-portal.'),
      b('Master-plan HOA is first-class product', 'Gate lists, truck limits, and approved hours are standard survey inputs on Indian Trail and Wesley Chapel growth.'),
      b('Empty miles from Mecklenburg yards are real', 'Even “local” Union pairs can price as distance work for Uptown-based crews.'),
      b('Monroe multi-family differs from pure HOA cul-de-sacs', 'Seat stairs and curb plans need inventories different from brand-new villages.'),
    ],
    zonesHeading: 'Union zones: NW growth HOAs, Weddington/Waxhaw edges, Monroe seat & eastern rural lots',
    zonesIntro: 'Two to four sharp products — growth HOAs, southwest edges, seat multi-family, and eastern lots.',
    zones: [
      z('nw-growth', 'Indian Trail / Wesley Chapel / Stallings growth', 'NW growth', ['Indian Trail', 'Wesley Chapel', 'Stallings'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'I-485 peaks', 'Long cul-de-sacs'], ['indian trail', 'wesley chapel', 'stallings'], 'Collect HOA COIs; build I-485 buffer for Mecklenburg pairs.'),
      z('sw-edges', 'Weddington / Waxhaw / Marvin edges', 'SW edges', ['Weddington', 'Waxhaw', 'Marvin'], 'HOA SFH, larger lots', ['Longer empty miles', 'NC-16 congestion', 'HOA rules'], ['weddington', 'waxhaw', 'marvin'], 'Prefer early starts; survey driveway depth.'),
      z('monroe-seat', 'Monroe seat multi-family & older stock', 'Monroe', ['Monroe', 'downtown edges', 'central multi-family'], 'Multi-family, older SFH, townhomes', ['Stairs', 'US-74 congestion', 'Mixed curb'], ['monroe'], 'Photo curb; confirm elevator vs stair access.'),
      z('east-rural', 'Eastern Union rural-edge lots', 'East edge', ['Marshville edges', 'eastern tracts'], 'SFH, rural-edge lots', ['Empty miles', 'Soft shoulders'], ['marshville', 'east union'], 'Survey truck access; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('hoa-south', 'South-collar HOA growth module', 'Master-plan rules dominate Union family volume.', ['Collect COI and gate lists before the estimate is final.', 'Saturday HOA windows push demand into peak crew slots.']),
      s('us74-freeflow', 'US-74 / I-485 freeflow', 'South-metro pairs still peak hard toward Mecklenburg.', ['Price portal-to-portal honestly.', 'Clarify Mecklenburg second addresses for drive-time assumptions.']),
      s('monroe-access', 'Monroe seat multi-family access', 'Seat density differs from pure cul-de-sac HOAs.', ['Inventory stairs and street width.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Union families compare Union County Public Schools feeders across Indian Trail, Monroe, Weddington, and Waxhaw — verify address boundaries; do not assume Charlotte-Mecklenburg maps apply.',
    hospitalsDetail: 'Atrium Health Union and Charlotte specialty spillover serve the county; map peak US-74 / I-485 times for ER access.',
    costIntro: 'HOA soft costs, US-74 freeflow, and empty miles from Charlotte yards often matter more than raw miles.',
    seasonalIntro: 'School years and summer family closings reshape demand more than Uptown corporate calendars alone.',
  },
  {
    file: 'cabarrus-nc.ts',
    exportName: 'cabarrusCountyNcTier2Intelligence',
    slug: 'cabarrus',
    hubTitle: 'Cabarrus County Moving Intelligence Hub',
    eyebrow: 'Cabarrus · Charlotte NE · Concord / Kannapolis',
    h1: 'Moving in Cabarrus County: Concord, Kannapolis & I-85 Northeast Growth',
    heroOpener:
      'Cabarrus County is Charlotte’s northeast I-85 collar — Concord HOA and multi-family growth, Kannapolis revitalizing multi-unit stock, Harrisburg edges, and motorsports/retail corridor freeflow that is not Mecklenburg University City with different labels. Expect I-85 portal time, event-week traffic near major venues, and mixed industrial-residential product under one county. This guide is for people moving in Cabarrus as NE Charlotte growth collar — not a Mecklenburg rename.',
    heroCredibility:
      'Charlotte NE collar · I-85 growth · Concord / Kannapolis · NCUC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-85 · US-29 · Concord Mills Blvd · NC-49 · NC-73',
    parentLabel: 'Mecklenburg County',
    parentHref: '/local-movers/north-carolina/mecklenburg',
    compareIntro:
      'Cabarrus is Charlotte NE I-85 growth collar — not Mecklenburg Uptown elevators and not pure rural Piedmont freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Mecklenburg crews fight beltway peaks into University City and Uptown. Cabarrus pairs ride I-85, US-29, and NC-49 — freer mid-day northeast of the ring, still peak-heavy toward Mecklenburg portals and Concord Mills retail weekends.'),
      b('Housing stock differences', 'Mecklenburg mixes towers and University multi-family. Cabarrus mixes Concord HOA SFH, Kannapolis multi-unit, and Harrisburg growth — more I-85 spillover product, less continuous South End loft density.'),
      b('Truck access & density', 'HOA packets and arterial multi-family curb plans dominate; event weeks near major venues rewrite staging uncommon on quiet Ballantyne cul-de-sacs.'),
      b('Rough cost posture (qualitative)', 'Local Cabarrus quotes often track NE-metro suburb rates for driveway SFH — I-85 peaks and multi-unit access still push prices up.'),
      b('Role difference', 'Cabarrus is Charlotte NE I-85 collar — not Mecklenburg core renamed.'),
    ],
    whatIntro: 'I-85 freeflow, Concord/Kannapolis mixed stock, and event-week staging — not interchangeable Mecklenburg boilerplate.',
    whatBullets: [
      b('I-85 peaks rewrite short-looking locals', 'Cabarrus ↔ Mecklenburg pairs freer mid-day still burn clock at commute peaks. Ask portal-to-portal.'),
      b('Concord HOA growth is first-class product', 'Gate lists and approved hours are standard on planned villages.'),
      b('Kannapolis multi-unit differs from pure SFH HOAs', 'Elevators and curb plans need inventories different from Harrisburg driveways.'),
      b('Motorsports/retail event weeks reshape freeflow', 'Major venue calendars can erase “quiet suburban” unload assumptions.'),
    ],
    zonesHeading: 'Cabarrus zones: Concord growth, Kannapolis multi-unit, Harrisburg edges & eastern lots',
    zonesIntro: 'Two to four sharp products under one NE I-85 collar label.',
    zones: [
      z('concord-growth', 'Concord HOA & multi-family growth', 'Concord', ['Concord', 'growth villages', 'Concord Mills edges'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'I-85 peaks', 'Retail congestion'], ['concord', 'concord mills'], 'Collect HOA COIs; build I-85 buffer.'),
      z('kannapolis', 'Kannapolis multi-unit & revitalizing stock', 'Kannapolis', ['Kannapolis', 'downtown edges', 'multi-family corridors'], 'Multi-unit, older SFH, townhomes', ['Elevators/stairs', 'Street parking', 'Mixed curb'], ['kannapolis'], 'Confirm elevator rules; inventory stairs.'),
      z('harrisburg', 'Harrisburg / west edge toward Mecklenburg', 'Harrisburg', ['Harrisburg', 'western edges'], 'HOA SFH, multi-family', ['I-85 freeflow', 'HOA rules'], ['harrisburg'], 'Clarify Mecklenburg second addresses early.'),
      z('east-edge', 'Eastern Cabarrus larger lots', 'East edge', ['Mount Pleasant edges', 'eastern tracts'], 'SFH, rural-edge lots', ['Empty miles', 'Soft shoulders'], ['mount pleasant', 'east cabarrus'], 'Survey approaches; prefer early starts.'),
    ],
    specialized: [
      s('i85-ne', 'I-85 northeast freeflow', 'NE-metro pairs still peak hard toward Mecklenburg.', ['Price portal-to-portal honestly.', 'Build buffers for Concord Mills and event weekends.']),
      s('concord-hoa', 'Concord HOA growth module', 'Planned suburbs dominate family volume.', ['Collect COI and gate lists early.', 'Do not quote Uptown elevator rates for driveway SFH.']),
      s('kannapolis-multi', 'Kannapolis multi-unit access', 'Revitalizing multi-family is a first-class product.', ['Inventory elevators vs stairs before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Cabarrus families compare Cabarrus County Schools and Kannapolis City Schools feeders — verify address boundaries; do not assume Charlotte-Mecklenburg maps apply.',
    hospitalsDetail: 'Atrium Health Cabarrus and Charlotte specialty spillover serve the county; map peak I-85 times for ER access.',
    costIntro: 'I-85 freeflow, HOA soft costs, and multi-unit access often matter more than raw miles.',
    seasonalIntro: 'School years, lease ends, and major-event weeks reshape demand by pocket.',
  },
  {
    file: 'gaston-nc.ts',
    exportName: 'gastonCountyNcTier2Intelligence',
    slug: 'gaston',
    hubTitle: 'Gaston County Moving Intelligence Hub',
    eyebrow: 'Gaston · Charlotte west · Gastonia / Belmont',
    h1: 'Moving in Gaston County: Gastonia, Belmont & West-Collar I-85 Access',
    heroOpener:
      'Gaston County is Charlotte’s western collar — Gastonia seat multi-story and industrial-residential mix, Belmont and Mount Holly east-edge growth toward the river, Cramerton and Dallas corridors, and I-85 / US-321 freeflow that is not Ballantyne HOA product with western labels. Expect mixed mill-town stock, west-collar empty miles, and river-edge densification under one county. This guide is for people moving in Gaston as west-metro collar — not a Mecklenburg rename.',
    heroCredibility:
      'Charlotte west collar · Gastonia / Belmont · I-85 / US-321 · NCUC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-85 · US-321 · US-74 · NC-279 · Wilkinson Blvd',
    parentLabel: 'Mecklenburg County',
    parentHref: '/local-movers/north-carolina/mecklenburg',
    compareIntro:
      'Gaston is Charlotte west collar on I-85 / Wilkinson — not Mecklenburg South End elevators and not pure rural foothills freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Mecklenburg crews fight west approaches and Uptown peaks. Gaston pairs ride I-85, Wilkinson Blvd, and US-321 — freer mid-day west of the river, still peak-heavy toward Mecklenburg portals and Belmont/Mount Holly commute windows.'),
      b('Housing stock differences', 'Mecklenburg mixes towers and south-ring HOAs. Gaston mixes Gastonia multi-story, mill-era stock, Belmont multi-family growth, and western larger lots — more industrial-residential fabric, less continuous Uptown vertical product.'),
      b('Truck access & density', 'Older seat streets need curb plans; east-edge growth adds HOA packets; soft shoulders appear farther west.'),
      b('Rough cost posture (qualitative)', 'Local Gaston quotes often sit near west-metro secondary rates for driveway SFH — multi-story access and empty miles still push prices up.'),
      b('Role difference', 'Gaston is Charlotte west collar — not Mecklenburg core renamed.'),
    ],
    whatIntro: 'West-collar freeflow, mill-town multi-story, and river-edge growth — not interchangeable Ballantyne boilerplate.',
    whatBullets: [
      b('I-85 / Wilkinson freeflow is still billable', 'Gaston ↔ Mecklenburg pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Gastonia multi-story is first-class product', 'Seat stairs and curb plans need inventories different from Belmont growth cul-de-sacs.'),
      b('Belmont / Mount Holly east edge densifies', 'Multi-family and HOA soft costs appear closer to the river.'),
      b('Industrial-residential mix rewrites truck type', 'Mill-adjacent streets reject pure south-ring HOA day-rate assumptions.'),
    ],
    zonesHeading: 'Gaston zones: Gastonia seat, Belmont/Mount Holly east, US-321 corridor & western lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, east growth, corridor stock, and western lots.',
    zones: [
      z('gastonia-seat', 'Gastonia multi-story & industrial-residential', 'Gastonia', ['Gastonia', 'downtown edges', 'mill-adjacent stock'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Tight streets', 'I-85 freeflow'], ['gastonia'], 'Inventory stairs; plan temporary no-parking.'),
      z('east-edge', 'Belmont / Mount Holly / Cramerton east edge', 'East edge', ['Belmont', 'Mount Holly', 'Cramerton'], 'Multi-family, HOA SFH, townhomes', ['HOA packets', 'Wilkinson peaks', 'River-bridge freeflow'], ['belmont', 'mount holly', 'cramerton'], 'Collect HOA COIs; build bridge/commute buffers.'),
      z('us321', 'US-321 / Dallas corridor', 'US-321 corridor', ['Dallas', 'High Shoals edges', 'US-321 multi-family'], 'SFH, multi-family, mixed stock', ['Arterial timing', 'Mixed access'], ['dallas', 'high shoals'], 'Prefer early starts; confirm driveway depth.'),
      z('west-lots', 'Western Gaston larger lots', 'West lots', ['Bessemer City edges', 'Cherryville edges', 'western tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['bessemer city', 'cherryville'], 'Photo approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('west-collar', 'I-85 / Wilkinson west-collar freeflow', 'West-metro pairs still peak hard toward Mecklenburg.', ['Price portal-to-portal honestly.', 'Clarify Mecklenburg second addresses early.']),
      s('east-growth', 'Belmont / Mount Holly growth module', 'East-edge densification is the river product.', ['Collect HOA packets before the estimate is final.', 'Build buffers for bridge and I-85 peaks.']),
      s('gastonia-seat', 'Gastonia multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Gaston families compare Gaston County Schools feeders across Gastonia, Belmont, Mount Holly, and western towns — verify address boundaries.',
    hospitalsDetail: 'CaroMont Regional and Charlotte specialty spillover serve the county; map peak I-85 / Wilkinson times for ER access.',
    costIntro: 'West-collar freeflow, multi-story access, and HOA soft costs on the east edge often matter more than raw miles.',
    seasonalIntro: 'School years, lease ends, and winter ice on western approaches reshape demand by pocket.',
  },
  {
    file: 'iredell-nc.ts',
    exportName: 'iredellCountyNcTier2Intelligence',
    slug: 'iredell',
    hubTitle: 'Iredell County Moving Intelligence Hub',
    eyebrow: 'Iredell · Charlotte north · Mooresville / Statesville',
    h1: 'Moving in Iredell County: Mooresville, Lake Norman Edge & I-77 North Growth',
    heroOpener:
      'Iredell County is Charlotte’s northern I-77 / Lake Norman collar — Mooresville multi-family and HOA growth, Lake Norman waterfront and association approaches, Statesville seat multi-story, and freeflow that still peaks hard toward Mecklenburg. It is not Huntersville renamed with a different county label: expect lake last-mile, motorsports/industrial employment corridors, and longer empty miles under one county. This guide is for people moving in Iredell as north-metro growth collar — not a Charlotte core rename.',
    heroCredibility:
      'Charlotte north collar · Lake Norman / I-77 · Mooresville / Statesville · NCUC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-77 · I-40 · US-21 · NC-150 · NC-115 · Brawley School Rd corridor',
    parentLabel: 'Mecklenburg County',
    parentHref: '/local-movers/north-carolina/mecklenburg',
    compareIntro:
      'Iredell is Charlotte north I-77 / Lake Norman growth — not Mecklenburg Uptown elevators and not pure foothills freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Mecklenburg crews fight I-77 peaks into Huntersville and Uptown. Iredell pairs ride I-77, NC-150, and US-21 — freer mid-day further north, still peak-heavy on Mooresville commute windows and lake-edge approaches.'),
      b('Housing stock differences', 'Mecklenburg mixes towers and north-ring HOAs. Iredell mixes Mooresville multi-family, Lake Norman association homes, and Statesville multi-story — more lake-edge and north-collar product, less continuous South End loft density.'),
      b('Truck access & density', 'Lake approaches can need smaller trucks; HOA/association packets dominate Mooresville growth; Statesville seat needs curb plans.'),
      b('Rough cost posture (qualitative)', 'Local Iredell quotes often track north-metro suburb rates for driveway SFH — lake shuttles and I-77 peaks still push prices up.'),
      b('Role difference', 'Iredell is Charlotte north Lake Norman collar — not Mecklenburg core renamed.'),
    ],
    whatIntro: 'I-77 freeflow, Lake Norman last-mile, and Mooresville growth — not interchangeable Huntersville boilerplate alone.',
    whatBullets: [
      b('I-77 north peaks rewrite short-looking locals', 'Iredell ↔ Mecklenburg pairs freer mid-day still burn clock. Ask portal-to-portal.'),
      b('Lake Norman association access is first-class product', 'Dock approaches, HOA rules, and narrow roads rewrite truck size assumptions.'),
      b('Mooresville multi-family differs from Statesville seat stock', 'Elevators and lease clusters need inventories different from seat stairs.'),
      b('Empty miles from Charlotte yards are real', 'Even “local” Iredell pairs can price as distance work for city-based crews.'),
    ],
    zonesHeading: 'Iredell zones: Mooresville growth, Lake Norman edge, Statesville seat & northern lots',
    zonesIntro: 'Two to four sharp products — growth multi-family, lake edge, seat multi-story, and northern lots.',
    zones: [
      z('mooresville', 'Mooresville multi-family & HOA growth', 'Mooresville', ['Mooresville', 'Brawley School corridor', 'growth villages'], 'HOA SFH, multi-family, townhomes', ['HOA packets', 'I-77 peaks', 'Lease clusters'], ['mooresville'], 'Collect HOA COIs; build I-77 commute buffers.'),
      z('lake-norman', 'Lake Norman association & waterfront edges', 'Lake Norman', ['Lake Norman edges', 'association communities'], 'SFH, lake homes, association stock', ['Narrow approaches', 'HOA/association rules', 'Seasonal staging'], ['lake norman', 'troutman edges'], 'Photo last-mile; discuss shuttle trucks early.'),
      z('statesville', 'Statesville seat multi-story & older stock', 'Statesville', ['Statesville', 'downtown', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-40 freeflow'], ['statesville'], 'Inventory stairs; plan temporary no-parking.'),
      z('north-lots', 'Northern Iredell larger lots', 'North lots', ['northern tracts', 'Harmony edges'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['harmony', 'north iredell'], 'Survey approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('i77-north', 'I-77 / Lake Norman north freeflow', 'North-metro pairs still peak hard toward Mecklenburg.', ['Price portal-to-portal honestly.', 'Build buffers for morning and evening peaks.']),
      s('lake-access', 'Lake Norman last-mile module', 'Waterfront approaches reject full-trailer assumptions.', ['Photo the final approach before promising a 26-foot truck.', 'Confirm association truck limits early.']),
      s('mooresville-growth', 'Mooresville growth & multi-family', 'Growth density is the north-collar product.', ['Collect HOA and elevator rules before the estimate is final.', 'Lease clusters stack around school calendars.']),
    ],
    schoolsIntro: 'Iredell families compare Iredell-Statesville Schools and Mooresville Graded School District feeders — verify address boundaries.',
    hospitalsDetail: 'Iredell Health System, Lake Norman Regional, and Charlotte specialty spillover serve the county; map peak I-77 times for ER access.',
    costIntro: 'I-77 freeflow, lake last-mile, and HOA soft costs often matter more than raw miles.',
    seasonalIntro: 'School years, lake tourism weekends, and winter ice reshape demand by pocket.',
  },
  {
    file: 'johnston-nc.ts',
    exportName: 'johnstonCountyNcTier2Intelligence',
    slug: 'johnston',
    hubTitle: 'Johnston County Moving Intelligence Hub',
    eyebrow: 'Johnston · Raleigh south · Clayton / Smithfield / Benson',
    h1: 'Moving in Johnston County: Clayton, Smithfield & I-40/I-95 South Growth',
    heroOpener:
      'Johnston County is Raleigh’s southern I-40 / I-95 growth collar — Clayton multi-family and HOA spillover, Smithfield seat stock, Benson and Selma logistics edges, and freeflow that still peaks hard toward Wake. It is not a Garner rename with different labels: expect longer empty miles from capital yards, warehouse-adjacent residential product, and I-95 interstate risk under one county. This guide is for people moving in Johnston as Raleigh south growth collar — not a Wake rename.',
    heroCredibility:
      'Raleigh south collar · I-40 / I-95 growth · Clayton / Smithfield · NCUC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-40 · I-95 · US-70 · US-301 · NC-42 · NC-50',
    parentLabel: 'Wake County',
    parentHref: '/local-movers/north-carolina/wake',
    compareIntro:
      'Johnston is Raleigh south I-40/I-95 growth collar — not Wake capital elevators and not pure rural Coastal Plain freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Wake crews fight I-40/I-440/I-540 peaks into Raleigh core. Johnston pairs ride I-40, NC-42, and US-70 — freer mid-day south of the Outer Loop, still peak-heavy toward Wake portals and Clayton commute windows.'),
      b('Housing stock differences', 'Wake mixes downtown elevators and Cary HOAs. Johnston mixes Clayton multi-family, Smithfield multi-story, and logistics-edge SFH — more south-collar growth and warehouse-adjacent stock, less continuous capital vertical product.'),
      b('Truck access & density', 'HOA packets dominate Clayton growth; seat streets need curb plans; I-95 edges add interstate authority questions on SC/VA legs.'),
      b('Rough cost posture (qualitative)', 'Local Johnston quotes often sit near south-Triangle suburb rates for driveway SFH — empty miles and multi-family access still push prices up.'),
      b('Role difference', 'Johnston is Raleigh south growth collar — not Wake core renamed.'),
    ],
    whatIntro: 'South-collar growth, I-40/I-95 freeflow, and logistics-edge residential — not interchangeable Raleigh boilerplate.',
    whatBullets: [
      b('I-40 peaks rewrite short-looking locals', 'Johnston ↔ Wake pairs freer mid-day still burn clock. Ask portal-to-portal.'),
      b('Clayton multi-family and HOA is first-class product', 'Gate lists and elevators need inventories different from Benson driveway lots.'),
      b('I-95 logistics edges create long empty miles', 'Warehouse-adjacent residential fails when crews assume Cary day rates.'),
      b('Smithfield seat multi-story differs from pure growth HOAs', 'Stairs and curb plans are real cost drivers.'),
    ],
    zonesHeading: 'Johnston zones: Clayton growth, Smithfield seat, I-95 logistics edges & southern lots',
    zonesIntro: 'Two to four sharp products — growth multi-family, seat stock, logistics edges, and southern lots.',
    zones: [
      z('clayton-growth', 'Clayton multi-family & HOA growth', 'Clayton', ['Clayton', 'growth villages', 'NC-42 corridor'], 'HOA SFH, multi-family, townhomes', ['HOA packets', 'I-40 peaks', 'Lease clusters'], ['clayton'], 'Collect HOA COIs; build I-40 buffer for Wake pairs.'),
      z('smithfield', 'Smithfield seat multi-story & older stock', 'Smithfield', ['Smithfield', 'downtown edges'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'US-70 freeflow'], ['smithfield'], 'Inventory stairs; plan temporary no-parking.'),
      z('i95-edge', 'Selma / Benson I-95 logistics edges', 'I-95 edge', ['Selma', 'Benson', 'I-95 multi-family'], 'SFH, multi-family, mixed stock', ['Arterial timing', 'Empty miles', 'Interstate adjacency'], ['selma', 'benson'], 'Prefer early starts; clarify out-of-state second addresses.'),
      z('south-lots', 'Southern & eastern larger lots', 'South lots', ['Four Oaks edges', 'eastern tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['four oaks', 'east johnston'], 'Photo approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('i40-south', 'I-40 / I-95 south-collar freeflow', 'South-Triangle pairs still peak hard toward Wake.', ['Price portal-to-portal honestly.', 'Build buffers for Clayton commute windows.']),
      s('clayton-growth', 'Clayton growth & multi-family module', 'South spillover density is the collar product.', ['Collect HOA and elevator rules early.', 'Do not quote downtown Raleigh elevator rates for driveway SFH.']),
      s('logistics-edge', 'I-95 logistics-edge residential', 'Warehouse corridors rewrite empty-mile assumptions.', ['Survey last-mile on industrial-adjacent streets.', 'Clarify FMCSA when either address is out of NC.']),
    ],
    schoolsIntro: 'Johnston families compare Johnston County Schools feeders across Clayton, Smithfield, Benson, and Selma — verify address boundaries; do not assume Wake County maps apply.',
    hospitalsDetail: 'UNC Health Johnston and Triangle specialty spillover serve the county; map peak I-40 times for ER access.',
    costIntro: 'I-40 freeflow, HOA soft costs, and logistics-edge empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, lease ends, and peak I-95 travel seasons reshape demand by pocket.',
  },
  {
    file: 'orange-nc.ts',
    exportName: 'orangeCountyNcTier2Intelligence',
    slug: 'orange',
    hubTitle: 'Orange County Moving Intelligence Hub',
    eyebrow: 'Orange · Chapel Hill / Carrboro / Hillsborough — Triangle',
    h1: 'Moving in Orange County: Chapel Hill, Carrboro & University Triangle Access',
    heroOpener:
      'Orange County is Triangle university-town product — Chapel Hill multi-story and near-campus density, Carrboro multi-family and older stock, Hillsborough seat edges, and freeflow on US-15-501 / I-40 that is not Durham research elevators or Raleigh capital towers with different labels. Expect term calendars, student multi-family COIs, and hill/stair access under one county. This guide is for people moving in Orange as Chapel Hill university Triangle — not a Durham rename.',
    heroCredibility:
      'Chapel Hill university Triangle · Term calendars · Carrboro density · NCUC household goods · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-40 · US-15-501 · NC-54 · NC-86 · Franklin Street corridor',
    parentLabel: 'Durham County',
    parentHref: '/local-movers/north-carolina/durham',
    parentAltLabel: 'Wake County',
    parentAltHref: '/local-movers/north-carolina/wake',
    compareIntro:
      'Orange is Chapel Hill / Carrboro university-town density — not Durham research-core elevators alone and not Wake capital multi-family.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Durham crews fight NC-147 and I-85 research peaks. Orange pairs ride US-15-501, NC-54, and I-40 links — freer mid-day toward Hillsborough, still peak-heavy on Franklin Street and campus windows. Portal-to-portal time is real; it is not a pure RTP office day.'),
      b('Housing stock differences', 'Durham mixes adaptive-reuse elevators and Southpoint multi-family. Orange mixes near-campus multi-story, Carrboro older multi-unit, and Hillsborough SFH — more university-town product, less continuous research-corridor density.'),
      b('Truck access & density', 'Campus-adjacent streets need curb plans and temporary no-parking; HOA packets appear on outer edges; term weekends rewrite staging.'),
      b('Rough cost posture (qualitative)', 'Local Orange quotes often track Triangle secondary-premium rates for multi-story access — term peaks and stairs push prices above quiet Hillsborough driveway jobs.'),
      b('Role difference', 'Orange is Chapel Hill university Triangle — not Durham or Wake core renamed.'),
    ],
    whatIntro: 'University term calendars, near-campus multi-story, and 15-501 freeflow — not interchangeable Durham boilerplate.',
    whatBullets: [
      b('UNC term calendars drive demand spikes', 'Move-in/out weekends fill crews and parking near campus. Book early.'),
      b('Near-campus multi-story is first-class product', 'Stairs, elevators, and COIs need inventories different from pure SFH lots.'),
      b('Carrboro density differs from Hillsborough seat stock', 'Tight older streets rewrite truck type assumptions.'),
      b('US-15-501 / I-40 freeflow is still billable', 'Orange ↔ Durham pairs freer mid-day still peak hard. Ask portal-to-portal.'),
    ],
    zonesHeading: 'Orange zones: Chapel Hill campus edge, Carrboro multi-unit, Hillsborough seat & rural edges',
    zonesIntro: 'Two to four sharp products — campus multi-story, Carrboro density, seat stock, and rural edges.',
    zones: [
      z('chapel-hill', 'Chapel Hill campus-edge multi-story', 'Chapel Hill', ['Chapel Hill', 'Franklin corridor', 'near-campus multi-family'], 'Multi-story, multi-unit, some SFH', ['Stairs/elevators', 'Term parking', 'COI packets'], ['chapel hill'], 'Book around term calendars; collect building rules.'),
      z('carrboro', 'Carrboro multi-unit & older stock', 'Carrboro', ['Carrboro', 'older multi-family', 'mixed SFH'], 'Multi-unit, older SFH, townhomes', ['Tight streets', 'Street parking', 'Mixed curb'], ['carrboro'], 'Photo curb width; inventory stairs.'),
      z('hillsborough', 'Hillsborough seat & western edges', 'Hillsborough', ['Hillsborough', 'seat multi-family', 'western SFH'], 'SFH, multi-unit, mixed stock', ['Arterial timing', 'I-40 freeflow'], ['hillsborough'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-edge', 'Northern & western rural edges', 'Rural edge', ['northern tracts', 'Efland edges'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['efland', 'north orange'], 'Survey approaches; prefer early starts for long pairs.'),
    ],
    specialized: [
      s('unc-terms', 'UNC / university move-cycle module', 'Term calendars drive demand spikes.', ['Book early around move-in/out weekends.', 'Price campus-edge curb time honestly.']),
      s('campus-multi', 'Near-campus multi-story access', 'Elevators and stairs are first-class cost drivers.', ['Collect COI and elevator reservations early.', 'Temporary no-parking often beats long carries.']),
      s('15501-freeflow', 'US-15-501 / I-40 freeflow', 'Triangle pairs still peak hard toward Durham and Wake.', ['Price portal-to-portal honestly.', 'Clarify Durham or Wake second addresses early.']),
    ],
    schoolsIntro: 'Orange families compare Chapel Hill-Carrboro City Schools and Orange County Schools feeders — verify address boundaries; do not assume Durham or Wake maps apply.',
    hospitalsDetail: 'UNC Medical Center and related campuses anchor acute care; map peak campus and 15-501 times for ER access.',
    costIntro: 'Term peaks, multi-story access, and 15-501 freeflow often matter more than raw miles.',
    seasonalIntro: 'University calendars, school years, and summer family closings reshape demand more than pure corporate Triangle patterns.',
  },
];
