/**
 * Validates JSON-LD graph integrity for curated-state county pages.
 * Run: npx tsx scripts/validate-county-schema.ts
 */
import { buildCountySchemaGraph } from '../lib/local-movers/build-county-schema-graph';
import { getCountiesForState, getCounty } from '../lib/local-movers/geography/index';
import {
  buildCountyDescription,
  buildCountyFaqItems,
  buildCountyLabel,
  buildCountyTestimonials,
  buildCountyTitle,
  getCountyPath,
  getMoversForCounty,
} from '../lib/local-movers/index';
import { getLocalState } from '../lib/local-movers/states';
import {
  buildSchemaPrimaryCity,
  validateCountySchemaGraph,
} from '../lib/local-movers/schema-helpers';

const CURATED_STATES = [
  'texas',
  'new-york',
  'new-jersey',
  'california',
  'south-carolina',
  'florida',
  'north-carolina',
  'tennessee',
  'alabama',
  'mississippi',
  'louisiana',
  'oklahoma',
  'arkansas',
  'kansas',
  'missouri',
  'georgia',
  'illinois',
  'michigan',
  'indiana',
  'ohio',
  'kentucky',
] as const;

const SPOT_CHECK: Array<{ stateSlug: string; countySlug: string; expectedCity?: string }> = [
  { stateSlug: 'texas', countySlug: 'travis', expectedCity: 'Austin' },
  { stateSlug: 'texas', countySlug: 'austin', expectedCity: 'Bellville' },
  { stateSlug: 'california', countySlug: 'los-angeles', expectedCity: 'Los Angeles' },
  { stateSlug: 'new-york', countySlug: 'new-york', expectedCity: 'Manhattan' },
  { stateSlug: 'florida', countySlug: 'miami-dade', expectedCity: 'Miami' },
  { stateSlug: 'north-carolina', countySlug: 'wake', expectedCity: 'Raleigh' },
  { stateSlug: 'tennessee', countySlug: 'shelby', expectedCity: 'Memphis' },
  { stateSlug: 'tennessee', countySlug: 'davidson', expectedCity: 'Nashville' },
  { stateSlug: 'tennessee', countySlug: 'knox', expectedCity: 'Knoxville' },
  { stateSlug: 'alabama', countySlug: 'jefferson', expectedCity: 'Birmingham' },
  { stateSlug: 'alabama', countySlug: 'madison', expectedCity: 'Huntsville' },
  { stateSlug: 'alabama', countySlug: 'mobile', expectedCity: 'Mobile' },
  { stateSlug: 'mississippi', countySlug: 'hinds', expectedCity: 'Jackson' },
  { stateSlug: 'mississippi', countySlug: 'harrison', expectedCity: 'Gulfport' },
  { stateSlug: 'mississippi', countySlug: 'desoto', expectedCity: 'Hernando' },
  { stateSlug: 'louisiana', countySlug: 'orleans', expectedCity: 'New Orleans' },
  { stateSlug: 'louisiana', countySlug: 'east-baton-rouge', expectedCity: 'Baton Rouge' },
  { stateSlug: 'louisiana', countySlug: 'jefferson', expectedCity: 'Gretna' },
  { stateSlug: 'oklahoma', countySlug: 'oklahoma', expectedCity: 'Oklahoma City' },
  { stateSlug: 'oklahoma', countySlug: 'tulsa', expectedCity: 'Tulsa' },
  { stateSlug: 'oklahoma', countySlug: 'cleveland', expectedCity: 'Norman' },
  { stateSlug: 'arkansas', countySlug: 'pulaski', expectedCity: 'Little Rock' },
  { stateSlug: 'arkansas', countySlug: 'benton', expectedCity: 'Bentonville' },
  { stateSlug: 'arkansas', countySlug: 'washington', expectedCity: 'Fayetteville' },
  { stateSlug: 'kansas', countySlug: 'johnson', expectedCity: 'Olathe' },
  { stateSlug: 'kansas', countySlug: 'sedgwick', expectedCity: 'Wichita' },
  { stateSlug: 'kansas', countySlug: 'shawnee', expectedCity: 'Topeka' },
  { stateSlug: 'missouri', countySlug: 'st-louis', expectedCity: 'Clayton' },
  { stateSlug: 'missouri', countySlug: 'jackson', expectedCity: 'Independence' },
  { stateSlug: 'missouri', countySlug: 'st-charles', expectedCity: 'St. Charles' },
  { stateSlug: 'missouri', countySlug: 'greene', expectedCity: 'Springfield' },
  { stateSlug: 'missouri', countySlug: 'st-louis-city', expectedCity: 'St. Louis' },
  { stateSlug: 'missouri', countySlug: 'clay', expectedCity: 'Liberty' },
  { stateSlug: 'missouri', countySlug: 'jefferson', expectedCity: 'Hillsboro' },
  { stateSlug: 'missouri', countySlug: 'boone', expectedCity: 'Columbia' },
  { stateSlug: 'missouri', countySlug: 'jasper', expectedCity: 'Carthage' },
  { stateSlug: 'missouri', countySlug: 'cass', expectedCity: 'Harrisonville' },
  { stateSlug: 'missouri', countySlug: 'platte', expectedCity: 'Platte City' },
  { stateSlug: 'missouri', countySlug: 'franklin', expectedCity: 'Union' },
  { stateSlug: 'missouri', countySlug: 'christian', expectedCity: 'Ozark' },
  { stateSlug: 'missouri', countySlug: 'cape-girardeau', expectedCity: 'Jackson' },
  { stateSlug: 'missouri', countySlug: 'buchanan', expectedCity: 'St. Joseph' },
  { stateSlug: 'missouri', countySlug: 'cole', expectedCity: 'Jefferson City' },
  { stateSlug: 'missouri', countySlug: 'st-francois', expectedCity: 'Farmington' },
  { stateSlug: 'missouri', countySlug: 'lincoln', expectedCity: 'Troy' },
  { stateSlug: 'missouri', countySlug: 'newton', expectedCity: 'Neosho' },
  { stateSlug: 'missouri', countySlug: 'johnson', expectedCity: 'Warrensburg' },
  { stateSlug: 'missouri', countySlug: 'taney', expectedCity: 'Forsyth' },
  { stateSlug: 'missouri', countySlug: 'pulaski', expectedCity: 'Waynesville' },
  { stateSlug: 'missouri', countySlug: 'callaway', expectedCity: 'Fulton' },
  { stateSlug: 'missouri', countySlug: 'phelps', expectedCity: 'Rolla' },
  { stateSlug: 'missouri', countySlug: 'pettis', expectedCity: 'Sedalia' },
  { stateSlug: 'missouri', countySlug: 'webster', expectedCity: 'Marshfield' },
  { stateSlug: 'missouri', countySlug: 'camden', expectedCity: 'Camdenton' },
  { stateSlug: 'missouri', countySlug: 'butler', expectedCity: 'Poplar Bluff' },
  { stateSlug: 'missouri', countySlug: 'howell', expectedCity: 'West Plains' },
  { stateSlug: 'missouri', countySlug: 'lawrence', expectedCity: 'Mount Vernon' },
  { stateSlug: 'missouri', countySlug: 'warren', expectedCity: 'Warrenton' },
  { stateSlug: 'missouri', countySlug: 'scott', expectedCity: 'Benton' },
  { stateSlug: 'missouri', countySlug: 'laclede', expectedCity: 'Lebanon' },
  { stateSlug: 'missouri', countySlug: 'barry', expectedCity: 'Cassville' },
  { stateSlug: 'missouri', countySlug: 'polk', expectedCity: 'Bolivar' },
  { stateSlug: 'missouri', countySlug: 'lafayette', expectedCity: 'Lexington' },
  { stateSlug: 'missouri', countySlug: 'stone', expectedCity: 'Galena' },
  { stateSlug: 'missouri', countySlug: 'marion', expectedCity: 'Palmyra' },
  { stateSlug: 'missouri', countySlug: 'stoddard', expectedCity: 'Bloomfield' },
  { stateSlug: 'missouri', countySlug: 'dunklin', expectedCity: 'Kennett' },
  { stateSlug: 'missouri', countySlug: 'texas', expectedCity: 'Houston' },
  { stateSlug: 'missouri', countySlug: 'miller', expectedCity: 'Tuscumbia' },
  { stateSlug: 'missouri', countySlug: 'adair', expectedCity: 'Kirksville' },
  { stateSlug: 'missouri', countySlug: 'audrain', expectedCity: 'Mexico' },
  { stateSlug: 'missouri', countySlug: 'randolph', expectedCity: 'Huntsville' },
  { stateSlug: 'missouri', countySlug: 'mcdonald', expectedCity: 'Pineville' },
  { stateSlug: 'missouri', countySlug: 'washington', expectedCity: 'Potosi' },
  { stateSlug: 'missouri', countySlug: 'ray', expectedCity: 'Richmond' },
  { stateSlug: 'missouri', countySlug: 'saline', expectedCity: 'Marshall' },
  { stateSlug: 'missouri', countySlug: 'crawford', expectedCity: 'Steelville' },
  { stateSlug: 'missouri', countySlug: 'henry', expectedCity: 'Clinton' },
  { stateSlug: 'missouri', countySlug: 'morgan', expectedCity: 'Versailles' },
  { stateSlug: 'missouri', countySlug: 'clinton', expectedCity: 'Plattsburg' },
  { stateSlug: 'missouri', countySlug: 'benton', expectedCity: 'Warsaw' },
  { stateSlug: 'missouri', countySlug: 'vernon', expectedCity: 'Nevada' },
  { stateSlug: 'missouri', countySlug: 'nodaway', expectedCity: 'Maryville' },
  { stateSlug: 'missouri', countySlug: 'wright', expectedCity: 'Hartville' },
  { stateSlug: 'missouri', countySlug: 'perry', expectedCity: 'Perryville' },
  { stateSlug: 'missouri', countySlug: 'ste-genevieve', expectedCity: 'Ste. Genevieve' },
  { stateSlug: 'missouri', countySlug: 'andrew', expectedCity: 'Savannah' },
  { stateSlug: 'missouri', countySlug: 'dallas', expectedCity: 'Buffalo' },
  { stateSlug: 'missouri', countySlug: 'pike', expectedCity: 'Bowling Green' },
  { stateSlug: 'missouri', countySlug: 'cooper', expectedCity: 'Boonville' },
  { stateSlug: 'missouri', countySlug: 'bates', expectedCity: 'Butler' },
  { stateSlug: 'missouri', countySlug: 'moniteau', expectedCity: 'California' },
  { stateSlug: 'missouri', countySlug: 'macon', expectedCity: 'Macon' },
  { stateSlug: 'missouri', countySlug: 'new-madrid', expectedCity: 'New Madrid' },
  { stateSlug: 'missouri', countySlug: 'gasconade', expectedCity: 'Hermann' },
  { stateSlug: 'missouri', countySlug: 'cedar', expectedCity: 'Stockton' },
  { stateSlug: 'missouri', countySlug: 'livingston', expectedCity: 'Chillicothe' },
  { stateSlug: 'missouri', countySlug: 'dent', expectedCity: 'Salem' },
  { stateSlug: 'missouri', countySlug: 'pemiscot', expectedCity: 'Caruthersville' },
  { stateSlug: 'missouri', countySlug: 'osage', expectedCity: 'Linn' },
  { stateSlug: 'missouri', countySlug: 'madison', expectedCity: 'Fredericktown' },
  { stateSlug: 'missouri', countySlug: 'douglas', expectedCity: 'Ava' },
  { stateSlug: 'missouri', countySlug: 'mississippi', expectedCity: 'Charleston' },
  { stateSlug: 'missouri', countySlug: 'barton', expectedCity: 'Lamar' },
  { stateSlug: 'missouri', countySlug: 'linn', expectedCity: 'Linneus' },
  { stateSlug: 'missouri', countySlug: 'montgomery', expectedCity: 'Montgomery City' },
  { stateSlug: 'missouri', countySlug: 'bollinger', expectedCity: 'Marble Hill' },
  { stateSlug: 'missouri', countySlug: 'ripley', expectedCity: 'Doniphan' },
  { stateSlug: 'missouri', countySlug: 'wayne', expectedCity: 'Greenville' },
  { stateSlug: 'missouri', countySlug: 'ralls', expectedCity: 'New London' },
  { stateSlug: 'missouri', countySlug: 'howard', expectedCity: 'Fayette' },
  { stateSlug: 'missouri', countySlug: 'st-clair', expectedCity: 'Osceola' },
  { stateSlug: 'missouri', countySlug: 'lewis', expectedCity: 'Monticello' },
  { stateSlug: 'missouri', countySlug: 'grundy', expectedCity: 'Trenton' },
  { stateSlug: 'missouri', countySlug: 'dekalb', expectedCity: 'Maysville' },
  { stateSlug: 'missouri', countySlug: 'ozark', expectedCity: 'Gainesville' },
  { stateSlug: 'missouri', countySlug: 'iron', expectedCity: 'Ironton' },
  { stateSlug: 'missouri', countySlug: 'hickory', expectedCity: 'Hermitage' },
  { stateSlug: 'missouri', countySlug: 'monroe', expectedCity: 'Paris' },
  { stateSlug: 'missouri', countySlug: 'caldwell', expectedCity: 'Kingston' },
  { stateSlug: 'missouri', countySlug: 'oregon', expectedCity: 'Alton' },
  { stateSlug: 'missouri', countySlug: 'daviess', expectedCity: 'Gallatin' },
  { stateSlug: 'missouri', countySlug: 'carroll', expectedCity: 'Carrollton' },
  { stateSlug: 'missouri', countySlug: 'harrison', expectedCity: 'Bethany' },
  { stateSlug: 'missouri', countySlug: 'maries', expectedCity: 'Vienna' },
  { stateSlug: 'missouri', countySlug: 'dade', expectedCity: 'Greenfield' },
  { stateSlug: 'missouri', countySlug: 'chariton', expectedCity: 'Keytesville' },
  { stateSlug: 'missouri', countySlug: 'shannon', expectedCity: 'Eminence' },
  { stateSlug: 'missouri', countySlug: 'gentry', expectedCity: 'Albany' },
  { stateSlug: 'missouri', countySlug: 'clark', expectedCity: 'Kahoka' },
  { stateSlug: 'missouri', countySlug: 'reynolds', expectedCity: 'Centerville' },
  { stateSlug: 'missouri', countySlug: 'shelby', expectedCity: 'Shelbyville' },
  { stateSlug: 'missouri', countySlug: 'sullivan', expectedCity: 'Milan' },
  { stateSlug: 'missouri', countySlug: 'carter', expectedCity: 'Van Buren' },
  { stateSlug: 'missouri', countySlug: 'atchison', expectedCity: 'Rock Port' },
  { stateSlug: 'missouri', countySlug: 'scotland', expectedCity: 'Memphis' },
  { stateSlug: 'missouri', countySlug: 'putnam', expectedCity: 'Unionville' },
  { stateSlug: 'missouri', countySlug: 'schuyler', expectedCity: 'Lancaster' },
  { stateSlug: 'missouri', countySlug: 'mercer', expectedCity: 'Princeton' },
  { stateSlug: 'missouri', countySlug: 'worth', expectedCity: 'Grant City' },
  { stateSlug: 'missouri', countySlug: 'holt', expectedCity: 'Oregon' },
  { stateSlug: 'missouri', countySlug: 'knox', expectedCity: 'Edina' },
  { stateSlug: 'illinois', countySlug: cook, expectedCity: 'Chicago' },
  { stateSlug: 'illinois', countySlug: dupage, expectedCity: 'Wheaton' },
  { stateSlug: 'illinois', countySlug: lake, expectedCity: 'Waukegan' },
  { stateSlug: 'illinois', countySlug: will, expectedCity: 'Joliet' },
  { stateSlug: 'illinois', countySlug: kane, expectedCity: 'Geneva' },
  { stateSlug: 'illinois', countySlug: mchenry, expectedCity: 'Woodstock' },
  { stateSlug: 'illinois', countySlug: winnebago, expectedCity: 'Rockford' },
  { stateSlug: 'illinois', countySlug: madison, expectedCity: 'Edwardsville' },
  { stateSlug: 'illinois', countySlug: 'st-clair', expectedCity: 'Belleville' },
  { stateSlug: 'illinois', countySlug: champaign, expectedCity: 'Urbana' },
  { stateSlug: 'illinois', countySlug: sangamon, expectedCity: 'Springfield' },
  { stateSlug: 'illinois', countySlug: peoria, expectedCity: 'Peoria' },
  { stateSlug: 'illinois', countySlug: mclean, expectedCity: 'Bloomington' },
  { stateSlug: 'illinois', countySlug: kendall, expectedCity: 'Yorkville' },
  { stateSlug: 'illinois', countySlug: 'rock-island', expectedCity: 'Rock Island' },
  { stateSlug: 'illinois', countySlug: tazewell, expectedCity: 'Pekin' },
  { stateSlug: 'illinois', countySlug: lasalle, expectedCity: 'Ottawa' },
  { stateSlug: 'illinois', countySlug: kankakee, expectedCity: 'Kankakee' },
  { stateSlug: 'illinois', countySlug: dekalb, expectedCity: 'Sycamore' },
  { stateSlug: 'illinois', countySlug: macon, expectedCity: 'Decatur' },
  { stateSlug: 'illinois', countySlug: vermilion, expectedCity: 'Danville' },
  { stateSlug: 'illinois', countySlug: williamson, expectedCity: 'Marion' },
  { stateSlug: 'illinois', countySlug: adams, expectedCity: 'Quincy' },
  { stateSlug: 'illinois', countySlug: grundy, expectedCity: 'Morris' },
  { stateSlug: 'illinois', countySlug: whiteside, expectedCity: 'Morrison' },
  { stateSlug: 'illinois', countySlug: boone, expectedCity: 'Belvidere' },
  { stateSlug: 'illinois', countySlug: jackson, expectedCity: 'Murphysboro' },
  { stateSlug: 'illinois', countySlug: ogle, expectedCity: 'Oregon' },
  { stateSlug: 'illinois', countySlug: henry, expectedCity: 'Cambridge' },
  { stateSlug: 'illinois', countySlug: knox, expectedCity: 'Galesburg' },
  { stateSlug: 'illinois', countySlug: coles, expectedCity: 'Charleston' },
  { stateSlug: 'illinois', countySlug: macoupin, expectedCity: 'Carlinville' },
  { stateSlug: 'illinois', countySlug: stephenson, expectedCity: 'Freeport' },
  { stateSlug: 'illinois', countySlug: woodford, expectedCity: 'Eureka' },
  { stateSlug: 'illinois', countySlug: clinton, expectedCity: 'Carlyle' },
  { stateSlug: 'illinois', countySlug: fayette, expectedCity: 'Vandalia' },
  { stateSlug: 'illinois', countySlug: shelby, expectedCity: 'Shelbyville' },
  { stateSlug: 'illinois', countySlug: perry, expectedCity: 'Pinckneyville' },
  { stateSlug: 'illinois', countySlug: washington, expectedCity: 'Nashville' },
  { stateSlug: 'illinois', countySlug: massac, expectedCity: 'Metropolis' },
  { stateSlug: 'illinois', countySlug: johnson, expectedCity: 'Vienna' },
  { stateSlug: 'illinois', countySlug: ford, expectedCity: 'Paxton' },
  { stateSlug: 'illinois', countySlug: white, expectedCity: 'Carmi' },
  { stateSlug: 'illinois', countySlug: clay, expectedCity: 'Louisville' },
  { stateSlug: 'illinois', countySlug: cass, expectedCity: 'Virginia' },
  { stateSlug: 'illinois', countySlug: mason, expectedCity: 'Havana' },
  { stateSlug: 'illinois', countySlug: menard, expectedCity: 'Petersburg' },
  { stateSlug: 'illinois', countySlug: marshall, expectedCity: 'Lacon' },
  { stateSlug: 'illinois', countySlug: greene, expectedCity: 'Carrollton' },
  { stateSlug: 'illinois', countySlug: wabash, expectedCity: 'Mount Carmel' },
  { stateSlug: 'illinois', countySlug: cumberland, expectedCity: 'Toledo' },
  { stateSlug: 'illinois', countySlug: jasper, expectedCity: 'Newton' },
  { stateSlug: 'illinois', countySlug: hamilton, expectedCity: 'McLeansboro' },
  { stateSlug: 'illinois', countySlug: schuyler, expectedCity: 'Rushville' },
  { stateSlug: 'illinois', countySlug: brown, expectedCity: 'Mount Sterling' },
  { stateSlug: 'illinois', countySlug: henderson, expectedCity: 'Oquawka' },
  { stateSlug: 'illinois', countySlug: edwards, expectedCity: 'Albion' },
  { stateSlug: 'illinois', countySlug: putnam, expectedCity: 'Hennepin' },
  { stateSlug: 'illinois', countySlug: stark, expectedCity: 'Toulon' },
  { stateSlug: 'illinois', countySlug: scott, expectedCity: 'Winchester' },
  { stateSlug: 'illinois', countySlug: pulaski, expectedCity: 'Mound City' },
  { stateSlug: 'illinois', countySlug: gallatin, expectedCity: 'Shawneetown' },
  { stateSlug: 'illinois', countySlug: alexander, expectedCity: 'Cairo' },
  { stateSlug: 'illinois', countySlug: calhoun, expectedCity: 'Hardin' },
  { stateSlug: 'illinois', countySlug: pope, expectedCity: 'Golconda' },
  { stateSlug: 'illinois', countySlug: hardin, expectedCity: 'Elizabethtown' },
  { stateSlug: 'illinois', countySlug: bureau, expectedCity: 'Princeton' },
  { stateSlug: 'illinois', countySlug: carroll, expectedCity: 'Mount Carroll' },
  { stateSlug: 'illinois', countySlug: 'jo-daviess', expectedCity: 'Galena' },
  { stateSlug: 'illinois', countySlug: lee, expectedCity: 'Dixon' },
  { stateSlug: 'illinois', countySlug: mercer, expectedCity: 'Aledo' },
  { stateSlug: 'illinois', countySlug: warren, expectedCity: 'Monmouth' },
  { stateSlug: 'illinois', countySlug: christian, expectedCity: 'Taylorville' },
  { stateSlug: 'illinois', countySlug: 'de-witt', expectedCity: 'Clinton' },
  { stateSlug: 'illinois', countySlug: douglas, expectedCity: 'Tuscola' },
  { stateSlug: 'illinois', countySlug: edgar, expectedCity: 'Paris' },
  { stateSlug: 'illinois', countySlug: effingham, expectedCity: 'Effingham' },
  { stateSlug: 'illinois', countySlug: fulton, expectedCity: 'Lewistown' },
  { stateSlug: 'illinois', countySlug: livingston, expectedCity: 'Pontiac' },
  { stateSlug: 'illinois', countySlug: logan, expectedCity: 'Lincoln' },
  { stateSlug: 'illinois', countySlug: moultrie, expectedCity: 'Sullivan' },
  { stateSlug: 'illinois', countySlug: piatt, expectedCity: 'Monticello' },
  { stateSlug: 'illinois', countySlug: hancock, expectedCity: 'Carthage' },
  { stateSlug: 'illinois', countySlug: mcdonough, expectedCity: 'Macomb' },
  { stateSlug: 'illinois', countySlug: morgan, expectedCity: 'Jacksonville' },
  { stateSlug: 'illinois', countySlug: pike, expectedCity: 'Pittsfield' },
  { stateSlug: 'illinois', countySlug: clark, expectedCity: 'Marshall' },
  { stateSlug: 'illinois', countySlug: iroquois, expectedCity: 'Watseka' },
  { stateSlug: 'illinois', countySlug: bond, expectedCity: 'Greenville' },
  { stateSlug: 'illinois', countySlug: jersey, expectedCity: 'Jerseyville' },
  { stateSlug: 'illinois', countySlug: monroe, expectedCity: 'Waterloo' },
  { stateSlug: 'illinois', countySlug: montgomery, expectedCity: 'Hillsboro' },
  { stateSlug: 'illinois', countySlug: randolph, expectedCity: 'Chester' },
  { stateSlug: 'illinois', countySlug: crawford, expectedCity: 'Robinson' },
  { stateSlug: 'illinois', countySlug: franklin, expectedCity: 'Benton' },
  { stateSlug: 'illinois', countySlug: jefferson, expectedCity: 'Mount Vernon' },
  { stateSlug: 'illinois', countySlug: lawrence, expectedCity: 'Lawrenceville' },
  { stateSlug: 'illinois', countySlug: marion, expectedCity: 'Salem' },
  { stateSlug: 'illinois', countySlug: richland, expectedCity: 'Olney' },
  { stateSlug: 'illinois', countySlug: saline, expectedCity: 'Harrisburg' },
  { stateSlug: 'illinois', countySlug: union, expectedCity: 'Jonesboro' },
  { stateSlug: 'illinois', countySlug: wayne, expectedCity: 'Fairfield' },
  { stateSlug: 'michigan', countySlug: wayne, expectedCity: 'Detroit' },
  { stateSlug: 'michigan', countySlug: oakland, expectedCity: 'Pontiac' },
  { stateSlug: 'michigan', countySlug: macomb, expectedCity: 'Mount Clemens' },
  { stateSlug: 'michigan', countySlug: kent, expectedCity: 'Grand Rapids' },
  { stateSlug: 'michigan', countySlug: ottawa, expectedCity: 'Grand Haven' },
  { stateSlug: 'michigan', countySlug: genesee, expectedCity: 'Flint' },
  { stateSlug: 'michigan', countySlug: washtenaw, expectedCity: 'Ann Arbor' },
  { stateSlug: 'michigan', countySlug: ingham, expectedCity: 'Mason' },
  { stateSlug: 'michigan', countySlug: kalamazoo, expectedCity: 'Kalamazoo' },
  { stateSlug: 'michigan', countySlug: livingston, expectedCity: 'Howell' },
  { stateSlug: 'michigan', countySlug: saginaw, expectedCity: 'Saginaw' },
  { stateSlug: 'michigan', countySlug: muskegon, expectedCity: 'Muskegon' },
  { stateSlug: 'michigan', countySlug: 'st-clair', expectedCity: 'Port Huron' },
  { stateSlug: 'michigan', countySlug: jackson, expectedCity: 'Jackson' },
  { stateSlug: 'michigan', countySlug: monroe, expectedCity: 'Monroe' },
  { stateSlug: 'michigan', countySlug: berrien, expectedCity: 'St. Joseph' },
  { stateSlug: 'michigan', countySlug: calhoun, expectedCity: 'Marshall' },
  { stateSlug: 'michigan', countySlug: allegan, expectedCity: 'Allegan' },
  { stateSlug: 'michigan', countySlug: eaton, expectedCity: 'Charlotte' },
  { stateSlug: 'michigan', countySlug: bay, expectedCity: 'Bay City' },
  { stateSlug: 'michigan', countySlug: lenawee, expectedCity: 'Adrian' },
  { stateSlug: 'michigan', countySlug: 'grand-traverse', expectedCity: 'Traverse City' },
  { stateSlug: 'michigan', countySlug: lapeer, expectedCity: 'Lapeer' },
  { stateSlug: 'michigan', countySlug: midland, expectedCity: 'Midland' },
  { stateSlug: 'michigan', countySlug: clinton, expectedCity: 'St. Johns' },
  { stateSlug: 'michigan', countySlug: 'van-buren', expectedCity: 'Paw Paw' },
  { stateSlug: 'michigan', countySlug: montcalm, expectedCity: 'Stanton' },
  { stateSlug: 'michigan', countySlug: marquette, expectedCity: 'Marquette' },
  { stateSlug: 'michigan', countySlug: shiawassee, expectedCity: 'Corunna' },
  { stateSlug: 'michigan', countySlug: ionia, expectedCity: 'Ionia' },
  { stateSlug: 'michigan', countySlug: isabella, expectedCity: 'Mount Pleasant' },
  { stateSlug: 'michigan', countySlug: barry, expectedCity: 'Hastings' },
  { stateSlug: 'michigan', countySlug: 'st-joseph', expectedCity: 'Centreville' },
  { stateSlug: 'michigan', countySlug: tuscola, expectedCity: 'Caro' },
  { stateSlug: 'michigan', countySlug: newaygo, expectedCity: 'White Cloud' },
  { stateSlug: 'michigan', countySlug: cass, expectedCity: 'Cassopolis' },
  { stateSlug: 'michigan', countySlug: branch, expectedCity: 'Coldwater' },
  { stateSlug: 'michigan', countySlug: hillsdale, expectedCity: 'Hillsdale' },
  { stateSlug: 'michigan', countySlug: mecosta, expectedCity: 'Big Rapids' },
  { stateSlug: 'michigan', countySlug: gratiot, expectedCity: 'Ithaca' },
  { stateSlug: 'michigan', countySlug: sanilac, expectedCity: 'Sandusky' },
  { stateSlug: 'michigan', countySlug: houghton, expectedCity: 'Houghton' },
  { stateSlug: 'michigan', countySlug: delta, expectedCity: 'Escanaba' },
  { stateSlug: 'michigan', countySlug: chippewa, expectedCity: 'Sault Ste. Marie' },
  { stateSlug: 'michigan', countySlug: wexford, expectedCity: 'Cadillac' },
  { stateSlug: 'michigan', countySlug: emmet, expectedCity: 'Petoskey' },
  { stateSlug: 'michigan', countySlug: clare, expectedCity: 'Clare' },
  { stateSlug: 'michigan', countySlug: huron, expectedCity: 'Bad Axe' },
  { stateSlug: 'michigan', countySlug: mason, expectedCity: 'Ludington' },
  { stateSlug: 'michigan', countySlug: alpena, expectedCity: 'Alpena' },
  { stateSlug: 'michigan', countySlug: oceana, expectedCity: 'Hart' },
  { stateSlug: 'michigan', countySlug: gladwin, expectedCity: 'Gladwin' },
  { stateSlug: 'michigan', countySlug: otsego, expectedCity: 'Gaylord' },
  { stateSlug: 'michigan', countySlug: charlevoix, expectedCity: 'Charlevoix' },
  { stateSlug: 'michigan', countySlug: manistee, expectedCity: 'Manistee' },
  { stateSlug: 'michigan', countySlug: dickinson, expectedCity: 'Iron Mountain' },
  { stateSlug: 'michigan', countySlug: cheboygan, expectedCity: 'Cheboygan' },
  { stateSlug: 'michigan', countySlug: iosco, expectedCity: 'Tawas City' },
  { stateSlug: 'michigan', countySlug: antrim, expectedCity: 'Bellaire' },
  { stateSlug: 'michigan', countySlug: roscommon, expectedCity: 'Roscommon' },
  { stateSlug: 'michigan', countySlug: osceola, expectedCity: 'Reed City' },
  { stateSlug: 'michigan', countySlug: leelanau, expectedCity: 'Suttons Bay' },
  { stateSlug: 'michigan', countySlug: menominee, expectedCity: 'Menominee' },
  { stateSlug: 'michigan', countySlug: ogemaw, expectedCity: 'West Branch' },
  { stateSlug: 'michigan', countySlug: kalkaska, expectedCity: 'Kalkaska' },
  { stateSlug: 'michigan', countySlug: benzie, expectedCity: 'Beulah' },
  { stateSlug: 'michigan', countySlug: missaukee, expectedCity: 'Lake City' },
  { stateSlug: 'michigan', countySlug: arenac, expectedCity: 'Standish' },
  { stateSlug: 'michigan', countySlug: gogebic, expectedCity: 'Bessemer' },
  { stateSlug: 'michigan', countySlug: crawford, expectedCity: 'Grayling' },
  { stateSlug: 'michigan', countySlug: lake, expectedCity: 'Baldwin' },
  { stateSlug: 'michigan', countySlug: 'presque-isle', expectedCity: 'Rogers City' },
  { stateSlug: 'michigan', countySlug: iron, expectedCity: 'Crystal Falls' },
  { stateSlug: 'michigan', countySlug: mackinac, expectedCity: 'St. Ignace' },
  { stateSlug: 'michigan', countySlug: alcona, expectedCity: 'Harrisville' },
  { stateSlug: 'michigan', countySlug: montmorency, expectedCity: 'Atlanta' },
  { stateSlug: 'michigan', countySlug: oscoda, expectedCity: 'Mio' },
  { stateSlug: 'michigan', countySlug: alger, expectedCity: 'Munising' },
  { stateSlug: 'michigan', countySlug: schoolcraft, expectedCity: 'Manistique' },
  { stateSlug: 'michigan', countySlug: baraga, expectedCity: 'Baraga' },
  { stateSlug: 'michigan', countySlug: luce, expectedCity: 'Newberry' },
  { stateSlug: 'michigan', countySlug: ontonagon, expectedCity: 'Ontonagon' },
  { stateSlug: 'michigan', countySlug: keweenaw, expectedCity: 'Eagle River' },
  { stateSlug: 'indiana', countySlug: marion, expectedCity: 'Indianapolis' },
  { stateSlug: 'indiana', countySlug: lake, expectedCity: 'Crown Point' },
  { stateSlug: 'indiana', countySlug: allen, expectedCity: 'Fort Wayne' },
  { stateSlug: 'indiana', countySlug: hamilton, expectedCity: 'Noblesville' },
  { stateSlug: 'indiana', countySlug: 'st-joseph', expectedCity: 'South Bend' },
  { stateSlug: 'indiana', countySlug: elkhart, expectedCity: 'Goshen' },
  { stateSlug: 'indiana', countySlug: hendricks, expectedCity: 'Danville' },
  { stateSlug: 'indiana', countySlug: tippecanoe, expectedCity: 'Lafayette' },
  { stateSlug: 'indiana', countySlug: vanderburgh, expectedCity: 'Evansville' },
  { stateSlug: 'indiana', countySlug: johnson, expectedCity: 'Franklin' },
  { stateSlug: 'indiana', countySlug: porter, expectedCity: 'Valparaiso' },
  { stateSlug: 'indiana', countySlug: monroe, expectedCity: 'Bloomington' },
  { stateSlug: 'indiana', countySlug: madison, expectedCity: 'Anderson' },
  { stateSlug: 'indiana', countySlug: clark, expectedCity: 'Jeffersonville' },
  { stateSlug: 'indiana', countySlug: delaware, expectedCity: 'Muncie' },
  { stateSlug: 'indiana', countySlug: laporte, expectedCity: 'La Porte' },
  { stateSlug: 'indiana', countySlug: vigo, expectedCity: 'Terre Haute' },
  { stateSlug: 'indiana', countySlug: hancock, expectedCity: 'Greenfield' },
  { stateSlug: 'indiana', countySlug: bartholomew, expectedCity: 'Columbus' },
  { stateSlug: 'indiana', countySlug: howard, expectedCity: 'Kokomo' },
  { stateSlug: 'indiana', countySlug: boone, expectedCity: 'Lebanon' },
  { stateSlug: 'indiana', countySlug: floyd, expectedCity: 'New Albany' },
  { stateSlug: 'indiana', countySlug: kosciusko, expectedCity: 'Warsaw' },
  { stateSlug: 'indiana', countySlug: morgan, expectedCity: 'Martinsville' },
  { stateSlug: 'indiana', countySlug: warrick, expectedCity: 'Boonville' },
  { stateSlug: 'indiana', countySlug: grant, expectedCity: 'Marion' },
  { stateSlug: 'indiana', countySlug: wayne, expectedCity: 'Richmond' },
  { stateSlug: 'indiana', countySlug: dearborn, expectedCity: 'Lawrenceburg' },
  { stateSlug: 'indiana', countySlug: henry, expectedCity: 'New Castle' },
  { stateSlug: 'indiana', countySlug: noble, expectedCity: 'Albion' },
  { stateSlug: 'indiana', countySlug: jackson, expectedCity: 'Seymour' },
  { stateSlug: 'indiana', countySlug: marshall, expectedCity: 'Plymouth' },
  { stateSlug: 'indiana', countySlug: shelby, expectedCity: 'Shelbyville' },
  { stateSlug: 'indiana', countySlug: lawrence, expectedCity: 'Bedford' },
  { stateSlug: 'indiana', countySlug: dekalb, expectedCity: 'Auburn' },
  { stateSlug: 'indiana', countySlug: dubois, expectedCity: 'Jasper' },
  { stateSlug: 'indiana', countySlug: lagrange, expectedCity: 'LaGrange' },
  { stateSlug: 'indiana', countySlug: harrison, expectedCity: 'Corydon' },
  { stateSlug: 'indiana', countySlug: montgomery, expectedCity: 'Crawfordsville' },
  { stateSlug: 'indiana', countySlug: putnam, expectedCity: 'Greencastle' },
  { stateSlug: 'indiana', countySlug: cass, expectedCity: 'Logansport' },
  { stateSlug: 'indiana', countySlug: huntington, expectedCity: 'Huntington' },
  { stateSlug: 'indiana', countySlug: adams, expectedCity: 'Decatur' },
  { stateSlug: 'indiana', countySlug: knox, expectedCity: 'Vincennes' },
  { stateSlug: 'indiana', countySlug: whitley, expectedCity: 'Columbia City' },
  { stateSlug: 'indiana', countySlug: steuben, expectedCity: 'Angola' },
  { stateSlug: 'indiana', countySlug: miami, expectedCity: 'Peru' },
  { stateSlug: 'indiana', countySlug: daviess, expectedCity: 'Washington' },
  { stateSlug: 'indiana', countySlug: jasper, expectedCity: 'Rensselaer' },
  { stateSlug: 'indiana', countySlug: jefferson, expectedCity: 'Madison' },
  { stateSlug: 'indiana', countySlug: clinton, expectedCity: 'Frankfort' },
  { stateSlug: 'indiana', countySlug: gibson, expectedCity: 'Princeton' },
  { stateSlug: 'indiana', countySlug: greene, expectedCity: 'Bloomfield' },
  { stateSlug: 'indiana', countySlug: wabash, expectedCity: 'Wabash' },
  { stateSlug: 'indiana', countySlug: ripley, expectedCity: 'Versailles' },
  { stateSlug: 'indiana', countySlug: wells, expectedCity: 'Bluffton' },
  { stateSlug: 'indiana', countySlug: washington, expectedCity: 'Salem' },
  { stateSlug: 'indiana', countySlug: jennings, expectedCity: 'Vernon' },
  { stateSlug: 'indiana', countySlug: decatur, expectedCity: 'Greensburg' },
  { stateSlug: 'indiana', countySlug: clay, expectedCity: 'Brazil' },
  { stateSlug: 'indiana', countySlug: scott, expectedCity: 'Scottsburg' },
  { stateSlug: 'indiana', countySlug: white, expectedCity: 'Monticello' },
  { stateSlug: 'indiana', countySlug: posey, expectedCity: 'Mount Vernon' },
  { stateSlug: 'indiana', countySlug: randolph, expectedCity: 'Winchester' },
  { stateSlug: 'indiana', countySlug: fayette, expectedCity: 'Connersville' },
  { stateSlug: 'indiana', countySlug: starke, expectedCity: 'Knox' },
  { stateSlug: 'indiana', countySlug: franklin, expectedCity: 'Brookville' },
  { stateSlug: 'indiana', countySlug: owen, expectedCity: 'Spencer' },
  { stateSlug: 'indiana', countySlug: sullivan, expectedCity: 'Sullivan' },
  { stateSlug: 'indiana', countySlug: carroll, expectedCity: 'Delphi' },
  { stateSlug: 'indiana', countySlug: fulton, expectedCity: 'Rochester' },
  { stateSlug: 'indiana', countySlug: jay, expectedCity: 'Portland' },
  { stateSlug: 'indiana', countySlug: spencer, expectedCity: 'Rockport' },
  { stateSlug: 'indiana', countySlug: orange, expectedCity: 'Paoli' },
  { stateSlug: 'indiana', countySlug: perry, expectedCity: 'Tell City' },
  { stateSlug: 'indiana', countySlug: fountain, expectedCity: 'Covington' },
  { stateSlug: 'indiana', countySlug: parke, expectedCity: 'Rockville' },
  { stateSlug: 'indiana', countySlug: rush, expectedCity: 'Rushville' },
  { stateSlug: 'indiana', countySlug: brown, expectedCity: 'Nashville' },
  { stateSlug: 'indiana', countySlug: vermillion, expectedCity: 'Newport' },
  { stateSlug: 'indiana', countySlug: tipton, expectedCity: 'Tipton' },
  { stateSlug: 'indiana', countySlug: newton, expectedCity: 'Kentland' },
  { stateSlug: 'indiana', countySlug: pulaski, expectedCity: 'Winamac' },
  { stateSlug: 'indiana', countySlug: pike, expectedCity: 'Petersburg' },
  { stateSlug: 'indiana', countySlug: blackford, expectedCity: 'Hartford City' },
  { stateSlug: 'indiana', countySlug: crawford, expectedCity: 'English' },
  { stateSlug: 'indiana', countySlug: switzerland, expectedCity: 'Vevay' },
  { stateSlug: 'indiana', countySlug: martin, expectedCity: 'Shoals' },
  { stateSlug: 'indiana', countySlug: benton, expectedCity: 'Fowler' },
  { stateSlug: 'indiana', countySlug: warren, expectedCity: 'Williamsport' },
  { stateSlug: 'indiana', countySlug: union, expectedCity: 'Liberty' },
  { stateSlug: 'indiana', countySlug: ohio, expectedCity: 'Rising Sun' },
  { stateSlug: 'ohio', countySlug: franklin, expectedCity: 'Columbus' },
  { stateSlug: 'ohio', countySlug: cuyahoga, expectedCity: 'Cleveland' },
  { stateSlug: 'ohio', countySlug: hamilton, expectedCity: 'Cincinnati' },
  { stateSlug: 'ohio', countySlug: montgomery, expectedCity: 'Dayton' },
  { stateSlug: 'ohio', countySlug: summit, expectedCity: 'Akron' },
  { stateSlug: 'ohio', countySlug: lucas, expectedCity: 'Toledo' },
  { stateSlug: 'ohio', countySlug: butler, expectedCity: 'Hamilton' },
  { stateSlug: 'ohio', countySlug: stark, expectedCity: 'Canton' },
  { stateSlug: 'ohio', countySlug: lorain, expectedCity: 'Elyria' },
  { stateSlug: 'ohio', countySlug: warren, expectedCity: 'Lebanon' },
  { stateSlug: 'ohio', countySlug: delaware, expectedCity: 'Delaware' },
  { stateSlug: 'ohio', countySlug: lake, expectedCity: 'Painesville' },
  { stateSlug: 'ohio', countySlug: mahoning, expectedCity: 'Youngstown' },
  { stateSlug: 'ohio', countySlug: clermont, expectedCity: 'Batavia' },
  { stateSlug: 'ohio', countySlug: trumbull, expectedCity: 'Warren' },
  { stateSlug: 'ohio', countySlug: licking, expectedCity: 'Newark' },
  { stateSlug: 'ohio', countySlug: medina, expectedCity: 'Medina' },
  { stateSlug: 'ohio', countySlug: greene, expectedCity: 'Xenia' },
  { stateSlug: 'ohio', countySlug: fairfield, expectedCity: 'Lancaster' },
  { stateSlug: 'ohio', countySlug: portage, expectedCity: 'Ravenna' },
  { stateSlug: 'ohio', countySlug: wood, expectedCity: 'Bowling Green' },
  { stateSlug: 'ohio', countySlug: clark, expectedCity: 'Springfield' },
  { stateSlug: 'ohio', countySlug: richland, expectedCity: 'Mansfield' },
  { stateSlug: 'ohio', countySlug: wayne, expectedCity: 'Wooster' },
  { stateSlug: 'ohio', countySlug: miami, expectedCity: 'Troy' },
  { stateSlug: 'ohio', countySlug: allen, expectedCity: 'Lima' },
  { stateSlug: 'ohio', countySlug: columbiana, expectedCity: 'Lisbon' },
  { stateSlug: 'ohio', countySlug: ashtabula, expectedCity: 'Jefferson' },
  { stateSlug: 'ohio', countySlug: geauga, expectedCity: 'Chardon' },
  { stateSlug: 'ohio', countySlug: tuscarawas, expectedCity: 'New Philadelphia' },
  { stateSlug: 'ohio', countySlug: muskingum, expectedCity: 'Zanesville' },
  { stateSlug: 'ohio', countySlug: ross, expectedCity: 'Chillicothe' },
  { stateSlug: 'ohio', countySlug: hancock, expectedCity: 'Findlay' },
  { stateSlug: 'ohio', countySlug: union, expectedCity: 'Marysville' },
  { stateSlug: 'ohio', countySlug: erie, expectedCity: 'Sandusky' },
  { stateSlug: 'ohio', countySlug: scioto, expectedCity: 'Portsmouth' },
  { stateSlug: 'ohio', countySlug: marion, expectedCity: 'Marion' },
  { stateSlug: 'ohio', countySlug: knox, expectedCity: 'Mount Vernon' },
  { stateSlug: 'ohio', countySlug: belmont, expectedCity: 'St. Clairsville' },
  { stateSlug: 'ohio', countySlug: pickaway, expectedCity: 'Circleville' },
  { stateSlug: 'ohio', countySlug: highland, expectedCity: 'Hillsboro' },
  { stateSlug: 'ohio', countySlug: mercer, expectedCity: 'Celina' },
  { stateSlug: 'ohio', countySlug: clinton, expectedCity: 'Wilmington' },
  { stateSlug: 'ohio', countySlug: crawford, expectedCity: 'Bucyrus' },
  { stateSlug: 'ohio', countySlug: fulton, expectedCity: 'Wauseon' },
  { stateSlug: 'ohio', countySlug: preble, expectedCity: 'Eaton' },
  { stateSlug: 'ohio', countySlug: ottawa, expectedCity: 'Port Clinton' },
  { stateSlug: 'ohio', countySlug: champaign, expectedCity: 'Urbana' },
  { stateSlug: 'ohio', countySlug: guernsey, expectedCity: 'Cambridge' },
  { stateSlug: 'ohio', countySlug: defiance, expectedCity: 'Defiance' },
  { stateSlug: 'ohio', countySlug: coshocton, expectedCity: 'Coshocton' },
  { stateSlug: 'ohio', countySlug: morrow, expectedCity: 'Mount Gilead' },
  { stateSlug: 'ohio', countySlug: williams, expectedCity: 'Bryan' },
  { stateSlug: 'ohio', countySlug: perry, expectedCity: 'New Lexington' },
  { stateSlug: 'ohio', countySlug: putnam, expectedCity: 'Ottawa' },
  { stateSlug: 'ohio', countySlug: jackson, expectedCity: 'Jackson' },
  { stateSlug: 'ohio', countySlug: hardin, expectedCity: 'Kenton' },
  { stateSlug: 'ohio', countySlug: gallia, expectedCity: 'Gallipolis' },
  { stateSlug: 'ohio', countySlug: 'van-wert', expectedCity: 'Van Wert' },
  { stateSlug: 'ohio', countySlug: fayette, expectedCity: 'Washington Court House' },
  { stateSlug: 'ohio', countySlug: adams, expectedCity: 'West Union' },
  { stateSlug: 'ohio', countySlug: henry, expectedCity: 'Napoleon' },
  { stateSlug: 'ohio', countySlug: hocking, expectedCity: 'Logan' },
  { stateSlug: 'ohio', countySlug: pike, expectedCity: 'Waverly' },
  { stateSlug: 'ohio', countySlug: carroll, expectedCity: 'Carrollton' },
  { stateSlug: 'ohio', countySlug: meigs, expectedCity: 'Pomeroy' },
  { stateSlug: 'ohio', countySlug: wyandot, expectedCity: 'Upper Sandusky' },
  { stateSlug: 'ohio', countySlug: paulding, expectedCity: 'Paulding' },
  { stateSlug: 'ohio', countySlug: noble, expectedCity: 'Caldwell' },
  { stateSlug: 'ohio', countySlug: harrison, expectedCity: 'Cadiz' },
  { stateSlug: 'ohio', countySlug: morgan, expectedCity: 'McConnelsville' },
  { stateSlug: 'ohio', countySlug: monroe, expectedCity: 'Woodsfield' },
  { stateSlug: 'ohio', countySlug: vinton, expectedCity: 'McArthur' },
  { stateSlug: 'ohio', countySlug: ashland, expectedCity: 'Ashland' },
  { stateSlug: 'ohio', countySlug: auglaize, expectedCity: 'Wapakoneta' },
  { stateSlug: 'ohio', countySlug: brown, expectedCity: 'Georgetown' },
  { stateSlug: 'ohio', countySlug: darke, expectedCity: 'Greenville' },
  { stateSlug: 'ohio', countySlug: holmes, expectedCity: 'Millersburg' },
  { stateSlug: 'ohio', countySlug: huron, expectedCity: 'Norwalk' },
  { stateSlug: 'ohio', countySlug: jefferson, expectedCity: 'Steubenville' },
  { stateSlug: 'ohio', countySlug: lawrence, expectedCity: 'Ironton' },
  { stateSlug: 'ohio', countySlug: logan, expectedCity: 'Bellefontaine' },
  { stateSlug: 'ohio', countySlug: madison, expectedCity: 'London' },
  { stateSlug: 'ohio', countySlug: sandusky, expectedCity: 'Fremont' },
  { stateSlug: 'ohio', countySlug: seneca, expectedCity: 'Tiffin' },
  { stateSlug: 'ohio', countySlug: shelby, expectedCity: 'Sidney' },
  { stateSlug: 'ohio', countySlug: athens, expectedCity: 'Athens' },
  { stateSlug: 'ohio', countySlug: washington, expectedCity: 'Marietta' },
  { stateSlug: 'kentucky', countySlug: jefferson, expectedCity: 'Louisville' },
  { stateSlug: 'kentucky', countySlug: fayette, expectedCity: 'Lexington' },
  { stateSlug: 'kentucky', countySlug: kenton, expectedCity: 'Covington' },
  { stateSlug: 'kentucky', countySlug: warren, expectedCity: 'Bowling Green' },
  { stateSlug: 'kentucky', countySlug: boone, expectedCity: 'Burlington' },
  { stateSlug: 'kentucky', countySlug: hardin, expectedCity: 'Elizabethtown' },
  { stateSlug: 'kentucky', countySlug: daviess, expectedCity: 'Owensboro' },
  { stateSlug: 'kentucky', countySlug: madison, expectedCity: 'Richmond' },
  { stateSlug: 'kentucky', countySlug: campbell, expectedCity: 'Alexandria' },
  { stateSlug: 'kentucky', countySlug: bullitt, expectedCity: 'Shepherdsville' },
  { stateSlug: 'kentucky', countySlug: oldham, expectedCity: 'La Grange' },
  { stateSlug: 'kentucky', countySlug: christian, expectedCity: 'Hopkinsville' },
  { stateSlug: 'kentucky', countySlug: pulaski, expectedCity: 'Somerset' },
  { stateSlug: 'kentucky', countySlug: mccracken, expectedCity: 'Paducah' },
  { stateSlug: 'kentucky', countySlug: laurel, expectedCity: 'London' },
  { stateSlug: 'kentucky', countySlug: scott, expectedCity: 'Georgetown' },
  { stateSlug: 'kentucky', countySlug: jessamine, expectedCity: 'Nicholasville' },
  { stateSlug: 'kentucky', countySlug: pike, expectedCity: 'Pikeville' },
  { stateSlug: 'kentucky', countySlug: franklin, expectedCity: 'Frankfort' },
  { stateSlug: 'kentucky', countySlug: shelby, expectedCity: 'Shelbyville' },
  { stateSlug: 'kentucky', countySlug: nelson, expectedCity: 'Bardstown' },
  { stateSlug: 'kentucky', countySlug: boyd, expectedCity: 'Catlettsburg' },
  { stateSlug: 'kentucky', countySlug: barren, expectedCity: 'Glasgow' },
  { stateSlug: 'kentucky', countySlug: hopkins, expectedCity: 'Madisonville' },
  { stateSlug: 'kentucky', countySlug: henderson, expectedCity: 'Henderson' },
  { stateSlug: 'kentucky', countySlug: calloway, expectedCity: 'Murray' },
  { stateSlug: 'kentucky', countySlug: clark, expectedCity: 'Winchester' },
  { stateSlug: 'kentucky', countySlug: whitley, expectedCity: 'Williamsburg' },
  { stateSlug: 'kentucky', countySlug: graves, expectedCity: 'Mayfield' },
  { stateSlug: 'kentucky', countySlug: greenup, expectedCity: 'Greenup' },
  { stateSlug: 'kentucky', countySlug: floyd, expectedCity: 'Prestonsburg' },
  { stateSlug: 'kentucky', countySlug: boyle, expectedCity: 'Danville' },
  { stateSlug: 'kentucky', countySlug: marshall, expectedCity: 'Benton' },
  { stateSlug: 'kentucky', countySlug: meade, expectedCity: 'Brandenburg' },
  { stateSlug: 'kentucky', countySlug: muhlenberg, expectedCity: 'Greenville' },
  { stateSlug: 'kentucky', countySlug: knox, expectedCity: 'Barbourville' },
  { stateSlug: 'kentucky', countySlug: logan, expectedCity: 'Russellville' },
  { stateSlug: 'kentucky', countySlug: montgomery, expectedCity: 'Mount Sterling' },
  { stateSlug: 'kentucky', countySlug: woodford, expectedCity: 'Versailles' },
  { stateSlug: 'kentucky', countySlug: grayson, expectedCity: 'Leitchfield' },
  { stateSlug: 'kentucky', countySlug: taylor, expectedCity: 'Campbellsville' },
  { stateSlug: 'kentucky', countySlug: grant, expectedCity: 'Williamstown' },
  { stateSlug: 'kentucky', countySlug: perry, expectedCity: 'Hazard' },
  { stateSlug: 'kentucky', countySlug: carter, expectedCity: 'Grayson' },
  { stateSlug: 'kentucky', countySlug: lincoln, expectedCity: 'Stanford' },
  { stateSlug: 'kentucky', countySlug: anderson, expectedCity: 'Lawrenceburg' },
  { stateSlug: 'kentucky', countySlug: rowan, expectedCity: 'Morehead' },
  { stateSlug: 'kentucky', countySlug: harlan, expectedCity: 'Harlan' },
  { stateSlug: 'kentucky', countySlug: ohio, expectedCity: 'Hartford' },
  { stateSlug: 'kentucky', countySlug: mercer, expectedCity: 'Harrodsburg' },
  { stateSlug: 'kentucky', countySlug: allen, expectedCity: 'Scottsville' },
  { stateSlug: 'kentucky', countySlug: bell, expectedCity: 'Pineville' },
  { stateSlug: 'kentucky', countySlug: johnson, expectedCity: 'Paintsville' },
  { stateSlug: 'kentucky', countySlug: breckinridge, expectedCity: 'Hardinsburg' },
  { stateSlug: 'kentucky', countySlug: spencer, expectedCity: 'Taylorsville' },
  { stateSlug: 'kentucky', countySlug: simpson, expectedCity: 'Franklin' },
  { stateSlug: 'kentucky', countySlug: hart, expectedCity: 'Munfordville' },
  { stateSlug: 'kentucky', countySlug: marion, expectedCity: 'Lebanon' },
  { stateSlug: 'kentucky', countySlug: bourbon, expectedCity: 'Paris' },
  { stateSlug: 'kentucky', countySlug: harrison, expectedCity: 'Cynthiana' },
  { stateSlug: 'kentucky', countySlug: letcher, expectedCity: 'Whitesburg' },
  { stateSlug: 'kentucky', countySlug: wayne, expectedCity: 'Monticello' },
  { stateSlug: 'kentucky', countySlug: adair, expectedCity: 'Columbia' },
  { stateSlug: 'kentucky', countySlug: clay, expectedCity: 'Manchester' },
  { stateSlug: 'kentucky', countySlug: russell, expectedCity: 'Jamestown' },
  { stateSlug: 'kentucky', countySlug: garrard, expectedCity: 'Lancaster' },
  { stateSlug: 'kentucky', countySlug: mccreary, expectedCity: 'Whitley City' },
  { stateSlug: 'kentucky', countySlug: mason, expectedCity: 'Maysville' },
  { stateSlug: 'kentucky', countySlug: henry, expectedCity: 'New Castle' },
  { stateSlug: 'kentucky', countySlug: casey, expectedCity: 'Liberty' },
  { stateSlug: 'kentucky', countySlug: rockcastle, expectedCity: 'Mount Vernon' },
  { stateSlug: 'kentucky', countySlug: fleming, expectedCity: 'Flemingsburg' },
  { stateSlug: 'kentucky', countySlug: lawrence, expectedCity: 'Louisa' },
  { stateSlug: 'kentucky', countySlug: larue, expectedCity: 'Hodgenville' },
  { stateSlug: 'kentucky', countySlug: pendleton, expectedCity: 'Falmouth' },
  { stateSlug: 'kentucky', countySlug: morgan, expectedCity: 'West Liberty' },
  { stateSlug: 'kentucky', countySlug: trigg, expectedCity: 'Cadiz' },
  { stateSlug: 'kentucky', countySlug: estill, expectedCity: 'Irvine' },
  { stateSlug: 'kentucky', countySlug: bath, expectedCity: 'Owingsville' },
  { stateSlug: 'kentucky', countySlug: jackson, expectedCity: 'McKee' },
  { stateSlug: 'kentucky', countySlug: knott, expectedCity: 'Hindman' },
  { stateSlug: 'kentucky', countySlug: todd, expectedCity: 'Elkton' },
  { stateSlug: 'kentucky', countySlug: webster, expectedCity: 'Dixon' },
  { stateSlug: 'kentucky', countySlug: lewis, expectedCity: 'Vanceburg' },
  { stateSlug: 'kentucky', countySlug: edmonson, expectedCity: 'Brownsville' },
  { stateSlug: 'kentucky', countySlug: powell, expectedCity: 'Stanton' },
  { stateSlug: 'kentucky', countySlug: caldwell, expectedCity: 'Princeton' },
  { stateSlug: 'kentucky', countySlug: butler, expectedCity: 'Morgantown' },
  { stateSlug: 'kentucky', countySlug: union, expectedCity: 'Morganfield' },
  { stateSlug: 'kentucky', countySlug: washington, expectedCity: 'Springfield' },
  { stateSlug: 'kentucky', countySlug: breathitt, expectedCity: 'Jackson' },
  { stateSlug: 'kentucky', countySlug: green, expectedCity: 'Greensburg' },
  { stateSlug: 'kentucky', countySlug: owen, expectedCity: 'Owenton' },
  { stateSlug: 'kentucky', countySlug: monroe, expectedCity: 'Tompkinsville' },
  { stateSlug: 'kentucky', countySlug: carroll, expectedCity: 'Carrollton' },
  { stateSlug: 'kentucky', countySlug: magoffin, expectedCity: 'Salyersville' },
  { stateSlug: 'kentucky', countySlug: martin, expectedCity: 'Inez' },
  { stateSlug: 'kentucky', countySlug: metcalfe, expectedCity: 'Edmonton' },
  { stateSlug: 'kentucky', countySlug: leslie, expectedCity: 'Hyden' },
  { stateSlug: 'kentucky', countySlug: lyon, expectedCity: 'Eddyville' },
  { stateSlug: 'kentucky', countySlug: clinton, expectedCity: 'Albany' },
  { stateSlug: 'kentucky', countySlug: hancock, expectedCity: 'Hawesville' },
  { stateSlug: 'kentucky', countySlug: mclean, expectedCity: 'Calhoun' },
];

let totalIssues = 0;

for (const stateSlug of CURATED_STATES) {
  const state = getLocalState(stateSlug);
  if (!state) {
    console.error(`Missing state: ${stateSlug}`);
    totalIssues += 1;
    continue;
  }

  const counties = getCountiesForState(stateSlug);

  for (const county of counties) {
    const result = getMoversForCounty(stateSlug, county.slug);
    if (!result) continue;

    const { movers } = result;
    const title = buildCountyTitle(county, state.name);
    const description = buildCountyDescription(county, state.name, movers.length);
    const path = getCountyPath(stateSlug, county.slug);
    const countyLabel = buildCountyLabel(county);
    const faqItems = buildCountyFaqItems(county, state.name, movers);
    const testimonials = buildCountyTestimonials(county, state.name);

    const graph = buildCountySchemaGraph({
      title,
      description,
      path,
      breadcrumbs: [
        { name: 'Home', path: '/' },
        { name: 'Local Movers', path: '/local-movers' },
        { name: state.name, path: `/local-movers/${stateSlug}` },
        { name: countyLabel, path },
      ],
      movers,
      county,
      stateName: state.name,
      faqItems,
      testimonials,
    });

    const issues = validateCountySchemaGraph(graph, county);
    if (issues.length) {
      for (const issue of issues) {
        console.error(`[${issue.stateSlug}/${issue.countySlug}] ${issue.issue}`);
        totalIssues += 1;
      }
    }
  }
}

for (const check of SPOT_CHECK) {
  const county = getCounty(check.stateSlug, check.countySlug);
  const state = getLocalState(check.stateSlug);
  if (!county || !state) {
    console.error(`Spot check missing data: ${check.stateSlug}/${check.countySlug}`);
    totalIssues += 1;
    continue;
  }

  const primaryCity = buildSchemaPrimaryCity(county);
  if (check.expectedCity && primaryCity !== check.expectedCity) {
    console.error(
      `[spot-check ${check.stateSlug}/${check.countySlug}] expected primary city "${check.expectedCity}", got "${primaryCity ?? 'none'}"`
    );
    totalIssues += 1;
  }
}

if (totalIssues > 0) {
  console.error(`\nCounty schema validation failed with ${totalIssues} issue(s).`);
  process.exit(1);
}

console.log(
  `County schema validation passed for ${CURATED_STATES.length} curated states and ${SPOT_CHECK.length} spot checks.`
);