import { type PackDef, z, s, b } from './wa-tier2-render';

/** WA Tier 2 Wave 1 packs 7–12 */
export const packsB: PackDef[] = [
  {
    file: 'lewis-wa.ts',
    exportName: 'lewisCountyWaTier2Intelligence',
    slug: 'lewis',
    hubTitle: 'Lewis County Moving Intelligence Hub',
    eyebrow: 'Lewis · Centralia / Chehalis — I-5 mid-south',
    h1: 'Moving in Lewis County: Centralia, Chehalis & I-5 Mid-South Access',
    heroOpener:
      'Lewis County is I-5 mid-south corridor product — Centralia multi-story and multi-family stock, Chehalis seat multi-unit, Napavine and rural edges, and freeflow that is not Thurston continuous Olympia capital multi-family with different labels. Expect rain staging, industrial-adjacent residential, and longer empty miles under one county. This guide is for people moving in Lewis as I-5 mid-south corridor — not an Olympia rename.',
    heroCredibility:
      'I-5 mid-south corridor · Centralia / Chehalis · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-5 · US-12 · SR-6 · SR-507 · Harrison Ave corridors',
    parentLabel: 'Thurston County',
    parentHref: '/local-movers/washington/thurston',
    compareIntro:
      'Lewis is I-5 mid-south corridor multi-story product — not Thurston continuous Olympia capital multi-family density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Thurston crews fight I-5 peaks into Olympia/Lacey. Lewis pairs ride I-5 and US-12 — freer mid-day further south, still peak-heavy on Centralia arterials and Chehalis corridors.'),
      b('Housing stock differences', 'Thurston mixes capital multi-story and Lacey multi-family. Lewis mixes Centralia multi-unit, Chehalis multi-story, and rural lots — more discontinuous corridor-town product, less continuous capital suburb density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; multi-family elevators appear on growth edges; rural lots add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Lewis quotes often sit at mid-south secondary rates for driveway SFH — multi-story access and empty miles still push prices up.'),
      b('Role difference', 'Lewis is I-5 mid-south corridor — not Olympia product renamed.'),
    ],
    whatIntro: 'Corridor multi-story, I-5 freeflow, and rain staging — not interchangeable Olympia boilerplate.',
    whatBullets: [
      b('I-5 freeflow is still billable', 'Lewis ↔ Thurston pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Centralia multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('Empty miles from Olympia yards are real', 'Even “local” Lewis pairs can price as distance work for Thurston-based crews.'),
      b('Rain staging rewrites open-carry plans', 'Protect cardboard and plan covered unload windows.'),
    ],
    zonesHeading: 'Lewis zones: Centralia multi-story, Chehalis multi-unit, Napavine edges & rural lots',
    zonesIntro: 'Two to four sharp products — multi-story seat, multi-unit twin town, corridor edges, and rural lots.',
    zones: [
      z('centralia', 'Centralia multi-story & multi-unit', 'Centralia', ['Centralia', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-5 freeflow'], ['centralia'], 'Inventory stairs; plan temporary no-parking.'),
      z('chehalis', 'Chehalis multi-unit & seat stock', 'Chehalis', ['Chehalis', 'seat multi-family'], 'Multi-unit, multi-story, older SFH', ['Stairs', 'Street parking', 'Mixed curb'], ['chehalis'], 'Inventory access type; prefer mid-week mornings.'),
      z('napavine', 'Napavine / I-5 corridor edges', 'Napavine', ['Napavine', 'I-5 multi-family'], 'SFH, multi-family, mixed stock', ['I-5 freeflow', 'Empty miles'], ['napavine'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-lots', 'Eastern rural lots', 'Rural lots', ['rural tracts', 'eastern approaches'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Rain staging'], ['east lewis'], 'Survey approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('i5-midsouth', 'I-5 mid-south freeflow', 'South pairs still peak hard toward Thurston.', ['Price portal-to-portal honestly.', 'Clarify Olympia second addresses early.']),
      s('centralia-seat', 'Centralia multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('rain-staging', 'Rain staging module', 'Open carries need weather-aware plans.', ['Protect cardboard and electronics.', 'Prefer mid-week mornings over saturated weekends when possible.']),
    ],
    schoolsIntro: 'Lewis families compare Centralia, Chehalis, Napavine, and related district feeders — verify address boundaries; do not assume Thurston maps apply.',
    hospitalsDetail: 'Providence Centralia and regional specialty spillover serve the county; map peak I-5 times for ER access.',
    costIntro: 'Multi-story access, I-5 freeflow, and empty miles from Olympia yards often matter more than raw miles.',
    seasonalIntro: 'School years, rain seasons, and winter ice reshape demand by pocket.',
  },
  {
    file: 'grant-wa.ts',
    exportName: 'grantCountyWaTier2Intelligence',
    slug: 'grant',
    hubTitle: 'Grant County Moving Intelligence Hub',
    eyebrow: 'Grant · Moses Lake — Columbia Basin',
    h1: 'Moving in Grant County: Moses Lake, Columbia Basin & I-90 Access',
    heroOpener:
      'Grant County is Columbia Basin independent product — Moses Lake multi-story and multi-family stock, Ephrata and Quincy edges, ag-adjacent residential, and freeflow on I-90 that is not Cascade/Puget Sound product with different labels. Expect agricultural calendars, summer heat pacing, and longer empty miles under one large county. This guide is for people moving in Grant as basin hub — not a Seattle-collar rename.',
    heroCredibility:
      'Columbia Basin independent · Moses Lake hub · I-90 freeflow · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-90 · SR-17 · SR-28 · SR-282 · Pioneer Way corridors',
    parentLabel: 'independent Columbia Basin (vs Puget Sound / Cascade defaults)',
    parentHref: '/local-movers/washington/king',
    compareIntro:
      'Grant is independent Columbia Basin hub on I-90 — not King Puget Sound multi-family density and not pure rural desert freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'King crews fight I-5/I-405 metro peaks. Grant pairs ride I-90 and SR-17 — freer mid-day basin freeflow, still peak-heavy on Moses Lake arterials and harvest windows.'),
      b('Housing stock differences', 'King mixes elevators and Eastside HOAs. Grant mixes Moses Lake multi-story, multi-family growth, and ag-edge SFH — more basin hub product, less continuous Sound multi-family density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; multi-family elevators appear on growth edges; rural lots add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Grant quotes often track basin secondary rates for multi-story access — long empty-mile pairs from the Sound price as distance work.'),
      b('Role difference', 'Grant is independent Columbia Basin hub — not Puget Sound product renamed.'),
    ],
    whatIntro: 'Basin multi-story, ag calendars, and I-90 freeflow — not interchangeable Puget Sound boilerplate.',
    whatBullets: [
      b('Agricultural calendars reshape mid-week demand', 'Harvest windows rewrite pure Saturday residential assumptions.'),
      b('Moses Lake multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('I-90 freeflow is still billable', 'Basin pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Summer heat still governs open carries', 'Early starts outperform noon load-outs June–August.'),
    ],
    zonesHeading: 'Grant zones: Moses Lake multi-story, multi-family growth, Ephrata/Quincy edges & rural basin lots',
    zonesIntro: 'Two to four sharp products — hub multi-story, multi-family growth, edge towns, and rural lots.',
    zones: [
      z('moses-lake', 'Moses Lake multi-story & multi-unit', 'Moses Lake', ['Moses Lake', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-90 freeflow'], ['moses lake'], 'Inventory stairs; plan temporary no-parking.'),
      z('multi-growth', 'Moses Lake multi-family growth', 'Multi-family growth', ['growth multi-family', 'HOA edges'], 'Multi-family, apartments, townhomes', ['Elevators', 'Heat staging', 'Lease clusters'], ['moses lake multi'], 'Collect elevator COIs; prefer early starts in summer.'),
      z('ephrata-quincy', 'Ephrata / Quincy corridor edges', 'Ephrata / Quincy', ['Ephrata', 'Quincy', 'corridor multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['ephrata', 'quincy'], 'Prefer early starts for long pairs.'),
      z('rural-basin', 'Rural basin lots', 'Rural basin', ['rural tracts', 'ag-edge lots'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Heat staging'], ['rural grant'], 'Survey approaches; soft ground after irrigation can block heavy trucks.'),
    ],
    specialized: [
      s('basin-hub', 'Columbia Basin hub module', 'Moses Lake multi-story dominates hub volume.', ['Inventory stairs and curb width.', 'Do not recycle Puget Sound day rates alone.']),
      s('i90-basin', 'I-90 basin freeflow', 'Basin pairs still peak hard; Sound legs are distance work.', ['Price portal-to-portal honestly.', 'Clarify King second addresses for long empty-mile assumptions.']),
      s('ag-heat', 'Ag calendar & heat pacing', 'Harvest and heat are first-class labor inputs.', ['Prefer early starts June–August.', 'Build buffers for harvest traffic.']),
    ],
    schoolsIntro: 'Grant families compare Moses Lake, Ephrata, Quincy, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Samaritan Healthcare and regional specialty spillover serve the county; map peak I-90 times for ER access.',
    costIntro: 'Multi-story access, I-90 freeflow, empty miles, and heat pacing often matter more than raw miles.',
    seasonalIntro: 'Harvest windows, school years, and summer heat reshape demand by pocket.',
  },
  {
    file: 'chelan-wa.ts',
    exportName: 'chelanCountyWaTier2Intelligence',
    slug: 'chelan',
    hubTitle: 'Chelan County Moving Intelligence Hub',
    eyebrow: 'Chelan · Wenatchee — north-central valley',
    h1: 'Moving in Chelan County: Wenatchee, River Valley & US-2 / US-97 Access',
    heroOpener:
      'Chelan County is north-central Washington river-valley product — Wenatchee multi-story and multi-family stock, East Wenatchee-edge approaches (clarify Douglas County lines), Cashmere and Leavenworth tourism edges, and freeflow on US-2 / US-97 that is not Puget Sound product with different labels. Expect agricultural calendars, tourism peaks, and mountain-approach last-mile under one county. This guide is for people moving in Chelan as independent north-central WA — not a Cascade/Puget rename.',
    heroCredibility:
      'North-central river valley · Wenatchee hub · US-2 / US-97 · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-2 · US-97 · SR-285 · SR-150 · Wenatchee Ave corridors',
    parentLabel: 'independent north-central Washington (vs Puget Sound defaults)',
    parentHref: '/local-movers/washington/king',
    compareIntro:
      'Chelan is independent north-central river-valley hub on US-2/97 — not King Puget Sound multi-family density and not pure mountain resort freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'King crews fight I-5/I-405 metro peaks. Chelan pairs ride US-2, US-97, and valley arterials — freer mid-day valley freeflow, still peak-heavy on Wenatchee arterials, harvest windows, and Leavenworth tourism weekends.'),
      b('Housing stock differences', 'King mixes elevators and Eastside HOAs. Chelan mixes Wenatchee multi-story, multi-family growth, and mountain-edge SFH — more river-valley product, less continuous Sound multi-family density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; tourism multi-family needs packets; mountain approaches rewrite truck size.'),
      b('Rough cost posture (qualitative)', 'Local Chelan quotes often track north-central secondary rates for multi-story access — tourism peaks and grades can price above quiet valley driveway jobs.'),
      b('Role difference', 'Chelan is independent north-central river valley — not Puget Sound product renamed.'),
    ],
    whatIntro: 'Wenatchee multi-story, tourism peaks, and US-2 freeflow — not interchangeable Puget Sound boilerplate.',
    whatBullets: [
      b('Agricultural calendars reshape mid-week demand', 'Harvest windows rewrite pure Saturday residential assumptions.'),
      b('Leavenworth tourism peaks rewrite weekends', 'Seasonal volume stacks around major tourism windows.'),
      b('Wenatchee multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('Mountain approaches rewrite truck size', 'Photo last-mile before promising full trailers.'),
    ],
    zonesHeading: 'Chelan zones: Wenatchee multi-story, multi-family growth, Cashmere/Leavenworth edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — hub multi-story, multi-family growth, tourism edges, and rural lots.',
    zones: [
      z('wenatchee', 'Wenatchee multi-story & multi-unit', 'Wenatchee', ['Wenatchee', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'US-2 freeflow'], ['wenatchee'], 'Inventory stairs; plan temporary no-parking.'),
      z('multi-growth', 'Wenatchee multi-family growth edges', 'Multi-family growth', ['growth multi-family', 'HOA edges'], 'Multi-family, apartments, townhomes', ['Elevators', 'Lease clusters'], ['wenatchee multi'], 'Collect elevator COIs; prefer early starts.'),
      z('leavenworth', 'Cashmere / Leavenworth tourism edges', 'Tourism edges', ['Cashmere', 'Leavenworth', 'tourism multi-family'], 'Multi-family, SFH, tourism stock', ['Tourism peaks', 'Narrow approaches', 'Grades'], ['leavenworth', 'cashmere'], 'Book around tourism peaks; photo last-mile.'),
      z('rural-valley', 'Rural river valley lots', 'Rural valley', ['rural tracts', 'orchard edges'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['rural chelan'], 'Survey approaches; soft ground after irrigation can block heavy trucks.'),
    ],
    specialized: [
      s('valley-hub', 'Wenatchee valley hub module', 'Hub multi-story and medical corridors dominate volume.', ['Inventory stairs and curb width.', 'Do not recycle Puget Sound day rates alone.']),
      s('tourism-peaks', 'Leavenworth tourism peak module', 'Seasonal weekends rewrite staging.', ['Book capacity early for peak seasons.', 'Build arterial buffers for festival windows.']),
      s('us2-freeflow', 'US-2 / US-97 freeflow', 'Valley pairs still peak hard; Sound legs are distance work.', ['Price portal-to-portal honestly.', 'Clarify King second addresses for long empty-mile assumptions.']),
    ],
    schoolsIntro: 'Chelan families compare Wenatchee, Cascade, Cashmere, and related district feeders — verify address boundaries; clarify East Wenatchee / Douglas County lines.',
    hospitalsDetail: 'Confluence Health campuses anchor acute care; map peak US-2 / arterial times for ER access.',
    costIntro: 'Multi-story access, tourism peaks, and mountain last-mile often matter more than raw miles.',
    seasonalIntro: 'Harvest windows, tourism peaks, school years, and winter ice reshape demand by pocket.',
  },
  {
    file: 'clallam-wa.ts',
    exportName: 'clallamCountyWaTier2Intelligence',
    slug: 'clallam',
    hubTitle: 'Clallam County Moving Intelligence Hub',
    eyebrow: 'Clallam · Port Angeles / Sequim — Olympic Peninsula',
    h1: 'Moving in Clallam County: Port Angeles, Sequim & Olympic Peninsula Access',
    heroOpener:
      'Clallam County is Olympic Peninsula end-of-road product — Port Angeles multi-story and multi-family stock, Sequim multi-family and growth edges, Forks and western long empty miles, and freeflow on US-101 that is not Kitsap ferry-suburb product with different labels. Expect ferry connections, rain staging, and discontinuous peninsula logistics under one county. This guide is for people moving in Clallam as independent peninsula market — not a Kitsap rename.',
    heroCredibility:
      'Olympic Peninsula independent · Port Angeles / Sequim · End-of-road logistics · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-101 · SR-112 · SR-113 · ferry approaches · Lauridsen Blvd corridors',
    parentLabel: 'independent Olympic Peninsula (vs Kitsap defaults)',
    parentHref: '/local-movers/washington/kitsap',
    compareIntro:
      'Clallam is independent peninsula end-of-road product on US-101 — not Kitsap continuous ferry-suburb multi-family density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Kitsap crews fight ferry/SR-16 peaks into Bremerton. Clallam pairs ride US-101 and peninsula arterials — freer mid-day peninsula freeflow, still peak-heavy on Port Angeles arterials, Sequim growth windows, and ferry connections.'),
      b('Housing stock differences', 'Kitsap mixes Bremerton multi-family and Silverdale HOAs. Clallam mixes Port Angeles multi-story, Sequim multi-family, and western rural lots — more end-of-road product, less continuous peninsula-suburb density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; multi-family elevators appear on Sequim growth; western lots add long empty miles and soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Clallam quotes often track peninsula secondary rates for multi-story access — long empty-mile pairs from the Sound price as distance work.'),
      b('Role difference', 'Clallam is independent Olympic Peninsula end-of-road — not Kitsap product renamed.'),
    ],
    whatIntro: 'Peninsula multi-story, ferry connections, and end-of-road empty miles — not interchangeable Kitsap boilerplate.',
    whatBullets: [
      b('End-of-road empty miles are first-class cost drivers', 'Sound-to-peninsula pairs fail when crews assume continuous multi-family density.'),
      b('Port Angeles multi-story is first-class product', 'Seat stairs need inventories different from pure Sequim cul-de-sacs.'),
      b('Ferry connections rewrite schedules', 'Sailing windows and truck limits are first-class survey inputs for some pairs.'),
      b('Rain staging rewrites open-carry plans', 'Protect cardboard and plan covered unload windows.'),
    ],
    zonesHeading: 'Clallam zones: Port Angeles multi-story, Sequim multi-family, Forks edges & western rural lots',
    zonesIntro: 'Two to four sharp products — hub multi-story, multi-family growth, western edges, and rural lots.',
    zones: [
      z('port-angeles', 'Port Angeles multi-story & multi-unit', 'Port Angeles', ['Port Angeles', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'US-101 freeflow'], ['port angeles'], 'Inventory stairs; plan temporary no-parking.'),
      z('sequim', 'Sequim multi-family & growth edges', 'Sequim', ['Sequim', 'growth multi-family', 'HOA edges'], 'Multi-family, HOA SFH, townhomes', ['Elevators', 'HOA packets', 'Lease clusters'], ['sequim'], 'Collect HOA COIs; prefer early starts.'),
      z('forks', 'Forks / western corridor edges', 'Forks', ['Forks', 'western multi-family'], 'SFH, multi-family, mixed stock', ['Long empty miles', 'Rain staging'], ['forks'], 'Prefer early starts for long pairs; survey approaches.'),
      z('rural-west', 'Western rural peninsula lots', 'Rural west', ['rural tracts', 'western approaches'], 'Larger lots, rural approaches', ['Long empty miles', 'Soft shoulders', 'Rain staging'], ['west clallam'], 'Survey approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('peninsula-end', 'Olympic Peninsula end-of-road module', 'Long empty miles dominate Sound-to-peninsula pricing.', ['Price portal-to-portal from mainland staging honestly.', 'Do not recycle Kitsap ferry-suburb day rates alone.']),
      s('pa-seat', 'Port Angeles multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('ferry-rain', 'Ferry connection & rain staging', 'Sailing windows and weather are first-class logistics inputs.', ['Confirm ferry truck size limits when applicable.', 'Protect cardboard and plan covered unload windows.']),
    ],
    schoolsIntro: 'Clallam families compare Port Angeles, Sequim, Quillayute Valley, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Olympic Medical Center and regional specialty spillover serve the county; map peak US-101 times for ER access.',
    costIntro: 'Multi-story access, end-of-road empty miles, and rain staging often matter more than raw miles.',
    seasonalIntro: 'School years, tourism shoulders, ferry peak seasons, and rain reshape demand by pocket.',
  },
  {
    file: 'walla-walla-wa.ts',
    exportName: 'wallaWallaCountyWaTier2Intelligence',
    slug: 'walla-walla',
    hubTitle: 'Walla Walla County Moving Intelligence Hub',
    eyebrow: 'Walla Walla · southeast valley',
    h1: 'Moving in Walla Walla County: Walla Walla Valley, College Edges & US-12 Access',
    heroOpener:
      'Walla Walla County is southeast Washington independent valley product — Walla Walla multi-story and multi-family stock, college-adjacent density, College Place and rural valley edges, and freeflow on US-12 that is not Tri-Cities continuous multi-family with different labels. Expect college calendars, tourism shoulders, and longer empty miles under one county. This guide is for people moving in Walla Walla as independent SE valley — not a Tri-Cities rename.',
    heroCredibility:
      'SE valley independent · College + residential · US-12 freeflow · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-12 · SR-125 · SR-124 · Isaacs Ave corridors',
    parentLabel: 'independent SE Washington (vs Tri-Cities defaults)',
    parentHref: '/local-movers/washington/benton',
    compareIntro:
      'Walla Walla is independent SE valley college/residential product — not Benton Tri-Cities employment multi-family density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Benton crews fight Kennewick/Richland arterials and bridge peaks. Walla Walla pairs ride US-12 and valley arterials — freer mid-day SE freeflow, still peak-heavy on Walla Walla arterials and college term windows.'),
      b('Housing stock differences', 'Benton mixes employment multi-family and West Richland HOAs. Walla Walla mixes city multi-story, college multi-family, and valley SFH — more college-town product, less continuous Tri-Cities employment density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; college multi-family needs COIs; rural lots add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Walla Walla quotes often track SE secondary rates for multi-story access — term peaks and empty miles still push prices up.'),
      b('Role difference', 'Walla Walla is independent SE valley hub — not Tri-Cities product renamed.'),
    ],
    whatIntro: 'College multi-family, valley multi-story, and US-12 freeflow — not interchangeable Tri-Cities boilerplate.',
    whatBullets: [
      b('College term calendars drive demand spikes', 'Move-in/out weekends fill crews near campus. Book early.'),
      b('Walla Walla multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('US-12 freeflow is still billable', 'SE pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Distinct from Tri-Cities employment multi-family defaults', 'Do not recycle Kennewick day rates alone.'),
    ],
    zonesHeading: 'Walla Walla zones: city multi-story, college multi-family, College Place edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — hub multi-story, college multi-family, edge multi-family, and rural lots.',
    zones: [
      z('ww-city', 'Walla Walla multi-story & multi-unit', 'Walla Walla city', ['Walla Walla', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'US-12 freeflow'], ['walla walla'], 'Inventory stairs; plan temporary no-parking.'),
      z('college', 'College multi-family corridors', 'College multi', ['college multi-family', 'campus edges'], 'Multi-family, apartments, some SFH', ['Term parking', 'COI packets', 'Elevators'], ['walla walla college'], 'Book around term calendars; collect building rules.'),
      z('college-place', 'College Place / edge multi-family', 'College Place', ['College Place', 'edge multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['college place'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-valley', 'Rural SE valley lots', 'Rural valley', ['rural tracts', 'ag-edge lots'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders'], ['rural walla walla'], 'Survey approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('se-valley', 'SE valley hub multi-story module', 'City multi-story and college multi-family dominate volume.', ['Inventory stairs and elevators.', 'Do not recycle Tri-Cities day rates alone.']),
      s('college-terms', 'College move-cycle module', 'Term calendars drive demand spikes.', ['Book early around move-in/out weekends.', 'Price campus-edge curb time honestly.']),
      s('us12-freeflow', 'US-12 SE freeflow', 'SE pairs still peak hard; Tri-Cities legs need clear county lines.', ['Price portal-to-portal honestly.', 'Clarify Benton second addresses early.']),
    ],
    schoolsIntro: 'Walla Walla families compare Walla Walla, College Place, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Providence St. Mary and regional specialty spillover serve the county; map peak US-12 times for ER access.',
    costIntro: 'Multi-story access, term peaks, and empty miles often matter more than raw miles.',
    seasonalIntro: 'College calendars, tourism shoulders, school years, and harvest windows reshape demand by pocket.',
  },
  {
    file: 'kittitas-wa.ts',
    exportName: 'kittitasCountyWaTier2Intelligence',
    slug: 'kittitas',
    hubTitle: 'Kittitas County Moving Intelligence Hub',
    eyebrow: 'Kittitas · Ellensburg — I-90 central Cascades east',
    h1: 'Moving in Kittitas County: Ellensburg, CWU Cycles & I-90 East Access',
    heroOpener:
      'Kittitas County is central Cascades-east independent product — Ellensburg multi-story and CWU-adjacent multi-family, Cle Elum and mountain-edge approaches, rural valley lots, and freeflow on I-90 that is not King Puget Sound multi-family with different labels. Expect university calendars, pass weather, and longer empty miles under one county. This guide is for people moving in Kittitas as independent I-90 university market — not a Seattle-collar rename.',
    heroCredibility:
      'I-90 university market · Ellensburg / CWU · Pass weather · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-90 · US-97 · SR-10 · SR-903 · University Way corridors',
    parentLabel: 'independent I-90 university (nearest hub contrast: King)',
    parentHref: '/local-movers/washington/king',
    compareIntro:
      'Kittitas is independent I-90 Ellensburg university product — not King Puget Sound multi-family density and not pure mountain freeflow alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'King crews fight I-5/I-405 metro peaks. Kittitas pairs ride I-90 and valley arterials — freer mid-day east of the Cascades, still peak-heavy on Ellensburg arterials, CWU term windows, and pass closures.'),
      b('Housing stock differences', 'King mixes elevators and Eastside HOAs. Kittitas mixes Ellensburg multi-story, CWU multi-family, and Cle Elum mountain-edge SFH — more university-town product, less continuous Sound multi-family density.'),
      b('Truck access & density', 'Campus multi-family needs COIs; seat multi-story needs curb plans; mountain approaches rewrite truck size and winter staging.'),
      b('Rough cost posture (qualitative)', 'Local Kittitas quotes often track I-90 secondary rates for multi-story access — term peaks and pass weather can price above quiet rural lots.'),
      b('Role difference', 'Kittitas is independent I-90 university market — not Puget Sound product renamed.'),
    ],
    whatIntro: 'CWU term calendars, Ellensburg multi-story, and I-90 pass freeflow — not interchangeable Seattle boilerplate.',
    whatBullets: [
      b('CWU term calendars drive demand spikes', 'Move-in/out weekends fill crews near campus. Book early.'),
      b('Ellensburg multi-story is first-class product', 'Seat stairs need inventories different from pure rural lots.'),
      b('I-90 pass freeflow is still billable', 'Pass conditions and peaks rewrite short-looking pairs. Ask portal-to-portal.'),
      b('Long empty miles from Puget Sound yards are real', 'Even “in-state” pairs can price as distance work for King-based crews.'),
    ],
    zonesHeading: 'Kittitas zones: Ellensburg multi-story, CWU multi-family, Cle Elum edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — hub multi-story, campus multi-family, mountain edges, and rural lots.',
    zones: [
      z('ellensburg', 'Ellensburg multi-story & multi-unit', 'Ellensburg', ['Ellensburg', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-90 freeflow'], ['ellensburg'], 'Inventory stairs; plan temporary no-parking.'),
      z('cwu', 'CWU campus-edge multi-family', 'CWU edge', ['campus multi-family', 'student stock'], 'Multi-family, apartments, some SFH', ['Term parking', 'COI packets', 'Elevators'], ['cwu', 'central washington'], 'Book around term calendars; collect building rules.'),
      z('cle-elum', 'Cle Elum / mountain-edge approaches', 'Cle Elum', ['Cle Elum', 'Roslyn edges', 'mountain SFH'], 'SFH, multi-family, mixed stock', ['Grades', 'Empty miles', 'Winter ice'], ['cle elum', 'roslyn'], 'Photo last-mile; winter mornings need flexibility.'),
      z('rural-valley', 'Rural Kittitas valley lots', 'Rural valley', ['rural tracts', 'valley approaches'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Winter ice'], ['rural kittitas'], 'Survey approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('cwu-cycles', 'CWU university move-cycle module', 'Term calendars drive demand spikes.', ['Book early around move-in/out weekends.', 'Price campus-edge curb time honestly.']),
      s('i90-pass', 'I-90 pass freeflow', 'Pass conditions rewrite freeflow assumptions.', ['Price portal-to-portal honestly.', 'Monitor closures and chain laws in season.']),
      s('vs-sound', 'Kittitas vs Puget Sound distinction', 'I-90 university product differs from Sound multi-family density.', ['Do not recycle Seattle day rates alone.', 'Clarify King second addresses for long empty-mile assumptions.']),
    ],
    schoolsIntro: 'Kittitas families compare Ellensburg, Cle Elum-Roslyn, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'Kittitas Valley Healthcare and regional specialty spillover serve the county; map peak I-90 times for ER access.',
    costIntro: 'Term peaks, multi-story access, and pass freeflow often matter more than raw miles.',
    seasonalIntro: 'University calendars, school years, and winter pass weather reshape demand by pocket.',
  },
];
