import { type PackDef, z, s, b } from './wa-tier2-render';

/** WA Tier 2 Wave 1 packs 1–6 */
export const packsA: PackDef[] = [
  {
    file: 'skagit-wa.ts',
    exportName: 'skagitCountyWaTier2Intelligence',
    slug: 'skagit',
    hubTitle: 'Skagit County Moving Intelligence Hub',
    eyebrow: 'Skagit · Mount Vernon / Burlington / Anacortes — north I-5 corridor',
    h1: 'Moving in Skagit County: Mount Vernon, Burlington & North I-5 Corridor Access',
    heroOpener:
      'Skagit County is north I-5 mid-corridor product — Mount Vernon multi-story and seat stock, Burlington multi-family and retail-corridor growth, Anacortes and island-edge approaches, and freeflow that is not Bellingham WWU density or Everett industrial multi-family with different labels. Expect agricultural calendars, rain staging, and longer empty miles under one county. This guide is for people moving in Skagit as north I-5 mid-corridor — not a Whatcom or Snohomish rename.',
    heroCredibility:
      'North I-5 mid-corridor · Ag + multi-family mix · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-5 · SR-20 · SR-536 · SR-9 · Anacortes approaches',
    parentLabel: 'Whatcom County',
    parentHref: '/local-movers/washington/whatcom',
    parentAltLabel: 'Snohomish County',
    parentAltHref: '/local-movers/washington/snohomish',
    compareIntro:
      'Skagit is north I-5 agricultural and mid-corridor multi-family product — not Whatcom Bellingham university density and not Snohomish Everett industrial multi-family alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Whatcom crews fight Bellingham arterials and border freeflow. Skagit pairs ride I-5, SR-20, and local arterials — freer mid-day between metros, still peak-heavy on Mount Vernon arterials and Burlington retail weekends.'),
      b('Housing stock differences', 'Whatcom mixes Bellingham multi-story and WWU multi-family. Skagit mixes Mount Vernon multi-unit, Burlington multi-family, and Anacortes stock — more ag-corridor product, less continuous university density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; multi-family elevators appear on Burlington growth; Anacortes approaches add ferry-adjacent timing.'),
      b('Rough cost posture (qualitative)', 'Local Skagit quotes often track north I-5 secondary rates for driveway SFH — multi-story access and empty miles still push prices up.'),
      b('Role difference', 'Skagit is north I-5 mid-corridor — not Bellingham or Everett product renamed.'),
    ],
    whatIntro: 'Ag calendars, Mount Vernon multi-story, and I-5 freeflow — not interchangeable Bellingham or Everett boilerplate.',
    whatBullets: [
      b('I-5 freeflow is still billable', 'Skagit ↔ Whatcom/Snohomish pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Mount Vernon multi-story is first-class product', 'Seat stairs need inventories different from pure Burlington cul-de-sacs.'),
      b('Agricultural calendars reshape mid-week demand', 'Harvest windows rewrite pure Saturday residential assumptions.'),
      b('Anacortes approaches add ferry-adjacent timing risk', 'Clarify island second addresses and sailing windows early.'),
    ],
    zonesHeading: 'Skagit zones: Mount Vernon multi-story, Burlington multi-family, Anacortes edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, multi-family growth, island-edge stock, and rural lots.',
    zones: [
      z('mount-vernon', 'Mount Vernon multi-story & seat stock', 'Mount Vernon', ['Mount Vernon', 'downtown edges', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-5 freeflow'], ['mount vernon'], 'Inventory stairs; plan temporary no-parking.'),
      z('burlington', 'Burlington multi-family & retail corridors', 'Burlington', ['Burlington', 'retail multi-family', 'growth villages'], 'Multi-family, HOA SFH, townhomes', ['Elevators', 'HOA packets', 'Retail peaks'], ['burlington wa'], 'Collect HOA COIs; build I-5 commute buffers.'),
      z('anacortes', 'Anacortes / island-edge approaches', 'Anacortes', ['Anacortes', 'ferry approaches', 'island multi-family'], 'Multi-family, SFH, mixed stock', ['Ferry timing', 'Arterial freeflow'], ['anacortes'], 'Clarify ferry windows; photo last-mile.'),
      z('rural-valley', 'Rural Skagit valley lots', 'Rural valley', ['rural tracts', 'ag-edge lots'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Rain staging'], ['rural skagit'], 'Survey approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('i5-mid', 'I-5 north mid-corridor freeflow', 'North pairs still peak hard toward Whatcom or Snohomish.', ['Price portal-to-portal honestly.', 'Clarify Bellingham or Everett second addresses early.']),
      s('ag-calendars', 'Agricultural calendar module', 'Harvest windows reshape mid-week demand.', ['Clarify hard dates early.', 'Do not quote pure Bellingham Saturday rates for ag-edge jobs.']),
      s('mv-seat', 'Mount Vernon multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
    ],
    schoolsIntro: 'Skagit families compare Mount Vernon, Burlington-Edison, Anacortes, Sedro-Woolley, and related district feeders — verify address boundaries; do not assume Whatcom or Snohomish maps apply.',
    hospitalsDetail: 'Skagit Regional Health and regional specialty spillover serve the county; map peak I-5 times for ER access.',
    costIntro: 'I-5 freeflow, multi-story access, and empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, harvest windows, rain staging, and tourism shoulders reshape demand by pocket.',
  },
  {
    file: 'yakima-wa.ts',
    exportName: 'yakimaCountyWaTier2Intelligence',
    slug: 'yakima',
    hubTitle: 'Yakima County Moving Intelligence Hub',
    eyebrow: 'Yakima · central Washington hub',
    h1: 'Moving in Yakima County: Yakima Valley, Medical Hub & I-82 Access',
    heroOpener:
      'Yakima County is central Washington independent hub product — Yakima multi-story and multi-family stock, West Valley HOA growth, Selah and Union Gap edges, and freeflow on I-82 that is not Puget Sound rain logistics with different labels. Expect agricultural calendars, regional medical corridors, summer heat pacing, and longer empty miles under one county. This guide is for people moving in Yakima as central WA hub — not a Seattle-collar rename.',
    heroCredibility:
      'Central WA independent · Ag + medical hub · I-82 freeflow · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-82 · US-12 · SR-24 · SR-821 · Yakima Ave corridors',
    parentLabel: 'independent central Washington (vs Puget Sound defaults)',
    parentHref: '/local-movers/washington/king',
    compareIntro:
      'Yakima is independent central WA agricultural and medical hub on I-82 — not King Puget Sound multi-family density and not pure rural basin freeflow.',
    compareBullets: [
      b('Drive time & corridor relationship', 'King crews fight I-5/I-405 metro peaks. Yakima pairs ride I-82 and valley arterials — freer mid-day central freeflow, still peak-heavy on Yakima arterials and harvest windows.'),
      b('Housing stock differences', 'King mixes elevators and Eastside HOAs. Yakima mixes city multi-story, West Valley multi-family, and ag-edge SFH — more valley hub product, less continuous Sound multi-family density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; multi-family elevators appear on West Valley growth; rural edges add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Yakima quotes often track central WA secondary rates for multi-story access — long empty-mile pairs from the Sound price as distance work.'),
      b('Role difference', 'Yakima is independent central WA hub — not Puget Sound product renamed.'),
    ],
    whatIntro: 'Valley multi-story, ag calendars, and I-82 freeflow — not interchangeable Puget Sound boilerplate.',
    whatBullets: [
      b('Agricultural calendars reshape mid-week demand', 'Harvest windows rewrite pure Saturday residential assumptions.'),
      b('Yakima multi-story is first-class product', 'Seat stairs need inventories different from pure West Valley cul-de-sacs.'),
      b('I-82 freeflow is still billable', 'Valley pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Summer heat still governs open carries', 'Early starts outperform noon load-outs June–August.'),
    ],
    zonesHeading: 'Yakima zones: city multi-story, West Valley multi-family, Selah edges & rural valley lots',
    zonesIntro: 'Two to four sharp products — hub multi-story, multi-family growth, edge towns, and rural lots.',
    zones: [
      z('yakima-city', 'Yakima multi-story & multi-unit', 'Yakima city', ['Yakima', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-82 freeflow'], ['yakima'], 'Inventory stairs; plan temporary no-parking.'),
      z('west-valley', 'West Valley multi-family & HOA growth', 'West Valley', ['West Valley', 'growth villages', 'HOA SFH'], 'HOA SFH, multi-family, townhomes', ['HOA packets', 'Elevators', 'Heat staging'], ['west valley yakima'], 'Collect HOA COIs; prefer early starts in summer.'),
      z('selah', 'Selah / Union Gap corridor edges', 'Selah / Union Gap', ['Selah', 'Union Gap', 'corridor multi-family'], 'SFH, multi-family, mixed stock', ['Empty miles', 'Arterial timing'], ['selah', 'union gap'], 'Prefer early starts; confirm driveway depth.'),
      z('rural-valley', 'Rural Yakima valley lots', 'Rural valley', ['rural tracts', 'ag-edge lots'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Heat staging'], ['rural yakima'], 'Survey approaches; soft ground after irrigation can block heavy trucks.'),
    ],
    specialized: [
      s('central-hub', 'Central WA hub multi-story module', 'City multi-story and medical corridors dominate volume.', ['Inventory stairs and curb width.', 'Do not recycle Puget Sound day rates alone.']),
      s('ag-calendars', 'Agricultural calendar module', 'Harvest windows reshape mid-week demand.', ['Clarify hard dates early.', 'Build buffers for ag traffic on valley arterials.']),
      s('i82-freeflow', 'I-82 valley freeflow', 'Central pairs still peak hard; Sound legs are distance work.', ['Price portal-to-portal honestly.', 'Clarify King second addresses for long empty-mile assumptions.']),
    ],
    schoolsIntro: 'Yakima families compare Yakima, West Valley, Selah, and related district feeders — verify address boundaries.',
    hospitalsDetail: 'MultiCare Yakima Memorial and regional specialty care anchor acute care; map peak I-82 / arterial times for ER access.',
    costIntro: 'Multi-story access, I-82 freeflow, ag empty miles, and heat pacing often matter more than raw miles.',
    seasonalIntro: 'Harvest windows, school years, and summer heat reshape demand by pocket.',
  },
  {
    file: 'benton-wa.ts',
    exportName: 'bentonCountyWaTier2Intelligence',
    slug: 'benton',
    hubTitle: 'Benton County Moving Intelligence Hub',
    eyebrow: 'Benton · Kennewick / Richland — Tri-Cities west/south',
    h1: 'Moving in Benton County: Kennewick, Richland & Tri-Cities I-82 Access',
    heroOpener:
      'Benton County is the Kennewick–Richland side of the Tri-Cities — multi-family and employment-corridor density, West Richland growth, river-bridge freeflow toward Pasco, and freeflow on I-82 / US-395 that is not Puget Sound product with different labels. Expect lab/energy calendars, summer heat pacing, and discontinuous bridge pairs under one county. This guide is for people moving in Benton as Tri-Cities employment hub — not a Franklin/Pasco rename and not a Yakima clone.',
    heroCredibility:
      'Tri-Cities employment hub · Kennewick / Richland · I-82 / Columbia · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-82 · US-395 · SR-240 · SR-224 · Columbia River bridges',
    parentLabel: 'independent southeast Washington (nearest hub contrast: Yakima)',
    parentHref: '/local-movers/washington/yakima',
    parentAltLabel: 'Franklin County',
    parentAltHref: '/local-movers/washington/franklin',
    compareIntro:
      'Benton is Tri-Cities Kennewick/Richland employment product — not Yakima valley ag hub alone and not Franklin Pasco east-bank product renamed.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Yakima crews fight valley arterials and I-82 peaks. Benton pairs ride I-82, US-395, and river bridges — freer mid-day Tri-Cities freeflow, still peak-heavy on Kennewick arterials and bridge windows into Pasco.'),
      b('Housing stock differences', 'Yakima mixes city multi-story and West Valley HOAs. Benton mixes Kennewick multi-family, Richland multi-unit, and West Richland growth — more continuous employment multi-family, less continuous ag-edge fabric.'),
      b('Truck access & density', 'Multi-family elevators dominate employment corridors; bridge freeflow is first-class; clarify Franklin second addresses.'),
      b('Rough cost posture (qualitative)', 'Local Benton quotes often track Tri-Cities secondary-premium rates for multi-family access — heat and bridge peaks can price above quiet rural lots.'),
      b('Role difference', 'Benton is Tri-Cities west/south employment hub — not Pasco east-bank or Yakima product renamed.'),
    ],
    whatIntro: 'Employment multi-family, bridge freeflow, and lab calendars — not interchangeable Pasco or Yakima boilerplate.',
    whatBullets: [
      b('Lab / energy calendars reshape mid-week demand', 'Hard report dates compete with Saturday family windows.'),
      b('River-bridge freeflow to Franklin is still billable', 'Benton ↔ Pasco pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Kennewick multi-family is first-class product', 'Elevators and parking need inventories different from pure SFH lots.'),
      b('Summer heat still governs open carries', 'Early starts outperform noon load-outs June–August.'),
    ],
    zonesHeading: 'Benton zones: Kennewick multi-family, Richland multi-unit, West Richland growth & river edges',
    zonesIntro: 'Two to four sharp products — multi-family cores, employment multi-unit, growth HOAs, and river edges.',
    zones: [
      z('kennewick', 'Kennewick multi-family & employment corridors', 'Kennewick', ['Kennewick', 'employment multi-family', 'west-side growth'], 'Multi-family, apartments, townhomes, SFH', ['Elevators', 'Heat staging', 'Bridge freeflow'], ['kennewick'], 'Confirm elevator rules; prefer early starts in summer.'),
      z('richland', 'Richland multi-unit & employment stock', 'Richland', ['Richland', 'employment multi-family'], 'Multi-family, SFH, townhomes', ['COI packets', 'Lease clusters', 'SR-240 freeflow'], ['richland'], 'Collect building packets; build commute buffers.'),
      z('west-richland', 'West Richland HOA growth', 'West Richland', ['West Richland', 'growth villages'], 'HOA SFH, townhomes, multi-family', ['HOA packets', 'Empty miles'], ['west richland'], 'Collect HOA COIs; prefer early starts.'),
      z('river-edge', 'Columbia river-edge approaches', 'River edge', ['river multi-family', 'bridge approaches'], 'Multi-family, SFH, mixed stock', ['Bridge freeflow', 'Wind staging'], ['columbia river benton'], 'Build bridge-peak buffers; clarify Franklin second addresses.'),
    ],
    specialized: [
      s('tri-cities-west', 'Tri-Cities west/south employment module', 'Kennewick/Richland multi-family dominates volume.', ['Collect elevator COIs early.', 'Do not recycle Pasco east-bank day rates alone.']),
      s('bridge-freeflow', 'Columbia bridge freeflow to Franklin', 'Cross-river pairs still peak hard.', ['Price portal-to-portal honestly.', 'Clarify Pasco second addresses early.']),
      s('lab-calendars', 'Lab / energy calendar module', 'Hard report dates reshape mid-week demand.', ['Align surveys with report dates when possible.', 'Build buffers for employment-corridor peaks.']),
    ],
    schoolsIntro: 'Benton families compare Kennewick, Richland, and related district feeders — verify address boundaries; do not assume Franklin maps apply.',
    hospitalsDetail: 'Kadlec Regional and Trios Health campuses anchor acute care; map peak bridge and I-82 times for ER access.',
    costIntro: 'Multi-family access, bridge freeflow, and heat pacing often matter more than raw miles.',
    seasonalIntro: 'Lab calendars, school years, and summer heat reshape demand by pocket.',
  },
  {
    file: 'franklin-wa.ts',
    exportName: 'franklinCountyWaTier2Intelligence',
    slug: 'franklin',
    hubTitle: 'Franklin County Moving Intelligence Hub',
    eyebrow: 'Franklin · Pasco — Tri-Cities east bank',
    h1: 'Moving in Franklin County: Pasco, East-Bank Multi-Family & Bridge Access',
    heroOpener:
      'Franklin County is the Pasco east-bank side of the Tri-Cities — multi-family and multi-story stock, growth edges, ag-adjacent residential, and freeflow that still peaks hard on river bridges into Benton. Expect distinct east-bank access, heat pacing, and discontinuous pairs under one county. This guide is for people moving in Franklin as Tri-Cities east bank — not a Kennewick/Richland rename.',
    heroCredibility:
      'Tri-Cities east bank · Pasco multi-family · Bridge freeflow · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'US-395 · SR-397 · I-182 · Columbia River bridges · Court Street corridors',
    parentLabel: 'Benton County',
    parentHref: '/local-movers/washington/benton',
    compareIntro:
      'Franklin is Tri-Cities Pasco east-bank product — not Benton Kennewick/Richland employment multi-family renamed.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Benton crews fight Kennewick/Richland arterials and SR-240 peaks. Franklin pairs ride US-395, I-182, and river bridges — freer mid-day east-bank freeflow, still peak-heavy on Pasco arterials and bridge windows into Benton.'),
      b('Housing stock differences', 'Benton mixes Kennewick multi-family and Richland multi-unit. Franklin mixes Pasco multi-story, east-bank multi-family, and ag-edge SFH — more continuous east-bank product, less continuous Richland employment density.'),
      b('Truck access & density', 'Multi-family elevators and seat multi-story dominate; bridge freeflow is first-class; ag edges add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Franklin quotes often track Tri-Cities secondary rates for multi-family access — bridge peaks and multi-story access still push prices up.'),
      b('Role difference', 'Franklin is Tri-Cities east bank — not Benton west/south product renamed.'),
    ],
    whatIntro: 'East-bank multi-story, bridge freeflow, and ag edges — not interchangeable Kennewick/Richland boilerplate.',
    whatBullets: [
      b('River-bridge freeflow to Benton is still billable', 'Pasco ↔ Kennewick pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Pasco multi-story is first-class product', 'Seat stairs need inventories different from pure growth cul-de-sacs.'),
      b('Distinct from Benton employment multi-family defaults', 'Do not recycle Richland day rates alone.'),
      b('Summer heat still governs open carries', 'Early starts outperform noon load-outs June–August.'),
    ],
    zonesHeading: 'Franklin zones: Pasco multi-story, multi-family growth, bridge edges & ag-edge lots',
    zonesIntro: 'Two to four sharp products — seat multi-story, multi-family growth, bridge approaches, and ag edges.',
    zones: [
      z('pasco-core', 'Pasco multi-story & multi-unit', 'Pasco core', ['Pasco', 'downtown edges', 'city multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Bridge freeflow'], ['pasco'], 'Inventory stairs; plan temporary no-parking.'),
      z('multi-growth', 'Pasco multi-family growth edges', 'Multi-family growth', ['growth multi-family', 'east-bank apartments'], 'Multi-family, apartments, townhomes', ['Elevators', 'Lease clusters', 'Heat staging'], ['pasco multi'], 'Collect elevator COIs; prefer early starts in summer.'),
      z('bridge-edge', 'Bridge approaches toward Benton', 'Bridge edge', ['bridge multi-family', 'I-182 edges'], 'Multi-family, SFH, mixed stock', ['Bridge freeflow', 'Wind staging'], ['pasco bridge'], 'Build bridge-peak buffers; clarify Benton second addresses.'),
      z('ag-edge', 'Ag-edge residential lots', 'Ag edge', ['ag-adjacent SFH', 'rural tracts'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Heat staging'], ['east franklin'], 'Survey approaches; soft ground after irrigation can block heavy trucks.'),
    ],
    specialized: [
      s('east-bank', 'Pasco east-bank multi-story module', 'East-bank multi-story and multi-family dominate volume.', ['Inventory stairs and elevators.', 'Do not recycle Kennewick/Richland day rates alone.']),
      s('bridge-freeflow', 'Columbia bridge freeflow to Benton', 'Cross-river pairs still peak hard.', ['Price portal-to-portal honestly.', 'Clarify Kennewick or Richland second addresses early.']),
      s('heat-pacing', 'Basin heat pacing module', 'Summer open carries are first-class labor-hours drivers.', ['Prefer early starts June–August.', 'Pace crews and protect inventories.']),
    ],
    schoolsIntro: 'Franklin families compare Pasco School District and related feeders — verify address boundaries; do not assume Benton maps apply.',
    hospitalsDetail: 'Lourdes Health and Benton specialty spillover serve the county; map peak bridge times for ER access.',
    costIntro: 'Multi-story access, bridge freeflow, and heat pacing often matter more than raw miles.',
    seasonalIntro: 'School years, ag calendars, and summer heat reshape demand by pocket.',
  },
  {
    file: 'cowlitz-wa.ts',
    exportName: 'cowlitzCountyWaTier2Intelligence',
    slug: 'cowlitz',
    hubTitle: 'Cowlitz County Moving Intelligence Hub',
    eyebrow: 'Cowlitz · Longview / Kelso — I-5 south industrial river towns',
    h1: 'Moving in Cowlitz County: Longview, Kelso & I-5 Industrial River Access',
    heroOpener:
      'Cowlitz County is I-5 southwest industrial river-town product — Longview multi-story and industrial-residential mix, Kelso multi-family and seat stock, Woodland edges, and freeflow that is not Clark County Vancouver multi-family with different labels. Expect mill/industrial calendars, rain staging, and longer empty miles under one county. This guide is for people moving in Cowlitz as industrial I-5 corridor — not a Vancouver WA rename.',
    heroCredibility:
      'I-5 industrial river towns · Longview / Kelso · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'I-5 · SR-4 · SR-411 · SR-432 · Ocean Beach Hwy corridors',
    parentLabel: 'Clark County',
    parentHref: '/local-movers/washington/clark',
    compareIntro:
      'Cowlitz is I-5 industrial river-town product — not Clark continuous Vancouver multi-family and Portland-bridge density alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Clark crews fight I-5/I-205 peaks into Vancouver and Portland bridges. Cowlitz pairs ride I-5 and SR-4 — freer mid-day further north, still peak-heavy on Longview arterials and industrial shift windows.'),
      b('Housing stock differences', 'Clark mixes Vancouver multi-family and Camas HOAs. Cowlitz mixes Longview multi-story, industrial-edge SFH, and Kelso multi-unit — more mill-town product, less continuous Portland-adjacent density.'),
      b('Truck access & density', 'Seat multi-story needs curb plans; industrial streets rewrite truck type; soft shoulders appear on rural edges.'),
      b('Rough cost posture (qualitative)', 'Local Cowlitz quotes often sit at southwest secondary rates for driveway SFH — multi-story access and empty miles still push prices up.'),
      b('Role difference', 'Cowlitz is industrial I-5 river-town corridor — not Vancouver WA product renamed.'),
    ],
    whatIntro: 'Industrial calendars, Longview multi-story, and I-5 freeflow — not interchangeable Vancouver boilerplate.',
    whatBullets: [
      b('I-5 freeflow is still billable', 'Cowlitz ↔ Clark pairs freer mid-day still peak hard. Ask portal-to-portal.'),
      b('Longview multi-story is first-class product', 'Seat stairs need inventories different from pure Woodland cul-de-sacs.'),
      b('Industrial calendars reshape mid-week demand', 'Shift patterns rewrite pure Saturday residential assumptions.'),
      b('Oregon adjacency creates interstate legs on some pairs', 'OR addresses require FMCSA authority even on short-looking hops.'),
    ],
    zonesHeading: 'Cowlitz zones: Longview multi-story, Kelso multi-unit, Woodland edges & rural lots',
    zonesIntro: 'Two to four sharp products — industrial multi-story, multi-unit seat, corridor edges, and rural lots.',
    zones: [
      z('longview', 'Longview multi-story & industrial-residential', 'Longview', ['Longview', 'downtown edges', 'mill-adjacent stock'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'I-5 freeflow'], ['longview'], 'Inventory stairs; plan temporary no-parking.'),
      z('kelso', 'Kelso multi-unit & seat stock', 'Kelso', ['Kelso', 'seat multi-family'], 'Multi-unit, multi-story, older SFH', ['Stairs', 'Street parking', 'Mixed curb'], ['kelso'], 'Inventory access type; prefer mid-week mornings.'),
      z('woodland', 'Woodland / I-5 corridor edges', 'Woodland', ['Woodland', 'I-5 multi-family'], 'SFH, multi-family, mixed stock', ['I-5 freeflow', 'Empty miles'], ['woodland wa'], 'Prefer early starts; clarify Clark second addresses.'),
      z('rural-lots', 'Eastern rural lots', 'Rural lots', ['rural tracts', 'eastern approaches'], 'Larger lots, rural approaches', ['Empty miles', 'Soft shoulders', 'Rain staging'], ['east cowlitz'], 'Survey approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('industrial-i5', 'I-5 industrial river-town freeflow', 'Southwest pairs still peak hard toward Clark.', ['Price portal-to-portal honestly.', 'Clarify Vancouver second addresses early.']),
      s('longview-seat', 'Longview multi-story access', 'Seat stairs are a first-class cost driver.', ['Inventory floor counts before comparing hourly rates.', 'Temporary no-parking often beats long carries.']),
      s('mill-calendars', 'Mill / industrial calendar module', 'Shift windows reshape mid-week demand.', ['Clarify hard report dates early.', 'Do not quote pure Camas HOA Saturday rates for industrial-edge jobs.']),
    ],
    schoolsIntro: 'Cowlitz families compare Longview, Kelso, Woodland, and related district feeders — verify address boundaries; do not assume Clark maps apply.',
    hospitalsDetail: 'PeaceHealth St. John and regional specialty spillover serve the county; map peak I-5 times for ER access.',
    costIntro: 'Multi-story access, I-5 freeflow, and industrial empty miles often matter more than raw miles.',
    seasonalIntro: 'School years, industrial calendars, and rain staging reshape demand by pocket.',
  },
  {
    file: 'island-wa.ts',
    exportName: 'islandCountyWaTier2Intelligence',
    slug: 'island',
    hubTitle: 'Island County Moving Intelligence Hub',
    eyebrow: 'Island · Oak Harbor / Coupeville / Camano — island logistics',
    h1: 'Moving in Island County: Oak Harbor, Camano & Ferry/Bridge Access',
    heroOpener:
      'Island County is ferry- and bridge-constrained island product — Oak Harbor multi-family and NAS Whidbey–adjacent stock, Coupeville multi-story edges, Camano Island approaches, and freeflow that is not mainland Snohomish multi-family with different labels. Expect sailing windows, military calendars, rain staging, and last-mile constraints under one county. This guide is for people moving in Island as island logistics market — not a Snohomish rename.',
    heroCredibility:
      'Island ferry/bridge logistics · NAS Whidbey edge · WA UTC HHG · FMCSA when interstate · Curated listings',
    majorCorridors: 'SR-20 · SR-525 · Camano approaches · ferry terminals · NAS access roads',
    parentLabel: 'Snohomish County',
    parentHref: '/local-movers/washington/snohomish',
    parentAltLabel: 'Kitsap County',
    parentAltHref: '/local-movers/washington/kitsap',
    compareIntro:
      'Island is ferry/bridge-constrained island product — not Snohomish continuous Everett multi-family density and not pure Kitsap peninsula product alone.',
    compareBullets: [
      b('Drive time & corridor relationship', 'Snohomish crews fight I-5 peaks into Everett. Island pairs ride SR-20, SR-525, and ferry/bridge approaches — freer mid-day on-island freeflow, still peak-heavy around sailings, NAS windows, and Camano approaches.'),
      b('Housing stock differences', 'Snohomish mixes Everett multi-family and Lynnwood HOAs. Island mixes Oak Harbor multi-unit, Coupeville multi-story, and Camano SFH — more island last-mile product, less continuous mainland multi-family density.'),
      b('Truck access & density', 'Ferry size limits and sailing windows are first-class; multi-family elevators appear on Oak Harbor growth; rural island lots add soft shoulders.'),
      b('Rough cost posture (qualitative)', 'Local Island quotes often track island secondary-premium rates when ferries constrain truck size — clean Camano driveway SFH can price lower than peak sailing multi-family jobs.'),
      b('Role difference', 'Island is ferry/bridge-constrained island logistics — not mainland Snohomish product renamed.'),
    ],
    whatIntro: 'Ferry/bridge constraints, NAS calendars, and island multi-family — not interchangeable Everett boilerplate.',
    whatBullets: [
      b('Ferry and bridge windows rewrite schedules', 'Sailing times and truck size limits are first-class survey inputs.'),
      b('NAS Whidbey PCS calendars compress demand', 'Report dates drive surveys more than preferred Saturdays.'),
      b('Oak Harbor multi-family is first-class product', 'Elevators and parking need inventories different from pure Camano lots.'),
      b('Distinct from mainland Snohomish day-rate assumptions', 'Do not recycle Everett multi-family rates alone.'),
    ],
    zonesHeading: 'Island zones: Oak Harbor multi-family, Coupeville multi-story, Camano approaches & rural island lots',
    zonesIntro: 'Two to four sharp products — base multi-family, seat multi-story, Camano approaches, and rural lots.',
    zones: [
      z('oak-harbor', 'Oak Harbor multi-family & NAS-adjacent stock', 'Oak Harbor', ['Oak Harbor', 'NAS-adjacent multi-family', 'growth apartments'], 'Multi-family, apartments, townhomes', ['PCS clusters', 'Elevators', 'COI packets'], ['oak harbor'], 'Book around report dates; collect building rules.'),
      z('coupeville', 'Coupeville multi-story & older stock', 'Coupeville', ['Coupeville', 'seat multi-family'], 'Multi-story, multi-unit, older SFH', ['Stairs', 'Street parking', 'Ferry freeflow'], ['coupeville'], 'Inventory stairs; plan temporary no-parking.'),
      z('camano', 'Camano Island approaches', 'Camano', ['Camano Island', 'bridge approaches', 'island SFH'], 'SFH, multi-family, mixed stock', ['Bridge freeflow', 'Empty miles', 'Rain staging'], ['camano'], 'Photo last-mile; build bridge-peak buffers.'),
      z('rural-island', 'Rural island lots', 'Rural island', ['rural tracts', 'island approaches'], 'Larger lots, rural approaches', ['Soft shoulders', 'Ferry timing', 'Empty miles'], ['rural island'], 'Survey approaches; soft ground after rain can block heavy trucks.'),
    ],
    specialized: [
      s('ferry-bridge', 'Ferry / bridge constraint module', 'Sailing windows and truck limits are first-class cost drivers.', ['Confirm ferry truck size limits early.', 'Build sailing buffers into portal-to-portal quotes.']),
      s('nas-pcs', 'NAS Whidbey PCS cycle module', 'Order-driven calendars dominate Oak Harbor volume.', ['Align surveys with report dates.', 'Document inventories carefully for military claims processes.']),
      s('island-multi', 'Oak Harbor multi-family access', 'Elevators and parking are first-class cost drivers.', ['Collect COI and elevator reservations early.', 'Do not recycle Everett mainland day rates alone.']),
    ],
    schoolsIntro: 'Island families compare Oak Harbor, Coupeville, South Whidbey, and related district feeders — verify address boundaries; do not assume Snohomish maps apply.',
    hospitalsDetail: 'WhidbeyHealth and mainland specialty spillover serve the county; map peak ferry/bridge times for ER access.',
    costIntro: 'Ferry constraints, multi-family access, and PCS peaks often matter more than raw miles.',
    seasonalIntro: 'PCS cycles, school years, ferry peak seasons, and rain staging reshape demand by pocket.',
  },
];
