export const UTAH_MOVE_SNAPSHOT = {
  route: '/utah',
  sourceClock: 'UDOT and Utah Code pages reviewed 2026-10-06; the Code page is effective 2026-05-06. The state sources publish no dataset-wide HHG-roster clock.',
  reviewedAt: '2026-10-06T14:35:00Z',
  sourceRowsAcquired: 0,
  observations: 0,
  existingLocalDirectoryRecords: 8,
  existingCountyGuides: 29,
  existingMatches: 'NOT_ACQUIRED',
  netNewEntities: 0,
  evidenceAttachments: 0,
  graphWrites: 0,
  links: {
    udotCarrierOverview: 'https://connect.udot.utah.gov/business/motor-carriers/',
    udotMotorCarrierDecision: 'https://connect.udot.utah.gov/business/motor-carriers/are-you-a-motor-carrier/',
    utahCode: 'https://le.utah.gov/xcode/Title72/Chapter9/C72-9-S102_2026050620260506.pdf',
    intrastateVehicleRegistration: 'https://connect.udot.utah.gov/business/motor-carriers/motor-carrier-registration-credentials/utah-intrastate-registration/',
    operatingAuthority: 'https://connect.udot.utah.gov/business/motor-carriers/motor-carrier-registration-credentials/motor-carrier-operating-authority/',
    usdot: 'https://connect.udot.utah.gov/business/motor-carriers/motor-carrier-registration-credentials/usdot-numbers-registering-with-the-fmcsa/',
    insurance: 'https://connect.udot.utah.gov/business/motor-carriers/motor-carrier-registration-credentials/motor-carrier-insurance-requirements-mcs-90/',
    fmcsaProtect: 'https://www.fmcsa.dot.gov/protect-your-move',
    fmcsaSafer: 'https://safer.fmcsa.dot.gov/',
    ucr: 'https://www.ucr.gov/',
    utahBusinessSearch: 'https://businessregistration.utah.gov/',
  },
} as const;
