/** LA-MOVE-001: LPSC household-goods common-carrier certificate. No public HHG roster acquired. */
export const LOUISIANA_MOVE_SNAPSHOT = {
  regulator: 'Louisiana Public Service Commission, Transportation Division',
  householdGoodsUrl: 'https://www.lpsc.louisiana.gov/Carrier_HGM',
  searchPortalUrl: 'https://lpscpubvalence.lpsc.louisiana.gov/portal/lpsc-web-portal',
  writtenEstimateOrderUrl: 'https://www.lpsc.louisiana.gov/docs/orders/GO-07-12-2013.pdf',
  complaintFormUrl: 'https://www.lpsc.louisiana.gov/docs/trans/HOUSEHOLD-COMPLAINT-FORM-Web.pdf',
  thirdPartyLetterUrl: 'https://www.lpsc.louisiana.gov/docs/trans/3rd-party-letter-05-08-15.pdf',
  interstateComplaintUrl: 'https://www.fmcsa.dot.gov/protect-your-move/file-a-complaint',
  statute: 'La. R.S. 45:164(E)',
  retrievedAt: '2026-10-05',
  generatedAt: '2026-10-05T21:00:00Z',
  hhgAuthorityVerification: 'KNOWN',
  hhgRoster: 'NOT_ACQUIRED',
  searchPortal: 'OPEN_SEARCH_ONLY',
  authorityRows: null,
  distinctCertificateNumbers: null,
  rowsWithUsdot: null,
  distinctUsdots: null,
  rowsWithMc: null,
  distinctMcs: null,
  exactFederalBridges: null,
  unmatchedStateRows: null,
  cargoMinimumUsd: null,
  providerInsuranceStatus: 'NOT_ACQUIRED',
  writtenEstimateRight: 'KNOWN',
  writtenEstimateOrderDate: '2013-07-12',
  tariffCorpus: 'NOT_ACQUIRED',
  complaintIntake: 'KNOWN',
  providerComplaintRows: 'NOT_ACQUIRED',
  complaintOutcomes: 'NOT_ACQUIRED',
  enforcementCapability: 'PARTIAL',
  providerEnforcementRows: 'NOT_ACQUIRED',
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
