/** IN-MOVE-001: Indiana DOR authority requirements and verification capability; no public HHG roster acquired. */
export const INDIANA_MOVE_SNAPSHOT = {
  regulator: 'Indiana Department of Revenue, Motor Carrier Services',
  authorityUrl: 'https://www.in.gov/dor/motor-carrier-services/usdot-and-ucr/indiana-intrastate-passenger-and-household-good-authority/',
  faqUrl: 'https://www.in.gov/dor/motor-carrier-services/frequently-asked-questions-motor-carrier-services/',
  recordsUrl: 'https://www.in.gov/dor/legal-records-requests/',
  formsUrl: 'https://www.in.gov/dor/tax-forms/other-forms/motor-carrier-forms-and-applications/',
  tariffGuidanceUrl: 'https://www.in.gov/dor/motor-carrier-services/files/mcs-goods-tariff-requirements.pdf',
  attorneyGeneralComplaintUrl: 'https://www.in.gov/attorneygeneral/consumer-protection-division/file-a-complaint/',
  interstateComplaintUrl: 'https://www.fmcsa.dot.gov/protect-your-move/file-a-complaint',
  retrievedAt: '2026-09-29',
  generatedAt: '2026-09-29T18:57:43Z',
  hhgAuthorityVerification: 'KNOWN',
  hhgRoster: 'NOT_ACQUIRED',
  authorityRows: null,
  distinctAuthorityNumbers: null,
  authorityStatusAsOf: null,
  rowsWithUsdot: null,
  distinctUsdots: null,
  rowsWithMc: null,
  distinctMcs: null,
  exactFederalBridges: null,
  unmatchedStateRows: null,
  formERequirement: 'KNOWN',
  providerInsuranceStatus: 'NOT_ACQUIRED',
  tariffRequestCapability: 'KNOWN',
  tariffCorpus: 'NOT_ACQUIRED',
  intrastateComplaintIntake: 'KNOWN',
  interstateComplaintIntake: 'KNOWN',
  providerComplaintRows: 'NOT_ACQUIRED',
  complaintOutcomes: 'NOT_ACQUIRED',
  enforcementCapability: 'PARTIAL',
  providerEnforcementRows: 'NOT_ACQUIRED',
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
