-- Task 010: private, append-oriented evidence operations. No production execution in this task.
create table if not exists move_v2_review_case(id uuid primary key default gen_random_uuid(),provider_id uuid not null,review_type text not null,status text not null,priority text not null,reason_code text not null,summary text not null,evidence_fingerprint text not null,decision_version integer not null default 0,related_ids jsonb not null default '{}'::jsonb,assigned_reviewer text,opened_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists move_v2_review_decision(id uuid primary key default gen_random_uuid(),review_case_id uuid not null references move_v2_review_case(id),provider_id uuid not null,decision_type text not null,decision_reason text not null,reviewer text not null,created_at timestamptz not null default now(),evidence_fingerprint text not null,selected_observation_ids uuid[] not null default '{}',rejected_observation_ids uuid[] not null default '{}',notes text,supersedes_decision_id uuid references move_v2_review_decision(id));
create table if not exists move_v2_provider_branch(id uuid primary key default gen_random_uuid(),provider_id uuid not null,address jsonb not null,coordinates point,phone text,website_url text,source_observation_ids uuid[] not null,confidence text not null,current_status text not null,review_status text not null,opened_observed_at timestamptz,closed_observed_at timestamptz,created_at timestamptz not null default now());
create table if not exists move_v2_freshness_policy(id text primary key,policy_version text not null,source_type text not null,soft_interval interval not null,hard_interval interval not null,hard_behavior text not null,retry_policy jsonb not null,created_at timestamptz not null default now());
create table if not exists move_v2_refresh_job(id uuid primary key default gen_random_uuid(),job_type text not null,mode text not null,status text not null,input_fingerprint text not null unique,checkpoint jsonb not null default '{}'::jsonb,attempts integer not null default 0,last_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists move_v2_source_change_event(id uuid primary key default gen_random_uuid(),provider_id uuid,source text not null,field_type text not null,old_observation jsonb,new_observation jsonb,detected_at timestamptz not null default now(),materiality text not null,consumer_impact text not null,review_required boolean not null);
create or replace function move_v2_deny_immutable_change() returns trigger language plpgsql as $$ begin raise exception 'Move V2 evidence operations ledger is append-only'; end $$;
drop trigger if exists move_v2_review_decision_immutable on move_v2_review_decision;create trigger move_v2_review_decision_immutable before update or delete on move_v2_review_decision for each row execute function move_v2_deny_immutable_change();
drop trigger if exists move_v2_change_event_immutable on move_v2_source_change_event;create trigger move_v2_change_event_immutable before update or delete on move_v2_source_change_event for each row execute function move_v2_deny_immutable_change();
alter table move_v2_review_case enable row level security;alter table move_v2_review_decision enable row level security;alter table move_v2_provider_branch enable row level security;alter table move_v2_freshness_policy enable row level security;alter table move_v2_refresh_job enable row level security;alter table move_v2_source_change_event enable row level security;
revoke all on move_v2_review_case,move_v2_review_decision,move_v2_provider_branch,move_v2_freshness_policy,move_v2_refresh_job,move_v2_source_change_event from anon,authenticated;
