/** MD-MOVE-001: official public query is protected by reCAPTCHA; no roster was fabricated. */
export const MARYLAND_MOVE_SNAPSHOT = {
  retrievedAt: '2026-09-29',
  generatedAt: '2026-09-29T12:42:24Z',
  queryUpdatedAt: '2025-12-01',
  regulatorUrl: 'https://www.labor.maryland.gov/license/hgm/',
  consumerUrl: 'https://www.labor.maryland.gov/license/hgm/hhmcon.shtml',
  searchUrl: 'https://www.dllr.state.md.us/cgi-bin/ElectronicLicensing/HGM/HHG_search.cgi',
  applicationUrl: 'https://www.labor.maryland.gov/license/hgm/hhmreginfo.shtml',
  regulationsUrl: 'https://www.labor.maryland.gov/license/hgm/hhgregulations.pdf',
  launchUrl: 'https://labor.maryland.gov/whatsnews/newregistrationhouseholdgoodsmovers.shtml',
  rosterCoverage: 'VERIFICATION_ONLY',
  rows: null,
  distinctRegistrations: null,
  rowsWithUsdot: null,
  distinctUsdots: null,
  rowsWithMc: null,
  distinctMcs: null,
  exactFederalBridges: null,
  rowsWithoutFederalIds: null,
  providerEnforcementRows: null,
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
