import{createHash}from"node:crypto";import{readFileSync,statSync}from"node:fs";import{Client}from"pg";
import type{WashingtonUtcRecord}from"../../../lib/move-v2/state-authority/washington";import{databaseUrl,ssl}from"../db/connection";
const path="artifacts/move-v2/state/wa-utc-pilot.json",url="https://www.utc.wa.gov/companies?exposed_select_industry=568";
async function main(){const c=new Client({connectionString:databaseUrl(),ssl});await c.connect();const data=JSON.parse(readFileSync(path,"utf8")) as WashingtonUtcRecord[];const body=readFileSync(path);try{await c.query("begin");
 const rel=await c.query(`insert into move_v2.state_source_release(state,regulator,source_name,source_url,source_class,retrieved_at,record_count,sha256,adapter_version,retrieval_method,ingestion_status)
 values('WA','Washington Utilities and Transportation Commission','UTC Household Goods Carrier pilot',$1,'STATE_REGULATOR_CURRENT',$2,$3,$4,'WA_UTC_HHG_2026_08_V1','BOUNDED_PAGINATED_HTML','PUBLISHED')
 on conflict(state,source_url,retrieved_at) do update set record_count=excluded.record_count returning state_source_release_id`,[url,statSync(path).mtime.toISOString(),data.length,createHash("sha256").update(body).digest("hex")]);
 let exact=0,review=0;for(const r of data){const hash=createHash("sha256").update(JSON.stringify(r)).digest("hex");const sr=await c.query(`insert into move_v2.state_authority_source_record
 (state_source_release_id,state,authority_type,license_registration_number,status,legal_name,dba_name,address,phone,email,website,relationship_observations,source_record_reference,source_record_hash,raw_record)
 values($1,'WA','WA_UTC_HHG',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) on conflict(state_source_release_id,source_record_reference) do update set source_record_hash=excluded.source_record_hash returning state_authority_source_record_id`,
 [rel.rows[0].state_source_release_id,r.utcId,r.status,r.legalName,r.dbaName??null,JSON.stringify({address:r.address,city:r.city,state:'WA',postalCode:r.postalCode}),r.phone??null,r.email??null,r.website??null,JSON.stringify(r.relationshipObservations??[]),r.sourceRecordReference,hash,JSON.stringify(r)]);
 const providers=r.usdot?await c.query(`select provider_id,legal_name,dba_name,phone,physical_address from move_v2.fmcsa_provider_fact where usdot=$1`,[r.usdot]):{rows:[]};
 if(providers.rows.length===1){exact++;const p=providers.rows[0];await c.query(`insert into move_v2.provider_state_authority_match(provider_id,state_authority_source_record_id,state,match_status,match_score,reason_codes,match_rule_version,matched_at)
 values($1,$2,'WA','STATE_MATCH_HIGH_CONFIDENCE',100,array['USDOT_EXACT'],'WA_UTC_IDENTITY_2026_08_V1',now()) on conflict do nothing`,[p.provider_id,sr.rows[0].state_authority_source_record_id]);
 const eligibility=r.status==='ACTIVE'?'STATE_VERIFIED_LOCAL_MOVER':r.status==='INACTIVE'?'STATE_INACTIVE_LOCAL_MOVER':'STATE_AUTHORITY_REVIEW';
 await c.query(`insert into move_v2.provider_local_eligibility(provider_id,state,eligibility,rule_version,reason_codes,state_authority_source_record_ids,evaluated_at)
 values($1,'WA',$2,'WA_UTC_ELIGIBILITY_2026_08_V1',$3,$4,now()) on conflict(provider_id,state) where superseded_at is null do update set eligibility=excluded.eligibility,reason_codes=excluded.reason_codes,state_authority_source_record_ids=excluded.state_authority_source_record_ids,evaluated_at=excluded.evaluated_at`,[p.provider_id,eligibility,[`UTC_${r.status}`,'USDOT_EXACT'],[sr.rows[0].state_authority_source_record_id]]);
 for(const [type,value] of [['UTC_ID',r.utcId],['UBI',r.ubi],['USDOT',r.usdot]] as const)if(value)await c.query(`insert into move_v2.state_provider_identifier(provider_id,state_authority_source_record_id,state,identifier_type,identifier_value,observed_at) values($1,$2,'WA',$3,$4,now()) on conflict do nothing`,[p.provider_id,sr.rows[0].state_authority_source_record_id,type,value]);
 for(const contact of [{type:'PHONE',value:r.phone},{type:'EMAIL',value:r.email},{type:'ADDRESS',value:r.address}].filter(x=>x.value))await c.query(`insert into move_v2.state_authority_contact_observation(provider_id,state_authority_source_record_id,contact_type,value,normalized_value,source_term,observed_at) values($1,$2,$3,$4,$5,$6,now()) on conflict do nothing`,[p.provider_id,sr.rows[0].state_authority_source_record_id,contact.type,contact.value,String(contact.value).toLowerCase().replace(/\s+/g,' '),`WA UTC ${contact.type}`]);
 }else review++;}
 await c.query("commit");console.log(JSON.stringify({records:data.length,exactMatches:exact,unmatchedOrReview:review}));}catch(e){await c.query("rollback");throw e}finally{await c.end()}}
void main();
