import type { InsuranceHub } from '@/types/insurance/agent';

/** 50+ priority MSA/city hubs — health insurance emphasis in every market */
export const INSURANCE_HUBS: InsuranceHub[] = [
  {
    slug: 'nyc-newark-jersey-city',
    stateSlug: 'new-york',
    stateCode: 'NY',
    stateName: 'New York',
    msaName: 'New York-Newark-Jersey City',
    shortName: 'NYC Metro',
    population: 19_800_000,
    enrollmentHighlight: '4.2M+ ACA and employer enrollees across tri-state corridor',
    localDescriptor: 'tri-state families, union plans, and diverse immigrant communities',
    priority: 1,
    zipCodes: ['10001', '10019', '11201', '07102', '07302'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'The nation\'s largest insurance market combines dense employer-sponsored coverage, ACA marketplace enrollment, and Medicaid managed care. Independent brokers navigate multi-state licensing and diverse-language enrollment needs across NYC boroughs, Long Island, and northern New Jersey.',
    healthNeeds: ['ACA multilingual enrollment', 'Union and employer transitions', 'Medicaid-to-Medicare bridges', 'Small business group plans'],
    metaTitle: 'Top Verified Insurance Agents in NYC Metro (2026) | Health Insurance Experts',
    metaDescription:
      'Compare 850+ verified insurance agents in New York-Newark-Jersey City. Health insurance specialists for ACA, Medicare, employer plans, and multi-line coverage. 100% data-driven, no paid placements.',
  },
  {
    slug: 'los-angeles',
    stateSlug: 'california',
    stateCode: 'CA',
    stateName: 'California',
    msaName: 'Los Angeles-Long Beach-Anaheim',
    shortName: 'Los Angeles',
    population: 12_900_000,
    enrollmentHighlight: 'Covered California leads national ACA enrollment volume',
    localDescriptor: 'Southern California families, entertainment industry, and Latino communities',
    priority: 2,
    zipCodes: ['90001', '90012', '90210', '90650', '91401'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Covered California makes LA County one of the highest ACA enrollment markets in the U.S. Agents here specialize in subsidy optimization, Medi-Cal transitions, entertainment-industry gig coverage, and wildfire-related property/health bundling for relocating families.',
    healthNeeds: ['Covered California subsidies', 'Medi-Cal eligibility', 'Entertainment gig economy plans', 'Bilingual enrollment'],
    metaTitle: 'Verified Insurance Agents in Los Angeles (2026) | ACA & Medicare Experts',
    metaDescription:
      'Find trusted health insurance agents in Los Angeles-Long Beach-Anaheim. ACA marketplace, Medicare, dental, and multi-line agencies verified from state DOI and public reviews.',
  },
  {
    slug: 'chicago',
    stateSlug: 'illinois',
    stateCode: 'IL',
    stateName: 'Illinois',
    msaName: 'Chicago-Naperville-Elgin',
    shortName: 'Chicago',
    population: 9_400_000,
    enrollmentHighlight: '2.1M+ marketplace and employer enrollees — union funds, HQ benefits, and Get Covered Illinois',
    localDescriptor: 'Chicagoland commuters, union households, North Side retirees, and collar-county relocations',
    priority: 3,
    zipCodes: ['60601', '60614', '60629', '60657', '60173', '60477', '60303'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Chicago Metro across Cook, DuPage, Lake, Will, and Kane is one of the nation\'s largest insurance markets with high-volume employer-sponsored plans, competitive individual/ACA offerings via Get Covered Illinois, and significant Medicare demand. Independent brokers navigate union health funds, downtown corporate benefits, and diverse multicultural enrollment across North Side, West Town, and western/northern suburbs.',
    healthNeeds: [
      'Get Covered Illinois ACA marketplace',
      'Union health fund navigation',
      'Cook County employer group plans',
      'Rush/UChicago network alignments',
      'Bilingual Medicare (EN/ES)',
      'DuPage/Lake suburban employer transitions',
    ],
    metaTitle: 'Insurance Agents in Chicago Metro (2026) | Cook, DuPage & Lake',
    metaDescription:
      'Compare 12 verified independent insurance agents in Chicago-Naperville-Elgin. Health, Medicare, ACA, and group specialists across Cook and collar counties — IL DOI verified.',
  },
  {
    slug: 'dallas-fort-worth',
    stateSlug: 'texas',
    stateCode: 'TX',
    stateName: 'Texas',
    msaName: 'Dallas-Fort Worth-Arlington',
    shortName: 'DFW',
    population: 8_100_000,
    enrollmentHighlight: 'Fastest-growing large MSA — corporate HQ and logistics driving employer-sponsored volume',
    localDescriptor: 'DFW corporate relocations, Plano tech corridor, Fort Worth logistics, and young families',
    priority: 4,
    zipCodes: ['75201', '76102', '75001', '75034', '76010', '75088', '75206'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Dallas-Fort Worth across Dallas, Tarrant, Collin, Denton, and Ellis counties is one of the fastest-growing U.S. insurance markets with high-volume employer-sponsored plans, competitive HealthCare.gov individual offerings, and Medicare demand in Plano, Arlington, and downtown Dallas corridors.',
    healthNeeds: [
      'Corporate relocation ACA',
      'Collin County employer group plans',
      'Fort Worth/Tarrant Medicare',
      'HealthCare.gov individual marketplace',
      'Tech corridor small-group benefits',
      'Hail/wind property + health bundling',
    ],
    metaTitle: 'Insurance Agents in Dallas-Fort Worth (2026) | Dallas, Tarrant & Collin',
    metaDescription:
      'Compare 12 verified independent insurance agents in DFW. Employer group, ACA, and Medicare specialists across Dallas, Fort Worth, and Collin — TX DOI verified.',
  },
  {
    slug: 'houston',
    stateSlug: 'texas',
    stateCode: 'TX',
    stateName: 'Texas',
    msaName: 'Houston-The Woodlands-Sugar Land',
    shortName: 'Houston',
    population: 7_300_000,
    enrollmentHighlight: 'Energy, healthcare, and port/logistics employer volume plus Gulf Coast ACA enrollment',
    localDescriptor: 'energy professionals, Texas Medical Center corridor, and diverse Houston suburbs',
    priority: 5,
    zipCodes: ['77002', '77024', '77025', '77479', '77380', '77584', '77032'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Houston Metro across Harris, Fort Bend, Montgomery, and Brazoria counties features massive employer-sponsored volume from energy, healthcare, and port/logistics sectors alongside competitive individual/ACA offerings and significant Medicare demand in The Woodlands, Sugar Land, and Clear Lake.',
    healthNeeds: [
      'Energy sector group benefits',
      'Texas Medical Center network plans',
      'Harris County ACA marketplace',
      'Fort Bend suburban employer plans',
      'Woodlands/Montgomery Medicare',
      'Flood-zone property + health bundles',
    ],
    metaTitle: 'Insurance Agents in Houston Metro (2026) | Harris, Fort Bend & Montgomery',
    metaDescription:
      'Compare 12 verified independent insurance agents in Houston-The Woodlands-Sugar Land. Energy employer benefits, ACA, and Medicare specialists — TX DOI verified.',
  },
  {
    slug: 'washington-dc',
    stateSlug: 'virginia',
    stateCode: 'VA',
    stateName: 'Virginia',
    msaName: 'Washington-Arlington-Alexandria',
    shortName: 'DC Metro',
    population: 6_300_000,
    enrollmentHighlight: 'Federal FEHB, government contractor benefits, and tri-jurisdictional ACA marketplace',
    localDescriptor: 'federal employees, Montgomery County professionals, and NoVA tech corridor',
    priority: 6,
    zipCodes: ['20001', '22201', '22314', '20814', '20171', '20007', '22043'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'The DC Metro across the District, Montgomery and Prince George\'s counties in Maryland, and Arlington and Fairfax in Virginia is a high-income market with significant federal/government employer-sponsored plans, competitive individual/ACA offerings, and robust Medicare demand among retirees and contractors.',
    healthNeeds: [
      'FEHB open season navigation',
      'Contractor-to-private transitions',
      'Maryland Health Connection ACA',
      'Virginia marketplace enrollment',
      'Montgomery County Medicare',
      'NoVA tech employer group plans',
    ],
    metaTitle: 'Insurance Agents in DC Metro (2026) | DC, Maryland & Virginia',
    metaDescription:
      'Compare 12 verified independent insurance agents in Washington-Arlington-Alexandria. FEHB, ACA, Medicare, and group specialists across DC, MD, and VA — multi-state DOI verified.',
  },
  {
    slug: 'miami-fort-lauderdale',
    stateSlug: 'florida',
    stateCode: 'FL',
    stateName: 'Florida',
    msaName: 'Miami-Fort Lauderdale-Pompano Beach',
    shortName: 'South Florida',
    population: 6_100_000,
    enrollmentHighlight: 'Nation\'s highest Medicare Advantage penetration market',
    localDescriptor: 'retirees, snowbirds, Caribbean and Latino communities',
    priority: 7,
    zipCodes: ['33101', '33139', '33301', '33024', '33401'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'South Florida leads the nation in Medicare Advantage enrollment density across Miami-Dade, Broward, and Palm Beach counties. Independent brokers in Doral, Hollywood, Fort Lauderdale, Greenacres, and Boca Raton compare Advantage, supplement, and ACA plans for retirees, snowbirds, and bilingual families — with property insurers addressing hurricane and flood risks alongside health coverage.',
    healthNeeds: [
      'Medicare Advantage comparison (tri-county)',
      'Bilingual ACA enrollment (Miami-Dade)',
      'Snowbird coverage transitions',
      'Palm Beach senior supplement plans',
      'Hurricane property + health bundling',
    ],
    metaTitle: 'Insurance Agents in South Florida (2026) | Miami-Dade, Broward & Palm Beach',
    metaDescription:
      'Compare 12 verified independent insurance agents across Miami-Dade, Broward, and Palm Beach. Medicare Advantage, ACA, supplement plans, and multi-line specialists — 4.9 avg rating, DFS verified.',
  },
  {
    slug: 'miami-dade',
    stateSlug: 'florida',
    stateCode: 'FL',
    stateName: 'Florida',
    msaName: 'Miami-Dade County',
    shortName: 'Miami-Dade',
    population: 2_700_000,
    enrollmentHighlight: 'Highest ACA and Medicare Advantage density in Florida',
    localDescriptor: 'Miami, Hialeah, Doral, Kendall, and Caribbean/Latino communities',
    priority: 55,
    zipCodes: ['33101', '33125', '33139', '33176', '33186'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Miami-Dade County is Florida\'s largest health insurance market with the nation\'s highest Medicare Advantage penetration. Independent brokers in Miami, Doral, and Kendall specialize in bilingual ACA enrollment, Medicare Advantage comparisons, and employer group plans for healthcare and logistics employers.',
    healthNeeds: [
      'Medicare Advantage comparison (Miami-Dade)',
      'Bilingual ACA enrollment (EN/ES)',
      'Jackson Health / Baptist network alignments',
      'Employer group plans (Doral corridor)',
      'Snowbird coverage transitions',
    ],
    metaTitle: 'Insurance Agents in Miami-Dade County (2026) | Health & Medicare Experts',
    metaDescription:
      'Compare verified health insurance agents in Miami-Dade County. Medicare Advantage, ACA, supplement, and group specialists — FL DFS verified, no paid placements.',
  },
  {
    slug: 'broward-county',
    stateSlug: 'florida',
    stateCode: 'FL',
    stateName: 'Florida',
    msaName: 'Broward County',
    shortName: 'Broward County',
    population: 1_950_000,
    enrollmentHighlight: 'Fort Lauderdale corridor — dense retiree and family ACA/Medicare market',
    localDescriptor: 'Fort Lauderdale, Hollywood, Pembroke Pines, and Coral Springs families',
    priority: 56,
    zipCodes: ['33301', '33024', '33023', '33064', '33026'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Broward County between Miami-Dade and Palm Beach combines high Medicare Advantage enrollment with growing employer-sponsored coverage along the I-95 corridor. Agents in Fort Lauderdale and Hollywood navigate Florida Blue, Humana, and UnitedHealthcare networks for seniors and young families.',
    healthNeeds: [
      'Medicare Advantage (Broward)',
      'ACA marketplace enrollment',
      'Fort Lauderdale employer group plans',
      'Broward Health network alignments',
      'Hurricane property + health bundling',
    ],
    metaTitle: 'Insurance Agents in Broward County (2026) | Fort Lauderdale Health Hub',
    metaDescription:
      'Find verified health insurance agents in Broward County. Medicare, ACA, and multi-line specialists serving Fort Lauderdale and Hollywood — FL DFS verified.',
  },
  {
    slug: 'palm-beach-county',
    stateSlug: 'florida',
    stateCode: 'FL',
    stateName: 'Florida',
    msaName: 'Palm Beach County',
    shortName: 'Palm Beach County',
    population: 1_500_000,
    enrollmentHighlight: 'Palm Beach retiree corridor — top Medicare supplement demand',
    localDescriptor: 'West Palm Beach, Boca Raton, Delray Beach, and Greenacres retirees',
    priority: 57,
    zipCodes: ['33401', '33431', '33444', '33463', '33411'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Palm Beach County is a premier retiree market with exceptional Medicare supplement and Advantage demand from West Palm Beach through Boca Raton. Independent agents compare plans across Cleveland Clinic Florida, HCA, and Florida Blue networks for snowbirds and year-round residents.',
    healthNeeds: [
      'Medicare supplement vs Advantage',
      'Palm Beach retiree enrollment',
      'Boca Raton / West Palm ACA',
      'Snowbird dual-residency coverage',
      'Group plans (Greenacres corridor)',
    ],
    metaTitle: 'Insurance Agents in Palm Beach County (2026) | Medicare & ACA Experts',
    metaDescription:
      'Compare verified insurance agents in Palm Beach County. Medicare supplement, Advantage, and ACA specialists in West Palm Beach and Boca Raton — FL DFS verified.',
  },
  {
    slug: 'philadelphia',
    stateSlug: 'pennsylvania',
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    msaName: 'Philadelphia-Camden-Wilmington',
    shortName: 'Philadelphia',
    population: 6_200_000,
    enrollmentHighlight: 'Pennie marketplace and cross-state tri-county enrollment',
    localDescriptor: 'tri-state commuters, healthcare workers, and university communities',
    priority: 8,
    zipCodes: ['19102', '19103', '19010', '08003', '19801'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Greater Philadelphia spans three states with Pennie (PA), Get Covered NJ, and Delaware marketplace options. Healthcare employment clusters create strong group-plan expertise among independent agencies serving collar counties and Wilmington corporate corridors.',
    healthNeeds: ['Pennie ACA enrollment', 'Cross-state licensing', 'Healthcare worker benefits', 'University young-adult plans'],
    metaTitle: 'Insurance Agents in Philadelphia Metro (2026) | Health Insurance Hub',
    metaDescription:
      'Verified insurance agents in Philadelphia-Camden-Wilmington. ACA, Medicare, employer plans, and multi-line coverage across tri-state region.',
  },
  {
    slug: 'atlanta',
    stateSlug: 'georgia',
    stateCode: 'GA',
    stateName: 'Georgia',
    msaName: 'Atlanta-Sandy Springs-Alpharetta',
    shortName: 'Atlanta',
    population: 6_200_000,
    enrollmentHighlight: 'Georgia\'s largest health market — 6–7 ACA carriers; Elevance leads large-group employer segment',
    localDescriptor: 'corporate HQ relocations, diverse Fulton-DeKalb core, and fast-growing Gwinnett-Cobb suburbs',
    priority: 9,
    zipCodes: ['30303', '30309', '30004', '30328', '30067', '30043'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Atlanta is Georgia\'s largest geographic health insurance market across Fulton, DeKalb, Gwinnett, Cobb, and Clayton — with 6–7 competing exchange carriers including Kaiser Permanente HMO, Oscar, Anthem BCBS, Ambetter, CareSource, and UnitedHealthcare. Corporate relocations drive large-group employer plans (Elevance, UnitedHealthcare, Cigna), while Georgia Access individual enrollment remains among the nation\'s most robust. Independent brokers navigate marketplace, Medicare, and group benefits for metro buyers.',
    healthNeeds: [
      'Georgia Access ACA (Ambetter, Anthem, Oscar)',
      'Kaiser Permanente HMO networks',
      'Large-group employer plans (Elevance/UnitedHealthcare)',
      'Corporate relocation health transitions',
      'Medicare in north Fulton & Gwinnett suburbs',
      'Gwinnett/Cobb suburban family plans',
    ],
    metaTitle: 'Insurance Agents in Atlanta Metro (2026) | Fulton, DeKalb & Gwinnett',
    metaDescription:
      'Compare 12 verified independent insurance agents in Atlanta-Sandy Springs-Alpharetta. ACA, Medicare, group health, and multi-line specialists across Fulton, DeKalb, Gwinnett, Cobb — GA OCI verified.',
  },
  {
    slug: 'phoenix',
    stateSlug: 'arizona',
    stateCode: 'AZ',
    stateName: 'Arizona',
    msaName: 'Phoenix-Mesa-Chandler',
    shortName: 'Phoenix',
    population: 5_100_000,
    enrollmentHighlight: 'Retiree influx fuels Medicare and ACA dual demand',
    localDescriptor: 'retirees, snowbirds, and fast-growing Maricopa families',
    priority: 10,
    zipCodes: ['85001', '85018', '85201', '85224', '85286'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Maricopa County combines rapid population growth with one of the highest retiree migration rates nationally. Health agents navigate Arizona marketplace plans, Medicare Advantage in sun-belt communities, and property coverage for monsoon and wildfire risks.',
    healthNeeds: ['Medicare for retirees', 'Arizona marketplace ACA', 'Snowbird transitions', 'Monsoon property bundling'],
    metaTitle: 'Insurance Agents in Phoenix Metro (2026) | Medicare & ACA Experts',
    metaDescription:
      'Verified insurance agents in Phoenix-Mesa-Chandler. Medicare, ACA, dental, home, and auto specialists for Arizona families and retirees.',
  },
  {
    slug: 'boston',
    stateSlug: 'massachusetts',
    stateCode: 'MA',
    stateName: 'Massachusetts',
    msaName: 'Boston-Cambridge-Newton',
    shortName: 'Boston',
    population: 4_900_000,
    enrollmentHighlight: 'Near-universal coverage via Health Connector and high-volume employer-sponsored plans',
    localDescriptor: 'academic, biotech, healthcare, and finance employment corridors',
    priority: 11,
    zipCodes: ['02108', '02139', '02458', '02134', '01803', '02171', '01902'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Boston Metro across Suffolk, Middlesex, Essex, Norfolk, and Plymouth is a major Northeast insurance market with high-volume employer-sponsored plans in education, healthcare, biotech, and finance, competitive individual/ACA offerings via Massachusetts Health Connector, and robust Medicare demand. Independent brokers optimize plan choices beyond minimum state requirements and guide biotech employer transitions and aging suburban supplement decisions.',
    healthNeeds: [
      'Massachusetts Health Connector optimization',
      'Biotech & hospital employer transitions',
      'Harvard/MIT student and young professional plans',
      'Medicare Advantage & supplements',
      'North Shore & South Shore suburban enrollment',
      'Tufts/MGB network alignments',
    ],
    metaTitle: 'Insurance Agents in Boston Metro (2026) | Suffolk, Middlesex & Norfolk',
    metaDescription:
      'Compare 12 verified independent insurance agents in Boston-Cambridge-Newton. Health, Medicare, ACA, and group specialists across Suffolk and collar counties — MA DOI verified.',
  },
  {
    slug: 'san-francisco',
    stateSlug: 'california',
    stateCode: 'CA',
    stateName: 'California',
    msaName: 'San Francisco-Oakland-Berkeley',
    shortName: 'Bay Area',
    population: 4_600_000,
    enrollmentHighlight: 'Tech employer benefits and Covered California high-cost region',
    localDescriptor: 'tech professionals, startup equity transitions, and diverse Bay Area',
    priority: 12,
    zipCodes: ['94102', '94110', '94601', '94704', '94301'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'The Bay Area\'s tech economy creates complex health benefit scenarios — startup equity transitions, contractor 1099 coverage, and high-income ACA subsidy cliffs. Agents specialize in Covered California optimization and executive group plan consulting.',
    healthNeeds: ['Tech startup benefits', '1099 contractor coverage', 'Covered California subsidy cliffs', 'Earthquake property bundling'],
    metaTitle: 'Insurance Agents in San Francisco Bay Area (2026)',
    metaDescription:
      'Verified insurance agents in SF-Oakland-Berkeley. Health insurance for tech professionals, ACA, Medicare, home, earthquake, and auto.',
  },
  {
    slug: 'riverside-san-bernardino',
    stateSlug: 'california',
    stateCode: 'CA',
    stateName: 'California',
    msaName: 'Riverside-San Bernardino-Ontario',
    shortName: 'Inland Empire',
    population: 4_700_000,
    enrollmentHighlight: 'Affordable housing migration drives Covered California and Medi-Cal enrollment growth',
    localDescriptor: 'LA overflow families, logistics workers, warehouse corridors, and first-time buyers',
    priority: 13,
    zipCodes: ['92501', '92401', '91761', '92879', '92201', '92553', '92408'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'The Inland Empire across Riverside and San Bernardino counties absorbs families priced out of coastal California, creating demand for affordable Covered California plans, Medicare among relocating retirees, and first-time homeowner bundles. Independent brokers serve logistics, warehouse, and service-sector workers with marketplace, Medi-Cal transitions, and wildfire property cross-sell.',
    healthNeeds: [
      'Affordable Covered California ACA',
      'Medi-Cal transitions',
      'Medicare in Riverside & San Bernardino',
      'Ontario-Corona logistics employer plans',
      'Bilingual Medicare (EN/ES)',
      'Wildfire property bundling',
    ],
    metaTitle: 'Insurance Agents in Inland Empire (2026) | Riverside & San Bernardino',
    metaDescription:
      'Compare 12 verified independent insurance agents in Riverside-San Bernardino-Ontario. ACA, Medicare, and group specialists — CA DOI verified.',
  },
  {
    slug: 'detroit',
    stateSlug: 'michigan',
    stateCode: 'MI',
    stateName: 'Michigan',
    msaName: 'Detroit-Warren-Dearborn',
    shortName: 'Detroit',
    population: 4_300_000,
    enrollmentHighlight: 'Auto industry benefits, UAW familiarity, and Michigan Health Insurance Marketplace enrollment',
    localDescriptor: 'auto industry workers, union households, Dearborn diverse communities, and Oakland suburbs',
    priority: 14,
    zipCodes: ['48201', '48226', '48009', '48307', '48126', '48083', '48101'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Detroit Metro across Wayne, Oakland, and Macomb reflects automotive industry benefit structures, UAW health fund familiarity, and competitive Michigan marketplace enrollment. Independent brokers navigate employer-sponsored plans, ACA individual coverage, and Medicare demand among aging Oakland and Macomb suburbs alongside diverse Dearborn and Detroit communities.',
    healthNeeds: [
      'Auto industry benefit transitions',
      'Michigan marketplace ACA (BCBSM, Priority Health)',
      'Union health fund navigation',
      'Medicare in Oakland & Macomb suburbs',
      'Dearborn multilingual communities',
      'Henry Ford / Corewell network alignments',
    ],
    metaTitle: 'Insurance Agents in Detroit Metro (2026) | Wayne, Oakland & Macomb',
    metaDescription:
      'Compare 12 verified independent insurance agents in Detroit-Warren-Dearborn. Health, Medicare, ACA, and group specialists across Wayne, Oakland, and Macomb — MI DIFS verified.',
  },
  {
    slug: 'seattle',
    stateSlug: 'washington',
    stateCode: 'WA',
    stateName: 'Washington',
    msaName: 'Seattle-Tacoma-Bellevue',
    shortName: 'Seattle',
    population: 4_000_000,
    enrollmentHighlight: 'Washington Healthplanfinder and Amazon/Microsoft/tech employer dominance',
    localDescriptor: 'tech workers, contractor 1099 households, and Puget Sound families',
    priority: 15,
    zipCodes: ['98101', '98109', '98004', '98402', '98052', '98103', '98122'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Seattle-Tacoma-Bellevue across King, Snohomish, Pierce, and Kitsap reflects Puget Sound\'s tech economy with high-volume employer-sponsored plans, Washington Healthplanfinder ACA enrollment, and significant Medicare demand among Eastside and North Sound retirees. Independent brokers navigate contractor 1099 coverage, ICHRA employer transitions, and earthquake/flood property bundling.',
    healthNeeds: [
      'Washington Healthplanfinder ACA',
      'Amazon/Microsoft employer transitions',
      'Contractor 1099 coverage',
      'Medicare on the Eastside',
      'UW Medicine / Swedish network alignments',
      'Earthquake & flood property bundling',
    ],
    metaTitle: 'Insurance Agents in Seattle Metro (2026) | King, Snohomish & Pierce',
    metaDescription:
      'Compare 12 verified independent insurance agents in Seattle-Tacoma-Bellevue. Health, Medicare, ACA, and group specialists across Puget Sound — WA OIC verified.',
  },
  // Remaining 35+ hubs (condensed metadata — full agent rosters generated programmatically)
  {
    slug: 'minneapolis',
    stateSlug: 'minnesota',
    stateCode: 'MN',
    stateName: 'Minnesota',
    msaName: 'Minneapolis-St. Paul-Bloomington',
    shortName: 'Twin Cities',
    population: 3_700_000,
    enrollmentHighlight: 'MNsure marketplace and Medtronic/healthcare HQ employer benefits',
    localDescriptor: 'Twin Cities families, healthcare corridor workers, and Edina/St Paul suburbs',
    priority: 16,
    zipCodes: ['55401', '55101', '55416', '55403', '55105', '55435'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Minneapolis-St. Paul across Hennepin and Ramsey counties features high-volume employer-sponsored plans from healthcare and retail headquarters, competitive MNsure individual/ACA offerings, and robust Medicare demand among aging suburbs. Independent brokers navigate Mayo-adjacent networks, Medtronic-scale benefits, and winter property bundling.',
    healthNeeds: [
      'MNsure ACA marketplace',
      'Healthcare employer plans (Medtronic corridor)',
      'Medicare in Hennepin & Ramsey suburbs',
      'Mayo/Allina network alignments',
      'St Paul vs Minneapolis county enrollment',
    ],
    metaTitle: 'Insurance Agents in Twin Cities (2026) | Hennepin & Ramsey',
    metaDescription:
      'Compare 12 verified independent insurance agents in Minneapolis-St. Paul-Bloomington. Health, Medicare, ACA, and group specialists — MN DOC verified.',
  },
  {
    slug: 'tampa',
    stateSlug: 'florida',
    stateCode: 'FL',
    stateName: 'Florida',
    msaName: 'Tampa-St. Petersburg-Clearwater',
    shortName: 'Tampa Bay',
    population: 3_300_000,
    enrollmentHighlight: 'Medicare-heavy Gulf Coast retiree market with strong independent broker volume',
    localDescriptor: 'retirees, military veterans, Tampa families, and St. Petersburg Gulf Coast communities',
    priority: 17,
    zipCodes: ['33602', '33701', '34677', '33544', '33764'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Tampa Bay rivals South Florida in Medicare density across Hillsborough, Pinellas, and Pasco counties. Independent brokers like HealthPlan4U and Affordable Insurance Team serve Tampa seniors with 17+ carrier comparisons, while multi-line agencies with 2,000+ reviews shop 80+ carriers alongside VA-adjacent navigation and hurricane-season property/health bundling.',
    healthNeeds: [
      'Medicare Advantage (Hillsborough/Pinellas networks)',
      'VA/TRICARE coordination',
      'ACA for Tampa workforce',
      'Group health (Bay area businesses)',
      'Hurricane flood + health bundling',
    ],
    metaTitle: 'Insurance Agents in Tampa Bay (2026) | Hillsborough, Pinellas & Pasco',
    metaDescription:
      'Compare 12 verified independent insurance agents in Tampa-St. Petersburg-Clearwater. Medicare, ACA, and multi-line specialists across Hillsborough, Pinellas, and Pasco — DFS verified.',
  },
  {
    slug: 'denver',
    stateSlug: 'colorado',
    stateCode: 'CO',
    stateName: 'Colorado',
    msaName: 'Denver-Aurora-Lakewood',
    shortName: 'Denver',
    population: 2_900_000,
    enrollmentHighlight: 'Connect for Health Colorado and rapid relocation-driven ACA enrollment',
    localDescriptor: 'relocating professionals, outdoor enthusiasts, and bilingual metro communities',
    priority: 18,
    zipCodes: ['80202', '80012', '80123', '80206', '80033', '80241'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Denver Metro across Denver, Arapahoe, Jefferson, and Adams counties reflects Colorado\'s relocation boom with high-volume employer-sponsored plans, Connect for Health Colorado individual enrollment, and significant Medicare demand. Independent brokers serve bilingual communities, foothill wildfire property risks, and cannabis/tech sector benefits.',
    healthNeeds: [
      'Connect for Health Colorado ACA',
      'Relocation & early-retiree coverage',
      'Medicare in Aurora & Lakewood suburbs',
      'Bilingual Medicare (EN/ES)',
      'UCHealth/Kaiser network alignments',
      'Wildfire property bundling',
    ],
    metaTitle: 'Insurance Agents in Denver Metro (2026) | Denver, Arapahoe & Jefferson',
    metaDescription:
      'Compare 12 verified independent insurance agents in Denver-Aurora-Lakewood. Health, Medicare, ACA, and group specialists — CO DOI verified.',
  },
  {
    slug: 'baltimore',
    stateSlug: 'maryland',
    stateCode: 'MD',
    stateName: 'Maryland',
    msaName: 'Baltimore-Columbia-Towson',
    shortName: 'Baltimore',
    population: 2_800_000,
    enrollmentHighlight: 'Maryland Health Connection and Johns Hopkins healthcare corridor',
    localDescriptor: 'healthcare workers, federal/DC commuters, and Columbia planned community',
    priority: 19,
    zipCodes: ['21201', '21044', '21234', '21231', '21206', '21093'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Baltimore Metro across Baltimore City and Baltimore County serves Maryland Health Connection enrollees, Johns Hopkins and University of Maryland healthcare employees, and DC commuter benefit transitions. Independent brokers navigate Mid-Atlantic Medicare markets and diverse urban/suburban enrollment.',
    healthNeeds: [
      'Maryland Health Connection ACA',
      'Hopkins/UMMS network alignments',
      'DC commuter FEHB transitions',
      'Medicare in Baltimore County suburbs',
      'Healthcare worker group plans',
      'Mid-Atlantic Medigap comparisons',
    ],
    metaTitle: 'Insurance Agents in Baltimore Metro (2026) | Baltimore City & County',
    metaDescription:
      'Compare 12 verified independent insurance agents in Baltimore-Columbia-Towson. Health, Medicare, ACA, and group specialists — MD MIA verified.',
  },
  {
    slug: 'st-louis',
    stateSlug: 'missouri',
    stateCode: 'MO',
    stateName: 'Missouri',
    msaName: 'St. Louis',
    shortName: 'St. Louis',
    population: 2_800_000,
    enrollmentHighlight: 'Bi-state MO/IL marketplace enrollment and Arch Brokerage individual health volume',
    localDescriptor: 'bi-state families, BJC healthcare corridor, and manufacturing workers',
    priority: 20,
    zipCodes: ['63101', '63117', '62034', '63141', '63110', '63104'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Greater St. Louis across St. Louis City and St. Louis County spans Missouri and Illinois marketplaces, requiring bi-state licensing for ACA and employer transitions. Independent brokers including Arch Brokerage (since 1969) serve healthcare, manufacturing, and diverse metro communities with Medicare and individual health expertise.',
    healthNeeds: [
      'Bi-state MO/IL ACA enrollment',
      'BJC/WashU network alignments',
      'Arch Brokerage individual health',
      'Employer benefit transitions',
      'Medicare in west county suburbs',
      'Blue Chip Consortium group plans',
    ],
    metaTitle: 'Insurance Agents in St. Louis Metro (2026) | St. Louis City & County',
    metaDescription:
      'Compare 12 verified independent insurance agents in Greater St. Louis. Health, Medicare, ACA, and group specialists — MO DCI verified.',
  },
  {
    slug: 'orlando',
    stateSlug: 'florida',
    stateCode: 'FL',
    stateName: 'Florida',
    msaName: 'Orlando-Kissimmee-Sanford',
    shortName: 'Orlando',
    population: 2_700_000,
    enrollmentHighlight: 'Hospitality workforce ACA enrollment plus growing Central Florida Medicare demand',
    localDescriptor: 'hospitality workers, theme-park economy, Winter Park families, and Central Florida retirees',
    priority: 21,
    zipCodes: ['32801', '32789', '34741', '32771', '32750'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Orlando\'s hospitality economy drives ACA demand among seasonal and theme-park workers across Orange County, while Winter Park and Kissimmee anchor independent Medicare and health brokers serving AdventHealth Orlando and Orlando Health networks. Multi-line independents with decades of tenure complement dedicated Medicare specialists across Seminole and Osceola counties.',
    healthNeeds: [
      'Hospitality & seasonal worker ACA',
      'Medicare Advantage (AdventHealth/Orlando Health networks)',
      'Winter Park small-business group health',
      'Kissimmee / Osceola family plans',
      'Seminole County multi-line bundling',
    ],
    metaTitle: 'Insurance Agents in Orlando Metro (2026) | Orange, Osceola & Seminole',
    metaDescription:
      'Compare 12 verified independent insurance agents in Orlando-Kissimmee-Sanford. Medicare, ACA, and multi-line specialists in Winter Park, Kissimmee, and Central Florida — DFS verified.',
  },
  {
    slug: 'charlotte',
    stateSlug: 'north-carolina',
    stateCode: 'NC',
    stateName: 'North Carolina',
    msaName: 'Charlotte-Concord-Gastonia',
    shortName: 'Charlotte',
    population: 2_700_000,
    enrollmentHighlight: 'Corporate health battleground — banking, tech, healthcare; Atrium + Oscar individual market',
    localDescriptor: 'banking HQ corridor, tech workers, Atrium Health networks, and Carolina relocations',
    priority: 22,
    zipCodes: ['28202', '28203', '28027', '28078', '29708'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Charlotte is North Carolina\'s ultimate corporate health insurance battleground in Mecklenburg — a banking, tech, and healthcare hub where large-group employer plans dominate. Atrium Health networks align with BCBSNC and Oscar Health individual products, making independent brokers essential for both corporate benefits and marketplace enrollment across Union, Cabarrus, and Gaston.',
    healthNeeds: [
      'Large-group employer plans (banking/tech)',
      'Atrium Health network navigation',
      'Oscar Health individual marketplace',
      'NC ACA individual/family',
      'Medicare in Mecklenburg suburbs',
      'Union/Cabarrus exurban coverage',
    ],
    metaTitle: 'Insurance Agents in Charlotte Metro (2026) | Mecklenburg & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Charlotte-Concord-Gastonia. Corporate group health, Medicare, ACA, and multi-line specialists — NC DOI verified.',
  },
  {
    slug: 'san-antonio',
    stateSlug: 'texas',
    stateCode: 'TX',
    stateName: 'Texas',
    msaName: 'San Antonio-New Braunfels',
    shortName: 'San Antonio',
    population: 2_600_000,
    enrollmentHighlight: 'Military/VA-adjacent and Latino community enrollment',
    localDescriptor: 'military families, Latino communities, and Hill Country growth',
    priority: 23,
    zipCodes: ['78205', '78216', '78238', '78130', '78250'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'San Antonio Metro across Bexar, Comal, Guadalupe, and Kendall counties serves high-volume employer-sponsored plans, bilingual ACA enrollment near military installations, and Medicare demand in a rapidly growing diverse population. Independent brokers navigate TRICARE/VA coordination and Hill Country suburban growth.',
    healthNeeds: [
      'Military/VA TRICARE coordination',
      'Bilingual ACA enrollment',
      'Employer group health',
      'Medicare for retiring military',
      'Hill Country suburban ACA',
      'Latino community marketplace',
    ],
    metaTitle: 'Insurance Agents in San Antonio Metro (2026) | Bexar & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in San Antonio-New Braunfels. Health, Medicare, ACA, and group specialists — TX DOI verified.',
  },
  {
    slug: 'portland',
    stateSlug: 'oregon',
    stateCode: 'OR',
    stateName: 'Oregon',
    msaName: 'Portland-Vancouver-Hillsboro',
    shortName: 'Portland',
    population: 2_500_000,
    enrollmentHighlight: 'Oregon Health Plan and Washington cross-river enrollment',
    localDescriptor: 'tech commuters, progressive healthcare consumers, and cross-river families',
    priority: 24,
    zipCodes: ['97201', '97214', '97124', '98660', '97045'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Portland Metro across Multnomah, Washington, and Clackamas counties spans Oregon marketplace enrollment with cross-river Washington demand, tech-commuter ACA transitions, and strong independent Medicare broker competition in progressive healthcare markets.',
    healthNeeds: [
      'Oregon marketplace ACA',
      'Cross-river WA/OR licensing',
      'Tech commuter individual plans',
      'Medicare in Multnomah suburbs',
      'Employer group benefits',
      'Clackamas/Washington County enrollment',
    ],
    metaTitle: 'Insurance Agents in Portland Metro (2026) | Multnomah & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Portland-Vancouver-Hillsboro. Health, Medicare, ACA, and group specialists — OR DFR verified.',
  },
  {
    slug: 'sacramento',
    stateSlug: 'california',
    stateCode: 'CA',
    stateName: 'California',
    msaName: 'Sacramento-Roseville-Folsom',
    shortName: 'Sacramento',
    population: 2_400_000,
    enrollmentHighlight: 'State capital employer plans and Covered California enrollment',
    localDescriptor: 'state employees, Gold River retirees, and Central Valley families',
    priority: 25,
    zipCodes: ['95814', '95661', '95670', '95762', '95695'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Sacramento Metro across Sacramento, Placer, El Dorado, and Yolo counties combines CalPERS-adjacent retirement expertise with Covered California enrollment, state-capital employer benefits, and foothill suburban Medicare growth in the Roseville-Folsom corridor.',
    healthNeeds: [
      'Covered California ACA',
      'CalPERS retirement transitions',
      'State employee group benefits',
      'Medicare in Gold River/Roseville',
      'Yolo County bilingual enrollment',
      'Wildfire-zone health transitions',
    ],
    metaTitle: 'Insurance Agents in Sacramento Metro (2026) | Sacramento & Placer',
    metaDescription:
      'Compare 12 verified independent insurance agents in Sacramento-Roseville-Folsom. Health, Medicare, ACA, and group specialists — CA DOI verified.',
  },
  {
    slug: 'pittsburgh',
    stateSlug: 'pennsylvania',
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    msaName: 'Pittsburgh',
    shortName: 'Pittsburgh',
    population: 2_400_000,
    enrollmentHighlight: 'Healthcare and university anchor institutions',
    localDescriptor: 'healthcare systems, university communities, and aging steel towns',
    priority: 26,
    zipCodes: ['15222', '15213', '15216', '15101', '15228'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Greater Pittsburgh across Allegheny, Beaver, Butler, Washington, and Westmoreland counties serves UPMC-adjacent healthcare workers, Carnegie Mellon and University of Pittsburgh ACA populations, and Medicare demand in aging South Hills and mill-town communities.',
    healthNeeds: [
      'UPMC network alignments',
      'University ACA enrollment',
      'Healthcare worker group plans',
      'Medicare in South Hills',
      'Westmoreland suburban Medigap',
      'Aging steel-town Medicare',
    ],
    metaTitle: 'Insurance Agents in Pittsburgh Metro (2026) | Allegheny & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Greater Pittsburgh. Health, Medicare, ACA, and group specialists — PA DOI verified.',
  },
  {
    slug: 'las-vegas',
    stateSlug: 'nevada',
    stateCode: 'NV',
    stateName: 'Nevada',
    msaName: 'Las Vegas-Henderson-Paradise',
    shortName: 'Las Vegas',
    population: 2_300_000,
    enrollmentHighlight: 'Hospitality workforce and retiree Medicare growth',
    localDescriptor: 'hospitality workers, retirees, and California overflow relocations',
    priority: 27,
    zipCodes: ['89101', '89117', '89148', '89012', '89145'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Las Vegas Valley across Clark County combines hospitality-worker ACA demand with retiree Medicare growth, California relocation health transitions, and bilingual enrollment in a rapidly expanding desert metro spanning Las Vegas, Henderson, and Summerlin.',
    healthNeeds: [
      'Hospitality worker ACA',
      'Retiree Medicare Advantage',
      'California relocation coverage',
      'Bilingual Medicare enrollment',
      'Summerlin/Henderson Medigap',
      'Small-business group health',
    ],
    metaTitle: 'Insurance Agents in Las Vegas Metro (2026) | Clark County',
    metaDescription:
      'Compare 12 verified independent insurance agents in Las Vegas-Henderson-Paradise. Health, Medicare, ACA, and group specialists — NV DOI verified.',
  },
  {
    slug: 'austin',
    stateSlug: 'texas',
    stateCode: 'TX',
    stateName: 'Texas',
    msaName: 'Austin-Round Rock-Georgetown',
    shortName: 'Austin',
    population: 2_400_000,
    enrollmentHighlight: 'Tech relocation capital of Texas',
    localDescriptor: 'tech transplants, startup culture, and Hill Country growth',
    priority: 28,
    zipCodes: ['78701', '78759', '78664', '78626', '78735'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Austin Metro across Travis, Williamson, Hays, and Bastrop counties serves constant health coverage transitions for relocating tech professionals, startup contractors, and Hill Country suburban Medicare growth in one of Texas\'s fastest-growing markets.',
    healthNeeds: [
      'Tech relocation ACA',
      'Startup contractor health plans',
      'Williamson County suburban enrollment',
      'Medicare in Travis County',
      'Small-business group benefits',
      'Bilingual marketplace support',
    ],
    metaTitle: 'Insurance Agents in Austin Metro (2026) | Travis & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Austin-Round Rock-Georgetown. Health, Medicare, ACA, and group specialists — TX DOI verified.',
  },
  {
    slug: 'cincinnati',
    stateSlug: 'ohio',
    stateCode: 'OH',
    stateName: 'Ohio',
    msaName: 'Cincinnati',
    shortName: 'Cincinnati',
    population: 2_200_000,
    enrollmentHighlight: 'Tri-state OH/KY/IN marketplace corridor',
    localDescriptor: 'tri-state commuters, P&G corridor, and Ohio River communities',
    priority: 29,
    zipCodes: ['45202', '45241', '45040', '41011', '45230'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Greater Cincinnati across Hamilton, Butler, Clermont, and Warren counties navigates tri-state OH/KY/IN marketplace enrollment, P&G corridor corporate benefits, UC Health retiree Medicare, and Ohio River community health plan comparisons.',
    healthNeeds: [
      'Tri-state ACA enrollment',
      'P&G corridor group benefits',
      'UC Health network alignments',
      'Medicare in Hamilton County',
      'Northern Kentucky commuter plans',
      'Corporate retiree transitions',
    ],
    metaTitle: 'Insurance Agents in Cincinnati Metro (2026) | Hamilton & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Greater Cincinnati. Health, Medicare, ACA, and group specialists — OH DOI verified.',
  },
  {
    slug: 'kansas-city',
    stateSlug: 'missouri',
    stateCode: 'MO',
    stateName: 'Missouri',
    msaName: 'Kansas City',
    shortName: 'Kansas City',
    population: 2_200_000,
    enrollmentHighlight: 'Bi-state MO/KS enrollment and logistics corridor',
    localDescriptor: 'bi-state families, logistics hub, and Midwest relocations',
    priority: 30,
    zipCodes: ['64106', '64108', '66202', '64068', '64157'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Kansas City Metro across Jackson, Clay, and Platte counties in Missouri plus Johnson and Wyandotte in Kansas demands agents who understand bi-state marketplace enrollment, logistics-worker ACA demand, and bilingual Medicare expertise in a split-state metro.',
    healthNeeds: [
      'Bi-state MO/KS ACA',
      'Johnson County KS enrollment',
      'Logistics worker health plans',
      'Medicare in Jackson County',
      'Bilingual Medicare enrollment',
      'Cross-border provider networks',
    ],
    metaTitle: 'Insurance Agents in Kansas City Metro (2026) | Jackson & Johnson',
    metaDescription:
      'Compare 12 verified independent insurance agents in Kansas City MO/KS. Health, Medicare, ACA, and group specialists — MO DCI verified.',
  },
  {
    slug: 'hartford',
    stateSlug: 'connecticut',
    stateCode: 'CT',
    stateName: 'Connecticut',
    msaName: 'Hartford-East Hartford-Middletown',
    shortName: 'Hartford',
    population: 1_200_000,
    enrollmentHighlight: 'Insurance capital of the world — industry employment hub',
    localDescriptor: 'insurance industry professionals and Connecticut suburbs',
    priority: 31,
    zipCodes: ['06103', '06107', '06119', '06457', '06033'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Hartford Metro across Hartford, Tolland, Middlesex, and New London counties combines Access Health CT enrollment with deep insurance-industry employment expertise, capital-region group benefits, and suburban Medicare demand in the insurance capital of the world.',
    healthNeeds: [
      'Access Health CT ACA',
      'Insurance industry group plans',
      'Capital region Medicare',
      'West Hartford suburban enrollment',
      'Employer benefits administration',
      'Farmington Valley Medigap',
    ],
    metaTitle: 'Insurance Agents in Hartford Metro (2026) | Hartford County & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Hartford-East Hartford-Middletown. Health, Medicare, ACA, and group specialists — CT DOI verified.',
  },
  {
    slug: 'des-moines',
    stateSlug: 'iowa',
    stateCode: 'IA',
    stateName: 'Iowa',
    msaName: 'Des Moines-West Des Moines',
    shortName: 'Des Moines',
    population: 700_000,
    enrollmentHighlight: 'Insurance industry HQ concentration',
    localDescriptor: 'insurance industry workers and Iowa farm communities',
    priority: 32,
    zipCodes: ['50309', '50266', '50021', '50310', '50009'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Des Moines Metro across Polk, Dallas, Warren, and Madison counties hosts major insurer headquarters creating deep agent expertise in Iowa marketplace enrollment, group benefit administration, and growing suburban Medicare demand in Iowa\'s capital city.',
    healthNeeds: [
      'Iowa marketplace ACA',
      'Insurer HQ group administration',
      'Medicare in Polk County',
      'West Des Moines suburban enrollment',
      'Ankeny growth corridor plans',
      'Farm family health transitions',
    ],
    metaTitle: 'Insurance Agents in Des Moines Metro (2026) | Polk & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Des Moines-West Des Moines. Health, Medicare, ACA, and group specialists — IA Insurance Division verified.',
  },
  {
    slug: 'jacksonville',
    stateSlug: 'florida',
    stateCode: 'FL',
    stateName: 'Florida',
    msaName: 'Jacksonville',
    shortName: 'Jacksonville',
    population: 1_600_000,
    enrollmentHighlight: 'Military, logistics workforce ACA, and First Coast Medicare growth',
    localDescriptor: 'military bases, port logistics, Duval families, and North Florida retirees',
    priority: 33,
    zipCodes: ['32202', '32225', '32003', '32259', '32082'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Jacksonville combines military and TRICARE navigation, logistics-worker ACA enrollment, and growing Medicare demand across Duval County. Independent brokers with exceptional review volume — including 2,000+ Google ratings — shop 80+ carriers alongside dedicated Medicare agencies with BBB A+ accreditation serving St. Johns, Clay, and Nassau counties.',
    healthNeeds: [
      'Medicare Advantage (Duval networks)',
      'Military/TRICARE transitions',
      'Logistics & port worker ACA',
      'Group health (St. Johns/Clay businesses)',
      'Hurricane property + health bundling',
    ],
    metaTitle: 'Insurance Agents in Jacksonville (2026) | Duval, St. Johns & Clay',
    metaDescription:
      'Compare 12 verified independent insurance agents in Jacksonville metro. Medicare, ACA, and multi-line specialists across Duval, St. Johns, Clay, and Nassau — DFS verified.',
  },
  { slug: 'fort-lauderdale', stateSlug: 'florida', stateCode: 'FL', stateName: 'Florida', msaName: 'Fort Lauderdale', shortName: 'Fort Lauderdale', population: 1_900_000, enrollmentHighlight: 'Broward Medicare density and cruise-industry workers', localDescriptor: 'Broward retirees, cruise workers, and yacht-industry professionals', priority: 34, zipCodes: ['33301', '33308', '33004'], healthInsuranceDensity: 'very-high', marketSnapshot: 'Broward County agents specialize in Medicare Advantage, cruise-industry ACA gaps, and coastal property/health bundles.', healthNeeds: ['Medicare Advantage', 'Maritime worker ACA', 'Coastal property'], metaTitle: 'Insurance Agents in Fort Lauderdale (2026)', metaDescription: 'Medicare and health agents in Broward County.' },
  {
    slug: 'san-jose',
    stateSlug: 'california',
    stateCode: 'CA',
    stateName: 'California',
    msaName: 'San Jose-Sunnyvale-Santa Clara',
    shortName: 'San Jose',
    population: 1_900_000,
    enrollmentHighlight: 'Silicon Valley tech equity and high-income Covered California cliffs',
    localDescriptor: 'Silicon Valley engineers, startup founders, and tech executives',
    priority: 35,
    zipCodes: ['95110', '95014', '94085', '95124', '95118'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'San Jose-Sunnyvale-Santa Clara across Santa Clara County serves constant health coverage transitions for tech professionals navigating RSU vesting, startup benefits gaps, and Covered California subsidy cliffs for high earners — alongside growing Medicare demand in Cupertino, Campbell, and Los Gatos corridors.',
    healthNeeds: [
      'Covered California high-income ACA',
      'Tech equity vesting transitions',
      'Startup contractor health plans',
      'Santa Clara County Medicare',
      'Small-business group benefits',
      'Bilingual Medicare (EN/ES)',
    ],
    metaTitle: 'Insurance Agents in San Jose / Silicon Valley (2026) | Santa Clara County',
    metaDescription:
      'Compare 12 verified independent insurance agents in San Jose-Sunnyvale-Santa Clara. Health, Medicare, ACA, and group specialists — CA DOI verified.',
  },
  {
    slug: 'nashville',
    stateSlug: 'tennessee',
    stateCode: 'TN',
    stateName: 'Tennessee',
    msaName: 'Nashville-Davidson-Murfreesboro',
    shortName: 'Nashville',
    population: 2_000_000,
    enrollmentHighlight: 'Global healthcare industry HQ — HCA-driven employer-sponsored volume and competitive individual market',
    localDescriptor: 'healthcare executives, Williamson suburban families, and Murfreesboro growth corridor',
    priority: 36,
    zipCodes: ['37201', '37027', '37129', '37064', '37203'],
    healthInsuranceDensity: 'very-high',
    marketSnapshot:
      'Nashville Metro (Rating Area 4) across Davidson, Williamson, and Rutherford is the epicenter of Tennessee corporate health insurance volume. HCA Healthcare and healthcare industry HQ concentration drive premium-heavy employer-sponsored plans, while the individual market attracts Oscar Health, Cigna, and UnitedHealthcare in a highly competitive marketplace.',
    healthNeeds: [
      'HCA and healthcare HQ group benefits',
      'Oscar/Cigna/UHC individual ACA',
      'Williamson suburban employer plans',
      'Rutherford small-group health',
      'Nashville Medicare Advantage',
      'Corporate relocation coverage',
    ],
    metaTitle: 'Insurance Agents in Nashville (2026) | Davidson, Williamson & Rutherford',
    metaDescription:
      'Compare 12 verified independent insurance agents in Nashville metro. Employer group, ACA, and Medicare specialists across Davidson, Williamson, and Rutherford — TN DOI verified.',
  },
  {
    slug: 'chattanooga',
    stateSlug: 'tennessee',
    stateCode: 'TN',
    stateName: 'Tennessee',
    msaName: 'Chattanooga',
    shortName: 'Chattanooga',
    population: 580_000,
    enrollmentHighlight: 'BCBS TN headquarters market with Alliant Health Plans Platinum-tier ACA competition',
    localDescriptor: 'Hamilton County families, manufacturing corridor, and diverse marketplace shoppers',
    priority: 36,
    zipCodes: ['37402', '37421', '37450', '37343'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Chattanooga (Rating Area 3) is uniquely competitive as headquarters of BlueCross BlueShield of Tennessee, yet offers diverse carrier choices including regional Alliant Health Plans — the only Tennessee marketplace carrier offering Platinum-tier plans.',
    healthNeeds: [
      'BCBS TN marketplace & group plans',
      'Alliant Health Platinum-tier ACA',
      'Hamilton County employer benefits',
      'Chattanooga Medicare comparisons',
      'Downtown corporate health',
      'Regional carrier navigation',
    ],
    metaTitle: 'Insurance Agents in Chattanooga (2026) | Hamilton County',
    metaDescription:
      'Compare 12 verified independent insurance agents in Chattanooga. BCBS TN and Alliant Health marketplace, Medicare, and group specialists — TN DOI verified.',
  },
  {
    slug: 'knoxville',
    stateSlug: 'tennessee',
    stateCode: 'TN',
    stateName: 'Tennessee',
    msaName: 'Knoxville',
    shortName: 'Knoxville & Tri-Cities',
    population: 1_100_000,
    enrollmentHighlight: 'Covenant Health and UT Medical Center networks with BCBS TN dominance',
    localDescriptor: 'Knoxville retirees, Blount County suburbs, and Tri-Cities regional employers',
    priority: 36,
    zipCodes: ['37912', '37934', '37601', '37660', '37865'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Knoxville & Tri-Cities (Rating Areas 1 & 2) across Knox, Blount, and Washington counties relies on localized provider networks including Covenant Health and UT Medical Center. Carrier competition narrows slightly but remains strong between national players and dominant BlueCross BlueShield of Tennessee.',
    healthNeeds: [
      'Covenant Health network plans',
      'UT Medical Center alignments',
      'BCBS TN employer group',
      'Knoxville Medicare Advantage',
      'Tri-Cities regional benefits',
      'Blount County ACA enrollment',
    ],
    metaTitle: 'Insurance Agents in Knoxville & Tri-Cities (2026) | Knox, Blount & Washington',
    metaDescription:
      'Compare 12 verified independent insurance agents in Knoxville and Tri-Cities. Covenant/UT network health, Medicare, and group specialists — TN DOI verified.',
  },
  {
    slug: 'raleigh',
    stateSlug: 'north-carolina',
    stateCode: 'NC',
    stateName: 'North Carolina',
    msaName: 'Raleigh-Cary-Durham',
    shortName: 'Research Triangle',
    population: 2_100_000,
    enrollmentHighlight: 'Highly educated workforce — BCBSNC and UnitedHealthcare dominate employer-sponsored market',
    localDescriptor: 'RTP tech, biotech, Duke/UNC university corridors, and Cary suburban families',
    priority: 37,
    zipCodes: ['27601', '27511', '27513', '27701', '27514'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'The Research Triangle across Wake, Durham, and Orange counties features a massive, highly educated tech, biotech, and university workforce. Commercial and employer-sponsored insurance is extremely competitive, dominated by Blue Cross Blue Shield of North Carolina and UnitedHealthcare, with growing individual ACA and Medicare demand in Raleigh, Durham, and Chapel Hill.',
    healthNeeds: [
      'BCBSNC employer group plans',
      'UnitedHealthcare corporate benefits',
      'Biotech/RTP employee benefits',
      'University-affiliated health plans',
      'NC marketplace ACA (individual)',
      'Durham/Chapel Hill Medicare',
    ],
    metaTitle: 'Insurance Agents in Research Triangle (2026) | Wake, Durham & Orange',
    metaDescription:
      'Compare 12 verified independent insurance agents in Raleigh-Cary-Durham. Group health, ACA, Medicare specialists for tech, biotech, and university markets — NC DOI verified.',
  },
  {
    slug: 'greensboro',
    stateSlug: 'north-carolina',
    stateCode: 'NC',
    stateName: 'North Carolina',
    msaName: 'Greensboro-High Point-Winston-Salem',
    shortName: 'The Triad',
    population: 1_700_000,
    enrollmentHighlight: 'High-volume tiered network market — Novant Health & Atrium Wake Forest Baptist',
    localDescriptor: 'Greensboro-Winston-Salem manufacturing, furniture corridor, and regional health systems',
    priority: 38,
    zipCodes: ['27401', '27101', '27260', '27012', '27407'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'The Triad is a dense regional hub where Novant Health and Atrium Health Wake Forest Baptist drive custom tiered network plans. Carriers structure BCBSNC Blue Home and Blue Local products to lure price-sensitive employers and individuals in Greensboro, Winston-Salem, and High Point across Guilford and Forsyth counties.',
    healthNeeds: [
      'BCBSNC Blue Home (Novant) tiered plans',
      'Blue Local (Atrium WFB) networks',
      'Small group employer health (2–50)',
      'Triad Medicare comparisons',
      'High Point manufacturing benefits',
      'Winston-Salem regional group plans',
    ],
    metaTitle: 'Insurance Agents in The Triad (2026) | Greensboro, Winston-Salem & High Point',
    metaDescription:
      'Compare 12 verified independent insurance agents in Greensboro-High Point-Winston-Salem. Tiered network health, Medicare, and group specialists — NC DOI verified.',
  },
  {
    slug: 'columbus',
    stateSlug: 'ohio',
    stateCode: 'OH',
    stateName: 'Ohio',
    msaName: 'Columbus',
    shortName: 'Columbus',
    population: 2_100_000,
    enrollmentHighlight: 'State capital and insurance industry employment hub',
    localDescriptor: 'state government, insurance industry, and Ohio State corridor',
    priority: 38,
    zipCodes: ['43215', '43017', '43221', '43230', '43085'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Columbus Metro across Franklin, Delaware, Fairfield, and Licking counties serves state employee benefit transitions, Ohio State University corridor enrollment, insurance-industry employment expertise, and growing suburban family and Medicare demand in Dublin, Westerville, and Upper Arlington.',
    healthNeeds: [
      'State employee benefit transitions',
      'Ohio marketplace ACA enrollment',
      'Ohio State corridor group plans',
      'Franklin County Medicare',
      'Suburban family health plans',
      'Insurance industry retiree Medicare',
    ],
    metaTitle: 'Insurance Agents in Columbus Metro (2026) | Franklin & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Columbus metro. Health, Medicare, ACA, and group specialists — OH DOI verified.',
  },
  {
    slug: 'indianapolis',
    stateSlug: 'indiana',
    stateCode: 'IN',
    stateName: 'Indiana',
    msaName: 'Indianapolis-Carmel-Anderson',
    shortName: 'Indianapolis',
    population: 2_100_000,
    enrollmentHighlight: 'Healthcare and logistics corridor with growing capital-city suburbs',
    localDescriptor: 'healthcare, logistics, and Indy 500 corridor families',
    priority: 39,
    zipCodes: ['46204', '46032', '46250', '46256', '46123'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Indianapolis-Carmel-Anderson across Marion, Hamilton, Hendricks, Johnson, and Hancock counties combines healthcare employment benefits expertise with Indiana marketplace enrollment, logistics-worker ACA demand, and fast-growing suburban Medicare in Carmel, Fishers, and Avon corridors.',
    healthNeeds: [
      'Healthcare system employee benefits',
      'Indiana marketplace ACA enrollment',
      'Carmel/Fishers suburban group plans',
      'Marion County Medicare',
      'Logistics corridor health plans',
      'IU Health network alignments',
    ],
    metaTitle: 'Insurance Agents in Indianapolis Metro (2026) | Marion & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Indianapolis-Carmel-Anderson. Health, Medicare, ACA, and group specialists — IN DOI verified.',
  },
  {
    slug: 'salt-lake-city',
    stateSlug: 'utah',
    stateCode: 'UT',
    stateName: 'Utah',
    msaName: 'Salt Lake City-Provo-Orem',
    shortName: 'Salt Lake',
    population: 1_300_000,
    enrollmentHighlight: 'Young family growth and Silicon Slopes tech corridor expansion',
    localDescriptor: 'young families, LDS communities, and Silicon Slopes tech',
    priority: 40,
    zipCodes: ['84101', '84043', '84604', '84117', '84011'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Salt Lake City-Provo-Orem across Salt Lake, Davis, Weber, and Utah counties serves young-family health plan demand, Silicon Slopes tech relocation coverage, Utah marketplace enrollment, and growing Medicare demand in the Wasatch Front suburban corridors.',
    healthNeeds: [
      'Utah marketplace ACA enrollment',
      'Silicon Slopes tech relocation',
      'Young family health plans',
      'Salt Lake County Medicare',
      'Small-business group benefits',
      'Intermountain Healthcare network alignments',
    ],
    metaTitle: 'Insurance Agents in Salt Lake City Metro (2026) | Salt Lake & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Salt Lake-Provo-Orem. Health, Medicare, ACA, and group specialists — UT DOI verified.',
  },
  {
    slug: 'milwaukee',
    stateSlug: 'wisconsin',
    stateCode: 'WI',
    stateName: 'Wisconsin',
    msaName: 'Milwaukee-Waukesha',
    shortName: 'Milwaukee',
    population: 1_600_000,
    enrollmentHighlight: 'Manufacturing benefits and Wisconsin marketplace enrollment',
    localDescriptor: 'manufacturing workers, brewery corridor, and lakefront communities',
    priority: 41,
    zipCodes: ['53202', '53186', '53005', '53208', '53220'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Milwaukee-Waukesha across Milwaukee, Waukesha, Ozaukee, and Washington counties navigates manufacturing benefit transitions, Wisconsin marketplace enrollment, brewery-corridor employer plans, and lakefront community Medicare growth in Brookfield, Wauwatosa, and Menomonee Falls suburbs.',
    healthNeeds: [
      'Manufacturing benefit transitions',
      'Wisconsin marketplace ACA enrollment',
      'Milwaukee County Medicare',
      'Aurora/Froedtert network alignments',
      'Small-business group benefits',
      'Waukesha suburban family plans',
    ],
    metaTitle: 'Insurance Agents in Milwaukee Metro (2026) | Milwaukee & Waukesha',
    metaDescription:
      'Compare 12 verified independent insurance agents in Milwaukee-Waukesha. Health, Medicare, ACA, and group specialists — WI OCI verified.',
  },
  {
    slug: 'oklahoma-city',
    stateSlug: 'oklahoma',
    stateCode: 'OK',
    stateName: 'Oklahoma',
    msaName: 'Oklahoma City',
    shortName: 'OKC',
    population: 1_400_000,
    enrollmentHighlight: 'Energy sector benefits and Tinker AFB military family enrollment',
    localDescriptor: 'energy workers, military, and tornado-alley homeowners',
    priority: 42,
    zipCodes: ['73102', '73120', '73034', '73159', '73142'],
    healthInsuranceDensity: 'moderate',
    marketSnapshot:
      'Oklahoma City Metro across Oklahoma, Canadian, and Cleveland counties serves energy sector benefit transitions, Tinker AFB military family health enrollment, Oklahoma marketplace ACA demand, and tornado-alley property/health bundling in Moore, Edmond, and Norman suburbs.',
    healthNeeds: [
      'Energy sector benefit transitions',
      'Tinker AFB military family health',
      'Oklahoma marketplace ACA enrollment',
      'Oklahoma County Medicare',
      'Tornado property/health bundling',
      'OU Health network alignments',
    ],
    metaTitle: 'Insurance Agents in Oklahoma City Metro (2026) | Oklahoma & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in OKC metro. Health, Medicare, ACA, and group specialists — OK DOI verified.',
  },
  {
    slug: 'louisville',
    stateSlug: 'kentucky',
    stateCode: 'KY',
    stateName: 'Kentucky',
    msaName: 'Louisville-Jefferson County',
    shortName: 'Louisville',
    population: 1_300_000,
    enrollmentHighlight: 'Healthcare and UPS logistics corridor on the Ohio River',
    localDescriptor: 'healthcare, bourbon industry, and Ohio River communities',
    priority: 43,
    zipCodes: ['40202', '40241', '40059', '40223', '40291'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Louisville-Jefferson County across Jefferson, Oldham, Bullitt, and Shelby counties serves Norton Healthcare and Baptist Health employment corridors, UPS Worldport logistics benefits, Kentucky marketplace enrollment, and bi-state Southern Indiana commuter health transitions along the Ohio River.',
    healthNeeds: [
      'Healthcare system employee benefits',
      'Kentucky marketplace ACA enrollment',
      'UPS/logistics corridor group plans',
      'Jefferson County Medicare',
      'Southern Indiana bi-state commuters',
      'Bourbon-industry small-group health',
    ],
    metaTitle: 'Insurance Agents in Louisville Metro (2026) | Jefferson & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Louisville-Jefferson County. Health, Medicare, ACA, and group specialists — KY DOI verified.',
  },
  {
    slug: 'memphis',
    stateSlug: 'tennessee',
    stateCode: 'TN',
    stateName: 'Tennessee',
    msaName: 'Memphis',
    shortName: 'Memphis',
    population: 1_300_000,
    enrollmentHighlight: 'FedEx logistics corridor driving massive employer-sponsored volume and narrow-network corporate plans',
    localDescriptor: 'logistics workers, Shelby County families, and Mississippi River bi-state corridor',
    priority: 44,
    zipCodes: ['38103', '38112', '38117', '38017', '38671'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Memphis Metro (Rating Area 6) across Shelby County represents massive covered lives driven by logistics giants like FedEx. Active battleground for regional individual plans and narrow-network corporate offerings alongside Oscar, Cigna, and UnitedHealthcare competition.',
    healthNeeds: [
      'FedEx-scale employer benefits',
      'Logistics corridor group health',
      'Shelby County ACA marketplace',
      'Narrow-network corporate plans',
      'Memphis Medicare Advantage',
      'Bi-state enrollment support',
    ],
    metaTitle: 'Insurance Agents in Memphis (2026) | Shelby County',
    metaDescription:
      'Compare 12 verified independent insurance agents in Memphis metro. Logistics employer benefits, ACA, and Medicare specialists — TN DOI verified.',
  },
  {
    slug: 'richmond',
    stateSlug: 'virginia',
    stateCode: 'VA',
    stateName: 'Virginia',
    msaName: 'Richmond',
    shortName: 'Richmond',
    population: 1_300_000,
    enrollmentHighlight: 'State capital employee benefits and RVA tech-corridor growth',
    localDescriptor: 'state government, university, and RVA tech growth',
    priority: 45,
    zipCodes: ['23219', '23233', '23113', '23238', '23112'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Richmond Metro across Henrico, Chesterfield, Hanover, and Goochland counties combines state employee benefit expertise with Virginia marketplace enrollment, VCU Health and Bon Secours network alignments, and fast-growing suburban Medicare in Short Pump, Midlothian, and Mechanicsville corridors.',
    healthNeeds: [
      'State employee benefit transitions',
      'Virginia marketplace ACA enrollment',
      'VCU/Bon Secours network alignments',
      'Henrico/Chesterfield Medicare',
      'RVA tech-corridor group benefits',
      'University-affiliated health plans',
    ],
    metaTitle: 'Insurance Agents in Richmond Metro (2026) | Henrico & Chesterfield',
    metaDescription:
      'Compare 12 verified independent insurance agents in Richmond metro. Health, Medicare, ACA, and group specialists — VA Bureau of Insurance verified.',
  },
  {
    slug: 'birmingham',
    stateSlug: 'alabama',
    stateCode: 'AL',
    stateName: 'Alabama',
    msaName: 'Birmingham-Hoover',
    shortName: 'Birmingham',
    population: 1_100_000,
    enrollmentHighlight: 'UAB healthcare anchor and Alabama marketplace enrollment',
    localDescriptor: 'healthcare workers, steel legacy, and Alabama families',
    priority: 46,
    zipCodes: ['35203', '35242', '35216', '35215', '35211'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Birmingham-Hoover across Jefferson, Shelby, St. Clair, and Blount counties serves UAB Medicine and St. Vincent\'s healthcare employment corridors, Alabama marketplace enrollment, steel-legacy retiree Medicare, and fast-growing Hoover–Vestavia Hills suburban family demand along the I-459 growth corridor.',
    healthNeeds: [
      'UAB healthcare employee benefits',
      'Alabama marketplace ACA enrollment',
      'Jefferson County Medicare',
      'Hoover/Vestavia suburban group plans',
      'Steel-legacy retiree transitions',
      'St. Vincent\'s network alignments',
    ],
    metaTitle: 'Insurance Agents in Birmingham Metro (2026) | Jefferson & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Birmingham-Hoover. Health, Medicare, ACA, and group specialists — AL DOI verified.',
  },
  {
    slug: 'buffalo',
    stateSlug: 'new-york',
    stateCode: 'NY',
    stateName: 'New York',
    msaName: 'Buffalo-Cheektowaga',
    shortName: 'Buffalo',
    population: 1_100_000,
    enrollmentHighlight: 'NY State of Health and Buffalo Niagara medical corridor employment',
    localDescriptor: 'Buffalo Niagara families, healthcare, and Canadian border corridor',
    priority: 47,
    zipCodes: ['14202', '14221', '14086', '14217', '14150'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Buffalo-Cheektowaga across Erie, Niagara, Cattaraugus, and Chautauqua counties navigates NY State of Health enrollment, Kaleida Health and Catholic Health employment corridors, Canadian border commuter coverage, and winter property/health bundling in Williamsville, Amherst, and Lancaster suburbs.',
    healthNeeds: [
      'NY State of Health ACA enrollment',
      'Kaleida/Catholic Health network alignments',
      'Erie County Medicare',
      'Canadian border commuter plans',
      'Buffalo Niagara medical corridor benefits',
      'Winter property/health bundling',
    ],
    metaTitle: 'Insurance Agents in Buffalo Metro (2026) | Erie & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Buffalo-Cheektowaga. Health, Medicare, ACA, and group specialists — NY DFS verified.',
  },
  {
    slug: 'providence',
    stateSlug: 'rhode-island',
    stateCode: 'RI',
    stateName: 'Rhode Island',
    msaName: 'Providence-Warwick',
    shortName: 'Providence',
    population: 1_600_000,
    enrollmentHighlight: 'HealthSource RI and Boston commuter corridor',
    localDescriptor: 'Boston commuters, coastal communities, and university populations',
    priority: 48,
    zipCodes: ['02903', '02886', '02809', '02915', '02910'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Providence-Warwick across Providence, Kent, and Bristol counties serves HealthSource RI marketplace enrollment, Brown University and Rhode Island Hospital employment corridors, Boston commuter benefit transitions, and coastal Warwick–Cranston suburban Medicare growth in Rhode Island\'s capital region.',
    healthNeeds: [
      'HealthSource RI ACA enrollment',
      'Brown University corridor benefits',
      'Boston commuter FEHB transitions',
      'Providence County Medicare',
      'Coastal Warwick/Cranston group plans',
      'Lifespan hospital network alignments',
    ],
    metaTitle: 'Insurance Agents in Providence Metro (2026) | Providence, Kent & Bristol',
    metaDescription:
      'Compare 12 verified independent insurance agents in Providence-Warwick. Health, Medicare, ACA, and group specialists — RI DBR verified.',
  },
  {
    slug: 'new-orleans',
    stateSlug: 'louisiana',
    stateCode: 'LA',
    stateName: 'Louisiana',
    msaName: 'New Orleans-Metairie',
    shortName: 'New Orleans',
    population: 1_200_000,
    enrollmentHighlight: 'Louisiana marketplace enrollment and tourism-worker ACA gaps',
    localDescriptor: 'tourism workers, port logistics, and hurricane-zone homeowners',
    priority: 49,
    zipCodes: ['70112', '70002', '70124', '70115', '70433'],
    healthInsuranceDensity: 'moderate',
    marketSnapshot:
      'New Orleans-Metairie across Orleans, Jefferson, St. Tammany, and Plaquemines parishes navigates Louisiana marketplace enrollment, Ochsner and LCMC Health employment corridors, tourism-hospitality seasonal coverage gaps, and hurricane-zone property/health bundling in Metairie, Kenner, and North Shore suburbs.',
    healthNeeds: [
      'Louisiana marketplace ACA enrollment',
      'Ochsner/LCMC network alignments',
      'Orleans Parish Medicare',
      'Tourism worker seasonal coverage',
      'Hurricane property/health bundling',
      'North Shore suburban group plans',
    ],
    metaTitle: 'Insurance Agents in New Orleans Metro (2026) | Orleans & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in New Orleans-Metairie. Health, Medicare, ACA, and group specialists — LA DOI verified.',
  },
  {
    slug: 'honolulu',
    stateSlug: 'hawaii',
    stateCode: 'HI',
    stateName: 'Hawaii',
    msaName: 'Urban Honolulu',
    shortName: 'Honolulu',
    population: 1_000_000,
    enrollmentHighlight: 'Hawaii marketplace and military/TRICARE coordination',
    localDescriptor: 'military families, tourism workers, and island communities',
    priority: 50,
    zipCodes: ['96813', '96814', '96815', '96816', '96789'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Urban Honolulu across Oahu serves Hawaii\'s unique state marketplace enrollment, Tripler Army Medical Center and Pearl Harbor military health coordination, Waikiki tourism-worker ACA transitions, and HMSA/Kaiser island network alignments from Kailua to Kapolei.',
    healthNeeds: [
      'Hawaii marketplace ACA enrollment',
      'Military/TRICARE coordination',
      'Honolulu County Medicare',
      'HMSA/Kaiser network alignments',
      'Tourism worker seasonal coverage',
      'Island-wide employer group plans',
    ],
    metaTitle: 'Insurance Agents in Honolulu Metro (2026) | Oahu & Honolulu County',
    metaDescription:
      'Compare 12 verified independent insurance agents in Urban Honolulu. Health, Medicare, ACA, and group specialists — HI DCCA verified.',
  },
  {
    slug: 'albuquerque',
    stateSlug: 'new-mexico',
    stateCode: 'NM',
    stateName: 'New Mexico',
    msaName: 'Albuquerque',
    shortName: 'Albuquerque',
    population: 900_000,
    enrollmentHighlight: 'beWellnm marketplace and Sandia labs corridor benefits',
    localDescriptor: 'Native communities, Sandia labs corridor, and Southwest families',
    priority: 51,
    zipCodes: ['87102', '87110', '87114', '87120', '87048'],
    healthInsuranceDensity: 'moderate',
    marketSnapshot:
      'Albuquerque across Bernalillo, Sandoval, Valencia, and Torrance counties serves beWellnm marketplace enrollees, Sandia National Laboratories and Kirtland AFB employment corridors, diverse Native community health needs, and fast-growing Rio Rancho suburban Medicare demand along the I-25 growth corridor.',
    healthNeeds: [
      'beWellnm ACA enrollment',
      'Sandia/Kirtland federal benefits',
      'Bernalillo County Medicare',
      'Native community health navigation',
      'Rio Rancho suburban group plans',
      'Bilingual enrollment support',
    ],
    metaTitle: 'Insurance Agents in Albuquerque Metro (2026) | Bernalillo & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Albuquerque. Health, Medicare, ACA, and group specialists — NM OSI verified.',
  },
  {
    slug: 'tucson',
    stateSlug: 'arizona',
    stateCode: 'AZ',
    stateName: 'Arizona',
    msaName: 'Tucson',
    shortName: 'Tucson',
    population: 1_000_000,
    enrollmentHighlight: 'Retiree Medicare demand and university corridor benefits',
    localDescriptor: 'retirees, university, and Davis-Monthan military corridor',
    priority: 52,
    zipCodes: ['85701', '85710', '85718', '85747', '85704'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Tucson across Pima County combines snowbird retiree Medicare demand with University of Arizona employment corridors, Davis-Monthan AFB military health navigation, Banner Health network alignments, and bilingual enrollment support in Catalina Foothills and Oro Valley suburbs.',
    healthNeeds: [
      'Retiree Medicare enrollment',
      'University of Arizona benefits',
      'Davis-Monthan military health',
      'Pima County ACA marketplace',
      'Banner Health network alignments',
      'Bilingual EN/ES enrollment',
    ],
    metaTitle: 'Insurance Agents in Tucson Metro (2026) | Pima County',
    metaDescription:
      'Compare 12 verified independent insurance agents in Tucson. Health, Medicare, ACA, and group specialists — AZ DIFI verified.',
  },
  {
    slug: 'fresno',
    stateSlug: 'california',
    stateCode: 'CA',
    stateName: 'California',
    msaName: 'Fresno',
    shortName: 'Fresno',
    population: 1_000_000,
    enrollmentHighlight: 'Covered California and agricultural worker Medi-Cal transitions',
    localDescriptor: 'agricultural workers, Central Valley families, and Medi-Cal transitions',
    priority: 53,
    zipCodes: ['93721', '93650', '93710', '93720', '93704'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Fresno and the Central Valley across Fresno, Madera, Kings, and Tulare counties specialize in Covered California enrollment, agricultural worker Medi-Cal transitions, Community Medical Centers employment corridors, and Clovis suburban family health demand in California\'s agricultural heartland.',
    healthNeeds: [
      'Covered California ACA enrollment',
      'Agricultural worker health coverage',
      'Medi-Cal transition support',
      'Fresno County Medicare',
      'Clovis suburban group plans',
      'Central Valley property/health bundling',
    ],
    metaTitle: 'Insurance Agents in Fresno Metro (2026) | Fresno & Central Valley',
    metaDescription:
      'Compare 12 verified independent insurance agents in Fresno and the Central Valley. Health, Medicare, ACA, and group specialists — CA DOI verified.',
  },
  {
    slug: 'omaha',
    stateSlug: 'nebraska',
    stateCode: 'NE',
    stateName: 'Nebraska',
    msaName: 'Omaha-Council Bluffs',
    shortName: 'Omaha',
    population: 950_000,
    enrollmentHighlight: 'Nebraska marketplace and insurance-industry employment expertise',
    localDescriptor: 'insurance industry, financial services, and bi-state families',
    priority: 54,
    zipCodes: ['68102', '68130', '68154', '68116', '51503'],
    healthInsuranceDensity: 'high',
    marketSnapshot:
      'Omaha-Council Bluffs across Douglas, Sarpy, Washington, and Cass counties leverages deep insurance-industry expertise for Nebraska marketplace enrollment, CHI Health and Methodist employment corridors, Mutual of Omaha corridor retiree transitions, and bi-state Iowa-Nebraska benefit coordination in Papillion and Elkhorn suburbs.',
    healthNeeds: [
      'Nebraska marketplace ACA enrollment',
      'CHI Health/Methodist network alignments',
      'Douglas County Medicare',
      'Insurance industry group benefits',
      'Bi-state Council Bluffs enrollment',
      'Papillion/Elkhorn suburban plans',
    ],
    metaTitle: 'Insurance Agents in Omaha Metro (2026) | Douglas & Surrounding',
    metaDescription:
      'Compare 12 verified independent insurance agents in Omaha-Council Bluffs. Health, Medicare, ACA, and group specialists — NE DOI verified.',
  },
];

export function getHubBySlug(stateSlug: string, hubSlug: string): InsuranceHub | undefined {
  return INSURANCE_HUBS.find((h) => h.stateSlug === stateSlug && h.slug === hubSlug);
}

export function getHubsByState(stateSlug: string): InsuranceHub[] {
  return INSURANCE_HUBS.filter((h) => h.stateSlug === stateSlug);
}

export function getAllHubParams(): { state: string; slug: string }[] {
  return INSURANCE_HUBS.map((h) => ({ state: h.stateSlug, slug: h.slug }));
}

export function getAllStateSlugs(): string[] {
  return [...new Set(INSURANCE_HUBS.map((h) => h.stateSlug))];
}

export function getHubByZip(zip: string): InsuranceHub | undefined {
  const normalized = zip.trim().slice(0, 5);
  return INSURANCE_HUBS.find((h) => h.zipCodes.includes(normalized));
}

export function getTopHubs(limit = 15): InsuranceHub[] {
  return [...INSURANCE_HUBS].sort((a, b) => a.priority - b.priority).slice(0, limit);
}